### ISSUE TITLE
Fysetc F6 uart pins for TMC2208 v1.2

### ISSUE THREAD

**Issue by SimoneBnc** [KevinOConnor/klipper#1002]
Hi
I am trying to configure the above board. According to what I read I should assign a "uart_pin" for each driver, but accoring to the page https://wiki.fysetc.com/F6_V1.3/#pin-definition they have wired both tx/rx pins: so how should it be done on klipper?

**Comment by KevinOConnor** [comment]
Set the uart_pin to the rx pin and don't use the tx pin.  You can use both rx and tx pins if you really want to (see config/example-extra.cfg for the details), but there is no particular advantage to using a separate tx pin.

-Kevin

**Comment by SimoneBnc** [comment]
ok thanks
