### ISSUE TITLE
Lagrange or bicubic?

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#1006]
The interpolation algorithm to use. May be either "lagrange" or "bicubic"
Can someone explain the diference and the best one?

**Comment by rmcbc** [comment]
And bed_tilt or bed_mesh? Where can I get better results?

**Comment by KevinOConnor** [comment]
They are two different math formulas for estimating the position of the bed between points that have actually been measured.  I don't know which would be better.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it doesn't look like anyone has the answer to this question.

-Kevin
