### ISSUE TITLE
What is Development Environment?

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#1018]
@KevinOConnor can you please tell what is your development environment?

- For python I use PyCharm, what do you use that fits perfect in klipper code?
- For c/c++ normaly I use arduino but because this c/c++ is for diferent processors what IDE do you use?

**Comment by mcmatrix** [comment]
I'm using https://code.visualstudio.com/

**Comment by rmcbc** [comment]
@mcmatrix this is a good IDE, on windows to compile what you use for C/C++? Or simply use the raspberry compiler?

**Comment by mcmatrix** [comment]
@rmcbc Yep, simply using the raspberry compiler.

**Comment by KevinOConnor** [comment]
FWIW, I don't use an IDE.  I just use a regular editor (emacs).

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as I think the original question was answered.

-Kevin
