### ISSUE TITLE
mesh leveling problems after klipper upgrade

### ISSUE THREAD

**Issue by ifUpEth0** [KevinOConnor/klipper#1026]
I recently did a pull/upgrade of my klipper install. I am having odd issues now with Mesh leveling. It is easiest to see with several pieces being printed front to back of the machine. The skirting and first layer perimeter go down well. Most of the infill will go down well but will be just a touch too high (z) toward the front of the printer. The really strange part is that I will see this in each piece progressively each layer. For example 4 pieces in a straight line down the middle of the printer will all have thinned or raised front left infill  and (perimeters after the first layer). Given this pattern and that this printer was printing fine before hand I do not think this is any kind of mechanical leveling or flatness issue. The print bed is 1/4" thick jig plate.

[klippy.log](https://github.com/KevinOConnor/klipper/files/2703725/klippy.log)

![20181221_115238](https://user-images.githubusercontent.com/18585522/50357000-fdaff800-0519-11e9-974c-1a45920aeae9.jpg)

**Comment by ifUpEth0** [comment]
I started the same print job after doing a (BED_MESH_CLEAR) and a homing routine. 


![20181221_125300](https://user-images.githubusercontent.com/18585522/50358774-1c18f200-0520-11e9-929d-bd3c7c810c9e.jpg)

**Comment by Arksine** [comment]
This is possibly due to the new fade_target option which defaults to the average z position in the mesh.  Try setting fade_target: 0 in your printer.cfg to see if it behaves as you expect (this would mimic previous behavior).

**Comment by KevinOConnor** [comment]
It looks like this was resolved, so I'm going to close this issue.

-Kevin
