### ISSUE TITLE
Klipper to smart stepper using BUS I2C/SPI (no central controlboard)

### ISSUE THREAD

**Issue by FixFuture** [KevinOConnor/klipper#1033]
Hi!
I have been researching possibility of building 3d-printer without centralized control board (like duet wifi) so that
1) Rpi runs octoprint and klipper.
2) each device would connected via bus (i2c/spi/...) and bus would have power with it
3) steppers would be smart steppers (such as [uStepper](
http://www.ustepper.com/index/)) and would have mcu firmware running
4) each device could communicate back to Rpi via bus (steppers about buffer, temp, current, etc; bed about temp, etc). Octoprint plugin reads bus and works with responses (plot, control, reacts...).

This would create truly scalable 3d printer achitecture.

Do we have all the pieces that we need to implement this

Related issues:
https://github.com/KevinOConnor/klipper/issues/119
https://github.com/KevinOConnor/klipper/issues/151
https://github.com/KevinOConnor/klipper/issues/485

**Comment by KevinOConnor** [comment]
FYI, I've been working on adding support for the Mechaduino (and the very similar "Smart Stepper" and their clones) to Klipper.  More details at PR #1038.

The support I'm working on uses the USB bus for all communication.  If someone wishes to add support for SPI/I2C then that's fine, but that isn't something that interests me.

-Kevin

**Comment by FixFuture** [comment]
Great! 

I'll take look at this. I have notified uStepper development team about klipper. 

The problem that I see with USB implementation is that number od steppers is limited to number of usb ports available and require separate power source.

I'll see if my skills are enough to contribute.

**Comment by KevinOConnor** [comment]
Sounds good.  I'm going to close this issue.  Further updates on mechaduino support can be tracked on PR #1038.

-Kevin
