### ISSUE TITLE
Extruder not heating up

### ISSUE THREAD

**Issue by amalabey** [KevinOConnor/klipper#1046]
I am trying to get Klipper working with Anycubic Delta Kossel (Pulley Upgrade) version printer. Installed, connected and did a basic calibration. But, if I set the tool temperature to 50C, it is not heating up. What could be the issue here?

I even tried adding "verify_heater" section and giving it more time to heat up, still no luck.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2712290/klippy.log)

**Comment by amalabey** [comment]
It appears to be a problem with the heater. What could have caused the heater to stop working?

**Comment by muenznej** [comment]
`Is there anything in Klipper that could have damaged the heater?`
well you could always damage smth by using wrong configs for example if the thermistor is broken the heater could be wrong and things escalate. Usuaully its not like this and the heaters have a broken cable. That was the case in like 100% of all my damaged heaters. I usually fix it by soldering/crimping and stiffen them with shrinking tube.

good luck with the new heater :-)

**Comment by KevinOConnor** [comment]
I can't think of anything that the software could do that would damage a heater - other than melting it - which does not appear to be the case here.

-Kevin
