### ISSUE TITLE
I have to run my Ender 3 at 240C for PLA

### ISSUE THREAD

**Issue by peterlpop** [KevinOConnor/klipper#1059]
It used to be 210F by subjective quality. How do I calibrate the settings it to show about correct? (and then I will use an external probe to make it accurate_).

**Comment by jakep82** [comment]
It sounds like you don't have the correct thermistor configured in your printer.cfg file.

**Comment by peterlpop** [comment]
I have NTC Thermistor 100K 3950 (been looking for answers ... found the way to define a new one in config file). 

What do I put in my config file based on this model?

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L150

**Comment by peterlpop** [comment]
Thanks. I guess using an already made ender3.cfg made me skip reading the example.cfg file.

**Comment by KevinOConnor** [comment]
I'm going to close this as I think the original question was answered.

-Kevin
