### ISSUE TITLE
first heating bed, then extruder nozzle. 

### ISSUE THREAD

**Issue by peterlpop** [KevinOConnor/klipper#1069]
Is it normal for the heaters to go one at a time - stock firmware heated them both (and I "think" Klipper did it as well on the first day I had it installed. Did I change something and I can't remember? Thanks.

**Comment by Master92** [comment]
It depends on what commands you send to the printer. For example when you issue an M140, the printer heats up the extruder to the specified temperature and waits for the process to be completed, before executing the next command. However an M104 does the same thing without waiting. Same for M109 and M190 for the heated bed.

**Comment by KevinOConnor** [comment]
I'm going to close this as I think the original question was answered.

-Kevin
