### ISSUE TITLE
unknown GCODE "?$G"

### ISSUE THREAD

**Issue by troisplus** [KevinOConnor/klipper#1074]
[klippy.4.1.19.log](https://github.com/KevinOConnor/klipper/files/2727167/klippy.4.1.19.log)
![screen1](https://user-images.githubusercontent.com/8343671/50690845-24e4ea00-102f-11e9-8f15-c14ced6fe771.jpg)
![screen2](https://user-images.githubusercontent.com/8343671/50690853-27474400-102f-11e9-97cc-b2cd9c49381e.jpg)

After several tests and a satisfactory first print, I want to solve a problem appeared from the beginning. Octoptint keeps sending an unknown GCODE (?$G to the terminal). I think this problem is related to the absence of a temperature check on the graph (yet functional during printing or PID). The command M105 does not answer either. Do you have an idea?

**Comment by john--** [comment]
Hi @troisplus , are you trying a klipper stable release, e.g. 0.7 or did you check out from master? I ask because master got quite a few merges recently, including something I personally put in around heater reporting. Not sure if that's the issue but I'd be curious to see if it's a new issue or not.

**Comment by john--** [comment]
Also, just one other thing to consider, is it Klipper or Octoprint at fault? A quick google search showed someone else seeing the same behaviour as you after installing a buggy CNC related Octoprint plugin. Not saying it's that, but something to keep in mind.

**Comment by troisplus** [comment]
OMG, i'm sorry...
I was however convinced to have disabled all the plugins off octoklipper and preheat ...
This is effectively the GRBL plugin fault.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the issue was resolved.

-Kevin
