### ISSUE TITLE
PID Tuning

### ISSUE THREAD

**Issue by tilsonm** [KevinOConnor/klipper#108]
I may be missing something, but when I try to run a PID Tune (M303 S215 C4) which should cycle around 215 degrees 4 times, it does not return the PID values to the terminal window in OctoPrint. Am I missing something?

**Comment by tilsonm** [comment]
I just found this information in /tmp/klippy.log after PID tuning finishes.
This will work temporarily, but I do not think this is a long-term solution. The klippy.log file can get very long and hard to sort through.

It would be nice to have it echo the results to the terminal window in OctoPrint, and/or automatically update the printer.cfg file.

**Comment by KevinOConnor** [comment]
As of commit 5caff594c, the PID tuning results will be reported back via the g-code terminal.

**Comment by lenne0815** [comment]
Great ! Thank you kevin !

**Comment by tilsonm** [comment]
Yes thank you Kevin!
