### ISSUE TITLE
BlTouch Bed Crash

### ISSUE THREAD

**Issue by Michi1210** [KevinOConnor/klipper#1092]
Hi guys,
I am new and I am not so good with 3d printer firmware.
I have Klipper installed and now try to take my BLTouch into operation.I have the problem that he drives to the first measuring point and ignores the triggering of the BL Touch (Nozzle goes down to the Z switch and into the bed)

My Config:
###########################################################################
[bltouch]
sensor_pin: ar2
control_pin: ar11
pin_move_time: 0.200
x_offset: 5
y_offset: 30
z_offset: 1.72
speed: 5
############################################################################
My Printer: Anycubic i3 Mega
BlTouch offsets: x -1, y -24 

currently I have a BlTouch clone, an original is on the way but because I really wanted to use for another printer.

Thx for Helping

**Comment by KevinOConnor** [comment]
In order for us to assist, you'll need to attach the klipper log file from the event.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

If you're going to retest, you may wish to retest with the code described at PR #1091.

-Kevin

**Comment by Michi1210** [comment]
Update:  get a new BlTouch and now it runs.
But I have another problem now.
He palpates me as he should from the surface (5x5) and then uses this grid (when printing moves the Z axis), but now I have the problem that he me in the left part of the Ultrabse by 0.1mm too deep, in the right part The UB fits it, no matter what I do and do it without change.
And if I look at the mesh with OctoPi (Bed Visualizer Plugin), the BED always looks different.

[klippy.log](https://github.com/KevinOConnor/klipper/files/2774243/klippy.log)

[printer.zip](https://github.com/KevinOConnor/klipper/files/2774248/printer.zip)

**Comment by KevinOConnor** [comment]
If you're reporting an issue with mesh bed levelling, then I suggest you open a new issue with the log and a description of the problem.  (Otherwise, the right people will not see your issue report.)

-Kevin
