### ISSUE TITLE
[Suggestion] Proper source folder naming

### ISSUE THREAD

**Issue by FHeilmann** [KevinOConnor/klipper#1093]
Since klipper contains multiple src subfolders that cater to a specific architecture as opposed to a specific mcu I suggest renaming them in a uniform way.

- avr devices are covered by the folder `avr`
- atsam devices like the sam3 and sam4 family are currently in a folder `sam3`, I suggest renaming this folder to `atsam` as that is how most libraries call this family of mcus
- the samd21 support is currently in a folder `samd21`. Since samd21 encompasses multiple mcus, and a very similar architecture exists in the samd51 family of chips which will probably become very relevant for klipper once the Adafruit Grand Central is released, I suggest renaming this folder to `atsamd`

Cheers,
Florian

**Comment by KevinOConnor** [comment]
Interesting.  I didn't realize the SAMD21 peripherals are also in higher end chips (eg, the SAMD51).

If you'd like to submit the above changes, I'm fine with it.

-Kevin

**Comment by FHeilmann** [comment]
See #1100
