### ISSUE TITLE
Increase square corner velocity past 5?

### ISSUE THREAD

**Issue by BladeScraper-Designs** [KevinOConnor/klipper#1099]
Someone told me that changing square corner velocity to something like 20 will make the printer fly off the table.  Sounds fun.  But Klipper throws an error when I tell it to use a value higher than 5.  Is it possible to change the max setting?

**Comment by jakep82** [comment]
Almost all configuration options are explained in example.cfg, and example-extras.cfg.

https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L300

**Comment by Master92** [comment]
You have to configure it in your `printer.cfg` first. You cannot issue a `SET_VELOCITY_LIMIT` command with a higher `SQUARE_CORNER_VELOCITY` than you set up in your config file. Once you change it there and issue a `RESTART`, the error will most likely disappear.

-Nils

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the original question was answered.

-Kevin
