### ISSUE TITLE
TMC2130 ISP after poweroff not moving

### ISSUE THREAD

**Issue by derju** [KevinOConnor/klipper#1119]
I´m running Klipper on a MKS Gen L @24V. After the 24V PSU is turned off and later on again i have to restart the firmware, otherwise the steppers wont move.
My guess is that the software doesn´t push the ISP config to the drivers after they´re inactive. Would be nice to change that so i can reliably use a HS110 wifi outlet to turn off the psu after a print and turn on again at the start of a print

**Comment by cmock** [comment]
According to the datasheet, you're not supposed to do this -- the motor voltage (Vm) needs to be powered on before the IO voltate (Vio) is powered on, or bad things may happen. Watterott recommends using their protector shield, which has a diode from Vio to Vm so Vm has at least 5V applied at all times (And I'm running this on a RAMPS with a switchable 12V power supply successfully).

**Comment by KevinOConnor** [comment]
I suppose it's possible to resend the tmc init sequence to the drivers.  Someone would need to do the development for that and submit a pull request though.  Also note that one could just type RESTART in the OctoPrint terminal as well.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it doesn't look like anyone is currently working on adding this support.  If someone wishes to implement it, please open a pull request with that support.

-Kevin

**Comment by krpepe** [comment]
@KevinOConnor  If you type RESTART in OctoPrint terminal you will need to re-send the psu on command as well or the psu off is recognized in the terminal window with an ok but does nothing.
