### ISSUE TITLE
standalone klipper

### ISSUE THREAD

**Issue by nikhil8333** [KevinOConnor/klipper#1122]
Hi kevin,
    I am a 3d printer hobbyist and you can count me  as a newbie hear, as far as understand klipper needs a host software to control it like octoprint which is a flask based web interface. but instead we can make a python application with kivy giving us full screen touch interface experience to access klipper and as an addon we can add pronterface for web interface instead of octoprint. this python app and pronterface together can make klipper more accessible.

**Comment by drphil3d** [comment]
Octoprint just gives you a web interface for the host, it's already written in python. The host software can be run on a raspberry pi, beagle bone black, allwinner cpu or desktop computer. The software is very accessible.

**Comment by bshowket** [comment]
I am user of kivvy and I think it's an excellent idea. Specially for rpi2. My rpi takes about 10 minutes before I can use the web interface. Where kivvy will be ready instantly. Also print via octoprint causes pause for small move, so I manually do sd card print most of the time. Kivvy is more responsive and with low power rpi and tft screen, it would be a great choice!

**Comment by drphil3d** [comment]
I have never heard of Kivvy. I don't think you understand the basic premise of this software or how it operates. The documentation may be a little bit hard to understand at first and be a little bit disorganized but It does a good job of explaining how it works and why its better. I wrote this article today about my mutli mcu printer that I'm building. https://vectormfg.net/klipper-multi-mcu

**Comment by bshowket** [comment]
From my understanding kivvy build for HMI interface with low cpu consumption and responsive. Kivvy take out all extra module and build on minimum configuration. You add what you need such as python, webserver, chrome... Which makes low power computer running smoothly. I understand klipper itself is standalone. Kivvy can solve HMI issue only.

**Comment by drphil3d** [comment]
That's actually an excellent idea, I was skeptical at first seeing it was originally built for PLCs but has evolved over the last few years quite a lot.
This would actually solve a few of the issues with raspbian / octoprint as far as being end user friendly. I was looking at adding a program that sets up a captive portal to connect to wifi, but it looks like they already have some of that code in here already.
https://github.com/pipaos/pipaos-tools/blob/master/src/pipaos-setwifi

http://kivypie.mitako.eu/kivy-pie.html

**Comment by nikhil8333** [comment]
> Octoprint just gives you a web interface for the host, it's already written in python. The host software can be run on a raspberry pi, beagle bone black, allwinner cpu or desktop computer. The software is very accessible.

Flask is basically a html integration to a python backend server, i used this methodology in some of my projects but always the latency makes trouble as sever needs boot up, but we cannot completely depend upon a kevy application as there are use cases where people control multiple printers from a single host PC and to compensate that we can add pronterface as an addon, or if kivy supports web interface we can integrate options into kivy itself--->> FYI i don't know whether kivy supports a web interface or server hosting, if anyone knows about it please enlighten me

**Comment by drphil3d** [comment]
the only way I can see doing this easily is by writing an octoprint plugin or using api access to pass commands from the screen buttons to octoprint. 
it's possible to connect multiple printers but that's a nightmare of is own and isn't practical for this application.
Kivy runs locally on the raspberry pi, it would just be a matter of getting the kivy touch screen interface to talk to octoprint. It already has access to shell scripts so it can change and configure things.

**Comment by drphil3d** [comment]
Google Kivy octoprint 

https://github.com/matt448/OctoPiTouchPanel
https://github.com/timothyhollabaugh/octoscreen
https://discourse.octoprint.org/t/gui-for-5-touchscreen-with-pi/1681/3

**Comment by nikhil8333** [comment]
Instead of using octoprint as a median a python ui is integrated with klipper which works Directly with klipper commands, by this klipper does not require any median softwares instead it becomes standalone. Your recommendation make the matter more complex as again a flask server based octoprint is involved. Kivy is just a python library hence can be embedded into klipper source files and can be called when required

**Comment by nikhil8333** [comment]
@KevinOConnor how does klipper communicate with octoprint and mcu, can you explain me so that we can start working on ui script

**Comment by drphil3d** [comment]
It communicates over serial

**Comment by theopensourcerer** [comment]
@nikhil8333 https://github.com/KevinOConnor/klipper/blob/master/docs/Code_Overview.md

As I understand it, essentially, Klipper sits _between_ Octoprint and the MCU. You configure Octoprint so that the printer port is actually an "internal" port on the Raspberry Pi (/tmp/printer). So Octoprint really doesn't "know" anything about Klipper at all as far as it is concerned it's just the printer MCU. 

If you haven't already I would suggest setting it up and getting familiar with it first.

**Comment by theopensourcerer** [comment]
@nikhil8333 https://github.com/KevinOConnor/klipper/blob/master/docs/Code_Overview.md

As I understand it, essentially, Klipper sits _between_ Octoprint and the MCU. You configure Octoprint so that the printer port is actually an "internal" port on the Raspberry Pi (in /tmp/printer). So Octoprint really doesn't "know" anything special about Klipper at all, as far as it is concerned it's just a printer MCU. 

If you haven't already I would suggest setting it up and getting familiar with it first.

**Comment by jakep82** [comment]
I'm sure Kevin has more insight, and the code overview is a good place to start, but to be clear Octoprint is in no way required to run Klipper.  All Octoprint provides is an easy to navigate web interface, and a method for feeding gcode to the virtual serial port that Klippy creates on the host computer.  

That said, other people have successfully used Klipper on a variety of host computers without Octoprint.  Octoprint is not a requirement in any way, but you do need a host computer to run Klippy, so the printer will always be tethered to something.

Some discussion about this can be found [here.](https://github.com/KevinOConnor/klipper/issues/138)

**Comment by theopensourcerer** [comment]
@jakep82 Thanks - having re-read my comment I can see that it wasn't very clear ;-)

**Comment by drphil3d** [comment]
that's really good to know, I just assumed it relied on octoprint sense I didn't see anything in the documentation that would have led me to think differently.

**Comment by BlackStump** [comment]
It would be great if a efficient web server a alternative to Octoprint could be made for Klipper.
actually a simple Pronterface is all that is need then people will have the option of simple and efficient or all singing and dancing but slow Octoprint.

**Comment by jakep82** [comment]
Please read the link I provided.  The second post is from someone that was using pronterface with Klipper a full year ago.  I'm also aware of a Klipper fork that integrates Duet Web Control, and Repetier Server also supports Klipper.  So to reiterate again, nothing prevents someone from using something other than Octoprint to run a printer with Klipper.

**Comment by BlackStump** [comment]
@jakep82  do you have a link of duet web control connecting to klipper, I looked at Repetier did not like it one bit so not a option for me. btw I was wanting it for the BBB/Replicape that Octoprint really struggles with atm and not sure why if I load a 15Mb gcode file Octoprint is 100% cpu usage and I can not even home until Octoprint finishes analyzing the gcode 15 minutes later.

**Comment by nikhil8333** [comment]
@theopensourcerer, thanks for the input, I have set it up already but was curious whether any extra functional requests are set up b/w octoprint and klipper, but yeah now everything is clear . So I think making a functional script having kivy libraries to produce UI and upon clicking any button or function on the ui it has to wake klipper functions individually according to usage is enough, no additional edits for previous settings are required, I guess

**Comment by jakep82** [comment]
@BlackStump It's a fork of Klipper maintained by @cruwaller .  It is nowhere close to a stock version of Klipper, and I don't know how stable his branch is, but it does include Duet web control.

https://github.com/cruwaller/klipper/tree/testing/klippy/modules

**Comment by BlackStump** [comment]
@jakep82  thanks I tried searching but came up blank.

**Comment by KevinOConnor** [comment]
FYI, I added an item to the FAQ for this question (commit 76138fde5).

-Kevin

**Comment by nikhil8333** [comment]
I understand but instead of a virtual serial port can't we call individual functions of klipper through a python code??,  If yes, then we can make a kivy interface directly calling functions instead of virtual serial

**Comment by KevinOConnor** [comment]
I'm sure it's possible - if someone is interested in developing this they should read through the documentation.  In particular, see the information on adding an "extras" module in docs/Code_Overview.md .

-Kevin
