### ISSUE TITLE
A little problem with the shutdown speed of the fans

### ISSUE THREAD

**Issue by nandinho84** [KevinOConnor/klipper#1126]
So, I've realized just now this problem. 
I have an heater fan set to a shutdown speed of 1.0. Everything is ok when I type M112 on the terminal... The fan goes full speed as it should. But when, for some reason, I need to make a firmware restart when the heater is on (it is supposed to turn off the fan for a short moment and then turn on again after "klipper is ready") if an error occours for some reason, then the fan just is turned off and then remains off... This is a problem if we do a firmware_restart with the heaters still hot.
This is a problem easily resolved with an M112, but I think it would be nice if it could engage the shutdown speed after the fw restart and an error occours.
I don't know if I made myself clear...

**Comment by workheart** [comment]
I cand confirm this, I just tried A firmware reset a HW reset (arduinomega) and restarted the Host. with the hotend at 100*C and the (extruder cooing)fan set to 50*c the fan went of during the reset for few sec but went on as soon as it booted again. 
can you recreat it maybee logg it?

**Comment by nandinho84** [comment]
The problem only occurs if some error happens during the reconnection. For example, if you change anything in the config file that results in an error.

**Comment by KevinOConnor** [comment]
This is the intended behaviour of FIRMWARE_RESTART.  The FIRMWARE_RESTART command does a restart of the micro-controller and clears its configuration.  At that point, the micro-controller does not know what pins should or should not be enabled.  It's the role of the host software do configure the micro-controller - but if the host software is incorrectly configured it will not be able to do that.

I recommend only issuing a FIRMWARE_RESTART command when the printer is in stable state.

-Kevin

**Comment by nandinho84** [comment]
Ok. In that case, that's not an error. But if it could be written in the installation documentation as a warning it would be useful for someone. Thanks
