### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by BearInThere** [KevinOConnor/klipper#1128]
As a newbie to python I spent hours yesterday trying to set up an IDE so I could step through the code and understand it.
Having finally realised my problem was that the IDE's I was trying targeted Python3 and that Klipper was written using Python2 things became a lot smoother, and with this realisation I found no shortage of reference here.

If you could add that small bit of info to your overview docs it may save someone else the pain.

Dan B

**Comment by trevjonez** [comment]
@BearInThere what did you end up with for your IDE and setup? 

I have gotten pycharm professional working very nicely and the code is all on a remote machine, run and debug included. I was contemplating doing a small tutorial journal entry to help anyone else with the setup. This is my first attempt at python anything so it was a hard earned lesson, but the outcome has been great for productivity.

**Comment by BearInThere** [comment]
I’m with you brother
I am keen to share my ignorance.

Kev, your project has obviously evolved to the point of existence.
Should it not be to the point where the curious can ask questions without logging an Issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jakep82** [comment]
You mean through IRC or the mailing list?

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#mailing-list

**Comment by BearInThere** [comment]
Trev  I’m hearing you.
I started with VS2017 (where I feel at home). But it was my ignorance of Python as a language that got me into trouble.
Pycharm didn’t fix it.  But it did help me to understand the limitations of my knowledge.
I’ve been paying 15$ a month to ReSharper for the last couple of years without complaint and the fact that Pycharm comes from the same source gives me confidence.

But hey that’s the tool we choose.

________________________________

**Comment by BearInThere** [comment]
Jakep82 
Yeah I am aware of the mailing list 

I was  thinking as the project grows more of a wiki.

Keven has create a brilliant system here and as more people become interested more questions will arise.
They should not be Issues, and the average fool should have a way to ask advice without signing upto a  mailing list.

Hey that's my POV

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/issues/1060#issuecomment-451052072

**Comment by BearInThere** [comment]
Cheers.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by BearInThere** [comment]
@trevjonez 
Cheers mate but right now I am 100% drunk.
Happy to chat later.

**Comment by BearInThere** [comment]
Back to my point
Had you mentioned Python2 in your documentation
I would no be playin 3.6

**Comment by KevinOConnor** [comment]
Thanks for the feedback.  I've noted it.  If I get additional queries like this I will add it to the FAQ.

-Kevin
