### ISSUE TITLE
Virtual SD Card shows hidden files

### ISSUE THREAD

**Issue by grblmpfh** [KevinOConnor/klipper#1138]
If you have configured a [virtual_sdcard] in combination with Octoprint a file named ".metadata.json" will be selectable in the list of files. Files starting with a "." should be invisible.

**Comment by grblmpfh** [comment]
I think I have to re-phrase that a little bit:

If you select "SD Card" on the displays menu Octoprints file ".metadata.json" is shown in the file list and can be selected for printing. It even gets loaded into Octoprint for printing which leads to an error.

So, files beginning with a "." should not be listed in that file list and should not be passed onto Octoprint.

I hope that is a little better to understand ;)

**Comment by KevinOConnor** [comment]
Understood.  I agree it should be changed.

-Kevin

**Comment by KevinOConnor** [comment]
Should be fixed as of commit f1c80490.

-Kevin
