### ISSUE TITLE
endstop phase on dual z?

### ISSUE THREAD

**Issue by tcj-lev** [KevinOConnor/klipper#1142]
Hi,
I would like to use the endstop phase feature on my dual z printer (Anycubic i3 Mega)
But this does not seem to work.
ENDSTOP_PHASE_CALIBRATE does not give any number for Z1 even not with STEPPER=stepper_z1

**Comment by KevinOConnor** [comment]
In order for us to assist, you'll need to attach the Klipper log file from the event.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin
