### ISSUE TITLE
"BLTouch failed to verify sensor state" on "G28 Z"

### ISSUE THREAD

**Issue by stemaDev** [KevinOConnor/klipper#1154]
"Send: G28
Recv: !! BLTouch failed to verify sensor state
Recv: !! BLTouch failed to verify sensor state" (X and Y homes, goes to center, if it's retracted, the pin is released (turns off it's light, never was blinking) but gives this error message when it should start going down)
"pin_up" and "pin_down" works ("control_pin" should be fine)
"QUERY_PROBE" shows "opened" and "TRIGGERED" correctly ("sensor_pin" should be fine)
Because of the things above, I would also think that I installed the bltouch right and that it works. It worked before on a tevo tarantula with an earlier klipper, now it's on an ender 3 (stock board) with the latest klipper. It's a clone, called "3d touch".
I have the VCC pin covered in the usb cable's plug, so the raspi is not powering the printer.

[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/2798212/printer.cfg.txt)
Edit: the sensor pin is just "^PC4" without the "!", I uploaded the wrong config file

**Comment by gerrylenz** [comment]
My workaround is

[bltouch]
...
pin_up_touch_mode_reports_triggered: False
...

**Comment by stemaDev** [comment]
> pin_up_touch_mode_reports_triggered

It starts to go down, but the pin isn't getting deployed that way (and light stays on). Also tried pin_up_reports_not_triggered and combinations, but nothing yet worked. Thanks though (Y)

**Comment by fredizzimo** [comment]
Many people have better luck with my version, https://github.com/KevinOConnor/klipper/pull/982. There are instructions near the bottom for how to test it out, so could you please test that instead?

So far I'm not aware of any clone that doesn't work with that, at least if you set `test_sensor_pin` to False. There might be some non-working configuration, but no one has provided proper logs so I can see if if something really is wrong or not. Note that the `test_sensor_pin` setting only tests for very specific cabling errors, and only works one genuine probes, most clones don't support it. Even if you have it disabled, the built in error checks are performed, which can detect a much wider range of errors. 

I also recommend my version if you care about more robust behaviour. These are some tests that I did with a genuine BLTouch Smart https://github.com/KevinOConnor/klipper/pull/1091#issuecomment-453749542, on the version that we merged to master, as you can see there are a lot of very basic issues.

**Comment by stemaDev** [comment]
"pin_up_touch_mode_reports_triggered: False" did work, maybe the cables went loose or maybe the "False" is case sensitive, but it works now, thank you!
