### ISSUE TITLE
Retract to fast

### ISSUE THREAD

**Issue by bensen-666** [KevinOConnor/klipper#1155]
Hi,

It's not easy to configurate Klipper with an Ender-4 and MKS Gen L and TMC2100 drivers.... I saw the documentation. It's good discribed. But i have a problem. The retract and feedrate after retraction is to fast! Normally i dont hear any steppermotor. But The e-axis make very hard noise. Where can i change the right values for the extruder? Sorry for my bad english

**Comment by KevinOConnor** [comment]
If you're having an issue with Klipper then you'll need to attach the Klipper log file - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

The speed of retraction is typically controlled by the slicer.  It's also possible to impose a limit in Klipper by setting the max_extrude_only_velocity and max_extrude_only_accel settings - see config/example.cfg for the details.

-Kevin

**Comment by bensen-666** [comment]
I changed the values. It seems that the Slicer settings will be ignored. I printed a callibration cube.... it shoud be 20x20x20mm ist is 20x20x5 mm in hight it is only 5mm. I don't know why. 
![img_20190127_194505](https://user-images.githubusercontent.com/26736343/51805439-8a627a00-226d-11e9-9f89-5f20e697e3bc.jpg)

**Comment by cosminr86** [comment]
Wrong z step distance
