### ISSUE TITLE
delta_calibrate stuck in "Working on calibration"

### ISSUE THREAD

**Issue by cmock** [KevinOConnor/klipper#1157]
I'm currently mechanically rebuilding my Kossel Mini and have been issuing quite a few successful DELTA_CALIBRATE commands today.

The last one of those, instead of almost immediately outputting the parameters after probing, just said "// Working on calibration..." over and over again. 

Fine, I think to myself, the optimization algorithm is running wild, but no, "top" shows no CPU usage for the klippy process...
[klippy.log](https://github.com/KevinOConnor/klipper/files/2799074/klippy.log)

After restarting the kippy process and issuing another DELTA_CALIBRATE, everything is back to normal.

**Comment by KevinOConnor** [comment]
FYI, I saw this recently on my delta printer as well.  My best guess was that it occurred because I ran detla_calibrate multiple times prior to finishing the first attempt.  I'll add it to my list of things to look at.

-Kevin

**Comment by Nossolov** [comment]
Same for me.
Once with advance calibrate, and yesterday with normal manuel calibration.
I thing (but not sure) that one calibration point (7 points for me) was not good and far from real (Maybe 1mm, my fault...).
Reboot the raspberry, calibrate again, and everything fine.

**Comment by pappabj0rn** [comment]
Ran into this yesterday too.
Was running a manual calibration and accidentally hit accept (set up as macro button) just after moving to a new point (so 5 or so mm up of the bed). It didn't like that and I had to abort and redo it, which den got stuck in the working on calibration loop.

**Comment by KevinOConnor** [comment]
@pappabj0rn - are you on a recent version of the code?  (I was thinking this might have been fixed with some reactor changes a few weeks ago, but I guess not.)

-Kevin

**Comment by pappabj0rn** [comment]
Yeah, just installed it this tuesday, I think.

**Comment by KevinOConnor** [comment]
FYI, I did find and fix an error in this area of the code (commit 139274f0).  If anyone sees this error again, please report it (and provide the klipper log file).

-Kevin

**Comment by Nossolov** [comment]
Ok, thank you. 
Everything works so great that i'm afraid by doing an update now ! 
May be for the next printer to come ? 
Really a great job. 



----- Mail original -----

De: "KevinOConnor" <notifications@github.com> 
À: "KevinOConnor/klipper" <klipper@noreply.github.com> 
Cc: "Nossolov" <palafon@laposte.net>, "Comment" <comment@noreply.github.com> 
Envoyé: Vendredi 13 Décembre 2019 01:41:19 
Objet: Re: [KevinOConnor/klipper] delta_calibrate stuck in "Working on calibration" (#1157) 



FYI, I did find and fix an error in this area of the code (commit 139274f ). If anyone sees this error again, please report it (and provide the klipper log file). 

-Kevin

**Comment by KevinOConnor** [comment]
Alas, it's definitely still broken.  I added a delta_calibrate test case, and now the automatic build will randomly fail sometimes..

-Kevin

**Comment by Nossolov** [comment]
Of course it's sad, but everything else works fine and manual calibration is easy and good. 

No chance i change Klipper for another one ! 


----- Mail original -----

De: "KevinOConnor" <notifications@github.com> 
À: "KevinOConnor/klipper" <klipper@noreply.github.com> 
Cc: "Nossolov" <palafon@laposte.net>, "Comment" <comment@noreply.github.com> 
Envoyé: Dimanche 15 Décembre 2019 16:53:45 
Objet: Re: [KevinOConnor/klipper] delta_calibrate stuck in "Working on calibration" (#1157) 



Alas, it's definitely still broken. I added a delta_calibrate test case, and now the automatic build will randomly fail sometimes.. 

-Kevin

**Comment by Alkarasu** [comment]
> FYI, I did find and fix an error in this area of the code (commit [139274f](https://github.com/KevinOConnor/klipper/commit/139274f0bbb0cd36e4bf1b858ea14da3b7859c2a)). If anyone sees this error again, please report it (and provide the klipper log file).
> 
> -Kevin

Got hit by it today. Here's the log.
[klippy.log](https://github.com/KevinOConnor/klipper/files/3969668/klippy.log)

**Comment by KevinOConnor** [comment]
I found and fixed an error that could cause these issues (commit abf49349).  Hopefully it is now fixed.  If anyone runs into this with the latest code, please report and attach the log.

-Kevin

**Comment by KevinOConnor** [comment]
I think this has been fixed.  The DELTA_CALIBRATE command has been in the automatic build tests and there hasn't been a build failure since abf4934.

-Kevin
