### ISSUE TITLE
Branch: work-replicape-20180108; Steppers not disabled when issuing M112

### ISSUE THREAD

**Issue by sapell** [KevinOConnor/klipper#116]
Klipper is not disabling the steppers when issuing M112.
For safety, that would be critical to release the motors when emergency stop is issued.

Uncertain whether this issue applies to other branches as I have not been able to test this on other branches as Replicape stepper disable was fixed just in this branch.

[klippy.log.gz](https://github.com/KevinOConnor/klipper/files/1616811/klippy.log.gz)

**Comment by KevinOConnor** [comment]
A valid point, that I had not thought of.  To be clear, the current control should be zero'd on an M112, but the new code would not turn off on an M112 (nor would it on any branch).  It requires some work to do that, as the mcu needs to be able to handle a shutdown itself, which means the mcu needs to know what spi message to send on a shutdown.

Lets use the existing issue #62 to track this.
