### ISSUE TITLE
[FR] post error on LCD

### ISSUE THREAD

**Issue by Hywelmartin** [KevinOConnor/klipper#1164]
Would it be possible to post the errors to the LCD like an (M117 LCD status message)

**Comment by KevinOConnor** [comment]
I'm sure it's possible, but someone would need to do the development work to implement it.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive as it isn't clear to me that anyone is currently working on implementing it.

-Kevin

**Comment by Hywelmartin** [comment]
well I don't have the knowledge.... @KevinOConnor  where do you store this kind of Ideas?
I got the idea due to many reports that "the printer just stopped" or "my printer just turned of the heaters"..
