### ISSUE TITLE
[controller_fan] is not a valid section

### ISSUE THREAD

**Issue by itsthejoker** [KevinOConnor/klipper#1165]
Hi there! When applying the config found here https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L432-L454 in an attempt to get automatic control of a LED light bar with higher PWM requirements than a fan, I get the error that [controller_fan] is not a valid section. Log is included.

Cheers!

[klippy.log](https://github.com/KevinOConnor/klipper/files/2801010/klippy.log)

edit: And if there's a better way to do what I'm trying to do (since with my limited knowledge of LEDs, I should just be able to connect them to direct non-PWM'd power since I just want full brightness) through Klipper, please let me know. Basically I just want a 12v light strip to come on when the heater's on and go off when the heater's off. Bonus points for allowing manual control through the web interface. I looked through the configs and the open issues but didn't see anything that relates to this.

**Comment by pecirep** [comment]
Looks like you're missing a mandatory option. Did you define a heater this fan associated with?

**Comment by itsthejoker** [comment]
Default is "extruder", which matches my config. I'll throw it in just to verify, though.

**Comment by pecirep** [comment]
can you post the entire section?

**Comment by itsthejoker** [comment]
Here's the entire [controller_fan] section with all flags set. It continues to give the same error as above.

```ini
[controller_fan]
pin: ar3
cycle_time: 0.005
hardware_pwm: False
max_power: 1
shutdown_speed: 1
kick_start_time: 0.100
idle_timeout: 60
idle_speed: 1
heater: extruder
```

**Comment by pecirep** [comment]
I've just copy-pasted that section to my printer and it works. This is a somewhat recent addition, have you updated klipper?

**Comment by itsthejoker** [comment]
That... is a great question. Let me take a look at that.

**Comment by itsthejoker** [comment]
Shit, that was the answer. I should have checked that. Thanks, mate!

**Comment by pecirep** [comment]
oh yeah, I killed that recently, thanks for the heads-up 😄
