### ISSUE TITLE
Features request MCU support for STM32F4/F7

### ISSUE THREAD

**Issue by semos2k** [KevinOConnor/klipper#1168]
Think about adding support for the mcu stm32f4 / f7 there is a lot of work developing boards with these low cost mcu, with support of fpu and many other things.

https://github.com/Aus3D/RUMBA32
https://github.com/ktand/Armed
https://github.com/hasenbanck/remram
https://github.com/ghent360/PrntrBoard

I love klipper, really a great job.

**Comment by KevinOConnor** [comment]
Indeed the stm32f4 does appear to be an interesting line of boards.  This would require an interested developer with the appropriate hardware and time to implement, however.

-Kevin

**Comment by JustAnother1** [comment]
I have done some development on STM32F4 chips. I have some stm32f4 dev boards around, but none of the mentioned boards. I also don't know if I would have the time.

But if an interested developer comes around I would offer to help.

**Comment by semos2k** [comment]
I think it is not necessary to have one of these boards, it is the same case of using an atmega2560 there are many models how important is the configuration of the pins and their responsibility.

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive as it doesn't look like it is currently being worked on.

-Kevin

**Comment by mocksoul** [comment]
H743ZI is also a "next MCU to support candidate" imo :)

**Comment by KevinOConnor** [comment]
FYI, stm32f4 support was recently added to Klipper.

-Kevin

**Comment by dreamcat4** [comment]
> H743ZI is also a "next MCU to support candidate" imo :)

@mocksoul yes indeed.... you called it!

This has the fastest coretex M7 by ST, and is now inside the new BIQU BX printer, it is BTT's faster control board now.

Another nice thing it comes with are touchsceen and adaptor boards / housings... all compatible with the rPi. So as shown in the video below here it is possible to install octoDash.

https://www.youtube.com/watch?v=bfhhUVJkP_s&t=0s

It seems these stm32h743 give a coremark benchmark result of '2000'. That is almost 4x faster than the 533 coremark score of the F4 series mcu that is in the SKR PRO....

This new controller board has not been released separately on its own yet. At least at the time of writing. But is named the SKR SE-BX. BTT seem to want to make the place to discuss about this board over on their reddit:

https://www.reddit.com/search/?q=se-bx
