### ISSUE TITLE
Extended G-Code for max_extrude_only accel/velocity?

### ISSUE THREAD

**Issue by ewb-git** [KevinOConnor/klipper#1171]
Hello,

I was looking at the extended gcode commands, and I saw you have a lot of useful commands for speeds and velocities, which would allow for easy testing with a "if layer z" command in many slicers.

I was also interested in testing the max_extrude_only accelerations and velocities, however, I believe there aren't any specific extended gcodes to target these? I might be wrong since I'm new to Klipper, but if they don't exist I think they could be useful for calibration/testing purposes.

Thank you!

**Comment by KevinOConnor** [comment]
There are currently no commands to change the "extrude_only" config settings at runtime.  Though it is possible to alter the settings in the file and then issue a RESTART command.

-Kevin

**Comment by ewb-git** [comment]
Yea I was thinking for tuning extruder acceleration/velocity, it would be nice to have an option to print a multi-level speed tower using z height. That way you can automate everything into 1 or 2 prints instead of having dozens of small print operations that need to be labeled, time consuming, and difficult to compare.

Well, it would be a nice feature to consider. Thanks!

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive as it doesn't look like it is currently being worked on.

-Kevin
