### ISSUE TITLE
Homing Procedure

### ISSUE THREAD

**Issue by Fabrizio3** [KevinOConnor/klipper#1173]
so, when i home i sometimes get the X endstop still triggered after retract error, this is caused by the X being already at home, and when it moves away, it doesnt move enough to turn the switch off, the switch (from pressed) needs about 5mm of retract to latch off (its shorter distance to trigger than to untrigger)
TLDR: can we change the homing bump/retract distance? just need it to be 1mm more to fix this issue (marlin has homing bump distance, so you can set it to what you need)

this would be the fix to the X endstop still triggered, the problem is you dont have enough room for the weitch to go back to the off state (i can demonstrate this in a video if needed)
we just need homing bump distance to be a setting

**Comment by Fabrizio3** [comment]
thanks! ill try to manually implement it, as its not on my config file for some reason

[stepper_x]
step_pin: PD7
dir_pin: PC5
enable_pin: !PD6
step_distance: .01
endstop_pin: ^!PC2
position_endstop: -30
position_max: 220
position_min: -30
homing_speed: 80

ill add 
homing_retract_dist: 6.0
and see if it works

**Comment by jakep82** [comment]
It's not included in any of the standard config files.  It defaults to 5mm which works on the vast majority of printers, but it can be adjusted.  This should solve your problem.

**Comment by Fabrizio3** [comment]
it werks! thank you!! (now i can set my Z to 1mm too!
