### ISSUE TITLE
Question for Pressure Advance

### ISSUE THREAD

**Issue by AndyWo83** [KevinOConnor/klipper#1175]
Hello,
must I disable the retract in my slicer settings to find the correct parameters? 
In the documentation is nothing written about this. But I think the retract needs to be disabled for this test?
Thanks

**Comment by AndyWo83** [comment]
I have in all my slicer settings a "retract on layer change".
In my opinion this would change the result, or you have to ignore this position.

**Comment by numanair** [comment]
Without retraction you might get one extra-blobby corner. Either way you should ignore this corner.

**Comment by KevinOConnor** [comment]
As mentioned above, the pressure advance test described at https://github.com/KevinOConnor/klipper/blob/master/docs/Pressure_Advance.md is robust to a wide variety of typical slicer settings.  So, print with "typical defaults".  Normal retraction settings should not impact the test, but if you are concerned then disable retraction.

-Kevin
