### ISSUE TITLE
Screens

### ISSUE THREAD

**Issue by JamieAKing** [KevinOConnor/klipper#1176]
Me again, and again it’s a question (probably a stupid one) not an issue 
I bought a fysetc f6 v1.3 and bundled with it were the 2208 stepper drivers and a screen
I’ve been playing with Klipper and although the actual motors have not turned up yet I think everything is working as it should be host/firmware wise. (Even a custom fan with therm sense in the electronics enclosure) all that is left is the screen 
Here is the git page relating to the screen. 
https://github.com/FYSETC/FYSTLCD/blob/master/README.md

I can’t find anything in Klippers screen config that looks like it would line up with just using  rx,tx, Am I right to asssume this is not a supported screen?

**Comment by trevjonez** [comment]
looks like the screen runs its own MCU and pulls images from an sdcard. so it could be done, not sure how best to deal with it. would be nice if the lcd could be attached directly to the host via usb so no load was placed on the F6 mcu though. you can already stress the 2560 enough will all the hookups the f6 provides.

so no support as of yet but not impossible to add by someone with the bandwidth to do the work.

**Comment by JamieAKing** [comment]
Thank you for the reply @trevjonez I shall put the screen in a box and put it in a safe place. So quite possibly the last I shall ever see of it. 
Presumably it would be easy enough to break out a usb cable and solder the connections directly to the pads on the screen allowing the host to do the heavy lifting.
I’m afraid the software side of it is very far beyond my understanding let alone within my skill set so unless someone is bored and looking for something to do, I will be more than content to just use the octoprint interface

**Comment by KevinOConnor** [comment]
I'm unsure what display you've received, but it doesn't sound like it is supported.  FYI, might be similar to the display discussed in #853.

-Kevin

**Comment by m24andrew** [comment]
https://slideplayer.com/slide/3380059/

**Comment by m24andrew** [comment]
I too bought the Fysetc F6 board and it came with this screen.  It is the same screen they put in the Wanhao Duplicators and the screen runs DWIN_OS.
I have searched and found some info but it's all a bit too technical for me...

[https://bleughbleugh.wordpress.com/2018/07/10/wanhao-duplicator-9-d9-technical-stuff/](url)

https://slideplayer.com/slide/3380059/

I'm in the same position as JamieAKing...it will stay in its box unless someone figures out how to use it with Klipper.

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it appears the original question has been answered (screen not supported).

-Kevin
