### ISSUE TITLE
Feature Request: Multiple Configuration Files

### ISSUE THREAD

**Issue by dushyantahuja** [KevinOConnor/klipper#1179]
Hi,

I change my nozzle sizes on a fairly regular basis - and have to then change the config files every time - new PID settings, new nozzle size, Z offset, etc. 

Is there a way to have multiple config files and then use a command to use a separate config file?

**Comment by theopensourcerer** [comment]
This is kind of discussed as a request in #1145. 

It seems like a few peeps would appreciate something here.

**Comment by JamieAKing** [comment]
FYI there is a octo Klipper plug-in in Octoptint that allows editing the config file from within octoprint.
I know it’s not the solution you are looking for but may help in the short term

**Comment by LazaroFilm** [comment]
Couldn’t you have multiple config files and ju rename them to activate/deactivate them?

**Comment by dushyantahuja** [comment]
That's what I'm doing now

**Comment by trevjonez** [comment]
another good way to do it is to use a symbolic link and keep your config files inside of a git repo with any name you like. alternatively you can modify the klippy launch arguments to looks some place other than `~/printer.cfg`. I keep mine here: https://github.com/trevjonez/i3-mk3-config probably need to rename the repo as something more generic as there is slowly more than just my i3-mk3 in there.

**Comment by KevinOConnor** [comment]
This issue looks like a dup of #1145.

-Kevin

**Comment by KevinOConnor** [comment]
Ah, okay.  FYI, there is some info on the klippy start parameters here: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#can-i-run-multiple-instances-of-klipper-on-the-same-host-machine

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to mark this issue as inactive as it doesn't look like it is currently being worked on.

-Kevin

**Comment by markwinger** [comment]
My request is slightly different.  I have 2 configs, one for printing on my ender 3, the other for using the ender 3 as a pen plotter.  To switch, I need to ssh in, and copy the desired config to printer.cfg, the back in clipper restart.  It;s easy enough but it is easy to mess up when copying files around.  A nice solution would be to go to the terminal in octoprint and type "restart plotter.cfg" or "restart ender3.cfg".  Or is something like this already implemented?

**Comment by JohnEdwa** [comment]
With the support for includes in the config file (https://github.com/KevinOConnor/klipper/pull/1359), the OctoKlipper plugin can then be used to modify the config through octoprint and you can add the two there, uncommenting whichever you want to use.

On a related note, could you share how exactly you are using Klipper as a plotter? I didn't manage to find a way to do it without having Arc support (G2 & G3) ?

**Comment by markwinger** [comment]
Modifying config files, even tho it is simple does not seem like that 'user friendly' of a solution, but that is just my opinion.

I had some trouble using it as a plotter.  I used this as a pen carrier: https://www.thingiverse.com/thing:2822264https://www.thingiverse.com/thing:2822264

I tried using inkscape to create gcode but it used arcs and klipper does not seem to support them.

I used design spark mechanical to create stl files but it has very poor support of text so I ended up using the free version of sketchup with installed the stl plug in.  Set text to a height of .2 and exported the stl file.  Then sliced with cura.  I set temps to 0, line widths to try match the pen (sharpie extra fine).  Layer height to .2 so I only  print 1 layer.

In clipper I had to change min_extrude_temp to 0, max_extrude_cross_section to 20.  Then set the z_offset higher so the pen has room.  I am printing on objects above the bed (flat surface) so I use a bltouch to set the height, then issue g1 z.5, to set the pen slightly above the object.  Then adjust the pen to just touch the surface, and print.  The z.5 may vary based on now much pressure is needed on the pen. 

Still working on it.

**Comment by JohnEdwa** [comment]
So for a proper plotter functionality, Klipper would need support for [G2/G3](http://marlinfw.org/docs/gcode/G002-G003.html) Arcs, and the [M302](http://marlinfw.org/docs/gcode/M302.html) cold extrusion setup which would also remove the need for modifying `max_extrude_cross_section` (though I think you should do by changing the `nozzle_diameter` instead).
The Z-change can already be done with `SET_GCODE_OFFSET`.

The biggest issue is the lack of Arc support to be honest. Without it, using Klipper as a plotter is really hacky and ugly.

**Comment by KevinOConnor** [comment]
FYI, if you don't have an extruder, then don't define an [extruder] config section.

If someone wishes to add an "extras" module that defines G2/G3, then that's fine.

-Kevin

**Comment by markwinger** [comment]
Oh.  Thanks.

**Comment by markwinger** [comment]
I commented out the extruder section and I get an error "No option 'sensor_type' in section: 'extruder'".
