### ISSUE TITLE
Adjust z height

### ISSUE THREAD

**Issue by forerunnert** [KevinOConnor/klipper#1181]
Hello, 
I want to adjust the z height of my delta printer 0.05mm down to dual in the first layer. 
What is the intended location to enter this offset? Preferably it should be persistent between prints.

**Comment by megablue** [comment]
if i understood you correctly, 
you can use `SET_GCODE_OFFSET Z=-0.05` to dive closer to the bed, the offset will persistent between prints until you restart the controller board or the klipper service.  just add this on your startup gcode.

**Comment by cmock** [comment]
alternatively, what I do is

<pre>
[homing_override]
gcode:
  G28
  SET_GCODE_OFFSET Z=.0.05
</pre>

**Comment by forerunnert** [comment]
That's what I needed exactly. I found SET_GCODE_OFFSET in the docs but there is no mention of persistence over restart though so I thought I was looking at the wrong parameter.
I expected a configfile parameter.
Thanks!

**Comment by Magoo0876** [comment]
What about the idea to tune the probes z offset? This would be persistent and no mod on the Gcode is needed.

**Comment by KevinOConnor** [comment]
I'm closing this as I believe the original question was answered (use SET_GCODE_OFFSET).

-Kevin

**Comment by KevinOConnor** [comment]
FYI, the new Bed_Level document describes how one can apply the SET_GCODE_OFFSET in a print start g-code macro: https://github.com/KevinOConnor/klipper/blob/master/docs/Bed_Level.md

-Kevin
