### ISSUE TITLE
Display current GCODE Z OFFSET

### ISSUE THREAD

**Issue by LazaroFilm** [KevinOConnor/klipper#1182]
Hi,
Is there a way to display the current z offset? I have a couple of macros button that I use to step the nozzle to the right height of my probe moves or if I change the nozzle. But I often lose count of how many times I clicked. Would love something like DISPLAY_GCODE_OFFSET command.

**Comment by JohnEdwa** [comment]
GET_POSITION replies back with a bunch of stuff, `gcode base: X:0.000000 Y:0.000000 Z:-0.050000 E:34.000000` tells you the offsets.

**Comment by KevinOConnor** [comment]
I'm closing this as I think the original question was answered.

-Kevin
