### ISSUE TITLE
BLTouch new configuration

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#1187]
How do I use the new configuration for bltouch replacing this:

[servo bltouch]
pin: ar4
maximum_servo_angle: 180
minimum_pulse_width: 0.0006
maximum_pulse_width: 0.0024
initial_angle: 90

[probe]
pin: ar18
speed: 3.0
x_offset: 35
y_offset: 0
#z_offset: 1.65
z_offset: 2.50
activate_gcode: 
	SET_SERVO SERVO=bltouch ANGLE=10
	SET_SERVO SERVO=bltouch ANGLE=60
	G4 P100
deactivate_gcode: 
	SET_SERVO SERVO=bltouch ANGLE=90

[homing_override]
set_position_z: 0
axes: z
gcode:
	G90
	G1 Z10 F800
	SET_SERVO SERVO=bltouch ANGLE=160
	G28 X0 Y0
	SET_SERVO SERVO=bltouch ANGLE=90
	G1 X75 Y110 F6000     ;X=110-x_offset
	G28 Z0
	G1 Z15

**Comment by BlackStump** [comment]
you replace your [servo bltouch] and [probe] with the new 
[bltouch]
sensor_pin: ar18
control_pin: ar4
x_offset: 35
y_offset: 0
z_offset: 2,5
speed: 3.0

the homing override just take out the SET_SERVO lines

https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L46

**Comment by rmcbc** [comment]
I try that before, now I find out that I didn't have latest version of software.
Because mine is a clone I have to put like this:

[bltouch]
sensor_pin: ar18
control_pin: ar4
x_offset: 35
y_offset: 0
z_offset: 2.5
speed: 3.0
**pin_up_reports_not_triggered: False
pin_up_touch_mode_reports_triggered: False**

[homing_override]
set_position_z: 0
axes: z
gcode:
	G90
	G1 Z10 F800
	G28 X0 Y0
	G1 X75 Y110 F6000     ;X=110-x_offset
	G28 Z0
	G1 Z15

Thanks.

**Comment by rmcbc** [comment]
Solved.
