### ISSUE TITLE
I2C stm32f1 supported ?

### ISSUE THREAD

**Issue by ShohninDmitriy** [KevinOConnor/klipper#1188]
What are pins used for the I2c port on the STM32F103C8 
preferably I2C 2 as it does not use the PWM ports

**Comment by KevinOConnor** [comment]
The i2c support has not been implemented on the STM32F103.

-Kevin

**Comment by ShohninDmitriy** [comment]
And it is possible to correct it somehow and to make support of I2C .just programming is not strong and to the stm32f103c8t6 wanted to use a clipper graphic screen SSD1306

**Comment by ShohninDmitriy** [comment]
Kevin could you please add I2C support to the STM32F103 port ?

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive as it doesn't look like it is currently being worked on.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, basic i2c support was added for the stm32 series (commit 078d2786).

-Kevin
