### ISSUE TITLE
Clear M117?

### ISSUE THREAD

**Issue by wormiedk** [KevinOConnor/klipper#1192]
Is it possible to clear the display or configure a timeout in the firmware? As soon as I issue a M117 command I never get the current position of the printer in the display again untill I reboot the printer.

**Comment by KevinOConnor** [comment]
Just run an `M117` command by itself to clear the message.

-Kevin

**Comment by shaiss** [comment]
@KevinOConnor could some simple code logic be added around lines 222 of https://github.com/KevinOConnor/klipper/blob/b260eb916863aa2dc1e632bdd164ee67c4675c68/klippy/extras/display/display.py to only hold the msg for ~5sec?
