### ISSUE TITLE
MKS GEN L and ender 4 stock display

### ISSUE THREAD

**Issue by bensen-666** [KevinOConnor/klipper#1200]
The logfile will not.help, because there is no error. I want to use stock 7920 ender 3 display. But it didnt work. The pinout from the mks ramps 1.3 board seems wrong. With a full graphics display it works. 

When i comment the original 7920 i dont see anything. When i put the cable 180° turned the display background lights. But is see nothin. The display is clear from signs..

**Comment by Magoo0876** [comment]
I'm using the stock display from the ender 3 type 12864. The connector at the display has to go to exp3, on the GEN L to EXP1 and the stock cable must be turned round. My settings are: 

[display]
lcd_type: st7920
cs_pin: ar27
sclk_pin: ar25
sid_pin: ar29
encoder_pins: ^ar23, ^ar17
click_pin: ^!ar35

**Comment by bensen-666** [comment]
Oh shit! I'm very dumb... I mean ENDER-4, not Ender 3 thats another display in Ender-4... Its smaller....in height.

**Comment by Magoo0876** [comment]
It is difficult to support you if you don't know what you are using. Maybe the pictures below can help. The 12864 LCD uses the st7920 as controller. I still recommend to check with a Terminal if the Printer Is ready. If there is a small other thing you will never see more than the backlight. 


The 2004 has 20 columns 4 rows. 
![unknown-2](https://user-images.githubusercontent.com/47366735/52363571-47f62580-2a43-11e9-8fde-1904472ddfec.jpeg)

ST7920 128x64 dots. 
![tb2xax3nvxxxxcoxpxxxxxxxxxx_ 737283681](https://user-images.githubusercontent.com/47366735/52363607-5ba18c00-2a43-11e9-8cc0-546b73f8ede5.jpg)

**Comment by bensen-666** [comment]
![img_20190207_044825](https://user-images.githubusercontent.com/26736343/52389459-ead69000-2a93-11e9-9ecd-5a909d241df8.jpg)

So i took a picture. Left display works, when i comment it in printer.cfg original display right is from ender 4 with 4 rows. I cant bring it to work

**Comment by KevinOConnor** [comment]
In order for us to assist, you'll need to attach the klipper log file from - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by bensen-666** [comment]
I hope thats what you need

[klippy.log](https://github.com/KevinOConnor/klipper/files/2846420/klippy.log)

**Comment by bensen-666** [comment]
With this preferences i see following on my ender-4 2004 display....
![img_20190208_194530](https://user-images.githubusercontent.com/26736343/52498892-588cd400-2bda-11e9-8656-97f5cb3f1629.jpg)

**Comment by Magoo0876** [comment]
I'm sorry but I do not have such a display to support you better. Fortunately there is already an issue to face this problem.  #1198 
Maybe you can use the other display in the meanwhile if you really need one.

**Comment by bensen-666** [comment]
I thank you for your time Magoo0876..... I read other issues to get an information...... But Kevin don't seem to know why it doesn't work... I checked the link..... But there is no solution

**Comment by bensen-666** [comment]
![img_20190209_171839](https://user-images.githubusercontent.com/26736343/52523354-ce537700-2c90-11e9-9231-1bd450aee7d2.jpg)

Now i have some funny things on my display 😀

**Comment by bensen-666** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2849116/klippy.log)

Is this an Failure of translation of the ISO and UTF standarts??

**Comment by KevinOConnor** [comment]
As with issue #1198, I don't know what would cause the above.  Best suggestion would be to verify wiring and pin definitions.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this in favour of the existing issue #1198.

-Kevin

**Comment by provistapp** [comment]
Kevin,
I have the same problem, never solved.
Please advise model LCD to buy that will work with MKS GEN L V1.0 and config in Marlin,
Thanks
