### ISSUE TITLE
Fysetc F6 config example for the Reprap LCD is wrong

### ISSUE THREAD

**Issue by nandinho84** [KevinOConnor/klipper#1206]
If anyone s strugling to make the Reprap Full Graphics LCD working on the Fysetc F6, here is the solution:
1st - flip around the connectors
2nd - change the config file to look like this:

[display]
lcd_type: st7920
cs_pin: PH1
sclk_pin: PA1
sid_pin: PH0
encoder_pins: ^PC6, ^PC4
click_pin: ^!PC2
[static_digital_output beeper]
pins: !PC0

**Comment by KevinOConnor** [comment]
Okay, I made the change (commit 6c10e4bc).

-Kevin
