### ISSUE TITLE
TMC2130 & UC1701 issue

### ISSUE THREAD

**Issue by blondak** [KevinOConnor/klipper#1208]
There is issue while usign TMC2130 & UC1701 on same MCU,
they both using SPI bus, but in initialization they use diffrent SPI speed, workaround is set 
spi_speed: 4000000 in every tmc2130 and display sections

[tmc2130 stepper_x]
spi_speed: 4000000
...

[tmc2130 stepper_y]
spi_speed: 4000000
...

[tmc2130 stepper_z]
spi_speed: 4000000
...

[display]
spi_speed: 4000000
...

My idea is, if bus can be edited on one place like
[spi default]
spi_speed: 4000000

[spi spi_bus_0]
spi_speed: 4000000

[display]
bus: spi_bus_0 (otherwise using default)

**Comment by KevinOConnor** [comment]
It's not clear to me what you are reporting.  If you've seen an error of some kind, then please the error you observed.  Also, we'll need the klipper log attached - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md
