### ISSUE TITLE
Display glitches after updating Klipper

### ISSUE THREAD

**Issue by FeuerVogel666** [KevinOConnor/klipper#1219]
Yesterday I have updated Klipper, so the Part on the Raspberry and the part on the Arduino.
I have an Ender3 and a Ramps setup wich is soldered to 24Volt with a Converter.

After a restart evrything looks fine and as espected, but after a little time it shifts the Layers around and gets more and mor unusable.
That goes on, till there are only these big fat Rings, on the screen.

![20190209_004004 1](https://user-images.githubusercontent.com/10796922/52519148-6af92300-2c57-11e9-9e77-a54ae48a1db2.jpg)
![20190209_004006 1](https://user-images.githubusercontent.com/10796922/52519154-78161200-2c57-11e9-96e1-b430f730dc66.jpg)
![20190209_094348 1](https://user-images.githubusercontent.com/10796922/52519160-87955b00-2c57-11e9-8b9d-d2ebca79a95e.jpg)

**Comment by KevinOConnor** [comment]
In order for us to assist, you will need to attach the klipper log file - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by FeuerVogel666** [comment]
I would post the log file, but there isnt any. I´ve searched for klippy.log and found nothing, even there is no Folder named tmp.
Do I have to aktivate logging?

**Comment by FeuerVogel666** [comment]
Thanks, I have found it.
I have figured out, that the problem with the display starts, when the printer is starting with the probing of the bed.
In Atachment my log File.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2882379/klippy.log)

**Comment by FeuerVogel666** [comment]
The Problem still exists. Yesterday i made a complete rebuild from the Printer (moved the electronics to a new Case and had a broken SD Card from the Raspberry Pi. So I made a clean reinstall.
And the Display still makes this Problem. Also I havent any Probe anymore, but a normal z-Endstopswitch.
Its a Stock Ender 3, except the MKS Gen L.
In Atatchment Below the new log.
[klippy.log](https://github.com/KevinOConnor/klipper/files/5882685/klippy.log)
