### ISSUE TITLE
Display not work after update

### ISSUE THREAD

**Issue by semos2k** [KevinOConnor/klipper#1224]
I have updated to the latest version of klipper and my screen has stopped working.
I did tests with two boards mks sbase and skr in both I obtained the same result.

![image](https://user-images.githubusercontent.com/23361212/52534093-17e0a800-2d0b-11e9-8a9d-abb0c813e984.png)

[klippy.log](https://github.com/KevinOConnor/klipper/files/2848884/klippy.log)

**Comment by KevinOConnor** [comment]
Odd.  We haven't made any changes to the display code recently.  There was some recent optimizations made to the lpc176x code though.

There are a couple of things you could try to trouble shoot this.  First is to go to a prior version of the code, reflash the micro-controller, and see if it fixes the problem:
cd ~/klipper ; git checkout c171b28a0b ; make clean ; sudo service klipper stop ; make flash ; sudo service klipper start

The second thing you could do is to see if increasing ST7920_CMD_DELAY and/or ST7920_SYNC_DELAY at the top of ~/klipper/klippy/extras/display/st7920.py fixes the issue.  (Be sure to run `sudo service klipper restart` after any code change.)

-Kevin

**Comment by semos2k** [comment]
@KevinOConnor when checkout the revision [c171b28] worked again. 

thx.

**Comment by semos2k** [comment]
Fixed on last revision.

thx.
