### ISSUE TITLE
Need help with bltouch setup

### ISSUE THREAD

**Issue by CharlesStArnault** [KevinOConnor/klipper#1229]
While setting up bltouch in my config file, I ran in a problem. I get this error message in octoprint

Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Unable to translate pin name: config_end_stop oid=14 pin=z_virtual_endstop pull_up=0 stepper_count=1

I've attached my config. Please help me!
[configBLTOUCH.txt](https://github.com/KevinOConnor/klipper/files/2849565/configBLTOUCH.txt)

**Comment by CharlesStArnault** [comment]
I forgot to mention, but I have an mks 1.4 board

**Comment by BlackStump** [comment]
try change your entry in stepper_z
from this
endstop_pin: z_virtual_endstop
to 
endstop_pin: probe:z_virtual_endstop

https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L49
