### ISSUE TITLE
MCU 'mcu' shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by ArdentSquirrel** [KevinOConnor/klipper#1233]
I am using two MCU's on a Piper 2 CoreXY with 4 Z Motors.  When using dual extruders and slicing with Cura, the MCU reliably shuts down within the first 4 layers.  If I slice with Slic3r, it does not happen as often, so I think it might be related to the speed, and maybe I am overcommitting my MCU's

I have my Extruder/X/Y motors driven with DRV8825 drivers configured for 1/32 microsteps.  The Z motors are driven with A4988 Drivers at 1/16 microsteps, and are on a separate MCU (Both MCUs are AtMega2560)

[klippy.timerinpast.log](https://github.com/KevinOConnor/klipper/files/2851860/klippy.timerinpast.log)

**Comment by FHeilmann** [comment]
your error is definitely due to too many steps being requested. Quad-Z can quickly overwhelm an 8-Bit MCU and 1/32 microstepping on XY in a CoreXY configuration will also put a lot of strain on the XYE microcontroller. One easy way to check is generating the loadgraph (either manually or by using the octoklipper plugin).

**Comment by KevinOConnor** [comment]
Although the step rates are high, what caused the excessive steps in this failure was extruder movement.  Something requested an extremely fast move of the extruder (extruder moving at ~4000mm/s).  That overloaded the extruder motor.  Unfortunately, the suspicious request did not get logged.  I suspect this is another symptom of the fade problem raised in issue #1234.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this in favour of #1234.

-Kevin
