### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [KevinOConnor/klipper#1245]
I would like to point out that identifiers like “[`_DECL_COMMAND`](https://github.com/KevinOConnor/klipper/blob/75f870994722cf2340d8bc39c0600ca592dadc7a/src/command.h#L10 "Update candidate")” and “[`__STEPPER_H`](https://github.com/KevinOConnor/klipper/blob/a38437f378ece33cb762b482120be629c78d3540/src/stepper.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by KevinOConnor** [comment]
This isn't a priority for me.

-Kevin
