### ISSUE TITLE
Unable to PID Tune

### ISSUE THREAD

**Issue by Joshj5hawk** [KevinOConnor/klipper#1253]
Good Morning all,
I am having issues trying to PID tune my extruder. M303 is not recognized which I see has been replaced with PID_CALIBRATE HEATER=<config_name> TARGET=<temperature> Which I've also tried, but I can't seem to find my heater number? I've tried 0, 1, E0, E1, T0, T1 and I've run out of things to try lol. Klippy.log zip file attached.

Thank you!
[klippy.zip](https://github.com/KevinOConnor/klipper/files/2864420/klippy.zip)

**Comment by Hywelmartin** [comment]
try
PID_CALIBRATE HEATER=extruder TARGET=215  
PID_CALIBRATE HEATER=heater_bed TARGET=60

**Comment by Joshj5hawk** [comment]
There I go over complicating things again ha. Thanks a bunch!
