### ISSUE TITLE
Servo support for BLTouch

### ISSUE THREAD

**Issue by RickMcConney** [KevinOConnor/klipper#128]
Has anyone figured out a way to get a BLTouch probe working as the Z end stop. I can home X and Y then move to the center of the bed but I need to deploy the probe before I can home Z. If the Servo Gcode (M280) was supported I think I could then deploy the probe and have it act as a normal end stop.

**Comment by KevinOConnor** [comment]
On Tue, Jan 16, 2018 at 02:19:55PM -0800, RickMcConney wrote:
> Has anyone figured out a way to get a BLTouch probe working as the Z end stop. I can home X and Y then move to the center of the bed but I need to deploy the probe before I can home Z. If the Servo Gcode (M280) was supported I think I could then deploy the probe and have it act as a normal end stop.

This looks similar to issue #46.  See the config/example-extras.cfg
file for information on manipulating servos.

-Kevin

**Comment by RickMcConney** [comment]
Thanks. I see from issue #46 that there is another issue after using the servo to deploy the probe. The BLtouch will stay triggered after it is hit and a backoff is performed. Which seems to cause the home to fail with the error in #46. Is there a work around for this.

**Comment by KevinOConnor** [comment]
Closing this in favor of the existing issue #46.
