### ISSUE TITLE
Metro m4 config

### ISSUE THREAD

**Issue by jimmyhorns** [KevinOConnor/klipper#1283]
I am struggling to work out how to use this with a metro m4 microcomtoller board. I’m aware that I am likely to need to build my own ramps type board, however I couldn’t see an example config file for this board to start working out the pin outs.

Am I missing something?...

Thanks in advance

**Comment by jakep82** [comment]
As you noted, you will need to design a controller board.  The design of the board would determine the pins.  You would then need to create your own config file with pins that match the board.

**Comment by FHeilmann** [comment]
the support for the samd51 is still in super early stages. Most of the things don't work properly yet, thats why there is no documentation of any sort.

**Comment by jimmyhorns** [comment]
Ah right - I thought this might be the case. I shall stick with my mkr sbase for now then and try and get this working first of all :)

Thanks for your help

**Comment by supermerill** [comment]
for the board, you can try with a cnc shield. You may not have enough output for everything (heaters, thermistors), so maybe a little ramps as a second mcu is needed.

**Comment by KevinOConnor** [comment]
There is still ongoing work with the SAMD51 line of chips.  However, it should be possible to launch a 3d printer with it.  One can use config/example.cfg as a starting point - just be sure to use the appropriate pin names (PA0-31, PB0-31, etc.).  Which pins to place in the config file depends on which pins one used to wire the printer.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this - as far as I know it should be possible to wire up a board with the metro-m4.

-Kevin
