### ISSUE TITLE
Could the PROBE command 

### ISSUE THREAD

**Issue by teikjoon** [KevinOConnor/klipper#1284]
Hello,

Was using the PROBE command while I was adjusting the bed spring thumbwheels, but was unable to run PROBE repeatedly without first raising the nozzle until the probe no longer triggered (using a capacitive probe).

Would it be possible for PROBE to raise the nozzle slightly before probing (i.e. what it does for G28)

Thanks.

**Comment by jakep82** [comment]
I use a gcode macro to do this. I think that's the best way to accomplish what you want.

**Comment by teikjoon** [comment]
@jakep82 okay thanks. I guess a macro would be ok
