### ISSUE TITLE
Unable to open config file /home/pi/printer.cfg

### ISSUE THREAD

**Issue by raoulfa** [KevinOConnor/klipper#1285]
Hi,

I just flashed Klipper on my A10m and now getting following error when trying to connect: Unable to open config file /home/pi/printer.cfg

I can connect to the printer but this error message will stay.

I took a look into the directory and the config file definitely is existing. Hope you have some good ideas since I actually can't find the tmp directory and a log file yet

**Comment by Hywelmartin** [comment]
The tmp folder is
/tmp
The klipper config is in
/home/pi
![bild](https://user-images.githubusercontent.com/33714214/53033516-7b887500-3471-11e9-90aa-59d86d45fe58.png)
