### ISSUE TITLE
Recv: !! Endstop x still triggered after retract -- Even after unplugging the endstop?

### ISSUE THREAD

**Issue by recuso** [KevinOConnor/klipper#129]
I had been waiting for a part but got back to my klippy-running maker select v2 (melzi board). It had previously been running well, but now when I try to print or home the X/y, it "jumps" a tiny bit away from the end and says:

Recv: !! Endstop x still triggered after retract

This is even after I unplug the endstop miroswitch all together or depress it. How should I go about trying to figure out what part is going on? I'e done a reboot of everything.

Here is my klippy.log:

Start printer at Wed Jan 17 07:56:53 2018 (1516175813.9 876.4)
===== Config file =====
[stepper_x]
step_pin = PD7
dir_pin = PC5
enable_pin = !PD6
step_distance = .0125
endstop_pin = ^!PC2
position_endstop = 0
position_max = 200
homing_speed = 50

[stepper_y]
step_pin = PC6
dir_pin = PC7
enable_pin = !PD6
step_distance = .0125
endstop_pin = ^!PC3
position_endstop = 0
position_max = 200
homing_speed = 50

[stepper_z]
step_pin = PB3
dir_pin = !PB2
enable_pin = !PA5
step_distance = 0.0025
endstop_pin = ^!PC4
position_endstop = 0.5
position_max = 200

[extruder]
step_pin = PB1
dir_pin = !PB0
enable_pin = !PD6
step_distance = .010
nozzle_diameter = 0.400
filament_diameter = 1.750
heater_pin = PD5
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PA7
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
min_temp = 0
max_temp = 250

[heater_bed]
heater_pin = PD4
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PA6
control = watermark
min_temp = 0
max_temp = 130

[fan]
pin = PB4

[mcu]
serial = /dev/ttyUSB0
baud = 115200

[printer]
kinematics = cartesian
max_velocity = 300
max_accel = 3000
max_z_velocity = 5
max_z_accel = 100

=======================
Starting serial connect
Loaded 51 commands (v0.5.0-56-g1bdebea-20171228_075725-octopi / gcc: (GCC) 4.8.1                                                                                                              binutils: (GNU Binutils) 2.24)
MCU config: ADC_MAX=1023 PWM_MAX=255 CLOCK_FREQ=16000000 SOFT_PWM_MAX=256 SERIAL                                                                                                             _BAUD=115200 MCU=atmega1284p STATS_SUMSQ_BASE=256
Sending MCU 'mcu' printer configuration...
Configured MCU 'mcu' (1024 moves)
Stats 879.0: gcodein=5 print_time=2.693 buffer_time=0.249 print_stall=0 mcu: mcu                                                                                                             _awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=806 byte                                                                                                             s_read=2560 bytes_retransmit=0 bytes_invalid=0 send_seq=101 receive_seq=99 retra                                                                                                             nsmit_seq=0 srtt=0.011 rttvar=0.005 rto=0.031 ready_bytes=0 stalled_bytes=0 freq                                                                                                             =15994984
Stats 880.0: gcodein=5 print_time=2.693 buffer_time=0.000 print_stall=0 mcu: mcu                                                                                                             _awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=812 byte                                                                                                             s_read=2625 bytes_retransmit=0 bytes_invalid=0 send_seq=102 receive_seq=102 retr                                                                                                             ansmit_seq=0 srtt=0.011 rttvar=0.004 rto=0.029 ready_bytes=0 stalled_bytes=0 fre                                                                                                             q=15994241
Stats 881.0: gcodein=10 print_time=2.693 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=818 byt                                                                                                             es_read=2732 bytes_retransmit=0 bytes_invalid=0 send_seq=103 receive_seq=103 ret                                                                                                             ransmit_seq=0 srtt=0.010 rttvar=0.005 rto=0.032 ready_bytes=0 stalled_bytes=0 fr                                                                                                             eq=15994143
Stats 882.0: gcodein=28 print_time=5.606 buffer_time=0.160 print_stall=0 mcu: mc                                                                                                             u_awake=0.023 mcu_task_avg=0.000146 mcu_task_stddev=0.000559 bytes_write=949 byt                                                                                                             es_read=2856 bytes_retransmit=0 bytes_invalid=0 send_seq=107 receive_seq=107 ret                                                                                                             ransmit_seq=0 srtt=0.011 rttvar=0.005 rto=0.031 ready_bytes=0 stalled_bytes=0 fr                                                                                                             eq=15994124
Endstop x still triggered after retract
Stats 883.0: gcodein=28 print_time=6.637 buffer_time=0.191 print_stall=0 mcu: mc                                                                                                             u_awake=0.023 mcu_task_avg=0.000146 mcu_task_stddev=0.000559 bytes_write=1172 by                                                                                                             tes_read=3033 bytes_retransmit=0 bytes_invalid=0 send_seq=115 receive_seq=115 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.031 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994088
Endstop x still triggered after retract
Stats 884.0: gcodein=46 print_time=7.835 buffer_time=0.389 print_stall=0 mcu: mc                                                                                                             u_awake=0.023 mcu_task_avg=0.000146 mcu_task_stddev=0.000559 bytes_write=1508 by                                                                                                             tes_read=3221 bytes_retransmit=0 bytes_invalid=0 send_seq=125 receive_seq=125 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.029 ready_bytes=7 stalled_bytes=0 f                                                                                                             req=15994086
Stats 885.0: gcodein=64 print_time=8.385 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.023 mcu_task_avg=0.000146 mcu_task_stddev=0.000559 bytes_write=1853 by                                                                                                             tes_read=3401 bytes_retransmit=0 bytes_invalid=0 send_seq=136 receive_seq=136 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.003 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994084
Endstop x still triggered after retract
Stats 886.0: gcodein=69 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.023 mcu_task_avg=0.000146 mcu_task_stddev=0.000559 bytes_write=1879 by                                                                                                             tes_read=3518 bytes_retransmit=0 bytes_invalid=0 send_seq=139 receive_seq=139 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994088
Stats 887.0: gcodein=69 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.015 mcu_task_avg=0.000108 mcu_task_stddev=0.000125 bytes_write=1885 by                                                                                                             tes_read=3640 bytes_retransmit=0 bytes_invalid=0 send_seq=140 receive_seq=140 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.003 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994097
Stats 888.0: gcodein=69 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.015 mcu_task_avg=0.000108 mcu_task_stddev=0.000125 bytes_write=1891 by                                                                                                             tes_read=3734 bytes_retransmit=0 bytes_invalid=0 send_seq=141 receive_seq=141 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.029 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994105
Stats 889.0: gcodein=69 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.015 mcu_task_avg=0.000108 mcu_task_stddev=0.000125 bytes_write=1897 by                                                                                                             tes_read=3842 bytes_retransmit=0 bytes_invalid=0 send_seq=142 receive_seq=142 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994119
Stats 890.0: gcodein=69 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.015 mcu_task_avg=0.000108 mcu_task_stddev=0.000125 bytes_write=1903 by                                                                                                             tes_read=3957 bytes_retransmit=0 bytes_invalid=0 send_seq=143 receive_seq=143 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994129
Stats 891.0: gcodein=74 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.015 mcu_task_avg=0.000108 mcu_task_stddev=0.000125 bytes_write=1909 by                                                                                                             tes_read=4058 bytes_retransmit=0 bytes_invalid=0 send_seq=144 receive_seq=144 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994126
Stats 892.0: gcodein=74 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000067 mcu_task_stddev=0.000058 bytes_write=1915 by                                                                                                             tes_read=4186 bytes_retransmit=0 bytes_invalid=0 send_seq=145 receive_seq=145 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994123
Stats 893.0: gcodein=74 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000067 mcu_task_stddev=0.000058 bytes_write=1921 by                                                                                                             tes_read=4301 bytes_retransmit=0 bytes_invalid=0 send_seq=146 receive_seq=146 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994128
Stats 894.0: gcodein=74 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000067 mcu_task_stddev=0.000058 bytes_write=1927 by                                                                                                             tes_read=4402 bytes_retransmit=0 bytes_invalid=0 send_seq=147 receive_seq=147 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994132
Stats 895.0: gcodein=74 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000067 mcu_task_stddev=0.000058 bytes_write=1933 by                                                                                                             tes_read=4531 bytes_retransmit=0 bytes_invalid=0 send_seq=148 receive_seq=148 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994129
Stats 896.0: gcodein=79 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000067 mcu_task_stddev=0.000058 bytes_write=1939 by                                                                                                             tes_read=4632 bytes_retransmit=0 bytes_invalid=0 send_seq=149 receive_seq=149 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994127
Stats 897.0: gcodein=79 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1945 by                                                                                                             tes_read=4746 bytes_retransmit=0 bytes_invalid=0 send_seq=150 receive_seq=150 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994125
Stats 898.0: gcodein=79 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1951 by                                                                                                             tes_read=4861 bytes_retransmit=0 bytes_invalid=0 send_seq=151 receive_seq=151 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994124
Stats 899.0: gcodein=79 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1957 by                                                                                                             tes_read=4976 bytes_retransmit=0 bytes_invalid=0 send_seq=152 receive_seq=152 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994124
Stats 900.0: gcodein=79 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1963 by                                                                                                             tes_read=5077 bytes_retransmit=0 bytes_invalid=0 send_seq=153 receive_seq=153 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994123
Stats 901.0: gcodein=84 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1969 by                                                                                                             tes_read=5192 bytes_retransmit=0 bytes_invalid=0 send_seq=154 receive_seq=154 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994124
Stats 902.0: gcodein=84 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1975 by                                                                                                             tes_read=5320 bytes_retransmit=0 bytes_invalid=0 send_seq=155 receive_seq=155 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994125
Stats 903.0: gcodein=84 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1981 by                                                                                                             tes_read=5421 bytes_retransmit=0 bytes_invalid=0 send_seq=156 receive_seq=156 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994124
Stats 904.1: gcodein=84 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1987 by                                                                                                             tes_read=5550 bytes_retransmit=0 bytes_invalid=0 send_seq=157 receive_seq=157 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994121
Stats 905.1: gcodein=84 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1993 by                                                                                                             tes_read=5651 bytes_retransmit=0 bytes_invalid=0 send_seq=158 receive_seq=158 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994121
Stats 906.1: gcodein=89 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=1999 by                                                                                                             tes_read=5752 bytes_retransmit=0 bytes_invalid=0 send_seq=159 receive_seq=159 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994121
Stats 907.1: gcodein=89 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000061 bytes_write=2005 by                                                                                                             tes_read=5894 bytes_retransmit=0 bytes_invalid=0 send_seq=160 receive_seq=160 re                                                                                                             transmit_seq=0 srtt=0.008 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994121
Stats 908.1: gcodein=89 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000061 bytes_write=2011 by                                                                                                             tes_read=5995 bytes_retransmit=0 bytes_invalid=0 send_seq=161 receive_seq=161 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994122
Stats 909.1: gcodein=89 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000061 bytes_write=2017 by                                                                                                             tes_read=6096 bytes_retransmit=0 bytes_invalid=0 send_seq=162 receive_seq=162 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.005 rto=0.030 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994122
Stats 910.1: gcodein=89 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000061 bytes_write=2023 by                                                                                                             tes_read=6225 bytes_retransmit=0 bytes_invalid=0 send_seq=163 receive_seq=163 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994122
Stats 911.1: gcodein=94 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000061 bytes_write=2029 by                                                                                                             tes_read=6326 bytes_retransmit=0 bytes_invalid=0 send_seq=164 receive_seq=164 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994122
Stats 912.1: gcodein=94 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000059 bytes_write=2035 by                                                                                                             tes_read=6440 bytes_retransmit=0 bytes_invalid=0 send_seq=165 receive_seq=165 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994125
Stats 913.1: gcodein=94 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000059 bytes_write=2041 by                                                                                                             tes_read=6569 bytes_retransmit=0 bytes_invalid=0 send_seq=166 receive_seq=166 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994126
Stats 914.1: gcodein=94 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000059 bytes_write=2047 by                                                                                                             tes_read=6670 bytes_retransmit=0 bytes_invalid=0 send_seq=167 receive_seq=167 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994128
Stats 915.1: gcodein=94 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000059 bytes_write=2053 by                                                                                                             tes_read=6771 bytes_retransmit=0 bytes_invalid=0 send_seq=168 receive_seq=168 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994130
Stats 916.1: gcodein=99 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000059 bytes_write=2059 by                                                                                                             tes_read=6900 bytes_retransmit=0 bytes_invalid=0 send_seq=169 receive_seq=169 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.003 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994130
Stats 917.1: gcodein=99 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2065 by                                                                                                             tes_read=7014 bytes_retransmit=0 bytes_invalid=0 send_seq=170 receive_seq=170 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994129
Stats 918.1: gcodein=99 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2071 by                                                                                                             tes_read=7115 bytes_retransmit=0 bytes_invalid=0 send_seq=171 receive_seq=171 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994129
Stats 919.1: gcodein=99 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2077 by                                                                                                             tes_read=7244 bytes_retransmit=0 bytes_invalid=0 send_seq=172 receive_seq=172 re                                                                                                             transmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994128
Stats 920.1: gcodein=99 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: mc                                                                                                             u_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2083 by                                                                                                             tes_read=7345 bytes_retransmit=0 bytes_invalid=0 send_seq=173 receive_seq=173 re                                                                                                             transmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0 f                                                                                                             req=15994127
Stats 921.1: gcodein=104 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2089 b                                                                                                             ytes_read=7446 bytes_retransmit=0 bytes_invalid=0 send_seq=174 receive_seq=174 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994126
Stats 922.1: gcodein=104 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=2095 b                                                                                                             ytes_read=7588 bytes_retransmit=0 bytes_invalid=0 send_seq=175 receive_seq=175 r                                                                                                             etransmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994126
Stats 923.1: gcodein=104 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=2101 b                                                                                                             ytes_read=7689 bytes_retransmit=0 bytes_invalid=0 send_seq=176 receive_seq=176 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994126
Stats 924.1: gcodein=104 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=2107 b                                                                                                             ytes_read=7790 bytes_retransmit=0 bytes_invalid=0 send_seq=177 receive_seq=177 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994126
Stats 925.1: gcodein=104 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=2113 b                                                                                                             ytes_read=7919 bytes_retransmit=0 bytes_invalid=0 send_seq=178 receive_seq=178 r                                                                                                             etransmit_seq=0 srtt=0.010 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994127
Stats 926.1: gcodein=109 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000061 bytes_write=2119 b                                                                                                             ytes_read=8020 bytes_retransmit=0 bytes_invalid=0 send_seq=179 receive_seq=179 r                                                                                                             etransmit_seq=0 srtt=0.010 rttvar=0.005 rto=0.028 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 927.1: gcodein=109 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2125 b                                                                                                             ytes_read=8134 bytes_retransmit=0 bytes_invalid=0 send_seq=180 receive_seq=180 r                                                                                                             etransmit_seq=0 srtt=0.010 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994127
Stats 928.1: gcodein=109 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2131 b                                                                                                             ytes_read=8263 bytes_retransmit=0 bytes_invalid=0 send_seq=181 receive_seq=181 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.029 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994127
Stats 929.1: gcodein=109 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2137 b                                                                                                             ytes_read=8364 bytes_retransmit=0 bytes_invalid=0 send_seq=182 receive_seq=182 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 930.1: gcodein=109 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2143 b                                                                                                             ytes_read=8465 bytes_retransmit=0 bytes_invalid=0 send_seq=183 receive_seq=183 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 931.1: gcodein=114 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000070 mcu_task_stddev=0.000059 bytes_write=2149 b                                                                                                             ytes_read=8594 bytes_retransmit=0 bytes_invalid=0 send_seq=184 receive_seq=184 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.005 rto=0.027 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 932.1: gcodein=114 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000060 bytes_write=2155 b                                                                                                             ytes_read=8708 bytes_retransmit=0 bytes_invalid=0 send_seq=185 receive_seq=185 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 933.1: gcodein=114 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000060 bytes_write=2161 b                                                                                                             ytes_read=8809 bytes_retransmit=0 bytes_invalid=0 send_seq=186 receive_seq=186 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994128
Stats 934.1: gcodein=114 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000060 bytes_write=2167 b                                                                                                             ytes_read=8938 bytes_retransmit=0 bytes_invalid=0 send_seq=187 receive_seq=187 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.026 ready_bytes=0 stalled_bytes=0                                                                                                              freq=15994130
Stats 935.1: gcodein=114 print_time=8.930 buffer_time=0.000 print_stall=0 mcu: m                                                                                                             cu_awake=0.006 mcu_task_avg=0.000071 mcu_task_stddev=0.000060 bytes_write=2173 b                                                                                                             ytes_read=9039 bytes_retransmit=0 bytes_invalid=0 send_seq=188 receive_seq=188 r                                                                                                             etransmit_seq=0 srtt=0.009 rttvar=0.004 rto=0.025 ready_bytes=0 stalled_bytes=0

**Comment by BlackStump** [comment]
I would check wiring! As a test remove your X endstop wires from the board end, you eluded that it was working but was waiting on part , was the part anyway related to the X endstop or involved messing with the wiring ?

**Comment by recuso** [comment]
Ah, I've unplugged both from the board itself and I still get: Recv: !! Endstop x still triggered after retract

The part wasn't related to the endstop itself but it was swapping out my extruder end. So yes, there was wiring on the extruder side. I didn't touch the endstop microswitch wire since the mounting wasn't changed.

I'll try to grab my big ole fluke 8025b from the garage, thank you for the thoughts/direction. I'm not sure how I might be able to check the board itself, though, now that I know the switches aren't at "fault" (as I said, it still says X triggered after unplugging the wires from the board itself).

**Comment by cmock** [comment]
I would first try to exclude a hardware problem -- flash your previous firmware and check whether the endstops (still unconnected) show up as open or triggered with M119. If they show up as triggered, you can be pretty sure you have a hardware problem.

If not, it's a software problem...

**Comment by recuso** [comment]
Curious! Well, BOTH X and Y are interpreted as always triggered right now. I was able to home it by using the "Z" microstop pin for all 3 and manually triggering it -- just to see what was up.

Cmock: Thank you, that's a good suggestion and kind of where my mind was going. Problem: I don't have the original firmware. I looked around online and have found a couple of files, but nothing that purports to be the original maker select firmware for sure. If I flashed something compatible or similar (say, for the wanhao di3 which is the same machine) but the pins are different I'm kind of back to square one on figuring out what pins are what -- with two pins already potentially broken. Yuck.

It seems like my only option might be to just flash some sort of arduino program onto it and see if I can read the inputs on those pins? I'm sorry that my particular understanding in this respect is a bit limited, but it seems like that'd be a safe-ish route to go. After confirming it's good or bad, re-flash klippy.

I'm using a Melzi (hybrid 1.0) type board  -- maker select v2 http://reprap.org/wiki/Melzi

Time to do a bit of digging it seems

**Comment by cmock** [comment]
Right, arduino would be the way to go in this case. Start with the "DigitalInputPullup" example and change the port number. As the endstops are inverted, it should report "1" for a disconnected or untriggered switch, and "0" for a triggered switch.
