### ISSUE TITLE
Problem with GLPI

### ISSUE THREAD

**Issue by skazznj** [KevinOConnor/klipper#1298]
Hello, I'm trying to update GLPI and wamp and import the data from the old GLPI into the new one. I downloaded wap and set it up, on phpMyadmin I created a database in which I imported the old data then I try to install GLPI by updating the database (which contains the old data) however when I want to update I have this message 
Mise à jour
Connexion à la base de données réussie

La version de la base de données semble correcte (5.7.24) - Parfait !La version de la base de données semble correcte (5.7.24) - Parfait !
Mise à jour en 9.3.2

Changement de la structure de la base de données - glpi_states (0 seconde)
PHP User Warning: Table glpi_states does not exists in C:\wamp64ajours\www\glpi\inc\dbmysql.class.php at line 704
PHP User Warning: Table glpi_states does not exists in C:\wamp64ajours\www\glpi\inc\dbmysql.class.php at line 704
PHP User Warning: Table glpi_states does not exists in C:\wamp64ajours\www\glpi\inc\dbutils.class.php at line 457
PHP User Warning: Table glpi_states does not exists in C:\wamp64ajours\www\glpi\inc\dbutils.class.php at line 457
9.3.2 multiple alter in glpi_states - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_states` ADD `is_visible_enclosure` TINYINT(1) NOT NULL DEFAULT '1' AFTER `is_visible_rack` , ADD `is_visible_pdu` TINYINT(1) NOT NULL DEFAULT '1' AFTER `is_visible_enclosure` , ADD INDEX `is_visible_enclosure` (`is_visible_enclosure`) , ADD INDEX `is_visible_pdu` (`is_visible_pdu`) - L'erreur est La table 'glpi.glpi_states' n'existe pas 

Help plz

**Comment by manu7irl** [comment]
wrong place mate...

**Comment by KevinOConnor** [comment]
This issue appears to have been opened in the wrong github repository.
