### ISSUE TITLE
unable to seek file (vsd)

### ISSUE THREAD

**Issue by maxcom99** [KevinOConnor/klipper#1308]
klipper log:
010 rttvar=0.004 rto=0.027 ready_bytes=0 stalled_bytes=0 freq=15999986 heater_bed: target=0 temp=32.2 pwm=0.000  print_time=3.285 buffer_time=0.000 print_stall=0 extruder: target=0 temp=30.9 pwm=0.000
Starting SD card print (position 0)
virtual_sdcard seek
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/virtual_sdcard.py", line 138, in work_handler
    self.current_file.seek(self.file_position)
AttributeError: 'NoneType' object has no attribute 'seek'
Unable to seek file

running latest master reinstalled everything, no dice

Additional log:
Send: M24
Recv: ok
Recv: !! Unable to seek file
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Unable to seek file
[...]
Send: M22
Recv: // Unknown command:"M22"
Recv: ok

Unable to "eject" the SD card as well. It was previously initialized and working. Reloading the UI allows to run initialize again but no files are created on the virtual SD card.

Send: M21
Recv: SD card ok
Send: M20
Recv: ok
Recv: Begin file list
Recv: End file list
Recv: ok

directories:

pi@octopi:~/.octoprint $ ls -al uploads/
total 6064
drwxr-xr-x  2 pi pi    4096 Feb 23 17:35 .
drwxr-xr-x 14 pi pi    4096 Feb 23 17:19 ..
-rw-------  1 pi pi 5792356 Feb 23 17:26 10mm_Bearing_20190223-172148.gcode
-rw-r--r--  1 pi pi   19616 Feb 23 17:35 .metadata.json
-rw-------  1 pi pi  383108 Feb 23 17:35 xyzCalibration_cube_ABS.gcode
pi@octopi:~/.octoprint $ ls -al virtualSd/
total 8
drwxr-xr-x  2 pi pi 4096 Feb 23 17:32 .
drwxr-xr-x 14 pi pi 4096 Feb 23 17:19 ..
pi@octopi:~/.octoprint $ ls -al
total 84
drwxr-xr-x 14 pi pi  4096 Feb 23 17:19 .
drwxr-xr-x 26 pi pi 12288 Feb 23 17:03 ..
-rw-r--r--  1 pi pi 14099 Feb 23 16:38 config.yaml
drwxr-xr-x  8 pi pi  4096 Feb 23 17:38 data
drwxr-xr-x  4 pi pi  4096 Feb 23 17:32 generated
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 logs
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 plugins
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 printerProfiles
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 scripts
drwxr-xr-x  4 pi pi  4096 Feb 23 17:32 slicingProfiles
drwxr-xr-x  3 pi pi  4096 Feb 23 17:32 timelapse
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 translations
drwxr-xr-x  2 pi pi  4096 Feb 23 17:35 uploads
-rw-------  1 pi pi   219 May 20  2018 users.yaml
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 virtualSd
drwxr-xr-x  2 pi pi  4096 Feb 23 17:32 watched

**Comment by KevinOConnor** [comment]
In order for us to assist you must attach the Klipper log file from the event - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by maxcom99** [comment]
@KevinOConnor I included the log at the top or are there more relevant sections that I missed and you want to see the whole thing?

**Comment by KevinOConnor** [comment]
I'm closing this pending the full log file attached to this issue as described above.

-Kevin
