### ISSUE TITLE
Klipper problem on Bigtreetech SKR V1.1

### ISSUE THREAD

**Issue by patoune08** [KevinOConnor/klipper#1309]
Hello,
I have a Bigtreetech SKR V1.1 board.
I installed octoprint and klipper but I can not connect octoprint to the printer.
Here is the octoprint terminal file.
Thanks for your help
[octo.log](https://github.com/KevinOConnor/klipper/files/2898175/octo.log)

**Comment by patoune08** [comment]
Here is a serial connection monitoring file.
[serial.log](https://github.com/KevinOConnor/klipper/files/2898190/serial.log)

**Comment by BlackStump** [comment]
The docs hold a wealth of info and for support you need to read this and supply the log mentioned.
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by patoune08** [comment]
Hello
I had read, but the problem is that I can not issue the command M112 since I can not connect to the printer. that's why I sent you these two files.
I would just like to know how to connect with this board.
Thank you

**Comment by BlackStump** [comment]
Have you read and followed the make flash info at the top of config here ?
https://github.com/KevinOConnor/klipper/blob/master/config/generic-bigtreetech-skr-v1.1.cfg

Ok I can understand you can not issue a M112 command from Octoprint but have you looked for the log file? /tmp/klippy.log  as per the instructions?

**Comment by FHeilmann** [comment]
you need to connect to /tmp/printer with octoprint, not to the MCU serial port directly.

**Comment by Skorpi08** [comment]
Does it only work via USB or UART?

**Comment by FHeilmann** [comment]
according to the sources you can configure UART0 instead of USB

**Comment by Skorpi08** [comment]
I have try it, TX to RX and RX to TX. without success

**Comment by FHeilmann** [comment]
you need to configure it during the `make menuconfig` step. Disable USB serial, then the code will switch over to the uart.

**Comment by patoune08** [comment]
A last post to say thank you, for now it seems to work but I think my board is dead.
I have high temperature indications on all three probes (between 170 and 180 ° C) while everything is cold.
Thanks again.
