### ISSUE TITLE
[Feature request] Set Max speed while printing 

### ISSUE THREAD

**Issue by hevilp** [KevinOConnor/klipper#1310]
Hi, 

We are able to set the printing speed for actions while printing. When I rise or decrease it, all speeds are affected (perimeter, infill, etc) 
Example
Decrease from 100 to 50%
100 mm/s - 50 mm/s
40 mm/s - 20 mm/s

Would be nice to set the maximum speed while printing. For example maxspeed to 50 mm/s

100 mm/s - 50 mm/s
40 mm/s - 40 mm/s

So I can put my printer in a quiet Mode easily.... 

Thanks

**Comment by timauton** [comment]
SET_VELOCITY_LIMIT VELOCITY=<whatever>

**Comment by hevilp** [comment]
Oh Thanks

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the original question was answered.

-Kevin
