### ISSUE TITLE
Use Socat to link /tmp/printer to a virtual serial port

### ISSUE THREAD

**Issue by andrea7376** [KevinOConnor/klipper#132]
Hi,
I'm not very familiar with linux but I would like test klipper with other software that support only real serial port.
Is it possible to use Socat to link /tmp/printer to a virtual serial port ?
How can I do?
Thank you.
Andrea

**Comment by andrea7376** [comment]
I tested something like that: sudo socat -d -d pty,/tmp/printer,raw,echo=0 pty,link=/dev/ttyS0,raw,echo=0
but doesn't seem to work.

**Comment by cmock** [comment]
How is your software determining what a "real serial port" is? Because /tmp/printer is a symlkink to a pseudoterminal (/dev/pts/N), so AFAIK it should accept all relevant ioctls.

If it is about filenames, just symlink /dev/pts/N to whatever path your software is happy with.

**Comment by KevinOConnor** [comment]
As noted - Klipper already produces a "virtual serial port" and /tmp/printer is a link to that port.  If you're having a problem with some software communicating with Klipper, please open an issue describing that problem (along with the klippy.log file for it).
