### ISSUE TITLE
Color Mixing Config

### ISSUE THREAD

**Issue by RobMink** [KevinOConnor/klipper#134]
I am having trouble configuring Kilpper for the diamond 3-1 print head.  After an update, it is complaining that I am using the same analog pin for all three extruders.  If I remove the offending line it says I have no sensor.  
[klippy.log](https://github.com/KevinOConnor/klipper/files/1649569/klippy.log)

[printerwith3extruders.cfg.txt](https://github.com/KevinOConnor/klipper/files/1649570/printerwith3extruders.cfg.txt)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/1649571/printer.cfg.txt)

I am sure I am just doing something wrong.  Thanks for reading this.

Note that the log items in question are at the very end.  I updated kipper because I was having a hard time getting prints to start.

**Comment by RobMink** [comment]
Wow, you are awsome!  Thanks!

**Comment by RobMink** [comment]
Tested - Fixed

**Comment by KevinOConnor** [comment]
Great!  I committed this to the master branch (commit 09eec37).
