### ISSUE TITLE
3dtouch tronxy x5s

### ISSUE THREAD

**Issue by jstankowski88** [KevinOConnor/klipper#1361]
I have a stock tronxy x5s and would like to add a geeetech 3dtouch probe to it. I'm struggling because I can't seem to find what the pin numbers are because the tronxy x5s board seems largely undocumented. I have a pin 27 breakout board I was trying to use, I also thought about trying to use the miso pin.

**Comment by blackyarr** [comment]
https://www.thingiverse.com/thing:3439261

maybe this will help you a little

**Comment by jstankowski88** [comment]
Thank you for the link. I can't believe I missed that.

**Comment by jstankowski88** [comment]
Unfortunately still no luck, I think I gave it wired correctly but I still can't deploy the pin with the debug commands. Any suggestions would be greatly appreciated.

**Comment by KevinOConnor** [comment]
In order for us to assist the Klipper log file must be attached to this issue - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

Beyond that, the only other suggestions would be to look at the example config files in the config/ directory.

-Kevin
