### ISSUE TITLE
Error: Unable to parse option 'bed_radius' in section 'bed_mesh' for round bed

### ISSUE THREAD

**Issue by Zultanic** [KevinOConnor/klipper#1380]
Hi Kevin, I am getting errors when I try to set up mesh leveling with a round bed, klipper doesn't seem to recognize the options that are entered into the config file. You will see from the log that both bed_radius and round_probe_count are giving issues.
[log.zip](https://github.com/KevinOConnor/klipper/files/2950059/log.zip)

**Comment by KevinOConnor** [comment]
Double check your config file - you have a comment after the round_probe_count parameter that hasn't actually been commented out.

-Kevin

**Comment by Zultanic** [comment]
That was it! Brain fart, thank you very much.
