### ISSUE TITLE
STM32 - FW_RESTART fails

### ISSUE THREAD

**Issue by smark-** [KevinOConnor/klipper#1400]
Sometimes I can recover it by issuing a "RESTART" command afterwards, but in most of the cases the only solution is to power cycle the board. Ideas?
[klippy.log](https://github.com/KevinOConnor/klipper/files/2972842/klippy.log)

**Comment by jakep82** [comment]
Try changing the restart method.

https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L264

**Comment by smark-** [comment]
> Try changing the restart method.
> 
> https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L264

Yeeees!! Thank you very much! I kind of remembered I read about this option somewhere but I could not find it. Thank you very much for your support!
