### ISSUE TITLE
Top level menu won't stay displayed

### ISSUE THREAD

**Issue by w1ebr** [KevinOConnor/klipper#1411]
The top level menu that shows extruder temps won't stay displayed on the screen. It jumps to the next level of menu. When I select"main menu", it displays for about 1 second and then goes back to the next level of menu.

Has anyone seen this behavior?

[klippy.log](https://github.com/KevinOConnor/klipper/files/2981168/klippy.log)

**Comment by mbgroot** [comment]
I have the same problem. Did it work for you?

**Comment by w1ebr** [comment]
This behavior was because I didn't have the signal inversion state set up properly.
This is what I have now:
[display]
lcd_type = st7920
cs_pin = PD2
sclk_pin = PD3
sid_pin = PL7
encoder_pins = ^PB5, ^PB6
click_pin = ^!PL6

**Comment by w1ebr** [comment]
Yes, look at my post, I updated it with my solution. GeneOn Apr 24, 2019 11:57 AM, mbgroot <notifications@github.com> wrote:I have the same problem. Did it work for you?

**Comment by mbgroot** [comment]
Thank you! Thank you! I also solved the problem, but forgot to write :)
