### ISSUE TITLE
After "restart" wrong stepper movement (homing)

### ISSUE THREAD

**Issue by fhtagnn** [KevinOConnor/klipper#1417]
Tested repeatedly on a Voron with the latest master freshly pulled, fresh install per installation readme, both ramps freshly flashed. After service restart / boot (best tested with slow homing speeds): 

1. G28: printer homes as expected
2. Move to safe location (in may case x175 y175 z 150)
3. Issue a "restart" (say config changes)
4. G28: y moves forward instead of x right ultimately crashing the toolhead into the gantry front idlers
5. firmware_restart fixes the stepper movement 

Initially, my homing override started with a z move up. Stress tested my gantry due to front steppers moving up and back steppers moving down.

Addendum:

- Separate G28 X, G28 Y does not change anything
- G28 Y first leads to x move to the left instead of y move to the back
- Steppers z1 and z3 have inverted movement, z and z2 move as expected

[klippy.log](https://github.com/KevinOConnor/klipper/files/2985601/klippy.log)

**Comment by FHeilmann** [comment]
I also encountered this issue.

**Comment by shaiss** [comment]
I have the same issue, but only after I did a git pull to the latest version today. my config @ https://pastebin.com/uyCnygFZ

**Comment by KevinOConnor** [comment]
Thanks.  That's a bad error.  Fix is in commit d7665875.

-Kevin

**Comment by markwinger** [comment]
I am new to klipper(1 day).  I am seeing this problem.  How do I get this fix installed?

**Comment by theopensourcerer** [comment]
It's in the docs but basically something like this (from memory so please check):

cd klipper
sudo service klipper stop
git pull (If you are on the master branch - use git status to check)
make clean
make
make flash FLASH_DEVICE=[your-usb-device-name]
sudo service klipper start

**Comment by fhtagnn** [comment]
Tested the fix. All back to normal!

Thanks, Kevin

**Comment by markwinger** [comment]
Worked for me too.
