### ISSUE TITLE
back to back manual stepper move command to the same position will trigger an internal error

### ISSUE THREAD

**Issue by megablue** [KevinOConnor/klipper#1471]
say if you issued "MANUAL_STEPPER STEPPER=toolchanger SPEED=300 ACCEL=200 MOVE=-20" twice in row, it will trigger the !! Internal error on command:"MANUAL_STEPPER"

[klippy.log](https://github.com/KevinOConnor/klipper/files/3026252/klippy.log)

**Comment by KevinOConnor** [comment]
Thanks.  I think it should be fixed now (commit 60ff2e9d).

-Kevin

**Comment by megablue** [comment]
thanks!
