### ISSUE TITLE
Heater extruder not heating at expected rate

### ISSUE THREAD

**Issue by noxx2015** [KevinOConnor/klipper#1496]
Hello, 

cant heat my extruder. get this 
Heater extruder not heating at expected rate

[klippy.log](https://github.com/KevinOConnor/klipper/files/3044623/klippy.log)

**Comment by jakep82** [comment]
Your extruder isn't heating. Either your heater cartridge is bad, you have a wiring issue, your mosfet is bad, or you've configured the wrong heater_pin.

**Comment by KevinOConnor** [comment]
I'm going to close this as I think the original question was answered (the code is correctly reporting that the extruder is not heating - likely an error in the config).  See https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md for some steps to help diagnose.

-Kevin
