### ISSUE TITLE
pid_deriv_time error

### ISSUE THREAD

**Issue by MrMbss1** [KevinOConnor/klipper#1507]
I'm having issues getting my printer to work after attempting to update the Klipper firmware. I followed the FAQ guide on how to update it. After the update, it's giving me this error: "Option 'pid_deriv_time' is not valid in section 'heater_bed' Once the underlying issue is corrected, use the "RESTART" command to reload the config and restart the host software. Printer is halted". I've tried changing the value between 0 and 10 in the config, but the issue persists.

What am I doing wrong?

When I look through the directories through my SFTP client, it looks like there's 2 different installs of Klipper inside one another, but I may be wrong. See attached screenshot. 

[klippy.log](https://github.com/KevinOConnor/klipper/files/3050436/klippy.log)

![image](https://user-images.githubusercontent.com/38134829/55669135-10093400-5874-11e9-8712-3cfd50b7d43e.png)

![image](https://user-images.githubusercontent.com/38134829/55669315-05e83500-5876-11e9-8386-003d2dbec132.png)

**Comment by Hywelmartin** [comment]
Have you tried to remove the pid_deriv_time.

For all the valid settings have a look in example.cfg

**Comment by MrMbss1** [comment]
@Hywelmartin
It wasn't even included in the config file to begin with, I added it to try and change the value to see if it fixed it. Sorry for not including that in the main post.

I've tried setting it at 2, which is the default value in example.cfg, no change

**Comment by Hywelmartin** [comment]
But that setting is for [Temperature-triggered cooling fans](https://github.com/KevinOConnor/klipper/blob/8c54fc8753031cea6366901538dcb94ef3de5b8e/config/example-extras.cfg#L593)
You are maybe looking for[smooth_time: 2.0](https://github.com/KevinOConnor/klipper/blob/8c54fc8753031cea6366901538dcb94ef3de5b8e/config/example.cfg#L170)

**Comment by MrMbss1** [comment]
I'm not sure I understand what you mean, can you elaborate?

I've completely removed the pid_deriv_time from the heatbed section now, as it was originally, yet it still gives me the same error. See attached 
![image](https://user-images.githubusercontent.com/38134829/55671817-448ce800-5894-11e9-8060-97f8bb2e4734.png)
![image](https://user-images.githubusercontent.com/38134829/55671822-4b1b5f80-5894-11e9-9b4d-a4ce6d4322b1.png)

**Comment by ShohninDmitriy** [comment]
[heater_bed]
heater_pin: P2.5
max_power: 1.0
sensor_type: NTC 100K MGB18-104F39050L32
sensor_pin: P0.23
control: pid
pid_Kp: 107.845
pid_Ki: 4.085
pid_Kd: 711.780
**pwm_cycle_time: 0.035**  Here is this string forgotten
min_temp: 0
max_temp: 130

**Comment by MrMbss1** [comment]
@ShohninDmitriy
I don't recall ever including that string, but I may be wrong. I'll try including it when I get back home sometime tomorrow

**Comment by Hywelmartin** [comment]
When you updated, did you flash your controller board(s) as well?

**Comment by MrMbss1** [comment]
@Hywelmartin
Yes, I flashed the board after updating. Also yes, I've also tried restarting OctoPrint and reboot the entire system multiple times

**Comment by jakep82** [comment]
Are you sure you're editing the correct config file?

**Comment by MrMbss1** [comment]
@jakep82
I'm editing the one in pi/home. Should be the correct one, yes?

**Comment by jakep82** [comment]
If you removed the line and you're still getting the error, then you edited the wrong file. SSH into your pi and type `nano ~/printer.cfg`

See if the pid_deriv_time line is still there.

**Comment by MrMbss1** [comment]
@jakep82
That's exactly what I've been doing. The line is not there

**Comment by KevinOConnor** [comment]
It looks like you've got a corrupt installation somehow.  You can try backing up your printer.cfg file, running the `~/klipper/scripts/klipper-uninstall.sh` script, manually running the `rm` command that script reports, and then rerunning the full installation steps from the Installation document.  If that doesn't help, try a complete reinstall of the sd card with OctoPi.

Be aware that config sections in printer.cfg are not required to be together, so if there is something odd in the config file, you'll need to check the entire file for it.

-Kevin

**Comment by MrMbss1** [comment]
@KevinOConnor 
I did as you said, and now it works. A thousand times thank you.

**Comment by KevinOConnor** [comment]
Thanks.  I'm going to close this issue as it looks like the original issue was resolved.

-Kevin
