### ISSUE TITLE
Another 'timer too close' error

### ISSUE THREAD

**Issue by lucashpandolfo** [KevinOConnor/klipper#152]
As the title says, the printer stops with a 'timer too close' error.

Now, before anything else, I should mention 2 things:
1. It's not 3d printing. It's laser engraving. I've attached a laser driver to the fan output and control the laser with M106 and M107 (only on and off, no power control)
2. I modified fan.py to make FAN_MIN_TIME = 0.

If I run the file without the M106/M107 commands, the file 'prints' ok. But with those commands the print fails always at the same part.

I think the issue arises when too many pwm state changes are issued (at least for me and my poor understanding of klipper).

So, the thing is, this may not be a klipper bug as I'm using the fan output as something else, but is there a way to achieve what I'm trying to achieve here with klipper? (rapid fan on/off changes)

If not, is there something like a safe min time between pwm events? (less than the default 0.1 s)

Sorry for the inconvenience and thanks for your work.

![graph](https://user-images.githubusercontent.com/591607/35587564-ee173c1a-05dc-11e8-9d21-38dd1c0e7768.png)
[klippy_6.log](https://github.com/KevinOConnor/klipper/files/1679120/klippy_6.log)

**Comment by KevinOConnor** [comment]
On Tue, Jan 30, 2018 at 08:03:01PM +0000, Lucas wrote:
> As the title says, the printer stops with a 'timer too close' error.
[...]
> 2. I modified fan.py to make FAN_MIN_TIME = 0.

The FAN_MIN_TIME is specifically there to prevent "Timer too close"
errors - it can't be removed.  This issue seems similar to issue #133
- I'll answer your other questions there.

-Kevin
