### ISSUE TITLE
Question, not an issue.

### ISSUE THREAD

**Issue by JulioDavidMartinez** [KevinOConnor/klipper#1525]
I've installed an AC heated bed that comes with the NTC 10k 3950 thermistor.
How do I set this up correctly in firmware?
This is the heated bed I've installed:
https://www.amazon.com/gp/product/B07GJDL7XB/ref=oh_aui_search_asin_title?ie=UTF8&psc=1

I've attached my klippy log for the sake of the bot.
Thanks for any help.
[klippy.log](https://github.com/KevinOConnor/klipper/files/3066646/klippy.log)

**Comment by gdachs** [comment]
[heater_bed]
...
sensor_type: NTC 100K beta 3950

**Comment by JulioDavidMartinez** [comment]
Thank you so much!!!

**Comment by gdachs** [comment]
Wait a moment. I see only now that your heater uses a 10K Thermistor. That is very uncommon. My settings will not work with it. I have an AC heater too, but it uses a 100K thermistor.

**Comment by jakep82** [comment]
The Amazon link says 100k.

**Comment by JulioDavidMartinez** [comment]
The Amazon Link does say 100k. I made a typo. Sorry. However when I look online for that thermistor, oddly there are two versions. 100k and 10k. I'll assume that the Amazon link is the correct one.

Again thank you guys so much for all you do!!!!

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original issue has been resolved.

-Kevin
