### ISSUE TITLE
Homing sequence

### ISSUE THREAD

**Issue by mentaluproar** [KevinOConnor/klipper#156]
I looked at the homing overrides and either I'm not using them correctly or they aren't doing what I want.  My printer is set up so that it cannot home X until after it homes Y.  Z doesnt matter, but would be preferred to be last.

So if I send G28, I want home Y, then home X, home Z.
if I send G28 X Y, I want home Y, then home X.
if I send G28 Z Y, I want home Y, then home Z.

Basically, I want an order for homing and a dependancy. So if Y is in the list, it is always homed first.  I also want to be able to say "I can't home X all by itself, I need to home Y too."

**Comment by KevinOConnor** [comment]
On Wed, Jan 31, 2018 at 04:25:39PM -0800, mentaluproar wrote:
> I looked at the homing overrides and either I'm not using them correctly or they aren't doing what I want.

In the future, if Klipper doesn't do what you expect, please attach
the klippy.log file.

> My printer is set up so that it cannot home X until after it homes Y.  Z doesnt matter, but would be preferred to be last.

It sounds like you want:

[homing_override]
gcode:
    G28 Y0
    G28 X0
    G28 Z0

> So if I send G28, I want home Y, then home X, home Z.
> if I send G28 X Y, I want home Y, then home X.
> if I send G28 Z Y, I want home Y, then home Z.

The homing_override feature disables per-axis homing - any G28 will
home all three axes.

-Kevin
