### ISSUE TITLE
Internal error on command:"G29"

### ISSUE THREAD

**Issue by LSergM** [KevinOConnor/klipper#1563]
[klippy.log](https://github.com/KevinOConnor/klipper/files/3097778/klippy.log)
Hi. Could you help me to figure out with this issue.

**Comment by JohnEdwa** [comment]
Klipper doesn't have `G29`, you need to use [the extended G-code commands](https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md).

In this case, most likely `BED_MESH_CALIBRATE`.

**Comment by KevinOConnor** [comment]
The G29 was a macro in the config.  The underlying error is a "timeout with mcu" error - best advice we have is in the FAQ at - https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors .

Also, if this is a new setup, make sure the config checks described at https://www.klipper3d.org/Config_checks.html

-Kevin

**Comment by LSergM** [comment]
Thank you for fast feedback.
You can close this issue because when I moved all signals on one board instead of two this issue disappeared.

-Serhii.
