### ISSUE TITLE
Trigorilla board and TMC2208 drivers - issue with axes not moving smoothly

### ISSUE THREAD

**Issue by dragsterbox** [KevinOConnor/klipper#1570]
Dear all,

Since I upgraded to TMC2208 (FYSETC v1.2), I am having 2 issues that I cannot fix:

1. I never managed to get my axis moving smoothly. Same for homing
2. Stepper motors direction is reversed and despite I change dir_pin it in the firmware, there is no change

I have tried many different configuration with no success.

I will really appreciate if someone can help on this and/or give me documentation.

Attached, my config file and log.
[printer.txt](https://github.com/KevinOConnor/klipper/files/3100890/printer.txt)

[klippy.log](https://github.com/KevinOConnor/klipper/files/3100888/klippy.log)

![Jumper](https://user-images.githubusercontent.com/37857756/56465649-985e0c00-6412-11e9-8f43-62aa35c17565.jpg)

**Comment by StefanMeGit** [comment]
And what happend? Just closing this does not help other people? U screwed up something?

**Comment by dragsterbox** [comment]
Hi Stefan,

Please do not close it. I will update this post with my fix and config file tonight. I am sure that it will help people using Piezo probe system.

**Comment by dragsterbox** [comment]
Issue is closed
