### ISSUE TITLE
Move queue empty during virtual SD print

### ISSUE THREAD

**Issue by jakep82** [KevinOConnor/klipper#160]
I made several successful prints from SD, but this one stopped mid-print with the error below.  Currently running the virtual SD branch.  Log attached.

Recv: // MCU 'mcu' shutdown: Move queue empty
Recv: // Once the underlying issue is corrected, use the
Recv: // "FIRMWARE_RESTART" command to reset the firmware, reload the
Recv: // config, and restart the host software.
Recv: !! Printer is shutdown

[klippy.log](https://github.com/KevinOConnor/klipper/files/1692285/klippy.log)

**Comment by KevinOConnor** [comment]
On Sat, Feb 03, 2018 at 11:02:10PM +0000, jakep82 wrote:
> I made several successful prints from SD, but this one stopped mid-print with the error below.  Currently running the virtual SD branch.  Log attached.
> 
> Recv: // MCU 'mcu' shutdown: Move queue empty
> Recv: // Once the underlying issue is corrected, use the
> Recv: // "FIRMWARE_RESTART" command to reset the firmware, reload the
> Recv: // config, and restart the host software.
> Recv: !! Printer is shutdown

This doesn't appear to be related to the SD code.  Instead, it looks
like there was a large amount of jitter between the system clock and
the PRU clock (they do have different clock circuits).

It's reported in the log as a bunch of "Resetting prediction variance"
messages - the code is complaining that it can't make a good clock
prediction.  This is the first time I've seen this come up.

Was there anything in the Linux system logs around the time of the
event?  Perhaps NTP messages?

I have some ideas on how we could make the code more resilient to this
type of jitter, but I'll need to think about it a bit.

-Kevin

**Comment by jakep82** [comment]
The only thing I'm seeing is a little spam from rsyslogd-2007.  This is repeated at random intervals from 30 seconds to 20+ minutes.

Feb  3 21:32:27 beaglebone rsyslogd-2007: action 'action 17' suspended, next retry is Sat Feb  3 21:32:57 2018 [try http://www.rsyslog.com/e/2007 ]

**Comment by cmock** [comment]
That rsyslog message is not time related, see [here](https://blog.dantup.com/2016/04/removing-rsyslog-spam-on-raspberry-pi-raspbian-jessie/).

Are you running ntpd on your raspberry?

**Comment by jakep82** [comment]
I'm not knowledgeable enough to say for sure.  It's a fresh installation of the most recent Jessie IoT on a BeagleBone Black Wireless.  All I've installed is Klipper, Octoprint, and mjpg-streamer.

**Comment by jakep82** [comment]
I've made about half a dozen successful prints since this occurred with zero issues. I don't know what happened, and I've not been able to reproduce it.

**Comment by KevinOConnor** [comment]
On Sun, Feb 04, 2018 at 04:52:02PM -0800, jakep82 wrote:
> I've made about half a dozen successful prints since this occurred with zero issues. I don't know what happened, and I've not been able to reproduce it. 

Yeah, I'm not surprised it isn't reproducible, as it's a pretty
unusual timing issue (the host hardware clock drifts significantly
from the mcu hardware clock over a short time period).

FYI, I've pushed commit 08874b9c in response to the original issue.

-Kevin

**Comment by jakep82** [comment]
I'm going to go ahead and close this issue.  It appears to be a rare edge case that I can't reproduce, and you've likely addressed it in that commit.
