### ISSUE TITLE
MCU losing connection randomly

### ISSUE THREAD

**Issue by Ivzaitsev** [KevinOConnor/klipper#1628]
I'm experiencing random klipper 'connection lost'. It happens once or twice a month both during prints and while printer is stationary. 90% of the time my octoprint server(I'm using an OrangePi) hangs as well.
I've checked both power supplys, temperatures and overall hardware status, everything looks normal. Doesn't happen when using marlin, but marlin is inferior
[klippy.log](https://github.com/KevinOConnor/klipper/files/3169319/klippy.log)

**Comment by KevinOConnor** [comment]
The best advice we have for this is in the FAQ: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin
