### ISSUE TITLE
MCU timer too close

### ISSUE THREAD

**Issue by rlesac** [KevinOConnor/klipper#1659]
Got the error in the middle of the print.
Using SKR v1.3, Cura 3.6, BananaPi.

[klippy-mcu-2019-05-20.log](https://github.com/KevinOConnor/klipper/files/3197701/klippy-mcu-2019-05-20.log)

**Comment by KevinOConnor** [comment]
The log indicates that the host software thread that runs the PID did not get CPU time for over 400ms.  This resulted in a failure.

It looks like you've done a custom installation of the host software.  It's necessary to ensure other (unrelated) tasks on the machine aren't given higher priority, and it's necessary to ensure the machine has sufficient resources for basic responsiveness.

-Kevin
