### ISSUE TITLE
SKR Mini read negative temp values

### ISSUE THREAD

**Issue by semos2k** [KevinOConnor/klipper#1692]
I compile klipper for skr mini but when read temperature for E0 the value is negative.

[klippy.txt](https://github.com/KevinOConnor/klipper/files/3238722/klippy.txt)

**Comment by semos2k** [comment]
My error thx

**Comment by mboyer85** [comment]
@semos2k 
Hi,
I'm waiting for my SKR mini and you're the first to try klipper ...
The procedure is the same for SKR mini and SKR V1.3 (copy the firmware.bin to SD) or does it need  to be flashed via USB.
Which controller did you select (make menuconfig)?

How about to pull request your config to the repo, is it possible ?

Thanks
