### ISSUE TITLE
// Unknown command:"BED_MESH_CALIBRATE"

### ISSUE THREAD

**Issue by totalitarian** [KevinOConnor/klipper#1694]
For some reason all the bed mesh gcodes give me an error like so

// Unknown command:"BED_MESH_CALIBRATE"
[klippy.zip](https://github.com/KevinOConnor/klipper/files/3243910/klippy.zip)

**Comment by Hywelmartin** [comment]
because you don't have bed_mesh in your config...


[[bed_mesh]](https://github.com/KevinOConnor/klipper/blob/1a8bd750fcaaea6f27298d72d309a2fa3eccf3b3/config/example-extras.cfg#L143
)

**Comment by totalitarian** [comment]
Whoops, forgot to remove the #. Thanks!
