### ISSUE TITLE
Multiple MCU documentation

### ISSUE THREAD

**Issue by Coolaswa** [KevinOConnor/klipper#170]
In the current config there apperently needs to be a 'main' MCU which cannot have an alias. This took some time to find out. Pull request #157 tries to add a little documentation towards this but not sufficient in my view. If there is a reason for there to be a main MCU please add a little documentation towards this issue, otherwise perhaps allow it to also have an alias.

Regards,
Michiel

**Comment by KevinOConnor** [comment]
I added a multi-mcu example configuration file as part of commit 22d7e48.  Currently, all timing in the system is dependent on a single "main" mcu.  This is also described briefly in docs/Code_Overview.md.
