### ISSUE TITLE
Failed to home z: Timeout during endstop homing

### ISSUE THREAD

**Issue by EvilGremlin** [KevinOConnor/klipper#1703]
I have a optical Z probe with servo, but it cannot home if it needs to travel more than 5-10mm, it just stops midway. XY homes just fine. In the log i homed Z from zero height, then raised it 20mm and then homing failed. Klipper is from yesterday's master branch, Octoprint 1.3.11
[klippy.log](https://github.com/KevinOConnor/klipper/files/3256459/klippy.log)

**Comment by KevinOConnor** [comment]
Best guess is that the stepper_z step_distance is not accurate - make sure to run the checks at https://www.klipper3d.org/Config_checks.html .  It's also possible the Z stepper is losing steps - you may want to double check its wiring.

-Kevin

**Comment by EvilGremlin** [comment]
Nope, absolutely everything is fine. Marlin works, Klipper don't.

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by EvilGremlin** [comment]
Nope, it doesn't work with right settings, so i flashed back marlin for now.

**Comment by KevinOConnor** [comment]
Okay.  Lets close this issue then.

-Kevin
