### ISSUE TITLE
SKR 1.3 Stealthchop @ 12/24 Volt

### ISSUE THREAD

**Issue by Achim01** [KevinOConnor/klipper#1709]
Hello,

i have buy some Bigtreetech TMC2208 V2.1.

First try on a Ramps 1.4 @ 24Volt in StandAlone Mode, stealthchop sound was perfect.
Second try on a Bigtreetech SKR V1.3 @ 12Volt in UART Mode, stealthchop sound was perfect too.
Third try on a Bigtreetech SKR V1.3 @ 24Volt in UART Mode, stealthchop sounds like a DRV8825.

Motor is a Vexta PK series, 4 Volt 1,2 Ampere 1,8°

Is that a Problem with my config, the Motor, the Init, or what ever.

SKR V1.3 @ 12Volt:
Send: dump_tmc stepper=stepper_x
Recv: // ========== Write-only registers ==========
Recv: // IHOLD_IRUN: 00081108 IHOLD=8 IRUN=17 IHOLDDELAY=8
Recv: // TPWMTHRS:   00000010 TPWMTHRS=16
Recv: // TPOWERDOWN: 00000032 TPOWERDOWN=50
Recv: // ========== Queried registers ==========
Recv: // GCONF:      000001c0 pdn_disable=1 mstep_reg_select=1 multistep_filt=1
Recv: // GSTAT:      00000001 reset=1
Recv: // IFCNT:      00000006 IFCNT=6
Recv: // OTP_READ:   0000000c OTP_FCLKTRIM=12
Recv: // IOIN@TMC220x: 20000140 PDN_UART=1 SEL_A=1(TMC220x) VERSION=0x20
Recv: // FACTORY_CONF: 0000000c FCLKTRIM=12
Recv: // TSTEP:      000fffff TSTEP=1048575
Recv: // MSCNT:      00000238 MSCNT=568
Recv: // MSCURACT:   011701ac CUR_A=-84 CUR_B=-233
Recv: // CHOPCONF:   14010053 toff=3 hstrt=5 TBL=2 MRES=4(16usteps) intpol=1
Recv: // DRV_STATUS: c0080000 CS_ACTUAL=8 stealth=1 stst=1
Recv: // PWMCONF:    c80d0e24 PWM_OFS=36 PWM_GRAD=14 pwm_freq=1 pwm_autoscale=1 pwm_autograd=1 PWM_REG=8 PWM_LIM=12
Recv: // PWM_SCALE:  00300077 PWM_SCALE_SUM=119 PWM_SCALE_AUTO=48
Recv: // PWM_AUTO:   000e00ff PWM_OFS_AUTO=255 PWM_GRAD_AUTO=14
Recv: ok

SKR V1.3 @ 24Volt:
Send: dump_tmc stepper=stepper_x
Recv: // ========== Write-only registers ==========
Recv: // IHOLD_IRUN: 00081108 IHOLD=8 IRUN=17 IHOLDDELAY=8
Recv: // TPWMTHRS:   00000010 TPWMTHRS=16
Recv: // TPOWERDOWN: 00000032 TPOWERDOWN=50
Recv: // ========== Queried registers ==========
Recv: // GCONF:      000001c0 pdn_disable=1 mstep_reg_select=1 multistep_filt=1
Recv: // GSTAT:      00000001 reset=1
Recv: // IFCNT:      00000006 IFCNT=6
Recv: // OTP_READ:   0000000c OTP_FCLKTRIM=12
Recv: // IOIN@TMC220x: 20000140 PDN_UART=1 SEL_A=1(TMC220x) VERSION=0x20
Recv: // FACTORY_CONF: 0000000c FCLKTRIM=12
Recv: // TSTEP:      000fffff TSTEP=1048575
Recv: // MSCNT:      00000218 MSCNT=536
Recv: // MSCURACT:   010b01db CUR_A=-37 CUR_B=-245
Recv: // CHOPCONF:   14010053 toff=3 hstrt=5 TBL=2 MRES=4(16usteps) intpol=1
Recv: // DRV_STATUS: c0080000 CS_ACTUAL=8 stealth=1 stst=1
Recv: // PWMCONF:    c80d0e24 PWM_OFS=36 PWM_GRAD=14 pwm_freq=1 pwm_autoscale=1 pwm_autograd=1 PWM_REG=8 PWM_LIM=12
Recv: // PWM_SCALE:  00050033 PWM_SCALE_SUM=51 PWM_SCALE_AUTO=5
Recv: // PWM_AUTO:   000e00a7 PWM_OFS_AUTO=167 PWM_GRAD_AUTO=14
Recv: ok

both after Homing

I hope someone has an idea for this problem.
(sorry for the "Google" English)

Thanks
Joachim
[klippy.log](https://github.com/KevinOConnor/klipper/files/3263279/klippy.log)

**Comment by KevinOConnor** [comment]
It may be due to differences in the power supply.  When running the steppers at 24V, you should be able to significantly reduce the current without reducing the torque.  A lower current would mean less noise.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
