### ISSUE TITLE
Intersecting Infill over extrusion causing nozzle to drag with higher density infill ... Pressure Advance?

### ISSUE THREAD

**Issue by drphil3d** [KevinOConnor/klipper#1714]
I'm having an issue on multiple printers running the latest code where when printing a higher density triangular infill pattern 30% or higher there seems to be an issue with over extrusion where infill overlaps itself. I've adjusted my extruder steps, filament width and pressure advance but can't seem to fix this issue. 

Maybe we need a better model for tuning pressure advance. It's just really hard to tell if it's set right. Would something similar to Marlins linear advance test generator work?
http://marlinfw.org/docs/features/lin_advance.html

[klippy.log](https://github.com/KevinOConnor/klipper/files/3269029/klippy.log)

**Comment by KevinOConnor** [comment]
If you've calibrated the extruder steps, and are then seeing overlap, it sounds like a slicer issue.  Slic3r is really bad at that, for example.

As for tuning pressure advance, in my own testing I've had poor results with the Marlin method - slight changes in bed level can completely skew the results.  There has been some interest in changing to a "pressure advance tower" method - see PR #1243 for further info.

-Kevin

**Comment by Hywelmartin** [comment]
The crossings in that infill is 3 lines stacked ontop of each other/ layer 
you can set the infill line width in Print Settings/Advanced but I don't think that the result will be different 

![image](https://user-images.githubusercontent.com/33714214/59280247-91f74e00-8c65-11e9-9a5b-946bf774cf02.png)

**Comment by drphil3d** [comment]
I think I found the perfect model for PA tuning 
https://www.thingiverse.com/thing:2371069

**Comment by drphil3d** [comment]
@KevinOConnor I found this pressure advance calibration model and python script on thingiverse
https://www.thingiverse.com/thing:3442071/files

**Comment by theopensourcerer** [comment]
@drphil3d This one worked really well for me:

https://github.com/PrusaOwners/prusaowners/wiki/Pressure_Advance

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
