### ISSUE TITLE
Error doing a PID tune

### ISSUE THREAD

**Issue by PerLangkjaer** [KevinOConnor/klipper#1716]
Good morning all

Yesterday i changed from a V5 to a V6 all-metal hotend and wanted to do a new PID tune.
Now i got this message:

Recv: // Heater extruder not heating at expected rate
Recv: // See the 'verify_heater' section in config/example-extras.cfg
Recv: // for the parameters that control this check.
Recv: //

And as you can see it aborts in the 2nd cycle at 191-192 degres Celsius.
I have solid readings from the thermistor I think and the heater seems to heat up good.
Its the same heatblock, heater and thermistor i use.

![PID error](https://user-images.githubusercontent.com/35040883/59155025-94984e80-8a7f-11e9-8358-37d5237dd714.jpg)
[klippy.log](https://github.com/KevinOConnor/klipper/files/3269188/klippy.log)

**Comment by KevinOConnor** [comment]
You should upgrade to the latest version of Klipper - there has been several improvements to the verify_heater mechanism.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the original question was answered (upgrade the software).

-Kevin

**Comment by PerLangkjaer** [comment]
Hello and sorry Kevin
For not having updated at the matter.
It where not a straight forward update, it took me 2 evenings and a reinstall to solve the update thing.

It did not do the trick with an update, so I took the hotend apart again and applied a little thermal paste to the thermistor and that surely solved my problem.

I just need to give you a shout out for your amazing work :-)

Regards 
Per
