### ISSUE TITLE
Installation on STM32F103ZE 

### ISSUE THREAD

**Issue by patoune08** [KevinOConnor/klipper#1717]
Hello,
I come back with new for #1636 :
I attach the loader of my card if someone can do something because I really want to be able to install Klipper.
Thank you.
[loader_chuanxingyuan.zip](https://github.com/KevinOConnor/klipper/files/3269580/loader_chuanxingyuan.zip)

**Comment by KevinOConnor** [comment]
This looks like a dup of #1636.  Unfortunately, it doesn't seem like anyone has any information to help you with.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this in favour of the existing issue #1636.  Alas, it doesn't look like anyone has further information on this.

-Kevin
