### ISSUE TITLE
Arduino DUE shutdown when run FORCE_MOVE

### ISSUE THREAD

**Issue by semos2k** [KevinOConnor/klipper#1720]
I installed the latest version of klipper on an arduino DUE, when I run FORCE_MOVE klipper is shutdown
![image](https://user-images.githubusercontent.com/23361212/59161098-c7ecd480-8aa3-11e9-8054-7d644b561ff5.png)
 
[klippy-due.txt](https://github.com/KevinOConnor/klipper/files/3269699/klippy-due.txt)

**Comment by KevinOConnor** [comment]
The FORCE_MOVE command is a diagnostic and debugging command.  If you attempt to move at a high velocity without using acceleration (or use an acceleration higher than the printer was originally configured for) then it can cause the micro-controller to flag those moves as errors.  It's not something we plan to fix as we don't recommend using FORCE_MOVE for anything other than debugging purposes.

-Kevin

**Comment by semos2k** [comment]
hello kevin, I tried to make a home and I obtained the same result.

**Comment by KevinOConnor** [comment]
You'd need to attach the Klipper log file from that event in order for us to assist.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
