### ISSUE TITLE
Filament width sensor -> display diameter and flow rate in display (SSD1306)?

### ISSUE THREAD

**Issue by modmt** [KevinOConnor/klipper#1726]
Hello all,

I'm using the Tsl1401cl filament diameter sensor in combination with the SSD1306 display.

Is there any possibility to show the current filament diameter and the current (changed by the current diameter measured by the sensor) flow rate in this display?

In the display there is only the feed rate shown, but I can renounce of this if there is a possibility to show the flow rate instead of feed rate.

Thank you in adcance for your help.
Matthias

[klippy.log](https://github.com/KevinOConnor/klipper/files/3285820/klippy.log)

**Comment by KevinOConnor** [comment]
The menu code supports custom display code (see config/example-menu.cfg).  However, be aware that the menu code is currently undergoing changes to support "g-code templates".

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
