### ISSUE TITLE
OctoPrint "Configuration" tab not updated after SAVE_CONFIG

### ISSUE THREAD

**Issue by joshpainter** [KevinOConnor/klipper#1741]
After a BED_MESH_CALIBRATE or a PROBE_CALIBRATE or a PID_CALIBRATE and then a SAVE_CONFIG, the Klipper Configuration tab in the Octoprint plugin is not refreshed with the latest changes. If you restart OctoPrint, the new changes show up. I expected to see the latest version of that file in that tab after a SAVE_CONFIG but it appears that it might be cached? This caused confusion because I thought SAVE_CONFIG was not actually saving anything even though it was. Log attached because you asked so nice but dunno if it helps anything. :)

[klippy.log](https://github.com/KevinOConnor/klipper/files/3303809/klippy.log)

**Comment by theopensourcerer** [comment]
I would guess you should report this to the Octoklipper plugin not here:

https://github.com/mmone/OctoprintKlipperPlugin

**Comment by Hywelmartin** [comment]
A refresh of the page normally sorts things out..

**Comment by mental405** [comment]
> I would guess you should report this to the Octoklipper plugin not here:
> 
> https://github.com/mmone/OctoprintKlipperPlugin

Good luck with that. I don't think anyone has touched OctoKlipper in almost a year.

**Comment by theopensourcerer** [comment]
Correct - but there are some more active forks ;-)

**Comment by KevinOConnor** [comment]
FYI, as indicated, this is something that should be reported to OctoKlipper.

-Kevin
