### ISSUE TITLE
BLTouch offset in screws_tilt_adjust and bed_mesh

### ISSUE THREAD

**Issue by wormiedk** [KevinOConnor/klipper#1782]
[printer.txt](https://github.com/KevinOConnor/klipper/files/3355499/printer.txt)
[printer.txt](https://github.com/KevinOConnor/klipper/files/3355492/printer.txt)

I have a prusa clone with the following bltouch section:
[bltouch]
sensor_pin: ar18
control_pin: ar6
pin_move_time: 1
pin_up_reports_not_triggered: True
pin_up_touch_mode_reports_triggered: False
x_offset: 37
y_offset: 2
z_offset: 1.1
speed: 2

My bed is 200x200.

The instructions for bed_mesh states that I should specify the Nozzle position for min and max (see below). 
However if I do that my BLTouch moves outside the bed when trying to probe as the BLtouch is then as 200+37 which is outside the Bed.  I would expect the bed_mesh section to sutract the x an y offsets from the max and min points when probing.

Is the mesh corrected for the offset? Otherwise the mesh will be shifted 37,2 in my case. 

The same applies for the [screws_tilt_adjust] section in which I manually have to subtact the offsets from the probe positions.

EDIT: complete printer.cfg attached as printer.txt

```
#min_point:
#   Defines the minimum x,y position to probe when for rectangular
#   beds. Note that this refers to the nozzle position, take care that
#   you do not define a point that will move the probe off of the bed.
#   This parameter must be provided for rectangular beds.
#max_point:
#   Defines the maximum x,y position to probe when for rectangular
#   beds. Follow the same precautions as listed in min_point. Also note
#   that this does not necessarily define the last point probed, only
#   the maximum coordinate. This parameter must be provided.
```

**Comment by wormiedk** [comment]
`[printer]
kinematics: cartesian
max_velocity: 100
max_accel: 1200 #was 900
max_z_velocity: 20
max_z_accel: 100

[bltouch]
sensor_pin: ar18
control_pin: ar6
pin_move_time: 1
pin_up_reports_not_triggered: True
pin_up_touch_mode_reports_triggered: False
x_offset: 37
y_offset: 2
z_offset: 1.1
speed: 2

[mcu]
serial: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AC01SLRG-if00-port0
pin_map: arduino

[force_move]
enable_force_move: True

[virtual_sdcard]
path: ~/.octoprint/uploads/

[stepper_x]
step_pin: ar54
dir_pin: !ar55
enable_pin: !ar38
step_distance: .0025 #til 32 microsteps (1/800)
endstop_pin: ^ar3
#endstop_pin: ^ar2
position_endstop: 0
position_max: 200
homing_speed: 50

[tmc2208 stepper_x]
uart_pin: ar63
tx_pin: ar59
microsteps: 16
interpolate: false
run_current: 0.6
hold_current: 0.3
stealthchop_threshold: 0

[stepper_y]
step_pin: ar60
dir_pin: !ar61
enable_pin: !ar56
step_distance: .0025
endstop_pin: ^ar14
#endstop_pin: ^ar15
position_endstop: 0
position_max: 200
homing_speed: 50

[tmc2208 stepper_y]
uart_pin: ar40
tx_pin: ar64
microsteps: 16
interpolate: False
run_current: 0.7
hold_current: 0.3
stealthchop_threshold: 0

[stepper_z]
step_pin: ar46
dir_pin: !ar48
enable_pin: !ar62
step_distance: .0025
endstop_pin: probe:z_virtual_endstop
#endstop_pin: !ar18
#endstop_pin: ^ar19
#position_endstop: 0.5
position_min: -5
position_max: 200
homing_speed: 10

[homing_override]
gcode:
  INIT_TMC stepper=stepper_y
  INIT_TMC stepper=stepper_x
  INIT_TMC stepper=extruder
  G1 Z10 F1200
  G28 X0
  G28 Y0
  G1 Y30 F3000
  G28 Z0
  G1 Z20 X0 Y0 F1200
set_position_z: 0.0
axes: z




[extruder]
step_pin: ar26
dir_pin: !ar28
enable_pin: !ar24
step_distance:  .0012
#step_distance: .001195
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: ar10
sensor_type: ATC Semitec 104GT-2
sensor_pin: analog13
#control: pid
#pid_Kp: 25.09
#pid_Ki: 2.30
#pid_Kd: 68.45
min_temp: 0
max_temp: 280
pressure_advance: 0.15

[tmc2208 extruder]
uart_pin: ar65
tx_pin: ar66
microsteps: 16
interpolate: True
run_current: 0.7
hold_current: 0.25
stealthchop_threshold: 20

[heater_bed]
heater_pin: ar8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog14
#control: watermark
min_temp: 0
max_temp: 130

[fan]
pin: ar9

# "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays
[display]
lcd_type: st7920
cs_pin: ar16
sclk_pin: ar23
sid_pin: ar17
encoder_pins: ^ar31, ^ar33
click_pin: ^!ar35
kill_pin: ^!ar41

[gcode_macro startprint]
gcode:
    M140 S60 ; start preheating bed do now wait
    G28
    G21 ;metric values
    G90 ;absolute positioning
    M107 ;start with the fan off
    M104 S{ETEMP} ; preheat extruder do not wait    
    M190 S{BTEMP} ;wait for bed
    M109 S{ETEMP} ;wait for extruder
    G92 E0 ;zero the extruded length

[gcode_macro endprint]
gcode:
    M104 S0 ;extruder heater off
    M140 S0 ;heated bed heater off (if you have it)
    G91 ;relative positioning
    G1 E-1 F300  ;retract the filament a bit before lifting the nozzle to release some of the pressure
    G1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more
    G28 X0 Y0 ;move X/Y to min endstops so the head is out of the way
    G1 Y150 z10
    M84 ;steppers off
    G90 ;absolute positioning
    M107 ; turn off fan

[gcode_macro load]
gcode:
    G0 E50
    G0 E50
    G0 E10

[gcode_macro unload]
gcode:
    G0 E-50
    G0 E-50
    G0 E-10

# Enable the "M118" and "RESPOND" extended commands.
[respond]
default_type: echo

[pause_resume]
recover_velocity: 50.0

# Tool to help adjust bed screws tilt using Z probe. One may define a
# [screws_tilt_adjust] config section to enable a SCREWS_TILT_CALCULATE
# g-code command.
[screws_tilt_adjust]
screw1: 0,5
screw1_name: forrest tv
#   An arbitrary name for the given screw. This name is displayed when
#   the helper script runs. The default is to use a name based upon
#   the screw XY location.
screw2: 163,5
screw2_name: forrest th
screw3: 163,200
screw3_name: bagerst th
screw4: 0,200
screw4_name: bagerst tv
#speed: 50
#   The speed (in mm/s) of non-probing moves during the calibration.
#   The default is 50.
#horizontal_move_z: 5
#   The height (in mm) that the head should be commanded to move to
#   just prior to starting a probe operation. The default is 5.
#screw_thread: CW-M3
#   The type of screw used for bed level, M3, M4 or M5 and the
#   direction of the knob used to level the bed, clockwise decrease
#   counter-clockwise decrease.
#   Accepted values: CW-M3, CCW-M3, CW-M4, CCW-M4, CW-M5, CCW-M5.
#   Default value is CW-M3, most printers use an M3 screw and
#   turning the knob clockwise decrease distance.


[bed_mesh]
speed: 50
horizontal_move_z: 5
min_point: 0,30
max_point: 160,160
probe_count: 5,5
#fade_start: 1.0
#   The gcode z position in which to start phasing out z-adjustment
#   when fade is enabled.  Default is 1.0.
#fade_end: 0.0
#   The gcode z position in which phasing out completes.  When set
#   to a value below fade_start, fade is disabled. It should be
#   noted that fade may add unwanted scaling along the z-axis of a
#   print.  If a user wishes to enable fade, a value of 10.0 is
#   recommended. Default is 0.0, which disables fade.
#fade_target:
#   The z position in which fade should converge. When this value is set
#   to a non-zero value it must be within the range of z-values in the mesh.
#   Users that wish to converge to the z homing position should set this to 0.
#   Default is the average z value of the mesh.
#split_delta_z: .025
#   The amount of Z difference (in mm) along a move that will
#   trigger a split. Default is .025.
#move_check_distance: 5.0
#   The distance (in mm) along a move to check for split_delta_z.
#   This is also the minimum length that a move can be split. Default
#   is 5.0.
#mesh_pps: 2,2
#   A comma separated pair of integers (X,Y) defining the number of
#   points per segment to interpolate in the mesh along each axis. A
#   "segment" can be defined as the space between each probed
#   point. The user may enter a single value which will be applied
#   to both axes.  Default is 2,2.
#algorithm: lagrange
#   The interpolation algorithm to use. May be either "lagrange"
#   or "bicubic". This option will not affect 3x3 grids, which
#   are forced to use lagrange sampling.  Default is lagrange.
#bicubic_tension: .2
#   When using the bicubic algorithm the tension parameter above
#   may be applied to change the amount of slope interpolated.
#   Larger numbers will increase the amount of slope, which
#   results in more curvature in the mesh. Default is .2.

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bed_mesh default]
#*# points =
#*# 	  0.016250, -0.212500, -0.797500
#*# 	  -0.055000, -0.280000, -0.917500
#*# 	  -0.135000, -0.465000, -1.117500
#*# x_count = 3
#*# y_count = 3
#*# min_x = 0.0
#*# max_x = 160.0
#*# min_y = 30.0
#*# max_y = 160.0
#*# x_offset = 37.0
#*# y_offset = 2.0
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 32.535
#*# pid_ki = 2.582
#*# pid_kd = 102.486
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 74.380
#*# pid_ki = 1.631
#*# pid_kd = 847.935
`

**Comment by KevinOConnor** [comment]
In order for us to assist, you need to attach the Klipper log file as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin

**Comment by wormiedk** [comment]
I think your tracker is overly focused on log files. This is NOT an error it is merely unexpected behaviour or a poor description in the readme file. As the bed leveling file states that I should note the position based on nozzle position I would assume that the auto bed leveling and screw adjustment procedures would use the nozzle offset. However, I can observe that this is not the case. I am therefore wondering if the generated mesh is correct with regard to the nozzle or if the map is actually a map of bed height at the probe position and therefore inaccurate. 
I fail to see how a log file would help?

**Comment by KevinOConnor** [comment]
The code works as it is documented - the position specified in the config are the nozzle positions (the coordinates for the nozzle) - to position the probe at a given location specify the coordinates of where the nozzle would be to obtain the given probe position.   If you've experienced some sort of issue with this, you'll need to include the log.

-Kevin
