### ISSUE TITLE
Temperature jumps massively when heating

### ISSUE THREAD

**Issue by lights0123** [KevinOConnor/klipper#1793]
Sometimes, when heating, the extruder thermistor temperature jumps a massive amount, either upwards or downwards. For example, in this case, the temperature jumped up by 75°C instantly, triggering an emergency shutdown. 
![Screenshot_2019-07-07 OctoPrint](https://user-images.githubusercontent.com/3756309/60770821-493c8480-a0ad-11e9-8309-a8062456d59d.png)

Additionally, sometimes during printing, the temperature falls a large amount, also triggering an emergency shutdown. I don't have a log of that now, but if it happens again, I will post an update. It seems to be a "fake" fall, as klipper responds by increasing the temperature rapidly, but this causes a massive increase after a few seconds.

I would assume faulty wiring—however, the same setup worked just fine on the stock [Repetier-ish firmware](https://github.com/seemecnc/Firmware). The same thing happens when the stepper motors are disabled. I am using an E3D v6 Chimera dual-extruder setup on a Rostock Max V2, using the stock RAMBo board.

[klippy.log](https://github.com/KevinOConnor/klipper/files/3365849/klippy.log)

**Comment by lights0123** [comment]
And during a print:
[klippy.log](https://github.com/KevinOConnor/klipper/files/3366109/klippy.log)

**Comment by KevinOConnor** [comment]
I suspect you are overloading your power supply (it may fail to maintain a stable voltage when the heaters are on).  You may wish to try reducing the `max_power` settings (eg, set max_power=0.3 in heater_bed, and max_power=0.8 in the extruders).

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
