### ISSUE TITLE
Skr 1.3 config , beeper always on.

### ISSUE THREAD

**Issue by Zamminx** [KevinOConnor/klipper#1811]
Hi, I just found an issue with SKR 1.3 config file regarding "RepRapDiscount 128x64 Full Graphic Smart Controller"

original
[output_pin beeper]
pins: !P1.30

fixed 

[output_pin beeper]
pin: P1.30       - no "s" on pin and not inverted.

I don't  know how to edit Git without opening the issue ticket, hope it helps others.

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 4d90b60f).

-Kevin
