### ISSUE TITLE
Help with getting my printer connected?

### ISSUE THREAD

**Issue by killcase** [KevinOConnor/klipper#1837]
First, I wasn't entirely sure where to ask for help, but here I am, if there is a better venue for help please let me know!

I recently bought a SKR1.3, to use on my Anycubic Linear Plus.  I've looked through some other configuration files, and got what I think will be a working configuration file, however, I cannot get Klipper to connect to the board after installing the firmware to the SD card.  I get a failed to connect error.  I followed the flash instructions, and updated the config file as needed, but it still fails?  
[klippy.log](https://github.com/KevinOConnor/klipper/files/3432227/klippy.log)

**Comment by cosminr86** [comment]
Your config have lots of issues. 
First:
There is no stepper x y z on delta printers. Afaik they are stepper_a, stepper_b, stepper_c and extruder.
Second you defined tmc2208 extruder1 but you don't have an extruder1 defined.

Dig more on examples.
