### ISSUE TITLE
Failing to setup BLTouch Clone - Tevo Tarantula

### ISSUE THREAD

**Issue by MitchOgden** [KevinOConnor/klipper#1853]
I'm trying to get the BLTouch clone to work, but keep getting "Failed to verify BLTouch probe is raised; retrying." So I can't get it to home on the Z-Axis.

I've attached the klippy.log
[klippy.log](https://github.com/KevinOConnor/klipper/files/3448920/klippy.log)

**Comment by BlackStump** [comment]
clones are it seems pretty hit and miss if they work correctly,
have you read the docs? especially about v3 clones
if not here are some places to start
https://github.com/KevinOConnor/klipper/blob/master/docs/BLTouch.md
https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L67
https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md#bltouch
if you have read and tried what was suggested then maybe some googling about clone problems
or it just maybe defective, also look through the closed issues as there is no shortage of problems with clones in general.
apart from that I have no other suggestions and maybe someone with more insight will jump in to help.
