### ISSUE TITLE
Probe triggered prior to movement

### ISSUE THREAD

**Issue by Saso-lab** [KevinOConnor/klipper#1870]
I'm tring to run the delta_calibrate, but the nozzle stops few centimeters above the bed and it reports the error "probe triggered prior to movement". I tried to insert a pause with the following macro, without success. If i run the second time the delta_calibrate command it starts probing.
I don't know if this can influence the calibration process, but since i had this issues i'm not able to have a perfect fist layer. These are my result after a mesh calibrate but when i print large objects i can see some points on the bed where the nozzle is too close (even if the bed map does not seem bad).
I'm using an skr 1.3 with smart effector.
![issue](https://user-images.githubusercontent.com/53084927/62763796-af417080-ba8c-11e9-8b2b-4558a66e0057.PNG)
![bed](https://user-images.githubusercontent.com/53084927/62763930-fcbddd80-ba8c-11e9-870f-05fdc9338318.PNG)
![bed2](https://user-images.githubusercontent.com/53084927/62763938-ffb8ce00-ba8c-11e9-8fd1-8131c79de92f.PNG)

[klippy.log](https://github.com/KevinOConnor/klipper/files/3485286/klippy.log)

**Comment by Hywelmartin** [comment]
have you tried with the pause inside the [probe] section??
```
[probe]
pin = P2.0
x_offset = 0
y_offset = 0
z_offset = 0
activate_gcode:
	G4 P500
```

**Comment by Saso-lab** [comment]
I just tried without success, i'm having this issue since i switched to the skr 1.3

**Comment by Hywelmartin** [comment]
pullup? as you are using the servo pin
pin: ^!2.0

**Comment by Saso-lab** [comment]
Thanks a lot man, i missed the "^". 
Now everything works.
