### ISSUE TITLE
Change attribute criteria from min_speed in TemperatureFan

### ISSUE THREAD

**Issue by meteyou** [KevinOConnor/klipper#1875]
Can you change the line 27 in klippy/extras/temperature_fan.py?

From:
> self.min_speed = config.getfloat('min_speed', 0.3, above=0., maxval=1.)

to:
> self.min_speed = config.getfloat('min_speed', 0.3, maxval=1.)

The problem is the temperature_fan cannot deactivate when the temp smaller than target temp and shutdown_speed doesn't work with software pwm.

[klippy.log](https://github.com/KevinOConnor/klipper/files/3489241/klippy.log)

**Comment by KevinOConnor** [comment]
It's not clear to me what the underlying issue being reported here is.  The "above=0." is intended to catch obvious config errors (like a user configuring `min_speed=-1234`).

-Kevin

**Comment by meteyou** [comment]
with above=0. your min speed is 0.1 but i want to setup the fan with min speed 0.0. This is my problem with above=0.

**Comment by KevinOConnor** [comment]
I believe that code was written by @wizhippo - any comments on this?

-Kevin

**Comment by KevinOConnor** [comment]
FYI, I made the requested change (commit 43103929).

-Kevin
