### ISSUE TITLE
Extruder Problems after Update, Yesterday

### ISSUE THREAD

**Issue by Achim01** [KevinOConnor/klipper#1877]
Objektsize 60x75x0.2 for Test.
(first layer is the Problem)

Printing with different amperage for Extruder
brings the same Result.

[klippy.log](https://github.com/KevinOConnor/klipper/files/3489857/klippy.log)
![60x75x02](https://user-images.githubusercontent.com/51460854/62832719-519b5880-bc33-11e9-9d1f-96293d70a547.jpg)

[60x75x02.gcode..zip](https://github.com/KevinOConnor/klipper/files/3489859/60x75x02.gcode.zip)

**Comment by KevinOConnor** [comment]
Nothing in the Klipper extruder code has changed recently.  You may wish to try running `DUMP_TMC STEPPER=extruder` to see if there is anything indicating an issue with the extruder driver.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it appears the conversation has concluded.

-Kevin
