### ISSUE TITLE
Subdirectories on a virtual SD card

### ISSUE THREAD

**Issue by mbgroot** [KevinOConnor/klipper#1885]
Is it possible to implement support for subdirectories on a virtual SD card?

Fake klipper log for bot
[klippy.log](https://github.com/KevinOConnor/klipper/files/3496815/klippy.log)

**Comment by KevinOConnor** [comment]
I'm sure it's possible, but I do not think there is a common mechanism for doing that in g-code.  FWIW, I'm leery of adding non-standard "enhancements" to the legacy g-code commands.

-Kevin

**Comment by KevinOConnor** [comment]
To be clear, one could certainly add new "extended g-code" commands to do that if one wished to.

-Kevin

**Comment by mbgroot** [comment]
Why do you need G-codes to print from subdirectories? It is not solved at the code level?

**Comment by KevinOConnor** [comment]
I'm going to close this issue as I believe the original question was answered (it is possible but someone would need to code it up).

-Kevin
