### ISSUE TITLE
usb_serial_generic_read_bulk_callback - urb stopped: -32

### ISSUE THREAD

**Issue by bdn76** [KevinOConnor/klipper#1936]
Printing stop suddenly after some time with error:

usb_serial_generic_read_bulk_callback - urb stopped: -32

in kernel log. 

[klipper.log](https://github.com/KevinOConnor/klipper/files/3570866/klipper.log)

RPi 3+, Ubuntu 18.04.3 64bit with latest update. Latest klipper ftom git. I'm double check cabling and not found any trouble.

**Comment by KevinOConnor** [comment]
The best advice we have is at https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin

**Comment by bdn76** [comment]
Hmm... I'm have been migrated to Rasbian 32bit from Ubuntu 64 bit and problem have been fixed. May be this is usefull for somebody.
