### ISSUE TITLE
Generic Melzi printer config moves Z stepper 10x too fast

### ISSUE THREAD

**Issue by ghandye** [KevinOConnor/klipper#194]
Summary - The default step_distance for the Z stepper in the included generic Melzi config (and other generic configs) is set pretty low, causing the Z stepper to move 10x too fast on printers that have a 400 steps/mm Z setup.

The included default is 0.00025, which works out to 4000 steps per mm.

On my Melzi-based printer (Monoprice Maker Select v2), this was 10x too fast - the proper value was 0.0025, equating to 400 steps per mm.

I realize this is just a default config and it has to be tweaked for each individual printer's Z screws/steppers, but the default seems dangerous to me. When performing the Z axis stepper tests per https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md, the default homing speed of 5 mm/sec ended up being 50 mm/sec (!) which caused my poor printer quite a bit of consternation. I was doubly confused when I bumped the configured Z homing speed down to 0.5 mm/sec and it still beat the heck out of my Z axis. Fortunately I had an M112 ready to go, and eventually figured it out.

I'd advocate that a saner more conservative default of 0.0025 is published with the Melzi config (and possibly any other configs that use this default). It's better to have a Z axis home 10x too slow by default than 10x too fast.

**Comment by KevinOConnor** [comment]
On Sun, Feb 25, 2018 at 08:02:41PM +0000, ghandye wrote:
> Summary - The default step_distance for the Z stepper in the included generic Melzi config (and other generic configs) is set pretty low, causing the Z stepper to move 10x too fast on printers that have a 400 steps/mm Z setup.
> 
> The included default is 0.00025, which works out to 4000 steps per mm.
> 
> On my Melzi-based printer (Monoprice Maker Select v2), this was 10x too fast - the proper value was 0.0025, equating to 400 steps per mm.
> 
> I realize this is just a default config and it has to be tweaked for each individual printer's Z screws/steppers, but the default seems dangerous to me. When performing the Z axis stepper tests per https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md, the default homing speed of 5 mm/sec ended up being 50 mm/sec (!) which caused my poor printer quite a bit of consternation. I was doubly confused when I bumped the configured Z homing speed down to 0.5 mm/sec and it still beat the heck out of my Z axis. Fortunately I had an M112 ready to go, and eventually figured it out.
> 
> I'd advocate that a saner more conservative default of 0.0025 is published with the Melzi config (and possibly any other configs that use this default). It's better to have a Z axis home 10x too slow by default than 10x too fast.

That makes sense.  I changed the defaults (commit 5d635c52).

Thanks,
-Kevin
