### ISSUE TITLE
Feature Request: TMC2130 SPI communication

### ISSUE THREAD

**Issue by maz3max** [KevinOConnor/klipper#195]
So far, klipper looks fantastic to me.
Is there a chance to control the Trinamic TMC2130 over the AVR slave board (or connected directly to the raspberry)?
That might not be a priority, but then you can have cool things like stall detection.

**Comment by gdachs** [comment]
In the meantime you could try this fork: https://github.com/cruwaller/klipper/commits/lpc176x

**Comment by NeelD87** [comment]
Its WIP , check the https://github.com/KevinOConnor/klipper/tree/work-tmc2130-20180217 branch

**Comment by maz3max** [comment]
Thanks, guys!
I am very happy you keep this project moving :smile:

**Comment by KevinOConnor** [comment]
As noted, there's been a bit of work on this.  There's also a long discussion in issue #101.  I'm going to close this issue in favor of that one.

**Comment by userosos** [comment]
How i can add support control TMC2130 SPI?
I did not find it in https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg .
