### ISSUE TITLE
Duet3d - can not connect to the device 

### ISSUE THREAD

**Issue by YaronSoffer** [KevinOConnor/klipper#1963]
login as: pi
pi@ender3.local's password:
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.9.118+ aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

62 packages can be updated.
0 updates are security updates.

New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Thu Sep 12 13:50:41 2019 from 192.168.0.118
pi@ender3:~$ cd klipper
pi@ender3:~/klipper$ make clean
pi@ender3:~/klipper$ sudo service klipper stop
pi@ender3:~/klipper$ cd ..
pi@ender3:~$ git fetch
fatal: Not a git repository (or any of the parent directories): .git
pi@ender3:~$ cd klipper
pi@ender3:~/klipper$ git fetch
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/KevinOConnor/klipper
   49779f1..361de30  master     -> origin/master
 * [new branch]      work-stm32usb-20190912 -> origin/work-stm32usb-20190912
pi@ender3:~/klipper$ ./klipper/scripts/install-octopi.sh
-bash: ./klipper/scripts/install-octopi.sh: No such file or directory
pi@ender3:~/klipper$ cd ..
pi@ender3:~$ ./klipper/scripts/install-octopi.sh

###### Running apt-get update...
Hit:1 http://mirrors.ustc.edu.cn/ubuntu-ports xenial InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu-ports xenial-updates InRelease
Hit:3 http://mirrors.ustc.edu.cn/ubuntu-ports xenial-backports InRelease
Hit:4 http://mirrors.ustc.edu.cn/ubuntu-ports xenial-security InRelease
Reading package lists... Done

###### Installing packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'libncurses-dev'
build-essential is already the newest version (12.1ubuntu2).
libffi-dev is already the newest version (3.2.1-4).
libncurses5-dev is already the newest version (6.0+20160213-1ubuntu1).
libusb-dev is already the newest version (2:0.1.12-28).
avr-libc is already the newest version (1:1.8.0+Atmel3.5.0-1).
avrdude is already the newest version (6.2-5).
binutils-arm-none-eabi is already the newest version (2.26-4ubuntu1+8).
binutils-avr is already the newest version (2.25+Atmel3.5.0-2).
dfu-util is already the newest version (0.8-1).
gcc-arm-none-eabi is already the newest version (15:4.9.3+svn231177-1).
gcc-avr is already the newest version (1:4.9.2+Atmel3.5.0-1).
libnewlib-arm-none-eabi is already the newest version (2.2.0+git20150830.5a3d536                      -1).
stm32flash is already the newest version (0.5-1).
python-dev is already the newest version (2.7.12-1~16.04).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.

###### Updating python virtual environment...
Collecting cffi==1.6.0
Collecting pyserial==3.2.1
  Using cached https://files.pythonhosted.org/packages/c0/a7/25d801d71d2eecbbf0f                      1142a9d38aa77be71172295259dabb7d91310289c/pyserial-3.2.1-py2.py3-none-any.whl
Collecting greenlet==0.4.10
Collecting pycparser (from cffi==1.6.0)
Installing collected packages: pycparser, cffi, pyserial, greenlet
Successfully installed cffi-1.6.0 greenlet-0.4.10 pycparser-2.19 pyserial-3.2.1
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

###### Launching Klipper host software...
[ ok ] Restarting klipper (via systemctl): klipper.service.
pi@ender3:~$ cd ~/klipper/
pi@ender3:~/klipper$ make menuconfig
scripts/kconfig/mconf /home/pi/klipper/src/Kconfig

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

pi@ender3:~/klipper$ rm .config
pi@ender3:~/klipper$ make menuconfig
scripts/kconfig/conf --olddefconfig /home/pi/klipper/src/Kconfig
#
# configuration written to /home/pi/klipper/.config
#
scripts/kconfig/mconf /home/pi/klipper/src/Kconfig
configuration written to /home/pi/klipper/.config

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

pi@ender3:~/klipper$ make
  Build Kconfig config file
#
# configuration written to /home/pi/klipper/.config
#
  Creating symbolic link out/board
  Compiling out/src/sched.o
  Compiling out/src/command.o
  Compiling out/src/basecmd.o
  Compiling out/src/debugcmds.o
  Compiling out/src/initial_pins.o
  Compiling out/src/gpiocmds.o
  Compiling out/src/stepper.o
  Compiling out/src/endstop.o
  Compiling out/src/adccmds.o
  Compiling out/src/spicmds.o
  Compiling out/src/thermocouple.o
  Compiling out/src/i2ccmds.o
  Compiling out/src/pwmcmds.o
  Compiling out/src/lcd_st7920.o
  Compiling out/src/lcd_hd44780.o
  Compiling out/src/buttons.o
  Compiling out/src/tmcuart.o
  Compiling out/src/spi_software.o
  Compiling out/src/atsam/main.o
  Compiling out/src/atsam/gpio.o
  Compiling out/src/atsam/i2c.o
  Compiling out/src/atsam/spi.o
  Compiling out/src/atsam/hard_pwm.o
  Compiling out/src/generic/crc16_ccitt.o
  Compiling out/src/generic/alloc.o
  Compiling out/src/generic/armcm_irq.o
  Compiling out/src/generic/armcm_timer.o
  Compiling out/src/atsam/sam4_usb.o
  Compiling out/src/generic/usb_cdc.o
  Compiling out/src/atsam/sam4e_afec.o
  Compiling out/src/atsam/sam4_cache.o
  Compiling out/src/../lib/sam4e/gcc/system_sam4e.o
  Compiling out/src/../lib/sam4e/gcc/gcc/startup_sam4e.o
  Building out/compile_time_request.o
Version: v0.7.0-349-gd766587-20190912_151942-ender3
  Linking out/klipper.elf
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-exit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-fini.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-impure.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-init.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memchr.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memcpy.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memmove.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use                       of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memset.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-__atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use                       of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-__call_atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t                      ; use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-exit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-fini.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-impure.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-init.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of                       wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memchr.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memcpy.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memmove.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use                       of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-memset.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use o                      f wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-__atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use                       of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: warning: /usr/li                      b/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/armv7e-m/fpu/libg_nano.a(li                      b_a-__call_atexit.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t                      ; use of wchar_t values across objects may fail
  Creating bin file out/klipper.bin
pi@ender3:~/klipper$ ls /dev/serial/by-id/*
/dev/serial/by-id/usb-03eb_6124-if00
pi@ender3:~/klipper$ sudo service klipper stop
pi@ender3:~/klipper$ make flash FLASH_DEVICE=/dev/serial/by-id/usb-03eb_6124-if0                      0
  Flashing out/klipper.bin to /dev/serial/by-id/usb-03eb_6124-if00
Entering bootloader on /dev/serial/by-path/platform-5311000.ohci3-controller-usb                      -0:1:1.0
Device reconnect on /dev/serial/by-path/platform-5311000.ohci3-controller-usb-0:                      1:1.0
lib/bossac/bin/bossac -U -p /dev/serial/by-path/platform-5311000.ohci3-controlle                      r-usb-0:1:1.0 -e -w out/klipper.bin -v

Erase flash

Done in 4.161 seconds
Write 18880 bytes to flash (37 pages)
[==============================] 100% (37/37 pages)
Done in 0.307 seconds
Verify 18880 bytes of flash
[==============================] 100% (37/37 pages)
Verify successful
Done in 0.380 seconds
Device reconnect on /dev/serial/by-path/platform-5311000.ohci3-controller-usb-0:1:1.0
pi@ender3:~/klipper$ sudo service klipper start
pi@ender3:~/klipper$ ls /dev/serial/by-id/*
/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00

**There is no klippy.log** - installation process went well 
However, I can not connect to the board the baund rate through the UI seem to be stack on 250000 baund no matter what I do in the octoprint.

Here is a snap for the output.
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d21210, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e0ff90, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f93d39ed0, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Recv: 
\x10?M��W��\x12��~\x0b\x10?3�\x08�&��~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Connection closed, closing down monitor
Changing monitoring state from "Connecting" to "Offline"
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d49910, open=True>(port='/dev/ttyACM0', **baudrate=250000,** bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Recv: 
\x10?L�� ��\x1f��~\x0b\x10?3�\x7f�f�2~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�u�#\x07f~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�u�#\x07f~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Connection closed, closing down monitor
Changing monitoring state from "Connecting" to "Offline"
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e327d0, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f93c83650, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d49f10, open=True>(port='/dev/ttyACM0', **baudrate=250000**, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e25d50, open=True>(port='/dev/ttyACM0', **baudrate=250000**, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e99110, open=True>(port='/dev/ttyACM0', Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d21210, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e0ff90, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f93d39ed0, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Recv: 
\x10?M��W��\x12��~\x0b\x10?3�\x08�&��~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Connection closed, closing down monitor
Changing monitoring state from "Connecting" to "Offline"
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d49910, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Recv: 
\x10?L�� ��\x1f��~\x0b\x10?3�\x7f�f�2~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�u�#\x07f~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�l�vV�~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�u�#\x07f~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Recv: �\x18~\x0b\x10?3�g�]��~\x0b\x10?3�p�
Connection closed, closing down monitor
Changing monitoring state from "Connecting" to "Offline"
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e327d0, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f93c83650, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33d49f10, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e25d50, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f33e99110, open=True>(port='/dev/ttyACM0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor

**Comment by YaronSoffer** [comment]
Instead of using the soft link I had used the "real name" ( check for soft links on linux). 

ls -l /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00
lrwxrwxrwx 1 root root 13 Sep 13 07:46 /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00 -> ../../ttyACM0
Still even with the "linked name" the problem is still the same.

**Comment by YaronSoffer** [comment]
Let me make my self clear here. There seems to be a problem in octoprint ( take a look in the log above), it always runs on baud rate of 250000 no matter what is set in the UI.
Is there a way to set the baud rate other than the UI? I can give it a try.

**Comment by BlackStump** [comment]
>  /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00 -> ../../ttyACM0
is the serial port between the HOST and the MCU

To communicate to the host you use /tmp/printer that is what @jakep82  was pointing out
>  Octoprint
>  From the main page, under the "Connection" section (at the top left of the page) make sure the
>  "Serial Port" is set to "/tmp/printer" and click "Connect"

**Comment by YaronSoffer** [comment]
You may have a point in there. I have two printers, one is already set with Klipper ( old ramps board + RPI), ( DUET3d + ender3 +  OPi ) . There seem to be a problem with Klipper on the second one. my guess there is some sort of failure in the service as I don't see /tmp/klippy.log.

**Comment by YaronSoffer** [comment]
As the service seems to crash on start I did a little digging....
First do a 
sudo service klipper stop 
Then run the follow 
/home/pi/klippy-env/bin/python /home/pi/klipper/klippy/klippy.py /home/pi/printer.cfg -l /tmp/klippy.log.
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 8, in <module>
    import util, reactor, queuelogger, msgproto
  File "/home/pi/klipper/klippy/reactor.py", line 7, in <module>
    import greenlet
ImportError: No module named greenlet.

I tried to run the "pip" version on the klippy-env - but somehow got this:
pi@ender3:~/klippy-env/bin$ ./pip
Traceback (most recent call last):
  File "./pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

Using the machine python 
/usr/bin/python /home/pi/klipper/klippy/klippy.py /home/pi/printer.cfg -l /tmp/klippy.log 
everything working well so far.
i am going to set it in " /etc/default/klipper"
KLIPPY_EXEC=/usr/bin/python

**Comment by YaronSoffer** [comment]
Still, something is not working - octoprint refuses to connect 
[klippy.log](https://github.com/KevinOConnor/klipper/files/3610031/klippy.log)

**Comment by YaronSoffer** [comment]
This is what I am getting on the terminal screen of octoprint

Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f95cd7110, open=True>(port='/tmp/printer', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f378c87d0, open=True>(port='/tmp/printer', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f378a99d0, open=True>(port='/tmp/printer', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor

**Comment by YaronSoffer** [comment]
connected !!
Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x7f87790510, open=True>(port='/tmp/printer', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection...
Changing monitoring state from "Opening serial port" to "Detecting baudrate"
Trying baudrate: 115200
Send: N0 M110 N0*125
Recv: ok
Changing monitoring state from "Detecting baudrate" to "Operational"
Send: N0 M110 N0*125
Recv: ok
Recv: ok
Send: N1 M115*39
Send: N2 M21*18
Recv: ok FIRMWARE_VERSION:v0.7.0-349-gd766587 FIRMWARE_NAME:Klipper
Recv: ok
Send: M105
Recv: ok B:26.8 /0.0 T0:26.9 /0.0
Send: M105
Recv: ok B:26.8 /0.0 T0:26.9 /0.0
Send: M105
Recv: ok B:26.7 /0.0 T0:26.9 /0.0
Send: M105
Recv: ok B:26.8 /0.0 T0:26.9 /0.0
