### ISSUE TITLE
SET_GCODE_OFFSET > HOME AXIS FIRST

### ISSUE THREAD

**Issue by schnello** [KevinOConnor/klipper#1964]
Hello.

Latest Klipper SW
Ubuntu 18 with Octoprint 1.3.12rc1
i3 Mega with LCD

Test preparation:
Turn on printer
Dont home the printer

If i send the "SET_GCODE_OFFSET Z=0" via the Terminal ... all is fine. 
Send: SET_GCODE_OFFSET Z=0
Recv: ok

If i use instead the LCD Menu (if a print is started) Klipper reports an Error Message. 

Recv: !! Must home axis first: 0.000 0.000 -0.005 [0.000]
Changing monitoring state from "Printing" to "Cancelling"

So if i start a print... and the printer is in the heating phase (not homed)... and i send via the LCD Menu the "offset comment" Octoprint aborts the print regarding the error message. I guess also the "offset" will not be used.

[klippy.log](https://github.com/KevinOConnor/klipper/files/3606721/klippy.log)

**Comment by KevinOConnor** [comment]
The menu z offset not only adjusts the offset, but also makes the offset take effect immediately (eg, `SET_GCODE_OFFSET Z=0.005 MOVE=1`).  If you want to make adjustments prior to homing, then you'll need to do them via the command-line.

-Kevin

**Comment by schnello** [comment]
Thanks for the explanation
