### ISSUE TITLE
HBot Kinematics support

### ISSUE THREAD

**Issue by CorvetteCole** [KevinOConnor/klipper#1965]
[klippy.log](https://github.com/KevinOConnor/klipper/files/3607607/klippy.log)

I've been looking in to implementing HBot kinematics on my own, however they are so simple I was wondering if you would like to just put them in real quick. It is essentially just CoreXY with the signs switched. I felt a little bad just taking your CoreXY configs and calling them mine after changing the signs.

I'm happy to commit this myself as well, just figured you might have a better variable naming scheme etc than I.

**Comment by CorvetteCole** [comment]
@KevinOConnor this was directed towards you a bit

**Comment by KevinOConnor** [comment]
It's not clear what is being reported or requested here.  The config/example-corexy.cfg is intended to document both corexy and hbot printers (as they are, in effect, the same).

-Kevin

**Comment by CorvetteCole** [comment]
@KevinOConnor I'm gonna go punch the mechanical engineer who told me otherwise, sorry about that!
