### ISSUE TITLE
Klipper shuts down if travel involves extruing and certain conditions are met 

### ISSUE THREAD

**Issue by jimmy00784** [KevinOConnor/klipper#1966]
Behavior:
When a travel move involves extruding, in certain conditions, Klipper will shutdown.

Steps to recreate:

G91; relative motion
G1 X10 E10 F2100; runs fine
G1 X-10 E-10 F2100; runs fine
G1 X9 E10 F2100; Klipper shutdown
G1 X-9 E-10 F2100; runs fine

Note:
The printer is CoreXY with titan extruder (3:1 gear ratio) setup involving TMC2130 v1.1 drivers

[klippy.log](https://github.com/KevinOConnor/klipper/files/3607668/klippy.log)

**Comment by KevinOConnor** [comment]
My advice would be to return max_extrude_cross_section to its default settings (ie, remove it from your config).  If some software is generating bogus requests that trigger the max_extrude_cross_section check then I recommend you try to address that in the software generating those requests.

The underlying issue is that Klipper was commanded to move the extruder faster than it is capable of doing.  The software is reporting that.

-Kevin

**Comment by nophead** [comment]
The limit should be a maximum flow rate through the nozzle, not a cross section.

**Comment by KevinOConnor** [comment]
Hi @nophead,

> The limit should be a maximum flow rate through the nozzle, not a cross section.

The max_extrude_cross_section check is intended to both place a cap (indirectly) on overall flow rate and to catch bogus moves that could cause nozzle clogging.  In particular, slic3r used to have a bug that would (seemingly randomly) cause gapfills to extrude massive amounts of filament.

You may be correct that specifying a maximum flow rate is a preferable option to the indirect check.  However, it also has issues (eg, it is unclear what a good default would be).

As far as I know, the current default setting for max_extrude_cross_section shouldn't hit on valid moves.  For a .4mm nozzle it would permit a cross section of .640mm^2 - which at a layer height of .3mm would allow an extrusion width up to 2.133mm.  It's not clear to me the gain of extruding lines wider than that on a .4mm nozzle - at wider lengths I'd certainly be concerned about filament curling up and attaching to the nozzle on my printers.  To my recollection, when this check does pop up and is reported here, it's almost exclusively an extrusion width that exceeds the default by 5x or more - often 10-100x.  So, if the current default is catching valid moves I'm certainly open to changing it, however that hasn't been my experience so far.

Cheers,
-Kevin

**Comment by nophead** [comment]
I start my prints with a very wide line along the edge of the bed, probably 10 times the nozzle width, to purge out the extruder and ensure it is fully primed. It is very slow travel, so it doesn't exceed the extruder's maximum flow rate but it does deposit a lot of plastic.

**Comment by jimmy00784** [comment]
@KevinOConnor I tested again and it appears that indeed if I disable pressure advance, I don't run into this issue with max_extrude_cross_section value of 2.406. 
How do you suggest I tune PA (0.45, lookahead 0.010) so that it plays well with max_extrude_cross_section value and not result in klipper shutdown on the mcu?
Please note that I use Titan exturder with 3-to-1 gear reduction.

**Comment by KevinOConnor** [comment]
Alas, I don't have any additional advice.

-Kevin

**Comment by jimmy00784** [comment]
@KevinOConnor Trial and error was the answer I suppose. Max Extrude Cross Section of 10 and Pressure Advance of 0.35 or 0.3 seem to work for my setup. Large Max Extrude Cross Section is needed to support fast loading of the filament from parking position which is at -173mm in my setup. Once the filament is brought to the nozzle, the actual extrusion takes place well within the expected max extrude cross section value of 2.405mm^2 (1mm travel + 1mm extrusion on 0.5mm nozzle).
