### ISSUE TITLE
Unable to load Klipper

### ISSUE THREAD

**Issue by UUAMike** [KevinOConnor/klipper#1971]
I had previously installed Klipper and had it working fine. After attempting to tweak a few configurations in the printer.cfg file, I could no longer load Klipper.

I tried several things to try to make it work again, but I decided to do a clean install of Octopi and Klipper. However, I still cannot load it and I am not sure where to go from here. 
[klippy.log](https://github.com/KevinOConnor/klipper/files/3614144/klippy.log)

**Comment by BlackStump** [comment]
follow the instructions below it might help
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#wheres-my-serial-port
