### ISSUE TITLE
Unable to control printer using LCD

### ISSUE THREAD

**Issue by UUAMike** [KevinOConnor/klipper#1979]
I am not able to use the dial on my printer (Ender 3) to select menu items on the LCD. The LCD appears to be displaying correctly. Please see attached log and printer.cfg below:

[klippy.log](https://github.com/KevinOConnor/klipper/files/3617747/klippy.log)

[stepper_x]
step_pin: PD7
dir_pin: !PC5
enable_pin: !PD6
step_distance: .0125
endstop_pin: ^PC2
position_endstop: 0
position_max: 235
homing_speed: 50

[stepper_y]
step_pin: PC6
dir_pin: !PC7
enable_pin: !PD6
step_distance: .0125
endstop_pin: ^PC3
position_endstop: 0
position_max: 235
homing_speed: 50

[stepper_z]
step_pin: PB3
dir_pin: PB2
enable_pin: !PA5
step_distance: .0025
endstop_pin: ^PC4
position_endstop: 0.0
position_max: 250

[extruder]
max_extrude_only_distance: 100.0
step_pin: PB1
dir_pin: !PB0
enable_pin: !PD6
step_distance: 0.010526
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PD5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA7
control: pid
# tuned for stock hardware with 200 degree Celsius target
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250

[heater_bed]
heater_pin: PD4
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA6
control: pid
# tuned for stock hardware with 50 degree Celsius target
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130

[fan]
pin: PB4

[mcu]
serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[display]
lcd_type: st7920
cs_pin: PA3
sclk_pin: PA1
sid_pin: PC1
encoder_pins: ^PD2, ^PD3
click_pin: ^!PC0

# This adds a bed screws adjust GCode, that moves the nozzle around for you so you can paper adjust.
[bed_screws]
screw1: 31,37
screw1_name: Front left screw
screw2: 31,208
screw2_name: Rear left screw
screw3: 201,208
screw3_name: Rear right screw
screw4: 201,37
screw4_name: Front right screw

# This adds pause/resume support
[pause_resume]

# This adds the 'respond' G-Code that you can use to send commands back to OctoPrint
[respond]
default_type: echo

# This enables a 'force_move' command ignoring all homing, Z-stops etc. Useful in debugging.
[force_move]
enable_force_move: True

# The following section is to add a 'Calibration' menu item that allows easy access to many calibration settings

# Overwrite the main menu, add a 'power off' item and a 'calibration' submenu
[menu __main]
type: list
name: Main Menu
items:
    __command_power_off
    __tune
    __octoprint
    __sdcard
    __control
    __calibration
    __temp
    __filament
    __prepare
    __test

# This sends a power off command to Octoprint that gets picked up by the 'action commands' plug in
[menu __command_power_off]
type: command
name: Power off
gcode: RESPOND TYPE=command MSG=action:poweroff

[menu __calibration]
type: list
name: Calibration
items:
    __calibration_home_all_axes
    __calibration_bed_screws_adjust
    __calibration_bed_mesh_calibrate
    __calibration_screws_calculate
    __calibration_probe_calibrate
    __calibration_probe_accuracy
    __general_firmware_restart
	
[menu __calibration_accept]
type: command
name: Accept
gcode: ACCEPT

[menu __calibration_abort]
type: command
name: Abort
gcode: ABORT
action: back

[menu __calibration_screws_calculate]
type: command
name: Screw tilt calculate
gcode:
	G28
	SCREWS_TILT_CALCULATE
	
[menu __calibration_bed_screws_adjust]
type: list
name: Adjust screws
enter_gcode: 
	G28
	BED_SCREWS_ADJUST
show_back: False
items:
	__calibration_accept
	__calibration_bed_screws_adjust_adjusted
	__calibration_save_config
	__calibration_abort
		
[menu __calibration_probe_accuracy]
type: command
name: Test accuracy
gcode:
	G28
	G0 X164 Y134 Z10 F6000
	PROBE_ACCURACY
	
[menu __calibration_save_config]
type: command
name: Save config
gcode: SAVE_CONFIG

[menu __general_firmware_restart]
type: command
name: Restart firmware	
gcode: FIRMWARE_RESTART

[menu __calibration_home_all_axes]
type: command
name: Home XYZ
gcode: G28

[menu __calibration_bed_screws_adjust_adjusted]
type: command
name: Adjusted
gcode: ADJUSTED

[menu __calibration_probe_calibrate]
type: list
show_back: False
name: Adjust Z offset
enter_gcode:
    G28
    G0 Z10 F6000
    PROBE_CALIBRATE
	
items:
    __calibration__toolhead_zpos
    __calibration_probe_calibrate_testz_minus, __calibration_probe_calibrate_testz_plus 
    __calibration_probe_calibrate_testz_minus_minus, 
    __calibration_probe_calibrate_testz_plus_plus
    __calibration_probe_calibrate_testz_minus_1, __calibration_probe_calibrate_testz_plus_1	    
    __calibration_probe_calibrate_testz_minus_point_1, 
    __calibration_probe_calibrate_testz_plus_point_1
    __calibration_accept
    __calibration_save_config
    __calibration_abort

[menu __calibration__toolhead_zpos]
type: item
width: 16
name: "Z = {0:.3f}"
cursor: \x20
parameter: toolhead.zpos

[menu __calibration_probe_calibrate_testz_minus]
cursor: \x20
type: command
width: 7
name: "   -"
gcode: TESTZ Z=-

[menu __calibration_probe_calibrate_testz_plus]
cursor: \x20
type: command
name: "   +"
width: 7
gcode: TESTZ Z=+

[menu __calibration_probe_calibrate_testz_minus_minus]
cursor: \x20
type: command
name: "   --"
width: 7
gcode: TESTZ Z=--

[menu __calibration_probe_calibrate_testz_plus_plus]
cursor: \x20
type: command
name: "   ++"
width: 7
gcode: TESTZ Z=++
	
[menu __calibration_probe_calibrate_testz_minus_1]
cursor: \x20
type: command
name: "  -1.0"
width: 7
gcode: TESTZ Z=-1

[menu __calibration_probe_calibrate_testz_plus_1]
cursor: \x20
type: command
name: "  +1.0"
width: 7
gcode: TESTZ Z=+1

[menu __calibration_probe_calibrate_testz_minus_point_1]
cursor: \x20
type: command
name: "  -0.1"
width: 7
gcode: TESTZ Z=-0.1

[menu __calibration_probe_calibrate_testz_plus_point_1]
cursor: \x20
type: command
name: "  +0.1"
width: 7
gcode: TESTZ Z=+0.1

[menu __calibration_bed_mesh_calibrate]
type: deck
name: Generate bed mesh
width: 18
show_back: False
enter_gcode:
    G28
    BED_MESH_CALIBRATE
    SAVE_CONFIG
items:
    __calibration_card_bed_mesh

[menu __calibration_card_bed_mesh]
type: card
name: Calibration card
content:
    "{0}"
    ""
    "   Will reboot"
    "  when complete"
items:
    __calibration_bed_mesh_calibrate_text_1
    
[menu __calibration_bed_mesh_calibrate_text_1]
type: item
name: "  [In progress]"
cursor: \x20

**Comment by KevinOConnor** [comment]
Your log shows an error message - you'll need to fix that.  In short, the menu customization was not accepted - either remove the customization or update it.

-Kevin
