### ISSUE TITLE
[question] How to update?

### ISSUE THREAD

**Issue by herrwusel** [KevinOConnor/klipper#198]
This might be a stupid question but how do I update properly? After I 'git pull' is there anything else to do? Do I need to build/reflash the microcontroller?

**Comment by mmone** [comment]
The [FAQ](https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-upgrade-to-the-latest-software) doc answers this question.

**Comment by herrwusel** [comment]
My bad! I missed it!
