### ISSUE TITLE
How do I issue the reset sequence to the bltouch from the command input line?

### ISSUE THREAD

**Issue by w1ebr** [KevinOConnor/klipper#200]
Hi Kevin,
My bltouch often comes up complaining (i.e. stuck in triggered state) when the machine is first powered on. With Marlin firmware, M280 P0 S160 would reset the bltouch. How do I do this via a klipper command or gcode?
Gene

**Comment by stemaDev** [comment]
SET_SERVO SERVO=bltouch ANGLE=160
