### ISSUE TITLE
Option to discard first read value when using multiple probes

### ISSUE THREAD

**Issue by vladbabii** [KevinOConnor/klipper#2024]
## Short version

I would like to request an option, when probing or homing (so for all XYZ endstops) to configure klipper to discard first value of the homing/probing. Based on my tests, if the kinematics of the printer are good enough, if something varies it's most likely in the first value read. By ignoring / discarding the first value a much better reading can be had. 

For example, with tmc2208 in standalone mode, at 50+ mm/s only the first hit of the endstop varied with +1 +0 micro step. If the first value can be discarded then the precision would be much better up to higher speeds.

## Long version:

I built a jig to test endstop precision
- steppers: a4988, drv8825, tmc2208, tmc2209 (tmcs both uart and without)
- endstops: omron high precision, omron normal precision, various no name (chinese) mechanical switches, optical endstops
![IMG_20190917_230009](https://user-images.githubusercontent.com/4667916/65839785-40102c00-e319-11e9-9a4d-1f7e17ba0f8b.jpg)

Ran the PROBE_ACCURACY command to test things.

Take-aways:
- optical endstops are worse than almost any option at over 30 mm/s (2+ steps can be missed)
- omron switches work with same precision (direct or with metal blade over button) up to 40 mm/s
- high precision switches work ok up to 70 mm/s
- when doing multiple probes, the error usually appears only in first probe so if possible, discard first reading for much higher accuracy
- most mechanical switches had 1 step error rate between 30 and 50 mm/s

[klippy.zip](https://github.com/KevinOConnor/klipper/files/3668150/klippy.zip)

**Comment by KevinOConnor** [comment]
FYI, homing normally does a "double tap" of the endstop - it's configured via the `homing_retract_dist` and `second_homing_speed` parameters.

For probing, it's possible to use the `samples_tolerance` and `samples_tolerance_retries` options to retry on a bad probe.

-Kevin

**Comment by vladbabii** [comment]
But don't sample_tolerance and samples_tolerance_retries retry second/third measurement ? I want to discard first one.

**Comment by KevinOConnor** [comment]
If the `samples: 2` then it should be possible to detect the discrepancy on the second probe, and then a total of 4 probes would be made (the first two discarded).  Dropping the first probe attempt outright might be possible from g-code scripts - otherwise a developer would need to implement and submit the code to implement it.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.  The existing config options can provide similar functionality and/or a developer can extend the code.

-Kevin
