### ISSUE TITLE
support МКС Gen L

### ISSUE THREAD

**Issue by userosos** [KevinOConnor/klipper#204]
What about МКС Gen L? It is like arduino+ramps but it have different numbers of pins.

**Comment by dragonnn** [comment]
Killpper doesn't make support for it, just write a proper configuration file since you configure every pin in it.

**Comment by userosos** [comment]
@dragonnn I made a reservation. I mean the configuration file, of course. Example.

**Comment by KevinOConnor** [comment]
It doesn't appear anyone is working on this, so I'm going to close this issue.
