### ISSUE TITLE
Enhancement request: More descriptive "ADC out of range" errors

### ISSUE THREAD

**Issue by ghandye** [KevinOConnor/klipper#205]
When troubleshooting "ADC out of range" errors, it would be helpful for the end user if the error included which pin was out of range. Information about the actual value that was seen that was out of range, and the min or max limit that was exceeded, might also be useful.

**Comment by KevinOConnor** [comment]
On Thu, Mar 01, 2018 at 04:21:00AM +0000, ghandye wrote:
> When troubleshooting "ADC out of range" errors, it would be helpful for the end user if the error included which pin was out of range. Information about the actual value that was seen that was out of range, and the min or max limit that was exceeded, might also be useful.

Indeed.  However, the ADC error above is raised in the
micro-controller when temperatures are out of range - it's intended as
a "last resort" type of safety check.  The MCU code is setup to
prioritize shutdown of the heaters in these types of events, so we
purposely don't output debug information prior to invoking the
internal shutdown.  The code organization currently makes it difficult
to report additional debugging information after the internal shutdown
has completed.

The software will continue to report temperatures though, so it's
likely one can find out which thermistor is out of range from the
OctoPrint temperature tab and/or the Stats messages in the klippy.log
file.

-Kevin

**Comment by ghandye** [comment]
Makes sense. Thanks!
