### ISSUE TITLE
Build environment issues

### ISSUE THREAD

**Issue by JeanJacquesBluffobaque** [KevinOConnor/klipper#206]
Not entirely sure this belongs here, but Google searches haven't provided a solution. I've been running Octoprint/Octopi for about 2 years. It's completely up to date. I've followed https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md to obtain Klipper.

At the 'Make' step, I get the error that setjmp.h is missing. I can _locate_ it, there are actually 2 instances of it. I can add the paths to the makefile using -I but that results in further missing header files.

As I've double checked that I followed all steps detailed in the Installation.md, I'm at a loss. How do I fix this?

**Comment by lenne0815** [comment]
Without any further knowledge it sounds like a permission error.

**Comment by KevinOConnor** [comment]
On Thu, Mar 01, 2018 at 12:41:09AM -0800, JeanJacquesBluffobaque wrote:
> Not entirely sure this belongs here, but Google searches haven't provided a solution. I've been running Octoprint/Octopi for about 2 years. It's completely up to date. I've followed https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md to obtain Klipper.
> 
> At the 'Make' step, I get the error that setjmp.h is missing. I can _locate_ it, there are actually 2 instances of it. I can add the paths to the makefile using -I but that results in further missing header files.
> 
> As I've double checked that I followed all steps detailed in the Installation.md, I'm at a loss. How do I fix this?

If you attempted the Klipper install from an OctoPi installation that
was originally done 2 years ago, then I think you should retry after
installing OctoPi 0.14 from scratch to an sdcard.

-Kevin

**Comment by JeanJacquesBluffobaque** [comment]
Install from scratch worked.
