### ISSUE TITLE
Getting 'Heater extruder not heating at expected rate' in the same print point.

### ISSUE THREAD

**Issue by andrico21** [KevinOConnor/klipper#2063]
Got 'Heater extruder not heating at expected rate' error on previous print, then resliced the same STL with some additional parts added - print job failed again on the same height/point (about 7hrs progress). Also after Klipper was shut down I noticed the chassis FAN is active, not sure - how to check the fact it was run sometime during print with klippy.log
![unnamed](https://user-images.githubusercontent.com/44984087/66705046-97a39400-ed2a-11e9-9a4a-a18ed274612d.jpg)

[klippy.log](https://github.com/KevinOConnor/klipper/files/3720926/klippy.log)

**Comment by tonn0297** [comment]
looks like you have a layerfan or some cooing on your heeterblock. it goes from 252 to 243 in a short amount of time

**Comment by andrico21** [comment]
@tonn0297 thanks for idea! thought I turned off the cooling, but now I've looked on this layer in slicer and realized it's bridging layer - first one after infill. Then I've checked cooling and discovered the autocooling is enabled.
Solved!
