### ISSUE TITLE
On-going project - docker stack for klipper

### ISSUE THREAD

**Issue by vladbabii** [KevinOConnor/klipper#2070]
I am working on a docker stack for docker. This stack runs klipper, ocotprint and other things each in their own docker image. This is mainly for my own use but i plan to support it in the future.

I am currently fake printing (no extruder and no real heating) with the stack to make sure it does not crash or do weird stuff during printing.

This is a usable work in progress and I am looking for feedback from anyone interested

github project - https://github.com/klipperondocker
installation instructions - https://github.com/klipperondocker/docs
development status (implented, ongoing and feature wishlist) - https://github.com/klipperondocker/dev/blob/master/README.md

Docker images - https://hub.docker.com/u/klipperondocker

Attached fake log fie for bot.
[klippy.zip](https://github.com/KevinOConnor/klipper/files/3723602/klippy.zip)

**Comment by KevinOConnor** [comment]
Okay, thanks for the info.  I'm going to close this as it looks like the conversation has concluded.

-Kevin
