### ISSUE TITLE
Printer stuck on heating

### ISSUE THREAD

**Issue by Kotletowsky** [KevinOConnor/klipper#2074]
[klippy.log](https://github.com/KevinOConnor/klipper/files/3730977/klippy.log)
Ender + MKS Gen L 1.0 + RaspberryPi
Hi, after hotend upgrade I have huge problem. I've changed hotend from stock ender to triangle e3dv6. Both are 24V. Turn on printer, and set heating to 200C. Suddenly, printer go to 340C, so I disconnect power and wait till it cool down. Now, after every powerup it's still heating. Just for test I've changed extruder heater to anonther channel, and I have the same situation. Heater runaway. The same with old ender heater. I have no idea what's happened, board is broken ? But why ?

**Comment by nophead** [comment]
Perhaps a short to ground in the heater cable somehow? Did you change the wiring?

**Comment by Kotletowsky** [comment]
Yes, but for sure there is no shortcut. Even l crimp new connectors. Also with old heater is the same situation.

**Comment by nophead** [comment]
No possibility you mixed up the heater and thermistor wires?

**Comment by Kotletowsky** [comment]
No way. I'm electrician :)

**Comment by nophead** [comment]
Does it all behave with the heater negative disconnected? I.e. stop heating and show correct temperature?

Seems like the MOSFET is shorted, they can be blown by ESD, but it would be odd to blow two.

**Comment by Kotletowsky** [comment]
It's still showing correct temperature, but doesn't stop. Still heating.

**Comment by Kotletowsky** [comment]
It's still showing correct temperature, but doesn't stop. Still heating.

**Comment by nophead** [comment]
What even with one wire disconnected?

**Comment by jakep82** [comment]
The MKS Gen L has 2 hotend outputs.  Move your hotend to the other output and change the pins in your config.  If it works correctly after that, then you know the mosfet on your board is shorted closed.

**Comment by Kotletowsky** [comment]
If I disconnect one wire, mosfet is still triggered. About second heater output - the same situation. I've tried that. Also, when temperature goes higher than 230 firmware at printer freeze.

**Comment by nophead** [comment]
If the board has a reset button hold that and see if the MOSFET turns off.

Did you change the firmware? If not how would it suddenly go wrong when you mess with the wiring? Looks more like you did something wrong with the wiring and blew up two MOSFETs.

**Comment by Kotletowsky** [comment]
When I reset board mosfets are turned off, but start after release. About wiring. There are only 4 wires. It couldn't be wrong. Firmware reflashed yesterday.

**Comment by nophead** [comment]
It now seems like a firmware heater pin configuration problem but you haven't made it clear what order you did things. If it failed simply by swapping extruders I can't see how it could be firmware. If you re-re-flashed the firmware before testing then it seems like the new firmware is miss-configured.

**Comment by Kotletowsky** [comment]
First, just changed hotend. And it fails. After that, I thought it was a problem with firmware. So I reflashed that and set the same configuration like before. Also, I don't get why it freeze when temperature goes higher than 240. Thermal runaway doesn't work?

**Comment by Kotletowsky** [comment]
Yes. I've set board fan to that output and extruder to second one (I have only one extruder). But now, board is dead. I need to wait for new one.

**Comment by Kotletowsky** [comment]
Ok. New board, mks gen l 1.4. I've connected only raspberry, New heater, New thermistor and power supply. The same situation. Heater runaway, I can't stop this.

**Comment by nophead** [comment]
You seem to have the extruder heater mapped to the fan connector, not the second extruder. Is your extruder heater wired to the fan connector? If not that looks like your problem.

**Comment by Kotletowsky** [comment]
> 
> 
> You seem to have the extruder heater mapped to the fan connector, not the second extruder. Is your extruder heater wired to the fan connector? If not that looks like your problem.

I just use one extruder heater channel to drive fan for stepsticks. 
Now, I reinstaled octopi, octoprint, klipper host. Flashed new board from zero. I have only power supply connected, no stepsticks in sockets. And even i can't connect to printer: "ADC out of range"

**Comment by nophead** [comment]
Yes but is the extruder heater that you say is always on actually connected to the fan connector on the board? That is where it is configured in your log of the first post. If you have the extruder heater wired to one of the heater connections it will not work with that configuration.

**Comment by Kotletowsky** [comment]
Now I have everything complete fresh. And I can't even connect to printer. When I click "connect" immediately have "adc out of range".

**Comment by nophead** [comment]
Well if you hadn't already said your are an electrician I would guess there is a problem with your thermistor connection, or it is configured for the wrong pin.

**Comment by Kotletowsky** [comment]
New raspberry, New SD cards. Clean install and everything works as it should
