### ISSUE TITLE
Klipper loose control over heaters while homing

### ISSUE THREAD

**Issue by RustyWraith** [KevinOConnor/klipper#2083]
Performing G28 may lead to a large overheat or loss of extruder temperature.
Or the cause is any g-code macro, I'm not sure yet.
[klippy.log](https://github.com/KevinOConnor/klipper/files/3745379/klippy.log)
![templog](https://user-images.githubusercontent.com/11280514/67122018-87415c80-f1f5-11e9-954d-c71c92e44a1f.PNG)

**Comment by KevinOConnor** [comment]
This is generally the result of voltage or wiring issues - for example: the power supply may not have sufficient power for the steppers and heaters (setting a max_power on the heaters may help), there could be poor ground wire connections, the axis movement may be tugging on the thermistor wire causing changes in voltage, the axis movement may be tugging on wires causing a general short, etc.

-Kevin

**Comment by RustyWraith** [comment]
Thank you!
After some investigation I believe it was sort of thermistor issues.
