### ISSUE TITLE
Tmc5160 spi issue

### ISSUE THREAD

**Issue by Akex2** [KevinOConnor/klipper#2086]
hello
I have 2 tmc2208 for X and Y with uart and a tmc 5160 v1.2 from bitreetech in spi on a SKR1.3
![Capture2](https://user-images.githubusercontent.com/8688892/67150512-93dab900-f2b8-11e9-96dd-509d703bb99d.PNG)

The config with init command seems not work properly, when i do some init with dump, i have MRES = 14 or 13 ...
[klippy.log](https://github.com/KevinOConnor/klipper/files/3747107/klippy.log)
![Capture](https://user-images.githubusercontent.com/8688892/67150458-eb2c5980-f2b7-11e9-806f-e7418ed311f0.PNG)
the cs pin is on extruder pin because i want try other place with the driver, for test it
[printer.cfg.log](https://github.com/KevinOConnor/klipper/files/3747109/printer.cfg.log)

**Comment by KevinOConnor** [comment]
How did you connect the jumpers on the skr v1.3?  If there are any other connected devices that use spi then all must be configured in klipper.  I've also seen reports of various tmc5160 step stick boards that need modification to be used properly - I don't know if that is needed for "tmc 5160 v1.2 from bigreetech".

-Kevin

**Comment by Akex2** [comment]
![8625ADF3-0932-4CAC-A74A-6BF850AEF82F](https://user-images.githubusercontent.com/8688892/67154939-d1653380-f304-11e9-9c4d-803a43da1cd7.jpeg)

**Comment by Akex2** [comment]
at the top is my board, and this is the setup for spi, i don't use sensorless
![Capture](https://user-images.githubusercontent.com/8688892/67154973-91528080-f305-11e9-9150-9bd44046d825.PNG)

there aren't other spi device on that board

For the V1.2 of this driver, no need modification for use in spi.

i don,t know where is the error :(

**Comment by vumario** [comment]
SKR board has SLP and RST pins connected together, but on TMC5160 those are CLK and SDO pins. To get SPI working correctly, you must cut off or otherwise disconnect CLK pin on your TMC5160 drivers

**Comment by lenne0815** [comment]
> 
> 
> SKR board has SLP and RST pins connected together, but on TMC5160 those are CLK and SDO pins. To get SPI working correctly, you must cut off or otherwise disconnect CLK pin on your TMC5160 drivers

This is the right answer.

**Comment by KevinOConnor** [comment]
Any further updates on this?  It sounds like the issue is thought to be a wiring issue with the stepsticks.

-Kevin

**Comment by gaggi** [comment]
> there aren't other spi device on that board
> 
> For the V1.2 of this driver, no need modification for use in spi.
> 
> i don,t know where is the error :(

That is a misjudgment, they added a pull-up resistor on v1.2 that pulls the CLK pin low so you don't need to solder a jumper wire from clock to ground, but you still need to remove the clock pin.

**Comment by Nandox7** [comment]
I also have the SKR v1.3 with BigTreeTechTMC5160 v1.2.

@gaggi so to confirm this is the pin I need to remove in the drivers?
![Inkedexplorer_edDI8tHqwC_LI](https://user-images.githubusercontent.com/117827/68579844-016ba680-046d-11ea-8589-7efcd05e640d.jpg)

**Comment by gaggi** [comment]
@Nandox7 yes that is the pin that needs to be removed.

**Comment by Akex2** [comment]
i already bended the pin, thanks at all for your help.
i think my driver has some hardware issue.
