### ISSUE TITLE
[Pause/Resume][Runout Sensor] Runout event detected while there is still filament

### ISSUE THREAD

**Issue by FromtonRouge** [KevinOConnor/klipper#2113]
I did an 8-10 hours print last night and saw a very strange bug with the filament runout detection.

I had 8-9 runout events detected during the print although the filament was still in the runout sensor like the image below.

![IMG_20191026_124145442](https://user-images.githubusercontent.com/1663920/67618328-48f7fe80-f7ee-11e9-8708-9223b222e4bc.jpg)

I even had a runout event detected just after resuming the print.
How is it possible,  is there something wrong in my configuration file? Could it be an electrical issue on my board (MKS Gen L) or my sensor? Any idea on this?

Thanks

[klippy.log](https://github.com/KevinOConnor/klipper/files/3774735/klippy.log)

**Comment by Arksine** [comment]
Most likely its the switch or wiring.  I notice that you have the switch pin inverted, which means that you are likely using a switch that is normally open.  I would recommend using a normally closed switch.  With a NC switch a wiring or mechanical issue won't trigger a runout, it would trigger an Insert which can only happen if the printer is ready/idle.

**Comment by tonn0297** [comment]
i have +1000h on the klipper runout detection. i would say its a hardware bug not a software.

**Comment by FromtonRouge** [comment]
Ok I desoldered and changed the wiring of the switch and it's now a normaly closed one. Didn't know about this trick, it's simple and it should work. Thanks!
