### ISSUE TITLE
MCU shutdown: Timer too close

### ISSUE THREAD

**Issue by fakio87** [KevinOConnor/klipper#214]
Hi, I have set up Klipper successfully but have issues when printing (machine stops, printer is disconnecting)

I am running a CR-10, confirgured with the standard CR-10 config. Connecting seem to work, heating seem to result in issues after some time.

I get the following log from the terminal:

Send: N3657 M204 S500*84
Recv: // Unknown command:"M204"
Recv: ok
Send: N3658 M205 X12 Y12*29
Recv: // Unknown command:"M205"
Recv: ok
Send: N3659 G1 F1800 X69.199 Y59.906 E289.27195*50
Recv: ok
Send: N3660 G1 X69.199 Y59.806*22
Recv: ok
Send: N3661 M204 S5000*97
Recv: // Unknown command:"M204"
Recv: ok
Send: N3662 M205 X30 Y30*20
Recv: // Unknown command:"M205"
Recv: ok
Send: N3663 G0 F4885.7 X68.799 Y59.693*111
Recv: ok
Send: N3664 M204 S500*84
Recv: // Unknown command:"M204"
Recv: ok
Send: N3665 M205 X12 Y12*19
Recv: // Unknown command:"M205"
Recv: ok
Send: N3666 M105*18
Recv: ok T0:192.4 /192.0 B:70.0 /70.0
Send: N3667 G1 F1800 X68.799 Y107.655 E290.86717*4
Recv: ok
Send: N3668 G1 X68.799 Y107.755*42
Recv: // MCU 'mcu' shutdown: Timer too close
Recv: // This is generally indicative of an intermittent
Recv: // communication failure between micro-controller and host.
Recv: // Once the underlying issue is corrected, use the
Recv: // "FIRMWARE_RESTART" command to reset the firmware, reload the
Recv: // config, and restart the host software.
Recv: !! Printer is shutdown
Changing monitoring state from 'Printing' to 'Operational'

**# In the log file the following is logged after the same message as in the terminal:**

Stats 2206.1: gcodein=108319 mcu: mcu_awake=0.016 mcu_task_avg=0.000134 mcu_task_stddev=0.000165 bytes_write=87329 bytes_read=104134 bytes_retransmit=1791 bytes_invalid=0 send_seq=2659 receive_seq=2659 r$
MCU 'mcu' shutdown: Timer too close
This is generally indicative of an intermittent
communication failure between micro-controller and host.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

Stats 2207.1: gcodein=108327 mcu: mcu_awake=0.016 mcu_task_avg=0.000134 mcu_task_stddev=0.000165 bytes_write=87349 bytes_read=104247 bytes_retransmit=1791 bytes_invalid=0 send_seq=2661 receive_seq=2661 r$
Stats 2208.1: gcodein=108327 mcu: mcu_awake=0.016 mcu_task_avg=0.000134 mcu_task_stddev=0.000165 bytes_write=87397 bytes_read=104412 bytes_retransmit=1791 bytes_invalid=0 send_seq=2665 receive_seq=2665 r$
Stats 2209.1: gcodein=108332 mcu: mcu_awake=0.008 mcu_task_avg=0.000087 mcu_task_stddev=0.000101 bytes_write=87417 bytes_read=104539 bytes_retransmit=1791 bytes_invalid=0 send_seq=2667 receive_seq=2667 r$

Any idea how to solve this?

**Comment by KevinOConnor** [comment]
In order for us to assist, you need to attach the klippy.log file as described at:
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin
