### ISSUE TITLE
Klipper reports temp 0 until restarted

### ISSUE THREAD

**Issue by mrvanes** [KevinOConnor/klipper#2148]
On cold boot, klippy continously reports tool and bed temp 0, until I give a restart in terminal window of octoprint:
```
Send: M105
Recv: ok B:0.0 /0.0 T0:0.0 /0.0
Send: M105
Recv: ok B:0.0 /0.0 T0:0.0 /0.0
Send: restart
Recv: ok
Recv: // Klipper state: Disconnect
Send: M105
Recv: ok T:0
Recv: // Klipper state: Ready
Send: M105
Recv: ok B:20.2 /0.0 T0:20.0 /0.0
Send: M105
Recv: ok B:20.3 /0.0 T0:20.0 /0.0
```
Attached is the klippy log including the restart command
[klippy.log](https://github.com/KevinOConnor/klipper/files/3810706/klippy.log)

**Comment by KevinOConnor** [comment]
The log indicates a `Timeout with MCU 'mcu' ` error.  If this is just a one off, then nothing to worry about.  If it reoccurs, the best advice we have is at: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin

**Comment by KevinOConnor** [comment]
Oh, it looks like you've done a custom install of the software.  If this problem occurs reliably on a reboot, then check for ModemManager (or similar) on the host machine - it's known to cause issues like the above.

-Kevin

**Comment by mrvanes** [comment]
Removed modemmanager, problem gone. Thanks!!
