### ISSUE TITLE
Question: Dual End Stops?

### ISSUE THREAD

**Issue by theopensourcerer** [KevinOConnor/klipper#216]
Hi, I'm building a CoreXY printer and plan to use end stops for both max and min on all three axis.
I'm not certain from the example.cfg and the FAQ if/how to configure these.

TIA

**Comment by wizhippo** [comment]
At the moment the end stops are only used for homing so there is no option to have both.  Only one at the home position on each axis.

**Comment by KevinOConnor** [comment]
Support for run-time checking of end stops is on the Todo list.  I'm going to close this issue for now as it doesn't seem like anyone is actively developing it right now.
