### ISSUE TITLE
Shared motor for extruders

### ISSUE THREAD

**Issue by Akex2** [KevinOConnor/klipper#2171]
Hi
I have a issue with conf file but not just that : 
My printer has 4 extruder but just one motor for all
It's my old prototype for uderstand how it work : 
https://www.youtube.com/watch?v=AvobluGq-zE

https://www.youtube.com/watch?v=yvdoWnII3OA

But i have a issue in conf file because i "used multiple times" the same pin. eh yes ;) 
But it's ok for me !
I search this error and go out. ;)
I do that : 
![Capture1](https://user-images.githubusercontent.com/8688892/68697493-3405c400-057f-11ea-9916-53c890f7a630.PNG)

Klipper boot it's good! yes... but the strange think is now : 
- when i use only one extruder in print is ok(1 or 2 or 3 ...).
- but when i use 2 or more:
    the first extruder work well
    but after the first change the extruder go in a wrong way ! 
    and after that the extruder keep this and the wrong way ( extrude= retract - retract= extrude)
    i tryed to retake the first extruder taked in the print and it turn also in a wrong way

After that i do that : 

![Capture2](https://user-images.githubusercontent.com/8688892/68698081-724fb300-0580-11ea-8349-1bea2bfaf647.PNG)

But with this modification klipper take the conf of the last extruder in the config file, and never change it( and i need to change the step_distance, the drive gear didn't have the exact same diameter)

I tryed to find the good way in toolhead.py
![Capture3](https://user-images.githubusercontent.com/8688892/68698925-446b6e00-0582-11ea-82f3-0c339a55b091.PNG)
If i good remember, comment 418 ligne and the wrong way go out, but is the same, the extruder never change and never change the setup for step distance.

Can you help me to fix that and maybe add a option for one motor used multiple times.
Thanks

[printer.cfg.LOG](https://github.com/KevinOConnor/klipper/files/3837591/printer.cfg.LOG)
[klippy.LOG](https://github.com/KevinOConnor/klipper/files/3837592/klippy.LOG)

**Comment by KevinOConnor** [comment]
> My printer has 4 extruder but just one motor for all

Interesting.

> But i have a issue in conf file because i "used multiple times" the same pin. 

It's not valid to disable those pin checks.  If one creates multiple extruders in the micro-controller it will just lead to chaos.

It would be necessary for the host code to create just one stepper object, and then share it among multiple extruders.  (Similar to how the shared_heater code works.)

-Kevin

**Comment by vladbabii** [comment]
@Akex2 your issue with reversed direction might be because you do a retract as the last move (asumption on my part). Can you do a small extude before changing extruders ?

**Comment by Akex2** [comment]
Thx all for yours reply
Ok @KevinOConnor 
I try do some change but is not easy to understand how to do that properly
I need just shared the pin not other in stepper.
I do that, but i think is not enought,  help is really apreciated 
![Capture](https://user-images.githubusercontent.com/8688892/69083907-59914280-0a43-11ea-8a77-96f24a273310.PNG)
Thx

**Comment by aschor** [comment]
Hi, is there a workaround for now ? I have a printer with hotswappable tool head, so I want to be able to use same pins for motor and sensors , but with different values for nozzle_size and pid values ... 

I can if I change the config manually each time I switch the toolhead but ...... that's not quite user friendly...

**Comment by ld3300** [comment]
Okay, I think I have figured out roughly what needs to happen, but it will take me a while.  I'm assuming we want to try and also include the option to have the second instance reverse driven compared to the first, as in #2517.  I'm slow, so don't hold your breath.

**Comment by EzDzO** [comment]
Hi, I have a different setup, but the same problem. 

I have a single extruder motor and a single heater but 2 different nozzle sizes that I can change using a stepper motor. 

Basically I need to create two extruder objects that have the same heater, the same sensor , the same pid values and the same stepper motor, but two different nozzle sizes and pressure advance settings.

Do you have any updates?

**Comment by KevinOConnor** [comment]
> Basically I need to create two extruder objects that have the same heater, the same sensor , the same pid values and the same stepper motor, but two different nozzle sizes and pressure advance settings.

In this situation, just define one extruder in the config file and create `T0` and `T1` macros that alter the pressure_advance setting (via the `SET_PRESSURE_ADVANCE` command).  The nozzle_size in the config is just used for internal sanity checks - set the config to the largest possible nozzle size you will be using.

-Kevin

**Comment by EzDzO** [comment]
> > Basically I need to create two extruder objects that have the same heater, the same sensor , the same pid values and the same stepper motor, but two different nozzle sizes and pressure advance settings.
> 
> 
> 
> In this situation, just define one extruder in the config file and create `T0` and `T1` macros that alter the pressure_advance setting (via the `SET_PRESSURE_ADVANCE` command).  The nozzle_size in the config is just used for internal sanity checks - set the config to the largest possible nozzle size you will be using.
> 
> 
> 
> -Kevin

Ok, that makes sense.

Thank you

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive.  It would be a nice feature to add, but it doesn't look like anyone is currently working on it.

-Kevin
