### ISSUE TITLE
Can't update to V0.8.0

### ISSUE THREAD

**Issue by AndyWo83** [KevinOConnor/klipper#2178]
Hi,
yesterday I wanted to install Klipper V0.8.0.
If I make a "git pull" in my klipper directory on my Raspberry PI3B + and the other commands from the installation guide, then I will finally see the V0.7.0 that was installed.
What am I doing wrong here?

Dump Klippy Log for Issue Bot:
[klippy.log](https://github.com/KevinOConnor/klipper/files/3851703/klippy.log)

**Comment by KevinOConnor** [comment]
You must attach the Klipper log for us to assist.

-Kevin
