### ISSUE TITLE
SKR Mini E3 V1.0 - BLTouch - Always Triggered State

### ISSUE THREAD

**Issue by dshag86** [KevinOConnor/klipper#2215]
Unknown BLTouch version, maybe v2.0? 

No matter what configuration I use, or pin on the board, the BLTouch is always in a triggered state. I have tried both the pin_up_touch_mode_reports_triggered: True/False && pin_up_reports_not_triggered: True/False. I can successfully send pin up and pin down without issue. 

Attached is the log after doing a test-bltouch.gcode

[klippy.zip](https://github.com/KevinOConnor/klipper/files/3888587/klippy.zip)

**Comment by ld3300** [comment]
When you send your debug commands to the BLTouch does the LED go out when it is extended?

**Comment by dshag86** [comment]
That's correct. Visually, the BLTouch works as intended.

**Comment by ld3300** [comment]
I'm not very good with parsing the log, so I didn't see anything that stuck out to me. You can try setting up some feedback to see what the pin state is doing.
Add something like this to your config file:

```
[gcode_button tempSense]
pin: ^sensor_pin   #put sensor pin for BLtouch here, assign an unused pin to BLtouch temporarily
press_gcode:
    RESPOND TYPE=echo MSG="PIN UP"
release_gcode:
    RESPOND TYPE=echo MSG="PIN DOWN"
```
Then send BLTOUCH_DEBUG COMMAND=pin_down and see what the terminal output says
Also try with pin_up.

If neither of those produce a result you may want to try turning the adjustment screw on the top as the probe may not be retracting far enough to be sensed.

You can also try applying power and issuing the commands with a multimeter connected to measure the voltage on the sense pin

**Comment by dshag86** [comment]
I'll try this and report back in a few days when I get a chance to tinker.

Thank you

**Comment by dshag86** [comment]
Unknown command:"RESPOND"

Tried: RESPOND_TYPE and RESPONDTYPE

all three are unknown commands

**Comment by KevinOConnor** [comment]
If you are able to control the bltouch, but are not able to read a signal from the bltouch, it generally indicates that the sensor pin is not configured with the correct pin or is not wired correctly.  The best advice we have is the instructions in at: https://www.klipper3d.org/BLTouch.html

-Kevin

**Comment by dshag86** [comment]
So I have it wired correctly, however the code given to me above I believe
is incorrect as it returns an error for that line.

The issue is that klipper only sees the bltouch as triggered regardless of
state or pin configuration. So either my bltouch is all of a sudden broken,
or I’m missing something here.

**Comment by KevinOConnor** [comment]
Alas, it doesn't seem anyone has any further advice to share here.  The best info I have is at: https://www.klipper3d.org/BLTouch.html

-Kevin

**Comment by BlackStump** [comment]
just my personal annoyance if a log is zipped I will not look, creates extra steps and cleanup on my pc
but looking at your log you have the wrong sensor pin

[bltouch]
sensor_pin: PC14
control_pin: PA1

**Comment by BlackStump** [comment]
![skr-mini-e3](https://user-images.githubusercontent.com/26130487/71757721-0ccad380-2eec-11ea-8b4b-18bd7ec02435.png)

**Comment by dshag86** [comment]
Without having the ability to look at the moment, are you suggesting this
is the correct pin config, or this is what I have and its wrong? I have
tried multiple pin configurations and mappings

Thanks!

**Comment by BlackStump** [comment]
I have given you the correct pins and shown the connections on the board which are servo and probe.

**Comment by dshag86** [comment]
Thank you, I believe I had the pin configuration correct per the schematic.
But I will try again with your suggestion when I have a chance to tinker.

Thank you again!

**Comment by FanDjango** [comment]
Hmm, in your log I can see:
```
[bltouch]
sensor_pin = ^PC2
control_pin = PA1
x_offset = -45
y_offset = -10
z_offset = 1.6
pin_move_time = 0.4
```

In the diagram posted by @BlackStump I see it should be PC14, that's what he was saying.

So there is a discrepancy you need to clear up first I think.

**Comment by dshag86** [comment]
The PC2 pin is the z end stop, which was suggested to be used instead of
PC14. However I do remember switching between the two when I was diagnosing
this issue a while back, still getting the same result.

**Comment by FanDjango** [comment]
OkiDoki. What about connecting some real switch on that pin (you might have a spare one) INSTEAD of the BLTouch and testing with that?

By the way, the wires to connect for the sensor signal pin, some people wrongly believe that it is not important which one goes to ground and which one goes to the PC14. It is not like a real switch. If you put the black one into PC14 it will be continuously triggered because BLACK is GND and will pull down the PC14 pin. Make sure you have the WHITE one on the PC14.

**Comment by dshag86** [comment]
I’ll check the wiring when I get a chance.
This is good insight, thank you.

**Comment by KevinOConnor** [comment]
Okay, I'm going to close this as it looks like the conversation has concluded.

-Kevin
