### ISSUE TITLE
Internal error on command:"G1"

### ISSUE THREAD

**Issue by technoplunk** [KevinOConnor/klipper#2237]
Klipper just shutdown mid print with the following error:

Internal error on command:"G1"

[klippy.log](https://github.com/KevinOConnor/klipper/files/3914682/klippy.log)

**Comment by KevinOConnor** [comment]
This looks like a dup of #2225 - which was fixed recently fixed (commit 988ee575).

-Kevin

**Comment by technoplunk** [comment]
Awesome. I'll update and try the print again tomorrow. It's too late to run it again tonight,

**Comment by technoplunk** [comment]
Ok, I ran the exact same gcode and it finished successfully. Looks like the fix was good.
