### ISSUE TITLE
Arduino Due + I2C OLED 128x64 - ssd1306

### ISSUE THREAD

**Issue by 1walkerit** [KevinOConnor/klipper#2259]
hi
I am trying to connect i2c OLED dispaly and Arduino Due. Reading the last issue it could be working but I still have problem. I connect i2c to pins 20,21 (SDA,SCL)  and no success, Can you help me to solve the problem?
![image](https://user-images.githubusercontent.com/19901103/70450926-d5ac0280-1aa4-11ea-9f96-32e6f8445c0f.png)
[klippy.log](https://github.com/KevinOConnor/klipper/files/3940537/klippy.log)

**Comment by KevinOConnor** [comment]
Try:
```
[display]
lcd_type = ssd1306
i2c_mcu = mcu
i2c_bus = twi1
```

-Kevin

**Comment by 1walkerit** [comment]
> [display]
lcd_type = ssd1306
i2c_mcu = mcu
i2c_bus = twi1

GREAT!
it is working, thank you very much and, please, close this issue. (y)
