### ISSUE TITLE
Unable to open port: [Errno 2] No such file or directory: '/dev/rpmsg_pru30'

### ISSUE THREAD

**Issue by 3DSTB** [KevinOConnor/klipper#226]
found this in the klipper.log

"Unable to open port: [Errno 2] No such file or directory: '/dev/rpmsg_pru30'"

ls -l /dev/rpmsg_pru3*
gives
ls: cannot access /dev/rpmsg_pru3*: No such file or directory

I use the latest Iot Image: bone-debian-8.10-iot-armhf-2018-03-06-4gb.img.xz

This is the uEnv.txt:
#Docs: http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

uname_r=4.4.113-ti-r147
#uuid=
#dtb=

###U-Boot Overlays###
###Documentation: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays
###Master Enable
enable_uboot_overlays=1
###
###Overide capes with eeprom
#uboot_overlay_addr0=/lib/firmware/<file0>.dtbo
#uboot_overlay_addr1=/lib/firmware/<file1>.dtbo
#uboot_overlay_addr2=/lib/firmware/<file2>.dtbo
#uboot_overlay_addr3=/lib/firmware/<file3>.dtbo
###
###Additional custom capes
#uboot_overlay_addr4=/lib/firmware/<file4>.dtbo
#uboot_overlay_addr5=/lib/firmware/<file5>.dtbo
#uboot_overlay_addr6=/lib/firmware/<file6>.dtbo
#uboot_overlay_addr7=/lib/firmware/<file7>.dtbo
###
###Custom Cape
#dtb_overlay=/lib/firmware/<file8>.dtbo
###
###Disable auto loading of virtual capes (emmc/video/wireless/adc)
#disable_uboot_overlay_emmc=1
disable_uboot_overlay_video=1
disable_uboot_overlay_audio=1
disable_uboot_overlay_wireless=1
#disable_uboot_overlay_adc=1
###
###PRUSS OPTIONS
###pru_rproc (4.4.x-ti kernel)
uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-4-TI-00A0.dtbo
###pru_uio (4.4.x-ti, 4.14.x-ti & mainline/bone kernel)
#uboot_overlay_pru=/lib/firmware/AM335X-PRU-UIO-00A0.dtbo
###
###Cape Universal Enable
enable_uboot_cape_universal=1
###
###Debug: disable uboot autoload of Cape
#disable_uboot_overlay_addr0=1
#disable_uboot_overlay_addr1=1
#disable_uboot_overlay_addr2=1
#disable_uboot_overlay_addr3=1
###
###U-Boot fdt tweaks... (60000 = 384KB)
#uboot_fdt_buffer=0x60000
###U-Boot Overlays###

cmdline=coherent_pool=1M net.ifnames=0 quiet

#In the event of edid real failures, uncomment this next line:
#cmdline=coherent_pool=1M net.ifnames=0 quiet video=HDMI-A-1:1024x768@60e

##enable Generic eMMC Flasher:
##make sure, these tools are installed: dosfstools rsync
#cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh

This
dmesg | grep pinctrl
returns
[    0.459939] pinctrl core: initialized pinctrl subsystem
[    1.225051] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568

and this
/lib/firmware$ ls -la /lib/firmware/
this
total 58720
drwxr-xr-x 15 root root   12288 Mar  6 16:15 .
drwxr-xr-x 15 root root    4096 Mar  6 16:09 ..
-rw-r--r--  1 root root    8593 Mar  5 06:24 ACME-revB.dtbo
-rw-r--r--  1 root root    1102 Mar  6 16:15 ADAFRUIT-SPI0-00A0.dtbo
-rw-r--r--  1 root root    1105 Mar  6 16:15 ADAFRUIT-SPI1-00A0.dtbo
-rw-r--r--  1 root root     867 Mar  6 16:15 ADAFRUIT-UART1-00A0.dtbo
-rw-r--r--  1 root root     867 Mar  6 16:15 ADAFRUIT-UART2-00A0.dtbo
-rw-r--r--  1 root root     867 Mar  6 16:15 ADAFRUIT-UART4-00A0.dtbo
-rw-r--r--  1 root root     867 Mar  6 16:15 ADAFRUIT-UART5-00A0.dtbo
-rw-r--r--  1 root root     378 Mar  5 06:24 AM335X-20-00A0.dtbo
-rw-r--r--  1 root root   36296 Nov  8 20:05 am335x-pru0-fw
-rw-r--r--  1 root root   35392 Nov  8 20:05 am335x-pru1-fw
-rw-r--r--  1 root root    2402 Mar  5 06:24 AM335X-PRU-RPROC-4-4-TI-00A0.dtbo
-rw-r--r--  1 root root    2958 Mar  5 06:24 AM335X-PRU-RPROC-4-4-TI-PRUCAPE-00A0.dtbo
-rw-r--r--  1 root root    2910 Mar  5 06:24 AM335X-PRU-RPROC-4-9-TI-00A0.dtbo
-rw-r--r--  1 root root     853 Mar  5 06:24 AM335X-PRU-UIO-00A0.dtbo
-rw-r--r--  1 root root    1205 Mar  5 06:24 am33xx_pwm-00A0.dtbo
drwxr-xr-x  2 root root    4096 Mar  6 16:01 ar3k
-rw-r--r--  1 root root  153416 Aug 30  2017 ar5523.bin
-rw-r--r--  1 root root   70624 Aug 30  2017 ar7010_1_1.fw
-rw-r--r--  1 root root   70624 Aug 30  2017 ar7010.fw
-rw-r--r--  1 root root   51312 Aug 30  2017 ar9271.fw
drwxr-xr-x 10 root root    4096 Mar  6 16:01 ath10k
-rw-r--r--  1 root root  246804 Aug 30  2017 ath3k-1.fw
drwxr-xr-x  5 root root    4096 Mar  6 15:55 ath6k
drwxr-xr-x  2 root root    4096 Mar  6 16:01 ath9k_htc
-rw-r--r--  1 root root     711 Mar  5 06:24 BB-ADC-00A0.dtbo
-rw-r--r--  1 root root    2418 Mar  5 06:24 BB-BBBMINI-00A0.dtbo
-rw-r--r--  1 root root    4226 Mar  5 06:24 BB-BBBW-WL1835-00A0.dtbo
-rw-r--r--  1 root root    4839 Mar  5 06:24 BB-BBGW-WL1835-00A0.dtbo
-rw-r--r--  1 root root    3518 Mar  5 06:24 BB-BELA-B2.dtbo
-rw-r--r--  1 root root    5585 Mar  5 06:24 BB-BONE-4D4C-01-00A1.dtbo
-rw-r--r--  1 root root    4409 Mar  5 06:24 BB-BONE-4D4N-01-00A1.dtbo
-rw-r--r--  1 root root    5597 Mar  5 06:24 BB-BONE-4D4R-01-00A1.dtbo
-rw-r--r--  1 root root    4613 Mar  5 06:24 BB-BONE-4D5C-01-00A1.dtbo
-rw-r--r--  1 root root    3438 Mar  5 06:24 BB-BONE-4D5N-01-00A1.dtbo
-rw-r--r--  1 root root    4516 Mar  5 06:24 BB-BONE-4D5R-01-00A1.dtbo
-rw-r--r--  1 root root    4578 Mar  5 06:24 BB-BONE-4D7C-01-00A1.dtbo
-rw-r--r--  1 root root    3438 Mar  5 06:24 BB-BONE-4D7N-01-00A1.dtbo
-rw-r--r--  1 root root    4516 Mar  5 06:24 BB-BONE-4D7R-01-00A1.dtbo
-rw-r--r--  1 root root    2859 Mar  5 06:24 BB-BONE-AUDI-02-00A0.dtbo
-rw-r--r--  1 root root    2964 Mar  5 06:24 BB-BONE-BACONE-00A0.dtbo
-rw-r--r--  1 root root    1415 Mar  5 06:24 BB-BONE-CRYPTO-00A0.dtbo
-rw-r--r--  1 root root    2247 Mar  5 06:24 BB-BONE-DVID-01-00A3.dtbo
-rw-r--r--  1 root root    1440 Mar  5 06:24 BB-BONE-eMMC1-01-00A0.dtbo
-rw-r--r--  1 root root    5781 Mar  5 06:24 BB-BONE-LCD3-01-00A2.dtbo
-rw-r--r--  1 root root    5778 Mar  5 06:24 BB-BONE-LCD4-01-00A1.dtbo
-rw-r--r--  1 root root    4556 Mar  5 06:24 BB-BONE-LCD5-01-00A1.dtbo
-rw-r--r--  1 root root    4502 Mar  5 06:24 BB-BONE-LCD7-01-00A1.dtbo
-rw-r--r--  1 root root    5760 Mar  5 06:24 BB-BONE-LCD7-01-00A2.dtbo
-rw-r--r--  1 root root    6804 Mar  5 06:24 BB-BONE-LCD7-01-00A3.dtbo
-rw-r--r--  1 root root    5514 Mar  5 06:24 BB-BONE-NH7C-01-A0.dtbo
-rw-r--r--  1 root root    2618 Mar  5 06:24 BB-BONE-REACH-00A0.dtbo
-rw-r--r--  1 root root    2344 Mar  5 06:24 BB-BONE-REACH-00B0.dtbo
-rw-r--r--  1 root root    6229 Mar  5 06:24 BB-BONE-REPLICAP-00A4.dtbo
-rw-r--r--  1 root root    6579 Mar  5 06:24 BB-BONE-REPLICAP-00B1.dtbo
-rw-r--r--  1 root root    6559 Mar  5 06:24 BB-BONE-REPLICAP-00B2.dtbo
-rw-r--r--  1 root root    6559 Mar  5 06:24 BB-BONE-REPLICAP-00B3.dtbo
-rw-r--r--  1 root root    6229 Mar  5 06:24 BB-BONE-REPLICAP-0A4A.dtbo
-rw-r--r--  1 root root    6657 Mar  5 06:24 BB-BONE-REPLICAP-0B3A.dtbo
-rw-r--r--  1 root root     887 Mar  5 06:24 BB-BONE-SERL-03-00A1.dtbo
-rw-r--r--  1 root root    4812 Mar  5 06:24 BB-BONE-WL1837-00A0.dtbo
-rw-r--r--  1 root root     594 Mar  5 06:24 BB-BONE-WTHR-01-00B0.dtbo
-rw-r--r--  1 root root     871 Mar  5 06:24 BB-CAN1-00A0.dtbo
-rw-r--r--  1 root root    5175 Mar  5 06:24 BB-CAPE-DISP-CT4-00A0.dtbo
-rw-r--r--  1 root root    5121 Mar  5 06:24 BB-GATEWAY-WL1837-00A0.dtbo
-rw-r--r--  1 root root    4083 Mar  5 06:24 BB-GREEN-HDMI-00A0.dtbo
-rw-r--r--  1 root root    5127 Mar  5 06:24 BB-HDMI-TDA998x-00A0.dtbo
-rw-r--r--  1 root root     960 Mar  5 06:24 BB-I2C1-00A0.dtbo
-rw-r--r--  1 root root     960 Mar  5 06:24 BB-I2C1-FAST-00A0.dtbo
-rw-r--r--  1 root root    1832 Mar  5 06:24 BB-I2C1-MCP7940X-00A0.dtbo
-rw-r--r--  1 root root    1901 Mar  5 06:24 BB-I2C1-PCA9685-00A0.dtbo
-rw-r--r--  1 root root     960 Mar  5 06:24 BB-I2C2-00A0.dtbo
-rw-r--r--  1 root root     960 Mar  5 06:24 BB-I2C2-FAST-00A0.dtbo
-rw-r--r--  1 root root     559 Mar  5 06:24 BB-I2C2-PCF8523-00A0.dtbo
-rw-r--r--  1 root root   14004 Mar  5 06:24 BBIM-00A0.dtbo
-rw-r--r--  1 root root    3095 Mar  5 06:24 bb-justboom-amp-00A0.dtbo
-rw-r--r--  1 root root    3095 Mar  5 06:24 bb-justboom-dac-00A0.dtbo
-rw-r--r--  1 root root    2115 Mar  5 06:24 bb-justboom-digi-00A0.dtbo
-rw-r--r--  1 root root    1483 Mar  5 06:24 BB-LCD-ADAFRUIT-18-SPI1-00A0.dtbo
-rw-r--r--  1 root root    3013 Mar  5 06:24 BB-NHDMI-TDA998x-00A0.dtbo
-rw-r--r--  1 root root    2453 Mar  5 06:24 BBORG_PROTO-00A2.dtbo
-rw-r--r--  1 root root    1198 Mar  5 06:24 BB-PWM0-00A0.dtbo
-rw-r--r--  1 root root    1198 Mar  5 06:24 BB-PWM1-00A0.dtbo
-rw-r--r--  1 root root    1198 Mar  5 06:24 BB-PWM2-00A0.dtbo
-rw-r--r--  1 root root    1016 Mar  5 06:24 BB-PWM-TIMER-P8.07.dtbo
-rw-r--r--  1 root root    1016 Mar  5 06:24 BB-PWM-TIMER-P8.08.dtbo
-rw-r--r--  1 root root    1016 Mar  5 06:24 BB-PWM-TIMER-P8.09.dtbo
-rw-r--r--  1 root root    1016 Mar  5 06:24 BB-PWM-TIMER-P8.10.dtbo
-rw-r--r--  1 root root    1525 Mar  5 06:24 BB-RELAY-4PORT-00A0.dtbo
-rw-r--r--  1 root root    1824 Mar  5 06:24 BB-RTC-01-00A0.dtbo
-rw-r--r--  1 root root    1079 Mar  5 06:24 BB-SPI0-ADS8688-0A00.dtbo
-rw-r--r--  1 root root    1082 Mar  5 06:24 BB-SPI0-MCP3008-00A0.dtbo
-rw-r--r--  1 root root    1523 Mar  5 06:24 BB-SPIDEV0-00A0.dtbo
-rw-r--r--  1 root root    1235 Mar  5 06:24 BB-SPIDEV1-00A0.dtbo
-rw-r--r--  1 root root    1239 Mar  5 06:24 BB-SPIDEV1A1-00A0.dtbo
-rw-r--r--  1 root root    1075 Mar  5 06:24 BB-UART1-00A0.dtbo
-rw-r--r--  1 root root    1075 Mar  5 06:24 BB-UART2-00A0.dtbo
-rw-r--r--  1 root root     915 Mar  5 06:24 BB-UART2-RTSCTS-00A0.dtbo
-rw-r--r--  1 root root     867 Mar  5 06:24 BB-UART3-00A0.dtbo
-rw-r--r--  1 root root    1075 Mar  5 06:24 BB-UART4-00A0.dtbo
-rw-r--r--  1 root root    1127 Mar  5 06:24 BB-UART4-RS485-00A0.dtbo
-rw-r--r--  1 root root    1075 Mar  5 06:24 BB-UART5-00A0.dtbo
-rw-r--r--  1 root root    5775 Mar  5 06:24 BB-VIEW-LCD4-01-00A0.dtbo
-rw-r--r--  1 root root    5775 Mar  5 06:24 BB-VIEW-LCD7-01-00A0.dtbo
-rw-r--r--  1 root root     974 Mar  5 06:24 BB-W1-P9.12-00A0.dtbo
-rw-r--r--  1 root root    7214 Mar  5 06:24 BEAGLEBOY-0013.dtbo
-rw-r--r--  1 root root     735 Mar  5 06:24 beaglelogic-00A0.dtbo
-rw-r--r--  1 root root    1171 Mar  5 06:24 bone_eqep0-00A0.dtbo
-rw-r--r--  1 root root    1187 Mar  5 06:24 bone_eqep1-00A0.dtbo
-rw-r--r--  1 root root    1187 Mar  5 06:24 bone_eqep2-00A0.dtbo
-rw-r--r--  1 root root    1187 Mar  5 06:24 bone_eqep2b-00A0.dtbo
drwxr-xr-x  2 root root    4096 Mar  6 15:57 brcm
-rw-r--r--  1 root root    3489 Mar  5 06:24 cape-bone-ibb-00A0.dtbo
-rw-r--r--  1 root root    1703 Mar  5 06:24 cape-CBB-Serial-r01.dtbo
-rw-r--r--  1 root root    9316 Mar  5 06:24 cape-univ-audio-00A0.dtbo
-rw-r--r--  1 root root   14671 Mar  5 06:24 cape-univ-emmc-00A0.dtbo
-rw-r--r--  1 root root   70377 Mar  5 06:24 cape-universal-00A0.dtbo
-rw-r--r--  1 root root  118786 Mar  5 06:24 cape-universala-00A0.dtbo
-rw-r--r--  1 root root  105028 Mar  5 06:24 cape-universalh-00A0.dtbo
-rw-r--r--  1 root root   62016 Mar  5 06:24 cape-universaln-00A0.dtbo
-rw-r--r--  1 root root   35600 Mar  5 06:24 cape-univ-hdmi-00A0.dtbo
-rw-r--r--  1 root root   13388 Mar  6 15:57 carl9170-1.fw
-rw-r--r--  1 root root    1057 Mar  5 06:24 dev-USB-PWR-CTL-00A1.dtbo
-rw-r--r--  1 root root    3183 Mar  5 06:24 DLPDLCR2000-00A0.dtbo
-rw-r--r--  1 root root    3717 Mar  5 06:24 DVK530-LCD4-01-00A0.dtbo
-rw-r--r--  1 root root    4416 Mar  5 06:24 GHI-DB-NH5C-00A0.dtbo
-rw-r--r--  1 root root    2182 Mar  5 06:24 GHI-LCD-00A0.dtbo
-rw-r--r--  1 root root    3057 Mar  5 06:24 GHI-TH-NH43C-00A0.dtbo
-rw-r--r--  1 root root    2711 Mar  5 06:24 GHI-TH-NH43R-00A0.dtbo
-rw-r--r--  1 root root    3053 Mar  5 06:24 GHI-TH-NH7C-00A0.dtbo
-rw-r--r--  1 root root   72684 Aug 30  2017 htc_7010.fw
-rw-r--r--  1 root root   50980 Aug 30  2017 htc_9271.fw
drwxr-xr-x  2 root root    4096 Mar  6 16:01 intel
-rw-r--r--  1 root root  337520 Aug 30  2017 iwlwifi-1000-5.ucode
-rw-r--r--  1 root root  337572 Aug 30  2017 iwlwifi-100-5.ucode
-rw-r--r--  1 root root  689680 Aug 30  2017 iwlwifi-105-6.ucode
-rw-r--r--  1 root root  701228 Aug 30  2017 iwlwifi-135-6.ucode
-rw-r--r--  1 root root  695876 Aug 30  2017 iwlwifi-2000-6.ucode
-rw-r--r--  1 root root  707392 Aug 30  2017 iwlwifi-2030-6.ucode
-rw-r--r--  1 root root  683996 Aug 30  2017 iwlwifi-3160-12.ucode
-rw-r--r--  1 root root  918080 Aug 30  2017 iwlwifi-3160-14.ucode
-rw-r--r--  1 root root  918212 Aug 30  2017 iwlwifi-3160-16.ucode
-rw-r--r--  1 root root  918268 Aug 30  2017 iwlwifi-3160-17.ucode
-rw-r--r--  1 root root  669872 Aug 30  2017 iwlwifi-3160-9.ucode
-rw-r--r--  1 root root 1384856 Aug 30  2017 iwlwifi-3168-21.ucode
-rw-r--r--  1 root root 1028092 Aug 30  2017 iwlwifi-3168-22.ucode
-rw-r--r--  1 root root 1036372 Aug 30  2017 iwlwifi-3168-29.ucode
-rw-r--r--  1 root root  150100 Aug 30  2017 iwlwifi-3945-2.ucode
-rw-r--r--  1 root root  187972 Aug 30  2017 iwlwifi-4965-2.ucode
-rw-r--r--  1 root root  353240 Aug 30  2017 iwlwifi-5000-2.ucode
-rw-r--r--  1 root root  340696 Aug 30  2017 iwlwifi-5000-5.ucode
-rw-r--r--  1 root root  337400 Aug 30  2017 iwlwifi-5150-2.ucode
-rw-r--r--  1 root root  454608 Aug 30  2017 iwlwifi-6000-4.ucode
-rw-r--r--  1 root root  444128 Aug 30  2017 iwlwifi-6000g2a-5.ucode
-rw-r--r--  1 root root  677296 Aug 30  2017 iwlwifi-6000g2a-6.ucode
-rw-r--r--  1 root root  679436 Aug 30  2017 iwlwifi-6000g2b-6.ucode
-rw-r--r--  1 root root  463692 Aug 30  2017 iwlwifi-6050-4.ucode
-rw-r--r--  1 root root  469780 Aug 30  2017 iwlwifi-6050-5.ucode
-rw-r--r--  1 root root  782300 Aug 30  2017 iwlwifi-7260-12.ucode
-rw-r--r--  1 root root 1049152 Aug 30  2017 iwlwifi-7260-14.ucode
-rw-r--r--  1 root root 1049284 Aug 30  2017 iwlwifi-7260-16.ucode
-rw-r--r--  1 root root 1049340 Aug 30  2017 iwlwifi-7260-17.ucode
-rw-r--r--  1 root root  680508 Aug 30  2017 iwlwifi-7260-9.ucode
-rw-r--r--  1 root root  880604 Aug 30  2017 iwlwifi-7265-12.ucode
-rw-r--r--  1 root root 1180224 Aug 30  2017 iwlwifi-7265-14.ucode
-rw-r--r--  1 root root 1180356 Aug 30  2017 iwlwifi-7265-16.ucode
-rw-r--r--  1 root root 1180412 Aug 30  2017 iwlwifi-7265-17.ucode
-rw-r--r--  1 root root  697828 Aug 30  2017 iwlwifi-7265-9.ucode
-rw-r--r--  1 root root 1002800 Aug 30  2017 iwlwifi-7265D-12.ucode
-rw-r--r--  1 root root 1384256 Aug 30  2017 iwlwifi-7265D-14.ucode
-rw-r--r--  1 root root 1384500 Aug 30  2017 iwlwifi-7265D-16.ucode
-rw-r--r--  1 root root 1383604 Aug 30  2017 iwlwifi-7265D-17.ucode
-rw-r--r--  1 root root 1385368 Aug 30  2017 iwlwifi-7265D-21.ucode
-rw-r--r--  1 root root 1028376 Aug 30  2017 iwlwifi-7265D-22.ucode
-rw-r--r--  1 root root 1036528 Aug 30  2017 iwlwifi-7265D-29.ucode
-rw-r--r--  1 root root 2345768 Aug 30  2017 iwlwifi-8000C-14.ucode
-rw-r--r--  1 root root 2351636 Aug 30  2017 iwlwifi-8000C-16.ucode
-rw-r--r--  1 root root 2394060 Aug 30  2017 iwlwifi-8000C-21.ucode
-rw-r--r--  1 root root 2120860 Aug 30  2017 iwlwifi-8000C-22.ucode
-rw-r--r--  1 root root 2227284 Aug 30  2017 iwlwifi-8000C-27.ucode
-rw-r--r--  1 root root 2309768 Aug 30  2017 iwlwifi-8000C-31.ucode
-rw-r--r--  1 root root 2389968 Aug 30  2017 iwlwifi-8265-21.ucode
-rw-r--r--  1 root root 1811984 Aug 30  2017 iwlwifi-8265-22.ucode
-rw-r--r--  1 root root 2234528 Aug 30  2017 iwlwifi-8265-27.ucode
-rw-r--r--  1 root root 2303024 Aug 30  2017 iwlwifi-8265-31.ucode
-rw-r--r--  1 root root    1946 Mar  6 15:57 LICENCE.atheros_firmware
-rw-r--r--  1 root root    4178 Mar  6 15:57 LICENCE.broadcom_bcm43xx
-rw-r--r--  1 root root    2115 Mar  6 15:57 LICENCE.rtlwifi_firmware.txt
-rw-r--r--  1 root root    2913 Mar  6 15:57 LICENCE.ti-connectivity
-rw-r--r--  1 root root     277 Mar  5 06:24 M-BB-BBG-00A0.dtbo
-rw-r--r--  1 root root     285 Mar  5 06:24 M-BB-OSD3358-SM-RED-00A0.dtbo
-rw-r--r--  1 root root   45412 Mar  6 15:57 mt7601u.bin
-rw-r--r--  1 root root    2542 Mar  5 06:24 NL-AB-BBBC-00D0.dtbo
-rw-r--r--  1 root root    3521 Mar  5 06:24 NL-AB-BBCL-00B0.dtbo
-rw-r--r--  1 root root     441 Mar  5 06:24 OSD3358-00A0.dtbo
-rw-r--r--  1 root root    1068 Mar  5 06:24 PB-I2C1-MPU-9DOF-CLICK.dtbo
-rw-r--r--  1 root root     535 Mar  5 06:24 PB-I2C1-RTC-6-CLICK.dtbo
-rw-r--r--  1 root root     527 Mar  5 06:24 PB-I2C1-RTC-CLICK.dtbo
-rw-r--r--  1 root root     527 Mar  5 06:24 PB-I2C1-RTC-PCF8523.dtbo
-rw-r--r--  1 root root     361 Mar  5 06:24 PB-I2C1-WEATHER-CLICK.dtbo
-rw-r--r--  1 root root    1068 Mar  5 06:24 PB-I2C2-MPU-9DOF-CLICK.dtbo
-rw-r--r--  1 root root     535 Mar  5 06:24 PB-I2C2-RTC-6-CLICK.dtbo
-rw-r--r--  1 root root     527 Mar  5 06:24 PB-I2C2-RTC-CLICK.dtbo
-rw-r--r--  1 root root     527 Mar  5 06:24 PB-I2C2-RTC-PCF8523.dtbo
-rw-r--r--  1 root root     361 Mar  5 06:24 PB-I2C2-WEATHER-CLICK.dtbo
-rw-r--r--  1 root root    9002 Mar  5 06:24 PB-simplegaming.dtbo
-rw-r--r--  1 root root    1813 Mar  5 06:24 PB-SPI0-ETH-CLICK.dtbo
-rw-r--r--  1 root root    1795 Mar  5 06:24 PB-SPI0-ETH-WIZ-CLICK.dtbo
-rw-r--r--  1 root root    1353 Mar  5 06:24 PB-SPI0-MICROSD-CLICK.dtbo
-rw-r--r--  1 root root    1988 Mar  5 06:24 PB-SPI0-OLEDB-CLICK.dtbo
-rw-r--r--  1 root root    1763 Mar  5 06:24 PB-SPI0-RTC-5-CLICK.dtbo
-rw-r--r--  1 root root    1646 Mar  5 06:24 PB-SPI0-THUNDER-CLICK.dtbo
-rw-r--r--  1 root root    1813 Mar  5 06:24 PB-SPI1-ETH-CLICK.dtbo
-rw-r--r--  1 root root    1795 Mar  5 06:24 PB-SPI1-ETH-WIZ-CLICK.dtbo
-rw-r--r--  1 root root    1353 Mar  5 06:24 PB-SPI1-MICROSD-CLICK.dtbo
-rw-r--r--  1 root root    1988 Mar  5 06:24 PB-SPI1-OLEDB-CLICK.dtbo
-rw-r--r--  1 root root    1763 Mar  5 06:24 PB-SPI1-RTC-5-CLICK.dtbo
-rw-r--r--  1 root root    1646 Mar  5 06:24 PB-SPI1-THUNDER-CLICK.dtbo
drwxr-xr-x  2 root root    4096 Mar  6 16:01 qca
-rw-r--r--  1 root root    7842 Mar  5 06:24 RoboticsCape-00A0.dtbo
-rw-r--r--  1 root root    8192 Jun 15  2014 rt2561.bin
-rw-r--r--  1 root root    8192 Jun 15  2014 rt2561s.bin
-rw-r--r--  1 root root    8192 Jun 15  2014 rt2661.bin
-rw-r--r--  1 root root    8192 Jun 15  2014 rt2860.bin
-rw-r--r--  1 root root    8192 Jun 15  2014 rt2870.bin
lrwxrwxrwx  1 root root      10 Jun 15  2014 rt3070.bin -> rt2870.bin
-rw-r--r--  1 root root    4096 Jun 15  2014 rt3071.bin
lrwxrwxrwx  1 root root      10 Jun 15  2014 rt3090.bin -> rt2860.bin
-rw-r--r--  1 root root    4096 Jun 15  2014 rt3290.bin
-rw-r--r--  1 root root    2048 Jun 15  2014 rt73.bin
drwxr-xr-x  2 root root    4096 Mar  6 16:01 RTL8192E
drwxr-xr-x  2 root root    4096 Mar  6 16:01 rtl_bt
drwxr-xr-x  2 root root    4096 Mar  6 16:01 rtl_nic
drwxr-xr-x  2 root root    4096 Mar  6 16:01 rtlwifi
-rw-r--r--  1 root root    2955 Mar  5 06:24 seeed-4mic-voicecard-00A0.dtbo
drwxr-xr-x  2 root root    4096 Mar  6 16:09 ti-connectivity
-rw-r--r--  1 root root     375 Mar  5 06:24 uio_pruss_enable-00A0.dtbo
-rw-r--r--  1 root root  118774 Mar  5 06:24 univ-all-00A0.dtbo
-rw-r--r--  1 root root   62008 Mar  5 06:24 univ-bbb-EVA-00A0.dtbo
-rw-r--r--  1 root root   70373 Mar  5 06:24 univ-bbb-EVx-00A0.dtbo
-rw-r--r--  1 root root  105020 Mar  5 06:24 univ-bbb-Exx-00A0.dtbo
-rw-r--r--  1 root root   75766 Mar  5 06:24 univ-bbb-xVA-00A0.dtbo
-rw-r--r--  1 root root   84131 Mar  5 06:24 univ-bbb-xVx-00A0.dtbo
-rw-r--r--  1 root root  118778 Mar  5 06:24 univ-bbb-xxx-00A0.dtbo
-rw-r--r--  1 root root  107110 Mar  5 06:24 univ-bbgw-00A0.dtbo
-rw-r--r--  1 root root   82622 Mar  5 06:24 univ-bbgw-EW-00A0.dtbo
-rw-r--r--  1 root root  105020 Mar  5 06:24 univ-bbgw-Ex-00A0.dtbo
-rw-r--r--  1 root root   96380 Mar  5 06:24 univ-bbgw-xW-00A0.dtbo
-rw-r--r--  1 root root  118778 Mar  5 06:24 univ-bbgw-xx-00A0.dtbo
-rw-r--r--  1 root root   75762 Mar  5 06:24 univ-emmc-00A0.dtbo
-rw-r--r--  1 root root  105016 Mar  5 06:24 univ-hdmi-00A0.dtbo
-rw-r--r--  1 root root   70369 Mar  5 06:24 univ-nhdmi-00A0.dtbo
drwxr-xr-x  2 root root    4096 Mar  6 15:55 zd1211

**Comment by 3DSTB** [comment]
may i found the solution:
# rmmod pru_rproc
# modprobe pru_rproc
# dmesg | grep pru

**Comment by manbehindthemadness** [comment]
So here is an interesting take on this problem, we have been converting our default firmware image to use klipper over at thing-printer for the Replicape boards (https://github.com/goeland86/ReFactor). After image creation everything is peachy with the exception of extremely long boot times. So to diagnose I use systemd-analyze blame and the problematic service are:
6min 32.053s networking.service
6min 31.707s generic-board-startup.service
The universal solution to preventing the networking.service from taking so long is to edit /etc/systemd/system/network-online.target.wants/networking.service and alter the timeout from 5min to 30s. Once this change has been made; however, the error you mentioned above manifests (Unable to open port: [Errno 2] No such file or directory: '/dev/rpmsg_pru30'). I have confirmed this on both a production printer and a development unit. I think what we have here is a service startup timing/order of operations problem.

**Comment by BlackStump** [comment]
out of curiousity I ran 
debian@beaglebone:~$ systemd-analyze
Startup finished in 7.947s (kernel) + 22.411s (userspace) = 30.359s
debian@beaglebone:~$ systemd-analyze blame
         15.967s generic-board-startup.service
         14.082s dev-mmcblk0p1.device
          2.697s systemd-udev-trigger.service
          1.967s keyboard-setup.service
          1.755s networking.service
          1.418s klipper_pru.service
          1.216s ssh.service
          1.184s systemd-journald.service
           945ms dnsmasq.service
           801ms systemd-logind.service
           682ms rsyslog.service
           624ms connman.service
           604ms systemd-timesyncd.service
           545ms bb-wl18xx-wlan0.service
           535ms udhcpd.service
           512ms systemd-modules-load.service
           472ms kmod-static-nodes.service
           453ms systemd-remount-fs.service
           450ms systemd-udevd.service
           435ms systemd-fsck-root.service
           431ms systemd-tmpfiles-setup.service
           421ms systemd-tmpfiles-setup-dev.service
           391ms sys-kernel-debug.mount
           354ms wpa_supplicant.service
           325ms sys-fs-fuse-connections.mount
           325ms systemd-sysctl.service
           309ms dev-mqueue.mount
           293ms systemd-journal-flush.service
           292ms systemd-update-utmp-runlevel.service
           247ms user@1000.service
           245ms systemd-update-utmp.service
           240ms sys-kernel-config.mount
           216ms systemd-user-sessions.service
           176ms console-setup.service
           150ms systemd-random-seed.service
           104ms bb-wl18xx-bluetooth.service
lines 14-36/36 (END)
not sure what going on with yours but my times are a lot different

**Comment by manbehindthemadness** [comment]
I think what is interesting is if I wait for ten mins or so and restart the klipper_pru service the error goes away, I am trying to isolate where it's coming from, what's not loaded that could cause the issue?
