### ISSUE TITLE
Must home axis first: 0.000 0.000 19.990 [0.000]

### ISSUE THREAD

**Issue by dpackham** [KevinOConnor/klipper#2272]
I get this on the screen when I try to issue a G8 or G29 via CLI
I am running the latest code via git pull as of this morning.  
I reflashed Marlin FW to test this and the printer does work and home. 
Any ideas?   Thanks

[printer.zip](https://github.com/KevinOConnor/klipper/files/3961530/printer.zip)
[klippy.zip](https://github.com/KevinOConnor/klipper/files/3961524/klippy.zip)

08:43:53 Must home axis first: 0.000 0.000 19.990 [0.000]
08:43:53 Must home axis first: 0.000 0.000 19.990 [0.000]
08:43:54 Must home axis first: 0.000 0.000 5.095 [0.000]
08:43:54 Must home axis first: 0.000 0.000 0.100 [0.000]
08:43:56 Must home axis first: 0.000 0.000 5.095 [0.000]
08:43:56 Must home axis first: 0.000 0.000 19.990 [0.000]
08:43:56 Must home axis first: 0.000 0.000 19.990 [0.000]

**Comment by tonn0297** [comment]
g28 first to home. 
klipper dont have a g29 you will have to make that macro. look at exsample_macro

**Comment by dpackham** [comment]
G28 doesn't even work.  Do I have to define that as well?

**Comment by Hywelmartin** [comment]
Your homeing override might be faulty.. I have never used it....

**Comment by dpackham** [comment]
Yup that was it...   something must have changed because it was working.   the one you referenced does work and am now using it.
