### ISSUE TITLE
Delta Calibration: Failed to home probe: Timeout during endstop homing

### ISSUE THREAD

**Issue by kevintong116** [KevinOConnor/klipper#228]
When I try to do a delta calibration
the printer stops after few probes and shows:
Failed to home probe: Timeout during endstop homing
What is the problem?
[klippy.log](https://github.com/KevinOConnor/klipper/files/1800250/klippy.log)

**Comment by kevintong116** [comment]
I found the problem.
The z height is set too high that when the head move to Z0, the probe cannot be triggered.
Setting the probe z position to a negative value or reduce the position_endstop value solve the problem.

**Comment by KevinOConnor** [comment]
Commit 45afa045 adds some hints to the error message to make this a little more clear.

**Comment by VanKurt** [comment]
Which value exactly needs to be set? Is it [stepper_z] -> position_min?
