### ISSUE TITLE
Cramps temperature values not correct

### ISSUE THREAD

**Issue by 3DSTB** [KevinOConnor/klipper#232]
This was already discussed here:
https://github.com/KevinOConnor/klipper/issues/37

I tested also the "Linux host process" with no other result.

I have the same problem. 
May it has somesthing to do with the hardware itself. I have not much knowledge about that but for me the design looks different than eg from the Ramps:

<a href="https://ibb.co/dzi4Hn"><img src="https://preview.ibb.co/iF4YA7/cramps_termistor.png" alt="cramps_termistor" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'>image uploader</a><br />

At room temperatur the value is 10% of the real value. I set the value for the bed to 30°C and the real temperature was 50°C. 

real temperature 20°C > measured output 2°C (10% of the real value)
real temperature 50°C > measured output 30°C (60% of the real value)

I checked the original design here (page 10): https://github.com/bobc/bobc_hardware/blob/master/RAMPS-FD/RAMPS-FD-Schematic.pdf

There is a reference voltage that comes into play. This gives always may a higher voltage then in real from the termistor?

**Comment by KevinOConnor** [comment]
This link: https://groups.google.com/forum/#!topic/machinekit/wZ8KAKqV7yo indicates that the CRAMPS board effectively uses a 2K pullup resistor.  So, add a pullup_resistor=2000 setting to your extruder and heater_bed config sections.

Separately, please choose one issue for all of your CRAMPS issues.  Please do not open new issues - we can track your status much better if you update status in one place.

**Comment by 3DSTB** [comment]
Thank you. I will test it.

If i have more issues i will go on here: https://github.com/KevinOConnor/klipper/issues/224

**Comment by 3DSTB** [comment]
The values are correct now.
