### ISSUE TITLE
Ender 5: MCU 'mcu' shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by BryanHaven** [KevinOConnor/klipper#2350]
[klippy.zip](https://github.com/KevinOConnor/klipper/files/4021570/klippy.zip)

Encountered this tonight, was unable to issue the M112 immediately but was able to get in and get the logs, did a log extract and those are attached as well. 

Running an Ender 5 with the stock board + BLTouch. I've reset the pi and the printer, resliced and trying again. 

Any guidance would be appreciated. Thank you.

**Comment by KevinOConnor** [comment]
Unfortunately, it looks like you got hit by a rare timing bug that was fixed a few weeks back (commit 988ee575).  I recommend upgrading to the latest version of the software.

-Kevin

**Comment by BryanHaven** [comment]
Roger that, will do that after the current prints. Thank you!

**Comment by BryanHaven** [comment]
Resolved with upgrade - no further incidents.
