### ISSUE TITLE
MCU 'mcu' shutdown: Timer too close

### ISSUE THREAD

**Issue by manu7irl** [KevinOConnor/klipper#2357]
Background:
I have an FYSETC F6 MCU working almost non stop in this configuration for more than 6 months.
I have klipper running on manjaro arch linux on an old thinkpad laptop, 5 times in a row I got my prints stop at different heights end positions.
I have DWC2 as UI no octoprint installed.
My drivers are:
TMC2208 UART for x and y
DRV8825 for extruder
A4988 for the dual Z
All running a 16 micorsteps.
My printer is a CR-10S, or what's left of it...
I can't find a solution for this...
Please help.
[klippy.log.2020-01-06.txt.zip](https://github.com/KevinOConnor/klipper/files/4030197/klippy.log.2020-01-06.txt.zip)

**Comment by KevinOConnor** [comment]
This issue tracker is only for code from this repository.  You'll need to reproduce on the pristine code (that is, without dwc2) and provide the log from that session.

-Kevin
