### ISSUE TITLE
x86 Linux debian. It's works.

### ISSUE THREAD

**Issue by doctor3lo** [KevinOConnor/klipper#237]
Hi all, I just want to tell you, that we have been able to run klipper on old nettop.

Atom CPU. 
Debian linux.
Anet board (need to choose 57600 for install on board).
ultimaker scheme.

Thank you for attention

**Comment by khseal** [comment]
I'm using a Klipper on a 2003 laptop under ubuntu 12.04. It was difficult but it all worked.

**Comment by KevinOConnor** [comment]
A number of people run Klipper on machines other than a Raspberry Pi.  It generally works once getting past the installation.

Cheers,
-Kevin
