### ISSUE TITLE
Virtual Probe not working

### ISSUE THREAD

**Issue by aaronthomaswebster** [KevinOConnor/klipper#239]
In the Example-extras.cfg it says:
The probe
section also creates a virtual probe:z_virtual_endstop pin. One may
set the stepper_z endstop_pin to this virtual pin on cartesian style
printers that use the probe in place of a z endstop.

Either I set it up wrong or it does not like to be used with dual steppers on the z axis. Any help would be great.
[Klipper.log](https://github.com/KevinOConnor/klipper/files/1809384/Klipper.log)

**Comment by Alexdad76** [comment]
Try it like this:
```

[stepper_z]
step_pin: ar46
dir_pin: ar48
enable_pin: !ar62
step_distance: .005
```
**endstop_pin: probe:z_virtual_endstop**
```
position_endstop: 3.2
position_max: 180
homing_speed: 10
```
