### ISSUE TITLE
keypad matrix

### ISSUE THREAD

**Issue by ld3300** [KevinOConnor/klipper#2391]
Hey, printer is running great, thank you for all the work. 

I have an Adafruit NeoTrellis M4 Express which is a SAMD51 board with a built in 8x4 button matrix with neopixels in each button.  I was hoping to set this up to use the buttons and colors in different states to do klipper based controls.  

The button matrix consists of 4 x Row pins and 8 x Column pins.  The buttons all have a diode between them and the row pins with the button on the cathode side.  All of the row and column pins are initialized as inputs with pullups, then the 4 x Row pins are put through a for loop where one at a time each is changed to an output low, checks which column pins are pulled low, then returns the pin to input with pullup. 

I struggled through the source a bit, and unless I am missing something it doesn't look like controlling a matrix like this directly from Klipper is possible.  I am uncertain if it would even be reasonable or possible.

My backup is to use something simple like an Arduino flashed with the Klipper host as a go between to pass the button states and the neopixel information (it would be a fun wiring frankenstein). 

If setting up a key matrix would be a desirable feature and possible in the resource space of Klipper is it a feature that could be tackled by a python newb with a bunch of hand holding?  It looks like it would be a new class in the buttons.py file.

Let me know your thoughts.  I'm interested in learning, but don't want to waste other's resources for a feature that only I would use (especially since I already have a cheat workaround stewing in my head).

Thanks,

David

[klippy.log](https://github.com/KevinOConnor/klipper/files/4057393/klippy.log)

**Comment by KevinOConnor** [comment]
It sounds like this would require both host python code and some C micro-controller code.  It's certainly possible for someone to implement it though.

-Kevin
