### ISSUE TITLE
Option 'step_pin' is not valid in section 'stepper_extruder'

### ISSUE THREAD

**Issue by klauskin** [KevinOConnor/klipper#2399]
Mks gen l v2.0 . Correctly set up the step pin but still getting the error.

pin map for v2.0
https://img.alicdn.com/imgextra/i4/12778391/O1CN01slqRrh2Br7vqDFjjb_!!12778391.jpg

[klippy.log](https://github.com/KevinOConnor/klipper/files/4069284/klippy.log)

**Comment by klauskin** [comment]
I use [extruder] as the setting. I get an error for no [stepper_extruder]. After change it to [stepper_extruder] no matter what is on the first line of the section, I will get an error for that.

**Comment by BlackStump** [comment]
the headers are
[extruder]
and
[tmc2209 extruder]
not
[tmc2209 stepper_extruder]
