### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by smellzmore** [KevinOConnor/klipper#24]
Sorry for being a total newb, but im coming from marlin and i'm trying to understand how to figure out step  distance for x,y,z, and e0. I'm using htd3 belts and 12 teeth pulleys for x/y and 3/8-12 acme screws on z. I'm using a direct drive mk8 drive gear on my extruder with an e3d hotend. I know that they are not very commonly used parts but its what i had laying around from another project. The install guide doesn't clarify how to calculate step distance. Would it be somewhat similar to marlin or is there a formula that i can use?By the way, great work! I'm looking foward on getting my setup working.

**Comment by TunaLatte** [comment]
Hey

Post your Marlin steps per millimeter.
The simple formula I used is 1/yourmarlinstepspermillimter, then round it to the nearest 7th digit.

**Comment by smellzmore** [comment]
Thank you! My steps per millimeter in Marlin are X88.88888888889, Y88.88888888889, Z1511.811023622047, and E136.611842. I probably can round things off but those settings are pretty accurate on prints.

**Comment by TunaLatte** [comment]
I don't think stepper motors can achieve that level of accuracy, in my case printed objects dimensional accuracy was on par if not better than Marlin (due to less vibration on outer perimeters aswell).
Guess it should be: X0.01125 Y0.01125 Z0.0006615 E0.0073200 (x & y weren't rounded).

**Comment by smellzmore** [comment]
Thank you for your help again! I will play with the configuration once I get a chance.
