### ISSUE TITLE
Strange behavior shutdown_value and soft_pwm within output_pin

### ISSUE THREAD

**Issue by berghauz** [KevinOConnor/klipper#2405]
Hi. Have faced pretty weird contradicts itself behavior of shutdown_value and soft_pwm
[klippy.log](https://github.com/KevinOConnor/klipper/files/4081210/klippy.log)

**Comment by berghauz** [comment]
Ok, it's works with just value, but fails with static_value.

**Comment by KevinOConnor** [comment]
Alas, the code doesn't currently support static_value or shutdown_value with "software pwm".  As noted, one can just use the regular "value" parameter.

-Kevin
