### ISSUE TITLE
No option 'mesh_min' in section: 'bed_mesh'

### ISSUE THREAD

**Issue by Metti93** [KevinOConnor/klipper#2407]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4082493/klippy.log)

Hi there, first post ever on Github.
i make it short.

After configer my "printer.cfg), and try to restart.
i get the Error "No option 'mesh_min' in section: 'bed_mesh'".
But is there really a option, to configer in my file?
When yes, how? 

Tanks guys!

**Comment by DrJeff** [comment]
> Changes
> 20200109: The bed_mesh module now references the probe’s location in for the mesh configuration. As such, some configuration options have been renamed to more accurately reflect their intended functionality. For rectangular beds, min_point and max_point have been renamed to mesh_min and mesh_max respectively. For round beds, bed_radius has been renamed to mesh_radius. A new mesh_origin option has also been added for round beds. Note that these changes are also incompatible with previously saved mesh profiles. If an incompatible profile is detected it will be ignored and scheduled for removal. The removal process can be completed by issuing the SAVE_CONFIG command. The user will need to re-calibrate each profile.

Change made to the code
