### ISSUE TITLE
Z_ENDSTOP_CALIBRATE

### ISSUE THREAD

**Issue by groot-lgbt** [KevinOConnor/klipper#2428]
Each time i do Z_ENDSTOP_CALIBRATE i end up with this:

`Send: ACCEPT
Recv: // Manual probe failed! Use TESTZ commands to position the
Recv: // nozzle prior to running ACCEPT.
Recv: ok`
No matter how many times I do TESTZ before Accept... Am I missing something ? Thx
[klippy.log](https://github.com/KevinOConnor/klipper/files/4113406/klippy.log)

**Comment by KevinOConnor** [comment]
Make sure the nozzle is several millimeters above the bed when you start the Z_ENDSTOP_CALIBRATE command.  (It is not valid to start calibration of the endstop when the endstop is already triggered.)

-Kevin

**Comment by groot-lgbt** [comment]
Ok, thanks a lot.

**Comment by KevinOConnor** [comment]
I've updated the documentation to note this (commit 0c9eb519).

-Kevin
