### ISSUE TITLE
FIRMWARE_RESTART issue

### ISSUE THREAD

**Issue by bigsubgit** [KevinOConnor/klipper#2475]
Hi all, I'm having issue with FIRMWARE_RESTART command sent from Repetier Server (but also if I launch an echo FIRMWARE_RESTART > /dev/pts/1).
The problems are about mcu, but sometimes there is a message about timeout or others.
Klipper disconnects and doesn't go ready again.

I'm using a SKR V1.3 and a raspberry pi 3 b+.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4155897/klippy.log)

**Comment by KevinOConnor** [comment]
FYI, there was a discussion on this in #2156 .

-Kevin

**Comment by bigsubgit** [comment]
Many thanks.

**Comment by KevinOConnor** [comment]
Okay, it sounds like we can close this ticket.

-Kevin
