### ISSUE TITLE
Nested gcode commands not working in current release

### ISSUE THREAD

**Issue by w1ebr** [KevinOConnor/klipper#2484]
Up until today, when I installed the latest release of Klipper, I have had no problem with including a gcode macro inside of a gcode macro. In the current release it says "MALFORMED COMMAND" and the nested gcode macro name "SET_CARRIAGE"

Several gcode macros include a gcode macro called "SET_CARRIAGE"

[klippy.log](https://github.com/KevinOConnor/klipper/files/4168880/klippy.log)

**Comment by KevinOConnor** [comment]
It doesn't like the ';' - there is no need to add semicolons in the gcode macros.  (I recommend removing all semicolons from from your macros.)  Klipper could have done better here (a semicolon generally starts a comment in g-code).  I'm not sure why it worked previously.

-Kevin

**Comment by w1ebr** [comment]
Great! I'll try it now!

**Comment by w1ebr** [comment]
Thank you, Kevin!
