### ISSUE TITLE
Request to use Filamnet Run Out Sensor

### ISSUE THREAD

**Issue by MarcinKnD** [KevinOConnor/klipper#249]
Can you add RunOut sensor? its connected to Servo1 (D6) on Ramps, I like this from Repetier Firmware.

It would be great that's make pause and filament change when trigger the senor

**Comment by leungtech** [comment]
yes, it is very important, please add,thx!!!

**Comment by Duckle29** [comment]
I guess this could be thought of as a request to implement M600 as done in marlin / smoothieware: http://reprap.org/wiki/Gcodes#M600:_Filament_change_pause

**Comment by MarcinKnD** [comment]
M600 It Will be great.

**Comment by MarcinKnD** [comment]
OK. I Have connect the Runout sensor to Orange PI and its finaly works, thaks to arhi (Bogdan Kecman) and his Octoprint-Filament-Reloaded-OrangePi.

Now the sensor Trigger the pause, 
and do GCODE
 After pause:
G91
G1 Z50
G1 E-40 F500
M104 S0
M140 S0


I change the filamnet

and after resume do gcode
G91
G1 Z50
G1 E-40 F500
M104 S0
M140 S0


When printer start printing its give 
> Your printer's firmware reported an error. Due to that the ongoing print job will be cancelled. Reported error: Move exceeds maximum extrusion (4.937mm^2 vs 0.640mm^2)


If we can after triger to pause remember all position XYZE, ten switch to relative, make some moves home XY, park in position to change fimalent, retract 4mm material, then after resume extract 3-4 mm material and then go to XYZE where pause whas trigered, than switch to abloute shold do the trick.

**Comment by ChiliApple** [comment]
it only works when you print from local space, not from virtuell SD!

**Comment by KevinOConnor** [comment]
With the addition of "buttons" support (commit 38d7b9ad) it should now be possible to put together a klipper host python "module" to support filament runout sensors.  I don't have one of these sensors, but if someone with the sensor is up for doing some development work, it should be possible.

-Kevin

**Comment by mamoit** [comment]
An example in the `example-extras.cfg` would be perfect. I'm trying to figure out how to do it and can't seem to find a way.

**Comment by mamoit** [comment]
Something like [this](https://github.com/mamoit/klipper/tree/PR-runnout)?

**Comment by KevinOConnor** [comment]
@mamoit - That code looks like a valid way to use the buttons module.  Please submit a pull request if you would like me to do a full review and you want to include it in mainline.

-Kevin

**Comment by mamoit** [comment]
PR created #545 still needs a ton of work, but I want your input.

**Comment by KevinOConnor** [comment]
Basic filament sensor support is now in Klipper.

-Kevin
