### ISSUE TITLE
Max31856: Cold Junction High Fault & Cold Junction Range Fault

### ISSUE THREAD

**Issue by albmargar30** [KevinOConnor/klipper#2498]
Hello, I am trying to connect a type K thermocouple to a board that carries an STM32F103 and a Max31856 from MCU to read the thermocouple. I don't know why it fails because the LED on the FAULT board always comes on and I might be skipping a parameter in the configuration file.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4186571/klippy.log)

**Comment by ld3300** [comment]
looks like it can't read the UART pin of tmc2208 stepper_x.  Try commenting it out temporarily and see if it starts up successfully.

**Comment by KevinOConnor** [comment]
FYI, there were a couple of recent issues found in the stm32f103 code that were recently fixed.  Best would be to retry with the latest code.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this ticket as the original issue may be fixed with the latest code.

-Kevin

**Comment by KevinOConnor** [comment]
Unfortunately, the Klipper initialization sequence for the MAX31856 board was defective (see #3567). It should now be fixed (commit 665ec5e).

-Kevin
