### ISSUE TITLE
[FEATURE REQUEST] virtual pin for filament_switch_sensor

### ISSUE THREAD

**Issue by test3210-d** [KevinOConnor/klipper#2505]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4207834/klippy.log)
I whant add virtual runout sensor in filament width sensor for filament_switch_sensor. If diameter out of range change virtual pin state (like probe:z virtual endstop) . This feature possible to implementation in tsl1401 and hall based sensors. I don't know how implement virtual pin. May be somebody can help ?

**Comment by Arksine** [comment]
While this is possible, I think the better option here would be for the filament width sensor to inherit the "BaseSensor" class in filament_switch_sensor.py.  Then when the width sensor detects a runout it can execute the proper callback.

**Comment by test3210-d** [comment]
harder to configure by user , all option from filament_switch_sensor migrate to filament width section ? or not ?

**Comment by Arksine** [comment]
To me it makes sense that all configuration for a filament sensor be in the same section.

**Comment by KevinOConnor** [comment]
I agree that doing an `import filament_switch_sensor` and then directly using that code is preferable to virtual pins.

@Arksine - what do you think about converting the filament_switch_sensor code from a "base class" to a "helper class"?  That might make it easier to use in the hall and tsl1401 classes.

That said, if you are interested in how virtual pins are implemented, there is an example in klippy/extras/probe.py - see the use of the `setup_pin()` method.

-Kevin

**Comment by KevinOConnor** [comment]
> what do you think about converting the filament_switch_sensor code from a "base class" to a "helper class"?

Specifically, I was thinking perhaps the `BaseSensor(object)` class could be converted to a `RunoutHelper` class, and SwitchSensor could be converted to something like:
```python
class SwitchSensor:
    def __init__(self, config):
        printer = config.get_printer()
        buttons = printer.try_load_module(config, 'buttons')
        switch_pin = config.get('switch_pin')
        buttons.register_buttons([switch_pin], self._button_handler)
        self.runout_helper = RunoutHelper(config)
    def _button_handler(self, eventtime, state):
        self.runout_helper.note_filament_present(state)
```

and then the RunoutHelper class could do all the work of discarding duplicate notifications, disabling events at printer startup, disabling events shortly after a previous event, disabling events on a SET_FILAMENT_SENSOR command, reporting status via GET_FILAMENT_SENSOR, etc.

That way, the hall and tsl1401 classes could just import this helper class and periodically call its `note_filament_present()` method.

Thoughts?
-Kevin

**Comment by test3210-d** [comment]
Ok, but what about 
```
        switch_pin = config.get('switch_pin')
        buttons.register_buttons([switch_pin], self._button_handler)
```
i still must set some pin, as i think, or no ?

**Comment by KevinOConnor** [comment]
> i still must set some pin, as i think, or no ?

My comments above were directed at @Arksine.

I'm proposing that the hall_filament_sensor.py code would add:
```
import filament_switch_sensor
...
self.runout_helper = filament_switch_sensor.RunoutHelper(config)
```
and then periodically call:
```
self.runout_helper.note_filament_present(self.lastFilamentWidthReading > 0.5)
```

It is just a proposal though, as it would require code changes to filament_switch_sensor.py.

-Kevin

**Comment by Arksine** [comment]
@KevinOConnor I think its a good idea.  It would definitely reduce duplicate code.  I'll get working on it.

**Comment by KevinOConnor** [comment]
FYI, the mentioned changes to filament_switch_sensor.py in https://github.com/KevinOConnor/klipper/issues/2505#issuecomment-586618603 were completed (commit 718da759) and thus it should now be possible to implement the hall_filament_sensor.py changes mentioned in https://github.com/KevinOConnor/klipper/issues/2505#issuecomment-586622668 .

-Kevin
