### ISSUE TITLE
Extruder stops moving

### ISSUE THREAD

**Issue by smark-** [KevinOConnor/klipper#2513]
I just installed a G5 flex extruder which has a 40:1 gear ration, thus a very small value for step_distance. I think there's a bug that makes the extruder stop moving during the print. I've been able to reproduce the issue myself by issuing a set of G1 commands to the extruder on Octoprint. If I increase the step value then the issue seem to disappear.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4208938/klippy.log)

**Comment by Arksine** [comment]
I would hazard a guess that its most likely the driver.  Trinamic drivers have auto-cutoff mechanisms when they detect an error condition.  If you can reproduce you could execute the DUMP_TMC gcode to see if GSTAT is has logged an error:

```
DUMP_TMC STEPPER=extruder
```

**Comment by smark-** [comment]
Problem solved, it was indeed the Trinamic auto-cutoff mechanisms kicking in. In particular I experienced this issue, even if I'm using TMC2130 drivers: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#my-tmc-motor-driver-turns-off-in-the-middle-of-a-print
The solution was to configure the drivers in spreadcycle mode.
