### ISSUE TITLE
Support M80\M81

### ISSUE THREAD

**Issue by userosos** [KevinOConnor/klipper#253]
Has klipper support M80 and M81 g-code command? And how i can configure it if klipper has support.

**Comment by cmock** [comment]
Gcode commands are documented in https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md

M80/M81 are not supported. 

What I have done is to configure the relevant pin as ```[output_pin power]``` (see ```config/example-extras.cfg```) which I then switch via ```SET_PIN PIN=power value=x```. That works fine, also with the "PSU control" octoprint plugin.

I don't have access to my printer now to cut&paste the full config, let me know if you need it, then I'll do that later.
