### ISSUE TITLE
Voron 2.2 Nozzle Probe Issue

### ISSUE THREAD

**Issue by Chezz1989** [KevinOConnor/klipper#2557]
Hello dear community,

I have build an Voron 2.2.

I have been struggling with the correct function of gantry leveling for days. The function of homing is carried out without problems, but when I run the G32, the Z_Probe triggers without touching an obstacle. it is strange when I'm in the homing function the inductive sensor works quite normally. only at gantry leveling does he "switch off"? I felt that?
1000 pages browsed, 100 times viewed the software ... tried etc.

I'm desperate.

thanks, people
Chris

[klippy.log](https://github.com/KevinOConnor/klipper/files/4241154/klippy.log)

**Comment by hevilp** [comment]
Take a look at the horizontal_move_z: 5 and increase it.

Your probe is probalby triggered while horizontal movement. (Probe triggered prior to movement in your log)

**Comment by Chezz1989** [comment]
i have increase it (try Z30, 100) but the problem is still there.

it seems like he's after homing X, Y, and Z and triggered he lift up a little bit and when he moved to the middle at this moment the probe triggered but there is nothing no heatbed no physical thing there!

Thank you for your efforts!

**Comment by Chezz1989** [comment]
I have solved the problem! The reason was the voltagedrop to the probe... the cable was to long (2.5 meters)
