### ISSUE TITLE
Wrong Extruder Direction

### ISSUE THREAD

**Issue by edjrwinnt** [KevinOConnor/klipper#2582]
I've changed the dir_pin from ar28 to !ar28 and the extruder still goes in reverse. 
 
[Klippy.log](https://github.com/KevinOConnor/klipper/files/4285034/Klippy.log)

**Comment by boboxx** [comment]
You need to flip the connection wire, I have never done it but there are 2 coils.

**Comment by Hywelmartin** [comment]
it doesn't seems like you saved that change
![bild](https://user-images.githubusercontent.com/33714214/75854406-69fddb00-5df0-11ea-89e5-a85aff0ea2b8.png)

**Comment by edjrwinnt** [comment]
It's is saved. I made other changes and they were there the next time I went to change something else in the file. I even tried it 2 or 3 times toggling back and forth with and without the !, plus I even tried the ^.

I will try the hardwire route but don't understand why this way will not work. 

Thank you both for your help.

**Comment by Hywelmartin** [comment]
well it doesn't show in the log..

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
