### ISSUE TITLE
Lulzbot Taz 6 cfg file not working

### ISSUE THREAD

**Issue by reinharm1959** [KevinOConnor/klipper#2591]
Despite several aatempts I cannot get Klipper to wok beyond homing the toolhead and then errors are thrown.  Log file attached.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4294650/klippy.log)
[klippy.log](https://github.com/KevinOConnor/klipper/files/4294654/klippy.log)

**Comment by jakep82** [comment]
Please don't open multiple tickets for the same issue.

**Comment by reinharm1959** [comment]
Sorry didn’t know that I had I thought I was adding to the existing conversation.

**Comment by KevinOConnor** [comment]
Closing as it appears to be a dup of #2586. 

-Kevin
