### ISSUE TITLE
"Timer too close" at start of print

### ISSUE THREAD

**Issue by ChoffaH** [KevinOConnor/klipper#2592]
Every time I start a print I get the error "MCU 'mcu' shutdown: Timer too close" right after homing.
Tried changing the USB cable without success.

Attached my log file below.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4295627/klippy.log)

Thank you!

**Comment by ld3300** [comment]
Try updating.  There was a bug causing that temporarily and I believe Kevin committed a version about an hour ago that might fix it.

**Comment by ChoffaH** [comment]
> Try updating. There was a bug causing that temporarily and I believe Kevin committed a version about an hour ago that might fix it.

That seems to have fixed it. Thank you!
