### ISSUE TITLE
M73 command results in strange display output

### ISSUE THREAD

**Issue by godefroi** [KevinOConnor/klipper#2611]
I'm using an Octoprint plugin to pass M73 GCode commands to Klipper during prints. This, as expected, causes the progress bar to show, but the times the show up to the right of the bar are... nonsensical.

There are actually two plugins in play here, but I don't think they would interact in any way on the Klipper side. One sends M117 commands to show the current layer and Z height. This works great. The other sends M73 commands to show completion percent. This doesn't. The end result is this:

![klipper_progress](https://user-images.githubusercontent.com/7189728/76481899-4d593880-63d8-11ea-98b8-273437de3efd.jpg)

This is near the end of a 7-hour 45-minute print. I don't know what "00:13" is meant to convey, but probably not that. The other number that flashes there is "-00:00" which is probably roughly correct; there was no more than a minute or two left when I took the picture. Sometimes, however, it's wildly incorrect.

This is a snippet of the terminal traffic in Octoprint, showing the M117 and M73 commands:
```
Send: N900842 G0 F18000 X175.242 Y113.975*79
Recv: ok
Send: N900843 G1 F4800 E-6.5*17
Recv: ok
Send: N900844 G1 F600 Z96*60
Recv: ok
Send: N900845 M117 L478/486 Z96.0/97.4*6
Recv: ok
Send: N900846 G0 F18000 X175.242 Y113.975 Z96*62
Recv: ok
Send: N900847 G0 X192.969 Y162.369*31
Recv: ok
Send: N900848 M117 L479/486 Z96.0/97.4*10
Recv: ok
Send: N900849 M73 P99*91
Recv: ok
Send: N900850 G1 F600 Z96*57
Recv: ok
Send: N900851 G1 F1920 E6.5*57
Recv: ok
Send: N900852 G1 F4800 X192.817 Y162.368 E0.00506*49
Recv: ok
Send: N900853 G1 X192.706 Y162.35 E0.00374*109
Recv: ok
Send: N900854 G1 X192.604 Y162.362 E0.00342*93
Recv: ok
Send: N900855 G1 X192.534 Y162.356 E0.00234*91
```

Also attached is the `klippy.log`.

[klippy.zip](https://github.com/KevinOConnor/klipper/files/4322042/klippy.zip)

**Comment by ld3300** [comment]
That is supposed to be the current printing time. , you are correct that the negative should be the estimated remaining time.  If I remember right mine was doing weird things too.  It seems to be working now, I wonder if it was fixed sometime in the last 2 months.  There were some display changes in March that might have been what made mine work correctly.

**Comment by KevinOConnor** [comment]
Unfortunately, the display's print time estimate is not particularly accurate.  There is no g-code command to indicate the "start of a print" nor "end of a print", so Klipper can only estimate how long a print has been in progress.  It looks like this particular print is suffering from "print stalls" - the printer is moving faster than OctoPrint can send commands.  That is causing the print time estimate to reset.  The very latest display code (as of a few days ago) may improve this.  Using virtual_sdcard may also improve this (as well as reduce pauses during the print due to OctoPrint running slow).  See config/example-extras.cfg for the details.

-Kevin

**Comment by godefroi** [comment]
The M73 Progress plugin for Octoprint (which I'm using) has the ability to send the estimated remaining time as another parameter (`R` I think); if Klipper could support that, then it would fix at least one of the two issues here (one being elapsed time being reset, the other being remaining time being calculated incorrectly).

https://plugins.octoprint.org/plugins/m73progress/

**Comment by ld3300** [comment]
It looks like it wouldn't be too hard to implement.  I will give it a try when I get some time and hopefully Kevin will have some time to look it over and check it.  Might be a couple of days.  The question I have is should "P" always be required with "R" as optional, or both as optional parameters.  It looks like the plugin sends P and R.

**Comment by godefroi** [comment]
The plugin always sends P, can be configured to also send R. Looking around, I don't see any firmware that supports R but not P.

**Comment by ld3300** [comment]
I think it would be less error prone that way

**Comment by ld3300** [comment]
see PR #2646

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the original question was answered (Klipper's estimates are limited).  There's some improvement that can be made to the display - lets track that in #2646 .

-Kevin
