### ISSUE TITLE
Layer Shifting in a Creality CR10s-Pro + E3V6 + BMG

### ISSUE THREAD

**Issue by netonjm** [KevinOConnor/klipper#2619]
Hello! First of all thank @KevinOConnor and the whole team behind this open source product. I am completely in love with the product and I hope to contribute somehow in the future.

After a wonderful learning path, I already have my Creality CR10S Pro working with Klipper, it has been a bit more complex than expected since I had no specific configuration for my [original Creality board model 2.4](https://cdn.shopify.com/s/files/1/1834/5761/products/1_d5d5825d-ed5a-472e-a8cc-199f2cbb3af9_1024x1024.jpg?v=1564608070) (Arduino/RAMS based), for which there was not much documentation but looks like very similar to the CR10/S, so I have used this base model, with some change of pins and it seems to work.

Additionally did some changes to the printer to make it a direct unit... added a BMG (bondtech) and an E3V6 with a 5015 fan.

But before trying it on Klipper I wanted to make sure there was no mechanical issues, so I tried it on Marlin first getting very good results:

**With Marlin:** 

![photo_2020-03-15_05-58-48](https://user-images.githubusercontent.com/1587480/76695632-27ef5780-6682-11ea-96c3-6808f9014714.jpg)

.![photo_2020-03-15_02-14-26](https://user-images.githubusercontent.com/1587480/76693287-cec3fb80-6662-11ea-9c50-7f693d6f6f60.jpg)

![photo_2020-03-15_02-14-44](https://user-images.githubusercontent.com/1587480/76693288-d08dbf00-6662-11ea-8db0-0091e3f8bcba.jpg)

Unfortunately, when trying to test my configuration using the same 3d printing software (no matter what I use I get same behaviour/pattern) with the same configuration, the results are not as expected, making a constant and strange printing patterns  (layer shifthing?) 

**With Klipper ([current master](https://github.com/KevinOConnor/klipper/commit/acd165cbea2f48812b7fd96c28b81622e5c13665)):** 

![photo_2020-03-15_02-17-54](https://user-images.githubusercontent.com/1587480/76693330-717c7a00-6663-11ea-824d-43bb2947eced.jpg)

![photo_2020-03-15_02-24-46](https://user-images.githubusercontent.com/1587480/76693381-3b8bc580-6664-11ea-9640-ddeb3dfcd6e5.jpg)

![photo_2020-03-15_02-24-41](https://user-images.githubusercontent.com/1587480/76693382-3cbcf280-6664-11ea-97bb-969a8721574a.jpg)

After some investigation I discovered this board has a tmc2208 drivers not sure if I have something to configure in ["step pulse duration"](https://github.com/KevinOConnor/klipper/issues/1457#issuecomment-478305167) ?

I don't know what else to try, I would be very grateful if someone could help me.

Greetings.

Log:
[klippy.log](https://github.com/KevinOConnor/klipper/files/4333623/klippy.log)

**Comment by BlackStump** [comment]
try upgrading to the latest version 
https://www.klipper3d.org/FAQ.html#how-do-i-upgrade-to-the-latest-software

**Comment by netonjm** [comment]
I updated to most recent hash in master branch following the guide:

![photo_2020-03-15_05-36-23](https://user-images.githubusercontent.com/1587480/76695375-f0cb7700-667e-11ea-8ee9-1a9ea9bcc84e.jpg)


[klippy.log](https://github.com/KevinOConnor/klipper/files/4333789/klippy.log)

**Comment by Hywelmartin** [comment]
[heater_bed]
heater_pin = ar8
sensor_type = EPCOS 100K B57560G104F
sensor_pin = analog14
control = watermark
min_temp = 0
max_temp = 130

---->

[heater_bed]
heater_pin = ar8
sensor_type = EPCOS 100K B57560G104F
sensor_pin = analog14
control: pid
pid_Kp: 22.2
pid_Ki: 1.08
pid_Kd: 114
min_temp: 0
max_temp: 130

and make a PID tune....

**Comment by KevinOConnor** [comment]
As @Hywelmartin indicates - this type of "z banding" is common when using the "watermark" heater - try using the pid heater.

Also, do upgrade to the very latest version (from just a few hours ago) as PR #2597 is important if you are running the tmc2208 in standalone mode.  See the FAQ for upgrade instructions.

-Kevin

**Comment by netonjm** [comment]
thank you guys! I just added the heater bed to use pid and now all works like a charm! 


![photo_2020-03-15_17-10-47](https://user-images.githubusercontent.com/1587480/76705373-f0af9380-66df-11ea-96e7-262d53c7d0a0.jpg)

the first test and it is the best calibration cube i have ever made. Great job!
