### ISSUE TITLE
Print failing almost immediately. 

### ISSUE THREAD

**Issue by dash3811** [KevinOConnor/klipper#2659]
I have installed Klipper and wen through the config checks and everything is working fine. however, when I try to do the test for pressure advance it will almost immediately stop. I have attached my log file as well as the gcode from simplify3d.

[square_tower.zip](https://github.com/KevinOConnor/klipper/files/4402414/square_tower.zip)

**Comment by KevinOConnor** [comment]
The log does not indicate any errors occurred.  If you think this is a software issue, be sure to issue an M112 command after the undesirable event, and then attach the log from that session - see https://www.klipper3d.org/Contact.html .

-Kevin

**Comment by dash3811** [comment]
I got it to work after disabling octolapse. Is it not compatible with that plugin?

**Comment by RomRider** [comment]
Octolapse is working with klipper but it is probably misconfigured for your setup. Run octolapse in test mode and check the logs from octolapse to undestand what happens.
![image](https://user-images.githubusercontent.com/21064206/78042835-e265a680-7372-11ea-8be6-ba8df4cc5a82.png)

**Comment by dash3811** [comment]
I am unsure why it keeps failing but I'm more concerned with why M106 is returning an unknown command response. 

![Untitled](https://user-images.githubusercontent.com/35877286/78165853-8bfb7500-7411-11ea-8fac-b73fa0850315.png)

**Comment by ld3300** [comment]
It looks like it might do that if you don't give it a value ie `M106 S<value>`

**Comment by dash3811** [comment]
I figured it out. my wiring was wonky
