### ISSUE TITLE
Request adding xy skew correction

### ISSUE THREAD

**Issue by leungtech** [KevinOConnor/klipper#266]
In marlin, there is a important function called "xy skew correction", this can help to correct xy skew which cause by poor installation of 3d printer, this is very hard to print a perfect square without this function, can you please adding this function??

**Comment by KenshiHH** [comment]
once is already enough

https://github.com/KevinOConnor/klipper/issues/258

**Comment by KenshiHH** [comment]
seriously, fix your hardware its not that hard

**Comment by leungtech** [comment]
0.2mm is hard to fix in hardware, software fixing skew will be easy and more precise

**Comment by KevinOConnor** [comment]
This is a duplicate of issue #258.
