### ISSUE TITLE
Fysetc Cheetah 1.1 sensorless homing Y does not work

### ISSUE THREAD

**Issue by Magoo0876** [KevinOConnor/klipper#2671]
I tried to setup sensorless homing but Y wont work. 
As mihero #2042 allready reported the Uart config for the Cheetha is wrong. I allready searched for the error and found the reason. Wrong solderd resistors for the uart id selection. The MSB and LSB are swopped. 
See the picture:
![20200329_125951 Kopie](https://user-images.githubusercontent.com/47366735/78077452-b238fa80-73a8-11ea-9c8e-f691bcc8611b.jpg)

So the correct sertting is:

X0 Y2 Z1 E3

hth Magoo
[klippy.log](https://github.com/KevinOConnor/klipper/files/4411733/klippy.log)

**Comment by csutcliff** [comment]
My 1.1b is configured the same as OP.

**Comment by KevinOConnor** [comment]
Thanks, I updated the default config (commit 4ea7b21).

-Kevin
