### ISSUE TITLE
MKS 1.4 and dual Z in Creality 10S

### ISSUE THREAD

**Issue by ChrisMechanic** [KevinOConnor/klipper#269]
Dear All!
I have Creality 10S and decided to flash klipper not into original motherboard, but to do it on MKS 1.4. However, I didn't check previously, MKS 1.4 does not offer dual Z motor. Or does it?

Here: http://osoyoo.com/2016/06/30/mks-1-4-3d-printer-board-marlin-firmware-installation-guide/
is written, in case of dual Z, I should connect 2nd Z to E1 in MKS 1.4.
Is that correct?
Will klipper work like that?

Thank you in advance for your responses!

Below please find original board of CR10S
![cr-10s](https://user-images.githubusercontent.com/21371893/38163933-89587c22-34fc-11e8-9eaf-cf522c8f1279.jpg)

and below here MKS 1.4 board I bought
![htb1nznuxkowbunjssppq6xpgpxan](https://user-images.githubusercontent.com/21371893/38163926-5aeb0396-34fc-11e8-8edf-0358e67b49da.jpg)

**Comment by bmc0** [comment]
I've not actually tested it, but it looks like you can just define a `[stepper_z1]` section and set the pins correctly. Klipper doesn't care what the axis is "supposed" to be. See [example-extras.cfg at line 147](https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L147) and [printer-anycubic-i3-mega-2017.cfg at line 40](https://github.com/KevinOConnor/klipper/blob/master/config/printer-anycubic-i3-mega-2017.cfg#L40).

**Comment by KenshiHH** [comment]
`[stepper_z1]
step_pin: ar36
dir_pin: ar34
enable_pin: !ar30
step_distance: 0.00625
endstop_pin: ^ar19`

my config for the mks gen 1.4 with dual z and dual z endstop.
working fine

**Comment by w1ebr** [comment]
Hello! Do the two z steppers run independently? If yes, how are they handled in Klipper?
Thanks!

**Comment by akpch** [comment]
I just plugged second z into E1 and stop into Z max.
