### ISSUE TITLE
progress bar shows 0%

### ISSUE THREAD

**Issue by 4noxx** [KevinOConnor/klipper#2695]
hello

i use a SKR E3 Mini with a RepRap 12864 Display and Repetier Server.

Problem: The progress bar shows only 0%. All other works perfect.
Repetier shows the correct value, but not Klipper / Display.

[klipper.log](https://github.com/KevinOConnor/klipper/files/4446701/klipper.log)

**Comment by KevinOConnor** [comment]
In order for the lcd display to show a progress bar, either the print has to be from a virtual_sdcard, or the user interface (OctoPrint or other) must send M73 commands to Klipper that explicitly state what the current progress is.

-Kevin

**Comment by 4noxx** [comment]
thx, i dont know if Repetier can send M73 commands, i think no.
so, then i doesnt need the status bar, can i delete or disable it from my mainscreen?

**Comment by mcmatrix** [comment]
> thx, i dont know if Repetier-Server can send M73 commands, i think no.
> so, then i doesnt need the status bar, can i delete or disable it from my mainscreen?

@4noxx Yes, it can but you need to modify the configuration file manually.
If you log via ssh to your repetier-server then go `/usr/local/Repetier-Server/firmware/`
I assume that you're using Klipper firmware in repetier-server config. 

Open file `Klipper.xml` for editing.
Remove comments from the line that is surrounded by red rectangle.
![image](https://user-images.githubusercontent.com/1433580/78828942-2c433200-79ee-11ea-8a1e-599fbb951df8.png)
I also added comments to the next line (don't know if this is needed)
Comment markup surrounding a tag`<!--` <some_tag></some_tag> `-->`

**Comment by 4noxx** [comment]
@mcmatrix 

thx, works :)
