### ISSUE TITLE
Part Cooling Fan not turning on during print 

### ISSUE THREAD

**Issue by dash3811** [KevinOConnor/klipper#2703]
I am able to turn the part cooling fans on and off when the printer isn't in use. However, when the printer is printing something the part cooling fan never turns on and issuing an M106 doesn't turn it on either.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4456976/klippy.log)

**Comment by ld3300** [comment]
What is the value of the fan when turned on?  M106 S<speed?>
