### ISSUE TITLE
menu.cfg

### ISSUE THREAD

**Issue by 4noxx** [KevinOConnor/klipper#2705]
is this correct?
https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/display/menu.cfg
line 532, start without point

    __temp __hotend0_current, __temp __hotend0_target

[klipper.log](https://github.com/KevinOConnor/klipper/files/4457698/klipper.log)

**Comment by mcmatrix** [comment]
Yes, the point is just name-space shortcut.
```
[menu __filament]
type: list
name: Filament
items:
    __temp __hotend0_current, __temp __hotend0_target
    .__unload
    .__load
    .__feed
```

`.__feed` inside `[menu __filament]` is translated to `__filament __feed`

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
