### ISSUE TITLE
Can't connect klipper

### ISSUE THREAD

**Issue by Mckevinho** [KevinOConnor/klipper#2709]
Hi,

I use marlin for long time and i wanna change to Klipper because i wanna use 2 boards in one printer, to have enough pins for all the features ;).
I installed Klipper on my raspberry pi4 and flashed the firmware to my MKS gen L board without problems.
I installed also the octoklipper plugin on octoprint. Now i try to connect with klipper but its doesn't work. Klipper is new for me and i can't find the solution on my own. I get always next message.

Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer
Klipper state: Not ready
05:02:46 Unable to connect

For so far as i guess is it something with USB connection. The strange thing is octoprint also doesn't see the printer.cfg file on the raspberry.

I hope someone can help me.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4463988/klippy.log)

Kevin

**Comment by neophrema** [comment]
Silly questions, 
you did remove the SD card, right?
Did you configure octoprint according to the manual of klipper?
https://www.klipper3d.org/Installation.html
`Unable to open port: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0' `
this seems odd to me, shouldnt there be something about "`/tmp/printer`"?

sincerely,
v.

**Comment by BlackStump** [comment]
https://www.klipper3d.org/FAQ.html#wheres-my-serial-port

**Comment by Mckevinho** [comment]
Hi,

Yeah i did the "/tmp/printer" as serial port in octoprint and also at the addiotional serial ports box.
in the behaviour topic, i marked this checkbox: 

Cancel any ongoing prints but stay connected to the printer
Please note that if you choose this, OctoPrint will still disconnect from the printer in case of fatal errors reported by your firmware (e.g. kill() called, fatal:).

 this serial port (/dev/ttyACM0) was first in the printer.cfg file but i changed it to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

i did all this configuration steps in octoprint like the manual descibed.

**Comment by BlackStump** [comment]
In your printer.cfg this line needs to be checked against the actual id of your connection, hence why I sent you the link  - where is my serial port.
>The general way to find a USB serial port is to run ls /dev/serial/by-id/* from an ssh terminal on the host machine. It will likely produce output similar to the following:
/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

**Comment by Mckevinho** [comment]
thx for response :smiley: 

in the printer.cfg I puted next:
[mcu]
serial = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

now there is a new error with the connection. Something like he doesn't get response and he stops with connecting.
Starting with klipper is not easy :wink: 

I've uploaded a new klippy.log

[klippy.log](https://github.com/KevinOConnor/klipper/files/4465901/klippy.log)

**Comment by BlackStump** [comment]
what does it show when you log into your Pi and run this command

ls /dev/serial/by-id/*

**Comment by KevinOConnor** [comment]
It looks like you've changed the baud rate in "make menuconfig".  Run "make menuconfig" again and do not enable "low-level options".  Then reflash the board.  See the FAQ for further details.

-Kevin

**Comment by Mckevinho** [comment]
This is the USB connection i get
![Schermafdruk 2020-04-15 18 55 52](https://user-images.githubusercontent.com/63485764/79365600-1c29d600-7f4b-11ea-9a6d-94638c743d52.png)

So i made also a new menuconfig without the low level option
![Schermafdruk 2020-04-15 19 01 58](https://user-images.githubusercontent.com/63485764/79365943-a3774980-7f4b-11ea-8b3f-7f1aaf72a31f.png)

You can see i have also an printer.cfg file
![Schermafdruk 2020-04-15 19 09 45](https://user-images.githubusercontent.com/63485764/79366585-bc342f00-7f4c-11ea-8dd8-f1252bdfe825.png)


but this message stay :(
![Schermafdruk 2020-04-15 19 12 49](https://user-images.githubusercontent.com/63485764/79366860-2e0c7880-7f4d-11ea-88b6-7bc038d406f6.png)

**Comment by Mckevinho** [comment]
I found the problem. It was the capital letter in "Printer.cfg".
Now he connects without problem🎉

Thanks all for helping me😊

Tomorrow I will change the board in my printer and test the klipper with a print.
The current board (skr1.4) stays remember the marlin while he has klipper on the sd now.

So I will changed it to the MKS gen L board. That works with the klipper.😊

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the solution was found.

-Kevin

**Comment by bogeyf14** [comment]
it sounds like OP didn't solve the original problem and instead used USB.

A solution that worked for me was to modify the printer.conf
instead of using "serial: /dev/ttyAMA0"
I have to use      "serial: /dev/serial0"
