### ISSUE TITLE
Recv: // Lost communication with MCU 'mcu'

### ISSUE THREAD

**Issue by swordfish45** [KevinOConnor/klipper#2719]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4467144/klippy.log)

![klipper_drop](https://user-images.githubusercontent.com/424527/79080352-239a7680-7ce2-11ea-9892-8d47a27d19ce.png)

[4-12-20_octoprint_Log.txt](https://github.com/KevinOConnor/klipper/files/4467161/4-12-20_Log.txt)

During print, lost communication with MCU. Octoprint running on raspberry pi 4. Noticed 2 webcam streams on the pi are no longer available. Octoprint UI continues to work as expected.

**Comment by ld3300** [comment]
Last time I had a problem like this it was a failing power supply that was running my pi.  It was allowing the voltage to dip low enough that it couldn't maintain connection on the USB ports.  Try running a print without the cameras connected, and if that doesn't work try a different power supply as well.

**Comment by swordfish45** [comment]
I have the Canakit power supply that came with the Pi4

**Comment by KevinOConnor** [comment]
The best information we have on this is in the FAQ: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin
