### ISSUE TITLE
Can't SET_SERVO to any of my servos

### ISSUE THREAD

**Issue by cyclonesurfer** [KevinOConnor/klipper#2726]
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/4472447/printer.cfg.txt)
[klippy.log.txt](https://github.com/KevinOConnor/klipper/files/4472448/klippy.log.txt)

I can't SET_SERVO any servo I set, please help.  It always returns 

Error:  The value 'TEST' is not valid for SERVO

**Comment by gabork** [comment]
The names might be case sensitive. Try it with lowercase (it's lowercase in your printer.cfg):
```
SET_SERVO SERVO=test ANGLE=21
```

**Comment by cyclonesurfer** [comment]
I tried lowercase, uppercase, and a mix of cases while trying to figure out how to make it work

**Comment by ld3300** [comment]
I think you need to try with a fresh install to master branch with no DWC modifications to make sure it isn't interfering.  It's really hard to troubleshoot when your code is modified from the master branch.

**Comment by Spacemarine2018** [comment]
I had a similar problem here: https://github.com/KevinOConnor/klipper/issues/2146

It was a problem with case sensitivity and DWC. Problem was gone when I switched to Octoprint.

I also reported it as an issue at DWC, but I think they didn't care.

**Comment by cyclonesurfer** [comment]
I followed the directions on klipper.info for klipper+DWC2.

I'd really like to ditch octoprint if possible...

**Comment by Spacemarine2018** [comment]
Then file a bug report for DWC2 and see if they respond.

**Comment by cyclonesurfer** [comment]
This seems like a problem with klipper and not dwc2 to me.

**Comment by Spacemarine2018** [comment]
Did you verify this by using octoprint instead of DWC?

**Comment by KevinOConnor** [comment]
This github tracker is exclusively for use with the code in this github repo.  You'll need to either reproduce the error on the pristine code and attach the corresponding log, or you'll need to report the error to the dwc2 developers.

-Kevin
