### ISSUE TITLE
Can't build controller FW

### ISSUE THREAD

**Issue by countAleister** [KevinOConnor/klipper#2728]
Hello everyone!
Don't judge strictly please, I'm very new to the Klipper and too much out of programming (more that 8y already).
Pi4 B. Following all the step-by-step instructions I'm to set it all up but got stuck at the controller FW step. After everything is configured, I'm facing following  in the end of the process:
`
pi@octopi:~/klipper $ make
  Building out/compile_time_request.o
Traceback (most recent call last):
  File "./scripts/buildcommands.py", line 609, in <module>
    main()
  File "./scripts/buildcommands.py", line 600, in main
    ctr_dispatch[cmd](req)
  File "./scripts/buildcommands.py", line 168, in decl_initial_pins
    + ','.join(self.initial_pins))
  File "./scripts/buildcommands.py", line 138, in decl_constant_str
    name, value = req.split(None, 2)[1:]
ValueError: need more than 1 value to unpack
make: *** [Makefile:91: out/compile_time_request.o] Error 1
`

Everything is freshly installed and updated. Any thoughts?
Thank you!

[klippy.log](https://github.com/KevinOConnor/klipper/files/4476395/klippy.log)

**Comment by ld3300** [comment]
Hi @countAleister did you take one of the example config files that matches your machine and change any values that may be different for your machine, then save it as printer.cfg in your home directory?

**Comment by countAleister** [comment]
@ld3300 Hello
Yes, sure, sorry, forgot to mention, I'm using to SKR 1.4 Turbo (LPC1769 120MHz) and custom CoreXY printer. 

Answering your previous question yes, i also tried it but it's the next step after the firmware is built as far as I can get so it doesn't matter. Anyway, I tried with the same result.

I bet you would like to see this params...
![image](https://user-images.githubusercontent.com/63659243/79307758-135fe280-7f00-11ea-9af4-ff4f35db6f72.png)

**Comment by ld3300** [comment]
Just to clarify, it looks like it is the "make" command that is getting an error.  Is that correct?

**Comment by countAleister** [comment]
> Just to clarify, it looks like it is the "make" command that is getting an error. Is that correct?

Exactly so, sir

**Comment by KevinOConnor** [comment]
Errors like the above are usually indicative of a corrupted SD card image.  You can try running "make clean" to see if it clears the error - otherwise you may need to rewrite the sd card.

-Kevin

**Comment by countAleister** [comment]
@KevinOConnor 
Dear Kevin, 
"make clean" didn't help. rewrite didn't help as well despite there are no errors during the installation
So I just gave up and downloaded the bin from some forum))) Works fine.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original poster has found a workaround for the issue.

-Kevin
