### ISSUE TITLE
example-extras reference to "Deck"

### ISSUE THREAD

**Issue by ld3300** [KevinOConnor/klipper#2747]
In example-extras [here](https://github.com/KevinOConnor/klipper/blob/b2a29c63497d1421cd7b0579f2e87dd32bb5e6c4/config/example-extras.cfg#L1787) there is still a reference to "Deck" type in menu example.  I'm not familiar enough with the new menu structure to rewrite the section.

David
[klippy.log](https://github.com/KevinOConnor/klipper/files/4497725/klippy.log)

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 57be62b1).

-Kevin

**Comment by ld3300** [comment]
Thank you!
