### ISSUE TITLE
BED_SCREWS_ADJUST starts a little closer to bed than G28 home

### ISSUE THREAD

**Issue by marcosscriven** [KevinOConnor/klipper#2757]
[klippy.zip](https://github.com/KevinOConnor/klipper/files/4511222/klippy.zip)

I'm using `BED_SCREWS_ADJUST` but found after the process the nozzle was a little higher after homing than while calibrating - just enough to affect adherence on the first layer.

I did the following to diagnose:

1. Home all axes - moves to 0,0,0 according to end stops.
2. Issue `BED_SCREWS_ADJUST` - now above first screw (I.e. screw1_x, screw1_y, 0)
3. Issue `ABORT`
4. Observe height of nozzle above bed
5. Home just Z axis - this results in immediately hitting end stop, pulling back, then slowly moving down again
6. Observe that nozzle is slightly further from bed than beginning of process
7. Issue `BED_SCREWS_ADJUST` again
8. Watch as nozzle moves towards bed and is slightly nearer again.

My theory is that homing by G28 means it approaches a second time more slowly, and therefore gives the end stop slightly more time to respond.

So I guess the question is, how do I get `BED_SCREWS_ADJUST` to approach the bed with the same profile as G28?

**Comment by KevinOConnor** [comment]
If you run G28, it will home the machine to a position of (0, 0, 0.5) - as you have position_endstop=0.5 in your config file.  This is a good setting to use, as you don't want to actually contact the bed during homing.  So, as near as I can tell, your setup is working as intended.  You've configured the machine to descend slightly below the nominal z endstop trigger position when running BED_SCREWS_ADJUST, and it looks like the code is doing just that.

-Kevin

**Comment by marcosscriven** [comment]
Thanks for the explanation @KevinOConnor - sorry for the confusion.
