### ISSUE TITLE
SAVE_CONFIG does not save M206's values

### ISSUE THREAD

**Issue by karabas2011** [KevinOConnor/klipper#2763]
Big delta. Mks Sbase+Raspberry/octoprint.
In order to fast adjusting 1st layer I used to use M206 Zxxx (or SET_GCODE _OFFSET in klipper) and save it with M500
Currently it seems impossible. 
SAVE_GCODE _STATE saves only during session. 
Another way - to change and save z-probe offset is impossible too without the whole calibration procedure.
Am I missed something?

[klipper.log](https://github.com/KevinOConnor/klipper/files/4515203/klipper.log)

**Comment by BlackStump** [comment]
M206 is not a supported command neither is M500 afaik
https://www.klipper3d.org/G-Codes.html

You can add a macro with SET_GCODE_OFFSET and/or add that to your start gcode
https://github.com/KevinOConnor/klipper/blob/master/config/sample-macros.cfg

**Comment by karabas2011** [comment]
I know. I use SET_GCODE _OFFSET and SAVE_CONFIG but it does not save.

**Comment by BlackStump** [comment]
I do not think set_gcode-offset is a save_config item, you would need to manually save it in your config.
>SAVE_CONFIG: This command will overwrite the main printer config file and restart the host >software. This command is used in conjunction with other calibration commands to store the >results of calibration tests.

**Comment by Hywelmartin** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Delta_Calibrate.md

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered (SAVE_CONFIG is not intended to save the state of SET_GCODE_OFFSET - edit the config manually for that).

-Kevin
