### ISSUE TITLE
Failed to verify BLTouch probe is raised; retrying.

### ISSUE THREAD

**Issue by sugar012** [KevinOConnor/klipper#2768]
I got this message 90% of the time. Normally t takes 4/5 firmware_restart to get the machine ready. When is conncted it fly like a bird but even with G29 it fails 3/4 probes. 
I searched in the issue but i dont think someone else got my exact error. Needless to say that i tried with marlin and i got no problems. What could it be? Thanks group
[klippy.log](https://github.com/KevinOConnor/klipper/files/4520888/klippy.log)

**Comment by sugar012** [comment]
and many times this:
![image](https://user-images.githubusercontent.com/53581505/80072641-cfe02680-8546-11ea-8979-0424927a491b.png)

**Comment by KevinOConnor** [comment]
It looks like Klipper failed to get a good clock synchronization upon first connecting to the micro-controller.  This resulted in incorrect scheduling of the initial bl-touch pin_up command, which caused the micro-controller to raise an error.  This would only be an issue upon connecting, because the clock synchronization code would properly sync up with the board after a few seconds.

I updated the Klipper code to try and improve the initial clock synchronization (commit f4429a54).  I recommend you update to the latest code (see the FAQ for details).

-Kevin

**Comment by KevinOConnor** [comment]
I should also mention that the "Failed to verify BLTouch probe is raised; retrying" is unrelated to the "timer too close" error I described above.  See https://www.klipper3d.org/BLTouch.html for information on the bltouch error.

-Kevin

**Comment by sugar012** [comment]
Thanks Kevin. i updated (both klipper and firmware) and also the issue with bltouch seems resolved. I saw you worked on that too. 
But i tried restarting only the printer but it need a firmware_restart to connect. Is it working as intended or still something wrong? Klippy.log attached

Thanks
[klippy.log](https://github.com/KevinOConnor/klipper/files/4568237/klippy.log)

**Comment by KevinOConnor** [comment]
The log you attached shows the old version of the code.  If the problem persists, try attaching a new log (running the latest code).

-Kevin

**Comment by sugar012** [comment]
here, sorry.
The BLtouch error returned
[klippy.log](https://github.com/KevinOConnor/klipper/files/4568368/klippy.log)

**Comment by artheoday** [comment]
I have this same error... 
![image](https://user-images.githubusercontent.com/12423705/80887276-a4043400-8cf0-11ea-9765-d4bf1364cb03.png)

**Comment by KevinOConnor** [comment]
@sugar012 - all of your logs still show the old version of Klipper.  If you're still looking for assistance, I suggest performing a clean checkout of Klipper and retry.  If you do post a log, please triple check it is from the latest code (the log will contain the version information).

-Kevin
