### ISSUE TITLE
Constant stepper phase in sensorless homing? (CoreXY, TMC5160)

### ISSUE THREAD

**Issue by Spacemarine2018** [KevinOConnor/klipper#2769]
When using sensorless homing with TMC5160, will the zero position always be set to a full step? Or does it work the same way as with a mechanical endstop, where it just stops on any micro-step, unless [endstop_phase] is used?

Is there a way to make sure, the zero position is always set to a full step?

I'm running a large CoreXY machine and I don't care where exactly the endstop triggers, as long a it triggers always at the same position. Due to elasticity in the system, the belt is always under high tension when the sensorless virtual endstop is triggered. As soon as current to the steppers is reduced, I can see the belt moving due to the reduced torque of the steppers.

Ideally, the zero position would be set to the next full step in positive X- and Y-direction.

I already read these two sources, but they didn't help a lot on that topic:
https://github.com/KevinOConnor/klipper/blob/master/docs/Endstop_Phase.md
https://www.klipper3d.org/Sensorless_Homing.html

[klippy.log](https://github.com/KevinOConnor/klipper/files/4521316/klippy.log)

**Comment by KevinOConnor** [comment]
FWIW, I don't know what behaviour the tmc5160 drivers have on sensorless homing and I suspect you wont find an answer here.  I suspect you could find the answer yourself by running DUMP_TMC on the driver after homing to see what phase it reports.

It sounds like the endstop_phase system could do what you describe on a cartesian printer, but endstop_phase doesn't support the x/y axes on a corexy printer.  I suspect it could be implemented, but an interested developer would need to take it on and submit it.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
