### ISSUE TITLE
Klipper cancelled print randomly with Internal error on command:"G1"

### ISSUE THREAD

**Issue by rrydman** [KevinOConnor/klipper#2771]
Printing normally and all of a sudden print is cancelled and endless spam of "Internal error on command:"G1"". First time I have seen this in 100+ prints on this printer.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4525420/klippy.log)

**Comment by KevinOConnor** [comment]
It looks like you are running code from a couple of months ago.  The error appears to be a "numerical stability problem" and there were several recent fixes for this type of error.  I recommend you grab the latest code (see the FAQ for upgrade instructions).

-Kevin
