### ISSUE TITLE
SKR 1.4 with TMC2209 and BLTouch

### ISSUE THREAD

**Issue by Xenomorphdelombre** [KevinOConnor/klipper#2772]
Hi,  swtched from the Ender 3 board to SKR 1.4 with TMC2209 and BLTouch.

I managed to get the printer back on, xyz move but the BLTouch does not work and I don't have temp nor can I heat the bed or the extruder.

Attached is Klippy.log

[klippy.log](https://github.com/KevinOConnor/klipper/files/4526094/klippy.log)

**Comment by davidja92** [comment]
Sounds like a config issue post up your config

**Comment by Xenomorphdelombre** [comment]
> # This file contains common pin mappings for the BIGTREETECH SKR V1.4
# board. To use this config, the firmware should be compiled for the
# LPC1768.

# See the example.cfg file for a description of available parameters.<

[stepper_x]
step_pin: P2.2
dir_pin: !P2.6
enable_pin: !P2.1
step_distance: .0125
endstop_pin: P1.29
position_min: 3
position_endstop: 3
position_max: 255
homing_speed: 100

[tmc2208 stepper_x]
uart_pin: P1.10
microsteps: 16
run_current: 0.800
hold_current: 0.500
stealthchop_threshold: 250

[stepper_y]
step_pin: P0.19
dir_pin: !P0.20
enable_pin: !P2.8
step_distance: .0125
endstop_pin: P1.28
position_min: 0
position_endstop: 0
position_max: 235
homing_speed: 100

[tmc2208 stepper_y]
uart_pin: P1.9
microsteps: 16
run_current: 0.800
hold_current: 0.500
stealthchop_threshold: 250

[stepper_z]
step_pin: P0.22
dir_pin: P2.11
enable_pin: !P0.21
step_distance: .0025
endstop_pin: probe:z_virtual_endstop
position_min: -5
position_max: 250

[tmc2208 stepper_z]
uart_pin: P1.8
microsteps: 16
run_current: 0.650
hold_current: 0.450
stealthchop_threshold: 30

# This is the part cooling fan that plugs right in to the fan output marked 'FAN'
[fan]
pin: P2.3

# Ender 3 stock heater fan wires into the second extruder heater output marked 'HE1'
[heater_fan e0_fan]
pin: P2.4
heater: extruder
heater_temp: 50.0
fan_speed: 1.0

# Ender 3 stock heater bed
[heater_bed]
heater_pin: P2.5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: P0.25
control: pid
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130

[extruder]
max_extrude_only_distance: 100.0
step_pin: P2.13
dir_pin: !P0.11
enable_pin: !P2.12
pressure_advance: 0.065
pressure_advance_smooth_time: 0.010
# Tune your Esteps just like in marlin except when you get a % under/over extrusion
step_distance: 0.00712
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: P2.7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: P0.24
control: pid
pid_kp = 26.194
pid_ki = 1.679
pid_kd = 102.158
min_temp: 0
max_temp: 250

[tmc2208 extruder]
uart_pin: P1.4
microsteps: 16
run_current: 0.800
hold_current: 0.500
stealthchop_threshold: 5

[mcu]
serial: /dev/serial/by-id/usb-Klipper_lpc1768_181505058C115553D830C34A030000F5-if00

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

###############################################
##  Probing/Mesh
###############################################

[bltouch]
sensor_pin: P0.10  # Pull-up (^ symbol) needed in open drain mode
control_pin: P2.0
# Some BLTouch V3 and many clones apparently require this, though mine didnt:
pin_up_touch_mode_reports_triggered: False
#flavor: genuine_smart_3.1
x_offset: -48
y_offset: -15
z_offset: 1.4
pin_move_time: 1


[bed_mesh]
speed: 250
horizontal_move_z: 8
mesh_min: 20,15
mesh_max: 205,215
probe_count: 3,3
fade_start: 1.0
mesh_pps: 2,2

[safe_z_home]
home_xy_position: 155,120
speed: 80.0
z_hop: 10.0
z_hop_speed: 10.0

[gcode_macro G29]
gcode:
    BED_MESH_CALIBRATE

[pause_resume]

[gcode_macro M600]
gcode:
	PAUSE
	CHANGE_FILAMENT_START

[gcode_macro CHANGE_FILAMENT_START]
gcode:
	SAVE_GCODE_STATE NAME=M600_state
	G91
	G1 E-.8 F2700
	G1 Z10
	G90
	G1 X50 Y0 F3000
	G91
	G1 E-5 F300

[gcode_macro CHANGE_FILAMENT_END]
gcode:
	G91
	RESTORE_GCODE_STATE NAME=M600_state
	RESUME
	

[respond]
default_type: echo


########################################
# Optional LCD configuration
########################################

# Ender 3 stock display plugs in to the EXP1 port
[display]
lcd_type: st7920
encoder_pins: ^P1.20, ^P1.18
click_pin: ^!P0.28
cs_pin: P1.22
sid_pin: P1.23
sclk_pin: P1.21

# This adds a screw tilt adjust command that probes certain points on the bed and recommends new bed screw positions (turn clockwise this much etc)
[screws_tilt_adjust]
screw1: 50,15
screw1_name: Front left screw
screw2: 50,235
screw2_name: Rear left screw
screw3: 245,15
screw3_name: Front right screw
screw4: 245,235
screw4_name: Rear right screw
horizontal_move_z: 10
speed: 250
screw_thread: CW-M3

[menu __main]
type = list
name = Main Menu
items =
	__tune
	__octoprint
	__sdcard
	__control
	__calibration
	__temp
	__filament
	__prepare

[menu __calibration]
type = list
name = Calibration
items = 
	__calibration_home_all_axes
	__calibration_bed_screws_adjust
	__calibration_bed_mesh_calibrate
	__calibration_screws_calculate
	__calibration_probe_calibrate
	__calibration_probe_accuracy
	__general_firmware_restart

[menu __calibration_accept]
type = command
name = Accept
gcode = ACCEPT

[menu __calibration_abort]
type = command
name = Abort
gcode = ABORT
action = back

[menu __calibration_screws_calculate]
type = command
name = Screw tilt calculate
gcode = 
	G28
	SCREWS_TILT_CALCULATE

[menu __calibration_bed_screws_adjust]
type = list
name = Adjust screws
enter_gcode = 
	G28
	BED_SCREWS_ADJUST
show_back = False
items = 
	__calibration_accept
	__calibration_bed_screws_adjust_adjusted
	__calibration_save_config
	__calibration_abort

[menu __calibration_probe_accuracy]
type = command
name = Test accuracy
gcode = 
	G28
	G1 X164 Y134 Z10 F6000
	PROBE_ACCURACY

[menu __calibration_save_config]
type = command
name = Save config
gcode = SAVE_CONFIG

[menu __general_firmware_restart]
type = command
name = Restart firmware
gcode = FIRMWARE_RESTART

[menu __calibration_home_all_axes]
type = command
name = Home XYZ
gcode = G28

[menu __calibration_bed_screws_adjust_adjusted]
type = command
name = Adjusted
gcode = ADJUSTED

[menu __calibration_probe_calibrate]
type = list
show_back = False
name = Adjust Z offset
enter_gcode = 
	G28
	G0 Z10 F6000
	PROBE_CALIBRATE
items = 
	__calibration__toolhead_zpos
	__calibration_probe_calibrate_testz_minus, __calibration_probe_calibrate_testz_plus
	__calibration_probe_calibrate_testz_minus_minus, __calibration_probe_calibrate_testz_plus_plus
	__calibration_probe_calibrate_testz_minus_1, __calibration_probe_calibrate_testz_plus_1
	__calibration_probe_calibrate_testz_minus_point_1, __calibration_probe_calibrate_testz_plus_point_1
	__calibration_accept
	__calibration_save_config
	__calibration_abort

[menu __calibration__toolhead_zpos]
type = item
width = 16
name = "Z = {0:.3f}"
cursor = \x20
parameter = toolhead.zpos

[menu __calibration_probe_calibrate_testz_minus]
cursor = \x20
type = command
width = 7
name = "   -"
gcode = TESTZ Z=-

[menu __calibration_probe_calibrate_testz_plus]
cursor = \x20
type = command
name = "   +"
width = 7
gcode = TESTZ Z=+

[menu __calibration_probe_calibrate_testz_minus_minus]
cursor = \x20
type = command
name = "   --"
width = 7
gcode = TESTZ Z=--

[menu __calibration_probe_calibrate_testz_plus_plus]
cursor = \x20
type = command
name = "   ++"
width = 7
gcode = TESTZ Z=++

[menu __calibration_probe_calibrate_testz_minus_1]
cursor = \x20
type = command
name = "  -1.0"
width = 7
gcode = TESTZ Z=-1

[menu __calibration_probe_calibrate_testz_plus_1]
cursor = \x20
type = command
name = "  +1.0"
width = 7
gcode = TESTZ Z=+1

[menu __calibration_probe_calibrate_testz_minus_point_1]
cursor = \x20
type = command
name = "  -0.1"
width = 7
gcode = TESTZ Z=-0.1

[menu __calibration_probe_calibrate_testz_plus_point_1]
cursor = \x20
type = command
name = "  +0.1"
width = 7
gcode = TESTZ Z=+0.1

[menu __calibration_bed_mesh_calibrate]
type = command
name = Generate bed mesh
width = 18
show_back = False
gcode = 
	G28
	BED_MESH_CALIBRATE
	SAVE_CONFIG+

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
<

**Comment by davidja92** [comment]
Config looks right for the 1.4 I would change  your tmc sections to 2209 since you are using that...if u activate temps do u feel them warming up even if they report 0?

**Comment by Xenomorphdelombre** [comment]
I wil lchange the names for TMC2209, Set heat and type status?

When I try to heat up nothing happens

**Comment by davidja92** [comment]
Did u ensure your thermistors are plugged in properly into you board?

**Comment by Xenomorphdelombre** [comment]
Yes I even tried other thermistor. Also plugged back old board, everything works. Status is Ready. I can move all axis

**Comment by davidja92** [comment]
Did you fix header to tmc2209 save it and restart firmware?

**Comment by Xenomorphdelombre** [comment]
I tried to go back to Marlin and I got a MAXTEMP error on boot.  Board is labeled as BigTreetech SKR 1.4 ARM Smoothieboard
<blockquote class="imgur-embed-pub" lang="en" data-id="a/EZvnCHE"><a href="//imgur.com/a/EZvnCHE"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by davidja92** [comment]
I saw I klipper log you attempting to set temp but your temp reading reports 0

**Comment by Xenomorphdelombre** [comment]
Power in DC IN, Bed in HB, Hot end on HE0 and Hotend fan on HE1. Thermistor are in: Bed: TB and hotend on TH0

**Comment by Xenomorphdelombre** [comment]
Also BLtouch does a self test when power on but doesn't deploy when homing

**Comment by davidja92** [comment]
Are you 1.4 or 1.4turbo?

**Comment by Xenomorphdelombre** [comment]
I believe it is a 1.4 the processor is  LPC1768

**Comment by davidja92** [comment]
Ok so visual of your board shows the nxp lpc1768 that would be non turbo

**Comment by davidja92** [comment]
Do you have your power jumper on vdd not usb?

**Comment by Xenomorphdelombre** [comment]
Yes VDD

**Comment by davidja92** [comment]
Sorry just to verify I have the red wires on the left and black on the right to power your bed and extruder?

**Comment by davidja92** [comment]
And check your 2 fuses

**Comment by Xenomorphdelombre** [comment]
> Sorry just to verify I have the red wires on the left and black on the right to power your bed and extruder?

Yes, Check both fuses, they are good 

This ia an odd one eh? :(

**Comment by davidja92** [comment]
Yeah you have exact same setup as me

**Comment by davidja92** [comment]
Does your bed mossfet power up? Should have an always on led and when u send power it should turn on another

**Comment by Xenomorphdelombre** [comment]
the always on Red is there, but when I send heat nothing lights up. As if the pins are wrong

**Comment by davidja92** [comment]
Do you have a spare mossfet to test ? Make sure it didn’t fail

**Comment by davidja92** [comment]
Hopefully it isn’t a bad board :( try hitting the reset button on the board itself

**Comment by davidja92** [comment]
When you went back to marlin the max temp error is cause by thermsistors broken it not plugged in

**Comment by davidja92** [comment]
Also why you bed heat shows 0.... verify wires are not broken and you don’t have them screwed down too tight

**Comment by Xenomorphdelombre** [comment]
I don't have another mosfet. The thermistor still works fine on the original Creality board. 

I haven'T try hitting reset... Let's see!

**Comment by Xenomorphdelombre** [comment]
Reset doesn't do anything. 

I tried Marlin without the probe connected as well as with the Define disable bogus maxtemp error. I was getting the same error. It start to look like a bad board...

**Comment by davidja92** [comment]
Join the klipper discord and post on the skr channel so we can get more people on this

**Comment by Xenomorphdelombre** [comment]
can you give me the link?

**Comment by davidja92** [comment]
https://discordapp.com/invite/df9yTE2

**Comment by Xenomorphdelombre** [comment]
Oh when I try to heat the hotend, there is one of the mosfet light that light up and then looks like the printer crashed. I couldn't control anymore had to power cycle

**Comment by davidja92** [comment]
You have an external mossfet on your hotend? External mossfet normally only for heatbed

**Comment by davidja92** [comment]
When you lose connection go into the terminal of octopi to see what the errors are

**Comment by Xenomorphdelombre** [comment]
No external mosfet.

Neverming I understand what happened. This is the HE1 fan that started because of
'HE1'
[heater_fan e0_fan]
pin: P2.4
heater: extruder
heater_temp: 50.0
fan_speed: 1.0

**Comment by davidja92** [comment]
Ahh ok

**Comment by davidja92** [comment]
Can you post up some nice pics of your board and how everything is plugged in so I can just comb through it

**Comment by Xenomorphdelombre** [comment]
https://imgur.com/a/L2chA5G

**Comment by davidja92** [comment]
Everything looks right I don’t get it...make sure the screws for the power wires all the way right and the actual metal wires making contact?

**Comment by davidja92** [comment]
Does the terminal report anything when u try to send heat to hot end or bed?

**Comment by Xenomorphdelombre** [comment]
I've got a bunch of these.

```
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
```

**Comment by davidja92** [comment]
Check the 3 boxes to suppress all those messages

**Comment by davidja92** [comment]
And send a m140 s50

**Comment by davidja92** [comment]
And advise on what the terminal returns

**Comment by Xenomorphdelombre** [comment]
Send: M140 S50
Recv: ok

**Comment by davidja92** [comment]
Put your hand on the bed is it getting warm?

**Comment by Xenomorphdelombre** [comment]
It is not, and the mosfet lef doesn't light up

**Comment by davidja92** [comment]
Klipper will error out after a 20 second timeout since it doesn’t have thermsistor showing the bed heating so just try to see if u feel any heat before the 20 or so seconds

**Comment by davidja92** [comment]
Verify your mossfet connection

**Comment by davidja92** [comment]
Any heat to your extruder by chance?

**Comment by Xenomorphdelombre** [comment]
No both are equialy cold. I tried to heat the bed and checked with a multimeter and no voltage on either bed or hotend screws

**Comment by davidja92** [comment]
You have a 3 wire or 4 wire mossfet?

**Comment by Xenomorphdelombre** [comment]
I'm not sure. See picture of the mosfet here: https://imgur.com/a/vhDvJUY

**Comment by davidja92** [comment]
On your hot bed can you refer the wires? And try to warm it up again

**Comment by Xenomorphdelombre** [comment]
refer?

**Comment by davidja92** [comment]
Reverse sorry..... online shows the board has the + and - backwards and it shouldn’t matter since the bed has no polarity since it’s just a resistor but some say switching it has worked

**Comment by Xenomorphdelombre** [comment]
Switched it, same result. I even switched one of the thermistor. Same result

**Comment by davidja92** [comment]
On you printer.cfg try changing your hotbed sensor pin to .23 instead of .25 let me know what happens

**Comment by davidja92** [comment]
If nothing move your hotbed thermsistor to th1 with the sensor pin still .23 and if nothing go back to normal...starting to sound like a bad bird out of ideas

**Comment by Xenomorphdelombre** [comment]
yeah I tried that. Looks like there is a portion of the board that is dead. Not all of it but maybe something was missed in manufacture. I will try to get it exchanged

Thanks for your help!

**Comment by davidja92** [comment]
No problem and good luck

**Comment by Xenomorphdelombre** [comment]
Bad board. Closing issue
