### ISSUE TITLE
Move exceeds maximum extrusion only after print restart

### ISSUE THREAD

**Issue by pmarkiewicz** [KevinOConnor/klipper#2776]
Move exceeds maximum extrusion (0.870mm^2 vs 0.640mm^2)

I have purge macro that is run at print start. I works after klipper restart and fails in mid of purge when I try to run print again (even same gcode). 
It was working correctly some time ago and appeared after klipper upgrade.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4529819/klippy.log)

**Comment by Hywelmartin** [comment]
it's not stated in the start of the macro if it's relative or absolute extrusion
Use absolute/relative distances for extrusion: M82, M83

**Comment by pmarkiewicz** [comment]
Thanks
