### ISSUE TITLE
Upgrading to Version 0.8.0

### ISSUE THREAD

**Issue by Xkc0** [KevinOConnor/klipper#2783]
Hi,

I´m trying to upgrade my Klipper instalation from 0.7.0 to 0.8.0, following the guide in the FAQ but the install-octopi.sh skript isn´t upgrading my klipper instalation. I´m running Octopi 0.16.0 and Ocotprint 1.4.0 on an Raspi 2B 1.1. 
What could I do to fix this?

Thanks for the amazing work

[klippy.log](https://github.com/KevinOConnor/klipper/files/4532946/klippy.log)

**Comment by pusewicz** [comment]
Simply updating klipper should be sufficient:

```
cd ~/klipper
git pull
sudo service klipper restart
```

**Comment by Xkc0** [comment]
Okay, thanks I'll check if this is working.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
