### ISSUE TITLE
Request: Use z probe speed for z axis speed in bed_tilt_calibrate

### ISSUE THREAD

**Issue by w1ebr** [KevinOConnor/klipper#279]
Hi Kevin,

Would you please use the z axis homing speed in the bed_tilt_calibrate routine?
(I am not good enough at python yet to understand where the z axis movement speed is set up for bed_tilt_calibrate; it appears to be passed a single speed value used for x and y but not used for z).

Thanks!
Gene

**Comment by KevinOConnor** [comment]
FYI, I've changed the probing code to limit the Z lift speed to be no greater than the Z probe speed (commit 68864333).  This should help reduce jerks of the Z axis.

Note, though, that this will use "[probe] speed" (and not "[stepper_z] homing_speed".  Also, this wont limit the initial Z position at the start of a bed_tilt_calibrate or delta_calibrate command (that remains limited by "[bed_tilt_calibrate] speed").
