### ISSUE TITLE
output_pin not work at skr e3 mini

### ISSUE THREAD

**Issue by whoim2** [KevinOConnor/klipper#2801]
if im adding:
```
[output_pin psupower]
pin: PC12
value: 0
shutdown_value: 0

```
printer not work:
`Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0x6fcb0dd0, open=True>(port='/tmp/printer', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Send: N0 M110 N0*125
Recv: ok
Send: N0 M110 N0*125
Changing monitoring state from "Connecting" to "Operational"
Send: N0 M110 N0*125
Recv: ok
Send: N1 M115*39
Recv: ok
Recv: ok FIRMWARE_VERSION:v0.8.0-443-gced389f4 FIRMWARE_NAME:Klipper
Send: M105
Recv: ok T:0
Send: G28
Recv: // Failed automated reset of MCU 'mcu'
Recv: // Once the underlying issue is corrected, use the
Recv: // "FIRMWARE_RESTART" command to reset the firmware, reload the
Recv: // config, and restart the host software.
Recv: // Error configuring printer
Recv: !! Failed automated reset of MCU 'mcu'
[klippy.zip](https://github.com/KevinOConnor/klipper/files/4558701/klippy.zip)
`

**Comment by KevinOConnor** [comment]
You likely need to add `restart_method: command` to the mcu section of your config - see config/example.cfg for the details.

-Kevin

**Comment by whoim2** [comment]
> You likely need to add `restart_method: command` to the mcu section of your config - see config/example.cfg for the details.
> 
> -Kevin

Thanks, worked! Maybe, add this to default stm32 configs?
