### ISSUE TITLE
No option "sensor_type" error

### ISSUE THREAD

**Issue by Akboo** [KevinOConnor/klipper#2802]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4558782/klippy.log)

**Comment by Akboo** [comment]
So, my problem, each time I connect Octoprint and do anything, I have this message error No option "sensor_type" in section "extruder"
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
Klipper state: Not ready

**Comment by pusewicz** [comment]
You have a section called `[stepper_extruder]` in your config file, whereas it should be called simply `[extruder]`.

**Comment by Akboo** [comment]
so like ive got the config fixd but now im getting this error
nable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
Unable to open port: Could not configure port: (5, 'Input/output error')
[klippy.log](https://github.com/KevinOConnor/klipper/files/4559648/klippy.log)

**Comment by Akboo** [comment]
Thanks you, my mistake was there. Problem solved
