### ISSUE TITLE
[bed_mesh] crash the Printer

### ISSUE THREAD

**Issue by darksoon** [KevinOConnor/klipper#2811]
Hello everyone,

here's the problem. When i set the bed mesh in my config the printer is not reachable anymore. If i leave out this setting the printer starts as usual and i can also run a G28. This "bug" only occurs no matter at which Position I insert the [bed_mesh]. I have included the current log. I hope someone can help me.

greetings

Hardware: 
- SKR 1.4 Turbo
- 2209 Driver
- Repetier Server

[klippy.log](https://github.com/KevinOConnor/klipper/files/4564830/klippy.log)

**Comment by Arksine** [comment]
It appears that Repetier is sending a gcode to Klipper while your MCU is trying to connect and bed_mesh isn't handling well.  I just created a PR for a fix.

**Comment by darksoon** [comment]
Hey,
This fix works perfekt thank you 😊
