### ISSUE TITLE
Printer sitting at 10mm when running bed_mesh or delta_config

### ISSUE THREAD

**Issue by Ratler5** [KevinOConnor/klipper#2813]
Every time I try and do a bed_mesh_calibrate or a Delta_configration (after G28)

the printer will move down and sit at 10mm off the bed and try probing without moving and just says
Send: bed_mesh_calibrate
Recv: // BLTouch failed to verify sensor state; retrying.
Recv: // BLTouch failed to verify sensor state; retrying.
Recv: !! BLTouch failed to verify sensor state
Recv: ok

But if i trigger my BLTouch with a piece of paper it will start moving and probe properly. 

Send: bed_mesh_calibrate
Recv: // probe at 0.010,-154.963 is z=9.781527
Recv: // probe at 0.010,-154.963 is z=1.294027
Recv: // Probe samples exceed tolerance. Retrying...
Recv: // probe at 0.010,-154.963 is z=1.294027
Recv: // probe at 0.010,-154.963 is z=1.294027
...

and idea how to fix?

[klippy.log](https://github.com/KevinOConnor/klipper/files/4566561/klippy.log)

thanks

**Comment by KevinOConnor** [comment]
This is covered briefly at https://www.klipper3d.org/BLTouch.html .  You may need to configure pin_up_touch_mode_reports_triggered.

-Kevin
