### ISSUE TITLE
M204 pls support

### ISSUE THREAD

**Issue by leungtech** [KevinOConnor/klipper#282]
it seems that klipper does not support m204, it is very important to control independent acceleration of infill and perimeter, just one acceleration is not perfect for surface quality.
pls add m204 support, thx!!

**Comment by tiziano149** [comment]
I agree. This was proposed for preassure advance alongside acceleration and junction deviation in issue #247
This was eventually implemented (see comments on #247) only for pressure advance but I would imagine that the procedure would be somewhat similar.

On another note, which slicer are you using that allows you to set accelerations per element (infill, outline, etc.)?

**Comment by leungtech** [comment]
Thx I use cura

**Comment by ScorpionTDL** [comment]
With Simplify 3D you can use the replace commands to insert more or less everything for different sections.
For Example you can add the following to the Terminal Commands for post processing:

{REPLACE "; raft" "M201 X1000 Y1000\n; raft"}
{REPLACE "; skirt" "M201 X1000 Y1000\n; skirt"}
{REPLACE "; infill" "M201 X4000 Y4000\n; infill"}
{REPLACE "; support" "M201 X5000 Y5000\n; support"}
{REPLACE "; gap fill" "M201 X2000 Y2000\n; gap fill"}
{REPLACE "; solid layer" "M201 X3000 Y3000\n; solid layer"}
{REPLACE "; inner perimeter" "M201 X1000 Y1000\n; inner perimeter"}
{REPLACE "; outer perimeter" "M201 X500 Y500\n; outer perimeter"}


An yea a implementation in Klipper would be nice.

**Comment by KevinOConnor** [comment]
I added a new SET_VELOCITY_LIMIT command (commit bdd26e42).  This new command allows the velocity, acceleration, and junction_deviation to be configured from a g-code command.

**Comment by ChiliApple** [comment]
Did I understand correctly that the M204 GCode command must be changed by a PostScript to the SET_VELOCITY_LIMIT command?

does anyone have a script or an example?
