### ISSUE TITLE
Printer screen blank but lit up blue... No info on screen

### ISSUE THREAD

**Issue by ZachGreatness** [KevinOConnor/klipper#2826]
I put the code for the BLTouch used with Teach Tech's tutorial, but now the screen is blank. It was working before, but I unplugged the printer and the Pi then I replugged it and tried to do the BLTouch code and now the screen has nothing on it except the blue light. Klipper will not start when trying to restart... It just disconnects. After trying some times, it says "Reported error: File contains parsing errors: /home/pi/printer.cfg"
[klippy.log](https://github.com/KevinOConnor/klipper/files/4573197/klippy.log)

**Comment by ZachGreatness** [comment]
Klipper will not start when trying to restart... It just disconnects. After trying some times, it says "Reported error: File contains parsing errors: /home/pi/printer.cfg"

**Comment by jakep82** [comment]
From your log

`ParsingError: File contains parsing errors: /home/pi/printer.cfg
	[line 106]: 'min_point 90, 20\n'`

You missed the colon.  It should be 

`min_point: 90`

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
