### ISSUE TITLE
Issue with TMC2130, homing with BLtouch

### ISSUE THREAD

**Issue by gdantonio79** [KevinOConnor/klipper#2829]
Hi,
when the homing phase of the axes starts, if the endstops are not activated after a certain time, the motors start to perform anomalous movements. Is it possible to set that time? If yes, how?
I have two motors to move the Y axis with only one endstop mounted in the Y max position, and if the motors do not reach the home in time the motors start to move on their own.
I would like to know how to set the bltouch, or have a starting point to set it.
Is it possible to test the correct communication of the SPI and the TMC2130 drivers? I mount the board MKS RUMBA32, on which the jumpers for the MISO signals have been made.
Thanks
[klippy.log](https://github.com/KevinOConnor/klipper/files/4577510/klippy.log)

**Comment by KevinOConnor** [comment]
It's not clear to me what's being reported here.  I recommend explicitly stating "what I saw" and "what I expected to see".

The length of homing moves is determined by the min_position and max_position configuration settings (and indirectly by the step_distance setting).  If the axis is not traversing the full distance on a homing move then double check these settings.

It's possible to query the tmc2130 drivers using the DUMP_TMC command - see docs/G-Codes.md for the details.

-Kevin
