### ISSUE TITLE
probe offsets correct but when BED_MESH_CALIBRATE is ran the "probe xxx.xx" is incorrect

### ISSUE THREAD

**Issue by iH8teF1ames** [KevinOConnor/klipper#2834]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4583563/klippy.log)
![IMG_3436 1](https://user-images.githubusercontent.com/30374881/81115079-28bda080-8ef1-11ea-9e48-02d4f7ca44e2.JPG)

**Comment by iH8teF1ames** [comment]
when looking at the terminal output it says the probe should be at  48.x but its pretty far off. The X and Y offset are from the BLTouch mounts page so they should be correct.

**Comment by Arksine** [comment]
The terminal doesn't tell you where the probe is, it tells you where the nozzle is.    It appears that you recently updated Klipper, so you may not be aware that the behavior of bed_mesh has changed (as outlined in Config_Changes.md).   With the current version of bed_mesh, it will generate points that place probe the actual designated area,  I see a `mesh_min: 10, 25` in your config, and it appears that your probe may be around X=10 in that picture.

**Comment by iH8teF1ames** [comment]
Interesting, ill look into that. So even though the terminal output says "probe at 48.x" it doesn't actually mean the probe and the position that its outputting is where the nozzle is?

**Comment by Arksine** [comment]
Correct.  When it says "probe at 48.x" the coordinate is the current tool position.  Perhaps that is something we could remedy by showing both the probe and tool locations.

**Comment by iH8teF1ames** [comment]
I think that could save some confusion for the future. Thank you for the insight! I will close the issue.
