### ISSUE TITLE
PID control/thermal shutdown

### ISSUE THREAD

**Issue by kevinrocksman** [KevinOConnor/klipper#285]
Is thermal safeties capable with Klipper?

**Comment by KenshiHH** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Releases.md

"Enhanced heater and thermistor hardware failure checks"

**Comment by kevinrocksman** [comment]
Where do I enable that?

**Comment by KevinOConnor** [comment]
On Mon, Apr 09, 2018 at 02:45:41PM -0700, kevinrocksman wrote:
> Where do I enable that? 

The heater checks are enabled by default.  The (recently updated) FAQ
has more info:

https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#will-the-heaters-be-left-on-if-the-raspberry-pi-crashes

-Kevin
