### ISSUE TITLE
unable to home or move axis aside from x axis

### ISSUE THREAD

**Issue by tsxfire** [KevinOConnor/klipper#2875]
here's the config file I have, but everytime I try to do anything on any axis other than X I can't do anything, when I use the dump stepper command I get 
but that happens for all the other steppers other than X as well
[klippy.log](https://github.com/KevinOConnor/klipper/files/4634099/klippy.log)

> The value 'stepper_z' is not valid for STEPPER

**Comment by BlackStump** [comment]
There is a big list of configs [here](https://github.com/KevinOConnor/klipper/tree/master/config)
choose the one that matches your printer and or your mcu and use that as a config to start from.
if you have [TMC Drivers](https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L1321) then use the example for every tmc driver that you have.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
