### ISSUE TITLE
bltouch position endstop in section 'stepper z' must be between position_min and position_max

### ISSUE THREAD

**Issue by R-Higgins** [KevinOConnor/klipper#2876]
Hi have the error 

position_endstop in section 'stepper_z' must be between position_min and position_max

I am using a BLtouch and just wanted to know what i am missing?

**Comment by R-Higgins** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4634588/klippy.log)

**Comment by BlackStump** [comment]
you have set the Bltouch 
z_offset: -4 
which is wrong for a bltouch - that is trigger distance of 4mm below the surface of the bed

**Comment by R-Higgins** [comment]
Magic mate i copied these from marlin setup and wasnt paying attention thanks very much
