### ISSUE TITLE
Recv: // Lost communication with MCU 'mcu'

### ISSUE THREAD

**Issue by Hairyloon** [KevinOConnor/klipper#2900]
As it says in the title. 
For no apparent reason, several hours into a long print...

Any clues?
I don't want a repeat performance if we can avoid it.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4658672/klippy.log)

ETA: I think I've recovered the print, but is there a feature that I've not discovered in Klipper to make it easier?
Could we think about one?

**Comment by jakep82** [comment]
This is generally indicative of a hardware issue.  See the FAQ for places to look.

https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#i-keep-getting-random-lost-communication-with-mcu-errors

**Comment by Hairyloon** [comment]
Given that I have been having undervoltage warnings and the low probability of finding any more clues (unless it happens again), I'll assume it was that and close this.
Thank you for the prompt response.
