### ISSUE TITLE
printrboard g2 not connecting to Klipper on raspberry pi 4 

### ISSUE THREAD

**Issue by Benyaaaa** [KevinOConnor/klipper#2905]
It just doesn't connect to the firmware I think.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4665514/klippy.log)

**Comment by KevinOConnor** [comment]
Typically these types of problems are due to an incomplete flash, or incorrect micro-controller settings in "make menuconfig".  Unfortunately, I don't have any further hints, and it doesn't look like anyone else does either.

-Kevin
