### ISSUE TITLE
Option 'mesh_origin' is not valid in section 'bed_mesh

### ISSUE THREAD

**Issue by dash3811** [KevinOConnor/klipper#2908]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4671413/klippy.log)

**Comment by Arksine** [comment]
The mesh_origin option applies to delta kinematics, you have a cartesian printer configured.

**Comment by qldestlp** [comment]
Greetings! After the update, klipper cannot configure the menu. I get an error. Tell me, how did you manage to get the right work?

**Comment by qldestlp** [comment]
> [klippy.log](https://github.com/KevinOConnor/klipper/files/4671413/klippy.log)

Greetings! After the update, klipper cannot configure the menu. I get an error. Tell me, how did you manage to get the right work?
