### ISSUE TITLE
Internal error on command:"G1"

### ISSUE THREAD

**Issue by Oranginator** [KevinOConnor/klipper#2924]
Hi guys,

i have no idea why I'm getting the error "Internal error on command:"G1"". Perhaps somebody is able to help me, thanks in advance!

Best regards Steffen
[klippy.log](https://github.com/KevinOConnor/klipper/files/4688547/klippy.log)

**Comment by Hywelmartin** [comment]
#2793

**Comment by Oranginator** [comment]
> #2793

I'm already using the latest build. I also updated my host software running on the SKR 1.1 Pro. With "make clean" etc.

**Comment by KevinOConnor** [comment]
There was an error in step flushing in certain cases where SET_PRESSURE_ADVANCE was called after a G4.  I think this should be fixed now (commit 9850dc75).

-Kevin

**Comment by Oranginator** [comment]
> There was an error in step flushing in certain cases where SET_PRESSURE_ADVANCE was called after a G4. I think this should be fixed now (commit [9850dc7](https://github.com/KevinOConnor/klipper/commit/9850dc75f4a7641a5bd12d9d2ccb7ca698619c88)).
> 
> -Kevin

Thank you, I'll try.

**Comment by KevinOConnor** [comment]
I'm going to close this as it is believed the Klipper bug is now fixed.

-Kevin
