### ISSUE TITLE
pressure advance vs linear advance

### ISSUE THREAD

**Issue by leungtech** [KevinOConnor/klipper#293]
In marlin 1.5, there is a function call linear advance, in klipper, there is pressure advance. Are they the same thing?? In marlin, linear advance will not retract, does pressure advance retract??
http://marlinfw.org/docs/features/lin_advance.html
Thx!!

**Comment by theopensourcerer** [comment]
There is documentation:

https://github.com/KevinOConnor/klipper/blob/master/docs/Pressure_Advance.md

**Comment by wizhippo** [comment]
Any chance we could modify or make use of something like http://marlinfw.org/tools/lin_advance/k-factor.html to tune pressure advance instead of printing the square such as replacing `M900 K0.4 ; set K-factor` with `SET_PRESSURE_ADVANCE ADVANCE=0.4`.

**Comment by wizhippo** [comment]
@dragonnn I'm going to try it, I was just hoping for constructive input/thoughts in regards to if the marlin testing method is just as good or if testing with a corner like the docs show would be better.  Perhaps one is more suited then the other for how they are implemented.

**Comment by KevinOConnor** [comment]
@wizhippo - when I first started thinking about pressure advance, I ran tests on my printer using a mechanism that seems similar to the marlin link above ( https://github.com/KevinOConnor/reprap-test/blob/master/extruder-spring/test-extruder-spring.py ).  Unfortunately, I found that method has two big drawbacks:
1 - minor changes in bed leveling have a significant impact on the results.  If the bed is just a little off, the test isn't useful.
2 - it's difficult to compare the results of two separate runs, thus making fine tuning harder.

In contrast, I've found the simple square test to be a very robust.  It takes a little longer to run, but the results are easy to interpret and very reliable.  The square could probably be a bit shorter to make it print faster, though.

Separately, the pressure advance documentation could use some updates.  I recently got my delta printer (with a long bowden tube) working well with a very high pressure advance (0.7).  (It's possible to get good results with a high pressure_advance if one lowers max_accel.)  Unfortunately, the ramps board on my delta melted ( https://imgur.com/a/FhHxV ) before I could finish my work on that.

**Comment by wizhippo** [comment]
Just for fun I ran it.  Bit hard to see as my bed is a mirror but it looks like high values work best.  My acceleration on the print is 2000mm/s.  You can see it here https://drive.google.com/open?id=0BxUx95JrlxN3bndGdXlVelRxczd3NVNvM1lpUjd5M2w2UTVF

Is it worth using such high values?

**Comment by Alexdad76** [comment]
@KevinOConnor 
> Unfortunately, the ramps board on my delta melted ( https://imgur.com/a/FhHxV ) before I could finish my work on that.

Always solder the power wires! This is a GRP (Good RAMPS Practice :-). 
[https://3deshnik.ru/wp-content/uploads/2015/10/IMG_5418.jpg](url)
[https://3deshnik.ru/wp-content/uploads/2015/10/IMG_5413.jpg](url)
I already know several cases of ignition of printers and even apartments ...
Be more careful! 
We need you alive and healthy!

**Comment by wizhippo** [comment]
@KevinOConnor Thanks for pointing out that you used a high value. After doing the test print I mentioned above 0.7 was looking good for me too.  I've since done multiple prints and have much better quality and less stringing.  I have reduced my retract distance from 6mm to 1mm.

**Comment by KevinOConnor** [comment]
Great.  I'm closing this topic though, as the original request (description of pressure advance) is already answered in the documentation.
