### ISSUE TITLE
[GCODE Arcs] Internal error on command:"G2"

### ISSUE THREAD

**Issue by Zwaubel** [KevinOConnor/klipper#2951]
Hi,

I am fiddling around with the gcode arcs extras module in combination with the octoprint arc welder plugin and am getting an 'Internal error on command:"G2"'.
From the log it seems that the get_status request in line 25 in the corresponding module is invalid.
I would appreciate any help.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4732112/klippy.log)

**Comment by KevinOConnor** [comment]
It looks like you have some kind of odd code merge.  Be sure to grab the latest code following the upgrade instructions in the FAQ: https://www.klipper3d.org/FAQ.html#how-do-i-upgrade-to-the-latest-software

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
