### ISSUE TITLE
Print work slow - Anet a8 Klipper

### ISSUE THREAD

**Issue by assafm25** [KevinOConnor/klipper#2960]
Hi, 
I use klipper for about 8 month.
All work well until the last 3 month.
I not use klipper and print for long time and when i try use it i see its work much slower then before (110)

I format my SD and re install and configure all but no news on the speed side.
`

[klippy.zip](https://github.com/KevinOConnor/klipper/files/4744764/klippy.zip)

`

**Comment by assafm25** [comment]
Any one ?!

**Comment by lbibass** [comment]
We need more information. What do you mean slow? Unresponsive? Slow print speeds? Stuttering?

**Comment by assafm25** [comment]
Hi,

Slow print speeds
its fills like its print on standard speed (50 mm)

**Comment by BlackStump** [comment]
Please supply the gcode that is printing slow for you.
Klipper is not slow so more then likely it is your slicer.

**Comment by assafm25** [comment]
Hi,

All of my prints are slow and not feels like on 110.
i can add some gcodes but all the same.
i use CURA

Some of my last prints:
https://www.thingiverse.com/thing:3008262

http://www.thingiverse.com/thing:1852762

**Comment by assafm25** [comment]
Mybe its a problem with my pi?

I Really don't know how to solved this.

**Comment by KevinOConnor** [comment]
I'm not sure there is much we can do to assist here - Klipper moves the toolhead at the speed specified in the gcode file.  If it's not running as fast as you'd like, you should configure the speed in your slicer.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the conversation has concluded.

-Kevin
