### ISSUE TITLE
How to limit motor feedrate at delta?

### ISSUE THREAD

**Issue by ZhenyaKa** [KevinOConnor/klipper#2973]
I print with fast speed 300mm/s (moving) with LV8729. (1/128, SKR1.3)
When print at center of table all is fine, but if head goes to edge of heatbed I got error:

"MCU 'mcu' shutdown: Stepper too far in past
This generally occurs when the micro-controller has been
requested to step at a rate higher than it is capable of
obtaining."

Is any method to limit max motor/driver feedrate

[klippy.log](https://github.com/KevinOConnor/klipper/files/4758239/klippy.log)

**Comment by KevinOConnor** [comment]
The only mechanism to limit velocity on a delta in Klipper is by setting the max_velocity parameters in the printer section of the printer.cfg file.  As indicated in docs/Kinematics.md, the actual velocity and accel can go up to 3 times this value in some cases (see that document for the details).

As for the original error you reported - the log is incomplete so there's little we can do to assist with that.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
