### ISSUE TITLE
How to limit logfile size?

### ISSUE THREAD

**Issue by ZhenyaKa** [KevinOConnor/klipper#2974]
Is any options for that?

I have 2 deltas, /tmp placed at ramdisk.

I have 2 files and them oversized very quckly

Is any method to limit 5-6 print session in log file? And when create new log

[klippy.log](https://github.com/KevinOConnor/klipper/files/4758256/klippy.log)

Maybe anybody have well working logrotate config for that?

**Comment by KevinOConnor** [comment]
There is no current mechanism to limit log file size.  However, the logs are automatically rolled over every day and only 5 days are kept.

-Kevin

**Comment by ZhenyaKa** [comment]
Yes, but I have two printers connected to Orange Pi Lite and when they print both I got huge logs for my ramdisk (/tmp) :(

**Comment by KevinOConnor** [comment]
I'm going to close this as the original question was answered (it is not currently possible).

-Kevin
