### ISSUE TITLE
 Failed to home x: Timeout during homing

### ISSUE THREAD

**Issue by Mckevinho** [KevinOConnor/klipper#2975]
Hi,

I'm making a new printer but i've problems with my steppers.

First, i bought a new board (MKS gen L V2.1) for the new printer. After i copied my settings from my first printer (ender3) and pasted it in a new config file. I just changed the pinnumbers the the MKS pinnumbers and the serial usb. The other settings i didn't change just to test the steppers but the steppers doesn't move with this. 

when i ask to home x or y, i get always instantly next error  "Failed to home x: Timeout during homing"

with the ender3 printer and the original config file, it works fine.

this is the klippy.log from the MKS board with the new configfile
[klippy.log](https://github.com/KevinOConnor/klipper/files/4759226/klippy.log)

**Comment by KevinOConnor** [comment]
FYI, it's possible to use multiple Z steppers on corexy, and it's possible to use multiple X and Y steppers on cartesian, but it is not currently possible to define multiple "XY" steppers on corexy.  If a cable splitter is used, then that should work with Klipper.

-Kevin

**Comment by Mckevinho** [comment]
Thanks all for respons👍

I will use cablesplitters

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
