### ISSUE TITLE
Ender 3 / 3D Touch - Failed to verify BLTouch probe is raised

### ISSUE THREAD

**Issue by federov31** [KevinOConnor/klipper#2987]
Hello,

I'm using a [SKR Mini E3 1.2](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/hardware/BTT%20SKR%20MINI%20E3%20V1.2/The%20Notement%20of%20BTT%20SKR%20MINI%20E3%20V1.2.pdf) with a Creality Ender 3 Pro and a [3DTouch from Trianglelabs](https://www.aliexpress.com/item/32832887426.html)

_**Klipper Firmware version: v0.8.0-585-g35bbd989**_

I've been printing all day and **my BLTouch was ok**, when I launch my `BED_MESH_CALIBRATE` it keeps displaying :

```
Recv: // Failed to verify BLTouch probe is raised; retrying.
Recv: // Failed to verify BLTouch probe is raised; retrying.
Recv: !! BLTouch failed to raise probe
```
I've followed the direction in the [BLTouch Initial tests](https://github.com/KevinOConnor/klipper/blob/master/docs/BLTouch.md) and everything is fine but when running the `BED_MESH_CALIBRATE` stops printing sequence. 

My Wiring 
![skr-mini-e3-v1 2-bltouch-drawing__compressed](https://user-images.githubusercontent.com/43416516/84579830-90f58100-add1-11ea-92fe-6e12fae398d6.jpg)

Can anyone help please ? 

You can find my logs and config attached

[klippy.log](https://github.com/KevinOConnor/klipper/files/4775708/klippy.log)

**Comment by federov31** [comment]
Gave it another try with **v0.8.0-582-g467e8e6f-20200610_151351-octopi**

Here's the Klipper.log 

[klippy.log](https://github.com/KevinOConnor/klipper/files/4775703/klippy.log)

**Comment by madsi1m** [comment]
Hi, I use skr mini 1.2 e3 with an Ender3 and a 3D Touch. Maybe some of my settings might help: https://github.com/madsi1m/MD_Klipper/blob/master/printer.cfg

**Comment by federov31** [comment]
I'll give it a try, why did you set `step_distance: 0.003125` because default for Creality is `step_distance: .0125` ?

**Comment by madsi1m** [comment]
With step distance I noticed a few things, first the mcu is mostly idle during a print, so there is room for it to process more commands. Second I experimented with some test prints and it seems like having more steps gives me a cleaner print which implies that the interpolation on the tmc2209 are not as good as Klipper sending more commands to the mcu.

With the 3D Touch also double check the connector plugs on the mcu, mine were a bit loose, maybe yours is also. Other thing I suspect is the +5V line on the skr could be a little dirty on mine, but yours is a Pro with a better PSU.

How did you connect the bltouch to the skr? Is it in the z-probe pin?

**Comment by federov31** [comment]
Hey @madsi1m , thanks for your time ! 

I wired as described in my first post. I also figured that the connector is a bit loose. I'll give it a try

![20200614_233559](https://user-images.githubusercontent.com/43416516/84604672-ec8a4200-ae97-11ea-9bc3-9487592a6fd4.jpg)

**Comment by madsi1m** [comment]
Somewhat off topic, but i also got sensor-less homing working for the x+y. (I can see you have the x+y endstops plugged in). Something to play with once the z is fixed.

**Comment by federov31** [comment]
I've done the wiring again , and now the probe is working fine :). The wire leading to the Z stop was damaged ! 

Concerning the X&Y sensorless homing due to the fact that I was previously printing with Klipper between 150 and 200 mm/s, I would rather not using them because I'm afraid of skipping steps. What do you think ?

**Comment by madsi1m** [comment]
Glad you found the problem.

With sensor-less homing, should not matter as the "bump" is only detected during homing. Also adjust `driver_SGTHRS` which is sensitivity. I haven't uploaded my latest yet but for my x i have it on 40 and my y is on 100. You will have to experiment so that it doesnt smash the side too hard and doesn't trigger on some dust on the wheels.

Other thing that might be of interest is the `gcode_button kill_switch` I use the original z endstop for this and have set it lower than the 3d touch so it triggers only when the 3d touch fails and the nozzle hits the bed.

**Comment by federov31** [comment]
I'll get back to Klipper now that my BL is working.
Would you mind sharing your working config on Git so I can give it a try ? @madsi1m

**Comment by madsi1m** [comment]
Updated, take only what you need, as things like z-offset and pid number will probably be different.

**Comment by federov31** [comment]
Hello I'm using your configuration right now and it's cool. I had to change the value for the extrudeur because it was skipping steps and clicking a lot. 

Is there a way to calculate those values ? Also is it possible to calculate the vref ?
