### ISSUE TITLE
Tool not heating when print is loaded in octoprint

### ISSUE THREAD

**Issue by Diana6969** [KevinOConnor/klipper#3020]
It's not that serious of an issue, but I really don't want to be switching the tool temps all the time. When I load and select print through octoprint it automatically selects the target temperature for the bed (from cura profile settings), but it doesn't do that for the tool.
I would be happy to hear any solutions!
PS: Kevin, what a marvellous job, I mean the Klipper is just amazing.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4826731/klippy.log)

**Comment by jakep82** [comment]
Not sure I follow what you're reporting.  I see no problems in the log regarding heating.  Have you looked at the gcode file in question to verify it's requesting the correct temperatures?  The log shows an initial hotend temp of 100, followed by a change to 215.

**Comment by jakep82** [comment]
Temperature is controlled by gcode.  If your start gcode includes `M109 S215`, then klipper will heat the hotend to 215 and wait until it reaches that temperature before running the next line of gcode.

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it looks like the original question was answered (specify the temperature in the slicer).

-Kevin
