### ISSUE TITLE
Arduino aliases not supported on mcu 'atmega1284p'

### ISSUE THREAD

**Issue by wjg68** [KevinOConnor/klipper#3045]
Getting the following error message trying to connect. please help.
Arduino aliases not supported on mcu 'atmega1284p'

[klippy.log](https://github.com/KevinOConnor/klipper/files/4869911/klippy.log)

**Comment by theopensourcerer** [comment]
The message tells you there is no support for Arduino pin names for that mcu. So you have to use the "native" hardware pin names:

https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L11

The Creality CR-10 boards seem to use this MCU so maybe one of the CR-10 the example config files might help, e.g.:

https://github.com/KevinOConnor/klipper/blob/master/config/printer-creality-cr10-2017.cfg

**Comment by wjg68** [comment]
thanks for the reply, I got the ender 3 w bltouch .cfg  file working. been working through some new errors but its connected to klipper. issues with the pid tuning. think i might be close. thanks againf for help.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like a solution was found for the original question.

-Kevin
