### ISSUE TITLE
Printer not ready after unplugging

### ISSUE THREAD

**Issue by samnab** [KevinOConnor/klipper#3048]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4871998/klippy.log)

Hi,

Novice here. So I had to move my printer and unplugged it from the Pi. After when the relocation I tried to print I continuously got "Klipper state: Not ready". I uninstalled klipper and reinstalled and I was not able to get the name of the USB port using "ls /dev/serial/by-id/*" not sure what to do. Log and cfg should be attached.
[printer.txt](https://github.com/KevinOConnor/klipper/files/4872004/printer.txt)

Any help would be appreciated.

**Comment by ld3300** [comment]
Hi @samnab ,

is it clear that the MCU is powered? are you using the same USB cable?

David

**Comment by KevinOConnor** [comment]
These types of issues are generally the result of a failed attempt to flash the micro-controller code.  Double check that procedure.  If you can't get any indication that there is a USB device attached to the machine then it may be a bad cable or problem on the printer board.

-Kevin
