### ISSUE TITLE
default_parameter_EXTRUDER_TEMP overrides Slicer Temp

### ISSUE THREAD

**Issue by DroneMang** [KevinOConnor/klipper#3052]
Hi,

In my start script I define "default_parameter_EXTRUDER_TEMP", but it appears I have to change it for each print.  If I print at 0.1 layer height, I use a lower temp.  I found that the slicers temp would not update klippers set temp for the extruder once the print starts after the start script has run.  Can I just omit default_parameter_EXTRUDER_TEMP somehow?

This log shows the behavior.  I preheated to 220, then the print started and followed the sliced file and went down to 200, but then the start script took over and sent it back to 220, but no return to 200.

Thanks,
DroneMang

[klippy4.zip](https://github.com/KevinOConnor/klipper/files/4873683/klippy4.zip)

**Comment by DroneMang** [comment]
I have solved it.  Here is my start script.  S3D handles a lot of what is in the example start script.

Could a simplified start script be added to the documentation, and noted in the slicers guide?

[gcode_macro START_PRINT]
gcode:
    BED_MESH_PROFILE LOAD=test_5_17x8
    # Use absolute coordinates
    G90
    # Reset the G-Code Z offset (adjust Z offset if needed)
    SET_GCODE_OFFSET Z=+0.45
    # Home the printer
    G28

**Comment by ld3300** [comment]
I believe the startup script is a really good starting place, but perhaps it needs an example of how to implement it in the slicer to function properly.  It is intended to pass the temperatures to the command and replace  or supplement the existing slicer g-code

**Comment by KevinOConnor** [comment]
I'm unsure what is being reported here.  The parameters can be modified in the config, manually at the start of each print, or in the slicer - that choice is yours.  There is documentation on this in docs/Command_Templates.md.

-Kevin

**Comment by DroneMang** [comment]
Okay. I think I've got this one figured out, thanks! This can be closed.
