### ISSUE TITLE
Unable to open port: [Errno 13] Permission denied: '/tmp/klipper_host_mcu'

### ISSUE THREAD

**Issue by hevilp** [KevinOConnor/klipper#3058]
I just followed
https://github.com/KevinOConnor/klipper/blob/master/docs/RPi_microcontroller.md

and stuck on:

`Unable to open port: [Errno 13] Permission denied: '/tmp/klipper_host_mcu'`

If I do `chmod 777 /tmp/klipper_host_mcu` and restart klipper, it works.

Do we have a fix for it?
[klippy.log](https://github.com/KevinOConnor/klipper/files/4875521/klippy.log)

**Comment by Arksine** [comment]
Rather than chmod /tmp/klipper_host_mcu to 777, the solution is to add your user to the tty group.  The documentation has been updated to reflect this.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original question was answered.

-Kevin
