### ISSUE TITLE
pid_Ki: 0 crashes Klipper

### ISSUE THREAD

**Issue by yschroeder** [KevinOConnor/klipper#3066]
When I try to set `pid_Ki` of the extruder to 0 (to calibrate via the Ziegler-Nichols method), Klipper crashes:

```
 Internal error during connect: float division by zero
```

One could argue that you never want Ki to be 0, but I still dont think Klipper should crash in this case.

[klippy.log](https://github.com/KevinOConnor/klipper/files/4890262/klippy.log)

**Comment by KevinOConnor** [comment]
FYI, this does look like a Klipper bug.

-Kevin

**Comment by KevinOConnor** [comment]
This should be fixed now (commit f8cb1e30).

-Kevin
