### ISSUE TITLE
PROBE_CALIBRATE configured z offset for BLTouch not respected when printing.

### ISSUE THREAD

**Issue by BlazingBlackBeard** [KevinOConnor/klipper#3075]
[klippy.log](https://github.com/KevinOConnor/klipper/files/4904243/klippy.log)

**Comment by ld3300** [comment]
hi @BlazingBlackBeard 

you haven't given a lot of context to work from.  Some description of what you are seeing, and the steps you have taken would go a long way towards finding the solution.  I can see you've done z height calibration.  What are you doing at the beginning of your print g-code?  Where are you seeing the failure?  How far off does the height seem to be?

David

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
