### ISSUE TITLE
12864 LCD for Ramps FD

### ISSUE THREAD

**Issue by kevintong116** [KevinOConnor/klipper#308]
What is the pin definition for the Ramps FD V2?
I can't get it work

**Comment by KevinOConnor** [comment]
The display code has not been enabled on the Due (no one has tested it).  If you're willing to run test code and report back the status then let us know.  If so, you'll need to be certain of the pin mappings to the display, and you should start by providing the klipper log file from your current config.

-Kevin

**Comment by kevintong116** [comment]
how can I help?

**Comment by KevinOConnor** [comment]
FYI, I was able to test the hd44780 and st7920 displays on my Due.  The micro-controller code worked fine on both, so I enabled them (commit 018c5daa).

**Comment by kevintong116** [comment]
I cant enable the st7920 displays
