### ISSUE TITLE
No option 'min_x' in section: bed_mesh

### ISSUE THREAD

**Issue by goosst** [KevinOConnor/klipper#3085]
Hello,

had the following issue: 
[klippy.log](https://github.com/KevinOConnor/klipper/files/4914165/klippy.log)

- did a (manual) bed mesh calibration on a delta printer
- executed the commands: `BED_MESH_PROFILE SAVE=mirror_bed` and `SAVE_CONFIG`
- results in the following error (when restarting or executing `BED_MESH_PROFILE LOAD=mirror_bed`):
```
Send: BED_MESH_PROFILE LOAD=mirror_bed
Recv: // No option 'min_x' in section: 'bed_mesh mirror_bed'
Recv: // Once the underlying issue is corrected, use the "RESTART"
Recv: // command to reload the config and restart the host software.
Recv: // Printer is halted
Recv: !! No option 'min_x' in section: 'bed_mesh mirror_bed'
Recv: ok
```

It doesn't sound like a legitimate error since it's a delta printer.

thanks!

**Comment by goosst** [comment]
p.s. manually deleting the mirror_bed from the (autogenerated) configuration, resolved the issue as well.

**Comment by Arksine** [comment]
I see what is happening here, I will push a fix in my next bed_mesh pull request. 

In the meantime you can work around this by saving the profile to a different name after calibration, before you enter SAVE_CONFIG.  It is the restart and load that is causing the issue.

**Comment by KevinOConnor** [comment]
FYI, PR #3111 was merged.

-Kevin
