### ISSUE TITLE
Macro M600 after timeout 

### ISSUE THREAD

**Issue by daredevil-ferreira** [KevinOConnor/klipper#3094]
[
[
[klippy.log](https://github.com/KevinOConnor/klipper/files/4919456/klippy.log)
](url)
[printer.txt](https://github.com/KevinOConnor/klipper/files/4919410/printer.txt)

When I M600, if I immediately change my filament, then execute de macro RESUME_MACRO, then resume Octoprint, it works.

If I leave my printer some time, temperature from bed & nozzle are set off automatically (I assume some security here when there is no move). 
In that case, when I try to use the RESUME_MACRO, I got the message to home first.

------
Send: RESUME_MACRO
Recv: // Unknown command:"M117"
Recv: !! Must home axis first: 22.994 25.929 25.485 [250.850]
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Must home axis first: 22.994 25.929 25.485 [250.850]
-----

**Comment by daredevil-ferreira** [comment]
Is there a way also to maintain the bed temperature after pausing the print ?

**Comment by Hywelmartin** [comment]
extend the idle timeout by incorporating SET_IDLE_TIMEOUT TIMEOUT=3600 into your M600 and reset the idle timeout in the resume macro with SET_IDLE_TIMEOUT TIMEOUT=600

**Comment by daredevil-ferreira** [comment]
Great, it works perfectly.
Thanks

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the original issue was resolved.

-Kevin
