### ISSUE TITLE
Filament end detected

### ISSUE THREAD

**Issue by TomaszKn** [KevinOConnor/klipper#311]
Does Klipper support filament end detected.

Regards
Tom

**Comment by KenshiHH** [comment]
https://github.com/KevinOConnor/klipper/tree/master/docs

**Comment by TomaszKn** [comment]
Could you write me more precision answer?

**Comment by KevinOConnor** [comment]
This looks like a duplicate of issue #249.  Alas, filament sensors are not currently supported.

-Kevin

**Comment by KevinOConnor** [comment]
I'm closing this in favor of the existing issue #249.
