### ISSUE TITLE
Spurious endstop trigger.

### ISSUE THREAD

**Issue by Hairyloon** [KevinOConnor/klipper#3137]
I imagine that this is a hardware problem rather than Klipper, but I don't know who else to ask for advice on this and I might be wrong and it is klipper.

I had a problem today where the endstop was triggered when the endstop wasn't triggered: the switch was open, my meter said the switch was open, but klipper said it was triggered.
I've got around it by connecting the switch to a spare pair of pins, but then I had the same problem with the probe, which I got around in the same way, but I don't have any more spare slots...
Any thoughts or ideas? 

[klippy.log](https://github.com/KevinOConnor/klipper/files/5001810/klippy.log)

**Comment by cyclonesurfer** [comment]
Did you recently update klipper?

My z endstop is always triggered after updating klipper and it worked previously.

https://github.com/KevinOConnor/klipper/issues/3134

**Comment by Hairyloon** [comment]
> 
> 
> Did you recently update klipper?
> 
No.
One minute it was working, then next it wasn't.
All I've done in between is wind it up and down the Z-axis (I wanted to check something).

> My z endstop is always triggered after updating klipper and it worked previously.
> 

Have you checked your printer.cfg still has the right pin set?

**Comment by cyclonesurfer** [comment]
Yes, I tried the Z+ also.

Checked with multimeter, triggered in any condition.

**Comment by Hairyloon** [comment]
You don't have an X+ or Y+ that you could live without?
Even if only for the purpose of testing.
That's what I'm doing on mine, though this printer never had X+ or Y+ endstops.

**Comment by cyclonesurfer** [comment]
Yes, my X+ and Y+ have been modified (by me) to be regular gpio pins

**Comment by KevinOConnor** [comment]
It sounds like a hardware problem.  This isn't a great place to ask about possible hardware issues as no one here really knows the particular hardware you have.

-Kevin

**Comment by Hairyloon** [comment]
It does sound like hardware, I said that at the start, and I can't see any way that it can be anything other than hardware, but it seemed odd to me that two sets of pins would suddenly stop working for no apparent reason.

**Comment by Sineos** [comment]
It could be an EMI / electromagnetic noise problem.
Is your board / end-stops equipped with filtering capacitors? If not try soldering a 100nF cap across the end-stop connectors or go for shielded end-stop cables.

**Comment by KevinOConnor** [comment]
I'm going to close this as it doesn't look like it is an "open issue" that needs to be tracked in Klipper.

-Kevin
