### ISSUE TITLE
Internal error on G1 command

### ISSUE THREAD

**Issue by bryanboettcher** [KevinOConnor/klipper#3147]
I occasionally get firmware crashes with G1 errors, with no reliable way to reproduce them.  Any ideas appreciated.

[klippy.zip](https://github.com/KevinOConnor/klipper/files/5012937/klippy.zip)

**Comment by KevinOConnor** [comment]
As discussed on IRC, this does look like a Klipper bug.  It will likely take a few days for me to follow up in more detail though.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, the error found in #3142 may have caused this issue.  As such, I recommend you update to the latest code (see the FAQ for upgrade instructions).  Let us know if the problem reoccurs with the latest code.

-Kevin
