### ISSUE TITLE
Internal error during connect: Choice 'item' for option 'type' is not a valid choice

### ISSUE THREAD

**Issue by robustini** [KevinOConnor/klipper#3186]
I've aligned Klipper to the master and now it gives me this error.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5072694/klippy.log)

**Comment by robustini** [comment]
I saw the differences in the menu.cfg, I adapted my cfg.

**Comment by cronos45** [comment]
Can you add a link to the differences you speak of?
