### ISSUE TITLE
Octoprint Menu LCD Screen

### ISSUE THREAD

**Issue by schnello** [KevinOConnor/klipper#3187]
Hi.

Since the latest update the Octoprint menu is "broken"

If the printer is in idle:
![image](https://user-images.githubusercontent.com/6481341/90219778-1663d480-de07-11ea-916b-34f812a14819.png)

If the printer is active:
![image](https://user-images.githubusercontent.com/6481341/90219796-2085d300-de07-11ea-9a65-0fbd342a4b80.png)

Any idea @mcmatrix?

**Comment by schnello** [comment]
Ok i found the problem but i dont understand why.

For better maintance i create a local copy of the user_menu.cfg and add this in my printer.cfg
[include klipper-config/user_menu_custom.cfg]

This works well in the past. But since the latest commit the octoprint menu item is broken. All other items are ok. If i fall back to the original user_menu.cfg all is fine. (user_menu_custom.cfg is atm a 1:1 copy, no modifications done yet)

**Comment by mcmatrix** [comment]
Hi @schnello 
Are these duplicate entries real menu items or remnants on the screen (can you select them)?

Could you share your full printer config.

**Comment by schnello** [comment]
Attached the full config.

>Are these duplicate entries real menu items or remnants on the screen (can you select them)?

Atm iam not at home but i will try it after work.
[klipper_config_schnello.zip](https://github.com/KevinOConnor/klipper/files/5073253/klipper_config_schnello.zip)

**Comment by mcmatrix** [comment]
Please try PR #3189
It should solve your issue.

**Comment by schnello** [comment]
Thanks for the quick fix. Looks good.
![image](https://user-images.githubusercontent.com/6481341/90259579-8cd5f600-de4a-11ea-8f59-df64e079186b.png)

**Comment by schnello** [comment]
@mcmatrix 
Onyl as gen question:
Is there a reason why in the main user_menu.cfg files the printer var are not used in the movement section:
input_max: 200
vs.
input_max: {printer.configfile.config.stepper_y.position_max}
