### ISSUE TITLE
Endstop Position with Probe

### ISSUE THREAD

**Issue by ich777** [KevinOConnor/klipper#319]
Hello Kevin,

i've discovered that the "position_endstop: 0.5" setting from the section "[stepper_z]" doesn't work if the probe is enabled, in my config the "z_offset: 2.25" from the section "[probe]" overrides it.
It doesn't matter what i set at "position_endstop: 0.5" for example i could take a value of 10 and it doesn't effect anything.
Must i provide the "position_enstop: 0.5" under "[stepper_z]" or can i delete the line?

Is it a bug or a feature? :D

**Comment by KevinOConnor** [comment]
That's very strange.  Can you reproduce, issue M112, and then post the log?

**Comment by KevinOConnor** [comment]
Closing, pending a log of the issue.
