### ISSUE TITLE
Printer is not ready (log attached)

### ISSUE THREAD

**Issue by HagglesworthMD** [KevinOConnor/klipper#3191]
Hi all,

New to this and I cant seem to connect to Klipper, I've attached log file.

Thanks for any insight.

[LOG.txt](https://github.com/KevinOConnor/klipper/files/5078339/LOG.txt)

**Comment by theopensourcerer** [comment]
In your log:

`Unable to open port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'`

Suggest going back to the FAQ and checking how to find your USB device. Also check cabling and power etc...
