### ISSUE TITLE
menu: not possible to override or hide items on default menu

### ISSUE THREAD

**Issue by danielfmo** [KevinOConnor/klipper#3212]
Hello,

The new implementation of the menu #2344 brings two limitations regarding the previous implementation.

1. As `menu.cfg` is loaded before main configuration (lines 654 and 656 of menu.py) it is not possible to override any `menuitem` from the default `menu.cfg` #3189 .

2. There is no mechanism that allows to hide or remove an existing `menuitem` from the default `menu.cfg`

For now, in order to have an usable menu, I have all my menu configuration in my printer.cfg and commented out the line 654 from `menu.py` so that `menu.cfg` is not loaded.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5098532/klippy.log)

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/issues/3199

**Comment by danielfmo** [comment]
Proposed solution of #3199 works
