### ISSUE TITLE
Bed Temp seems to keep climing - even after tuning.

### ISSUE THREAD

**Issue by changedsoul** [KevinOConnor/klipper#3224]
[klippy.log-1.txt](https://github.com/KevinOConnor/klipper/files/5110864/klippy.log-1.txt)

I am seeing issues with my bed reaching temp. If I approach the temp from below, it seems to work fine. However, If I preheat the bed to say 60C and then try to print with an M190, the printer just sits waiting. 
Watching the temp when I do this, it seems if the temp has drifted a tad over 60C.
Watching the light for the heated bed, instead of it just turning off the bed power to allow it to cool, I see it applying power and it keeps heating it, slowly increasing the temp past the set point by a few degs, instead of dropping down.

I did a bed tune a few times and the issue still persists.

Can you confirm if this is a bug?

**Comment by KevinOConnor** [comment]
This is generally the result of poor heater pid parameters.

For some heaters that are very powerful (and thus cause rapid heating), some people have reported success by configuring a lower `max_power` setting.

-Kevin

**Comment by changedsoul** [comment]
Thank you for the suggestion. 
I would assume that if I ran a pid tune with the default of 1 for max_current and it’s still not correct, running the tune again after I modify max_current would probably put me right back where I am, with the temp slowly climbing.  
I’ll experiment and report back. Hope it works. 
Thanks.

**Comment by changedsoul** [comment]
Well I tried the max power option and it didnt work well for me. I probably implemented it wrong in my config. 
No matter, as the outside temps are now not surface of the sun status, it seems to be working better like it used to.
Seems it was the extreme ambient temp heat causing the issues.
