### ISSUE TITLE
Bug: SAFE_CONFIG with PROBE_CALIBRATE fails

### ISSUE THREAD

**Issue by apphead** [KevinOConnor/klipper#3227]
I followed the procedure outlined [here](https://www.klipper3d.org/Bed_Level.html). On ACCEPT and SAVE_CONFIG, I get this message (see terminal out below): 
**SAVE_CONFIG section 'bltouch' option 'z_offset' conflicts with included value**

`
Send: PROBE_CALIBRATE
Recv: // probe at 100.000,150.000 is z=1.610373
Recv: // probe at 100.000,150.000 is z=1.604712
Recv: // probe at 100.000,150.000 is z=1.602196
Recv: // Starting manual Z probe. Use TESTZ to adjust position.
Recv: // Finish with ACCEPT or ABORT command.
Recv: // Z position: ?????? --> 6.606 <-- ??????
Recv: ok
[...]
Send: TESTZ Z=-6.1
Recv: // Z position: ?????? --> 0.506 <-- 6.606
Recv: ok
[...]
Send: TESTZ Z=-.1
Recv: // Z position: ?????? --> 0.406 <-- 0.506
Recv: ok
[...]
Send: TESTZ Z=-.1
Recv: // Z position: ?????? --> 0.306 <-- 0.406
Recv: ok
[...]
Send: ACCEPT
Recv: // bltouch: z_offset: 1.300
Recv: // The SAVE_CONFIG command will update the printer config file
Recv: // with the above and restart the printer.
Recv: ok
[...]
Send: SAVE_CONFIG
Recv: !! SAVE_CONFIG section 'bltouch' option 'z_offset' conflicts with included value
Recv: ok
[...]
`
[klippy.txt](https://github.com/KevinOConnor/klipper/files/5113620/klippy.txt)

**Comment by KevinOConnor** [comment]
If you configure the bltouch in a config file other than printer.cfg then you can't use SAVE_CONFIG with the bltouch.  (That is, if it's configuration is in a file that printer.cfg loads via `[include my_other_config.cfg]`.)  Either manually update the config with the new z_offset settings or only configure the bltouch in the main printer.cfg file.

-Kevin

**Comment by apphead** [comment]
Hi Kevin. Maybe you should mention that ` only configure the bltouch in the main printer.cfg file.` in the documentation.

**Comment by Vassssko** [comment]
Why not update multiple files on save config? Like put # on included value and put measured value into main cfg?
