### ISSUE TITLE
TMC Extruder Enabled but not moving

### ISSUE THREAD

**Issue by jieweiyang** [KevinOConnor/klipper#3228]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5114057/klippy.log)

[klippy.log.txt](https://github.com/KevinOConnor/klipper/files/5114058/klippy.log.txt)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/5114081/printer.cfg.txt)

[pins_GT2560_V3.0.h.txt](https://github.com/KevinOConnor/klipper/files/5114060/pins_GT2560_V3.0.h.txt)

Just moved from Marlin to Klipper, most of the basic functions has been successfully migrated and tuned.

The only issue is the extruder with TMC_2130, once issued a G1 command, it is enabled, jump a step, and then not moving. Connect the extruder cable to a bare stepper still the same.

Dump_tmc showed there are lost steps. 
The TMC2130 definition is similar to X/Y steppers.
Extruder minimum temperature set to 20 lower than room temp already.
MM/Step calculated from  Marlin Steps/MM with Titan Extruder.

Commented out all TMC2130(Extruder) settings, STP/DIR/EN pin remain the same, run 4988 without issue.

**Comment by KevinOConnor** [comment]
I'd recommend using the STEPPER_BUZZ command to verify the config, as described in the Config_checks document: https://www.klipper3d.org/Config_checks.html

Otherwise, it seems like Klipper is successfully communicating with the tmc2130.  It may be a hardware fault of some kind in the driver or its wiring.

-Kevin

**Comment by jieweiyang** [comment]
All hardware wiring remain the same as migrated from Marlin on same board.  Stepper_Buzzer also tried and same symptom.
Will try to swap the stepper stick with X or Y and try again.
