### ISSUE TITLE
Ender 3 + Bltouch problems

### ISSUE THREAD

**Issue by Duz1nho** [KevinOConnor/klipper#3258]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5139820/klippy.log)

Hi, I´ve installed ok everything, but, when I´m turn on printer and send G28 command without send BLTOUCH_DEBUG COMMAND=reset before, the printer´s halted and show the message 

Recv: // Failed to verify BLTouch probe is raised; retrying.
Recv: !! BLTouch failed to deploy

If I send BLTOUCH_DEBUG COMMAND=reset , and after G28, the command execute ok.

I´m already test the pin_up_touch_mode_reports_triggered: Falseat bl_touch parameters, but no effect.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5139841/klippy.log)

**Comment by BlackStump** [comment]
[best advice with anything Bltouch is here](https://www.klipper3d.org/BLTouch.html)
also 
make sure you see the Bltouch do a self test on power up  (ie pin down , pin up , pin down, pin up) and not go into error mode
