### ISSUE TITLE
Internal error on command:"G28"

### ISSUE THREAD

**Issue by jalanjarosz** [KevinOConnor/klipper#3267]
Changed from S-Curve back to Klipper Main and updated now that S-Curve has been merged.

Attempted to simply home printer, which has been working well for about a year on Klipper and received the Internal error on command:"G28" issue.

Re-Flashed both MEGA controllers, attempted the G28 Home command and had same issue.
[klippy.log](https://github.com/KevinOConnor/klipper/files/5146184/klippy.log)

I'm also seeing that after the Klipper failure, Octoprint seems less responsive.  While watching the screen during a reboot, there is some issues with shutting down the Octoprint service.

Octoprint has not been updated recently.  I'm using the latest build, 1.4.2 under Python 2.7 still.

**Comment by dmbutyugin** [comment]
@jalanjarosz It appears that your config has invalid values
```
[input_shaper]
shaper_freq_x = 0.0194
shaper_freq_y = 0.0141
```
Namely, it looks like the values were not updated from the old format - seconds - to the new format in Hz.

**Comment by jalanjarosz** [comment]
@dmbutyugin That was it.   Thanks!

Is there a quick reference for and adjustment to the input_shaper values, from old to new, or should I go though the print/measure process again?

(on a side note, this made me upgrade my SBC a little faster)  

Thanks!

**Comment by jalanjarosz** [comment]
Decided to re-run the ringing tests and tests are coming out really nice. 
Closing ticket as issue is resolved.
Thank you @dmbutyugin
