### ISSUE TITLE
Unable to Update Z Offset Value!

### ISSUE THREAD

**Issue by quad121** [KevinOConnor/klipper#3276]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5168811/klippy.log)

My problem is after changing the Nozzle it throw the Z-Offset out, so I made the'Tune' as it was printing the first layer and noted the figure. The nozzle is too low, I deducted this figure from the 'BLTouch' section in the 'SAVE_CONFIG' section and updated that figure. I then did a 'FIRMWARE_RESTART' Tried  to print again but no difference! I then tried performing the 'Probe_Calibrate' again and used the paper under the nozzle and adjusted the nozzle down using the 'TESTZ' commands, when i had this right i 'ACCEPT' , Then finally SAVE_CONFIG.  This still doesnt seem to save nor change the Offset. Any help would be most appreciated!

**Comment by quad121** [comment]
I have also tried changing the value of the z-offset in the 'printer' firmware folder under 'bltouch', but it doesn't have any effect.

**Comment by KevinOConnor** [comment]
The log doesn't show that SAVE_CONFIG was ever run.  You need to type that command into the OctoPrint terminal.  If you continue to have issues, issue an M112 command immediately after running SAVE_CONFIG and provide that log file.

-Kevin
