### ISSUE TITLE
Dont know why - all runs years ok now MCU is SHUTDOWN

### ISSUE THREAD

**Issue by xsasx** [KevinOConnor/klipper#3281]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5174056/klippy.log)

I have no idea whats going on with my Anet a8 - its runs now for years with klipper and trianglelab bltouch and from yesterday it brings me MCU Shutdown cause of BED - i replaced the BED but still it bring MCU shutdown.

Dont know what to do maybe you can find out in my logs

thanks

**Comment by Hywelmartin** [comment]
MCU 'mcu' shutdown: ADC out of range
