### ISSUE TITLE
endstops not triggering with skr pro 1.2 +  Lost communication 

### ISSUE THREAD

**Issue by nagamotoK** [KevinOConnor/klipper#3283]
I tried to upgrade a _sidewinder x1_ with an _skr pro 1.2_ and klipper. Due to the board change I don't have any marlin values to compare to or can even be sure that the problem is not due to bad wiring.  

At the moment the endstops wont trigger. 

I tried pullup ^, pulldown ~, inverted ! and I always get 
> Send: QUERY_ENDSTOPS
> Recv: x:open y:open z:open

even when I move the axis manually to touch the endstop. (well with inverted they are triggered but wont open)
[klippy.log](https://github.com/KevinOConnor/klipper/files/5177795/klippy.log)
**EDIT:** after leaving the printer for a few minutes alone, klipper reports 
> Recv: !! Lost communication with MCU 'mcu' 

[klippy_after_com_loss.log](https://github.com/KevinOConnor/klipper/files/5177858/klippy_after.Com.los.log)
Powersuppy for the pi 4b is the official one. The one in the printer delivers 24v, 8.5A, should be enough for idle, right? I did connect the _board power in_ and  _heat bed power in_ to the same terminal on the psu, since it only provides 2 power out and the skr pro needs 3. Heatbed is powered by AC though -- so it should not draw to much current form the board, I suppose. 

Thanks for any help! 

### Board layout:
![grafik](https://user-images.githubusercontent.com/50252002/92301846-6b5abc80-ef67-11ea-93aa-dfdc2b467637.png)
### wiring:
![grafik](https://user-images.githubusercontent.com/50252002/92301925-0489d300-ef68-11ea-80b0-0d371270e995.png)

**Comment by BlackStump** [comment]
[have you read the skr pro manual](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/SKR-PRO-V1.2/manual/SKR-PRO-V1.2-user%20manual.pdf)

Pay attention to what it says about the TMC2209

**Comment by nagamotoK** [comment]
ah thanks - I seen it but I didn't understood it at the moment. Would you use stallguard or endstops?

for the com. loss: I think this works now. I taped up the two outer usb pins in the usb type A plug, see here: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

**Comment by nagamotoK** [comment]
I bend the stall guard pin out of the way, it is not connecting or touching anything. 

Send: QUERY_ENDSTOPS gives now:

> Recv: x:TRIGGERED y:TRIGGERED z:TRIGGERED

but still moving the eg. the x axis to the endstops does not result x:open 

adding "^" to the config seems to have no effect, "!" reverses to open  but no change

**Comment by nagamotoK** [comment]
I might be on to something the mks gen l does provide 5V to the sensor and the skr pro just 3.3V. Is this the reason why the sensor does not work anymore? 

![grafik](https://user-images.githubusercontent.com/50252002/92307344-17b39780-ef96-11ea-81a1-f06357ab8f3c.png)

**Comment by nagamotoK** [comment]
ok -- this was the problem, the inductive endstops form the sidewinder require 5V, I used the first pin from extension 2 for this
