### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by ramezquitao** [KevinOConnor/klipper#329]
Is there a forum to ask questions related to klipper use and installation, that are not "issues"?.
I know this is not the best place to ask this, but I didn't found a better one.

Thanks

**Comment by theopensourcerer** [comment]
There is a an IRC channel on freenode and a group on Facebook.

**Comment by theopensourcerer** [comment]
There is also a mailing list:

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by ramezquitao** [comment]
Is the mailing list working? I haven't been able to use it.


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

**Comment by ramezquitao** [comment]
Yes it is. 

Sorry

**Comment by KevinOConnor** [comment]
The best way is via the mailing list, IRC, or a github issue.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

Cheers,
-Kevin
