### ISSUE TITLE
Klipper stops/crashes middle of print

### ISSUE THREAD

**Issue by fietstasss** [KevinOConnor/klipper#3305]
-->
Hi all,
I'm having issues with my 3d printer stopping/crashing somewhere in the middle of a print.  I've tried the same print (same gcode) for a few times and it stops -about- at the same spot every time, not exactly the same point though. 
I've also tried with OctoPrint running in safe mode and also tried with another one in safe-mode and different gcode which had lower speeds (50mm/s), all still concluded in the same behaviour as described above. 

> 

Attached you can also find my klippy log, as well the one after doing an 'extraction' [as explained here ](https://github.com/KevinOConnor/klipper/blob/master/docs/Debugging.md#extracting-information-from-the-klippylog-file)
[klippy.log](https://github.com/KevinOConnor/klipper/files/5194208/klippy.log)
[klippy_Extracted.log](https://github.com/KevinOConnor/klipper/files/5194207/klippy_Extracted.log)
[Uploading klippy.log…]()

**Comment by BlackStump** [comment]
That is way tooooo busy for my eyes. please do not copy and paste but attach as a log
where is the klippy.log

**Comment by fietstasss** [comment]
Fixed with edit, excuse me.

**Comment by KevinOConnor** [comment]
See the FAQ: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin
