### ISSUE TITLE
No Serial ID after flash, SKR mini E3 v2

### ISSUE THREAD

**Issue by paul-arnold** [KevinOConnor/klipper#3333]
Hi folks,

Board: SKR E3 mini v2
I set up make menuconfig like this:
![image](https://user-images.githubusercontent.com/7791335/93236738-77bcf180-f77f-11ea-8b64-f802ec1ac970.png)
Did a make, renamed klipper.bin to firmware.bin, put it on the SD card and powercycled the board. Firmware.cur is on the SD card, so I assume the flash was successful.
Unfortunately, I get:
![image](https://user-images.githubusercontent.com/7791335/93236955-be125080-f77f-11ea-93b6-048da3e706ae.png)

relating to this issue: https://github.com/KevinOConnor/klipper/issues/2730
I'm at pretty much the same point, issue was closed.
I also tried the commands mentioned in the opening post of that issue

lsusb gives me:
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
There is no change on dmesg output when I plug or unplug the board from the Pi

Any help is appreciated

/Edit: I had a serial id via "ls /dev/serial/by-id/*" before flashing the mcu
/Edit 2: For a test I put the original firmware back on and immediately got an ID:
![image](https://user-images.githubusercontent.com/7791335/93240158-15b2bb00-f784-11ea-8da2-46080939faf9.png)
I assume something is not right in the menuconfig. Any ideas?

/Edit 3: after a few hours I found the solution.
Reddit quote:
"The USB pullup enable signal, which the host uses to detect a USB device, moved from PC13 on v1.2 to PA14 on v2.0"
So, in make menuconfig, I set "GPIO pins to set at micro-controller startup" to !PA14.

After a new make and flashing the firmware, I finally got a serial ID:
![image](https://user-images.githubusercontent.com/7791335/93250762-92996100-f793-11ea-94f1-70be5a8f2246.png)

[klippy.log](https://github.com/KevinOConnor/klipper/files/5226332/klippy.log)

**Comment by marcosscriven** [comment]
@Roycinger - I was able to fix this with https://github.com/KevinOConnor/klipper/issues/3077#issuecomment-657142479
