### ISSUE TITLE
Display Off at Shutdown

### ISSUE THREAD

**Issue by TheRunnerPi** [KevinOConnor/klipper#3337]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5232220/klippy.log)

Hi,

is it possible to turn off the display when the printer is in standby mode? 
When I switch to standby mode via OctoPrint everything is off, only the display is still lit.

Display is a "12864" and it is hanging on a ramps.
When I switch on the printer, the display is off for a few seconds before it starts up.  So it should be possible to turn off the display in standby mode by command, right?

Maybe someone has already solved something like this and can help me.

Thanks for your help.

**Comment by KevinOConnor** [comment]
The "st7920" displays do not have the ability to turn off the backlight from software.

-Kevin

**Comment by TheRunnerPi** [comment]
Okay, thanks for the Infomation. 
Then i will go for a second relay board to cut the power off.

Regards,
Daniel

**Comment by homasholz** [comment]
is it possible on hd44780 ?
