### ISSUE TITLE
Laser Support

### ISSUE THREAD

**Issue by openbuilds-engineer** [KevinOConnor/klipper#334]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode
https://github.com/Smoothieware/Smoothieware/tree/edge/src/modules/tools/laser

Some important features that's must have
- Proportional laser (M4 mode in grbl, on by default in smoothie) scales PWM power according to acceleration to prevent darker burns during (ac/de)celleration
- G0=laseroff move, G1=laseronmove (Makes gcode generator more efficient, no need for m3/m5 on every segment / change etc
- PWM freq configurable (we found that between various diode drivers and CO2 driver, it helps to tweak pwm freq for a better linear response. CO2 PSUs seem to like a 1khz, whereas some of the chinesier diode drivers need 30khz, etc)

Also, working on adding support for LaserWeb directly (Instead export gcode -> then into Octoprint) (Not much use for laser until we have a Laser module support (; )

**Comment by KevinOConnor** [comment]
It's not clear if you are requesting that this feature be added, or are indicating that you are planning to work on it.

I don't think that, I personally, will have time to look at something like this in the next several months.

You may want to update the existing issue #133 with the items above, as that's probably a better place to track this.

**Comment by openbuilds-engineer** [comment]
Asking for feature to be added please (: 

I want to work on the frontend side of things by intergrating LaserWeb as an optional  replacement for Octoprint .  But LaserWeb needs firmware level Laser support before thats worth doing (; 

Closing this one, will follow 133.  Weirdly, it doesnt show up in a search?

![klipper no laser](https://user-images.githubusercontent.com/31449271/40072431-22381a2a-5874-11e8-88d5-b45233289c78.JPG)
