### ISSUE TITLE
Custom menu entries disappeared

### ISSUE THREAD

**Issue by Roycinger** [KevinOConnor/klipper#3367]
Hi,

After my latest git pull (around 4 days ago), I edited my menu.cfg to add some custom points.
They showed up and everything was working.

Now I just noticed that my custom menu point "Load / Unload" is no more present.
My menu.cfg:
https://pastebin.com/66Ku8NCP

Any reason why those menu point is gone?
[klippy.log](https://github.com/KevinOConnor/klipper/files/5283437/klippy.log)

**Comment by ld3300** [comment]
I'm behind myself, and will be spending the next couple of days catching up, but in [klippy/extras/display/menu.cfg](https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/display/menu.cfg) it looks like the format has changed a little.
try changing:

`!toolhead.is_printing`

to:

`{not printer.idle_timeout.state == "Printing"}`

-David

**Comment by Roycinger** [comment]
Hi David,

that's highly prossible indeed.
I expected Klipper to throw an error when using an old syntax (like it did when the menu.cfg had the "old" format).
I'll try after the running print and report back.
-Paul

**Comment by ld3300** [comment]
Hi Paul,

My guess is that Klipper sees the logic as a valid command, but it just always returns false.  So it probably can't tell there's a problem.  Please let me know if it works, I'm no pro, and appreciate opportunities to learn.

-David

**Comment by Roycinger** [comment]
I'll report back, will most likely be tomorrow after that 10hr print :)

**Comment by Roycinger** [comment]
The syntax that David mentioned worked indeed.
Thanks for pointing that out!

-Paul
