### ISSUE TITLE
SPI DAC DAC084S085 implementation

### ISSUE THREAD

**Issue by Blaster1920** [KevinOConnor/klipper#3373]
LOG FILE: [klippy.log](https://github.com/KevinOConnor/klipper/files/5286653/klippy.log)

Hi, I'm trying to communicate to my SPI DAC that controls the motor drivers's VRef on my Alligator rev.2 board.

The DAC is a DAC084S085 and here's the implementation for RepRapFirmware (RRF):
[DAC084S085 RRF.zip](https://github.com/KevinOConnor/klipper/files/5286657/DAC084S085.RRF.zip)

So far with the help of @MarcoAntonini we managed to generate the values that needs to be used to set the DAC channel and the DAC value (then translated into vref).
[dac_alligator py.txt](https://github.com/KevinOConnor/klipper/files/5286664/dac_alligator.py.txt)

Unfortunately as you can see from the .log it looks like the custom subsection shouldn't be in mcu(?)
What's would be the correct implementation for this?

Thanks in advance and congratulation for the immense work you've done so far.

**Comment by KevinOConnor** [comment]
The `custom` option was removed some time back (it was too cryptic to use or maintain).

I recommend you take a look at klippy/extras/ad5206.py - you'll want to copy that to klippy/extras/dac084S085.py and then make the changes necessary to set the 4 channels on your particular device.

-Kevin

**Comment by Blaster1920** [comment]
> The `custom` option was removed some time back (it was too cryptic to use or maintain).
> 
> I recommend you take a look at klippy/extras/ad5206.py - you'll want to copy that to klippy/extras/dac084S085.py and then make the changes necessary to set the 4 channels on your particular device.
> 
> -Kevin

Hi,
I tried to do as suggested but the SPI bus is not being set. I used a signal spoofer to check the busses but they're empty.
This is the script I've written:
[dac084S085.txt](https://github.com/KevinOConnor/klipper/files/5302091/dac084S085.txt)

And this is how it's called from the config file:
`[dac084S085 my_digipot]
enable_pin: PB14
vrefX: 125
vrefY: 125
vrefZ: 125
vrefE: 125
`
Any suggestion? With RRF I can confirm the board is functional.

**Comment by KevinOConnor** [comment]
Not sure why that would be.  I'd say double check your pins.  You can also use the console.py tool to manually issue commands for diagnostic purposes (though it's a bit of work to configure the spi connection before you can send commands on it).  https://www.klipper3d.org/Debugging.html#manually-sending-commands-to-the-micro-controller

-Kevin

**Comment by Blaster1920** [comment]
> Not sure why that would be. I'd say double check your pins. You can also use the console.py tool to manually issue commands for diagnostic purposes (though it's a bit of work to configure the spi connection before you can send commands on it). https://www.klipper3d.org/Debugging.html#manually-sending-commands-to-the-micro-controller
> 
> -Kevin

Ok, managed to fix the code, it is now working as expected and tested on the board: 
[dac084S085.txt](https://github.com/KevinOConnor/klipper/files/5343930/dac084S085.txt)

usage:
`
[dac084S085 my_digipot]
enable_pin: PB14
spi_bus : spi0
motor1 : 10
motor2 : 100
motor3 : 150
motor4 : 255
`

Is there any chance you could commit it?

**Comment by KevinOConnor** [comment]
Great.  It looks like useful functionality to me.  It would need to be submitted as a "github pull request" for me to commit - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .  FYI, I'd recommend some code changes as part of that review (eg, add copyright, time.sleep() isn't valid, add scale config parameter, add docs to config/example-extras.cfg).

Cheers,
-Kevin
