### ISSUE TITLE
Fans nonfunctional

### ISSUE THREAD

**Issue by Zwaubel** [KevinOConnor/klipper#3374]
Since 55e20f2c198ae45485d714b4588fcf6768bc6165 fans are no longer working. Neither an additional fan nor the standard extruder fan spins up automatically or via M106 command.
I might be missing something and if so I'm sorry for spamming the issues board.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5288505/klippy.log)

**Comment by ld3300** [comment]
Hi @Zwaubel,

I'm not able to reproduce the problem on my end.  Will you try a couple of things for me?  Does the hotend fan kick on if you set the hot end to 100 degrees?  Will you comment out the Hardware PWM line and see if that makes a difference?

thanks,

-David

**Comment by Zwaubel** [comment]
Hi David,

Thank you for looking into this. 
I was fiddling around with the temperature setting already. From within the normal operating range (20 C (cold) - 215 C (printing temp)) the temperature does not seem to affect the fans behavior.
I will try using SW PWM later today or tomorrow depending on my time schedule and will report back asap. 

Thanks anyway, 
Vincent.

**Comment by KevinOConnor** [comment]
There was an error in a recent merge.  I think it should be fixed now (commit 4d0d2197).

-Kevin

**Comment by Zwaubel** [comment]
Hi Kevin,

I'll check that today, when I'm back at the printer and will report back. 
Thanks for those quick adjustments. 

Vincent

**Comment by Zwaubel** [comment]
Update: both fans are working again, but strangely my [heater_fan hotendFan] won't accept hardware PWM anymore. Will crosscheck the corresponding arduino pins HW PWM support tomorrow. But I'm pretty sure I was using it in HW PWM mode before...

**Comment by Zwaubel** [comment]
I'm going to close this as the printer is working fine despite the hardware pwm issue on
