### ISSUE TITLE
installing to stm32f103zet6 (trigorilla pro board) - can't connect.

### ISSUE THREAD

**Issue by sprig** [KevinOConnor/klipper#3379]
Hi,

I'm using a trigorilla pro board which has an STM32F103ZET6 chip on it. It also has jumpers for to put the chip in bootloader mode so that one can freely flash the chip. USART1 is connected to USB via a pl2303 it appears, and I'm able to flash and run marlin 2.0.x successfully on it.

I tried building and flashing klipper. Everything appears to run smoothly, except that I can't actually connect to it. build config and log attached. I tried flashing both via the makefile as well as manually with `stm32flash`.

Pointers/help welcome.

P.S.
The lines 
```
Got error 0 in read: (0)Success
Timeout on serial connect
Unable to open port: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```
from the log file are not from cable errors or the like - they were from when I moved the jumpers back into normal operation and restarted the board.

[config.txt](https://github.com/KevinOConnor/klipper/files/5289156/config.txt)
[klippy.log](https://github.com/KevinOConnor/klipper/files/5289136/klippy.log)

**Comment by KevinOConnor** [comment]
That error indicates the host is unable to contact the micro-controller.  It generally means the board was either not successfully flashed or the settings in "make menuconfig" are not correct.

It's never been necessary for any other board, but you could try a different baud rate.  (I see references that the max for the pl2303 is 230400 baud.)  If so, make sure to change both in "make menuconfig" and in the printer.cfg file (see https://www.klipper3d.org/FAQ.html#how-do-i-change-the-serial-baud-rate ).

-Kevin
