### ISSUE TITLE
Multiple MCU "random" MCU shutdown

### ISSUE THREAD

**Issue by chainsol** [KevinOConnor/klipper#338]
## Problem
I have dual RAMPS boards driving a Railcore, with three Z steppers. To handle this, I have all three Z steppers on their own board and set up in Klipper as a second MCU. Sometimes, when homing, I get an error in the console:
```
Send: G28
Recv: !! Internal error on command:"G28"
Recv: !! Internal error on command:"G28"
```
[This is a log of one such incident - pardon the mess but I didn't format it to show off just the error.](http://paste.ubuntu.com/p/QQkg9RsB3q/) As you can see, the second MCU shuts down with an error around line 1749, `MCU 'z' shutdown: Move queue empty`.

Sometimes this happens after an e-stop, however this time, it was immediately after Klipper was restarted but not a full power cycle of the printer, e.g. the RAMPS boards were powered over USB. 

## Suggestion
It's almost unnoticeable when the second MCU shuts down. This should likely be more prominent, since a second MCU is likely to be performing some functionality essential to the printer.

**Comment by KevinOConnor** [comment]
This appears to be a bug in the homing code when multiple MCUs are used and when there is a delay in the homing_override section.  I think it should be fixed with commit 6c3db80d.
