### ISSUE TITLE
MCU 'mcu' shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by BosenSwe** [KevinOConnor/klipper#3388]
[klippy_1.log](https://github.com/KevinOConnor/klipper/files/5311586/klippy_1.log)

I have some problems and I need help to analyze my logfile.
Fault message is: **MCU 'mcu' shutdown: Rescheduled timer in the past**

What is causing it? is it the extruder?

Creality CR10s with BMG.

**Comment by KevinOConnor** [comment]
Your log file doesn't look complete (it is missing the host machine software version information).  Without a complete log there isn't much we can do.

That said, if you're not running the latest version of the code, I recommend you upgrade, as there were recent fixes in this area. (See the FAQ for upgrade instructions.)

-Kevin
