### ISSUE TITLE
MCU 'mcu' shutdown: Move queue empty

### ISSUE THREAD

**Issue by troypouliot** [KevinOConnor/klipper#3395]
Hi Kevin
I had a mcu shutdown a couple hours into a print. 

**MCU 'mcu' shutdown: Move queue empty**

This is the first time I've has this happen. I have not changed anything in quite a while. 

I read a bit on this and saw that there were some other reported cases in the past and you had suggested to change CLOCK_MONOTONIC to CLOCK_MONOTONIC_RAW per issue [#392](https://github.com/KevinOConnor/klipper/issues/392)

It looks like my firmware version is recent enough where you already implemented this fix. Can you tell what happened?
[klippy log.zip](https://github.com/KevinOConnor/klipper/files/5323159/klippy.log.zip)

**Comment by KevinOConnor** [comment]
That error indicates the host clock tracking got out of sync with the micro-controller clock.  I'm not sure why that occurred.  There were several important fixes in the last few months though - I recommend you upgrade to the latest code.

-Kevin
