### ISSUE TITLE
Failed to home probe: Timeout during homing

### ISSUE THREAD

**Issue by hn0550** [KevinOConnor/klipper#3403]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5333467/klippy.log)
I use an infrared sensor, which often prompts this error
thank you

**Comment by jakep82** [comment]
An incorrect step_distance can cause this error.  You've indicated in your other issue that you needed to change that value to half of what is shown on this log.  This error should be solved by fixing your step_distance, or changing the microstep setting on your drivers to match this step_distance.
