### ISSUE TITLE
Request adding support for RGBW NeoPixels

### ISSUE THREAD

**Issue by alatdneg** [KevinOConnor/klipper#3410]
Just wired these into my printer, and have now realised they don't appear to be support..

Can we get them added, please ?

**Comment by alatdneg** [comment]
Looks like the current code almost works, as the LED's light up, it's just that they expect 4 components not 3. Setting to white works (you need to increase led_chain by 1/3), but any other colour obviously will not.

**Comment by KevinOConnor** [comment]
I attempted to update the neopixel code in PR #3380 with RGBW support.  I don't have this hardware, so I don't know if it will work.  If you test it, let me know the results (success or failure).

-Kevin
