### ISSUE TITLE
Heater extruder not heating at expected rate - too sensitive?

### ISSUE THREAD

**Issue by nocjef** [KevinOConnor/klipper#3413]
Got an interesting issue with, "Heater extruder not heating at expected rate"
trying to run a PID tune (PID_CALIBRATE HEATER=extruder TARGET=230)
was getting shutdowns
Watched the kliipy.log during PID tune, it heats up and hits 230, requests to heat to 225 and hits that ok, then 230 again but the temp is still dropping
The heater catches up and starts heating but only gets a few readings in before I get the error
I get about 22 polls before the shutdown. The heater is heating back up starting about poll 15 but the temp has dropped to 215.6 at that point

klippy.log attached.
[klippy.log.gz](https://github.com/KevinOConnor/klipper/files/5357918/klippy.log.gz)

**Comment by KevinOConnor** [comment]
```
Heater extruder not heating at expected rate
Transition to shutdown state: Heater extruder not heating at expected rate
See the 'verify_heater' section in config/example-extras.cfg
for the parameters that control this check.
```

As indicated in the error, it may be necessary to tune the verify_heater section for your heater.  (It may also be possible that your heater is not capable of reliably reaching the desired temperature.)

-Kevin
