### ISSUE TITLE
Wrong position_max for stepper_z in printer-creality-cr10s-2017.cfg 

### ISSUE THREAD

**Issue by nic-str** [KevinOConnor/klipper#342]
I've noticed that the position_max for stepper_z in the CR-10s config is wrong.

It should be 400 instead of 200, because the build volume is 300x300x400mm.

**Comment by KevinOConnor** [comment]
It does look wrong.  I don't have the hardware though.  If you (or someone else) has the CR-10s and can confirm that the config can changed and the printer can be safely commanded to a position of Z400 without a frame collision, then I'll update the config.

@cymen / @jm493 - do you have any comments on this?

**Comment by nic-str** [comment]
I have the CR-10s and i can confirm that the printer can safely go to z400. It's technically the same printer as the "normal" CR-10, only with a dual lead screw design. In the config of the CR-10 (printer-creality-cr10-2017.cfg ) the position_max is also 400.

**Comment by KevinOConnor** [comment]
Thanks.  Commit 3505a072.

-Kevin
