### ISSUE TITLE
Ender 3 SKR Mini E3 | MCU 'mcu' shutdown: ADC out of range

### ISSUE THREAD

**Issue by cobramike** [KevinOConnor/klipper#3426]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5380317/klippy.log)

When i start my printer its shuting down. Yesterday it was working. And today i was trying to start calibriting Extruder.

MCU 'mcu' shutdown: ADC out of range
This generally occurs when a heater temperature exceeds
its configured min_temp or max_temp.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
Klipper state: Not ready

**Comment by Roycinger** [comment]
Check / measure if one of your thermistors went bad.
ADC out of range usually indicates that Klipper can't read a value

**Comment by cobramike** [comment]
Its working correctly. When i change back to marlin its working like a charm
