### ISSUE TITLE
Klipper display config

### ISSUE THREAD

**Issue by th3fallen** [KevinOConnor/klipper#3430]
Per the documentation here https://github.com/th3dstudio/UnifiedFirmware/blob/2.0.x/Firmware/Marlin/src/pins/lpc1769/pins_TH3D_EZBOARD.h#L173

There are no d5,d6,d7 pins so I'm at a loss as to how to map this to a config to make this work any suggestions would be greatly appreciated. this is the LCD in use https://www.th3dstudio.com/product/12864-lcd-display-w-cables-sd-slot-mks-ramps-boards/

[klippy.log](https://github.com/KevinOConnor/klipper/files/5385233/klippy.log)

**Comment by Hywelmartin** [comment]
isn't that display the #[ "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays](https://github.com/KevinOConnor/klipper/blob/cf6d302ac3979aec2d55a166fe5446c46c2765ef/config/sample-lcd.cfg#L13)

you need to make(or [buy](https://www.th3dstudio.com/product/ezboard-creality-dual-lcd-adapter-board/)) an adapter that routes all signals needed to EXP1 
Or buy another [display](https://www.amazon.co.uk/creality-Tickas-Printer-Replacement-Creality/dp/B08FHX7MRT)

**Comment by th3fallen** [comment]
I have that adapter already installed

**Comment by Hywelmartin** [comment]
As THC3 doesn't believe in open source hardware, you have to use a multimeter to see how all things is routed..

Plugs on normal boards
![image](https://user-images.githubusercontent.com/33714214/96367424-0e4d4b80-114e-11eb-98ff-41b8bf46adea.png)
.
.
.
.
.
Plug on your board
![image](https://user-images.githubusercontent.com/33714214/96367446-2d4bdd80-114e-11eb-9eef-dc25dfe69f40.png)
