### ISSUE TITLE
Can't connect Ender3 V2

### ISSUE THREAD

**Issue by yo3gts** [KevinOConnor/klipper#3443]
Hi, I did everything by the book ... and yet there's something wrong, I can't connect
I have attached the log

[klippy.log](https://github.com/KevinOConnor/klipper/files/5397710/klippy.log)

**Comment by BlackStump** [comment]
To me it looks like you have configured the mcu for a BTT Mini E3 V1.2 is that what you have? if you have a standard Ender3 V2 then you should follow the info on that config [here](https://github.com/KevinOConnor/klipper/blob/master/config/printer-creality-ender3-v2-2020.cfg)

**Comment by yo3gts** [comment]
Thank you for the help!
I used this configuration to which I added BL-touch, I also tried display ...
A stupid question ... when I put the klipper.bin firmware on the card and turn on the printer, does it completely replace the marlin firmware and the display is blank? Does the printer only use the clipper firmware?

**Comment by jerkwagon** [comment]
@yo3gts did you get this resolved i have the 4.2.7 board as well and im having severe issues. 

as far as i know the screen will go blank unti you plug it in the pie.
