### ISSUE TITLE
Rename E-Stop macro to Emergency-Stop

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [KevinOConnor/klipper#3452]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5415464/klippy.log)
The meaning of E-Stop is not obvious. E-Stop could mean end-stop or emergency stop. Rename to Emergency stop.

**Comment by KevinOConnor** [comment]
Klipper does not have an "E-Stop" command.  I don't understand what is being reported here.

-Kevin

**Comment by ProfEngr** [comment]
Maybe it's something already configured in Mainsail or Octoprint's Octoklipper plugin?
