### ISSUE TITLE
X motor does not work good

### ISSUE THREAD

**Issue by theodore0310** [KevinOConnor/klipper#3458]
Hi, after about 30h of printing the x motor started to moves jerking, shake everything and doing a lot of noise. It works as a lot of step which slow down after each one. The movement end with homing timeout. This is my feeling, please help me. If the log file is not right, let me know. thanks

**Comment by theodore0310** [comment]
[serial.log](https://github.com/KevinOConnor/klipper/files/5421436/serial.log)

**Comment by Roycinger** [comment]
We would need a klippy.log at least. You can find it in the /tmp folder of your Pi.
See here: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by theodore0310** [comment]
[Uploading klippy.log…]()

**Comment by theodore0310** [comment]
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/5428071/klippy.log.zip)
is the same file but compressed

**Comment by theodore0310** [comment]
I have an Artillery sidewinder X1 with this profile: https://github.com/Clank50AE/Clanks-Klipper-Configs/blob/master/SideWinder%20X1%20Stock.cfg

**Comment by theodore0310** [comment]
the issue was caused by a faulty cable
