### ISSUE TITLE
Has anyone attempted firmware install on an XYZ Da Vinci 1.1plus Atmel board?

### ISSUE THREAD

**Issue by basktrading** [KevinOConnor/klipper#346]
I have an XYZ Da Vinci 1.1plus running on stock 1.1M firmware. After an exhaustive search, I presently know of no other viable alternative firmware for this printer.

The stock processor is an Atmel ATSAM3X8E ARM processor with PCB soldered DRV8825 stepper drivers.

Has anyone attempted flashing this type of chip configuration with Klipper? I am very interested in pursuing this approach, and at my wits end with the XYZ firmware limitations. However, the printer is still up and and running for now, so I wanted to check if anyone has experimented with a similar implementation.

**Comment by KevinOConnor** [comment]
I don't have any experience with that board, and it would appear no one else here does as well.  If you can get access to a schematic and know how to upload flash to the board, then you could try to put together a config file for it.
