### ISSUE TITLE
Choice 'item' for option 'type' is not a valid choice

### ISSUE THREAD

**Issue by BobaSchmidt76** [KevinOConnor/klipper#3470]
Hi,
after updating Klipper I get this message "Choice 'item' for option 'type' is not a valid choice"

What went wrong?

Regards
Marko

[klippy.log](https://github.com/KevinOConnor/klipper/files/5434524/klippy.log)

**Comment by BlackStump** [comment]
[did you check the config changes doc](https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Changes.md)

>20200809: The menu system has been rewritten. If the menu has been customized then it will be necessary to update to the new configuration. See config/example-menu.cfg for configuration details and see klippy/extras/display/menu.cfg for examples.

**Comment by BobaSchmidt76** [comment]
In the changes Log is nothing abot the Menu.
I´ve got Mesh Leveling editet months ago. But if I delete the Bed Mesh leveling comes "Option 'set_velocity_limit square_corner_velocity' is not valid in section 'printer'"

**Comment by theopensourcerer** [comment]
@BobaSchmidt76 It says exactly that... "20200809: The menu system has been rewritten. " 

See the example-menu.cfg and you will see there is no type called "item"

https://github.com/KevinOConnor/klipper/blob/master/config/example-menu.cfg#L21

**Comment by BlackStump** [comment]
This is not a valid entry in your printer.cfg
>set_velocity_limit square_corner_velocity: 3.5

**Comment by BobaSchmidt76** [comment]
I´ve updated the Menu.cfg and the Display.cfg. But still the same error. Sorry my English is not so good.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5434623/klippy.log)

**Comment by theopensourcerer** [comment]
```
[menu __prepare meshBed zposition]
type = item
```

There is no type called "item".

**Comment by BobaSchmidt76** [comment]
What should stand there instead?

**Comment by BobaSchmidt76** [comment]
I reinstall klipper.
