### ISSUE TITLE
Failing to detect BLTouch trigger during mesh calibration

### ISSUE THREAD

**Issue by MattArceri** [KevinOConnor/klipper#3481]
I recently set up Klipper on my Sidewinder X1. Outside of adding a BLTouch from TriangleLabs and swapping the leadscrews to ones with half the lead, the printer is 100% stock. I immediately had major issues running mesh_calibration. I can probe seemingly any spot on the bed and run probe_accuracy for dozens of samples and I have no issues at all. Once I run mesh_calibration it will almost always fail partway through by crashing into the bed and stopping due to a timeout. Originally I was running Klipper V0.8 but now I'm on V0.9 and the issue still occurs. Although I do occasionally observe it on other points, it seems to largely occur on the far left point of the second row of test points. Probing just that point on its own seems to have no issues. I have run it as slowly as 1mm/s with no noticeable improvement. I've found no apparent cable issues and I've never needed to do anything to start probing again.

Using my phone's camera in slow motion, judging from the LED on the BLTouch it appears to trigger exactly the same as any other point. I'm not quite to the point of haphazardly mounting my printer on something with the base off so I can hook up a scope to the PCB but could if it was needed to absolutely rule out anything strange with the wiring. It's unfortunately just not an easy printer to do that to.

Right now I'm thinking that something may be causing the BLTouch signal to just not be detected by Klipper but I'm open to investigating anything if someone has test suggestions.
 
Log attached
[klippy.log](https://github.com/KevinOConnor/klipper/files/5455583/klippy.log)

**Comment by KevinOConnor** [comment]
Alas, the best advice we have on the BL-Touch is at https://www.klipper3d.org/BLTouch.html .  If you're getting random failures at a certain point on the bed, it may be a loose wire being pulled when the toolhead/bed moves.

-Kevin
