### ISSUE TITLE
neopixel_update command not found

### ISSUE THREAD

**Issue by pheonix3330** [KevinOConnor/klipper#3484]
I updated to the latest klipper firmware and also updated the mcu firmware just in case. I made the color_order change listed in the klipper config changes but I am still getting an error when trying to boot. "command not found: neopixel_update". The only way I can get klipper to start is by commenting out the neopixel lines.

Here is what the neopixel section looks like in my config:
[neopixel fysetc_mini12864]
pin: P1.21
chain_count: 3
initial_RED: 1.0
initial_GREEN: 0.0
initial_BLUE: 0.0
color_order: RGB

Any ideas what could be happening? This is the error in the klippy.log:

Protocol error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 151, in _connect
    cb()
  File "/home/pi/klipper/klippy/mcu.py", line 571, in _connect
    self._send_config(None)
  File "/home/pi/klipper/klippy/mcu.py", line 510, in _send_config
    cb()
  File "/home/pi/klipper/klippy/extras/neopixel.py", line 57, in build_config
    "neopixel_update oid=%c pos=%hu data=%*s", cq=cmd_queue)
  File "/home/pi/klipper/klippy/mcu.py", line 667, in lookup_command
    return CommandWrapper(self._serial, msgformat, cq)
  File "/home/pi/klipper/klippy/mcu.py", line 384, in __init__
    self._cmd = serial.get_msgparser().lookup_command(msgformat)
  File "/home/pi/klipper/klippy/msgproto.py", line 300, in lookup_command
    raise error("Unknown command: %s" % (msgname,))
error: Unknown command: neopixel_update
Build file /home/pi/klipper/klippy/../.config(1067): Tue Oct 27 16:29:35 2020
[klippy.log](https://github.com/KevinOConnor/klipper/files/5465979/klippy.log)

**Comment by KevinOConnor** [comment]
When upgrading the software, please be sure to always follow the directions in the FAQ: https://www.klipper3d.org/FAQ.html#how-do-i-upgrade-to-the-latest-software

In particular, you will sometimes need to reflash the firmware.

-Kevin

**Comment by pheonix3330** [comment]
Thanks Kevin, I thought I had reflashed the mcu but I realize now I forgot to rename the klippy.bin file to firmware.bin before loading it onto the sd card for my skr 1.4. Thanks for the response.
