### ISSUE TITLE
Quad Gantry Leveling is not accurate

### ISSUE THREAD

**Issue by ymanyin** [KevinOConnor/klipper#3504]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5486951/klippy.log)

Expected result:
After QGL, 4 corners should be leveled within the desired tolerance.

Actual result:
There is a 1mm difference between Z/Z3 and Z1/Z2.
Z/Z1 are leveled so as Z2/Z3 within tolerance.
The problem occurs in X axis not Y axis.
However, the system shows the measurement are all under 0.0075tolerance.
1mm is the actual difference.

The 1mm difference can always be recreated precisely after I hand move all axis to simulate the situation.
Could it be a wrong calculation? I am not saying this is a program problem.
I just want to get some help and solve the problem. Thanks in advance!
Please let me know if this is a mechanical problem and how can I correct it?
I do have a video on Youtube for the issue. https://youtu.be/kS1Zv6krtrg
I used a gauge to measure the bed after doing a QGL.

The printer is Voron 2.4. I made it a a bed sized 550mm square.
The problem do exist on my other Voron 2.4 250mm. But the difference is only 0.1mm on this printer.
It seems like the difference get bigger when the bed size is larger.

**Comment by KevinOConnor** [comment]
Alas, this isn't a good location for general support questions.  You're probably better off asking your question in a Voron forum.

-Kevin
