### ISSUE TITLE
New kinematics for Klipper

### ISSUE THREAD

**Issue by Ilnur3D** [KevinOConnor/klipper#3507]
Hello dear developers of the Klipper firmware. Sorry for the translation, I don't know much English.
I have the following appeal to you. My friend and I came up with the idea of creating a printer with a new kinematic scheme for working in the XY plane. The closest analogue of our kinematics is MASLOW CNC.
I can say a beginner in programming, but I tried to create my own kinematics based on your firmware. In this regard, I want to ask you to look at the files that I dropped and check. I created the code for the kinematics based on the code for the coreXY and polar kinematics. I also wanted to ask you to add kin-ematics to your main firmware.
Attached to my request are files explaining the operation of the kinematics, the files that I changed and created, as well as the entire firmware file.
The file can be downloaded from the following link: https://yadi.sk/d/PViNndohXvfAdQ
Thanks for attention. I look forward to hearing from you.

Sincerely, Ilnur Akhmetkhanov!
axmetxahob2@yandex.ru
![1](https://user-images.githubusercontent.com/73010989/98196074-0874aa00-1f45-11eb-8e23-dd0e2fea4ce8.jpg)
[klippy.log](https://github.com/KevinOConnor/klipper/files/5491895/klippy.log)
[описание кинематики.pdf](https://github.com/KevinOConnor/klipper/files/5491896/default.pdf)

**Comment by KevinOConnor** [comment]
Okay, thanks.  If you'd like to submit code for inclusion into Klipper you will need to open a github pull request and follow the directions at: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Keivn
