### ISSUE TITLE
layer shift issues delta printer

### ISSUE THREAD

**Issue by goosst** [KevinOConnor/klipper#3524]
Dear Klippers,

I have a delta printer which seems to experience layer shifts, the weird thing is they only start after hours of printing (like 4-5 hours into the print). This is happening practically in every longer print.

Since I find it strange, printer-hardware issues would occur so late in the print, I'm wondering if:
1. Something in the log files / firmware of klipper can help me debug this issue?
2. Other klipper users experience similar behaviour on delta printers

![IMG-20201112-WA0000](https://user-images.githubusercontent.com/8907127/98964173-caf5bb00-2508-11eb-98b1-c5b9f640a188.jpeg)
![IMG_20201112_165341019](https://user-images.githubusercontent.com/8907127/98964179-ccbf7e80-2508-11eb-8032-f63712eab1a3.jpg)
![IMG_20201112_165402154](https://user-images.githubusercontent.com/8907127/98964185-ce894200-2508-11eb-96b7-8f1a23ad0d2e.jpg)

[klippy.log](https://github.com/KevinOConnor/klipper/files/5531729/klippy.log)

**Comment by goosst** [comment]
or to make it a bit more concrete, is there anything in klipper that helps monitoring any of the temperatures of the (stepper)motor (extruder, actuation, ... ) or controllerboard ?

thanks!

**Comment by Hywelmartin** [comment]
https://github.com/KevinOConnor/klipper/blob/bdaca327072598452c14aa6716fa292446cc8086/config/example-extras.cfg#L1179

**Comment by goosst** [comment]
I do understand how to hook up external temp sensor, I was mainly wondering if there were temperatures available from internal components like from common controlboards etc.
