### ISSUE TITLE
endstop_phase: fix error handling in case endstop accuracy is insufficient

### ISSUE THREAD

**Issue by bromor** [KevinOConnor/klipper#3531]
Hello,

I have faced an unhandled exception in `enstop_phase` module.

Steps to reproduce: 
- In `[endstop_phase]` config section, set `endstop_accuracy` to a value bigger than phases*step_distance
- Start klippy

Result:
klippy enters the following line with `config` undefined:
https://github.com/KevinOConnor/klipper/blob/bdaca327072598452c14aa6716fa292446cc8086/klippy/extras/endstop_phase.py#L61
The line should read like `raise self.printer.config_error(...`

[klippy.log](https://github.com/KevinOConnor/klipper/files/5541328/klippy.log)

**Comment by KevinOConnor** [comment]
This issue was fixed back in commit 96eba9f2.

-Kevin

**Comment by bromor** [comment]
Thanks!
