### ISSUE TITLE
Loses connection to MCU at G28 Z

### ISSUE THREAD

**Issue by PerLangkjaer** [KevinOConnor/klipper#3537]
After installing a second Z stepper i get this error a G28 or G28 Z when moving the Z axis
I have testet with 1/16 microstepping as well and its the  same

[klippy.log](https://github.com/KevinOConnor/klipper/files/5543084/klippy.log)

**Comment by jakep82** [comment]
You've configured a probe as your endstop for stepper_z, and a regular endstop pin for stepper_z1.  I don't believe that's a valid combination.  You need to remove the endstop from your stepper_z1 section if you want to use a probe as your Z endstop.
