### ISSUE TITLE
Unstable mcu frequency with atmega2560 and ramp 1.4

### ISSUE THREAD

**Issue by RichardBsolut** [KevinOConnor/klipper#354]
I get random "Lost communication with MCU" and "Timer too close" error messages when trying to print something. While searching the logs I noticed that the mcu freq is constantly slowing down.
That's why I only plotted the frequency.

![test](https://user-images.githubusercontent.com/1217900/40390583-08cea8cc-5e16-11e8-9506-33a27e1fe975.png)

First, only usb is connected. red line usb disconnected and immediately reconnected. green line powered the 12v rail at the ramps board (draws ~20mA).

Could this be the reason for my problem with the "Lost communication with MCU" / "Timer too close"?
Any advice on how to get around it. Or anything else I can test?

[log.file.log](https://github.com/KevinOConnor/klipper/files/2028602/log.file.log)

**Comment by cmock** [comment]
For reference: I have data from my raspberry pi GPS NTP servers, where the clock varies by about 6ppm over the course of a year (due to the temperature variations in an unheated room). 

Your clock drifts by more than 180 ppm over some hours -- to me, that indicates that the crystal on your MCU is pretty crappy.

I assume the drift is mainly due to temperature rise, where the sharp rise at the green event would be due to the added heat from the 5V regulator (which is near to the crystal on an Arduino Mega, if that is what you're using).

I'd suggest changing your Mega board (or the crystal if you're OK with soldering); as a workaround, pointing a fan in between the sandwitched boards from the USB connector side should cool things down, and maybe having the printer turned on for 2 or 3 hours before trying to print to get to a thermal equilibrium could also help.

**Comment by StefanMeGit** [comment]
How did u plot the connection? Is there any tutorial?

**Comment by herrwusel** [comment]
@StefanMeGit: check [here](https://github.com/KevinOConnor/klipper/blob/master/docs/Debugging.md#generating-load-graphs)

**Comment by RichardBsolut** [comment]
My question is more does klipper need such a stabile frequency to work? The plot above shows a ~1khz (1 ms) difference over 1 1/2 hour. Or may there is something else i need to look for.

@cmock iam pretty sure its an crappy crystal. its the cheapest arduino mega board i could find from china. But i like the fan idea, i'm going to do another plot with fan tonight.

**Comment by KevinOConnor** [comment]
On Wed, May 23, 2018 at 03:49:31AM -0700, RichardBsolut wrote:
> My question is more does klipper need such a stabile frequency to work? The plot above shows a ~1khz (1 ms) difference over 1 1/2 hour. Or may there is something else i need to look for.

Klipper does require a stable frequency, but the drift you are
reporting should not be an issue for the Klipper software directly.
(Klipper recalculates the drift roughly every second, so it should
just accomodate a slowly drifting clock like you are seeing.)  Even if
the clocks drifted too much for the Klipper software, it would not
result in the error messages you reported earlier.

The "Lost communication with MCU" and "Timer too close" errors are
indicative of severe USB communication failures.  It's possible that
power fluctuations, heat fluctuations, and/or clock fluctuations could
impact the arduino's USB chip to the point it fails.  Another common
culprit is heavy electrical noise.

-Kevin

**Comment by RichardBsolut** [comment]
Ok here the plot with fan as cmok described it.
![test](https://user-images.githubusercontent.com/1217900/40452010-be14b4b8-5ee0-11e8-9848-b6e6d5c5093a.png)
Red line: powered the 12v rail  Green line: power on the fan.


For the "Lost communication with MCU" and "Timer too close" errors. Tomorrow i use an trustworthy usb-serial connector to exclude any fails on the usb chip mounted on the arduino board. Heavy electrical noise, is hard to measure (at least for me) lets hope its not the case.


[log.file.log](https://github.com/KevinOConnor/klipper/files/2032935/log.file.log)

**Comment by RichardBsolut** [comment]
Hi @KevinOConnor , please close the ticket.
I still have the "Lost communication with MCU" and "Timer too close" errors even with an external usb-serial chip. But it certainly has nothing to do with the unstable frequency.

**Comment by hg42** [comment]
with USB I often find bad cables as a reason for failing communication.

Many USB applications just retry a packet if they fail. But there are applications with real time demands that cannot retry, like high speed sound and video streaming or Klipper.

So bad cables that work in office can still fail for Klipper. I tend to use my cables from external hard disks for such applications. They are usually of better quality. ALso older cables seem to be less cheap. I throw away failing cables.

**Comment by cmock** [comment]
@KevinOConnor , I think for cases like this it would be nice to have a "ping" tool, that just sends a packet to the MCU that is then echoed, and runs for a set amount of time and then spits out statistics, just like ping does. That could help finding USB timing/stability issues...

**Comment by hg42** [comment]
Klipper is already "pinging", see the Stats lines in the log.
This includes rtt (round trip time) and counts of transmission errors etc.
Do you think of something else?

**Comment by KevinOConnor** [comment]
On Fri, May 25, 2018 at 12:36:39AM -0700, RichardBsolut wrote:
> Hi @KevinOConnor , please close the ticket.

Hi,

FYI, since you opened the ticket, you should be able to close it as
well.

> I still have the "Lost communication with MCU" and "Timer too close" errors even with an external usb-serial chip. But it certainly has nothing to do with the unstable frequency.

It's always possible it is something else - though it does sound like
a communication issue.  If you can post the Klipper log file of an
error (when running an unmodified version of klipper), we can take a
look.

Otherwise, as Harald mentioned, you might want to verify the usb plug
and cables are all in a good state.

-Kevin

**Comment by KevinOConnor** [comment]
On Fri, May 25, 2018 at 03:20:43AM -0700, christian mock wrote:
> @KevinOConnor , I think for cases like this it would be nice to have a "ping" tool, that just sends a packet to the MCU that is then echoed, and runs for a set amount of time and then spits out statistics, just like ping does. That could help finding USB timing/stability issues...

As Harald indicates, Klipper is always doing this.  Both the low level
code and the clock synchronization code are analyzing latency, jitter,
etc.  It's possible we could report more in the logs, but there is
already a lot of info there.

Also, it's worth pointing out that the errors cited in this issue
(lost communication with mcu, timer too close) are severe errors.  The
comms would have to be cut for 5+ seconds for a "lost communication
with mcu" error, and a "timer too close" would be many retransmit
rounds over a couple hundred milliseconds.  Neither of these are
symptomatic of sporadic errors.

-Kevin

**Comment by KevinOConnor** [comment]
On Fri, May 25, 2018 at 01:57:12AM -0700, Harald wrote:
> with USB I often find bad cables as a reason for failing communication.
> 
> Many USB applications just retry a packet if they fail. But there are applications with real time demands that cannot retry, like high speed sound and video streaming or Klipper.

Although it is true that Klipper has some hard timing requirements, I
would point out that Klipper isn't very demanding.  It typically
transfers no more than around 5KB/s and is typically tolerant up to
around 100ms of jitter.

-Kevin

**Comment by hg42** [comment]
> Although it is true that Klipper has some hard timing requirements, I would point out that Klipper isn't very demanding

yes, sorry, I only wanted to say, that it can't work with delays I sometimes see with bad cables (more like seconds), while non-real time applications can wait very long, sometimes in the range of minutes. I sometimes have this with usb storage devices. So, whenever a copy operation takes too long, check the cable :-)

Though I don't have such problems with klipper using a mid-quality 5m cable from the host (Linux PC) to a cheap 10-port hub and good 1.5m cables from the hub to the MCUs. The MCUs are an old original Arduino Mega 2560 or the cheap Tronxy 8bit board.

However, when I started to use klipper, I had one bad (cheap, new, untested) cable that resulted in shutdowns. First thing I do on communication failures is changing cables (if the cables are not proven as 100% working).

**Comment by RichardBsolut** [comment]
I tested @hg42 "the cable is shit" these even if it's a little embarrassing, he's right. Other cable all fine. 

It is exactly as described by  @KevinOConnor .
"Time to close" comes through "set_pwm_out", which sometimes ends up in retransmit and suddenly arrives somehow after all. In all other cases "lost communication with mcu" comes along. 
Since the retransmit occurs at different times (at heating / in the middle of an print), the behavior looks totally random and sporadic. 

Must be that electrical noise thing.

Finally, sorry for the miss leading issue.
