### ISSUE TITLE
Ender 3 + SKR Mini E3 V2 - Printer Not Ready

### ISSUE THREAD

**Issue by casterle** [KevinOConnor/klipper#3544]
I thought I'd give klipper a try on my Ender 3/SKR Mini E3 V2 combo. I've run into a 'Printer Not Ready' issue that I suspect is related to the serial connection.

The instructions refer to a folder /dev/serial but I have no such folder (latest OctoPi + OctoPrint). I have a non-folder called 'serial1', which I am trying to use. 

The attached log file has 2 runs (service start/stop), the first using the default serial setting and the second using /dev/serial1. The errors change from 'unable to open port' to timeouts.

I'm not sure why I don't have a /dev/serial, or if that's the problem. Suggestions?

[klippy.log](https://github.com/KevinOConnor/klipper/files/5550135/klippy.log)

**Comment by Feche** [comment]
make menuconfig
- Use USB for communication

Then, under USB ids check 'USB serial number from CHIPID'
