### ISSUE TITLE
Hang up during print. Klippy.log not written

### ISSUE THREAD

**Issue by cmoeg** [KevinOConnor/klipper#355]
![photo_2018-05-24_00-06-04](https://user-images.githubusercontent.com/29042251/40454371-e7938c80-5ee8-11e8-969e-1030ce320777.jpg)
During printing a model the second time Klipper hung up during print (already 75% done).
Octoprint does not boot anymore and is not accesable via network.
![image](https://user-images.githubusercontent.com/29042251/40453736-79add3b2-5ee6-11e8-9ac4-afdf430d23ce.png)
[octoprint.log](https://github.com/KevinOConnor/klipper/files/2033079/octoprint.log)

**Comment by cmock** [comment]
That's a linux system that's booted into emergency mode, which usually is due to some severe disk problem.

Given the experiences I've had with SD cards on my raspberrys over the years, the first thing i'd try is to use a new SD card...

**Comment by cmoeg** [comment]
ok will try the third sd-card,...
