### ISSUE TITLE
cant move tool after canceling print

### ISSUE THREAD

**Issue by derdigge** [KevinOConnor/klipper#359]
Deak all

I am facing a strange issue. If iam canceling a print, Z is at +15mm.
Now i want to lift the Zool to +40mm to remove the bad print.

The terminal says allays:
Send: G1 Z50
Recv: !! Must home axis first: 185.246 166.866 50.000 [1151.887]

I do not think that this is a planned behavior? Homing Z in this situation will be a verry bad idea.

So what i am doing wrong?

BR
derdigge

**Comment by derdigge** [comment]
Thanks for your reply.

But how others are canceling? I am the onlyone ever canceled a print?

;)

**Comment by oderwat** [comment]
Well.. see https://github.com/KevinOConnor/klipper/issues/335

**Comment by derdigge** [comment]
@oderwat 

Thanks. This works now.
