### ISSUE TITLE
Unable to open config file /home/pi/printer.cfg

### ISSUE THREAD

**Issue by liveblood** [KevinOConnor/klipper#3590]
Hi 
Here is a screen shot :- https://paste.pics/d22ef2977659f0a37c2ca36468a6dcbe
Unable to open config file /home/pi/printer.cfg
[klippy.log](https://github.com/KevinOConnor/klipper/files/5613210/klippy.log)

Hope you can help

Thanks
Martin

**Comment by jakep82** [comment]
Did you go all the way through the installation document?  Specifically, did you copy one of the sample configs into your /home/pi directory as stated in the section linked below?

https://www.klipper3d.org/Installation.html#configuring-klipper
