### ISSUE TITLE
new menu implementation : lost functionnalities ? or undocumented syntax change ?

### ISSUE THREAD

**Issue by aschor** [KevinOConnor/klipper#3601]
Hi,

So I'm trying to get up to date and I'm hurting several walls updating my configuration on the "new" menu syntax. here are the steps I'm truggling with. I understand the need to symplify the code and have only one syntax, but a lot of things are not doable anymore, OR there is no documentation on how to do it, and that quite unfortunate. 

0) [Config_Changes.md](../blob/master/docs/Config_Changes.md) tells us that "The menu system has been rewritten. If the menu has been customized then it will be necessary to update to the new configuration. See config/example-menu.cfg for configuration details"  => okay, but that "example-menu.cfg" has been removed too....

1) 'Items is no more allowed ( to list menu items)' : so 'before', we could build a menu (item or list), and we could insert this SAME menu under various leafs of the menu tree. For exemple : extruder temperature in "prepare", and also in "filament change". But now that, to my understanding, we only one syntax left for menus and in this syntax me MUST inlude all parents from the actual entry, we cannot share a menu anymore. Am I right ? Or is there a way ?  why do I want to do that, because I don't want to write the same code twice. e.g. :
```
[menu __main __filament]
type: list
name: Filament  
items:  
    __temp __hotend0_current, __temp __hotend0_target
    .__feed
    .__change
    .__unload
    .__preload
    .__load
    .__loadresume
    .__resume
```

2) because of that syntax, we cannot override anymore a full default menu, we have to either redefine all the children with 'enabled: False' or redefine the whole main menu. Am I right ?

~~3) something that is no more allowed (but why ?) : 'input_step2' to define the steps when turning encoder wheel fast. I'm reaaaally missing this one on my custom menu bltouch / testZ  (input_step: 0.01 / input_step2: 0.1 ). Same for extruder temp target (input_step: 1 / input_step2: 10) is there another way, another syntax please ?~~
==> edit : it is automatic and no more editable :
input_step:
   Editing step - Must be a positive integer or float value. It has
   internal fast rate step. When "(input_max - input_min) /
   input_step > 100" then fast rate step is 10 * input_step else fast
   rate step is same input_step.

~~4) menu's ACTION element is no more allowed : so how do we tell the menu that we want to go back or exit to home screen on click ? I did not find. Is there a way now ?~~
==> !! this one is solved, I found it (but the doc is unclear, and there is NO example using it) : 
in the [ menu xxxx ]  "simply" under gcode element :
```
[ menu __main __donothing]
type : command
name: donothing
gcode:
   RESPOND MSG=doing nothing
   { menu.exit() }
```
5) 'transform' menu element is not allowed anymore. So before I had this uggly entry, how can I handle that with the jinja2 syntax ? Is that possible ? I don't get how to 
~~[menu RelaysLeds]
type: input
name: LEDSs {1:3s}
parameter: 0
input_min: 0
input_max: 1
input_step: 1
transform:
    choose('Off','On')
gcode: 
    RESPOND TYPE=command MSG=action:relaisLeds{1}
action:
    back~~

works with that :
```
[gcode_macro relayleds]
variable_ledsstatus: 0
gcode: 
    {% if VALUE is defined %}        
        {% if VALUE|float == 1 %}
            SET_GCODE_VARIABLE MACRO=relayleds VARIABLE=ledsstatus VALUE=1
            RESPOND TYPE=command MSG=action:relaisLedsOn
        {% else %}
            SET_GCODE_VARIABLE MACRO=relayleds VARIABLE=ledsstatus VALUE=0
            RESPOND TYPE=command MSG=action:relaisLedsOff
        {% endif %}
    {% else %}
        RESPOND MSG="LEDs are : { 'On' if ledsstatus else 'Off'}"
    {% endif %}

[menu __main __relais __RelaysLeds]
type: input
name: LEDSs {'On ' if menu.input else 'Off'}
input: {printer["gcode_macro relayleds"].ledsstatus}
input_min: 0
input_max: 1
input_step: 1
gcode: 
    relayleds VALUE={menu.input}
    #{ menu.back() }

```

6) there is on my side a BIG missunderstanding in macro parameters, and how to call them.
sometimes in docs, we can see "G4 P{DELAY}"
sometimes we can see "M117 Now at { params.VALUE|float * 100 }%"  

==> for that 2nd version (params.xxx) => WHY the '%' after the '}' ? If I write it like that, it does not work on my side, it would print just 'Now at  %'.  if I write {% params.VALUE|float * 100 %} klipper refuses with a TemplateSyntaxError: Encountered unknown tag 'params' ......... so ......... how do macro params  really work ? I'm confused how they are used with jinja and wether the "params" is an old thing or not ? seems to me that they are called with { VALUE } (no params, no "%" but I'm not sure what syntax is that)

~~7) bonus question : for macro variables ... WHAT IS a python literal ?? as I'm trying to use "OFF" and "ON", the variable get initialized but then I cannot set_gcode_variable it because "Recv: !! Unable to parse 'ON' as a literal"  ... (yes it's not related to menus, but If I can get an answer without opening an issue just for that .... ho, and google was of no help on that topic)~~

that syntax works :
```
SET_GCODE_VARIABLE MACRO=RELAY_LEDS VARIABLE=ledsstatus VALUE="'ON'"
```

... there "may" be other things missing, I still have not succesfully migrated my full configuration yet. 

[klippy.log](https://github.com/KevinOConnor/klipper/files/5636273/klippy.log)

**Comment by mcmatrix** [comment]
Hi @aschor,

I'll try to answer your questions.

0. The example configurations are now collected into one place [klipper/docs/Config_Reference.md](https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md) 
The `menu.cfg` has a expired reference to example file.

1. `Items` attribute is no more allowed.
A child item can belong only to one parent.

2.  Yes, you cannot alter the existing menu structure like previously
but you can override or add items from/to default menu.
For example, this will disable (hide) Octoprint menu.
```ini
[menu __main __octoprint]
type: disabled
```
5. Current syntax is more powerful and uses the same approx as in gcode-macros. 
Please check the existing examples in the default menu configuration.
For example `[menu __main __control __fanonoff]` and `[menu __main __control __caselightonoff]`

**Comment by aschor** [comment]
thanks @mcmatrix , I had'nt spotted that one __caselightonoff I'll try to adapt it (as the pin is on the pi, and I want to control it even if printer is not connected anymore) (which happens a lot right now, as firmware_restart makes sometime klipper process to crash and terminate but that's another subject).

I'll update initial post with what I find

**Comment by mcmatrix** [comment]
6. `"M117 Now at { params.VALUE|float * 100 }%"`
In Klipper's jinja templates the `{% ... %}` is for a statement.
The expression is between `{...}`, the expression always returns a value
and in gcode template after jinja evaluation the `{...}` will be replaced by that value.
Please check Jinja syntax and `config/sample-macros.cfg` for examples.

`"M117 Now at { params.VALUE|float * 100 }%"`
It will be `M117 Now at 37%`
If the param.VALUE value is 0.37.

**Comment by mcmatrix** [comment]
7. Show your macro code or what you have at the moment.
Let's see what's wrong with that.

**Comment by mcmatrix** [comment]
5. Maybe something like this. I haven't tested it.
```
[menu RelaysLeds]
type: input
name: LEDSs {'On ' if menu.input else 'Off'}
input: 0
input_min: 0
input_max: 1
input_step: 1
gcode: 
    RESPOND TYPE=command MSG=action:relaisLeds{'On ' if menu.input else 'Off'}
    { menu.back() }
```

**Comment by aschor** [comment]
wow, thanks ! I'll take that 5)  I think it will work, you master this jinja :)

7) is really a macro to try to understand how variables and parameters work. but CLEARLY, like stated in 6), there is NO "params"  : ` { params.DISPLAYONLY }` doesn't work (throws TemplateSyntaxError: Encountered unknown tag 'params' and refuses to start firmware) whereas `{ DISPLAYONLY }`   works  ; 


here I get error "litteral error" when calling `relay_leds displayonly=0 ` (but the respond tells me it's value is "OFF" !) :
```
[gcode_macro relay_leds]
variable_ledsstatus: "OFF"
default_parameter_displayonly: 1
gcode: 
    {% if DISPLAYONLY == "0"  %}
        RESPOND MSG="variable value : { ledsstatus }"
        SET_GCODE_VARIABLE MACRO=relay_leds VARIABLE=ledsstatus VALUE="ON"
        RESPOND MSG="variable value : { ledsstatus }"
    {% else %}
        RESPOND MSG="displayonly = { DISPLAYONLY }  "
    {% endif %}
```

for me, "params" never works anywhere in macros, it's undefined. is the following really working for you ? here I get error at firmware start (and it does not start)
```
[gcode_macro relay_leds]
variable_ledsstatus: "OFF"
default_parameter_displayonly: 1
gcode: 
    {% if params.DISPLAYONLY == "0"  %}
        RESPOND MSG="variable value : { ledsstatus }"
        SET_GCODE_VARIABLE MACRO=relay_leds VARIABLE=ledsstatus VALUE='ON'
        RESPOND MSG="variable value : { ledsstatus }"
    {% else %}
        RESPOND MSG="displayonly = { params.DISPLAYONLY }  "
    {% endif %}
```

by the way, I don't understand why, in a [macro] bloc, we cannot assign a value to the variable directly without all this fancy set_gcode_variable. Or can we ? if not, there is no point in having the variable reside in a [macro] bloc, they could be in a [variables] bloc if it existed (?)

**Comment by mcmatrix** [comment]
About your gcode macro `[gcode_macro RELAY_LEDS]`.

It looks like the SET_GCODE_VARIABLE MACRO command likes to get string values in a specific way.
The single quotes will be stripped away and then the internal parser doesn't recognize it as a string.

Btw why this code, why not store the number value what you get from parameter.
Anyway, this is how I got your macro working. 

```ini
[gcode_macro RELAY_LEDS]
variable_ledsstatus: "OFF"
default_parameter_DISPLAYONLY: 1
gcode:
    {% if DISPLAYONLY == "0"  %}
        RESPOND MSG="variable value : { ledsstatus }"
        SET_GCODE_VARIABLE MACRO=RELAY_LEDS VARIABLE=ledsstatus VALUE="'ON'"
        RESPOND MSG="variable value : { ledsstatus }"
    {% else %}
        RESPOND MSG="displayonly = { DISPLAYONLY }  "
    {% endif %}

```

**Comment by aschor** [comment]
I'm rethinking the thing, as I can switch the leds from octoprint via a system menu, and thus via a mobile app, and also via mqtt addon. And really I (like many I believe) am total stranger to jinja so not knowing all ways to do we don't "choose" the right way because we don't know it yet ... this macro was just tinkering, trials and errors because of the lack of more examples ....

thank you for your answers ! (so you confirm that the "param.VALUE" syntax is outdated and not working ?)

**Comment by aschor** [comment]
@mcmatrix 

do you have any idea why this always calls the macro with value 0, even if using the menu it changes from 'off' to 'on', but reverts back to 'off' when I click on 'on' ?  Macro works correctly when used via terminal. 


```
[gcode_macro relayleds]
variable_ledsstatus: 0
gcode: 
    {% if VALUE is defined %}        
        {% if VALUE|float == 1 %}
            SET_GCODE_VARIABLE MACRO=relayleds VARIABLE=ledsstatus VALUE=1
            RESPOND TYPE=command MSG=action:relaisLedsOn
        {% else %}
            SET_GCODE_VARIABLE MACRO=relayleds VARIABLE=ledsstatus VALUE=0
            RESPOND TYPE=command MSG=action:relaisLedsOff
        {% endif %}
    {% else %}
        RESPOND MSG="LEDs are : { 'On' if ledsstatus else 'Off'}"
    {% endif %}

```
```
[menu __main __relais __RelaysLeds]
type: input
name: LEDSs {'On ' if menu.input else 'Off'}
input: {printer["gcode_macro relayleds"].ledsstatus}
input_min: 0
input_max: 1
input_step: 1
gcode: 
    relayleds VALUE=menu.input
    #{ menu.back() }
```

Do I guess correctly if I say that a menu input cannot be a variable in a macro ?
if So, can we change a menu input value  via a macro ?

**Comment by mcmatrix** [comment]
What I see from the menu code that you're not using the expression brackets.
Maybe this is better.
```ini
[menu __main __relais __RelaysLeds]
type: input
name: LEDSs {'On ' if menu.input else 'Off'}
input: {printer["gcode_macro relayleds"].ledsstatus}
input_min: 0
input_max: 1
input_step: 1
gcode: 
    relayleds VALUE={menu.input}
    #{ menu.back() }
```

**Comment by aschor** [comment]
yes you're right ! it works that way, thanks ! (fighting the PI not booting from USB all day drove me nuts)

point 5 answered !

**Comment by mcmatrix** [comment]
I'm not the specialist of macro internals but it looks like it's there.

Example macro.
```ini
[gcode_macro REPORT_PARAMS]
gcode:
    {% for name in params %}
        { action_respond_info("params['%s'] = %s" % (name, params[name])) }
    {% endfor %}
```

When you call macro with parameters `REPORT_PARAMS TEST1=2 TEST3=4`
the output will be
```
params['TEST1'] = 2
params['TEST3'] = 4
```
Without parameters it's empty.

It will output to log, use this command to get live log stream.
`tail -f /tmp/klippy.log`

**Comment by aschor** [comment]
ok, your macro works indeed. But check that :
```
[gcode_macro REPORT_PARAMS_def]
default_parameter_displayonly: 1
gcode:
    {% for name in params %}
        { action_respond_info("params['%s'] = %s" % (name, params[name])) }
    {% endfor %}    
```
and the result : 
```
Send: REPORT_PARAMS_DEF TEST1=2 TEST3=4
Recv: // params['TEST1'] = 2
Recv: // params['TEST3'] = 4
```
==> no "params['displayonly']

Soooo default_parameters are NOT included in "params" dict. that's odd behaviour but that explains why I encountered errors while trying tu use it  ......... is this a bug ? or is this "expected" behaviour ?

**Comment by mcmatrix** [comment]
I think `params` may have its purpose.

In your case its safe to use the standard way ([link to gcode doc](/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#g-code-macros-and-events)).

If you always call the macro with parameter then you might not need `default_parameter_XXXX`
It's up to you to decide whether you want default value for the parameter or not
but you can always refer to your parameter named `XXXX` in the macro template via `{XXXX}`.

**Comment by aschor** [comment]
ok, closing it since my questions got answered, thanks
