### ISSUE TITLE
Printer head goes out of print area and CommandError: Unable to read tmc uart 'stepper_a' register IFCNT

### ISSUE THREAD

**Issue by mukamuk1** [KevinOConnor/klipper#3607]
[klippy2.error.log](https://github.com/KevinOConnor/klipper/files/5648860/klippy2.error.log)

Hi!
I got this rather serious issue suddenly. I have runned this config pretty much untouched for many weeks and I have printed with it dozens of prints. And after this accident everything works normally.

I started print normally and after start printhead went straight out of print area and jammed it near one of support towers. What it looked like that one of the motors shutdown and two other motors pushed the printhead down and out of print area. Printer did stop the movement automatically but still belts where slipping for about 10 seconds.

My question is that what happened? And how to avoid this? Is this user (config) error? Perhaps catch this error and stop any movement if this happens during print?

Edit: Printer is Flsun QQ-S Pro with 2208 drivers in UART-mode.

**Comment by LazaroFilm** [comment]
I'm also getting some stepper issues with the last update. Something is aloof.
