### ISSUE TITLE
Ender 3 + MKS GEN L: Unable to read tmc uart 'stepper_x' register IFCNT

### ISSUE THREAD

**Issue by Zwen1111** [KevinOConnor/klipper#3631]
Can somebody help me with this error:
` Unable to read tmc uart 'stepper_x' register IFCNT`

I tried to do everything in the [video](https://youtu.be/5bIzcA8PBgY) of TeachingTech. I copied his printer.cfg file and changed a few settings that have another name these days. I don't have BLTouch so I removed that block of settings. If you are interested in the config, I attached it as a .txt. 

Also I added the klippy.log file. I don't have any idea what is causing the problem. I tried to find any other issues with the same kind of problem, but nothing helps. I hope somebody of you could 😃 

[klippy.log](https://github.com/KevinOConnor/klipper/files/5685188/klippy.log)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/5685189/printer.cfg.txt)
![IMG_20201213_194808](https://user-images.githubusercontent.com/23332341/102020867-5074c100-3d7c-11eb-97de-10cfab57c342.jpg)
![IMG_20201213_194819](https://user-images.githubusercontent.com/23332341/102020869-51a5ee00-3d7c-11eb-8d5e-45188bbab349.jpg)
![IMG_20201213_194828](https://user-images.githubusercontent.com/23332341/102020871-52d71b00-3d7c-11eb-8f44-582dbb809965.jpg)

**Comment by NBouquain** [comment]
From the picture, you have two MKS pins per TMC UART pin, but in you config file only one is declared.
You need to add the _tx_pin_ parameter in each TMC2208 sections.

If your steppers are connected as per the video, the configuration should be as follow (tx_pin should be the one with the resistor). Note that your TMC2208 section for the extruder is incorrectly named stepper_extruder, extruder is enough.

[tmc2208 stepper_x]
uart_pin: ar63  #   The pin connected to the TMC2208 PDN_UART line. (RX)
tx_pin:   ar40  #   The TX pin if separate

[tmc2208 stepper_y]
uart_pin: ar64  #   The pin connected to the TMC2208 PDN_UART line. (RX)
tx_pin:   ar59  #   The TX pin if separate

[tmc2208 stepper_z]
uart_pin: ar65  #   The pin connected to the TMC2208 PDN_UART line. (RX)
tx_pin:   ar42  #   The TX pin if separate

[tmc2208 extruder]
uart_pin: ar66  #   The pin connected to the TMC2208 PDN_UART line. (RX)
tx_pin:   ar44  #   The TX pin if separate

**Comment by Zwen1111** [comment]
> From the picture, you have two MKS pins per TMC UART pin, but in you config file only one is declared.
> You need to add the _tx_pin_ parameter in each TMC2208 sections.
> 
> If your steppers are connected as per the video, the configuration should be as follow (tx_pin should be the one with the resistor). Note that your TMC2208 section for the extruder is incorrectly named stepper_extruder, extruder is enough.
> 
> [tmc2208 stepper_x]
> uart_pin: ar63  #   The pin connected to the TMC2208 PDN_UART line. (RX)
> tx_pin:   ar40  #   The TX pin if separate
> 
> [tmc2208 stepper_y]
> uart_pin: ar64  #   The pin connected to the TMC2208 PDN_UART line. (RX)
> tx_pin:   ar59  #   The TX pin if separate
> 
> [tmc2208 stepper_z]
> uart_pin: ar65  #   The pin connected to the TMC2208 PDN_UART line. (RX)
> tx_pin:   ar42  #   The TX pin if separate
> 
> [tmc2208 extruder]
> uart_pin: ar66  #   The pin connected to the TMC2208 PDN_UART line. (RX)
> tx_pin:   ar44  #   The TX pin if separate

At first I thought that this would fix it, but unfortunately it didn't. Anything I could do to find out if the wiring is working as it should? 

The LCD isn't showing anything, that is not good as well. Any solution?

**Comment by NBouquain** [comment]
The LCD not showing anything is a typical behavior in case of Klipper incomplete initialization due to an error, in your case the TMC2208 configuration failure.

Just for confirmation, have you soldered to two pads on the bottom of each driver to enable UART mode as described here? https://www.bigtree-tech.com/products/bigtreetech-tmc2208-v3-0.html

**Comment by Zwen1111** [comment]
> The LCD not showing anything is a typical behavior in case of Klipper incomplete initialization due to an error, in your case the TMC2208 configuration failure.
> 
> Just for confirmation, have you soldered to two pads on the bottom of each driver to enable UART mode as described here? https://www.bigtree-tech.com/products/bigtreetech-tmc2208-v3-0.html

It looks like there is already a resistor soldered on it. I tried to wire it without a resistor, but it didn't work

![IMG_20201221_102152.jpg](https://user-images.githubusercontent.com/23332341/102760850-65ea7c00-4376-11eb-93e4-78351013bacd.jpg)

**Comment by NBouquain** [comment]
Weird, perhaps it is a 0 Ohm resistor to replace the solder joint, in that case no soldering is required.
Based on this picture, the UART should be available on the MS3 pin (instead of the PDN pin).

If the wiring has not been modified compared to your first post, you are currently connected to the PDN pin (ie the middle one), 
could you try to connect to the the left pin ?

**Comment by Zwen1111** [comment]
Should I revert the changes to the configuration file that you suggested?

**Comment by NBouquain** [comment]
Not for now, it should work regardless of the presence or not of a resistor on the driver.
Once your setup is working, you could try to replace your wires with a single dupon wire (without inline resistor), and the configuration file should then be updated to remove  the 'tx_pin'

**Comment by Zwen1111** [comment]
The error remains unfortunately...

**Comment by Zwen1111** [comment]
I solved it! I came across [this](https://www.youtube.com/watch?v=6RcrgmNvyeA) video that explained two of the three jumpers were needed:
![afbeelding](https://user-images.githubusercontent.com/23332341/102820745-0b810800-43d6-11eb-8943-0767b8b43a4a.png)
On my board all three of the jumpers were connected. I removed the one that was missing. I wired it up like @NBouquain explained. So the cables had to be on the left (MS3) pin.

**Comment by NBouquain** [comment]
All right, it was so obvious that I forgot about that one :-(
To avoid any interaction in UART mode you should remove all the jumper. They are no longer required since you can change the stepper microsteps through the 'microsteps:' parameter
