### ISSUE TITLE
Scheduled digital out event will exceed max_duration

### ISSUE THREAD

**Issue by Afterschnitzel** [KevinOConnor/klipper#3635]
Hi.
I have disconnecting issues randomly during the print after updating klipper. Can you please help me?
Enisy Rambo - custom MK3S printer.

>  19:34:11
> Previous MCU 'mcu' shutdown: Scheduled digital out event will exceed max_duration
> 19:34:12
> Previous MCU 'mcu' shutdown: Scheduled digital out event will exceed max_duration
> Once the underlying issue is corrected, use the
> "FIRMWARE_RESTART" command to reset the firmware, reload the
> config, and restart the host software.
> Printer is shutdown

[klippy.log](https://github.com/KevinOConnor/klipper/files/5690888/klippy.log)

**Comment by KevinOConnor** [comment]
The log indicates a large number of messages are being lost between the host and micro-controller.  It looks like you're using a Prusa variant of the einsy rambo which has a known bug in the firmware of the usb-to-serial chip.  My understanding is that board requires some updates to run successfully with Klipper.  @Arksine may have more info.

-Kevin

**Comment by Afterschnitzel** [comment]
Thank you Kevin. I already notified the Einsy board has performance issues. I am unable use more than 16 microstepping on extruder using 3.5:1 gear ratio and 0.8°stepper. 
So I ordered BTT002 board and I will see B-)

**Comment by Arksine** [comment]
Kevin is correct.  Prusa flashes a custom version of "usbserial" firmware on the Atmega 32u2.  Unfortunately this firmware corrupts serial transfers and it gets progressively worse over time.  If you want to use the Einsy with Klipper you can flash a [modified version](https://github.com/PrusaOwners/mk3-32u2-firmware) of the Firmware.  This does require a programmer (or an Arduino flashed with the ArudinoISP sketch).  If you aren't comfortable doing this waiting on the BTT002 is probably your best bet.

**Comment by Afterschnitzel** [comment]
Thank you guys for your advices. I will try to tune Einsy before my BTT002 arrive :-)

**Comment by Afterschnitzel** [comment]
Hi. 
I played with Arduino Leonardo this weekend and I succesfully flashed 32u2. So I will see if the problem is solved or not :-)

**Comment by Afterschnitzel** [comment]
So problem was solved, thanks again.

**Comment by dvoelkel** [comment]
Had the same problem, found this hint,
followed the solution, and fixed the problem.

First print died after 90 minutes, Now at 120 minutes and still printing.

Thanks mates :)

**Comment by dvoelkel** [comment]
Narf. Died after 150 minutes :-( Same problem :-(

**Comment by Afterschnitzel** [comment]
Hi. Maybe you didn' reflash 32u2 properly. But I don't know how to check it.
I think this solution solved my problem, I did 5 Hour print without issue. But in next 2 days after flash my BTT002 arrived and I am not using Einsy Rambo anymore. So I didn't make any longer prints on it.
I must day that BTT002 is great print quality improvement with Klipper on MK3S.

**Comment by dzhaparoff** [comment]
@Afterschnitzel Hi! Sorry for offtop, my question is about BTT002 + Klipper. How is it? It is worth to upgrade from stock prusa einsy to BTT002? How reliably BTT002 works with Klipper? All features implemented and working properly?

**Comment by Afterschnitzel** [comment]
> @Afterschnitzel Hi! Sorry for offtop, my question is about BTT002 + Klipper. How is it? It is worth to upgrade from stock prusa einsy to BTT002? How reliably BTT002 works with Klipper? All features implemented and working properly?

Hi. Yes, BTT002 is worth replacement for obsolete 8bit Einsy Rambo. But I reccomend to print Zaribo electronic case, because in stock box there is conflict with driver's heatsinks.

**Comment by dzhaparoff** [comment]
> > @Afterschnitzel Hi! Sorry for offtop, my question is about BTT002 + Klipper. How is it? It is worth to upgrade from stock prusa einsy to BTT002? How reliably BTT002 works with Klipper? All features implemented and working properly?
> 
> Hi. Yes, BTT002 is worth replacement for obsolete 8bit Einsy Rambo. But I reccomend to print Zaribo electronic case, because in stock box there is conflict with driver's heatsinks.

Thank you! Yep, i already have big thick reversed Einsy-box with more space for better cable management and RaspberryPI.

**Comment by Afterschnitzel** [comment]
> > > @Afterschnitzel Hi! Sorry for offtop, my question is about BTT002 + Klipper. How is it? It is worth to upgrade from stock prusa einsy to BTT002? How reliably BTT002 works with Klipper? All features implemented and working properly?
> > 
> > 
> > Hi. Yes, BTT002 is worth replacement for obsolete 8bit Einsy Rambo. But I reccomend to print Zaribo electronic case, because in stock box there is conflict with driver's heatsinks.
> 
> Thank you! Yep, i already have big thick reversed Einsy-box with more space for better cable management and RaspberryPI.

Don't forget to add system fan. I didn't do that and fry BTT002 heater bed mosfet in enclosure.

**Comment by dzhaparoff** [comment]
Oh, thanks for the advice! Such a strange thing, original einsy's mosfets are cool enough.
