### ISSUE TITLE
Z won't home, stepper does not move / engage

### ISSUE THREAD

**Issue by trooper55** [KevinOConnor/klipper#3638]
when trying to run a g28 y0 x0 z0 the printer will home verything but the z. it hangs after deplying the probe it goes from red probe deployed blue light then out. Then sits there no z motor movement at all. 

[klippy.log](https://github.com/KevinOConnor/klipper/files/5695111/klippy.log)

**Comment by FanDjango** [comment]
BLTouch original (V3.1?) or clone?
Please remove  `pin_up_touch_mode_reports_triggered = False`, not needed for original BLTouch
Have you worked the stufff in [](https://github.com/KevinOConnor/klipper/blob/master/docs/BLTouch.md)?
The blue light goes out in klipper after commands, because the PWM is shut off until the next command.
Need more info

**Comment by trooper55** [comment]
I apologize I am very new to this. any info you need please let me know. I do a lot of mechanical work so i can describe stuff fairly well. So I was able to home all 3 axis and ran just fine with a print minus me not setting the z offset right. I replaced the filament feed tube from the factory to the fancy blue one. I accidently pulled the plug out of the bltouch. I plugged it back in checked for any other issues and found non then started to re do the calibration for the z offset but once trying to home the z nothing. the motors don't even seem to engage. I took out the line of code you suggested and tried again and nothing.  When commanded to home the z I can still turn the z lead screw with no resistance.  As far as the blue light deal i Just feel like i remember the blue light being on solid tell touched before I unplugged it. Sorry Im just grasping at straws I also have an ender3 v2 that I cant communicate with after trying to install klipper so im down to no working 3d printers ahahah my own fault. 

Controller board i think is the factory 4.2.2 board im running on pi 4 2gb.

**Comment by FanDjango** [comment]
> I took out the line of code you suggested and tried again and nothing.

I was not expecting that to solve the immediate problem but perhaps later ones

>  When commanded to home the z I can still turn the z lead screw with no resistance

Well, that points to the configuration in klipper for the z stepper being wrong, or the z stepper wiring being wrong. If the z stepper won't move, how should a probe ever get to the point of doing something?

Consider changing the title of the issue to "Z won't home, stepper does not move / engage". It's not the fault of the BLTouch.

**Comment by trooper55** [comment]
I reloaded the original printer config file in the directory and still nothing. working on trying to figure out how to test the stepper motors them self.

**Comment by FanDjango** [comment]
These are the ones that need to be checked:
```
[stepper_z]
step_pin = PL3
dir_pin = PL1
enable_pin = !PK0
```

**Comment by trooper55** [comment]
[stepper_z]
step_pin: PL3
dir_pin: PL1
enable_pin: !PK0
step_distance: .001266
endstop_pin: probe:z_virtual_endstop
position_max: 400
position_min: 0
homing_speed: 10.0

**Comment by FanDjango** [comment]
Yes, but are they right?

**Comment by FanDjango** [comment]
> So I was able to home all 3 axis and ran just fine with a print minus me not setting the z offset right

Let's go back a step.

It worked before, and now, no more Z movement? So then the pin definitions would not be the problem.

**Comment by FanDjango** [comment]
In the log:
`Failed to home z: Timeout during homing`

Ok, I would test removing the `[bltouch]` section (temporarily):
```
[bltouch]
sensor_pin = ^PD3
control_pin = PB5
x_offset = -43
y_offset = -8
z_offset = 0
speed = 3.0
pin_up_touch_mode_reports_triggered = False
```
and put the `^PD3` definition into to stepper_z section instead of the virtual endstop.

I would then remove the plug(s) of the bltouch completely.

This would be a configuration of a normal z-axis with a fake endstop (^PD3). Its a lie, of course, and you should manually move the nozzle up quite far, then turn on the printer, try to home and if it moves, turn it off immediately to avoid damage, because the ^PD3 endstop is fake, just for testing.

If moves now, a problem with the bltouch needs to be checked. If it still does not move, need to test more things.

**Comment by trooper55** [comment]
testing now, Recv: // Klipper state: Ready
Send: M105
Recv: ok B:20.6 /0.0 T0:21.2 /0.0
Send: G91
Recv: ok
Send: G28 X0 Y0
Recv: ok
Send: G90
Recv: ok
Send: M105
Recv: ok B:20.6 /0.0 T0:21.2 /0.0
Send: G91
Recv: ok
Send: G28 Z0

14:04:04 Firmware version: v0.9.1-115-g77add956
14:04:04 Connected to host via /tmp/printer @0bps
14:04:05 Firmware version: v0.9.1-115-g77add956
14:04:17 Move out of range: 180.000 180.000 410.000 [0.000]
14:04:55 Klipper state: Disconnect
14:04:59 Klipper state: Ready
14:05:52 Too many consecutive timeouts, printer still connected and alive?


Guessing I have an issue with the board or my stepper motors. great.

**Comment by trooper55** [comment]
any easy way to go back to factory firmware quick just to check its not software?

**Comment by FanDjango** [comment]
> 4:04:17 Move out of range: 180.000 180.000 410.000 [0.000]

Huh? Its not even trying

**Comment by trooper55** [comment]
nope after taking out the probe code and setting ^PD3 probe plugged in or out homes x and y centers to home z then sits

**Comment by FanDjango** [comment]
Don't give up too early.

`position_max = 400` is in your Z. Why does he want to go to to 410? Homing upwards? Lemme check a few things...

**Comment by trooper55** [comment]
[stepper_z]
step_pin: PL3
dir_pin: PL1
enable_pin: !PK0
step_distance: .001266
endstop_pin: ^PD3
position_endstop: 400
position_max: 400
position_min: 0.0
homing_speed: 15.0

**Comment by FanDjango** [comment]
Add a homing dir.

`homing_positive_dir: false`

**Comment by FanDjango** [comment]
I see the problem now

**Comment by FanDjango** [comment]
#homing_positive_dir:
#   If true, homing will cause the stepper to move in a positive
#   direction (away from zero); if false, home towards zero. It is
#   better to use the default than to specify this parameter. The
#   default is true if position_endstop is near position_max and false
#   if near position_min.

**Comment by trooper55** [comment]
14:13:16 Connected to host via /tmp/printer @115200bps
14:13:16 Firmware version: v0.9.1-115-g77add956
14:13:16 Firmware version: v0.9.1-115-g77add956
14:13:26 Klipper state: Disconnect
14:13:29 Klipper state: Ready
14:15:38 Failed to home z: Timeout during homing
14:15:41 Klipper state: Disconnect
14:15:56 Klipper state: Ready
14:16:17 Failed to home z: Timeout during homing

**Comment by FanDjango** [comment]
You need to rethink the positions you are defining there.

Is it true that your endstop is 400 AND your pos max is 400?

Describe your printer. You home downwards, otherwise you would not be using the probe

So mine is like this:

```
[stepper_z]
step_pin: P2.2
dir_pin: P0.20
enable_pin: !P0.19
step_distance: .00125
endstop_pin: probe: z_virtual_endstop
position_min: -25
position_endstop: 2.1
position_max: 225
homing_speed: 15
homing_retract_dist: 2.5
homing_retract_speed: 30
second_homing_speed: 2.5
homing_positive_dir: false
```

**Comment by FanDjango** [comment]
I suggest:

Your next test with

```
[stepper_z]
position_min: -25
position_endstop: 2.1
position_max: 400
homing_speed: 15
homing_retract_dist: 2.5
homing_retract_speed: 30
second_homing_speed: 2.5
homing_positive_dir: false
```

**Comment by trooper55** [comment]
[stepper_z]
step_pin: PL3
dir_pin: PL1
enable_pin: !PK0
step_distance: .001266
endstop_pin: ^PD3
position_endstop: 400
position_max: 400
position_min: 0.0
homing_speed: 15.0
homing_positive_dir: false


Im just using the defaults that came with the klipper files. as the worked off the bat.  and working from there.

**Comment by FanDjango** [comment]
But not the BLTouch yet. Get ready to turn off the printer

**Comment by trooper55** [comment]
14:15:41 Klipper state: Disconnect
14:15:56 Klipper state: Ready
14:16:17 Failed to home z: Timeout during homing
14:19:58 Klipper state: Disconnect
14:20:01 Klipper state: Ready
14:20:03 Must home axis first: 10.000 0.000 0.000 [0.000]

with what you posted

[stepper_z]
step_pin: PL3
dir_pin: PL1
enable_pin: !PK0
step_distance: .001266
endstop_pin: ^PD3
position_min: -25
position_endstop: 2.1
position_max: 400
homing_speed: 15
homing_retract_dist: 2.5
homing_retract_speed: 30
second_homing_speed: 2.5
homing_positive_dir: false

**Comment by FanDjango** [comment]
Does your printer home upwards (nozzle towards bed) or downwards (nozzle away from bed)

**Comment by trooper55** [comment]
no movement on any of the changes. just x and y movement

**Comment by FanDjango** [comment]
Can we do this conversation on discord? I think we have a communication problem

**Comment by FanDjango** [comment]
It your printer WOULD WORK WELL, would it home upwards (nozzle towards bed) or downwards (nozzle away from bed)

**Comment by FanDjango** [comment]
>  I do a lot of mechanical work so i can describe stuff fairly well

Describe better. You are letting me do a lot guessing

**Comment by trooper55** [comment]
sure where have a link to chat.

And everything you make a suggestion I log into and edit the printer.confg file save it. log into octoklipper run the restart command. use the control tab to home x and y axis. then I tell it to home the z axis the head moves to the center of the ender 5 plus and sits there tell it communication errors out. I have taken the electrical connections apart and reseated them in hopes of a lose connection.

**Comment by FanDjango** [comment]
https://discord.gg/QsmxAFgn

**Comment by FanDjango** [comment]
Spent a lot of time on discord.

Ok, we've cleared up most of the stuff. Most of the above discussion can be ignored and @trooper55 will close this and open up a new one with up-to date info on what is actually going on.

One thing that threw me was "position_endstop" --> being replaced by "z_offset" when you define the `[bltouch]`. 

In the official docs:

```
position_endstop:
#   Location of the endstop (in mm). This parameter must be provided
#   for the X, Y, and Z steppers on cartesian style printers. 
```

and 

```
#homing_positive_dir:
#   If true, homing will cause the stepper to move in a positive
#   direction (away from zero); if false, home towards zero. It is
#   better to use the default than to specify this parameter. The
#   default is true if position_endstop is near position_max and false
#   if near position_min.
```

but specifiying this when you also specify `[bltouch]` section causes:
```
!! Option 'position_endstop' is not valid in section 'stepper_z'
```

**Comment by KevinOConnor** [comment]
Okay.  FYI, there is a mention of this at: https://www.klipper3d.org/Config_Reference.html#bed-probing-hardware .  There was also a recent change documented at: https://www.klipper3d.org/Config_Changes.html

-Kevin

**Comment by trooper55** [comment]
went back to oem firmware and tried to home nothing. looks like the board chose to die.
