### ISSUE TITLE
BTT SKR mini e3 v2: Unable to read tmc uart 'stepper_x' register IFCNT

### ISSUE THREAD

**Issue by rngSplat** [KevinOConnor/klipper#3644]
Getting the error "Unable to read tmc uart 'stepper_x' register IFCNT" in klipper. I read this could be a bad driver, so I flashed back to Marlin to confirm and debug. It works as expected in Marlin, but klipper cannot connect. Doesn't seem to be a hardware issue.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5713157/klippy.log)

**Comment by rngSplat** [comment]
I tried switching the order of the sections in the config. It appears to be throwing the error on whatever the first one in the config is.

**Comment by al3ph** [comment]
Yeah I get this error on and off, usually restarting klipper gets it working, or switching it on and off again.

**Comment by al3ph** [comment]
Sounds like the board is just not responding properly.

**Comment by rngSplat** [comment]
Flipping it on and off has not helped so far.

If it's an issue of the driver not responding appropriately, why doesn't Marlin see the same issue? TMC debug came back clean.

**Comment by ThomasW69** [comment]
I have the same issue on a BTT SKR1.4 Turbo with the BTT TMC2209 v1.2 drivers. For me it looks like Klipper isn't supporting these drivers in a stable way yet.
