### ISSUE TITLE
2 or more Klipper on one Pi

### ISSUE THREAD

**Issue by LuckySunny85** [KevinOConnor/klipper#3657]
Hi, 
I have OctoPrint and Klipper running on a Raspberry with multiple instances. The setup went well. However, I can't control the second printer ( both Ender 3 with a SKR mini) in OctoPrint - /tmp/printer2/ can't be entered or selected as a port. In addition, I can control the first printer from the second instance if I select /tmp/printer/ there.
I have done this several times now with the Pi3b and the Pi4 and always end up with the same error.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5719990/klippy.log)

With kind regards 

LuckySunny

**Comment by BlackStump** [comment]
[did you read this section?](https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#can-i-run-multiple-instances-of-klipper-on-the-same-host-machine)

**Comment by greyhound3** [comment]
Have you read this http://thomas-messmer.com/index.php/14-free-knowledge/howtos/79-setting-up-octoprint-for-multiple-printers ? Works perfectly for me.

**Comment by LuckySunny85** [comment]
The installation is not the problem. The installation went well.
But i dont get a connection to the secound printer. 
In the secound Octoprint it looks like this, i cant take printer2 as a port
![printer 2](https://user-images.githubusercontent.com/75226156/103153295-d2f37c80-478f-11eb-89e2-4e2216b4f8d8.png)
If i delet tmp/printer it looks like this.
![printer21](https://user-images.githubusercontent.com/75226156/103153380-62992b00-4790-11eb-8977-ea1dfee06dd5.jpg)

**Comment by 1N4148** [comment]
Looks like your second instance wasn't started with the right parameter -l /tmp/klippy2.log -I /tmp/printer2
