### ISSUE TITLE
Sensorless homing not working, triggering immediately? [SKR v1.3 + TMC2209]

### ISSUE THREAD

**Issue by welo78** [KevinOConnor/klipper#3697]
Hi guys, I seem to be having issues with setting up the sensorless homing on Lerdge TMC2209. I switched to these drivers on X and Y but cannot get it to home at all. Previously I was using TMC2130 which worked just fine. I have a HyperCube CoreXY.

There are no jumpers present underneath the drivers themselves. UART jumper is in place as well as X and Y diag jumpers. Force move commands work flawlessly.

What I tried so far:
- numerous combinations on both stepper_x and stepper_y diag_pin with ! and ^ to no avail
- tried run current from 0.1 to 1 ( I read that this might be the cause of sensitivity issues)
- setting the sensitivity from 1 - 250 (setting it to 1 causes the motor to atleast move a few mms before triggering, if setup to 250 it does not move at all)
- combinations of all of the above

Klippy log might provide more information however the settings there are experimental, like I said I tried a lot of stuff.

Any suggestions are welcome. I for one think that the sensitivity even if set to 1 is still too high. Idk if there is an option to lower it even further or to use different diag pin ?

I am also adding the [official driver schematic](https://www.lerdge.com/public/upload/file/360f824755ab521bd741a67994b1de7e.pdf) which might provide some more informaton regarding resistors and other stuff which unfortunatelly I do not know enough.

Below is my soldering/setup of these drivers. Force movement works flawlessly.
![image](https://user-images.githubusercontent.com/42773655/103294005-45af6280-49f1-11eb-8544-af68e1eedb11.png)
![image](https://user-images.githubusercontent.com/42773655/103294025-5233bb00-49f1-11eb-94e3-53a10f61f392.png)

Klipper log:
[klippy.log](https://github.com/KevinOConnor/klipper/files/5751137/klippy.log)

TMC2209 stepper_x dump:
```
Send: DUMP_TMC STEPPER=stepper_x
Recv: // ========== Write-only registers ==========
Recv: // IHOLD_IRUN: 00080202 IHOLD=2 IRUN=2 IHOLDDELAY=8
Recv: // TPWMTHRS:   00000034 TPWMTHRS=52
Recv: // TPOWERDOWN: 00000014 TPOWERDOWN=20
Recv: // SGTHRS:     00000001 SGTHRS=1
Recv: // ========== Queried registers ==========
Recv: // GCONF:      000001c0 pdn_disable=1 mstep_reg_select=1 multistep_filt=1
Recv: // GSTAT:      00000001 reset=1
Recv: // IFCNT:      00000015 IFCNT=21
Recv: // OTP_READ:   00000011 OTP_FCLKTRIM=17
Recv: // IOIN:       21000041 ENN=1 PDN_UART=1 VERSION=0x21
Recv: // FACTORY_CONF: 00000011 FCLKTRIM=17
Recv: // TSTEP:      000fffff TSTEP=1048575
Recv: // MSCNT:      0000004c MSCNT=76
Recv: // MSCURACT:   00dc006f CUR_A=111 CUR_B=220
Recv: // CHOPCONF:   13030053 toff=3 hstrt=5 TBL=2 vsense=1 MRES=3(32usteps) intpol=1
Recv: // DRV_STATUS: c0020000 CS_ACTUAL=2 stealth=1 stst=1
Recv: // PWMCONF:    c80d0e24 PWM_OFS=36 PWM_GRAD=14 pwm_freq=1 pwm_autoscale=1 pwm_autograd=1 PWM_REG=8 PWM_LIM=12
Recv: // PWM_SCALE:  0000000a PWM_SCALE_SUM=10
Recv: // PWM_AUTO:   0021006b PWM_OFS_AUTO=107 PWM_GRAD_AUTO=33
Recv: // SG_RESULT:  00000002 SG_RESULT=2
```

**Comment by welo78** [comment]
It seems the issue is with the diag pin position. These drivers were created as Waterott equals and thus have the diag pin on the left side. However BTT TMC2209 have it on the correct side which is the right side. 

This means that a jumper cable must be in place in order to work properly. However using mechanical endstops and not using the stallguard/sensorless homing option at all could also fix this issue. I will come back with more findings.

**Comment by dertester** [comment]
From the doc it should be right.
The diag is next to EN. Did you insert the jumpers and have nothing connected to corsseponding endstops?

Maybe your homing speed is to high / low?

**Comment by welo78** [comment]
Which doc ? The skr board and klipper is configured the right diag socket. These Lerdge drivers are the same as Waterott which have the diag pin on left side. Big tree tech and fysetc TMC2209 have it on the right side and thus work from factory.

I did try a makeshit solution by soldering a long pin on the left and bending it to be on the right side in a "S"  ... all is working now flawlessly which supports my theory.

**Comment by dertester** [comment]
Everything okay. Left and right are maybe not the best way for communication.
