### ISSUE TITLE
Connect BlTouch problem

### ISSUE THREAD

**Issue by Rivega42** [KevinOConnor/klipper#372]
[klippy.zip](https://github.com/KevinOConnor/klipper/files/2069223/klippy.zip)

Good afternoon.
I connect bltouch (in a log it is visible a config) ......
Power on the bltouch comes 5 volts
If I connect a button instead of a sensor, then everything works, and if I connect a sensor, a problem arises.
I do a home check, after which the carriage jerks a bit and then the MCU swears at the wrong temperature
Recv: // "MCU 'mcu' shutdown: ADC out of range
Recv: // This generally occurs when a heater exceeds
Recv: // its configured min_temp or max_temp. "

tell me please what I did not right?

**Comment by KevinOConnor** [comment]
I don't see anything in the log that indicates a software issue.  Best guess is that the bltouch is wired incorrectly (or is malfunctioning) and causing a short or extreme electrical noise when it triggers.

-Kevin
