### ISSUE TITLE
Can't find Step_distance for my ender 3 pro

### ISSUE THREAD

**Issue by thelandinlook** [KevinOConnor/klipper#3727]
I've just installed Klippy (quite new to 3d printing) and I'm reading everywhere that I need to find my step_distance to calibrate extrusion. I just can't find it anywhere and it's driving me mad. Youtube videos show it in the config file, but nothing. I scoured the logs, configs, github, nothing. What am I missing? 

Thanks. x  
[klippy.txt](https://github.com/KevinOConnor/klipper/files/5768626/klippy.txt)

**Comment by zellneralex** [comment]
step_distance get replaced by rotation_distance. The filling might help https://www.klipper3d.org/Rotation_Distance.html#extruder

**Comment by thelandinlook** [comment]
> step_distance get replaced by rotation_distance. The might help https://www.klipper3d.org/Rotation_Distance.html#extruder


Brilliant, sorted everything. thanks :)
