### ISSUE TITLE
SKR mini E3 V1.2 - Timer too close / lost mcu conenction

### ISSUE THREAD

**Issue by Stephan3** [KevinOConnor/klipper#3728]
Hello.

For testing i installed two E3 V1.2 i had arround to one if my Vorons. It feels like random that it throws timer too close / lost mcu conenctions midprint. I had 24h prints running fine, just repeat the same plate which failed after 4? hours.

One time it told timer too close, the other time it told me lost communication. i kept both logfiles.

The host system has not changed for 3 Years now. It a Atom X5 minipc. 
[klippy_communication_lost.zip](https://github.com/KevinOConnor/klipper/files/5773169/klippy_communication_lost.zip)
[klippy_timertoclose.zip](https://github.com/KevinOConnor/klipper/files/5773170/klippy_timertoclose.zip)

Thanks
Stephan

**Comment by KevinOConnor** [comment]
You'll need to attach the logs here if you wish to use this github issue tracker.  The docs explain how to compress the logs if they are large.

-Kevin

**Comment by Stephan3** [comment]
EDIT - Post updated

**Comment by ankle-hunter** [comment]
i can't get klipper to work on the skr mini e3 v1.2. i tried every combination. my printer just won't boot. and yeah i changed the klipper.bin file to firmware.bin file and put it on a sd card and in the printer and start the printer. can you maybe upload your klipper.bin file?

**Comment by Stephan3** [comment]
@ankle-hunter 
i just did it as its stated in the config example header. But here it is attached.
[klipper.bin.zip](https://github.com/KevinOConnor/klipper/files/5794896/klipper.bin.zip)

**Comment by Stephan3** [comment]
I replaced one of the Boards on 08th and it now seems to work. i close this for now.

**Comment by ankle-hunter** [comment]
Thanks!

**Comment by ankle-hunter** [comment]
> I replaced one of the Boards on 08th and it now seems to work. i close this for now.

Thanks!

**Comment by ankle-hunter** [comment]
> I replaced one of the Boards on 08th and it now seems to work. i close this for now.

even with your .bin file the printer won't start. the screen of the ender 3 pro is just blue. nothings happens. klipper keeps saying 

Printer is not ready
The klippy host software is attempting to connect. Please retry in a few moments.
Klipper state: Not ready
Printer is not ready
