### ISSUE TITLE
Internal error on command:"G28"

### ISSUE THREAD

**Issue by Aloafromhell** [KevinOConnor/klipper#3758]
Today I installed mainsail with klipper and moonraker. After the installation everything works except for the homen. Neither the individual axes nor everything can be homed together. Where is the error? Attached my klippy log.

Internal error on command:"G28"
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

[klippy.log](https://github.com/KevinOConnor/klipper/files/5796212/klippy.log)

**Comment by KevinOConnor** [comment]
Unfortunately, your log is incomplete (it's lacking important version information).  That said, I'd suggest pulling the latest version of the code (with commit c57352a3).

-Kevin
