### ISSUE TITLE
Random BLTouch Bed Crashing

### ISSUE THREAD

**Issue by vertigo235** [KevinOConnor/klipper#376]
So, I've been having an occasional bed crash when homing with the BLTouch sensor, it has only happened 3 times or so now.  

Is it possible to set some sort of probe abort, because right now, if there is a failure the motors just keep running pushing the head down until I shut the machine off?  Almost like thermal runaway protection, the firmware should know that the probe failed after it has gone a certain distance.

**Comment by vertigo235** [comment]
hmm, I realize there is a flaw in my thought process, since the probe is used to home and set the min z, the printer doesn't know where it is and how long would be acceptable to go, bummer.

I do have a z stop, is it possible to use that as an emergency stop perhaps, the z-stop switch is below my bed level height.

**Comment by theopensourcerer** [comment]
Yep - I have a probe _and_ a z end stop. Am not at home right now so no access to my config file but it is explained in the docs and config examples.

**Comment by KevinOConnor** [comment]
I'm aware that @chainsol reported a similar issue with the bltouch not deploying properly.  I don't have a bltouch, so I can't provide any direct feedback.  I'm not aware of a mechanism to verify the bltouch is operational before homing.

In general, I recommend homing away from the bed if you can.  That's been much more stable for me.  As @theopensourcerer indicates, you can use a traditional endstop to avoid issues with the bltouch (it can be used while homing away or towards the bed).

If this occurs again, you should try to issue an M112 as soon as you can and then attach the log.  That will at least give us some information on what was occurring at the time of the failure.  Details at:
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by vertigo235** [comment]
ohhh I see, so home up and then we know how down the bed "should" be?

**Comment by vertigo235** [comment]
OK so it just happened again, most interestingly, I issued an M112 command and it did nothing.  Had to turn the machine off.

**Comment by oderwat** [comment]
Could you tell what happens in more detail?

Is the bltouch blinking before, while or after it probes?
Has the pin been deployed before probing and is just not triggering?

Did you run the self test `SET_SERVO SERVO=bltouch ANGLE=120` and checked that this really moves the pin in/out endlessly until you reset it `SET_SERVO SERVO=bltouch ANGLE=160`? If that does not work well you may need to adjust the device (maggot screw in the middle of the top).

There is also a possibility that the probe does not triggers even if the pin was down but not "down enough". You may need to mount the probe 1-2 mm higher, to avoid this.

Here is my BLTouch config for comparison:

```
[servo bltouch]
pin: PA4
maximum_servo_angle: 180
minimum_pulse_width: 0.0006
maximum_pulse_width: 0.0024
# SET_SERVO SERVO=bltouch ANGLE=x
# 10 = push pin down
# 60 = endstop test mode
# 90 = pull pin up
# 120 = self test (pin up & down)
# 160 = release alarm / reset

[probe]
pin: ^PC4
z_offset: 2.65
activate_gcode:
    SET_SERVO SERVO=bltouch ANGLE=160
    SET_SERVO SERVO=bltouch ANGLE=90
    G4 P200
    SET_SERVO SERVO=bltouch ANGLE=10
    SET_SERVO SERVO=bltouch ANGLE=60
    G4 P200
deactivate_gcode:
    G1 Z5 F600
    SET_SERVO SERVO=bltouch ANGLE=90

[homing_override]
axis: z
set_position_z: 5
gcode:
    G90
    G1 Z10 F600
    G28 X0 Y0
    G1 X160 Y120 F7200
    SET_SERVO SERVO=bltouch ANGLE=160
    SET_SERVO SERVO=bltouch ANGLE=90
    G28 Z0
    SET_SERVO SERVO=bltouch ANGLE=160
    SET_SERVO SERVO=bltouch ANGLE=90
    G1 X0 Y0 F7200

[stepper_z]
endstop_pin: probe:z_virtual_endstop
position_endstop: 2.65
....
```

**Comment by vertigo235** [comment]
Why all the extra resets in your homing_override?

**Comment by oderwat** [comment]
About the failure detection: I think it is hard to detect if the probe failed. You could define a maximum distance you are willing to risk but as the z axis can be everywhere when starting the homing procedure it is pretty much useless, because either you have it very long and thus the head would crash a long time or pretty short which would abort the homing probably to early. It would be nice to have a "move into sensor probing position" test, like an optical end stop which would trigger when before the probe is being used. There could also be an max z endstop being used first, but that would make homing really slow.

**Comment by chainsol** [comment]
Yeah, I considered Z max, but 300mm of travel at 10mm/s is a long time to wait for homing. I have the TMC2130 drivers and am thinking some sort of emergency endstop with the sensorless homing could help?

**Comment by vertigo235** [comment]
I tried your settings but I was getting a homing timeout for some reason. 

I'll play with it some more later.

**Comment by oderwat** [comment]
@vertigo235 did you changed my pins to the ones for your computer?

@KevinOConnor I update https://github.com/KevinOConnor/klipper/issues/387 with a diagram of how the BLTouch is supposed to work (instead of "faking" it with the 60° end stop test mode)

**Comment by oderwat** [comment]
Hmm.. maybe there should be `G4 P100` after every reset (160°) command, before the pin up (90°). I actually thought 160° would also always pull the pin. But at least my 3D Touch clone does not.

**Comment by dragonnn** [comment]
This could be hardware problem, I need to add capacitors to my bltouch clone.
Like this: 
https://reprapy.pl/download/file.php?id=4618&mode=view

**Comment by KevinOConnor** [comment]
FYI, it is possible that the bltouch should use a different homing sequence.  I am relying on others to provide the appropriate software/config for the bltouch.

Some notes:
- be sure to delay 100ms on each servo update (the code will internally space servo updates by 100ms, but the gcode stream also needs the delay)
- it may be worthwhile to write a python "extras" module for the bltouch (if it requires any special verification mechanisms).  For example, it's not difficult to catch a 10ms signal.
- it is possible that software pwm is not sufficient for the bltouch (though that seems unlikely).  Doing hardware pwm is possible, but is a lot of work.

-Kevin

**Comment by oderwat** [comment]
@KevinOConnor I could donate send/order you a BLTouch (clone). But I guess you don't want to fiddle with that. I did not have enough time to dig into the code (even if I would prefer that to my current day job project). I may be able to implement this eventually though.

**Comment by KevinOConnor** [comment]
Lets consolidate this issue into issue #387.

**Comment by banolka** [comment]
> [servo bltouch] pin: PA4 maximum_servo_angle: 180 minimum_pulse_width: 0.0006 maximum_pulse_width: 0.0024 # SET_SERVO SERVO=bltouch ANGLE=x # 10 = push pin down # 60 = endstop test mode # 90 = pull pin up # 120 = self test (pin up & down) # 160 = release alarm / reset [probe] pin: ^PC4 z_offset: 2.65 activate_gcode: SET_SERVO SERVO=bltouch ANGLE=160 SET_SERVO SERVO=bltouch ANGLE=90 G4 P200 SET_SERVO SERVO=bltouch ANGLE=10 SET_SERVO SERVO=bltouch ANGLE=60 G4 P200 deactivate_gcode: G1 Z5 F600 SET_SERVO SERVO=bltouch ANGLE=90 [homing_override] axis: z set_position_z: 5 gcode: G90 G1 Z10 F600 G28 X0 Y0 G1 X160 Y120 F7200 SET_SERVO SERVO=bltouch ANGLE=160 SET_SERVO SERVO=bltouch ANGLE=90 G28 Z0 SET_SERVO SERVO=bltouch ANGLE=160 SET_SERVO SERVO=bltouch ANGLE=90 G1 X0 Y0 F7200 [stepper_z] endstop_pin: probe:z_virtual_endstop position_endstop: 2.65

I tried same settings but is giving me an error.  - No option 'step_pin' in section: 'stepper_z'
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
Klipper state: Not ready
