### ISSUE TITLE
Is there a way to access a session variable?

### ISSUE THREAD

**Issue by w1ebr** [KevinOConnor/klipper#377]
Hi Kevin,

I want to write a python script that will only issue a command (like bed_tilt_calibrate) if it hasn't already been issued in the current printing session. (and is therefore still in effect). I know I can write a script that calls the command. Is there a way to access "session variables" so I can check whether the command was ever issued?

Thanks!
Gene

**Comment by KevinOConnor** [comment]
On Wed, Jun 06, 2018 at 08:45:15PM +0000, w1ebr wrote:
> I want to write a python script that will only issue a command (like bed_tilt_calibrate) if it hasn't already been issued in the current printing session. (and is therefore still in effect). I know I can write a script that calls the command. Is there a way to access "session variables" so I can check whether the command was ever issued?

I'm not sure what you mean by "session variables", but if you are
writing python code it seems to me the simplest solution would be to
change the bed_tilt code to track when the calibration has been run
and be capable of relaying that to other classes interested in the
information.

-Kevin
