### ISSUE TITLE
Prusa default config 

### ISSUE THREAD

**Issue by pollock1234** [KevinOConnor/klipper#3770]
Hi there,

I've just installed Klipper on my prusa but seem to be having an issue with the menu filament feed menu item at the bottom. It doesnt seem to like the name parameter. The only way for me to get it working is to remove the item completely. Is there a syntax change needed to be made? The attached logfile directs me to the name section as it expects end of statement but receives a : instead.

Thanks in advance

[log.txt](https://github.com/KevinOConnor/klipper/files/5808554/log.txt)

**Comment by nunorosado1991** [comment]
Can you add your ptinter.cfg?
is connect via usb?
witch board?
thansk a lot

**Comment by pollock1234** [comment]
Hi sorry for the late reply. I'm away from my machine. Its an einsy rambo clone for a prusa mk3s running the stock printer config supplied by prusa. I'll link to their github. https://raw.githubusercontent.com/PrusaOwners/klipper/master/config/printer-prusa-i3-mk3-2017.cfgCheersP
-------- Original message --------From: nunorosado1991 <notifications@github.com> Date: 31/01/2021  14:45  (GMT+00:00) To: KevinOConnor/klipper <klipper@noreply.github.com> Cc: pollock1234 <pollock1234@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [KevinOConnor/klipper] Prusa default config  (#3770) 
Can you add your ptinter.cfg?
is connect via usb?
witch board?
thansk a lot

**Comment by pollock1234** [comment]
Sorry its a einsy rambo 1.1b if that makes any odds
-------- Original message --------From: nunorosado1991 <notifications@github.com> Date: 31/01/2021  14:45  (GMT+00:00) To: KevinOConnor/klipper <klipper@noreply.github.com> Cc: pollock1234 <pollock1234@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [KevinOConnor/klipper] Prusa default config  (#3770) 
Can you add your ptinter.cfg?
is connect via usb?
witch board?
thansk a lot

**Comment by pollock1234** [comment]
Sorry its via usb too
-------- Original message --------From: nunorosado1991 <notifications@github.com> Date: 31/01/2021  14:45  (GMT+00:00) To: KevinOConnor/klipper <klipper@noreply.github.com> Cc: pollock1234 <pollock1234@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [KevinOConnor/klipper] Prusa default config  (#3770) 
Can you add your ptinter.cfg?
is connect via usb?
witch board?
thansk a lot
