### ISSUE TITLE
Unable to read tmc uart 'stepper_x' register IFCNT

### ISSUE THREAD

**Issue by W0nderwaffle** [KevinOConnor/klipper#3786]
brand new skr mini e3 Turbo. no clue what is going wrong.
[klippy.log](https://github.com/KevinOConnor/klipper/files/5825455/klippy.log)

**Comment by olofolshall** [comment]
Have you tried messing around with the uart addresses?

**Comment by Afterschnitzel** [comment]
Did you remove diag pins from drivers?
