### ISSUE TITLE
ls -l /dev/serial/by-id/ Issue

### ISSUE THREAD

**Issue by n6apg** [KevinOConnor/klipper#3807]
[klippy.log](https://github.com/KevinOConnor/klipper/files/5839792/klippy.log)

Any ideas how to resolve this issue? 
I tried 2 different PIs different usb cables, different boards (SKR mini 3 V2 and stock creality 4.2.2) and in all cases I get the same issue

If I do a lsusb I get the following

i@octopi:~/klipper $ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

But a ls /dev/serial/by-id returns the following

i@octopi:~/klipper $ ls /dev/serial/by-id/
ls: cannot access '/dev/serial/by-id/': No such file or directory

klippy log attached.

Thank you!

**Comment by mks-viva** [comment]
Hi! You can try to restart putty.exe and resend command **"ls /dev/serial/by-id/*"**
