### ISSUE TITLE
SET_GCODE_OFFSET Z takes no effect

### ISSUE THREAD

**Issue by PuddingBaer91** [KevinOConnor/klipper#3810]
Hi,

if i issue the following command over terminal while printing nothing happens:

SET_GCODE_OFFSET Z=+1
or
SET_GCODE_OFFSET Z_ADJUST=1

I get no errors so i don't know whats wrong. I only can say it not adjust the z value...

thank you for your help

here are the log files: 
[octoprint (6).log](https://github.com/KevinOConnor/klipper/files/5842610/octoprint.6.log)
[klippy.log](https://github.com/KevinOConnor/klipper/files/5842612/klippy.log)

**Comment by schnello** [comment]
If you want add the offset immediately use the MOVE option.

> If "MOVE=1" is specified then a toolhead move will be issued to apply the given offset (otherwise the offset will take effect on the next absolute G-Code move that specifies the given axis). If "MOVE_SPEED" is specified then the toolhead move will be performed with the given speed (in mm/s); otherwise the toolhead move will use the last specified G-Code speed.

**Comment by PuddingBaer91** [comment]
thank you
