### ISSUE TITLE
Klipper activates all fans when Pi shuts down

### ISSUE THREAD

**Issue by Roycinger** [KevinOConnor/klipper#3815]
Hi folks,

on all my Klipper driven printers, I noticed that all controlled fans are driven at 100% as soon as the host / Pi shuts down.
They only stop when I flip the physical power switch and cut power to the entire system.
This is somehow undesireable to me.
Is there a possibility to suppress this behaviour?

For good measure: 
[klippy (7).log](https://github.com/KevinOConnor/klipper/files/5851946/klippy.7.log)

**Comment by Hywelmartin** [comment]
(https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#fan

![bild](https://user-images.githubusercontent.com/33714214/105414264-8c325e80-5c37-11eb-9b05-04bb8361862c.png)

**Comment by Roycinger** [comment]
Thanks. If the default is 0, the fans shouldn't run then if I understand it correctly. Though, they do.
Nevertheless, setting this parameter explicitely solved the fans spinning on Pi shutdown.
Also the illumination if the LEDs on my smart effector turn on, which I can't suppress with shutdown_speed

**Comment by Hywelmartin** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#output_pin

![bild](https://user-images.githubusercontent.com/33714214/105416310-3a3f0800-5c3a-11eb-9aa8-6eacf598d82e.png)

**Comment by Roycinger** [comment]
The illumination LEDs on the smart effector dont have an assigned pin. They turn on whenever the hotend turns on:
![image](https://user-images.githubusercontent.com/7791335/105418190-fb5e8180-5c3c-11eb-8651-a40e6224ff66.png)
I dont see the hotend heating up after the Pi shutdown, nevertheless

**Comment by jakep82** [comment]
The part cooling fan has a default shutdown_speed of 0.  Most other fans have a default value equal to max_power.  This is explained in the documents.

https://www.klipper3d.org/Config_Reference.html#heater_fan

**Comment by Roycinger** [comment]
Alright, that makes it totally clear! Thanks for the assistance!
