### ISSUE TITLE
Dependency python-dev missing

### ISSUE THREAD

**Issue by yschroeder** [KevinOConnor/klipper#382]
When installing `klipper` on a fresh Raspbian Stretch (image from 2018-04-18), installation of `cffi` and `greenlet` fails, due to missing `Python.h`. The package `python-dev` would provide this dependency but is not installed.

Note: I am not using Octopi/Octoprint currently and my guess is that Octoprint already installed this dependency, so it slipped through the dependencies for `klipper`. However, I guess it should still be listed in the install script.

**Comment by KevinOConnor** [comment]
Thanks.  I added it (commit 5f640699).  This may also have been the cause of issue #321.

-Kevin
