### ISSUE TITLE
adding new kinematics - REXY

### ISSUE THREAD

**Issue by StratRide** [KevinOConnor/klipper#3821]
Hi, guys, my name is Vlad Strateniuk, i'm from Ukraine and here is REXY, my project direct driven extruder on CoreXY Kinematic 

The XYE motors is taken out of the print space which is why the extruder work is to  compensate the printing head movement.

An example of working prototype on Marlin firmware - https://youtu.be/TQYYHrxIG90?t=70

I've made a fully working prototype of the printer and now i want to try to make it real on your software.

I have already installed the Klipper and everything is working fine, but yet i need help with changing the way how  the printing head works.

it'll be very helpful if you'll make my life easier with this :)

Сontacts:
My YouTube chanel - https://www.youtube.com/channel/UClrjyWYI3MfJcCRgSFK640A
Facebook - https://www.facebook.com/ssstrat/
Telegram - @stratride

[klippy.log](https://github.com/KevinOConnor/klipper/files/5855019/klippy.log)

**Comment by KevinOConnor** [comment]
Interesting.  If the X/Y stepper pulses are dependent on the E position, then you'll have a bit of work to do in order for this to work in Klipper.  The Klipper kinematics code does not currently pass the E position to the stepper kinematics code.  It would require some structural work to change that.

-Kevin
