### ISSUE TITLE
Bug/feature Heater don't turn off when idle time is reached

### ISSUE THREAD

**Issue by Hywelmartin** [KevinOConnor/klipper#3836]
Yesterday I heated up my bed from the LCD when I was removing a print.. and left it as it should timeout in set 10 min.. it didn't..

![bild](https://user-images.githubusercontent.com/33714214/105628886-f3226400-5e3f-11eb-832d-909f3ebc1cb9.png)
![bild](https://user-images.githubusercontent.com/33714214/105628894-f9b0db80-5e3f-11eb-8020-cd176a79518d.png)
[klippyheater_on_forever.zip](https://github.com/KevinOConnor/klipper/files/5862101/klippyheater_on_forever.zip)

**Comment by mcmatrix** [comment]
Hi @Hywelmartin 
I tested this scenario on my printer, having following idle settings
```ini
[idle_timeout]
#timeout: 360
timeout: 120
gcode:
    M117 HOME/ HEAT!!!
    TURN_OFF_HEATERS
    M84
```
1. Test 
- Printer LCD is at the home screen.
- Set bed temperature to 35C from Repetier-Server web UI
- Homed the printer and waited.
- After approx. idle time the bed temp target was turned to 0

2. Test 
- Set bed temperature to 35C from Repetier-Server web UI
- Homed the printer and in LCD activated the Temperature menu and set the cursor to Bed temp (like in your image).
- After approx. idle time the bed temp target was turned to 0

So in both cases, the idle timeout was working and setting heaters target to 0

**Comment by Hywelmartin** [comment]
I can do this on both of my printers...

from LCD set temp and leave the cursor like the picture... 

[klippy (2).log](https://github.com/KevinOConnor/klipper/files/5869239/klippy.2.log)
