### ISSUE TITLE
FLASH did not work after update

### ISSUE THREAD

**Issue by StefanMeGit** [KevinOConnor/klipper#385]
I updated my pi tot he newest version as I did many times before, but I get this error...

```
pi@octopi:~/klipper $ make flash FLASH_DEVICE=/dev/ttyUSB0
Makefile:78: recipe for target 'out/src/sched.o.ctr' failed
make: *** [out/src/sched.o.ctr] Illegal instruction
```
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/2087864/klippy.log.zip)

**Comment by cmock** [comment]
I think I also had that recently and solved it with

    make clean
    make

**Comment by KevinOConnor** [comment]
An "Illegal instruction" is usually an indication of a corrupt sd card.  But, first check with a full rebuild as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-upgrade-to-the-latest-software

**Comment by StefanMeGit** [comment]
Thats the funny thing, I already did it like in the description. I order a new SD Card before I make more tests about this. I ll give feedback as soon as possible

**Comment by StefanMeGit** [comment]
After a an complete new install of Octoprint, id worked on the third try...
