### ISSUE TITLE
Endstop phase calibration not available for stepper z1

### ISSUE THREAD

**Issue by bartolomeus** [KevinOConnor/klipper#3890]
I have a cartesian with dual independant z motors and want to use endstop phase calibration for z.
It works for the first motor: stepper_z
but it never shows the trigger phase for stepper_z1

This is the response I get:
12:20:30 $ ENDSTOP_PHASE_CALIBRATE
12:20:30 // stepper_x: trigger_phase=0/64 (range 0 to 1)
12:20:30 // stepper_y: trigger_phase=21/64 (range 21 to 22)
12:20:30 // stepper_z: trigger_phase=26/64 (range 5 to 29)
12:22:29 $ ENDSTOP_PHASE_CALIBRATE stepper=stepper_z
12:22:29 // stepper_z: trigger_phase=26/64 (range 5 to 29)
12:22:29 // The SAVE_CONFIG command will update the printer config file with these parameters and restart the printer.
12:22:23 $ ENDSTOP_PHASE_CALIBRATE stepper=stepper_z1
12:22:23 !! Stats not available for stepper stepper_z1

[klippy.log](https://github.com/KevinOConnor/klipper/files/5925386/klippy.log)

**Comment by KevinOConnor** [comment]
That is correct - the endstop_phases code does not support axes with multiple stepper.  An interested developer would need to extend the code in order for that to be supported.

-Kevin
