### ISSUE TITLE
pause_resume registers undocumented "CANCEL_PRINT" gcode

### ISSUE THREAD

**Issue by yschroeder** [KevinOConnor/klipper#3895]
According to the [documentation](https://www.klipper3d.org/G-Codes.html#pause-resume) the `[pause_resume]` registers 3 new gcodes. However in reality it also registers `CANCEL_PRINT`.

This caught me off-guard as I have my own `CANCEL_PRINT` defined, resulting in a weird error message about redefining the `CANCEL_PRINT` gcode.

Relevant line in source:
https://github.com/KevinOConnor/klipper/blob/a7b50b6002d2982c6b426f180a5f6bf9db976e1f/klippy/extras/pause_resume.py#L20

**Comment by yschroeder** [comment]
I think this issue should stay open, as I think it needs fixing.

**Comment by KevinOConnor** [comment]
This should be fixed with #4370.

-Kevin
