### ISSUE TITLE
Avoid Open Spaces toolpath problem

### ISSUE THREAD

**Issue by Deymos42** [KevinOConnor/klipper#3901]
Using simplify 3D we always try to keep select the options: "avoid crossing open sapces" & "only retract when crossing open spaces". When previewing the .gcode in simplify3D it is possible to observe that the toolpath is correct and the open spaces are avoid and hecne NO retract is activated. In the image the toolpath of the extruder is represented as red lines.

![image](https://user-images.githubusercontent.com/51133816/107156056-55b94b00-697c-11eb-950c-07e054d28e4c.png)

The problem ocurred when checking the real toolpath klipper was doing in the print, no open spaces where avoided and retract was not activated too (we think this is because in simplify 3D no retract commands were generated due to the "only retract when crossing open spaces" option) causing a lot of stringging in the piece. 

![WhatsApp Image 2021-02-07 at 19 28 19](https://user-images.githubusercontent.com/51133816/107156080-7681a080-697c-11eb-82cc-2a49c9ebbacf.jpeg)

Our question is the next: does klipper changes the toolpath to its own "optimal" criteria, ignoring the original toolpath generated by the slicer (in this case Simplify3D)? If the case, it is possible to alter it in order to avoid open spaces? It is possible to see a preview of the toolpath klipper will do in the print?

[klippy.log](https://github.com/KevinOConnor/klipper/files/5939724/klippy.log)

**Comment by Sineos** [comment]
It is not the job of the firmware to alter the tool-path. Rather to do everything possible to follow it as exactly as possible and Klipper really excels in this.
This is rather a S3D bug (which btw. is a slicer that is no longer maintained since Q1 2019). Analyse your gcode and check if there is really the commands that you would expect. You can also check https://gcode.ws/
