### ISSUE TITLE
Webcam does not work with start script under Mainsail

### ISSUE THREAD

**Issue by 3DFans** [KevinOConnor/klipper#3930]
Hey
I followed the following instructions, which also works so far, but if I add the script to start and then want to query "sudo service mainsail-stream start" and then query the status, an error occurs that it does not work. But if I call the script directly, it works.

`done
pi@raspberrypi:~ $ sudo chmod 755 /etc/init.d/mainsail-stream.sh
pi@raspberrypi:~ $ sudo update-rc.d mainsail-stream.sh defaults
pi@raspberrypi:~ $ sudo service mainsail-stream start
Job for mainsail-stream.service failed because the control process exited with error code.
See "systemctl status mainsail-stream.service" and "journalctl -xe" for details.
pi@raspberrypi:~ $ sudo service mainsail-stream status
● mainsail-stream.service
   Loaded: loaded (/etc/init.d/mainsail-stream.sh; generated)
   Active: failed (Result: exit-code) since Sun 2021-02-14 09:53:27 GMT; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4668 ExecStart=/etc/init.d/mainsail-stream.sh start (code=exited, status=2)

Feb 14 09:53:27 raspberrypi systemd[1]: Starting mainsail-stream.service...
Feb 14 09:53:27 raspberrypi mainsail-stream.sh[4668]: /etc/init.d/mainsail-stream.sh: 15: /etc/init.d/mainsail-stream.sh: Syntax err
Feb 14 09:53:27 raspberrypi systemd[1]: mainsail-stream.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 09:53:27 raspberrypi systemd[1]: mainsail-stream.service: Failed with result 'exit-code'.
Feb 14 09:53:27 raspberrypi systemd[1]: Failed to start mainsail-stream.service.
`

**Comment by Sugaroverdose** [comment]
Mainsail isn't part of klipper
https://github.com/meteyou/mainsail/issues
