### ISSUE TITLE
robin nano v3 serialport not working

### ISSUE THREAD

**Issue by b3sky** [KevinOConnor/klipper#3942]
marlin firmware serial works fine..

/dev/serial/by-id/usb-STMicroelectronics_GENERICSTM32F407VGT6_CDC_in_FS_Mode_397534873436-if00

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0483:5740 STMicroelectronics Virtual COM Port
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

after flash stm32f407 klipper firmware

ls /dev/serial/by-id/* 

can't find serialport

**Comment by mks-viva** [comment]
> marlin firmware serial works fine..
> 
> /dev/serial/by-id/usb-STMicroelectronics_GENERICSTM32F407VGT6_CDC_in_FS_Mode_397534873436-if00
> 
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 001 Device 003: ID 0483:5740 STMicroelectronics Virtual COM Port
> Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 
> after flash stm32f407 klipper firmware
> 
> ls /dev/serial/by-id/*
> 
> can't find serialport

You can try to restart putty.exe
