### ISSUE TITLE
Loosing steps when "Gap fill" 

### ISSUE THREAD

**Issue by szymongamza** [KevinOConnor/klipper#3951]
### Ohhh boy it was long way to find this bug...
So my printers constantly were losing steps in random places (I thought it was random...)
After many changes in my speeds, accelerations, hardware, I have decided to record part when It happens.

Then I was able to cut out part of gcode to be able to reproduce problem. I managed to find, that Gap fill movement is some specific (random?) places is loosing step for no reason (even with PA turned off).

### It was here:
![image](https://user-images.githubusercontent.com/40543244/108254747-b48c7a80-715b-11eb-88c5-03c65eeed397.png)
### And this white line look like this:
G1 X184.637 Y160.372
G1 F3000.000
G1 X184.621 Y160.232 E1.00527 ;this
G1 X184.624 Y160.012 E1.00979 ;this
G1 X184.627 Y159.792 E1.01568 ;this
G1 X184.630 Y159.572 E1.02294 ;this
G1 X184.633 Y159.352 E1.03157 ;this
G1 X184.612 Y159.001 E1.04662 ;this
G1 X184.605 Y157.532 E1.10948 ;this
G1 X184.629 Y157.007 E1.12206 ;this
G1 X184.599 Y156.592 E1.13202 ;this
G1 E0.63202 F6000.00000
G92 E0

### when I turn it into:
G1 X184.637 Y160.372
G1 F3000.000
;G1 X184.621 Y160.232 E1.00527 ;this
;G1 X184.624 Y160.012 E1.00979 ;this
;G1 X184.627 Y159.792 E1.01568 ;this
;G1 X184.630 Y159.572 E1.02294 ;this
;G1 X184.633 Y159.352 E1.03157 ;this
;G1 X184.612 Y159.001 E1.04662 ;this
;G1 X184.605 Y157.532 E1.10948 ;this
;G1 X184.629 Y157.007 E1.12206 ;this
G1 X184.599 Y156.592 E1.13202 ;this
G1 E0.63202 F6000.00000
G92 E0

### All worked well.

I know, that I can just turn off Gap fill, but it's not solution.

### My setttings:
Acceleration: 4000 mm/s^2
Accel to Decel: 2000 mm/s^2
Travel Speed: 600 mm/s
Speed of printing on this layer: 50 mm/s
Square Corner Velocity: 10 mm/s

### Gcode to reproduce:
[gcode to reproduce.zip](https://github.com/KevinOConnor/klipper/files/5998056/gcode.to.reproduce.zip)

Fake log:
[klippy.log](https://github.com/KevinOConnor/klipper/files/5998062/klippy.log)

**Comment by gandzia44** [comment]
### Update in case!
Increasing microsteps from 25 to 50 (weird stepper driver), fixed losing step on this gcode. I will try to reproduce case on other gcodes.

Maybe there was no enough resolution?

### Here is my part of config before:
[stepper_x]
step_pin: PE14
dir_pin: PA0
enable_pin: !PC3
microsteps: 25
rotation_distance: 60
endstop_pin: PB10
position_endstop: 0
position_max: 375
homing_speed: 50

[stepper_y]
step_pin: PE11
dir_pin: !PE8
enable_pin: !PD7
microsteps: 25
rotation_distance: 60
endstop_pin: PE12
position_endstop: 0
position_max: 310
homing_speed: 50

### After:

[stepper_x]
step_pin: PE14
dir_pin: PA0
enable_pin: !PC3
microsteps: 50
rotation_distance: 60
endstop_pin: PB10
position_endstop: 0
position_max: 375
homing_speed: 50

[stepper_y]
step_pin: PE11
dir_pin: !PE8
enable_pin: !PD7
microsteps: 50
rotation_distance: 60
endstop_pin: PE12
position_endstop: 0
position_max: 310
homing_speed: 50
