### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by bakaufman** [KevinOConnor/klipper#3967]
In "measuring resonances", please correct
```~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_20210219.csv -o /tmp/shaper_calibrate_x.png --max_smoothing=0.2```
to 
```~/klipper/scripts/calibrate_shaper.py /tmp/calibration_data_x_*.csv -o /tmp/shaper_calibrate_x.png --max_smoothing=0.2```

**Comment by dmbutyugin** [comment]
Hmm, I do not see the original line in https://github.com/KevinOConnor/klipper/blob/master/docs/Measuring_Resonances.md
