### ISSUE TITLE
Klippersreen sometimes does not display the current Print

### ISSUE THREAD

**Issue by jailbreaker07** [KevinOConnor/klipper#3978]
From time to time I have the problem that the Klipperscreen does not show the current print.  Even old baby steps or flow corrections are still there, as soon as something is changed, the values ​​are up to date again.  Is there a possibility to initialize or reload Klippersreen before printing?

**Comment by jakep82** [comment]
@jailbreaker07 Klipperscreen is a separate project.  If you have a problem with it, you need to open an issue for Klipperscreen, not Klipper.

https://github.com/jordanruthe/KlipperScreen/issues
