### ISSUE TITLE
G4 issue?

### ISSUE THREAD

**Issue by robustini** [KevinOConnor/klipper#4009]
I am trying to time the bed cooling using the G4 command.
Unfortunately, it seems to me that it doesn't work.
Here is an example, considering a bed temperature of 110° at the end of the print: 

M140 S90 ; bed temp at 90°
; G4 P180000 ; wait 180 seconds
G4 S180 ; wait 180 seconds
M140 S80
G4 S180
M140 S70
G4 S180
M140 S60
G4 S180
M140 S50
G4 S180
M140 S0 ; turn off bed

"S" should be a value in seconds and P in milliseconds.
Instead of running the g-code correctly Klipper when it executes this sequence immediately turns off the bed.
Where I'm wrong? Or is a Klipper issue?

**Comment by jakep82** [comment]
The docs only list support for the P variable. 

https://www.klipper3d.org/G-Codes.html

**Comment by robustini** [comment]
> 
> 
> The docs only list support for the P variable.
> 
> https://www.klipper3d.org/G-Codes.html

This is a problem, I'll try to solve it in another way.
