### ISSUE TITLE
SKR Mini V2.0 is not recognized

### ISSUE THREAD

**Issue by tobit6795** [KevinOConnor/klipper#4016]
So i flashed the SKR Mini v2.0 with latest Klipper build like this:

STM32F103 with a "28KiB bootloader". Also, select "Enable extra
low-level configuration options" and configure "GPIO pins to set at
micro-controller startup" to "!PA14".

Flash was done over SD card/firmware.bin file.

After plugin in the usb cable i got the following dmesg:

```
usb 1-1.2: new full-speed USB device number 6 using xhci_hcd
usb 1-1.2: device descriptor read/64, error -32
usb 1-1.2: device descriptor read/64, error -32
usb 1-1.2: new full-speed USB device number 7 using xhci_hcd
usb 1-1.2: device descriptor read/64, error -32
usb 1-1.2: device descriptor read/64, error -32
usb 1-1-port2: attempt power cycle
usb 1-1.2: new full-speed USB device number 8 using xhci_hcd
usb 1-1.2: Device not responding to setup address.
usb 1-1.2: Device not responding to setup address.
usb 1-1.2: device not accepting address 8, error -71
usb 1-1.2: new full-speed USB device number 9 using xhci_hcd
usb 1-1.2: Device not responding to setup address.
usb 1-1.2: Device not responding to setup address.
usb 1-1.2: device not accepting address 9, error -71
usb 1-1-port2: unable to enumerate USB device
```

I also reflashed BTT compiled version of Marlin for Ender 3 Pro. With that one i get the USB device without issues

```
hub 1-1:1.0: 4 ports detected
usb 1-1.2: new full-speed USB device number 3 using xhci_hcd
usb 1-1.2: New USB device found, idVendor=1eaf, idProduct=0004, bcdDevice= 2.00
usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-1.2: Product: Maple
usb 1-1.2: Manufacturer: LeafLabs
usb 1-1.3: new high-speed USB device number 4 using xhci_hcd
```

**Comment by tobit6795** [comment]
Soo, my second SKR Mini V2.0 just arrived. I've completely rebuild the image, flashed again over SD Card.
Same issue here, so i think it's an firmware related issue

**Comment by raymondh2** [comment]
Might be related to #3959 . This has been an issue I have seen a few times on the Voron Discord.

**Comment by amikhalev** [comment]
FWIW, I am running commit 1950380d6c90e57f6fa844f886d208e5391ede7b on an SKR Mini V2.0 right now and it works.

Did you set the USB vendor/product IDs in the menuconfig?

**Comment by tobit6795** [comment]
i retried everything on a clean system(freshly installed raspberry pi os) and with that image, everything worked. i dont now what caused this. I indeed cleared things up before every make (make clean / make distclean).
