### ISSUE TITLE
CoreXZ, Xgoes right direction, Z goes wrong

### ISSUE THREAD

**Issue by killgates1986** [KevinOConnor/klipper#4020]
Cant find the solution, X is homing right, but the Z axis goes wrong :/ 
Adding ! to step_dir of X or Z doesnt work. Switching wires also doesnt work.
[klippy.log](https://github.com/KevinOConnor/klipper/files/6093511/klippy.log)

**Comment by ShawnBuckley** [comment]
There might be other motor connection configurations to try, the voron discord has a great chart for figuring that out:
https://media.discordapp.net/attachments/741806179247980695/769705713306959903/SW-steppers.png

**Comment by killgates1986** [comment]
it worked! thx m8!
