### ISSUE TITLE
klipper_pru starting before PRU is initialized

### ISSUE THREAD

**Issue by jakep82** [KevinOConnor/klipper#4043]
I'm not familiar enough with sysvinit and systemd to know exactly why this happens, but klipper_pru fails to start during a system boot because the PRU isn't available yet.  @goeland86 found this was fixed by removing the klipper_pru start script from rc.d defaults, and instead calling this script from a service file that doesn't start until /dev/remoteproc exists.  I managed to hack my way into a set of working path and service files, but I'm hoping someone more knowledgeable can create proper files and an update to the install-beaglebone.sh script.  I'm now successfully running Klipper with a Replicape on Debian 10 and a 4.19 kernel, and this appears to be the last remaining Klipper related bug to make everything work.

**Comment by goeland86** [comment]
I'm sorry I haven't had time to jump in on this. I'm struggling to keep up with work right now, and I'll try to get to it as soon as I have a bit of a breather.
