### ISSUE TITLE
[support or FR] z_endstop offset measure with detachable probe

### ISSUE THREAD

**Issue by robvoi** [KevinOConnor/klipper#4049]
Hey. I hope someone can help me out here.
I use a detachable probe for tilt calibration and bed mesh (setting bed center to 0).
Is there way to set the z_endstop offset with it? The distance z_endstop to probe is fixed. So it should be possible to calculate the current distance between bed and probe.
What is a good way to do this?

**Comment by robvoi** [comment]
Dear Bot.
I fully get that Discord should be used. Didn't get an answer there though. That's why I tried here.
Very good software - so thanks in any case. :-)

**Comment by KevinOConnor** [comment]
Alas, I don't know the answers to your questions - you'll likely need to implement it and tell us about it.

-Kevin
