### ISSUE TITLE
Consistent MCU 'mcu' shutdown: Stepper too far in past on SKR v1.4 Turbo with specific GCode

### ISSUE THREAD

**Issue by janvorli** [KevinOConnor/klipper#4061]
I have a GCode file that always causes my Anycubic Kossel Linear Plus with SKR V1.4 Turbo board to crash with this error. I haven't hit this issue with other prints before over the last few months. I have updated to the latest klipper firmware today and the issue persists.
I am attaching the klippy.log file and also the GCode file that causes the problem. It happens early in the file, it basically just prints one line and crashes.

It looks like in the following part of the gcode, the first G1 command draws the line that is visible and the second G1 results in the crash without moving the head anywhere:
```gcode
;LAYER:1
M117 INDICATOR-Layer1
G1 Y-40.000000 Z0.200000 E6.539222
G91
G1 X-8.000000 
```
[1002_GemBird_PLA_white_T03_V01.zip](https://github.com/KevinOConnor/klipper/files/6152978/1002_GemBird_PLA_white_T03_V01.zip)
[klippy.log](https://github.com/KevinOConnor/klipper/files/6152968/klippy.log)

It would be great to get some guidance on how to figure out what's in that GCode is triggering the problem. I can try to debug it myself, I am experienced in C++ programming and also have some basic knowledge of Python. But I have no idea where to start.

**Comment by KevinOConnor** [comment]
FWIW, as the error message should have indicated, you're requesting too many steps per second.  It looks to be your extruder, and it looks like you've turned off the extruder safety checks (that would have warned you about excessive extruder movement).  Note that, regardless of mcu processing power, it's not possible to exceed ~200K steps/s with the default stepper pulse width length of 2us.

-Kevin
