### ISSUE TITLE
Ender 3 V2 serial connection issue 

### ISSUE THREAD

**Issue by GwnXander** [KevinOConnor/klipper#4073]
Dear Kevin,

We try to install klipper on a Ender 3 V2 with a generic-creality-v4.2.7.cfg motherboard

In the make menuconfig we set

Uncheck Enable extra low-level configuration options.
Set processor architecture to STMicroelectronics STM32.
Set processor model to STM32F103.
Set bootloader offset to 28KiB bootloader.

but we cannot connect with octoprint to the printer 

Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer
Klipper state: Not ready

Closing serial port due to emergency stop M112.
Recv: // Shutdown due to M112 command
Connection closed, closing down monitor
Changing monitoring state from "Operational" to "Offline (Error: Closing serial port due to emergency stop M112.)"
Changing monitoring state from "Offline" to "Opening serial connection"
Connecting to port /tmp/printer, baudrate 250000
Changing monitoring state from "Opening serial connection" to "Connecting"
Connected to: Serial<id=0x676557b0, open=True>(port='/tmp/printer', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor

In the klippy.log file

Starting serial connect
Timeout on connect
Wait for identify_response
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 65, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/home/pi/klipper/klippy/serialhdl.py", line 249, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 306, in get_response
    cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 241, in raw_send_wait_ack
    raise error("Serial connection closed")
error: Serial connection closed

[klippy.log](https://github.com/KevinOConnor/klipper/files/6167253/klippy.log)

Thank you very much !

Kind Regards,

Xander & Dirk

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/blob/master/config/printer-creality-ender3-v2-2020.cfg#L1-L4
