### ISSUE TITLE
Klipper board

### ISSUE THREAD

**Issue by martin5256** [KevinOConnor/klipper#408]
Hello there Kevin i would like to propose a idea to you about a board tailored to klippers features 
if you are interested please message me martin525622@gmail.com 

I hope we can have a chat 

thanks :)

**Comment by KevinOConnor** [comment]
Hi Martin,

We chatted about this a few days ago on IRC.  I'm not that knowledgeable about board design, so I'm not sure there is much I can contribute.

Cheers,
-Kevin
