### ISSUE TITLE
Klipper wont connect to my skr 1.4 turbo

### ISSUE THREAD

**Issue by mklsmusam** [KevinOConnor/klipper#4090]
Hey, so I'm moving from Marlin to Klipper, I followed this tutorial :https://www.youtube.com/watch?v=AtW3GqkKUz8&t=
I'm installing it on ender 3 pro with Skr 1.4 turbo with tmc2209 and Raspberry Pi Zero W using serial.
I connected the raspi to skr via 4 pins, RX to tx, tx to RX, gnd to gnd, 5v to 5v like on this photo-
![image](https://user-images.githubusercontent.com/50438823/111919288-9206bd80-8a89-11eb-99d0-20accc27b324.png)

I followed every step in the tutorial:
1. Swapping ports used by GPIO and Bluetooth
sudo nano /boot/config.txt
Move the cursor to the very end and add:
dtoverlay=pi3-miniuart-bt

2. Disabling the serial console
sudo nano /boot/cmdline.txt
Look for following string (text) and delete it
console=serial0,115200

3. Raspi-config stuff
sudo raspi-config
Go to 'Interfacing Options'
Then P6 - Serial
Then No
Then Yes
Then go down to finish and reboot.

4. Rebuild your Klipper MCU firmware, unselecting "Use USB for communication (instead of serial). Flash updated firmware to your board

5. Update your printer.cfg:
serial: /dev/ttyAMA0

As the printer.cfg I used this config file- https://github.com/KevinOConnor/klipper/blob/master/config/generic-bigtreetech-skr-v1.4.cfg

All Im getting is this : 
![image](https://user-images.githubusercontent.com/50438823/111919342-d2fed200-8a89-11eb-8675-cd67002ddfbd.png)

Thanks, Sam

**Comment by Talha909** [comment]
> Hey, so I'm moving from Marlin to Klipper, I followed this tutorial :https://www.youtube.com/watch?v=AtW3GqkKUz8&t=
> I'm installing it on ender 3 pro with Skr 1.4 turbo with tmc2209 and Raspberry Pi Zero W using serial.
> I connected the raspi to skr via 4 pins, RX to tx, tx to RX, gnd to gnd, 5v to 5v like on this photo-
> ![image](https://user-images.githubusercontent.com/50438823/111919288-9206bd80-8a89-11eb-99d0-20accc27b324.png)
> 
> I followed every step in the tutorial:
> 
> 1. Swapping ports used by GPIO and Bluetooth
>    sudo nano /boot/config.txt
>    Move the cursor to the very end and add:
>    dtoverlay=pi3-miniuart-bt
> 2. Disabling the serial console
>    sudo nano /boot/cmdline.txt
>    Look for following string (text) and delete it
>    console=serial0,115200
> 3. Raspi-config stuff
>    sudo raspi-config
>    Go to 'Interfacing Options'
>    Then P6 - Serial
>    Then No
>    Then Yes
>    Then go down to finish and reboot.
> 4. Rebuild your Klipper MCU firmware, unselecting "Use USB for communication (instead of serial). Flash updated firmware to your board
> 5. Update your printer.cfg:
>    serial: /dev/ttyAMA0
> 
> As the printer.cfg I used this config file- https://github.com/KevinOConnor/klipper/blob/master/config/generic-bigtreetech-skr-v1.4.cfg
> 
> All Im getting is this :
> ![image](https://user-images.githubusercontent.com/50438823/111919342-d2fed200-8a89-11eb-8675-cd67002ddfbd.png)
> 
> Thanks, Sam

Did you find the solution. I am also got the same error. Did you find the solution.
