### ISSUE TITLE
GitHub sponsoring

### ISSUE THREAD

**Issue by dabde** [KevinOConnor/klipper#4093]
Hi,

a more general question to @KevinOConnor. Want to sponsor you with GitHub sponsoring. Or other way you prefer for your work. But could not find any information for this in your repo or webpage.

thanks

**Comment by theopensourcerer** [comment]
https://www.klipper3d.org/FAQ.html#how-can-i-donate-to-the-project

**Comment by dabde** [comment]
Ahhh okay, thx.
