### ISSUE TITLE
Z Offset question

### ISSUE THREAD

**Issue by ich777** [KevinOConnor/klipper#41]
Hello!
I'm currently using Marlin 1.1.6 with a RAMPS 1.4.2 and ABL Z Probe.
Is klipper currently able to set a Z Offset for the sensor (i've got no Endstop for the Z axis and if i can set an offset it would be possible to level the bed manually an try the firmware)?
I really would like to klipper but i haven't found any information about that.
Can clipper run on x86_64 hardware, for my Ocotprint host i'm running a Gigabyte Brix with an Intel Core i3.
Regards

**Comment by KevinOConnor** [comment]
Alas, Klipper does not currently have support for Z probes nor auto bed leveling.  It's on the TODO list.  I've recently assembled a delta printer that has a Z probe, so I plan to look at it in the near future.  However, I do not have an ETA for when support will be added.

It is possible to run the host software on a machine other than a Raspberry Pi.  However, to do so would require a Linux machine and Linux admin knowledge to translate the actions taken in scripts/install-octopi.sh to equivalent commands on the Linux distribution in use.

I'm going to close this issue as the Z probe support already has issue #9 and issue #19 open.

**Comment by ich777** [comment]
Thank you for your quick answer!

No i dont mean the automatic bed leveling i mean the z offset. Because i have no z endstop i want to know if its possible to set a z offset so that the sensor can do its job and act as a z endstop and not for bed leveleing or something else. I think many people has such a sensor and it would be cool if you implement a z offset first bevore you add a bed leveling process to test your firmware.

The intel machine that im running is an commandline only ubuntu machine. So if i understand it rigt it is possible to run your firmware on a amd86_64 host.

**Comment by KevinOConnor** [comment]
On Tue, Nov 07, 2017 at 11:14:13PM +0000, ich777 wrote:
> Thank you for your quick answer!
> 
> No i dont mean the automatic bed leveling i mean the z
> offset. Because i have no z endstop i want to know if its possible
> to set a z offset so that the sensor can do its job and act as a z
> endstop and not for bed leveleing or something else. I think many
> people has such a sensor and it would be cool if you implement a z
> offset first bevore you add a bed leveling process to test your
> firmware.

In that case, you should be able to define the pin attached to the
z-probe as the stepper_z.endstop_pin.  The z-offset is then the
endstop_position.  So, for example, if your z probe triggers when the
nozzle is 3mm away from the bed then you'd set the endstop_position to
3.

> The intel machine that im running is an commandline only ubuntu
> machine. So if i understand it rigt it is possible to run your
> firmware on a amd86_64 host.

Yes - walk through the steps in scripts/install-octopi.sh.  Ubuntu may
be close enough to the Raspbian distro that you can just run the
script - I'm not sure - but let me know if it works.

-Kevin

**Comment by andremariz** [comment]
Sorry to revive this post as i've seen the ner klipper version supports ABL. Ive read it but cant understand how to make it work.
I have to substitute the z part in printer.cfg with the code in config-extras?
