### ISSUE TITLE
Erroneous bltouch error message on shutdown due to other fault

### ISSUE THREAD

**Issue by h3po** [KevinOConnor/klipper#4105]
My mcu (SKR 1.3) was shutting down due to a misconfiguration of the E0 thermistor, leading to a shutdown with the last logged error message being "BLTouch raise probe error: BLTouch failed to raise probe", because of how the regex octoprint works the displayed message was "Failed to verify BLTouch probe is raised; retrying".
The error handling in [bltouch.py](https://github.com/KevinOConnor/klipper/blob/afe853aecc2bd5c6875cc7f4cc6da4e919d8e4a8/klippy/extras/bltouch.py#L125) should test wether the mcu is online.
I'll have to read and understand more of the code to be able to fix it myself, so I'm filing this here in the meantime.

    [...]
    Receive: 93 1453.790294 1453.781055 8: seq: 1d, tmcuart_response oid=4 read=''
    Receive: 94 1453.806700 1453.792137 18: seq: 1e, tmcuart_response oid=4 read='\n\xfaO \x80\x00\x02(\xa2\xfe'
    Receive: 95 1453.818823 1453.809599 8: seq: 1f, tmcuart_response oid=4 read=''
    Receive: 96 1453.835117 1453.820553 18: seq: 10, tmcuart_response oid=4 read='\n\xfaO \x80\x00\x02H\xa2\xd9'
    Receive: 97 1453.848738 1453.848409 11: seq: 11, clock clock=360960814
    Receive: 98 1454.349255 1453.848409 14: seq: 11, thermocouple_result oid=11 next_clock=441000000 value=0 fault=0
    Receive: 99 1454.349854 1453.848409 12: seq: 11, shutdown clock=411012131 static_string_id=Thermocouple ADC out of range
    Transition to shutdown state: MCU 'mcu' shutdown: Thermocouple ADC out of range
    Reactor garbage collection: (1452.070933769, 0.0, 0.0)
    Failed to verify BLTouch probe is raised; retrying.
    Failed to verify BLTouch probe is raised; retrying.
    BLTouch raise probe error: BLTouch failed to raise probe

**Comment by KevinOConnor** [comment]
You'll need to attach the full Klipper log file if you think there is an issue in the code: https://www.klipper3d.org/Contact.html
