### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Bensal1999** [KevinOConnor/klipper#4106]
Dear Kevin
I have done so many times in so many ways the installation and every time I get this massage:
![error](https://user-images.githubusercontent.com/81255199/112533968-d3111180-8daa-11eb-8bee-3515d116fa2d.png)

Everything works perfekt i can controll the printer via webinterface until I add this [t5uid1]
firmware: dgus_reloaded to  the printer.cfg. This is wy I think there is an issue. I have flashed the screen firmware and the klipper Logo is shown. 
Maybe you could help me I would really appreciated that I am about to give up...

**Comment by jakep82** [comment]
This screen is not supported by Klipper.  If you have an issue, you need to report it to the person that forked Klipper at https://github.com/Desuuuu/klipper
