### ISSUE TITLE
Klipper wont install

### ISSUE THREAD

**Issue by youngster30uk** [KevinOConnor/klipper#4108]
###### Installing packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libusb-1.0-0' for regex 'libusb-1.0'
Note, selecting 'libusb-1.0-0-dev' for regex 'libusb-1.0'
Note, selecting 'libusb-1.0-doc' for regex 'libusb-1.0'
build-essential is already the newest version (12.6).
libffi-dev is already the newest version (3.2.1-9).
libusb-1.0-0 is already the newest version (2:1.0.22-2).
libusb-1.0-0 set to manually installed.
The following additional packages will be installed:
  libftdi1 libhidapi-libusb0 libnewlib-dev libpython-dev libpython2-dev libpython2.7 libpython2.7-dev libstdc++-arm-none-eabi-newlib python2-dev python2.7-dev
Suggested packages:
  dfu-programmer avrdude-doc gcc-doc ncurses-doc libnewlib-doc
The following NEW packages will be installed:
  avr-libc avrdude binutils-arm-none-eabi binutils-avr dfu-util gcc-arm-none-eabi gcc-avr libftdi1 libhidapi-libusb0 libncurses-dev libnewlib-arm-none-eabi libnewlib-dev libpython-dev
  libpython2-dev libpython2.7 libpython2.7-dev libstdc++-arm-none-eabi-newlib libusb-1.0-0-dev libusb-1.0-doc libusb-dev python-dev python2-dev python2.7-dev stm32flash virtualenv
0 upgraded, 25 newly installed, 0 to remove and 70 not upgraded.
Need to get 222 MB of archives.
After this operation, 1,905 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf avrdude armhf 6.3-20171130+svn1429-2+rpt1 [284 kB]
Err:2 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf binutils-avr armhf 2.26.20160125+Atmel3.6.1-4
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:3 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf gcc-avr armhf 1:5.4.0+Atmel3.6.1-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:4 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf avr-libc all 1:2.0.0+Atmel3.6.1-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:5 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libftdi1 armhf 0.20-4
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:6 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libhidapi-libusb0 armhf 0.8.0~rc1+git20140818.d17db57+dfsg-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:7 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf binutils-arm-none-eabi armhf 2.31.1-11+rpi1+11
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:8 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf gcc-arm-none-eabi armhf 15:7-2018-q2-6
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:9 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libncurses-dev armhf 6.1+20181013-2+deb10u2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:10 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libnewlib-dev all 3.1.0.20181231-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:11 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libnewlib-arm-none-eabi all 3.1.0.20181231-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:12 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libpython2.7 armhf 2.7.16-2+deb10u1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:13 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libpython2.7-dev armhf 2.7.16-2+deb10u1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:14 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libpython2-dev armhf 2.7.16-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:15 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libpython-dev armhf 2.7.16-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:16 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libstdc++-arm-none-eabi-newlib all 15:7-2018-q2-5+12
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:17 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libusb-1.0-0-dev armhf 2:1.0.22-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:18 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libusb-1.0-doc all 2:1.0.22-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:19 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf libusb-dev armhf 2:0.1.12-32
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:20 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf python2.7-dev armhf 2.7.16-2+deb10u1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Get:21 http://raspbian.raspberrypi.org/raspbian buster/main armhf python2-dev armhf 2.7.16-1 [1,216 B]
Get:22 http://raspbian.raspberrypi.org/raspbian buster/main armhf python-dev armhf 2.7.16-1 [1,192 B]
Err:23 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf virtualenv all 15.1.0+ds-2
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:24 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf dfu-util armhf 0.9-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Err:25 http://mirror1.ku.ac.th/raspbian/raspbian buster/main armhf stm32flash armhf 0.5-1
  404  Not Found [IP: 2406:3100:1010:c02::211 80]
Fetched 286 kB in 12s (24.5 kB/s)
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/b/binutils-avr/binutils-avr_2.26.20160125+Atmel3.6.1-4_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/g/gcc-avr/gcc-avr_5.4.0+Atmel3.6.1-2_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/a/avr-libc/avr-libc_2.0.0+Atmel3.6.1-2_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/libf/libftdi/libftdi1_0.20-4_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/h/hidapi/libhidapi-libusb0_0.8.0~rc1+git20140818.d17db57+dfsg-2_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/b/binutils-arm-none-eabi/binutils-arm-none-eabi_2.31.1-11+rpi1+11_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/g/gcc-arm-none-eabi/gcc-arm-none-eabi_7-2018-q2-6_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/n/ncurses/libncurses-dev_6.1+20181013-2+deb10u2_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/n/newlib/libnewlib-dev_3.1.0.20181231-1_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/n/newlib/libnewlib-arm-none-eabi_3.1.0.20181231-1_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python2.7/libpython2.7_2.7.16-2+deb10u1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python2.7/libpython2.7-dev_2.7.16-2+deb10u1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python-defaults/libpython2-dev_2.7.16-1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python-defaults/libpython-dev_2.7.16-1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/libs/libstdc++-arm-none-eabi/libstdc++-arm-none-eabi-newlib_7-2018-q2-5+12_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/libu/libusb-1.0/libusb-1.0-0-dev_1.0.22-2_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/libu/libusb-1.0/libusb-1.0-doc_1.0.22-2_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/libu/libusb/libusb-dev_0.1.12-32_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python2.7/python2.7-dev_2.7.16-2+deb10u1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/p/python-virtualenv/virtualenv_15.1.0+ds-2_all.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/d/dfu-util/dfu-util_0.9-1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Failed to fetch http://mirror1.ku.ac.th/raspbian/raspbian/pool/main/s/stm32flash/stm32flash_0.5-1_armhf.deb  404  Not Found [IP: 2406:3100:1010:c02::211 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

how do I resolve this? I have installed klipper before, but now it is not working for me

**Comment by TazerReloaded** [comment]
Seems like your raspbian mirror is down. Try to comment everything except `deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi` in your `/etc/apt/sources.list`.
This is an OS configuration issue and has nothing to do with Klipper.
