### ISSUE TITLE
[minor] Accept non case sensitive command

### ISSUE THREAD

**Issue by tarsonis123** [KevinOConnor/klipper#4111]
Using macros a lot like most folks do I guess. The OctoKlipper plugin isn't convenient for PID tuning so I use the OP macro plugin for PID with save_config command. However the macro plugin converts any commands to upper case. Same goes for OctoApp which converts to upper case too.  But for some reason I can't imaging Klipper seems to make a difference between upper and lower case.

Send: PID_CALIBRATE HEATER=HEATER_BED TARGET=60
Recv: !! Unknown heater 'HEATER_BED'

Sure because it is heater_bed. Klipper expects **heater_bed**.  Same for **extruder** which is then unknown as **EXTRUDER**.

The PID works. Its a minor workflow related issue but would be nice if this would be solved. Greetings

**Comment by BlackStump** [comment]
Maybe it is time to try a Klipper specific frontend like 
[Mainsail](https://github.com/meteyou/mainsail)
or
[Fluidd](https://github.com/cadriel/fluidd/tree/master)
