### ISSUE TITLE
Get MCU shutdown error in last 3 consecutive print

### ISSUE THREAD

**Issue by jonathanoeijoeng** [KevinOConnor/klipper#4115]
Hi,

I got error MCU shutdown in my last 3 consecutive print on the same gcode file. I have printed this file many time before without any problem.
This is 3.5 hours printing and got MCU shutdown error in around 30 mins before completed time.
I use Ender 3 v2 with 4.2.2 stock mainboard. 

Thanks

![image](https://user-images.githubusercontent.com/7046560/112739247-e1268400-8f9c-11eb-9fb0-ebaed2e477b8.png)

[klippy.txt](https://github.com/KevinOConnor/klipper/files/6216686/klippy.txt)

**Comment by Gilabite** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#help-it-doesnt-work

**Comment by KevinOConnor** [comment]
FWIW, you should read the FAQ entry on this: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin
