### ISSUE TITLE
Extruder skipping if try to extrude or retract more than 20mm

### ISSUE THREAD

**Issue by dragonisko** [KevinOConnor/klipper#4116]
As in discription. i cant extract or retract more than 20mm, extruder starting skipping after that.

i can extrude 20mm and it will start skipping if will try extract more, can retract 20mm without restarting klipper of printer, can repeat that as many time without problems, it will start skipping if i will try extrude or retract more than 20mm (in one go or 2x10)

[klippy (2).log](https://github.com/KevinOConnor/klipper/files/6216716/klippy.2.log)

**Comment by Gilabite** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#help-it-doesnt-work

**Comment by dragonisko** [comment]
it was grinded gear on bmg
