### ISSUE TITLE
Rotary Delta, Printing behaviour / Kinematic

### ISSUE THREAD

**Issue by Egris89** [KevinOConnor/klipper#4120]
Hello,

i am using a Rotary Delta Printer with a Duet2 Board. I wanted to try out Klipper and converted my machine from RRF to Klipper.
I´m very imprest at the moment but i run into a strange printing behavoir. I double checked my printer-Config settings but i have right now no clue what is causing this problem.

My Problem:
[Conifg.zip](https://github.com/KevinOConnor/klipper/files/6217187/Conifg.zip)

When Im printing a part there are recurring sections in the print where it looks like the kinematic has changed somehow...
This is happining in X & Y Plane at the same time. I first noticed it while printing the Input-Shaper-Tuning STL.

![Input_Shaper_Print](https://user-images.githubusercontent.com/81512761/112750082-ab969080-8fc6-11eb-82a4-b34cb06b5192.jpg)

I printed a Benchy and there the Effect is even stronger visible. (The fully printed Benchy is made with RRF)

![Benchy_Klipper](https://user-images.githubusercontent.com/81512761/112750084-af2a1780-8fc6-11eb-9e96-4cd7b77387f7.jpg)

At the momet i have no clue what is causing this.
Thank you very much for any help.

Best regards

**Comment by KevinOConnor** [comment]
Sorry, but we don't use github to diagnose printer issues.  That said, your print defects are common with the "watermark" (aka bang bang) bed heater - you should tune and enable the PID heater for your bed.

We don't get a lot of rotary delta users, so your feedback would be welcome.  I recommend using the Klipper Discourse server for that: https://www.klipper3d.org/Contact.html

-Kevin
