### ISSUE TITLE
Internal error on command:"G1"

### ISSUE THREAD

**Issue by clsferguson** [KevinOConnor/klipper#4122]
[klippy.zip](https://github.com/KevinOConnor/klipper/files/6218601/klippy.zip)

Strange error, found the same issue on a google search of the error. The issue was resolved in a bugfix i think i understood. But it appears to be in my klippy.log

I'm going to reboot my printer and run the same print and see if it happens again. But i thought you may like to take a look.

**Comment by jakep82** [comment]
You're running a version of Klipper that's more than 4 months old.  You should update Klipper before attempting the print again.

**Comment by clsferguson** [comment]
I will look into updating. It hasn’t been causing much grief, just this one time.

For what its worth, I turned off my printer and turned it back on and ran the same gcode file. It is almost done now.

**Comment by KevinOConnor** [comment]
As discussed in #4097, a change was made today for a similar issue.  I recommend updating to the very latest version of the code.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this in favor of the existing #4097 .

-Kevin
