### ISSUE TITLE
Missing printer. endpoints for Filament motion sensor

### ISSUE THREAD

**Issue by zellneralex** [KevinOConnor/klipper#4126]
I am not sure if this is a bug report or a feature request, so I let Kevin decide ...

Installing a Filament motion sensor I found out that the following printer. endpoints are missing. As it uses the same GCodes I was expecting that it would use similar printer. variables like:

printer["filament_motion_sensor <config_name>"].enabled
printer["filament_motion_sensor <config_name>"].filament_detected 

in the same way as its already defined for:

printer["filament_switch_sensor <config_name>"].enabled: Returns True if the switch sensor is currently enabled.
printer["filament_switch_sensor <config_name>"].filament_detected: Returns True if the sensor is in a triggered state.

**Comment by Arksine** [comment]
The module needs a `get_status()` method.  The contributor said he was going to look into it.
