### ISSUE TITLE
Need help using serial instead of USB

### ISSUE THREAD

**Issue by chrstrvs** [KevinOConnor/klipper#4127]
Hi!

I'm using a SKR Pro board and I'm trying to use serial instead of USB to communicate between the Pi and the SKR board.
When I was running Marlin this was working without any issues, so I'm sure that my cable is working and that it's connected to the correct pins on the Pi (but I double checked anyway).
I have connected the cable to UART 3 on the SKR board.
I have edited the "make menuconfig" to use serial instead of USB and flashed it to the SKR board. I also made sure that the firmware was really flashed.
In the config I have changed the serial to /dev/ttyAMA0.
In Octoprint I have changed the serial port to /dev/ttyAMA0.

When I connect in Octoprint I get a message saying "Connected to host via **/tmp/printer** @250000bps".
When I request status I get "Printer is not ready
The klippy host software is attempting to connect. Please
retry in a few moments.
Klipper state: Not ready".

I'm not really sure what I have done wrong. Is not UART3 the correct serial to use on the SKR board? Have I missed a step?

Thanks in advance!

Regards,
Christian
[klippy.log](https://github.com/KevinOConnor/klipper/files/6230643/klippy.log)

**Comment by lowtolerance** [comment]
Regardless of how you are actually handling communication between klipper and mcu, Octoprint should be configured to connect to the serial device located at /tmp/printer. By setting Octoprint to connect to the printer’s serial port directly, you bypass klipper entirely and connect to a firmware that’s incompatible with being controlled directly by Octoprint.
