### ISSUE TITLE
BLTouch Incorrect X-Offset Calculation causing bed_mesh probes to be offset to the left

### ISSUE THREAD

**Issue by davidswart** [KevinOConnor/klipper#4140]
Using Klipper on en Ender 3 V2 with a BLTouch v3.1 and the swiss-micro direct drive with the printed fan shroud as per https://store.micro-swiss.com/products/micro-swiss-direct-drive-extruder. the x-offset calculation seems to be incorrectly calculated such that when you get it to work, the mesh is skewed to the left. It would seem that the distance between each probe point on the x-axis is calculated incorrectly.

For example, using the following BLTouch and bed mesh settings:

[bltouch]
sensor_pin: ^PB1
control_pin: PB0
x_offset: -45.15
y_offset: -8.28
z_offset:2.56
speed: 5.0
samples: 2
#X-45.15 Y-8.28 Z-2.40 -- For current Fan Shroud
pin_up_touch_mode_reports_triggered: False
probe_with_touch_mode: True

[bed_mesh]
speed: 120
horizontal_move_z: 5
mesh_min: 20,20
mesh_max: 184.85,220
probe_count: 5,5

the mesh min start the BLTouch of in the right place, but the mesh_max values (184.85) is the max_value - "x-offset", the offset should not have to be used, just the mesh_max value as specified. Using a mesh_max=220,220 causes the following errors:

Move out of range: 265.150 28.280 5.000 [0.000]

So, the minimum X value for the mesh_max that you can get away with seems to be the   mesh_max - (mesh_min + x_offset). The y_offset calculation does not seem to suffer from this issue.

I am not sure if this is done by design to perhaps prevent the extruder from crashing into the right-side gantry of the printer. It would be nice to allow the user to determine the intended mesh_max or at least specify the distance between probes?

**Comment by Arksine** [comment]
You can not specify a `mesh_min` or a `mesh_max` that is unreachable.  Setting a `mesh_max` of X=220 requires that the tool move to X=265.15 to probe that area.  This is unreachable on your printer, thus you get an error.  This restriction applies to both axes, it isn't possible to probe a mesh that the tool cannot reach.  If you want a mesh that large you will have to use manual probing.
