### ISSUE TITLE
Message Bombs on error

### ISSUE THREAD

**Issue by EddieGreen** [KevinOConnor/klipper#4152]
Details in previously submitted ticket

https://github.com/KevinOConnor/klipper/issues/4151#issue-854370787

[klippy.log](https://github.com/KevinOConnor/klipper/files/6287005/klippy.log)

**Comment by KevinOConnor** [comment]
As mentioned in the previous ticket, we choose not to use github for support.  Please delete this ticket and refrain from opening new tickets.

-Kevin

**Comment by EddieGreen** [comment]
So, is this a bug or normal behaviour?

I don't know why you choose to respond this way. Please explain why

I've read other issues and the ticket protocol and all I've done is provide detail on two issues that warrant the same kind of responses as other posts. I don't need you to resolve my issues with the amps or sensors, just clear down the ticket(s) with a meaningful response.

**Comment by KevinOConnor** [comment]
I don't know.  We don't use github as tool to find out.

-Kevin
