### ISSUE TITLE
No diagnostic information on errors

### ISSUE THREAD

**Issue by EddieGreen** [KevinOConnor/klipper#4153]
Details in previously submitted ticket

https://github.com/KevinOConnor/klipper/issues/4151#issue-854370787

[klippy.log](https://github.com/KevinOConnor/klipper/files/6287014/klippy.log)

**Comment by wesk-ms** [comment]
In January, the decision was made to not use Github for support requests.  The tickets you have opened are clearly requests for help with troubleshooting an issue with your printer.  The contact document has the links to the Discord and Discourse sites where you can get help and support for Klipper.
