### ISSUE TITLE
Limiting BED power

### ISSUE THREAD

**Issue by AndrezinhoCosta** [KevinOConnor/klipper#4159]
Tenho uma Tevo Tarantula modificada. Placa SKR 1.4Turbo, motores S42B em X e Y, dual Z, Direct Drive com BMG Titan, entre outras coisas. Uma delas foi pra solucionar aquele eterno problema de aquecimento da mesa da Tarantula: é uma mesa de 24V que está ligada através de um SSR de 25A diretamente em 110V. 
No Marlin eu pude reduzir o MAX_BED_POWER para 50 (cerca de 20% da potencia máxima - 255) e a mesa funcionou perfeitamente bem.
Qual parâmetro preciso mudar no Klipper para limitar a potencia de aquecimento da mesa?

I have a modified Tevo Tarantula. SKR 1.4Turbo board, S42B engines in X and Y, dual Z, Direct Drive with BMG Titan, among other things. One of them was to solve that eternal heating problem of the Tarantula bed: it is a 24V table that is connected via a 25A SSR directly at 110V.
In Marlin I was able to reduce the MAX_BED_POWER to 50 (about 20% of the maximum power - 255) and the bed worked perfectly well.
Which parameter do I need to change in Klipper to limit the heating power of the bed?

**Comment by zellneralex** [comment]
No support in github but you need to set 

#max_power: 1.0
#   The maximum power (expressed as a value from 0.0 to 1.0) that the
#   heater_pin may be set to. The value 1.0 allows the pin to be set
#   fully enabled for extended periods, while a value of 0.5 would
#   allow the pin to be enabled for no more than half the time. This
#   setting may be used to limit the total power output (over extended
#   periods) to the heater. The default is 1.0.

In your [heater_bed] section
