### ISSUE TITLE
When doing bed mesh, the mesh is floating far above Z=0 

### ISSUE THREAD

**Issue by nirurin** [KevinOConnor/klipper#4177]
https://imgur.com/a/WS28yPO  = picture of the problem
https://pastebin.com/SR36KiRW = my current config

Ender 5 Plus, with SKR 1.4Turbo and a bltouch v3.1 as my endstop using the Probe pins. 

I've tried a lot to fix this, and the klipper discord and the creality discord are both baffled by it. 

The issue becomes a real problem, because after a bed mesh if I do a G1 Z0 the nozzle will end up about 1.2mm above the print bed (that's including my offset, without my offset it would be at about 2.5mm above the print bed) meaning it prints in mid air. 

The only 'solution' I've found, is by adding the 'relative_reference_index' line to the bed mesh, and pick the most central point I can. This puts the graph fairly near the middle where it should be, and the nozzle ends up only 0.05 away from where it should be (which is easier to deal with). However I don't yet know if this is going to be consistent, or if it will change each time and need constant offset changing. 

I also know (according to the documentation for klipper) that THIS SHOULD NOT WORK, as the relative referencing is for people who use a z-endstop and just use the bltouch for probing. My bltouch IS my endstop. 

Edit/Update: Relative reference ends up with a central point that pinches the paper (if I set the right offset) however if I move the nozzle to other parts of the bed it's not as accurate, usually about 0.1-0.2mm off the paper. So the bed mesh doesn't seem to be working correctly even with the relative reference (though it does at least show the visualiser in the middle, instead of way up off the top of the axis)

**Comment by KevinOConnor** [comment]
Sorry, but we don't use github to troubleshoot issues like this.  If you couldn't get a solution on Discord, you can try the Klipper Discourse server.  Ultimately you may have to track down a solution yourself or wait for someone in the community to assist.

-Kevin
