### ISSUE TITLE
Batch mode using multiple controller boards

### ISSUE THREAD

**Issue by Bernouillle** [KevinOConnor/klipper#4186]
Hi Guys,
i did some changes in Klipper for a project and i upgraded the setup from one to two boards. How do i run the debugging (batch) mode with two boards mentioned in the config file? Is it possible at all? I can run the batch mode with just a one board config file. Can i change the klipper.dict file to adjust it for running the batch mode with a two board setup? FYI i use a smoothieboard for five motors and an additional ramps board for the sixth motor and the extruder. Attached you find my config file (in a log format). I do get a flush error in octoprint, when i try to extrude. Unfortunately, i don't have the klippy.log file available atm. Maybe you can help with the provided informations in this ticket.
Thanks for your help! 
[printer.log](https://github.com/KevinOConnor/klipper/files/6331812/printer.log)

**Comment by KevinOConnor** [comment]
It's possible but not currently documented.  It's something like:
```
~/klippy-env/bin/python ~/klipper/klippy/klippy.py ~/printer.cfg -i somefile.gcode -d out/klipper.dict -d my_second_mcu=out/klipper.dict
```

If you have further questions, probably best to use Discord or Discourse.

-Kevin
