### ISSUE TITLE
!! TMC 'stepper_y' reports error: DRV_STATUS: 801f5000 s2vsa=1 stealth=1 CSACTUAL=31 stst=1

### ISSUE THREAD

**Issue by Oranginator** [KevinOConnor/klipper#4187]
Hi I got the problem that my printer crashes with the following message "!! TMC 'stepper_y' reports error: DRV_STATUS: 801f5000 s2vsa=1 stealth=1 CSACTUAL=31 stst=1", checking the errorcode s2vsa=1 indicates that there's a short circuit somewhere. I checked TMC 5160 driver and motor by replacing them with spare parts. This changed nothing. For me it's looking like some software issue.

I did the following steps before posting:
1. Checking motor and wiring with multimeter
2. Replacing motor, TMC 5160 and wiring with spare parts
3. Checking TMC 5160 before the error with DUMP_TMC Stepper= stepper_y
4. I'm able to do homing and random manual moves using G1 as often and long as I want and no errors occur.
5. When using Z_TILT_ADJUST it's moving to the first probing point and before triggering  it crashes with "!! TMC 'stepper_y' reports error: DRV_STATUS: 801f5000 s2vsa=1 stealth=1 CSACTUAL=31 stst=1"

Step 3 and 4 are reproduceable.

I did not replace SKR Pro 1.1, as I think a damaged board would be more likely produce capital errors.

What I did before the error occured:
I added ADXL345 follwing the steps mentioned here [https://www.klipper3d.org/Measuring_Resonances.html](url) and here [https://www.klipper3d.org/RPi_microcontroller.html](url).

I hope I've chosen the right way to submit this Issue, thx in advance.

[klippy.log](https://github.com/KevinOConnor/klipper/files/6332107/klippy.log)

**Comment by KevinOConnor** [comment]
Sorry, we don't use github for support.  You'll need to ask on Discord or Discourse.

-Kevin
