### ISSUE TITLE
Long Print: MCU 'mcu' shutdown: Move queue empty

### ISSUE THREAD

**Issue by lmgreco** [KevinOConnor/klipper#419]
Hello,

I was printing a large print with over 24 hours print time already executed when I received this error "MCU 'mcu' shutdown: Move queue empty"

I am not a coder, so I am submitting this error log in hopes it helps find a bug with my printer or with the firmware. Also, I do not want to start another long print if this is something I need to fix!

[klippy.zip](https://github.com/KevinOConnor/klipper/files/2131091/klippy.zip)

**Comment by KevinOConnor** [comment]
This appears to be the same as issue #392.  This is what your frequence graph looks like:
![klippy freq](https://user-images.githubusercontent.com/3004890/41858686-7b2cc68a-7868-11e8-96cb-e49f834c817f.png)
During the failure, the host software could no longer make predictions about the micro-controller clock and that eventually led to an error.  The Klipper software should have done better - this is a bug.  There is a work around described in issue #392, but a full fix still needs to be implemented.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I'm going to close this in favor of the existing issue #392.
