### ISSUE TITLE
Raspberry Pi GPIO internal pullup doesn't work

### ISSUE THREAD

**Issue by gerleimarci** [KevinOConnor/klipper#4207]
I tried to attach an encoder and a pushbutton to the GPIO pins but it only works with external pullup resistors.

```
[mcu rpi]
serial: /tmp/klipper_host_mcu

[display]
lcd_type: sh1106
i2c_mcu: rpi
i2c_bus: i2c.1
encoder_pins: ^rpi:gpio23, ^rpi:gpio24
click_pin: ^!rpi:gpio22
```

**Comment by KevinOConnor** [comment]
On most Linux installations, the pullup interface is not supported.  I've changed the code to make that more clear (commit 70ea0806).

-Kevin
