### ISSUE TITLE
Pulse width for step/dir signals

### ISSUE THREAD

**Issue by motorist828** [KevinOConnor/klipper#422]
I do not know English well, I hope you understand me.
I have slow drivers tb6560 that are controlled by Arduino Mega 2560
I fail due to very fast signals, after switching from mach3 to klipper
Can I set the minimum signal width (8μs)?

**Comment by AxMod3DPrint** [comment]
It's currently not possible, but if you provide your klippy.log as described in https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md there may be something else that is able to be done to help.

**Comment by motorist828** [comment]
I do not have errors in the log
I get a print incline, because the drivers do not keep up with the signal 
this happens at any speed and acceleration
![test](https://user-images.githubusercontent.com/40582999/41908737-b2c34c82-794d-11e8-93e6-5081a19813b0.JPG)

**Comment by dragonnn** [comment]
I think he need the same option as here:
https://duet3d.dozuki.com/Wiki/Using_external_stepper_motor_drivers#Section_Configuring_the_Enable_polarity_and_step_timing
Some stepper driver just doesn't catch up when the pulse length is to short.

**Comment by motorist828** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2137465/klippy.log)

**Comment by KevinOConnor** [comment]
It isn't currently possible to configure the step signal width.

It should be possible to change the code to do so if you wish.  For the atmega2560 you would delete the "select NO_UNSTEP_DELAY" line from src/avr/Kconfig and then modify the "#define UNSTEP_TIME timer_from_us(2)" in src/stepper.c to use a greater time.  After these modifications it would be necessary to do a full rebuild: make distclean ; make menuconfig ; sudo service klipper stop ; make flash ; sudo service klipper start

Such a change is untested and would not reach nearly the stepping rates obtainable with an unmodified klipper.

-Kevin

**Comment by motorist828** [comment]
Thanks, it helped!

**Comment by nick-parker** [comment]
Sorry to bump a zombie issue, but is there up to date reference material on this anywhere? I have a driver I'm pretty sure is upset with my pulse lengths, and the files referenced above don't seem to have the relevant lines anymore.

**Comment by KevinOConnor** [comment]
The pulse width is now configured during "make menuconfig".  Be sure to enable "low level options" and then you should see the option to configure a custom pulse width.

Cheers,
-Kevin

**Comment by nick-parker** [comment]
Right, awesome! I've got this test rig moving now, thanks a bunch!
