### ISSUE TITLE
[REQUEST] M400 gcode command

### ISSUE THREAD

**Issue by Gi0cas** [KevinOConnor/klipper#424]
Hi, i want to ask if there is the possibility to add support to another gcode command : M400.

In Marlin this command has this feature : "Finishes all current moves and and thus clears the buffer."
In my case it's useful because it force to wait the finish of the movements (especially the homing at the end of the print, to leave the print area) than let to go on with other gcode instead of buffer all and consider the print done without the time for last moves.

What do you think? It's a doable support?

**Comment by oderwat** [comment]
`M400` is supposed to exist already. It is mentioned in the GCode Docs and implemented in code: https://github.com/KevinOConnor/klipper/blob/3e88ffabf1b3c54baa48aca058b98354d4d959bc/klippy/gcode.py#L482

**Comment by KevinOConnor** [comment]
It is already implemented.
