### ISSUE TITLE
MKS Mini 12864 LCD enforced optional pin

### ISSUE THREAD

**Issue by Asterchades** [KevinOConnor/klipper#4251]
The configuration for the MKS Mini 12864 LCD screen are incorrectly requiring a pin to be enforced while using software SPI when not all examples of the display have the pin in question.

When using the screen type "uc1701" with software SPI, three additional pins are required: SCLK, MOSI, and MISO. This is in addition to the five (or six, if a buzzer is present) pins required to control the screen and receive input: CS, A0, Encoder +/-, and Encoder click. This doesn't represent a problem when two 10-pin connectors are used, but not all variants of this screen have - or require - two connectors and instead use only one. A single connector with 10 pins cannot physically provide 11 pins of connection.

The 10-pin variants of this display do not have or require the MISO pin to be configured in order to operate. However, Klipper will still enforce a pin being assigned to this function. The only option presently to get the display to work in this case is to find a "throw away" pin which is otherwise unused to assign to the MISO function. This is fine for some configurations where there is such a pin, but communicating to or from a hanging pin - even in the presence of a pull-up/-down - creates potential for interference, and not all such setups will have access to an unused pin.

**Comment by KevinOConnor** [comment]
This was discussed a bit in PR #4132 .  If you're actively working on implementing this, then you can use this ticket to provide update on your status.  Otherwise, we don't use github to track feature requests - see: https://www.klipper3d.org/Contact.html

-Kevin
