### ISSUE TITLE
requests  COREXZ

### ISSUE THREAD

**Issue by malgangda** [KevinOConnor/klipper#426]
He
![4761527153110164-815277266](https://user-images.githubusercontent.com/40621613/41962652-182e15ce-79e5-11e8-9e8f-0ffc02bf2853.jpg)
llo, I would like to ask if there is the possibility to provide support to another kinematics (CoreXZ)

I am currently building a 3D printer with an endless belt. Similar to the Blackbelt 3D printer.
For this printer I need a COREXZ kinematics in Klipper.
I have already run Klipper on a standard printer and am thrilled.
Hence this request.

What do you think? It is a feasible support?

**Comment by oderwat** [comment]
This is so cool! Is that your own design? I would love to make this one of my next projects! Without having a printer for testing it probably will be pretty hard to help implementing the kinematics though.

**Comment by malgangda** [comment]
Hello, the kinematics of CoreXY is the same as in COREXY. The axes Y and Z must be exchanged. So a motor to X and a motor to Z then proceed together.

**Comment by KevinOConnor** [comment]
It's certainly possible to implement, but it would require development work.  There's some info on adding new kinematics at: https://github.com/KevinOConnor/klipper/blob/master/docs/Code_Overview.md#adding-new-kinematics

-Kevin
