### ISSUE TITLE
Virtual SD Card cannot print files with white space (in the filename) from the LCD Screen

### ISSUE THREAD

**Issue by DanyYanev** [KevinOConnor/klipper#4262]
Title says it all, I've attached a log file where the error is present. 

What I can see from the error, is that the filename is cut on the space, trimming the rest of the filename and the extension.

The full filename is - `Voron_Design_Cube_v7_0.2mm_PLA_Voron 2.4_55m 10col.gcode`

Printing files without white spaces works just fine

Note: Printing from files with white spaces works from `mainsail`
[klippy.log](https://github.com/KevinOConnor/klipper/files/6420693/klippy.log)

**Comment by W-Floyd** [comment]
This is still an issue.
