### ISSUE TITLE
new BTT SKR 2 disables 12V after flashing klipper firmware

### ISSUE THREAD

**Issue by Vassssko** [KevinOConnor/klipper#4265]
This new BTT board implements feature mostly aimed to newbies: some simple circuitry and Marlin firmware helps amateur makers not to burn their drivers while inserted upside down.
As a part of this solution, 12V bus (VBB) are controlled by STM32 chip. Pin PC13 used for this: it enables all the fans, motor drivers, heatbeds etc only after "insertion check" and specific command from Marlin firmware.
Surely, klipper firmware does not pulls this pin up and 12V bus are disabled by default making everything not usable. 
There is a [link ](https://github.com/bigtreetech/SKR-2) to documentation, schematic and Marlin config example.

I believe menuconfig should include SKR 2 board explicitly to enable PC13 pullup by default.

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/pull/4234
