### ISSUE TITLE
Feature Request: Onboard SD Support

### ISSUE THREAD

**Issue by zx4017555** [KevinOConnor/klipper#4269]
Feature request to support the onboard SD of the printer mainboard(i.e skr mini, creality 4.x.x) instead of using the [virtual_sd] and the ability to start prints(both on the onboard SD and the virtual_sd) from the LCD(if enabled)

**Comment by swilkens** [comment]
That seems impractical. The gcode is processed by the host, why keep the input data on the client?

You would have to read from the SD card on the board, transfer to the host - process - and transfer back. Essentially halving the bandwidth available.
