### ISSUE TITLE
Klipper Stopping on FAST moves.  MCU limit or bug?

### ISSUE THREAD

**Issue by Maglin** [KevinOConnor/klipper#427]
There was a recent change to my Z which increased its resolution considerably.  One the first leveling it stopped on a 100mm/s Z/X/Y move.  This is one MCU running 4 Z steppers and the other MCU running 2 X/Y steppers.  I'm including the log files.  I did it several times and found if I move my Z faster than 50mm/s 
 now it does this.  I issued an M112 after each event so it's in there a few times.

[Klippy.log](https://pastebin.com/fVUCuTZR)

edit: I just relooked at my logs and it is just attempting to go over the step rate of that MCU.  Is it possible to have the MCU lock all 4 steppers in sync and just send a single Z command once the gantry leveling has been accomplished?  This thing is capable of going much faster.  I know I can put it on better hardware and that is still a WIP.

**Comment by grigorig** [comment]
You have:
`MCU 'z' shutdown: Rescheduled timer in the past`
This is a typical sign off hitting the MCU step rate limit.

**Comment by KevinOConnor** [comment]
As indicated, the requested step rate is too high for an atmega2560 (with your config a Z move of 100mm/s would be 160K steps/s).  I don't think it would make sense to attempt to engineer a software solution - it would be high effort, high risk, and there'd be little reward given there isn't much call to move the Z that fast.

-Kevin

**Comment by Maglin** [comment]
Thank you for the reply.  I was just asking.  I would like my Z hop to be as fast as possible.  In a few weeks, the SAM4E will be running klipper.  I'll be using that before too long.
