### ISSUE TITLE
Temperature Sensors on LPC176x extremely inaccurate after upgrade

### ISSUE THREAD

**Issue by dushyantahuja** [KevinOConnor/klipper#4276]
I generally keep klipper updated (using fluidd's update capability), though do not update the microcontroller code unless required. I upgraded klipper today, and was asked to upgrade the microcontroller code as well since some of the commands had changed. Upgraded the firmware, and the temperature sensors became extremely inaccurate. There was no change to the hardware, or wiring - but the printer refused to even reach a temperature of 200 degrees as per klipper. The actual temperature of the extruder had gone up to 250+ degrees. 

I reverted klipper back to https://github.com/KevinOConnor/klipper/commit/2130e3e5d44965e9ec6685b4dbdc540383363713 - basically removing the changes made on 25 March 2021; and the printer started working again; there still seems to be a bug in the temperature tracking as there was a sudden jump in the temperature from 180 to 190, and then it came down to 180.

Looks like one of these commits created the bug:
https://github.com/KevinOConnor/klipper/commit/6cab7bcfcb12003a538435f351a73978f5fbb954
https://github.com/KevinOConnor/klipper/commit/ae89a65956f95c2bee652396286d97b47ff804b6
https://github.com/KevinOConnor/klipper/commit/39188e1cf3f84a8bbf039be4b327a032f551d3bd

Please find attached the klippy logs from the current master, as well as the 24th March commit.
[klippy - 24 March commit.log](https://github.com/KevinOConnor/klipper/files/6446987/klippy.-.24.March.commit.log)
[klippy - current master.log](https://github.com/KevinOConnor/klipper/files/6446988/klippy.-.current.master.log)

**Comment by KevinOConnor** [comment]
Nothing should have changed with those commits.  In particular, the last commit of 45cd3543 returns the code to something very similar to the original code.

Would it be possible for you to test those 4 commits (6cab7bc, ae89a65, 39188e1, 45cd3543) and determine which one introduced the regression?  Is it possible this is a transient error (not directly related to the code)?

-Kevin
