### ISSUE TITLE
MCU 'host' error during config: Linux gpio interface does not support pullup/pulldown

### ISSUE THREAD

**Issue by manoukianv** [KevinOConnor/klipper#4280]
Hello,

I detect an issue with the default SPI_SOFTWARE config on an host MCU since the last update (commit 8eef1e214639284e386e0d833b6e9c092f9db53e)

I use rpi host for the ADXL, on secondary spi channel with this config :
```
cs_pin: host:gpiochip0/gpio16
spi_speed: 5000000
spi_software_sclk_pin: host:gpiochip0/gpio21
spi_software_mosi_pin: host:gpiochip0/gpio20
spi_software_miso_pin: host:gpiochip0/gpio19
```
and got a pullup/pulldown issue : 
```
"MCU 'host' error during config: Linux gpio interface does not support pullup/pulldown"
```

Logs file : 
[klippy (4).log](https://github.com/KevinOConnor/klipper/files/6450542/klippy.4.log)

I hope it can help.
Best regards
Vincent

**Comment by KevinOConnor** [comment]
FYI, I reverted the original commit causing this issue (in the new commit d6197964).  So, this problem should now be resolved.

-Kevin
