### ISSUE TITLE
temperature_host abort on read error

### ISSUE THREAD

**Issue by TheJoshW** [KevinOConnor/klipper#4294]
Hi,
I am using a `[temperature_host enclosure_temp]` section to read temperatures from a DHT22 sensor attached to the Pi.
I have configured it in the following way:

1. Add `dtoverlay=dht11,gpiopin=23` to `/boot/config.txt`
2. Add the following to `printer.cfg`:
```
[temperature_sensor enclosure_temp]
sensor_type: temperature_host
sensor_path: /sys/bus/iio/devices/iio:device0/in_temp_input

[temperature_sensor enclosure_hum]
sensor_type: temperature_host
sensor_path: /sys/bus/iio/devices/iio:device0/in_humidityrelative_input
```

This all works fine, except the DHT22 is known to be flakey and sometimes needs to be read a couple of times to get a value.
`temperature_host.py` doesn't like this and stops polling the sensor if it gets a read error.

Is it possible to make it retry X times, or continue polling if it gets a read error?
Another minor issue is I am reading the humidity as a temperature, so if this can be fixed as well, great.
[klippy.log](https://github.com/KevinOConnor/klipper/files/6488731/klippy.log)

**Comment by KevinOConnor** [comment]
The temperature_host module isn't suitable to use with the DHT22 - it's only intended to monitor the temperature of builtin cpu sensors.  Best to ask on Discord or Discourse for alternatives as we don't use github to diagnose problems with individual printers.

-Kevin
