### ISSUE TITLE
[Idea] Z-Wobble Calculation

### ISSUE THREAD

**Issue by Ramalama2** [KevinOConnor/klipper#4300]
Hey guys,
first thanks for klipper @KevinOConnor, it's the best piece of software that exists, im just impressed. Just sad that there aren't that much developers, that contribute code, i don't know, maybe some partnerships with printer companies could help, dunno, but that's another topic 🙈

About z-wobble, aside from all the coding that is needed, just in theory, is it possible to use adxl345 or probably a higher sensitive sensor, to measure z-wobble?

my first thought would be simply, that you mount it and let your bed or head (whatever is on the z-axis), drive at different speeds up and down.
So in theory you should figure out with an calculation or whatever (theory), at which heights it shifts to x & y.

And sure, i know, proper printer etc, but that would make any cheap printer amazing 😂

Topic can be closed, if there is no interest, i just need some theory craft.

cheers

**Comment by KevinOConnor** [comment]
Thanks.  However, discussions on new features should use Klipper Discord or Discourse.

-Kevin
