### ISSUE TITLE
OS X Klipper installation wanted?

### ISSUE THREAD

**Issue by oderwat** [KevinOConnor/klipper#432]
I have Klipper now running on my iMac including flashing the firmware and "everything". I needed to modify the Makefile because the OS X `ln` does not have the `-T` parameter. I also needed to skip `util.clear_hupcl(ser.fileno())` because this causes an error (I am not sure why). 

It works using Homebrew with adding a tap for the avm-gcc and some environment manipulations for getting `make menuconfig` running. But that is all I needed to change. I completed my Anycubic Kossel Plus klipper setup just running everything on the Mac.

Currently I am running it through a Octoprint installation which is also on my Mac but I am still experimenting with getting other slicers/hosts work directly with Klipper.

Is there any interest in adding this information and/or changes to the files somehow into the Klipper repository?

**Comment by StefanMeGit** [comment]
I am highly interested in this!

**Comment by ysoldak** [comment]
Interesting. Just write up an instruction in docs folder? Like InstallationOSX.md with all gory details so people can repeat the process. Later could integrate it into scripts themselves.

**Comment by KevinOConnor** [comment]
I'm open to adding an install script, adding documentation, and/or making the code a little more resilient to different operating systems.

-Kevin

**Comment by KevinOConnor** [comment]
Feel free to open a pull request when ready.

**Comment by myk3y** [comment]
So what happened to this?

**Comment by dieideeistgut** [comment]
I'm gonna second here that i'd love to try this within OSX - sadly i can't get the perfect (brew-) environment going so some small hints regarding used brew packages/cask may be usefull here. I don't think that a full documentation would be needed though.

**Comment by oderwat** [comment]
I am not using it like that anymore but this is what I did the last time I used it (Mai):

Installing Python 2.7 with a virtual env and the following packages.

```
Package    Version
---------- -------
cffi       1.11.5
greenlet   0.4.13
pip        10.0.1
pycparser  2.18
pyserial   3.4
setuptools 39.2.0
wheel      0.31.1
```

I previously also added the following dirty hack to the code. Not sure if that is still needed.

```
diff --git a/klippy/serialhdl.py b/klippy/serialhdl.py
index 0f9e87a..eeb756c 100644
--- a/klippy/serialhdl.py
+++ b/klippy/serialhdl.py
@@ -262,6 +262,7 @@ class SerialBootStrap:

 # Attempt to place an AVR stk500v2 style programmer into normal mode
 def stk500v2_leave(ser, reactor):
+    return
     logging.debug("Starting stk500v2 leave programmer sequence")
     util.clear_hupcl(ser.fileno())
     origbaud = ser.baudrate
```

I can't remember exactly what I installed with homebrew, but I guess something like the following:

```
brew install gnu-sed gawk binutils homebrew/dupes/gperf grep gettext ncurses pkgconfig
brew install avr-gcc
```

For `make menuconfig` to work you may also need a little dirty "hack":

```
brew link gettext --force
brew link ncurses --force
```

This may or may not help. Good luck.

**Comment by trevjonez** [comment]
fwiw a single docker image that has octoprint with octoklipper and klipper all together would probably go a long way for this type of thing. I plan to do it at some point as I recently setup an intel nuc that should have the capacity to run many instances of such a container config :)

**Comment by oderwat** [comment]
@trevjonez You mean something like https://github.com/sillyfrog/OctoPrint-Klipper-mjpg-Dockerfile ?

**Comment by trevjonez** [comment]
yup pretty much exactly that. I am no docker pro but I do know that should at least give a good jumping off point for whatever configuration wants to be done. It is likely also a great way to fix/workaround the issues people have had building arm mcu firmware on ubuntu
