### ISSUE TITLE
No USART3 on makemenu for STM32F103

### ISSUE THREAD

**Issue by edriyin1** [KevinOConnor/klipper#4323]
Hello, today I bought some filament after long time. I upgraded all Klipper, Mainsail and Moonraker. And then I took [
![error1](https://user-images.githubusercontent.com/58746649/119581553-77bfc780-bdcb-11eb-9e91-d0c6a5ed4b6d.png)
](url)
this error. Then I tried to reflash my MKS Robin Nano V1.2 board on TT Sapphire Plus. But when I enter "Communication interface" there is no USART3. I tried others but it didnt work.
![error2](https://user-images.githubusercontent.com/58746649/119581741-d84f0480-bdcb-11eb-92d8-d302b8a6d790.png)
Last time I flashed USART3 is available at pins(PB11, PB10).

**Comment by KevinOConnor** [comment]
I think this should be fixed now (commit 12acb99a).

-Kevin
