### ISSUE TITLE
"Timer to Close" mcu shutdown

### ISSUE THREAD

**Issue by Stephan3** [KevinOConnor/klipper#4324]
On one of my pritners i run a raspi4 with klipper. On that printer it happened now the second time that it shuts down with "Timer to Close". I ran tha same 22h plate the 2 days before just fine but now the third stopped after some time. Its the same gcode file, just pushed "play" no upload, no nothing.
See the log attached. 
[klippy.zip](https://github.com/KevinOConnor/klipper/files/6545245/klippy.zip)

**Comment by KevinOConnor** [comment]
We don't use github to help diagnose issues like this.  A "timer too close" is typically the result of host cpu or connectivity issues.  If you want to track it down, then the load graph and log analysis tools (see docs/Debugging.md) can be helpful.  Otherwise, best to report on Klipper Discord or Discourse to see if others can help.

-Kevin

**Comment by Stephan3** [comment]
Thanks for your answer. I allready did what you said. The Graph looks not Horroble.
At 1 a 22h print(same gcode) ended just successfully. at 2 it died with timer to close. 

![grafik](https://user-images.githubusercontent.com/47381132/119692038-5b636f80-be4b-11eb-95fe-12de2404336a.png)

**Comment by KevinOConnor** [comment]
FYI, you'll want to look at the system stats, not the mcu stats - run `graphstats.py --help` for details.

-Kevin

**Comment by Stephan3** [comment]
I replaced now the PI, the Cable, reinstalled everything and it happended again. 3 days it printed fine on day 4 it died with timer to close. See the graphs i created. Wether i am blind or ther is nothing. I dont know what i can do next.

![crash_host](https://user-images.githubusercontent.com/47381132/120188518-81f02480-c216-11eb-99e3-1b0a1b270f6f.png)
![crash_mcu](https://user-images.githubusercontent.com/47381132/120188520-8288bb00-c216-11eb-842c-b4caf4e04026.png)
