### ISSUE TITLE
Unable to uninstall klipper firmware/reinstall Marlin.

### ISSUE THREAD

**Issue by bassamanator** [KevinOConnor/klipper#4333]
Hi there,

I need to reinstall Marlin on my printer (Anycubic Mega S) while I wait for parts. I use Cura to do my firmware flashing as recommended by Anycubic. The problem is Cura (4.8.0 and 4.9.1) no longer *sees* the printer. 

I've tried to reinstall Marlin via Cura on my Raspberry Pi 4, Windows 10 (Thinkpad), and Ubuntu (Thinkpad). I've used all 3 successfully in the past for firmware flashing.

Please help. 

Thanks.

**Comment by bassamanator** [comment]
I used avrdude to flash marlin back onto the board.
`avrdude -p m2560 -P /dev/ttyUSB0 -c wiring -D -U flash:w:MEGA_S_DGUS_v1.2.0-beta.3.hex`

**Comment by Shadow27374** [comment]
This is exactly what I was looking for, thank you!

That belongs best very well marked in the documentation.

**Comment by Gilabite** [comment]
https://www.klipper3d.org/FAQ.html#how-do-i-uninstall-klipper

**Comment by Shadow27374** [comment]
No, I have not found any instructions on how to do it either. But this thread was found quickly.

**Comment by Enlightnd** [comment]
I don't see exactly why Klipper would need installation documentation for another firmware included in its documentation.

The other firmware or the board documentation should cover that.

That's like asking Microsoft to have instructions on how to install every flavor of linux, Asking Apple to have instructions on how to install Windows, etc

**Comment by Shadow27374** [comment]
Because it is not the "standard" and a way back in the description would already be good.

**Comment by bassamanator** [comment]
> I don't see exactly why Klipper would need installation documentation for another firmware included in its documentation.
> 
> The other firmware or the board documentation should cover that.
> 
> That's like asking Microsoft to have instructions on how to install every flavor of linux, Asking Apple to have instructions on how to install Windows, etc

If klipper has instructions on how to change your current firmware to klipper firmware, then there should instructions on how to revert your firmware from klipper to whatever it was before. This improves klipper's documentation, it does not hurt it. And the instructions need not be extremely detailed, simply pointing users to `avrdude` documentation would be sufficient.

But then again, I believe in helping people solve their problems, and making a good thing even better.
