### ISSUE TITLE
'MCU 'mcu' shutdown: Timer too close' when printing for a long time

### ISSUE THREAD

**Issue by gunsliger** [KevinOConnor/klipper#4343]
I got error "MCU 'mcu' shutdown: Timer too close" after over 20 hours of printing. 

No additional plugins in octoprint. I try to change power supply, usb cable - has no effect. If pring time more than 5 hours - an error may occur.
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/6589427/klippy.log.zip)

**Comment by MattByczko** [comment]
Did you solve this in the end @gunsliger

**Comment by gunsliger** [comment]
No, I couldn't solve the problem.
Roll back to Marlin...
