### ISSUE TITLE
Impossible to use hardware with multiplexed endstop pins

### ISSUE THREAD

**Issue by l29ah** [KevinOConnor/klipper#4355]
`error: pin foo used multiple times in config`
For example, both Duex2 and Duex5 have individual SG_TST pins of TMC2660s ORed and presented as one pin.
I think an option to force using a pin multiple times would be a good solution for this and other cases. See also: https://github.com/KevinOConnor/klipper/pull/4076

**Comment by KevinOConnor** [comment]
Okay, but we don't use github for feature requests.  It can be raised on Klipper Discord or Discourse if you wish.

-Kevin
