### ISSUE TITLE
Error's configuring stepper z1

### ISSUE THREAD

**Issue by gorf25** [KevinOConnor/klipper#4413]
My config gives me errors  with the position endstops, position max, amd homing speed.
But only now that i have added the stepper z1 and only with the z1.
I have read that the error would be caused by a probe virtual endstop but i don't have that setup in my config 
Just receive this error message, Option 'homing_speed' is not valid in section 'stepper_z1'
its a duet maestro board, using E1 for the z1 stepper

[stepper_z1]
step_pin: PC5
dir_pin: PC6
enable_pin: !PA1
microsteps: 16
rotation_distance: 8
endstop_pin: ^PC7
#position_endstop: 0
#position_max: 200
#homing_speed: 50

[tmc2208 stepper_z1]
uart_pin: PA9
tx_pin: PA10
select_pins: PC14, PC16, PC17
sense_resistor: 0.075
run_current: 0.800
stealthchop_threshold: 30

Thanks gary

**Comment by jornada812** [comment]
endstop_pin, position_endstop, position_max, homing_speed, position_min, homing_retract_dist, etc. is set only for z motor. Z1 should not contain these values, they are common with Z
