### ISSUE TITLE
Accelerometer diagnostics

### ISSUE THREAD

**Issue by onfoot** [KevinOConnor/klipper#4419]
This is more like a feature idea/request/sanity check.

Since we can mount accelerometers on some types of printers permanently, we can leverage them to perform different types of diagnostics, like belt tension, if there is any backlash due to for loose grub screws or lead screw nuts being worn out, bent extrusions or rails, or rails binding up, whether motion is smooth in all directions etc.

Are there any experiments done by someone on this or any desire to add such features to Klipper?

Most of us surely do some manual diagnostics from time to time, but let's say one has multiple printers that are supposed to be online 24/7, it would be useful to be able to perform a basic periodic check of printer's mechanics.

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/precise-belt-tension-for-corexy/367

Please direct such discussions to Discourse

**Comment by onfoot** [comment]
Thanks, will do!
