### ISSUE TITLE
CR-10 CFG file not working Unable to translate pin name: config_analog_in oid=4 pin=analog14

### ISSUE THREAD

**Issue by Crunch69** [KevinOConnor/klipper#444]
CR-10 cfg file not working get the following error
Unable to translate pin name: config_analog_in oid=4 pin=analog14Recv: // Once the underlying issue is corrected, use the "RESTART"

The ender 3 cfg file loads and works so it is something to do with the CR10 file

 This file contains common pin mappings for the 2017 Creality
CR-10. To use this config, the firmware should be compiled for the
AVR atmega1284p.

[stepper_x]
step_pin: PD7
dir_pin: !PC5
enable_pin: !PD6
step_distance: .0125
endstop_pin: ^PC2
position_endstop: 0
position_max: 300
homing_speed: 50

[stepper_y]
step_pin: PC6
dir_pin: !PC7
enable_pin: !PD6
step_distance: .0125
endstop_pin: ^PC3
position_endstop: 0
position_max: 300
homing_speed: 50

[stepper_z]
step_pin: PB3
dir_pin: PB2
enable_pin: !PA5
step_distance: .0025
endstop_pin: ^PC4
position_endstop: 0.0
position_max: 400

[extruder]
step_pin: PB1
dir_pin: !PB0
enable_pin: !PD6
step_distance: 0.010526
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PD5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA7
control: pid
pid_Kp: 22.57
pid_Ki: 1.72
pid_Kd: 73.96
min_temp: 0
max_temp: 250

[heater_bed]
heater_pin: PD4
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA6
control: pid
pid_Kp: 426.68
pid_Ki: 78.92
pid_Kd: 576.71
min_temp: 0
max_temp: 130

[fan]
pin: PB4

[mcu]
serial: /dev/ttyUSB0

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[display]
lcd_type: st7920
cs_pin: PA3
sclk_pin: PA1
sid_pin: PC1

**Comment by KevinOConnor** [comment]
To report an issue, you need to attach the Klipper log file.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by Crunch69** [comment]
i already modified the ender 3 file so the log would be no good

**Comment by Crunch69** [comment]
the log is gone I did a complete reinstall with the ender 3cfg and then adjust its bed size

**Comment by AxMod3DPrint** [comment]
So is it working now? If not, even if you did a complete re-install of klipper there will be a log at `/tmp/klippy.log` We really could do with that in order to help you out with this.
