### ISSUE TITLE
403 error on libftdi1_0.20-4_armhf.deb

### ISSUE THREAD

**Issue by stevekeen123** [KevinOConnor/klipper#4457]
unable to compile klipper on octopi when doing 
./klipper/scripts/install-octopi.sh

getting error 
Err:1 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libftdi1 armhf 0.20-4
  403  Forbidden [IP: 202.158.214.106 80]
E: Failed to fetch http://mirror.aarnet.edu.au/pub/raspbian/raspbian/pool/main/libf/libftdi/libftdi1_0.20-4_armhf.deb  403  Forbidden [IP: 202.158.214.106 80]

**Comment by BlackStump** [comment]
looks like a broken link to raspbian mirror, are you using a old octopi image?
in anycase it seems to be a raspbian/octopi issue not a klipper one.
