### ISSUE TITLE
 Unknown pin chip name 'probe'

### ISSUE THREAD

**Issue by maviles798** [KevinOConnor/klipper#4468]
When i press get status is send me these error  Unknown pin chip name 'probe' im using a bl touch 3.1 on an ender 6. here is my log file. 
[klippy (1).log](https://github.com/KevinOConnor/klipper/files/6779602/klippy.1.log)

**Comment by aepkolol** [comment]
You have in your config under [stepper_z]

` endstop_pin = probe:z_virtual_endstop`

However, you don't have a [bltouch] section in your config, so the are no pins defined for your probe.

**Comment by maviles798** [comment]
find the problem thanks
