### ISSUE TITLE
Disable all motors doesn't disable inactive toolhead

### ISSUE THREAD

**Issue by HorseEars** [KevinOConnor/klipper#447]
I commented on this a while ago in the IRC but I am not sure if it ever got addressed so I figured I would post an issue because it's still frustrating. 
Running M84 on my machine disables all motors except the inactive tool extruder. 
When I replace my M84 commands with tool changes and M84 all motors are disabled.
```
T0
M84
T1
M84
```
I am using an IDEX dual extruder setup
[klippy.log](https://github.com/KevinOConnor/klipper/files/2153694/klippy.log)

**Comment by KevinOConnor** [comment]
That issue should have been fixed as of commit 41058d22.

-Kevin

**Comment by HorseEars** [comment]
Awesome, this was the last gripe I had with klipper. Thanks so much Kevin
