### ISSUE TITLE
MKS Robin Nano V1.2 - host vs. mcu version mismatch

### ISSUE THREAD

**Issue by Hanezzz** [KevinOConnor/klipper#4481]
Hi,

My setup:
printer: TT Spphire Plus
board: MKS Robin nano V 1.2
STM32F103
28 KiB bootloader

After an klipper upgrade, I'm recently experiencing an error about host vs. mcu version mismatch:

**mcu 'mcu': Command format mismatch: endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c vs endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c

This type of error is frequently caused by running an older
version of the firmware on the micro-controller (fix by
recompiling and flashing the firmware).

Known versions: host=v0.9.1-617-gf2421005, mcu=v0.9.1-489-g1ed67120

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Protocol error connecting to printer.**

After I got an error message, I have done a new firmware setup, using "make menuconfig"; "make".
Than I flashed a MKS board, using microSD again.
Host and MCU versions still mismatch and I'm not able to make them to be the same.
Is it possible, that newest version of Klipper compiles an older and thus, for host, incompatible version of FW?
Any suggestions?

Thanks to all!
Jan

**Comment by BlackStump** [comment]
Please read [FAQ how do I upgrade to the latest firmware](https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-upgrade-to-the-latest-software)
make clean
