### ISSUE TITLE
Doc: "Multiple Klipper Boards on One Pi"

### ISSUE THREAD

**Issue by evenlund** [KevinOConnor/klipper#4495]
The "Multiple Klipper Boards on One Pi" document is missing two important lines from step 9. The two lines immediately following substep 2 in the init.d/klipper2 file should also be renamed to "klipper2" or the install will fail.

**Comment by KevinOConnor** [comment]
It's not clear what document you are referring to.  Maybe something to discuss on Discord or Discourse.

-Kevin

**Comment by evenlund** [comment]
https://klipper.info/helpful-tips-1/multiple-klipper-boards-on-one-pi

**Comment by KevinOConnor** [comment]
That is an unofficial Klipper website - you can inquire on one of the Klipper community forums about it.

-Kevin
