### ISSUE TITLE
Timer reset during print

### ISSUE THREAD

**Issue by MrKekson** [KevinOConnor/klipper#450]
My timer resets during print. Both time left, and time spent, resets to 0, then start to climb back to their proper numbers, basically behave like it's resetting the time data. The % indicator next to it stays like it should be.

I think it's related to m commands from Octoprint, like feed rate change, but did not happens all the time. Pause-restart definitely doing it. 

Trying to grab logs when it happening, but i can't reproduce it reliably. Except the pause one.

**Comment by KevinOConnor** [comment]
On Mon, Jul 02, 2018 at 10:16:07AM -0700, Oli wrote:
> My timer resets during print. Both time left, and time spent, resets to 0, then start to climb back to toer proper numbers, basically behave like it's resetting the time data. The % indicator next to it stays like it should be.
> 
> I think it's related to m commands from Octoprint, like feed rate change, but did not happens all the time. Pause-restart definitely doing it. 

G-Code does not define a "start of print" nor "end of print" command.
So, when printing from OctoPrint (or similar), Klipper just tracks how
long it has been receiving commands without any significant pause
between commands.

If, OctoPrint stalls data for a couple of seconds, then Klipper will
reset its internal "time in a print" tracking.  I suspect this is what
you are seeing.

-Kevin
