### ISSUE TITLE
TMC2008 drivers not supporting One Wire UART Addressing

### ISSUE THREAD

**Issue by ElGranPepo** [KevinOConnor/klipper#4507]
environment:

- TwoTrees Sapphire Plus printer
- MKS Robin Nano 1.2 board
- 3x2208 (X,Y,Extruder) + 2x2225(Z, Z1) TMC Stepper drivers - using 2208 for 2225 as per comments

Configured in Printer.CFG as **tmc2208** stepper_ with uart_address: being anything other than 0 I get:

 **Option 'uart_address' in section 'tmc2208 stepper_y' must have maximum of 0**

when I change the line to **tmc2209** stepper_ i get no error, one wire is supported on both drivers

the Klipper documentation also says that its supported in 2008s:

https://www.klipper3d.org/Config_Reference.html#tmc2208

klippy.log attached

Watermott TMC datasheet attached.

also, any problems when running these as 2209s? dont want to burn my board 

thank you for such a great software! :)

[klippy.log](https://github.com/KevinOConnor/klipper/files/6855796/klippy.log)

[TMC220x_TMC2224_Datasheet_Rev1.11.pdf](https://github.com/KevinOConnor/klipper/files/6855791/TMC220x_TMC2224_Datasheet_Rev1.11.pdf)

**Comment by ElGranPepo** [comment]
this is a bug request

**Comment by jakep82** [comment]
Klipper only supports one wire UART on 2209 drivers.

**Comment by ShohninDmitriy** [comment]
2208 for 2225 do not support addressing

**Comment by ElGranPepo** [comment]
Thanks for the feedback but i cant find this limitation in the documentation. The Trinamic documentation states that its supported


![image](https://user-images.githubusercontent.com/60438864/126533007-17cbb707-b43a-4e71-9884-d4dd006f2fd1.png)

**Comment by jakep82** [comment]
The 2209 supports up to 4 addresses (0-3).  The data sheet you copied from the 2208 clearly states that it supports a single address, and requires analog switches to address more than one IC.  Here's the relevant section from the 2209 data sheet.

```
ADDRESSING MULTIPLE SLAVES
As the TMC2209 uses has a limited number of UART addresses, in principle only up to four ICs can be
accessed per UART interface channel. Adding analog switches allows separated access to more
individual ICs. This scheme is similar to an SPI bus with individual slave select lines (Figure 4.2). With
this scheme, the microstep resolution can be selected via MS1 and MS2 pins (consider actual setting
for addressing).

**Comment by ElGranPepo** [comment]
> The 2209 supports up to 4 addresses (0-3). The data sheet you copied from the 2208 clearly states that it supports a single address, and requires analog switches to address more than one IC. Here's the relevant section from the 2209 data sheet.
> 
> ```
> ADDRESSING MULTIPLE SLAVES
> As the TMC2209 uses has a limited number of UART addresses, in principle only up to four ICs can be
> accessed per UART interface channel. Adding analog switches allows separated access to more
> individual ICs. This scheme is similar to an SPI bus with individual slave select lines (Figure 4.2). With
> this scheme, the microstep resolution can be selected via MS1 and MS2 pins (consider actual setting
> for addressing).
> ```

thank you Jake, i understand that we would need to enable analog switching to do this.  it looks like there has been conversation about this in the past:

https://github.com/KevinOConnor/klipper/issues/542

https://github.com/KevinOConnor/klipper/issues/542#issuecomment-414033488

**Comment by jakep82** [comment]
Soft UART is already implemented for the 2208, but each driver requires it's own GPIO pin.  It handles bi-directional communication (RX and TX) on a single wire, not multiple drivers.  What you want to do can't be done with your hardware.

**Comment by ElGranPepo** [comment]
> Soft UART is already implemented for the 2208, but each driver requires it's own GPIO pin. It handles bi-directional communication (RX and TX) on a single wire, not multiple drivers. What you want to do can't be done with your hardware.

Thank you, Closing.
