### ISSUE TITLE
STM32F0: wrong alternate pins for USART1

### ISSUE THREAD

**Issue by Desuuuu** [KevinOConnor/klipper#4541]
STM32F0 currently allows using USART1 on PA15/PA14 ([code reference](https://github.com/KevinOConnor/klipper/blob/be122411b588ce95785c49dbdf9e4b31a214242e/src/stm32/stm32f0_serial.c#L21)), which isn't valid.

These pins map to USART2 when using AF1.

According to the [STM32F072 datasheet](https://www.st.com/resource/en/datasheet/stm32f072rb.pdf), the alternate mapping for USART1 is PB7/PB6 using AF0.

**Comment by KevinOConnor** [comment]
Thanks.  That config option was added for the stm32f031, but it is confusing.  I reworked it a little (commit 0971a8c2).  Hopefully, it is a little more clear now.

-Kevin
