### ISSUE TITLE
"mcu 'mcu': Firmware constant 'PWM_MAX' not found" when using output_pin with hardware_pwm

### ISSUE THREAD

**Issue by photocromax** [KevinOConnor/klipper#4545]
I added an output_pin for a 24V white led strip. I was trying pwm functionalities in order to dim the light. When I turned on hardware_pwm and save the configuration, Klipper throw this error:

```
mcu 'mcu': Firmware constant 'PWM_MAX' not found

This type of error is frequently caused by running an older
version of the firmware on the micro-controller (fix by
recompiling and flashing the firmware).

Known versions: host=v0.9.1-647-gbe122411, mcu=v0.9.1-647-gbe122411
```

After checking for updates, I've tried to re-flash the mcu just to be sure it was updated to the last version available, but it already was like that, and the error was the same.

I also tried to set the hardware_pwm via the console. It doesn't throw an error, but I guess this option is not changed at "runtime"

**Comment by KevinOConnor** [comment]
Alas, not all mcus support hardware pwm.

-Kevin
