### ISSUE TITLE
Unknown pin chip name 'probe' - z-axis endstop

### ISSUE THREAD

**Issue by Daniel-engman** [KevinOConnor/klipper#4552]
[klippy.log](https://github.com/KevinOConnor/klipper/files/6912937/klippy.log)
<img width="393" alt="fluidd_dashboard_probe" src="https://user-images.githubusercontent.com/71314349/127777237-fe804b76-4ef9-453d-bfa3-48bbcdd31075.png">
Printer: Ender 3 max with added BL-touch
Running KlipperWrt snapshot using fluidd on a Creality wifi box
The config file: https://github.com/KevinOConnor/klipper/blob/master/config/printer-creality-ender3max-2021.cfg
**endstop_pin: probe:z_virtual_endstop**
It's seems to be that line that causes the issue, I unfortunately haven't found any solutions that eliminate this problem. 
Any way to correct this error?

**Comment by Enlightnd** [comment]
Probably because you are using = instead of :?

**Comment by Gilabite** [comment]
Remove the indented gcode macro section safe_z_home from the stepper_z  and bltouch areas (and the indentation from that as well). This isnt a github issue its a user error issue and belongs on discord, discourse.

**Comment by Daniel-engman** [comment]
> Remove the indented gcode macro section safe_z_home and bed_mesh from the stepper_z and bltouch areas (and the indentation from that as well). This isnt a github issue its a user error issue and belongs on discord, discourse.

Thank you for your reply, though in the actual code, there is no such indentation. Only in the logs, therefore I don't exactly know how I am able to correct such a mistake.  Added extra newlines just to exaggerate.
<img width="523" alt="indentation" src="https://user-images.githubusercontent.com/71314349/127781963-3a9ab091-f916-4dd3-bc52-bb04706e97d3.png">

**Comment by Gilabite** [comment]
post your config and not the log so I can see it

**Comment by Daniel-engman** [comment]
> Probably because you are using = instead of :?

I noticed I wrote the post wrong, old habit of writing declarations using equals. I am using : in the code itself. Thank you for noticing

**Comment by Daniel-engman** [comment]
> post your config and not the log so I can see it

[printer.txt](https://github.com/KevinOConnor/klipper/files/6913207/printer.txt)
Saved as a text file this is the config

**Comment by Gilabite** [comment]
you have a space in the config before those macros and bltouch section you moved down, there cant be any spaces before that or it will read it as indented

**Comment by Gilabite** [comment]
its a single space

**Comment by Gilabite** [comment]
you only indent gcode in your macros

**Comment by Daniel-engman** [comment]
> you have a space in the config before those macros and bltouch section you moved down, there cant be any spaces or tabs before that or it will read it as indented

Alright I really have gone blind, thank you! That solved the issue, I'm gonna go get my eyes checked now.
