### ISSUE TITLE
problem detect filament sensor after first print

### ISSUE THREAD

**Issue by tjengbudi** [KevinOConnor/klipper#4554]
hello,
i have post to the forum and asked if somebody have the same problem. but there is no one replying. so i believe it is an error
i used kiauh installer, installed last version klipper (v0.9.1-659-g69d9497d), moonraker (v0.7.1-34-g5522e15) and fluidd (v1.16.2)
there is 2 main problem:

the first problem occurred when i print another session after the first time ( first means after klipper restart). the smart sensor is not recognize again by system. i realize after my filament run out but the system is not paused and still running without filament.
after i realize i try several condition :
a. i reboot host, check the tune tab and the warning show up at my sensor panel, it will change to ok icon after i refresh the endstop status
b. try restart klipper service, check again the tune tab and my sensor panel already have ok icon
c. i push emergency button, push firmware restart and check the icon will be in warning state, and will be ok after i refresh the endstop status like a condition
d. print the object until it finished. check the sensor it at warning state, cannot change to ok state after push refresh endstop status
e. i print another object ( session 2 without restart) and simulate the filament is runout/empty the system never paused. it will paused in first session.

the second problem related with smart filament sensor setting, my setup is :slight_smile:

[filament_motion_sensor my_sensor]
detection_length: 12.0
extruder: extruder
switch_pin: P1.26
pause_on_runout: True
event_delay: 5
pause_delay: 1

the problem is when it have no filament/jam it will paused but after the nozzle parked, it will return and running the printing again. but the z height is not back to save position. after several second it will down with nozzle keep running.
there is 2 problem with this. 1. cannot really paused. 2. the z position is not back to the position

budi

**Comment by drveni** [comment]
> hello,
> i have post to the forum and asked if somebody have the same problem. but there is no one replying. so i believe it is an error
> i used kiauh installer, installed last version klipper (v0.9.1-659-g69d9497d), moonraker (v0.7.1-34-g5522e15) and fluidd (v1.16.2)
> there is 2 main problem:
> 
> the first problem occurred when i print another session after the first time ( first means after klipper restart). the smart sensor is not recognize again by system. i realize after my filament run out but the system is not paused and still running without filament.
> after i realize i try several condition :
> a. i reboot host, check the tune tab and the warning show up at my sensor panel, it will change to ok icon after i refresh the endstop status
> b. try restart klipper service, check again the tune tab and my sensor panel already have ok icon
> c. i push emergency button, push firmware restart and check the icon will be in warning state, and will be ok after i refresh the endstop status like a condition
> d. print the object until it finished. check the sensor it at warning state, cannot change to ok state after push refresh endstop status
> e. i print another object ( session 2 without restart) and simulate the filament is runout/empty the system never paused. it will paused in first session.
> 
> the second problem related with smart filament sensor setting, my setup is :slight_smile:
> 
> [filament_motion_sensor my_sensor]
> detection_length: 12.0
> extruder: extruder
> switch_pin: P1.26
> pause_on_runout: True
> event_delay: 5
> pause_delay: 1
> 
> the problem is when it have no filament/jam it will paused but after the nozzle parked, it will return and running the printing again. but the z height is not back to save position. after several second it will down with nozzle keep running.
> there is 2 problem with this. 1. cannot really paused. 2. the z position is not back to the position
> 
> budi

could you please send my link of printer.cfg and all macros? i have similar problem... maybe I'm wrong somewhere ..
