### ISSUE TITLE
which directory will I find the /tmp/klippy.log

### ISSUE THREAD

**Issue by Crunch69** [KevinOConnor/klipper#456]
where can I find the /tmp/klippy.log?  I issued the M112 and sftp into my pi yet could not find the log file in the klipper or klippy-env directory.  Could you provide a complete path to the log

**Comment by mvturnho** [comment]
/tmp/klippy.log is the complete path.

**Comment by Crunch69** [comment]
i am connecting with notepad ++  i have no /tmp directory on my pi.  my directory shows root/ home/pi/klipper

**Comment by Crunch69** [comment]
found it

**Comment by albmargar30** [comment]
@Crunch69 where did you find it? I'm looking for the windows terminal and WinSCP and I can't find it.

**Comment by theopensourcerer** [comment]
@Crunch69 "/tmp" is the directory.

The leading "/" means the "top" or root directory of the system.
