### ISSUE TITLE
DELTA_CALIBRATE uses incorrect parameter name

### ISSUE THREAD

**Issue by DeanCording** [KevinOConnor/klipper#4571]
After doing a `DELTA_CALIBRATE` Klipper reports the results as:

    stepper_a: position_endstop: 404.870784 angle: 208.981638 arm: 250.659000

The reported arm length should have the label `arm_length` instead of `arm`

**Comment by KevinOConnor** [comment]
Should be fixed - commit d7b04aa1.

-Kevin
