### ISSUE TITLE
Stuttering during probing

### ISSUE THREAD

**Issue by avispa4291** [KevinOConnor/klipper#4584]
Since the last update multiple users on the Voron discord have reported a stuttering of z movement during probing sequences. In most cases it does not affect overall probing but in some cases it has caused probing sequence to fail.

**Comment by JMTV250** [comment]
I have also noticed a strange z hop/stutter after completing probing of bed on Z after probing bed during Klicky z offset

**Comment by jclloyd27** [comment]
I have also noted that is during extensive probing eg. Bed Mesh Calibration.
Per the OP I haven't noticed it creating outlier readings or causing a functional impact

**Comment by jclloyd27** [comment]
I have also noted that is during extensive probing eg. Bed Mesh Calibration.
Per the OP I haven't noticed it creating outlier readings or causing a functional impact

**Comment by Tallen27** [comment]
I have seen this happen with Klicky probe during Voron 2.4 Quad Gantry Level and Bed Mesh Calibration
