### ISSUE TITLE
v0.9.1-699-g23bb6fa1 causes unability to home of voron 2.4 with 4 z motors

### ISSUE THREAD

**Issue by Vassssko** [KevinOConnor/klipper#4600]
Hello.

I've just updated klipper and got an error during home routine:
"Homing instance has no attribute 'get_stepper_trigger.positions'", 'error': 'WebRequestError')

Rolling back to previous release fixes the issue instantly.
![photo_2021-08-20_10-48-56](https://user-images.githubusercontent.com/80907968/130199272-00a04e05-0092-4f5b-bc66-fa97ba1450e2.jpg)
[klippy.log](https://github.com/KevinOConnor/klipper/files/7019976/klippy.log)

**Comment by Vassssko** [comment]
Found out that klipper_z_calibration have reference to that issue: https://github.com/protoloft/klipper_z_calibration/issues/13 as well.

**Comment by LeandroMarceddu** [comment]
Works fine here. Can you attach your printer.cfg?

**Comment by LeandroMarceddu** [comment]
> Found out that klipper_z_calibration have reference to that issue: [protoloft/klipper_z_calibration#13](https://github.com/protoloft/klipper_z_calibration/issues/13) as well.

It looks like that module is to blame by using something that's not available any more. Disabling this module should get you up and running again.

**Comment by Vassssko** [comment]
Found out that module was updated, and I was not fetched the update correctly. I have to doublecheck this, but it looks like the issue have that rootcause. Anyway for all of the folks having similar issue I would like to point to this: https://github.com/protoloft/klipper_z_calibration/issues/13#issuecomment-902526509
