### ISSUE TITLE
Heated Bed

### ISSUE THREAD

**Issue by Maximuscr31** [KevinOConnor/klipper#463]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2171494/klippy.log)
I have finally got everything working well with klippy except for my heated bed. I have no bed option in the picture. When I first setup klippy I was not using a heated bed but have since gotten another and connected everything to ramps. Is there a setting I must enable to make it recognize the heated bed and use it? I can reset it all up again if necessary but prefer to fix it if able. 
![noheatedbed](https://user-images.githubusercontent.com/3136361/42393414-545cebf6-8124-11e8-9b14-f02baf208067.jpg)

**Comment by mmone** [comment]
There is a typo in the config "heater_bed" instead of heated_bed

**Comment by mmone** [comment]
Do you have "Heated Bed" activated in your OctoPrint printer profile?

**Comment by Maximuscr31** [comment]
I did not. That took care of it. Thank you so much.
