### ISSUE TITLE
Printer is not ready The klippy host software is attempting to connect. Please retry in a few moments.

### ISSUE THREAD

**Issue by arshillimbani123** [KevinOConnor/klipper#4643]
my printer is not connecting to klipper.
![image](https://user-images.githubusercontent.com/72181493/131547670-f5181dac-3bda-4ec1-a678-aaa0b7f6694a.png)
in ssh it shows I device but in a fluid it not connecting
![image](https://user-images.githubusercontent.com/72181493/131547868-aeff7e98-8fa3-41bb-9cc5-abd176e72658.png)
what should I do ??
I tried changing USB cable and tried every USB port in raspberry pi
[klippy.log](https://github.com/KevinOConnor/klipper/files/7085727/klippy.log)

**Comment by theopensourcerer** [comment]
Unfortunately Github is not used for this kind of issue. Please see:

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#help-it-doesnt-work

**Comment by bill-orange** [comment]
Same here after latest update.

**Comment by theophile** [comment]
You need to follow these instructions to set up your pi as a host mcu: https://www.klipper3d.org/RPi_microcontroller.html#install-the-rc-script

**Comment by arshillimbani123** [comment]
> Same here after latest update.

I am also facing this problem after update.

**Comment by bill-orange** [comment]
@theophile I did as directed in your link and it did not work.  I eventually got it to work.  In the successful compile, I added a 'make clean' before make.  That may be a necessary step in this rare case case.

**Comment by theophile** [comment]
Yes, you should always do a `make clean` before recompiling for a different architecture.
