### ISSUE TITLE
Error with SKR 2 extruder

### ISSUE THREAD

**Issue by KC6331** [KevinOConnor/klipper#4647]
When I create a printer.cfg with only E0 listed with its values, I get an error that I need to specify micro steps for E1, even if it is not in the fhe file anywhere. If I add it is, I have to set min temp to -100 as there is nothing connected, but then I get an error when heating because its trying to heat both hotends. Please can someone assist with this issue? When I save and run like that I get the following: Option ‘microsteps’ in section ‘extruder1’ must be specified

[klippy.log](https://github.com/KevinOConnor/klipper/files/7095697/klippy.log)

**Comment by schnello** [comment]
Hello.

Delete the section [extruder1] and [tmc2209 extruder1]

Regards
