### ISSUE TITLE
Another "Move exceeds maximum extrusion (2.037mm^2 vs 2.000mm^2)"

### ISSUE THREAD

**Issue by vert-rouge** [KevinOConnor/klipper#4660]
Hi,

I’ve read the other issues, and mine does not seems to be related to the slicer.
I’ve done the print multiple time. Sometimes it works really well, and sometimes, it doesn’t.

example in the klippy, where the interesting stuff starts at line #22114
line 22114 : first unsuccessful print
line 22206 : second unsuccessful print.
line 22292 : reboot
line 23191 : successful print

the print is actually not finished.
I have the gcode if it’s useful.

I’m using Fluidd, and use the exact same file.

**Comment by strayr** [comment]
this looks like a support request? 
Is this your purge line? Is it really fat? 
Log doesn't look like it's attatched properly
See
```
[extruder]
max_extrude_cross_section: 1 #set this to something sane
```
you should probably take this to the discourse, community discord or r/klippers
interesting that it's only sometimes over the limit though i think that's some odd floating point rounding behaviour in the iterative solver? I had similar behaviour in a second print of a fat purge line failed i thing becasue it was using accel and PA from the last print not the accel from the config file and it was enough to push the floating point rounding over the edge.

**Comment by vert-rouge** [comment]
Hi,
I come from the discourse.
I really think it is a bug as I made section calculation by hand.
[klippy.zip](https://github.com/KevinOConnor/klipper/files/7127564/klippy.zip)

My guess is there is some problems with pressure advance. I looked at the code, but I didn’t manage to get debug log working.

**Comment by vert-rouge** [comment]
I don't think this is a request for help.

There is a problem if a code produce different results, and the problem keep happening.

**Comment by watzon** [comment]
I agree. I'm having this same issue both with Cura and with gcode generated by https://teachingtechyt.github.io.

In both cases there is no pressure advance settings in play, and even increasing the max_extrude_cross_section property to an insane number still gives issues.

**Comment by RyushoYosei** [comment]
THere very much is a problem here, I have encountered it myself With profiles that were working flawlessly without issue for months suddenly now having this issue.
