### ISSUE TITLE
Resonance compensation X Axis no csv output

### ISSUE THREAD

**Issue by Dreamdancer100** [KevinOConnor/klipper#4662]
Good morning have some big problem when I made resonance compensation with adxl345  2 weeks ago all is fine but after klipper update I made new test but X axis won’t give csv output for Y axis test all is fine. Made all Firmware new update all to latest but X axis won’t give output. When test run to 133 hz klipper freeze and nothing happened Input shaper was startet but no csv file I must restart klipper to work with Printer again! If I testing after 133 hz I see temp sensors are freeze too what can I do ?

**Comment by Talha909** [comment]
I have the same error message. adxl works good before the update. After update my adxl disconnect. If you find any thing please let me know.  Thanks. 
[klippy (1).log](https://github.com/KevinOConnor/klipper/files/7116170/klippy.1.log)
 and data

**Comment by Dreamdancer100** [comment]
Yeah when I’ve some answer I told you the result!
The hard way is to setup new pi means reinstall  mainsail OS

**Comment by Talha909** [comment]
> Yeah when I’ve some answer I told you the result!
> The hard way is to setup new pi means reinstall mainsail OS

I reinstall the pi with fresh fluidd. But the result was same. So it does not change any thing when reinstall

**Comment by Dreamdancer100** [comment]
I’ve used one new adxl345 but same problem 
I think the Problem comes out klipper update

**Comment by Dreamdancer100** [comment]
Mainsail OS have some update I installed and in evening I test resonance X axis again if that problem fixed

**Comment by Dreamdancer100** [comment]
I‘m test after System Update no result 
Resonance test X axis no csv output

**Comment by Dreamdancer100** [comment]
Anyone some idea

**Comment by Dreamdancer100** [comment]
OK thanks a lot
i will contact right one
