### ISSUE TITLE
Installation on fedora server

### ISSUE THREAD

**Issue by willy059** [KevinOConnor/klipper#4665]
Hi, i tryed to install klipper on fedora server 34 and i got many issues
I used install-centos.sh script

first, I have to force installing greenlet cffi and serial with python 2.7, pip for python 3 is by default,

(reading from bottom to top)

> 00:30 klipper.service: Failed with result 'exit-code'.
> 00:30 klipper.service: Main process exited, code=exited, status=1/FAILURE
> 00:30 ImportError: No module named greenlet
> 00:30 import greenlet
> 00:30 File "/home/william/klipper/klippy/reactor.py", line 7, in <module>
> 00:30 import util, reactor, queuelogger, msgproto
> 00:30 File "/home/william/klipper/klippy/klippy.py", line 8, in <module>
> 00:30 Traceback (most recent call last):
> 00:30 Started Starts klipper on startup.

corrected with 

>   101  curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
>   102  python2.7 get-pip.py
>   103  pip install greenlet
>   104  pip install cffi
>   105  pip install serial

second I have to use ExecStart=/usr/bin/python2.7 to the service, if not :

> 00:20 klipper.service: Failed with result 'exit-code'.
> 00:20 klipper.service: Main process exited, code=exited, status=203/EXEC
> 00:20 klipper.service: Failed at step EXEC spawning /home/william/klippy-env/bin/python: Permission denied
> 00:20 klipper.service: Failed to locate executable /home/william/klippy-env/bin/python: Permission denied
> 00:20 Started Starts klipper on startup.

third, I have to put log in my home /home/william/klippy.log, if not :

> 00:39 klipper.service: Failed with result 'exit-code'.
> 00:39 klipper.service: Main process exited, code=exited, status=1/FAILURE
> 00:39 IOError: [Errno 13] Permission denied: '/var/log/klippy.log'
> 00:39 stream = open(self.baseFilename, self.mode)
> 00:39 File "/usr/lib64/python2.7/logging/__init__.py", line 950, in _open
> 00:39 StreamHandler.__init__(self, self._open())
> 00:39 File "/usr/lib64/python2.7/logging/__init__.py", line 920, in __init__
> 00:39 logging.FileHandler.__init__(self, filename, mode, encoding, delay)
> 00:39 File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
> 00:39 BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
> 00:39 File "/usr/lib64/python2.7/logging/handlers.py", line 171, in __init__
> 00:39 self, filename, when='midnight', backupCount=5)
> 00:39 File "/home/william/klipper/klippy/queuelogger.py", line 27, in __init__
> 00:39 ql = QueueListener(filename)
> 00:39 File "/home/william/klipper/klippy/queuelogger.py", line 62, in setup_bg_logging
> 00:39 bglogger = queuelogger.setup_bg_logging(options.logfile, debuglevel)
> 00:39 File "/home/william/klipper/klippy/klippy.py", line 308, in main
> 00:39 main()
> 00:39 File "/home/william/klipper/klippy/klippy.py", line 350, in <module>
> 00:39 Traceback (most recent call last):
> 00:39 Started Starts klipper on startup.

Only all this "fixed" I can lauch the service, but I still have this error :

> 00:55 Exception: Unable to build C code module (error=32512)
> 00:55 raise Exception(msg)
> 00:55 File "/home/william/klipper/klippy/chelper/__init__.py", line 256, in do_build_code

That's actually a testing server, all this are fine on my other Ubuntu server, but for stability reason and other server usage, I have to migrate to Fedora server.

**Comment by theopensourcerer** [comment]
Hi, I don't think you will get much help here for this kind of issue. 

Please see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#help-it-doesnt-work
