### ISSUE TITLE
Cannot specify a manual_stepper which uses radians

### ISSUE THREAD

**Issue by zouden** [KevinOConnor/klipper#4672]
When defining a manual stepper, I get this error:

    Error: Option 'rotation_distance' in section 'manual_stepper stepper_a' must be specified

My config specifies `gear_ratio` but not `rotation_distance` because this manual stepper rotates (and has an endstop) but does not move with a belt. This configuration _should_ cause Klipper to enable `units_in_radians` (as seen here https://github.com/KevinOConnor/klipper/blob/master/klippy/stepper.py#L230) but it doesn't, because units_in_radians defaults to False instead of None (line 262 of stepper.py). 

I see two solutions: improve the "auto detection" of radians (eg change False to None) or allow the user to specify units_in_radians=true in the config.

[klippy.log](https://github.com/KevinOConnor/klipper/files/7137924/klippy.log)

**Comment by KevinOConnor** [comment]
Okay, but that is the intended behavior - as the manual stepper code only works as a cartesian style axis.  A change in behavior would require an interested developer to implement and submit it.

-Kevin
