### ISSUE TITLE
Wrong automatic PID calibration?

### ISSUE THREAD

**Issue by robustini** [KevinOConnor/klipper#4682]
I have found that unfortunately the automatic calculation of the PID is wrong in many situations, or rather it gives values that do not maintain an accurate hotend temperature.
These are the PIDs found by the calibration:

pid_kp = 18.441
pid_ki = 0.640
pid_kd = 132.774

With these values at 200° I have an excursion of +/- 0.7°, sometimes even 2°.
I notice that in the calibration phase the target temperature reaches over 15° that declared, nothing strange if the automatism then understands that it should lower the proportional to then try again, however in the following phases it continues to exceed a lot.
Even repeating the calibration several times, perhaps first at a low temperature then at a higher temperature, the PIDs found are almost always the same wrong.
These are PIDs that I entered manually instead:

pid_kp = 10
pid_ki = 0.7
pid_kd = 80

With these manual values at 200° I have an excursion of +/- 0.1°.
The automatic calibration at least here fails with a 24V heating cartridge.
I tried to play with max power and pwm cycle time but the results after calibration are always inaccurate. 
I believe that automatism should work better than something manual... :P
I therefore ask @KevinOConnor if possible to review the part of the code concerning that calibration, there could be some room for improvement.
My two cents...

[klippy.zip](https://github.com/KevinOConnor/klipper/files/7148378/klippy.zip)

**Comment by robustini** [comment]
The pictures of the charts show the huge difference.
To interpret them correctly look at the temperature scaling on the left. 

PID detected with calibration

![calibration_pid](https://user-images.githubusercontent.com/3864712/132977795-7ca96db2-d61d-41d7-9772-644bcb45a106.JPG)


PID entered manually

![manual_pid](https://user-images.githubusercontent.com/3864712/132977640-30507d7a-1183-4e92-a90c-be07c317f72a.JPG)

**Comment by keleticsaba** [comment]
As new user, i can agree. After marlin, starting of the print takes minutes to target temperature. Also pid values differ marlin pid tuning values. Increasing the smoothing time to 2 or 3 seconds helps a bit. However what I get is overshooting the target temperature, not fluctuating over target. 24V system, with mega2560.

**Comment by keleticsaba** [comment]
Update:
Using lower target temperature with the calibration made a good results. (The Klipper tutorial uses 170C.)
PID_CALIBRATE HEATER=extruder TARGET=120 >>> Now my printjob at 245C starts instantly, and temperature is rock solid.

**Comment by robustini** [comment]
Already tried, 

> 
> 
> Update:
> Using lower target temperature with the calibration made a good results. (The Klipper tutorial uses 170C.)
> PID_CALIBRATE HEATER=extruder TARGET=120 >>> Now my printjob at 245C starts instantly, and temperature is rock solid.

Already ready several times, the described problem remains.

**Comment by KevinOConnor** [comment]
You should upgrade to the most recent version of the code, as changes to smooth_time have improved this behaviour.  Otherwise, you'll need to reach out the to the Klipper community via Discord or Discourse to see if someone can help.

-Kevin
