### ISSUE TITLE
MCU 'mcu' shutdown: Move queue empty

### ISSUE THREAD

**Issue by bdanmcm** [KevinOConnor/klipper#471]
4 Hours into a print at 99% done.  Printer stops, turns off heaters and shows error:
MCU 'mcu' shutdown: Move queue empty

Printing on stock anet a8 board @60mm/s.  So far this is the only print this has happened on but it is the longest print attempted using klippy.

Attached is the log

Thanks
Brendan

[klippy.zip](https://github.com/KevinOConnor/klipper/files/2176141/klippy.zip)

**Comment by KevinOConnor** [comment]
Unfortunately, you've hit the same bug described in issue #392.

![klippy freq](https://user-images.githubusercontent.com/3004890/42455509-706a9d8c-8360-11e8-8f65-4391d97fb657.png)

**Comment by bdanmcm** [comment]
Thanks kevin, I just removed the display to see if there was an issue with that.  I will try today with the CLOCK_MONOTONIC_RAW change on a longer print and update tonight/tommorrow.

**Comment by bdanmcm** [comment]
Just tested on an 11 hour print.  Printed perfect, no issues after changing to CLOCK_MONOTONIC_RAW.  Closing issue...
