### ISSUE TITLE
Cant compile STM32F1  code

### ISSUE THREAD

**Issue by sniperlucian** [KevinOConnor/klipper#473]
I adjusting menuconfig to STM32f10 devices and get following error message:

make: *** No rule to make target 'out/board/irq.h', needed by "out/src/sched.o". Stop

Are here any undocumented requirements I need to install to compile STM32 ?

**Comment by KevinOConnor** [comment]
If one makes significant changes in "make menuoconfig" then it is sometimes necessary to run "make clean" prior to running "make".

-Kevin

**Comment by sniperlucian** [comment]
Had to install 
"sudo apt-get install gcc-arm-none-eabi"

compiling now - but getting a lot of warnings:

'use 2-byte wchar_t yet the output is to use 4-byte wchar_t .... may fail'
