### ISSUE TITLE
optparse is deprecated, should use argparse instead

### ISSUE THREAD

**Issue by mamoit** [KevinOConnor/klipper#477]
argparse should be used in place of optparse as stated [here](https://docs.python.org/3.7/library/optparse.html) for python 3.
> Deprecated since version 3.2: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

and [here](https://docs.python.org/2.7/library/optparse.html) for python 2.
> Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

**Comment by KevinOConnor** [comment]
We'll move to an alternative should there be a reason to.  No further development on optparse is not a reason in itself.
