### ISSUE TITLE
[Request] multiple probes by bet_tilt_adjust and z_tilt_adjust

### ISSUE THREAD

**Issue by derdigge** [KevinOConnor/klipper#483]
Dear all.

Is it possible to add an option like "sample_count" to [z_tilt] and [bed_tilt] or [probe]?
In my case even if i set my probe to be verry close(1mm) from bed before trigger i still have a deviation.
So the idea is for every probe(homing Z also?) take a mean of sample_count -5?4?3?.

For example my homing override looks like:
```
[z_tilt]
z_positions:
	30,30
	280,30
speed: 10
horizontal_move_z: 5

[homing_override]
set_position_z: 0
gcode:
	G90
	G0 Z5
	G28 X0 Y0
	G0 X30 Y30
	G28 Z   # triggering 2 times
	G0 Z10
	z_tilt_adjust # causes Z postion ~0.3at 30,30
```

at 30,30 z_tilt_adjust 1st messure should be at z height 0.00?? But it never is even after repeating G28(homing_override) several times. my probe is not that bad. i did a macro probing 30 times the middle of the bed with several settings of probe distance(screw on probe). see spreadsheet:
[https://docs.google.com/spreadsheets/d/e/2PACX-1vSdj2cX5h4j1YioAmY_HiGg4OGMYIGFgeTDVTBumcHqYFICtD9eGr5jePxrT7SiYy5VxdImVtgsO_Lw/pubhtml](https://docs.google.com/spreadsheets/d/e/2PACX-1vSdj2cX5h4j1YioAmY_HiGg4OGMYIGFgeTDVTBumcHqYFICtD9eGr5jePxrT7SiYy5VxdImVtgsO_Lw/pubhtml)

in my oppinion a mean of 3-5 will improve first layer.

Thanks for reading
derdigge

**Comment by KevinOConnor** [comment]
It would help if you could attach the klipper log file after running your homing sequence.

Do you really have your z screw directly under 30,30?  That's rare.  If it is not located there, then you will need to configure the z screw locations to get good results.

If you want to probe the same point multiple times, just place that point multiple times in the "points" parameter.

-Kevin

**Comment by derdigge** [comment]
Thanks Kevin for taking Care of MY problem. The printer is a CR10s with dual Z. I switched to MKS gen 1.4 board as my original board broke(mosfet molt). I do not have a log at hand now. Please dont hurt me but at the moment i have Marlin back on it for testing theire probe implementation. There is no Z_tilt alikke feature with Marlin. The z_tilt is useful for CR10 as the extruder side lowerd a few mm when motors turn of and you need to fix by hand.

I also Tired it at the middle of the bed(Y direction) with Klipper.

Do i understand you right? if i use this config:
```
[z_tilt]
z_positions:
	60,165
	240,165
points:
	30,165
	30,165
	30,165
	270,165
	270,165
	270,165
speed: 40
horizontal_move_z: 5
```

It takes the mean of 3 messures at 30,165 as "heigth" value for adjustment? So i only do have a missunderstanding of what points is doing? So is the behavior the same for [bed_tilt]?
Wouldnt it be easyer to have a parameter like "probes per position"?

Thanks after your answer ill try that.

derdigge

**Comment by derdigge** [comment]
So i did a quick test. Strange thing that the corrections made on 5 runs(one after another) are that big? Thats confuses me. see here:

https://pastebin.com/NZb8uhBp

my full config:
https://pastebin.com/7iNJfccd

/tmp/klippy.log
https://pastebin.com/XLLBq9Cz

**Comment by KevinOConnor** [comment]
On Sun, Jul 15, 2018 at 11:37:49AM -0700, derdigge wrote:
> So i did a quick test. Strange thing that the corrections made on 5 runs(one after another) are that big? Thats confuses me. see here:

Your z_positions do not make sense.  The z_position should be the
cartesian coordinate of the Z screw.  That is, it should be the
theoretical position that one would command the nozzle to move to so
that the nozzle would be directly above the screw.

On the CR10 I think one z_position should have a negative number for
the X coordinate and the other should have an X coordinate greater
than 300.

-Kevin

**Comment by derdigge** [comment]
Ahhhhh

Stupid me! So the Z position is for 

Z1=X0-(distance from X0 to leadscrew)= -30
Z2=X330+(distance from X330 to leadscrew) = 355

I just want clear it as i missunderstood google/ducomentation here/exampleconfigs. Maybe others after me have the same confusion(s).

Does this:

```
[z_tilt]
z_positions:
	60,165
	240,165
points:
	30,165
	30,165
	30,165
	270,165
	270,165
	270,165
speed: 40
horizontal_move_z: 5
```

or this:

```
[bed_tilt]
x_adjust: 0
y_adjust: 0
speed: 60
horizontal_move_z: 5
points:
	30,60
	30,60
	30,60
	260,60
	260,60
	260,60
	30,165
	30,165
	30,165
	260,165
	260,165
	260,165
	30,230
	30,230
	30,230
	260,230
	260,230
	260,230

```

build a mean value of 3 meassures at each point?

And a thing i also cant get a clear understanding of is where has probe offset X/Y to be set ?

Sorry for (maybe) wasting your time here.

**Comment by mamoit** [comment]
Probing the same point multiple times can be extremely useful for noisy probes.
Apparently, if you repeat the probing point it should average out the results.
You can see the `finalize` method in the `BedTiltCalibrate` class.

**Comment by KevinOConnor** [comment]
On Sun, Jul 15, 2018 at 02:05:45PM -0700, derdigge wrote:
> I just want clear it as i missunderstood google/ducomentation here/exampleconfigs. Maybe others after me have the same confusion(s).
> 
> Does this:
[...]
> points:
> 	30,165
> 	30,165
> 	30,165
> 	270,165
> 	270,165
> 	270,165
[...]
> points:
> 	30,60
> 	30,60
> 	30,60
> 	260,60
> 	260,60
> 	260,60
> 	30,165
> 	30,165
> 	30,165
> 	260,165
> 	260,165
> 	260,165
> 	30,230
> 	30,230
> 	30,230
> 	260,230
> 	260,230
> 	260,230
[...]
> build a mean value of 3 meassures at each point?

Yes.

-Kevin

**Comment by derdigge** [comment]
Thanks for the hints and answers. For me i can confirm if i probe a grid on my 300x300 bed of 8x8 points 3times per point i have an quite good result.(0.05-0.1 deviation per point) If i do it 10times per point the result is very acurate. I have ecxact nozzledistance at nearly all points even if the bed is in "random" positions. I messured the values above with this Device:
https://www.contorion.de/messen-pruefen/holex-messuhr-10-58-mm-56869918?gclid=CjwKCAjwyrvaBRACEiwAcyuzRGp02IHFYXtgdXDW6Xwrp2HOc2Y8LjMJGMW7aEGOwlr3X8FSujWCxxoCrl8QAvD_BwE&aid=167004271356&targetid=aud-171138861919:pla-460643373832&ef_id=WLhzJQAAAC1VYRWk:20180718205111:s

So for me probing multiple times at the same spot takes a long time but gives verry accurate result, at least for me. As the config then "explodes" i thing a parameter like "repeat probing" would be useful. Sorry that i cant contribute such code but maybe you can consider this for the future.

Thanks for the helping hands here an your patience. :)

**Comment by mamoit** [comment]
I think that would be a pretty easy PR to do.
If @KevinOConnor deems that it is a desired feature I volunteer to implement it.

**Comment by derdigge** [comment]
@mamoit  

Your my hero :)

**Comment by KevinOConnor** [comment]
On Wed, Jul 18, 2018 at 02:15:38PM -0700, Miguel Almeida wrote:
> I think that would be a pretty easy PR to do.
> If @KevinOConnor deems that it is a desired feature I volunteer to implement it.

I'd say we should wait and see how common a request this becomes.  For
example, probing multiple times in multiple places (eg, in a grid) may
be more resilient to slight bed defects.

-Kevin

**Comment by mamoit** [comment]
It has my vote then :+1: 
Maybe `PROBE` itself could have an optional argument that could take the number of probes to do and average out the result.
This way all the methods that use `PROBE` could make the most of it.
