### ISSUE TITLE
Following PEP8

### ISSUE THREAD

**Issue by mamoit** [KevinOConnor/klipper#484]
I've been trying to read through this project, and it seems that following [PEP8](https://www.python.org/dev/peps/pep-0008/) could do a lot in terms of readability.

**Comment by oderwat** [comment]
You may want to do like me and let PyCharm re-format everything to make it more readable and allow inspection of the code more easily.

**Comment by mamoit** [comment]
That's one option, but if you're planning on contributing, then there is a need to keep a consistent (readable) formating throughout the project, since a patch developed on a re-formated codebase may not apply correctly on the repo.

**Comment by oderwat** [comment]
I know...

**Comment by KevinOConnor** [comment]
I don't think github issues are a good place for discussing high-level topics like this, as they tend to never be "complete" and thus stay open forever.  The mailing list or IRC might be a better place (see https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md for details.)

Further, I don't think a discussion on coding style will be productive.  I fear it will just lead to "bike shedding".

**Comment by mamoit** [comment]
Fair enough.
