### ISSUE TITLE
Running Klipper as a Linux real-time process ?

### ISSUE THREAD

**Issue by ghost** [KevinOConnor/klipper#485]
I am interested about running Klipper as a Linux real-time process. In other words using CPUs native GPIOs, SPI, I2C ports etc. Noticed there is some support in src/linux/, but no much info how this can be used. Would you be able to provide additional information ?

**Comment by KevinOConnor** [comment]
The Klipper micro-controller code is capable of running as a Linux process with real-time scheduling.  This code (in src/linux/) is used with the Replicape to provide some basic ADC, I2C, and SPI capabilities that that board requires.  Other interfaces (such as GPIO) have not been implemented.  It would be possible to do further extend the code to add additional capabilities.  However, I suspect controlling a stepper motor at high speeds would be impractical via a Linux real-time process.

-Kevin

**Comment by dim08** [comment]
I tried compiling it on x86 platform and it didn’t generate bin file, just elf. Also when tried:
objcopy -O binary klipper.elf klipper.bin
got:
-bash: ./klipper.bin: cannot execute binary file: Exec format error 

Regarding the control of step motors. Some Internet post state that data transfer over 25 MHz via bitbang on RPi might be feasible. If custom Linux kernel driver is written just for the step motors control ?

**Comment by dim08** [comment]
@FHeilmann, I did some profiling, the Klipper and Repetier-Server processor usage is not much. As well as their processor usage probably can be caped by some utilities ?

i.MX233 offers about 500 DMIPS. BCM2837 (RPi 3) offers 4x ~2760 DMIPS, totaling 11040 DMIPS which seem like a total waste just for generating step motor signals. I’ve done some comparison for running Klipper on bare-metal, not clamming for accuracy, see the image bellow. The expected step rates (red) were calculated based on the info from (Features.md).

In my opinion, there suppose to be some way to achieve near real-time execution in Linux. Probably it requires some additional research.

![comparison_klipper](https://user-images.githubusercontent.com/32874759/42950958-a7ff9566-8b64-11e8-80f2-94cac6f90d97.png)

**Comment by FHeilmann** [comment]
It's not that simple unfortunately. 

Feel free to try but prepare yourself for nasty concurrency effects once you move to speeds which require tight timing guarantees.
