### ISSUE TITLE
Possible to set extruder offset?

### ISSUE THREAD

**Issue by kevinmce** [KevinOConnor/klipper#493]
As far as i can see there is no way to set an offset between hotends. 

Not an important feature but might be nice to have this controlled in the firmware.

**Comment by KevinOConnor** [comment]
I'm not really sure what you mean by "offset between hotends".  However, you should look at the SET_GCODE_OFFSET command, and look at the activate_gcode and deactivate_gcode descriptions for extra extruders in config/example-extras.cfg.

-Kevin

**Comment by kevinmce** [comment]
Ahh thats exactly what i was looking for. 

I thought it would be part of the extruder config. But as part of the activate/deactivate gcode is good too. 

Ill leave a link to the[ extended gcode section ](https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md#extended-g-code-commands
)for anyone searching the same info in the future.
