### ISSUE TITLE
Add support M220 M221 command.

### ISSUE THREAD

**Issue by khseal** [KevinOConnor/klipper#50]
It is not possible to change speed and extrusion during printing.

**Comment by hg42** [comment]
I have implemented M220 (speed factor), which was easy...and will create a PR once it is tested enough.
I could implement it at gcode level, so all is included in gcode.py

M221 (flow factor) is another beast.

I recently had one firmware, that did it wrong. Changing M221 mid-print caused excessive E movement.
I think it was Marlin2, the only other firmware I have used lately was Smoothieware, but this worked for years (I think, or I did never change the factor late in the print).

If we had only relative movement it would be easy.
With absolute movement mode it becomes more complex.
I'll try that later.

**Comment by khseal** [comment]
Nice. Thank you for your work. 
Change of speed sometimes it is necessary.

**Comment by hg42** [comment]
are you able to test the PR?

**Comment by KevinOConnor** [comment]
FYI, there is code for M220/M221 available on the work-m221-20171222 branch.

**Comment by KevinOConnor** [comment]
FYI, I committed this to the master branch (commit 3ab9a8d2) and I have removed the work-m221-20171222 branch.
