### ISSUE TITLE
Error trying to implement  "force_move"

### ISSUE THREAD

**Issue by bruce356** [KevinOConnor/klipper#510]
Send: status
Recv: // Error loading kinematics 'cartesian'
Recv: // Once the underlying issue is corrected, use the "RESTART"
Recv: // command to reload the config and restart the host software.
Recv: // Printer is halted
Recv: !! Error loading kinematics 'cartesian'
Recv: ok
[...]

[klippy.log](https://github.com/KevinOConnor/klipper/files/2248071/klippy.log)

Thanks

**Comment by AxMod3DPrint** [comment]
I believe force_move is a newer addition, you are using @mcmatrix branch for the LCD menu, it is quite possible that that isn't currently in line with the master branch in terms of latest additions and hasn't been rebased to the latest commits. As such, force_move may not be implemented, and going by the log, this seems to be possibly the case, although I could be wrong. 

I'll leave @mcmatrix or @KevinOConnor to weigh in here.

**Comment by KevinOConnor** [comment]
Right - the code being run isn't from a branch in this repo.  This issue tracker is only for support of code from this repo.

**Comment by mcmatrix** [comment]
Sorry for this, but that repo is just for menu testing purposes (not meant for normal usage).
Currently, I'm working hard to merge the menu module to the Klipper master branch.
@bruce356 You have to wait until the merge is done. Then the menu module will
be part of Klipper.

**Comment by KevinOConnor** [comment]
To be clear, the code being run doesn't appear to be from the menu testing branch either.
