### ISSUE TITLE
M117 gcode doesn't work when the message starts with a digit.

### ISSUE THREAD

**Issue by raparada** [KevinOConnor/klipper#523]
Hello!!

M117 gcode doesn't work when the message starts with a digit. That's the case of ipOnConnect octopring plugin. Same issue if I try manually: "M117 192.168.x.x" 
To solve this I had to modify the plugin's code by adding a "_" before server_ip.

Thanks!!

**Comment by KevinOConnor** [comment]
Indeed it does not work.  This doesn't look simple to solve though, because of the funky g-code parsing rules.  I'll try to take a look at it, but it's not a high priority for me right now.

-Kevin

**Comment by raparada** [comment]
Thanks you Kevin for you answer and you fantastic work!!

**Comment by imrcly** [comment]
Just a note it doesn't like [ either

**Comment by KevinOConnor** [comment]
This should be fixed now (commit e94f3b78).

-Kevin

**Comment by raparada** [comment]
Thank you all!!
-Rodrigo
