### ISSUE TITLE
Addressable Slave Boards [Feature Request]

### ISSUE THREAD

**Issue by viniciusmiguel** [KevinOConnor/klipper#525]
Hello guys.
Since e3d launched the idea of a gantry with quick tools exchange I am thinking about how to control the tools.
Comparing all the firmware available nowadays I think Klipper is the best suitable for it because of the multiple board's control.

The idea is to have a mcu with specific hardware embedded in each tool (extruder, spindle, magnetic pick and place, etc). and a RS-485 bus or CAN (but on this case there's a hardware compatibility problem) so with the T commands, we can switch between the different tools.
Ideally, the tools should share the same bus, because on the extruder tools, for example, the hot-end can't turn off entirely because the time to heat is too long, so the different tool holders have bus interconnection to keep on track of all idle tools (and the active one of course).

So I would like to start a debate about if this is something that is interesting for the project, and different approaches for this implementation.

**Comment by KevinOConnor** [comment]
If you're looking for a general discussion on a topic, I think the Klipper mailing list is probably a better fit.  The mailing list info is at: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin
