### ISSUE TITLE
Where did the "motor_off_time" option go?

### ISSUE THREAD

**Issue by Sapanonic** [KevinOConnor/klipper#526]
> ...
> Recv: // Option 'motor_off_time' is not valid in section 'printer'
> Recv: // Once the underlying issue is corrected, use the "RESTART"
> Recv: // command to reload the config and restart the host software.
> Recv: // Printer is halted
> Recv: !! Option 'motor_off_time' is not valid in section 'printer'
> Changing monitoring state from "Operational" to "Error: Option 'motor_off_time' is not valid in section 'printer'"
> Changing monitoring state from "Error: Option 'motor_off_time' is not valid in section 'printer'" to "Offline (Error: Option 'motor_off_time' is not valid in section 'printer')"
> Connection closed, closing down monitor

**Comment by jakep82** [comment]
Check the idle_timeout option in the example-extras.cfg.

https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg
