### ISSUE TITLE
generate hex file for ATMega16/32/8535

### ISSUE THREAD

**Issue by 4Joe** [KevinOConnor/klipper#527]
Hi Kevin
how to generate hex file for another ATMega chip such as ATmega16, ATmega32 or ATmega8535. Seems all these chips are pin compatible with ATmega644/1284p

Do you have the plan to include these chips in next release of kliiper ?

**Comment by AxMod3DPrint** [comment]
If they are AVR compatible, then they should be supported out of the box, even if they are not explicitly mentioned in the Documentation

**Comment by KevinOConnor** [comment]
To support another atmega chip, it generally requires a few changes to src/avr/Kconfig, src/avr/gpio.c, and klippy/pins.py.  If you have a particular chip that isn't supported and you are willing to run test code, then let us know the exact model number of the chip and we may be able to get some test code for you.

-Kevin

**Comment by 4Joe** [comment]
Thanks for your information. I have unused gen7 board with DIP40 socket for Atmega Avr chip. I would like to test ATMEGA16 or ATMEGA32 to run klipper firmware on them. I have both of them in my drawer 😁.

**Comment by KevinOConnor** [comment]
I pushed up a test branch with at attempt at atmega32 support:

cd ~/klipper ; git fetch ; git checkout origin/work-atmega32-20180817 ; sudo service klipper restart

Please let me know your results from testing it (success or failure).

The atmega16 support is possible, but due to the small flash size it would require manually disabling features to get the code to fit.  (The atmega168 has a similar issue.)

-Kevin

**Comment by KevinOConnor** [comment]
Any update on this?

**Comment by 4Joe** [comment]
Hi Kevin.
I'm sorry for late repply. I have successfully generate the hex file for
Atmega32 dan burning it via usbasp to an Atmega32 chip.

But not yet test it on real printer cause a day before you repply my issue,
I have disassembled my printer for major upgrade. Please let me about 2
week to finish reassembly it then testing kipper atmega32 on it.

Best Regards
Dafi

**Comment by KevinOConnor** [comment]
Let me know if you (or anyone else) is able to test it.

-Kevin
