### ISSUE TITLE
Klipper timeout after AVR restart.

### ISSUE THREAD

**Issue by khseal** [KevinOConnor/klipper#53]
AVR controller has its own power supply.
If turn off and turn on AVR power then Klipper is no longer connected to AVR.
Restart service solves the problem.
Example in log
Timeout with MCU 'mcu' (eventtime=3040.583039)
Timeout with MCU 'mcu' (eventtime=3041.584679)

**Comment by KevinOConnor** [comment]
On Wed, Dec 06, 2017 at 05:49:13PM +0000, Sergey wrote:
> AVR controller has its own power supply.
> If turn off and turn on AVR power then Klipper is no longer connected to AVR.
> Restart service solves the problem.
> Example in log
> Timeout with MCU 'mcu' (eventtime=3040.583039)
> Timeout with MCU 'mcu' (eventtime=3041.584679)

That's by design.  If the host detects an error (in this case the mcu
resetting) then it enters an error state.  The error state is cleared
by issuing a FIRMWARE_RESTART command in the Octoprint terminal
window.

-Kevin

**Comment by khseal** [comment]
Your command is working.  I need to figure out how to automate this. Thanks for the info.
