### ISSUE TITLE
Add M80 & M81 command to turn on/off PSU through PS_ON pin

### ISSUE THREAD

**Issue by henkyprayoga** [KevinOConnor/klipper#531]
Octoprint has plugin to control additional power supply (https://github.com/foosel/OctoPrint/wiki/Control-your-printer's-ATX-PSU-through-a-RAMPS-board-using-OctoPrint).

Merlin & repertier has support for M80/M81 command. It will set PS_ON pin state. Can you please implement this in klippy too? 

Thank you very much.

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/issues/253

**Comment by henkyprayoga** [comment]
Thanks!!! It works!
