### ISSUE TITLE
Endstop for z is not accurate enough for stepper phase adjustment

### ISSUE THREAD

**Issue by StefanMeGit** [KevinOConnor/klipper#533]
After I checked my log files for something else, I found this message...

```
Changing z endstop position to 0.009 (from 0.000)
Endstop for z is not accurate enough for stepper phase adjustment
```

What des it mean? Homing works just finde. I also didn't get any bad message in the terminal I push multiple times HOMING in Octorprint. 

[klippy.log](https://github.com/KevinOConnor/klipper/files/2279610/klippy.log)

**Comment by KevinOConnor** [comment]
The stepper phase adjustment mechanism allows one to improve the accuracy of endstops by combing the endstop trigger with the stepper phase.  In order for it to work, the endstop must be accurate enough to determine which "cycle" the stepper is in (which then allows the stepper phase to provide further accuracy).  If you're unsure of your endstop accuracy, you can just remove the "homing_endstop_accuracy = 0.1" from your config, and klipper will assume that it is accurate enough.

-Kevin

**Comment by StefanMeGit** [comment]
Ok thanks, I am ware of "homing_endstop_accuracy = 0.1" but I was just confused by this message on the startup. I didn't get this message by actual homing. Do I screw up something?
