### ISSUE TITLE
Internal error on comand: "G1"

### ISSUE THREAD

**Issue by ChiliApple** [KevinOConnor/klipper#534]
hy,

I had the error on 2 prints, the GCode seems to tune, but something about the conversion of the steps seems to be flawed ?!

in my config I have this value for my stepper "step_distance: .00234665"
klipper is up to date ...

![bildschirmfoto 2018-08-11 um 20 09 20](https://user-images.githubusercontent.com/38113577/43994796-016bff0e-9da3-11e8-8057-4d7c9fb348de.png)

**Comment by AxMod3DPrint** [comment]
Please attach your klippy.log to this issue as this will give more information.

**Comment by ChiliApple** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2283894/klippy.log)

**Comment by gdachs** [comment]
There is an unbelievable big amount of extrusion. This gcode line looks fishy.

**Comment by ChiliApple** [comment]
the gcode looks ok in my opinion, but the value in the terminal not

**Comment by Arksine** [comment]
As long as that is absolute extrusion I don't see a problem with it.  The asterisk you see in the terminal is just a checksum, so the terminal gcode is okay too.

The klippy.log you attached doesn't seem to show this error, it just shows where you entered M112 to shut down the system.  Can you reproduce the error and attach the accompanying klippy.log?

**Comment by KevinOConnor** [comment]
There isn't much we can do without a log file from the event itself.  I'm going to close this - I'll reopen if there is a log file.
