### ISSUE TITLE
Error loading kinematics

### ISSUE THREAD

**Issue by tuwwe** [KevinOConnor/klipper#536]
Erroring loading kinematics, it doesnt matter what i try delta,corexy,cartesian. Everyone says same

Starting Klippy...
Args: ['/home/pi/klipper/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.6.0-340-gbe3131d'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.9 (default, Sep 17 2016, 20:26:04) \n[GCC 4.9.2]'
Start printer at Sun Aug 12 09:53:24 2018 (1534067604.3 6.7)
===== Config file =====
[driver drv8825_32]
type = DRV8825
microsteps = 8

[driver tmc2130_x]
type = TMC2130
ss_pin = ar34
spi_mode = 3
spi_speed = 4000000
current = 1100.0
steps_per_mm = 400
step_distance = .0225
microsteps = 32
mode = spreadCycle
diag0_out = temp_prewarn
diag1_out = stall
diag0_active_high = 1
diag1_active_high = 1
interpolate = 0
sensor_less_homing = 1
stealth_max_speed = 30
stall_threshold = 3

[driver tmc2130_y]
type = TMC2130
ss_pin = ar32
spi_mode = 3
spi_speed = 4000000
current = 1100.0
microsteps = 32
steps_per_mm = 400
step_distance = .0225
mode = spreadCycle
diag0_out = temp_prewarn
diag1_out = stall
diag0_active_high = 1
diag1_active_high = 1
interpolate = 0
sensor_less_homing = 1
stealth_max_speed = 30
stall_threshold = 3

[driver tmc2130_z]
type = TMC2130
ss_pin = ar32
spi_mode = 3
spi_speed = 4000000
current = 1100.0
microsteps = 32
mode = spreadCycle
diag0_out = temp_prewarn
diag1_out = stall
diag0_active_high = 1
diag1_active_high = 1
interpolate = 0
sensor_less_homing = 1
stealth_max_speed = 30
stall_threshold = 3

[stepper_x]
driver = tmc2130_x
steps_per_mm = 400
step_distance = .0225
motor_step_angle = 0.9
pitch = 2.
teeths = 16.
step_pin = ar38
dir_pin = !ar36
enable_pin = !ar40
endstop_min_pin = ar54
endstop_max_pin = ar55
position_min = 0
position_max = 220
position_endstop = 0
homing_offset = 0
homing_speed = 30
homing_direction = min
homing_retract_dist = 0

[stepper_y]
driver = tmc2130_y
steps_per_mm = 400
step_distance = .0225
motor_step_angle = 0.9
pitch = 2.
teeths = 16.
step_pin = ar28
dir_pin = !ar26
enable_pin = !ar30
endstop_min_pin = ar56
endstop_max_pin = ar57
position_min = 0
position_max = 270
position_endstop = -2
homing_offset = 0
homing_speed = 30
homing_direction = max
homing_retract_dist = 0

[stepper_z]
driver = tmc2130_z
motor_step_angle = 1.8
pitch = 4.0
teeths = 1
gear_ratio = 2.0
step_pin = ar23
dir_pin = ar29
enable_pin = !ar25
endstop_min_pin = ar58
endstop_max_pin = ar59
position_min = 0
position_max = 220
position_endstop = 2.15
homing_pos_x = 200
homing_pos_y = 200
homing_offset = 0
homing_speed = 3
homing_direction = min
homing_retract_dist = 0
homing_retract_after = 5.

[extruder0]
step_pin = ar41
dir_pin = ar39
enable_pin = !ar43
steps_per_mm = 837
nozzle_diameter = 0.400
filament_diameter = 1.750
heater = heater 0
min_extrude_temp = 170
pressure_advance = 0.0
max_extrude_cross_section = 99.0

[SKIP_extruder1]
step_pin = ar33
dir_pin = ar31
enable_pin = !ar35
steps_per_mm = 837
nozzle_diameter = 0.400
filament_diameter = 1.750
heater = heater 1
min_extrude_temp = 90
pressure_advance = 0.0
max_extrude_cross_section = 99.0

[sensor hotend_rtd]
sensor_pin = ar47
sensor_type = MAX31865
rtd_nominal_r = 100
rtd_reference_r = 430
rtd_num_of_wires = 2
rtd_use_50hz_filter = false
spi_mode = 1
spi_speed = 8000000
min_temp = 0
max_temp = 300

[sensor hotend_therm_k]
sensor_pin = ar47
sensor_type = MAX31856
tc_type = K
tc_use_50hz_filter = false
tc_averaging_count = 1
spi_mode = 1
spi_speed = 8000000
min_temp = 0
max_temp = 300

[sensor hotend_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog9
min_temp = 0
max_temp = 270

[sensor hotend2_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog10
min_temp = 0
max_temp = 270

[sensor bed_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog11
min_temp = 0
max_temp = 120

[sensor hotend_remote_rtd]
sensor_pin = hotend_remote:ar10
sensor_type = MAX31865
rtd_nominal_r = 100
rtd_reference_r = 430
rtd_num_of_wires = 2
rtd_use_50hz_filter = false
spi_mode = 1
spi_speed = 8000000
min_temp = 0
max_temp = 300

[heater 0]
sensor = 'hotend_rtd'
heater_pin = ar7
min_temp = 0
max_temp = 300
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
sensor_pin = hotend_remote:ar10
sensor_type = MAX31865
rtd_nominal_r = 100
rtd_num_of_wires = 2
rtd_reference_r = 430
spi_mode = 1
spi_speed = 8000000
protect_period_heat = 20
protect_hysteresis_heat = 2
protect_period = 10
protect_hysteresis_runaway = 10

[SKIP_heater 1]
sensor = hotend2_ntc
heater_pin = ar6
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
protect_period_heat = 300
protect_hysteresis_heat = 70
protect_period = 60
protect_hysteresis_runaway = 60

[heater bed]
sensor = bed_ntc
heater_pin = ar8
min_temp = 0
max_temp = 120
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
protect_period_heat = 50
protect_hysteresis_heat = 2
protect_period = 10
protect_hysteresis_runaway = 10

[chamber]
sensor = hotend2_ntc
pin = ar11
control = watermark
target_temp = 40.

[SKIP_heater_fan hotend]
pin = ar11
max_power = 1.0
kick_start_time = 0.1
hard_pwm = 0
heater = heater 0
heater_temp = 50.0
fan_speed = 1.0

[mcu]
serial = /dev/ttyACM0
baud = 250000
pin_map = arduino
restart_method = arduino

[mcu hotend_remote]
serial = /dev/ttyUSB0
baud = 115200
pin_map = arduino
restart_method = arduino

[printer]
name = OULWare
kinematics = cartesian
max_velocity = 200
max_accel = 2500
max_accel_to_decel_ratio = 1.0
max_z_velocity = 5
max_z_accel = 30
motor_off_time = 600
junction_deviation = 0.2
require_home_after_motor_off = false
allow_move_without_home = true

[idle_position]
idle_position_x = 10.0
idle_position_y = 10.0
idle_position_z_lift = 5.0
idle_position_travel_speed = 2000

[gcodes.arch]

[gcodes.retract]
test = false

[virtual_sdcard]
path = ~/.octoprint/uploads/

[hostcmd]
commands = 
	list = ls -al
	echo = echo "this is a test"

=======================
Error loading kinematics 'cartesian'
Traceback (most recent call last):
  File "/home/pi/klipper/klipper/klippy/toolhead.py", line 245, in __init__
    self.kin = mod.load_kinematics(self, config)
  File "/home/pi/klipper/klipper/klippy/kinematics/cartesian.py", line 165, in load_kinematics
    return CartKinematics(toolhead, config)
  File "/home/pi/klipper/klipper/klippy/kinematics/cartesian.py", line 14, in __init__
    for n in ['x', 'y', 'z']]
  File "/home/pi/klipper/klipper/klippy/stepper.py", line 265, in LookupMultiRail
    rail = PrinterRail(config)
  File "/home/pi/klipper/klipper/klippy/stepper.py", line 121, in __init__
    mcu_endstop = ppins.setup_pin('endstop', config.get('endstop_pin'))
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 93, in get
    return self._get_wrapper(self.fileconfig.get, option, default)
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 69, in _get_wrapper
    v = parser(self.section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'endstop_pin' in section: 'stepper_x'
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 243, in _connect
    self._read_config()
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 221, in _read_config

**Comment by gdachs** [comment]
Why not first fix the missing endstop pins in the config file that are mentioned in the log? Maybe the error is then gone.

**Comment by tuwwe** [comment]
here is printer.cfg file and they are there 
i dont know why ist show them log file

# OULWare PrinterController v1.0 + DUE
#    - TMC2130 on XY axis!
#    - DRV8825 for Z and E0 & E1
#
#  === DRIVERS ===
#
#  -------------------
#  | X | End MIN | D54
#  | X | End MAX | D55
#  | Y | End MIN | D56
#  | Y | End MAX | D57
#  | Z | End MIN | D58
#  | Z | End MAX | D59
#  -------------------
#
# === HEATERS ===
# | AUX | D9 |
# | BED | D8 |
# | E0  | D7 |
# | E1  | D6 |
#
# === THERMISTORS ===
# | T0    | A9  |
# | T1    | A10 |
# | T2    | A11 |
# | TC CS | D47 |
#
# === FAN ===
# | FAN0 | D10 |
# | FAN1 | D11 |
# | FAN2 | D12 |
# | FAN3 | D13 |
#
# === STEPPER X ===
# | STEP | D38 |
# | DIR  | D36 |
# | EN   | D40 |
# | CS   | D34 |
#
# === STEPPER Y ===
# | STEP | D28 |
# | DIR  | D26 |
# | EN   | D30 |
# | CS   | D32 |
#
# === STEPPER Z ===
# | STEP | D23 |
# | DIR  | D29 |
# | EN   | D25 |
# | CS   | D27 |
#
# === STEPPER E1 ===
# | STEP | D44 |
# | DIR  | D42 |
# | EN   | D46 |
# | CS   | D48 |
#
# === STEPPER E2 ===
# | STEP | D33 |
# | DIR  | D31 |
# | EN   | D35 |
# | CS   | D37 |
#
# === STEPPER E3 ===
# | STEP | D41 |
# | DIR  | D39 |
# | EN   | D43 |
# | CS   | D45 |
#
#
#

[driver drv8825_32]
type:               DRV8825
microsteps:         8
;step_distance: 0.01
;steps_per_mm: 6400

[driver tmc2130_x]
type:               TMC2130
# SPI
ss_pin:             ar34
spi_mode:           3
spi_speed:          4000000
# config
current:            1100.0
steps_per_mm:       400
step_distance: .0225
microsteps:         32
mode:               spreadCycle
diag0_out:          temp_prewarn
diag1_out:          stall
diag0_active_high:  1
diag1_active_high:  1
interpolate:        0
sensor_less_homing: 1
stealth_max_speed:  30
stall_threshold:    3

[driver tmc2130_y]
type:               TMC2130
# SPI
ss_pin:             ar32
spi_mode:           3
spi_speed:          4000000
# config
current:            1100.0
microsteps:         32
steps_per_mm:       400
step_distance: .0225
mode:               spreadCycle
diag0_out:          temp_prewarn ;
diag1_out:          stall
diag0_active_high:  1
diag1_active_high:  1
interpolate:        0
sensor_less_homing: 1
stealth_max_speed:  30
stall_threshold:    3

[driver tmc2130_z]
type:               TMC2130
# SPI
ss_pin:             ar32
spi_mode:           3
spi_speed:          4000000
# config
current:            1100.0
microsteps:         32
mode:               spreadCycle
diag0_out:          temp_prewarn ;
diag1_out:          stall
diag0_active_high:  1
diag1_active_high:  1
interpolate:        0
sensor_less_homing: 1
stealth_max_speed:  30
stall_threshold:    3


# The stepper_x section is used to describe the X axis as well as the
# stepper controlling the X+Y movement.
[stepper_x]
driver:             tmc2130_x
steps_per_mm:       400
step_distance: .0225
motor_step_angle:   0.9
pitch:              2.
teeths:             16.

step_pin:           ar38
dir_pin:            !ar36
enable_pin:         !ar40
endstop_min_pin:    ar54
endstop_max_pin:    ar55
position_min:       0
position_max:       220
position_endstop:   0
homing_offset:      0
homing_speed:       30
homing_direction:   min
homing_retract_dist:0

# The stepper_y section is used to describe the Y axis as well as the
# stepper controlling the X-Y movement.
[stepper_y]
driver:             tmc2130_y
steps_per_mm:       400
step_distance: .0225
motor_step_angle:   0.9
pitch:              2.
teeths:             16.

step_pin:           ar28
dir_pin:            !ar26
enable_pin:         !ar30
endstop_min_pin:    ar56
endstop_max_pin:    ar57

position_min:       0
position_max:       270
position_endstop:   -2
homing_offset:      0
homing_speed:       30
homing_direction:   max
homing_retract_dist:0

[stepper_z]
driver:             tmc2130_z
motor_step_angle:   1.8
pitch:              4.0
teeths:             1
gear_ratio:         2.0

step_pin:           ar23
dir_pin:            ar29
enable_pin:         !ar25
endstop_min_pin:    ar58
endstop_max_pin:    ar59

position_min:       0
position_max:       220
#ceramic tile
position_endstop:   2.15
#with steel plate
#position_endstop:   19.20
homing_pos_x:       200
homing_pos_y:       200
homing_offset:      0
homing_speed:       3
homing_direction:   min
homing_retract_dist: 0
homing_retract_after: 5.

########################################
[extruder0]
step_pin:           ar41   ; ar44
dir_pin:            ar39   ; ar42
enable_pin:         !ar43  ; !ar46
steps_per_mm:       837	   ;(1/32) 418.5 (1/16) ;with 1.8 motor and 1/16 setps 837
nozzle_diameter:    0.400
filament_diameter:  1.750
heater:             heater 0
min_extrude_temp:   170
#deactivate_gcode:  ""
#activate_gcode:    ""
pressure_advance:   0.0
max_extrude_cross_section:  99.0

[SKIP_extruder1]
step_pin:           ar33
dir_pin:            ar31
enable_pin:         !ar35
steps_per_mm:       837
nozzle_diameter:    0.400
filament_diameter:  1.750
heater:             heater 1
min_extrude_temp:   10
min_extrude_temp:   90
pressure_advance:   0.0
max_extrude_cross_section: 99.0

########################################
[sensor hotend_rtd]
sensor_pin:          ar47
sensor_type:         MAX31865
rtd_nominal_r:       100
rtd_reference_r:     430
rtd_num_of_wires:    2
rtd_use_50Hz_filter: false
spi_mode:            1
spi_speed:           8000000
min_temp:            0
max_temp:            300

[sensor hotend_therm_k]
sensor_pin:         ar47
sensor_type:        MAX31856
tc_type:            K
tc_use_50Hz_filter: false
tc_averaging_count: 1
spi_mode:           1
spi_speed:          8000000
min_temp:           0
max_temp:           300

[sensor hotend_ntc]
sensor_type:        NTC 100K beta 3950
sensor_pin:         analog9
min_temp:           0
max_temp:           270

[sensor hotend2_ntc]
sensor_type:        NTC 100K beta 3950
sensor_pin:         analog10
min_temp:           0
max_temp:           270

[sensor bed_ntc]
sensor_type:        NTC 100K beta 3950
sensor_pin:         analog11
min_temp:           0
max_temp:           120

[sensor hotend_remote_rtd]
sensor_pin:          hotend_remote:ar10
sensor_type:         MAX31865
rtd_nominal_r:       100
rtd_reference_r:     430
rtd_num_of_wires:    2
rtd_use_50Hz_filter: false
spi_mode:            1
spi_speed:           8000000
min_temp:            0
max_temp:            300


########################################
#[heater 0]
#sensor:             hotend_ntc
#heater_pin:         ar7
#control:            pid
#pid_Kp:             22.2
#pid_Ki:             1.08
#pid_Kd:             114
#*** Thermal protection
#protect_period_heat:        20
#protect_hysteresis_heat:    2
#protect_period:             10
#protect_hysteresis_runaway: 10

[heater 0]
sensor:             'hotend_rtd'
heater_pin:         ar7
min_temp:           0
max_temp:           300
control:            pid
pid_Kp:             22.2
pid_Ki:             1.08
pid_Kd:             114
#*** Thermistor:
#sensor_pin:         analog0
#sensor_type:        NTC 100K beta 3950
#*** MAX31865 + PT100
sensor_pin:         hotend_remote:ar10
sensor_type:        MAX31865
rtd_nominal_r:      100
rtd_num_of_wires:   2
rtd_reference_r:    430
spi_mode:           1
spi_speed:          8000000
#*** Thermal protection
protect_period_heat:        20
protect_hysteresis_heat:    2
protect_period:             10
protect_hysteresis_runaway: 10


[SKIP_heater 1]
sensor:             hotend2_ntc
heater_pin:         ar6
control:            pid
pid_Kp:             22.2
pid_Ki:             1.08
pid_Kd:             114
#*** Thermal protection
protect_period_heat:        300
protect_hysteresis_heat:    70
protect_period:             60
protect_hysteresis_runaway: 60


[heater bed]
sensor:             bed_ntc
heater_pin:         ar8
min_temp:           0
max_temp:           120
control:            pid
pid_Kp:             22.2
pid_Ki:             1.08
pid_Kd:             114
#*** Thermal protection
protect_period_heat:        50
protect_hysteresis_heat:    2
protect_period:             10
protect_hysteresis_runaway: 10

[chamber]
sensor: hotend2_ntc
pin: ar11
control: watermark
target_temp: 40.

########################################
#[fan 0]
#pin:                ar10
#max_power:          1.0
#kick_start_time:    0.1
#hard_pwm:           0



[SKIP_heater_fan hotend]
pin:                ar11
max_power:          1.0
kick_start_time:    0.1
hard_pwm:           0
heater:             heater 0
heater_temp:        50.0
fan_speed:          1.0

########################################
[mcu]
#serial:         /dev/serial0 ; Due port
serial:         /dev/ttyACM0 ; Due port
#serial:         /dev/ttyUSB0 ; Due port
;serial:         /tmp/klipper_host_mcu
baud:           115200
pin_map:        arduino
restart_method: arduino

[mcu hotend_remote]
serial:         /dev/ttyUSB0 ; Arduino Nano port
baud:           115200
pin_map:        arduino
restart_method: arduino

[printer]
name:           OULWare
kinematics:     cartesian
max_velocity:   200
max_accel:      2500
max_accel_to_decel_ratio: 1.0
#max_accel_to_decel: 1500
max_z_velocity: 5
max_z_accel:    30
motor_off_time: 600
junction_deviation: 0.2 ; default 0.02
require_home_after_motor_off: false
allow_move_without_home:      true
;sw_limit_check_enabled:       false


[idle_position]
idle_position_x:		10.0
idle_position_y:		10.0
idle_position_z_lift:		5.0
idle_position_travel_speed:	2000


[gcodes.arch]

[gcodes.retract]
test = false

[virtual_sdcard]
path: ~/.octoprint/uploads/


[hostcmd]
commands: 
  list = ls -al
  echo = echo "this is a test"

**Comment by jakep82** [comment]
This a config file for the Cruwaller/OulWare fork of Klipper.  It's heavily modified from mainline Klipper so you aren't going to be able to get support here.

**Comment by tuwwe** [comment]
Thats i have oulware board and here is pins easy  modify but it doesnt matter what config i put it says same problem

**Comment by jakep82** [comment]
If you installed from this Git repository you need to create your own custom config file.  I have an OULWare board and that's what I did.  The config file your using will only work if you installed from the here [https://github.com/OULWare/klipper](url).

**Comment by obelisk79** [comment]
definitely an issue with your config file. looks like all of the section headers are non-standard and that is most likely the source of your kinematics error. I got the exact same error when I tried to organize the config file for better readability using tab characters (aka unexpected things in the config text).

**Comment by gdachs** [comment]
@obelisk79: the error message claims: `NoOptionError: No option 'endstop_pin' in section: 'stepper_x'`
and he has really no option "endstop_pin" in the config. So why to look for other reasons?

**Comment by obelisk79** [comment]
@gdachs If you look where he re-posted his config a second time, the endstop pin appears to be defined. so I offered, based on my own experience that it may be a formatting/syntax error.

**Comment by tuwwe** [comment]
I have been fighting with config file, and always come other error , tryed others working configs what have done to oulware board but doesnt work on my klipper, i dont try drive stepper only tryed status and then i get error

**Comment by tuwwe** [comment]
=============== Log rollover at Sat Aug 18 13:37:43 2018 ===============
INFO     root :: Starting Klippy...
INFO     root :: Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.5.0-423-g899b180'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.13 (default, Nov 24 2017, 17:33:09) \n[GCC 6.3.0 20170516]'
INFO     printer.gcode :: queue fileno <Queue.PriorityQueue instance at 0x75a47210>
INFO     printer :: Start printer at Sat Aug 18 13:37:44 2018 (1534588664.7 7.4)
INFO     config :: ===== Config file =====
[driver drv8825_x]
type = DRV8825
microsteps = 32

[driver drv8825_y]
type = DRV8825
microsteps = 32

[driver tmc2130_x]
type = TMC2130
ss_pin = ar34
spi_mode = 3
spi_speed = 8000000
current = 1000.0
microsteps = 32
mode = stealthChop
diag0_out = temp_prewarn
diag1_out = stall
diag0_active_high = 1
diag1_active_high = 1
interpolate = 0
sensor_less_homing = 1
stealth_max_speed = 100
stall_threshold = 3

[driver tmc2130_y]
type = TMC2130
ss_pin = ar32
spi_mode = 3
spi_speed = 8000000
current = 800.0
microsteps = 32
mode = stealthChop
diag0_out = temp_prewarn
diag1_out = stall
diag0_active_high = 1
diag1_active_high = 1
interpolate = 1
sensor_less_homing = 1
stealth_max_speed = 100
stall_threshold = 10

[stepper_x]
driver = tmc2130_x
motor_step_angle = 1.8
pitch = 2.
teeths = 16.
step_pin = ar38
dir_pin = ar36
enable_pin = ar40
endstop_min_pin = ar54
endstop_max_pin = ar55
position_min = 0
position_max = 220
position_endstop = 0
homing_offset = 0
homing_speed = 40
homing_direction = min
homing_retract_dist = 0

[stepper_y]
driver = tmc2130_y
motor_step_angle = 1.8
pitch = 2.
teeths = 16.
step_pin = ar28
dir_pin = ar26
enable_pin = !ar30
endstop_min_pin = ar56
endstop_max_pin = ar57
position_min = 0
position_max = 200
position_endstop = 0
homing_offset = 0
homing_speed = 40
homing_direction = min
homing_retract_dist = 0

[driver tmc2100_z]
type = TMC2100
microsteps = 16

[stepper_z]
driver = tmc2100_z
motor_step_angle = 1.8
pitch = 2.
teeths = 1.
gear_ratio = 1.0
step_pin = ar23
dir_pin = ar29
enable_pin = ar25
endstop_min_pin = ar58
endstop_max_pin = ar59
position_min = 0
position_max = 200
position_endstop = 0
homing_pos_x = 10
homing_pos_y = 10
homing_offset = 0
homing_speed = 3
homing_direction = min
homing_retract_dist = 5.
homing_retract_dist_after = 10.

[SKIP_extruder0]
step_pin = ar44
dir_pin = ar42
enable_pin = ar46
steps_per_mm = 837
nozzle_diameter = 0.400
filament_diameter = 1.750
heater = heater 1
min_extrude_temp = 170
pressure_advance = 0.05
max_extrude_cross_section = 99.0

[extruder1]
step_pin = ar41
dir_pin = ar39
enable_pin = !ar43
steps_per_mm = 837
nozzle_diameter = 0.400
filament_diameter = 1.750
heater = heater 0
min_extrude_temp = 170
pressure_advance = 0.05
max_extrude_cross_section = 99.0

[sensor hotend_rtd]
sensor_pin = ar47
sensor_type = MAX31865
rtd_nominal_r = 100
rtd_reference_r = 430
rtd_num_of_wires = 2
rtd_use_50hz_filter = false
spi_mode = 1
spi_speed = 8000000
min_temp = 0
max_temp = 300

[sensor hotend_therm_k]
sensor_pin = ar47
sensor_type = MAX31856
tc_type = K
tc_use_50hz_filter = false
tc_averaging_count = 1
spi_mode = 1
spi_speed = 8000000
min_temp = 0
max_temp = 300

[sensor hotend1_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog9
min_temp = 0
max_temp = 270

[sensor hotend2_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog10
min_temp = 0
max_temp = 270

[sensor bed_ntc]
sensor_type = NTC 100K beta 3950
sensor_pin = analog11
min_temp = 0
max_temp = 120

[heater 0]
sensor = hotend1_ntc
heater_pin = ar7
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
protect_period_heat = 20
protect_hysteresis_heat = 2
protect_period = 10
protect_hysteresis_runaway = 10

[heater bed]
sensor = bed_ntc
heater_pin = ar8
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
protect_period_heat = 20
protect_hysteresis_heat = 4
protect_period = 10
protect_hysteresis_runaway = 10

[fan 0]
pin = ar10

[heater_fan hotend]
pin = ar11
max_power = 1.0
kick_start_time = 0.1
hard_pwm = 0
heater = heater 0
heater_temp = 50.0
fan_speed = 1.0

[mcu]
serial = /dev/ttyACM0
baud = 250000
pin_map = arduino
restart_method = arduino

[printer]
name = OULWare
kinematics = cartesian
max_velocity = 350
max_accel = 2500
max_accel_to_decel_ratio = 1.0
max_z_velocity = 20
max_z_accel = 30
motor_off_time = 600
junction_deviation = 0.2
require_home_after_motor_off = false
allow_move_without_home = true

=======================
INFO     printer.toolhead :: toolhead 'printer' created
INFO     printer.stepper_x :: steps per mm 200.0 , step in mm 0.005
INFO     printer.stepper_y :: steps per mm 200.0 , step in mm 0.005
INFO     printer.stepper_z :: steps per mm 1600.0 , step in mm 0.000625
INFO     printer.toolhead :: Idle position: X:0.0 Y:0.0 Zlift:0.4
INFO     printer.toolhead :: Kinematic created: cartesian
INFO     printer.toolhead :: max_accel: 2500.0
INFO     printer.toolhead :: max_accel_to_decel: 2500.0
INFO     printer.extruder1.extruder1 :: steps per mm 837.0 , step in mm 0.00119474313023
INFO     printer.extruder1 :: Extruder max_extrude_ratio=41.159417
ERROR    printer :: Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 303, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 273, in _read_config
    self._try_load_extensions('gcodes', 'load_gcode', config)
  File "/home/pi/klipper/klippy/klippy.py", line 251, in _try_load_extensions
    init_func(self, config)
  File "/home/pi/klipper/klippy/gcodes/gui_stats.py", line 395, in load_gcode
    GuiStats(printer, config)
  File "/home/pi/klipper/klippy/gcodes/gui_stats.py", line 16, in __init__
    self.babysteps = printer.lookup_object('babysteps')
  File "/home/pi/klipper/klippy/klippy.py", line 202, in lookup_object
    raise self.config_error("Unknown config object '%s'" % (name,))
Error: Unknown config object 'babysteps'
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 303, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 273, in _read_config
    self._try_load_extensions('gcodes', 'load_gcode', config)
  File "/home/pi/klipper/klippy/klippy.py", line 251, in _try_load_extensions
    init_func(self, config)
  File "/home/pi/klipper/klippy/gcodes/gui_stats.py", line 395, in load_gcode
    GuiStats(printer, config)
  File "/home/pi/klipper/klippy/gcodes/gui_stats.py", line 16, in __init__
    self.babysteps = printer.lookup_object('babysteps')
  File "/home/pi/klipper/klippy/klippy.py", line 202, in lookup_object
    raise self.config_error("Unknown config object '%s'" % (name,))
Error: Unknown config object 'babysteps'


this is what i get now

**Comment by AxMod3DPrint** [comment]
Unfortunately, as you are using the OULWare fork, we really cannot help here. This is throwing an error regarding babystepping `Error: Unknown config object 'babysteps'` which is something that is not included in the Master of Klipper. You are better off posting on the OULWare fork for help with this.

**Comment by gdachs** [comment]
@tuwwe learn to attach the logfile instead of pasting it to the message.
Anyway, as you can see my advice did help. You get now another error, I have only no idea why you don't see it. 
It seems rather obvious, it says: "Error: Unknown config object 'babysteps'"
So remove it from the config.

**Comment by tuwwe** [comment]
Srry about that, im new here and dont know all tricks here, i would remove it from config but i dont have it in config, only babysteps.py in gcodes folder

**Comment by obelisk79** [comment]
Post your config in pastebin

**Comment by gdachs** [comment]
@tuwwe: sorry you are right, I misread the error message. As you got told now multiple times, you are using a fork of klipper that is incompatible with this from KevinOConnor. You should ask the owner of this fork for support.
