### ISSUE TITLE
Mesh Bed Leveling Save Feature For Manual Probe

### ISSUE THREAD

**Issue by ygtc** [KevinOConnor/klipper#554]
Hi, i love to see mesh bed calibration feature and i want to ask question or maybe request i can't realize.

I m using mesh bed leveling with manual probe so there is no pnp,capacitive sensor so when i calibrate my bed and create mesh, when i restart firmware, my current mesh is gone.Is there a setting for keep forever like bed tilt? Or we have to generate mesh every time when reboot? 

Keep up to great work! Thank you from now:)

**Comment by ygtc** [comment]
#555 
That's what i m talking about:)
@Arksine

**Comment by derdigge** [comment]
+1 for mesh safing

**Comment by lenne0815** [comment]
That would be great !

**Comment by KevinOConnor** [comment]
It should now be possible to save/restore bed mesh points (primarily as of commit b261d31e).

**Comment by ygtc** [comment]
yeah i see that. Thanks to this feature i closed issue now
