### ISSUE TITLE
PID Values return format

### ISSUE THREAD

**Issue by imrcly** [KevinOConnor/klipper#561]
When you ru a PID this is the message that is returned:

// PID parameters: pid_Kp=22.035 pid_Ki=0.786 pid_Kd=154.520
// To use these parameters, update the printer config file with
// the above and then issue a RESTART command

But the Config file expects
pid_Kp: 22.035 
pid_Ki: 0.786 
pid_Kd: 154.520

Would it be difficult to change the resulting output format to read like the other calibration routines : 
// PID parameters: pid_Kp: 22.035 pid_Ki: 0.786 pid_Kd:154.520
// To use these parameters, update the printer config file with
// the above and then issue a RESTART command

**Comment by KevinOConnor** [comment]
The config file will take either "=" or ":" as separator between field name and value.  Ultimately we want PID_CALIBRATE to support saving/restoring values to the config.  That will likely happen soon as that general support is needed for some other important features.

-Kevin
