### ISSUE TITLE
Allways let motors on?

### ISSUE THREAD

**Issue by derdigge** [KevinOConnor/klipper#572]
Hello.

How to set stay motors on? If Z falls down on motors off. I went throug example configs and found nothing regarding to this.

Thanks.

**Comment by StefanMeGit** [comment]
# Idle timeout. An idle timeout is automatically enabled - add an
# explicit idle_timeout config section to change the default settings.
#[idle_timeout]
#gcode:
#   A list of G-Code commands (one per line) to execute on an idle
#   timeout. The default is to run "M84".
#timeout: 600
#   Idle time (in seconds) to wait before running the above G-Code
#   commands. The default is 600 seconds.


From the example-extras

**Comment by derdigge** [comment]
@StefanMeGit 

Yes saw this but i dont wand to turn them off, not increasing a timeout.

[idle_timeout]
gcode:

so this will do nothing when timeout reached?
Or set timeout to 0?

**Comment by StefanMeGit** [comment]
Give it a try... set the timer to 10 seconds and leave the code section empty. Should work.

**Comment by derdigge** [comment]
yes it did. Great. Thank you
