### ISSUE TITLE
Feature Request: E-Stop should skip the printer queue and stop immediately

### ISSUE THREAD

**Issue by dushyantahuja** [KevinOConnor/klipper#583]
E-Stop should skip the printer queue and stop the printing immediately. I think this would be easier on Klipper than on Marlin. Though, not sure how right I am.

**Comment by KevinOConnor** [comment]
Klipper does handle M112 requests as soon as they arrive.  If you're having an issue with this, you should attach the Klipper log file as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by dushyantahuja** [comment]
Please see attached.
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/2338111/klippy.log.zip)

**Comment by KevinOConnor** [comment]
I don't see any M112 issued in that log.  The procedure for issuing the M112 is described at: https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md#verify-m112

Run through that procedure and then forward the log from that.
-Kevin

**Comment by dushyantahuja** [comment]
Closing this ticket - M112 was not getting issued correctly in my instance. Octoprint was waiting for the print to get cancelled before issuing the M112.
