### ISSUE TITLE
Delta config: Tower offset?

### ISSUE THREAD

**Issue by balaji-ramani** [KevinOConnor/klipper#584]
I have a delta printer that I would like to move to klipper, but the towers have an offset and I don't find a configuration that allows for that.

**Comment by blaskkaffe** [comment]
Offset like in diferent distances from the middle or from each other?

**Comment by balaji-ramani** [comment]
I am referring to the delta radius of each of the tower being slightly different. In smoothie it is set with M665 A B C settings.

**Comment by KevinOConnor** [comment]
The delta radius, arm lengths, and endstop positions can all be individually configured.  An offset is implemented by adding the value in and then configuring the printer with the absolute value.  See the config/example-delta.cfg file the details.

-Kevin

**Comment by balaji-ramani** [comment]
I looked at config/example-delta.cfg and the code.  I see that arm length and endstop position can be set individually, but there is just one config value for radius.  Am I missing something?

**Comment by KevinOConnor** [comment]
There is only one radius.  (The radius and the tower angles define where the towers are relative to each other.)  If you've got a tower offset of some kind it is likely an endstop position offset.

It would help if you could include the log file of what you've tried in Klipper along with the explicitly smoothie configuration that you use.

-Kevin

**Comment by blaskkaffe** [comment]
A picture or info of in what whay they are offset would be helpful

**Comment by balaji-ramani** [comment]
This page has a diagram that describes the issue better - http://forum.seemecnc.com/viewtopic.php?t=8698&start=25#p72862.

In the above diagram, due to a build issue the distance of the A, B and C towers on my printer are not the same.  Having the capability to adjust for that in the firmware has allowed me to print dimensionally correct parts.

**Comment by KevinOConnor** [comment]
Klipper doesn't support that.  It's just a (confusing) way of specifying the tower angles - changing the distance of one tower is equivalent to changing the angles of the other two towers.

-Kevin

**Comment by frankvdh** [comment]
Changing a tower's position is the same mathematically as changing the
printer radius plus changing the towers' radial positions.

If one or more towers is moved from its ideal position (120 degree angle
from other towers and same radius from the ideal centre) in any direction
(including radially), the 3 tower points describe a new circle with a
different radius and centre from the ideal. The tower points are not 120
degrees apart relative to the new centre. So, if you can correct for radius
and tower angle, you can correct for any tower position error (unless the 3
towers are in a straight line ;) ).

The Delta calibrator at escher3d.com allows you to calculate the tower
angles and radius.

I don't know much about CNC, but I guess that the absolute position of the
centre is possibly important there? But for 3D printing, it's not really an
issue.

Frank

**Comment by balaji-ramani** [comment]
Thank you for the explanation, Frank.  That cleared it up for me.  I will close this.

**Comment by KevinOConnor** [comment]
FYI, there is an enhanced calibration mechanism for Klipper that is being tested.  This enhanced mechanism supports calibration that take into account XY part dimensions.  See #615 for details.

-Kevin
