### ISSUE TITLE
Delta_calibrate

### ISSUE THREAD

**Issue by pakogil** [KevinOConnor/klipper#591]
Hello, sorry for my English, google traslate.
I have an Anycubic Delta Kossel Plus, I already have all the software and firmware installed on the Trigorilla board. Now I'm stuck on the calibration issue "DELTA_CALIBRATE". I have the test sensor placed in the printer and it detects perfectly when I hit it "query_pulse", but when I send it "delta_calibrate", it goes down and does not raise the head.
I'm sure something is missing but I do not know wha.

**Comment by ozligia** [comment]
Hi, @pakogil.
Have the same printer with custom nozzle probe.
Please find my config attached to compare with, or post your config for us to examine.
[printer.txt](https://github.com/KevinOConnor/klipper/files/2337490/printer.txt)

**Comment by KevinOConnor** [comment]
Please attach the Klipper log file (the config doesn't really help us much) - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by pakogil** [comment]
Thanks for answering. I already managed to print for the first time. I had the pin of the probe upside down. I already managed to do the Delta_Calibrate.
What is the way to calibrate the z_offset, I put the one I had in Marlin and it seems to work.
How can I calibrate the z_offset for Klipper?
Thank you again, regards

P.S. The impression I made was a gcode generated with Cura and I look great.
