### ISSUE TITLE
Unable to translate pin name: config_end_stop

### ISSUE THREAD

**Issue by ifUpEth0** [KevinOConnor/klipper#602]
I am working to upgrade my existing corexy on klipper to have 3 z steppers. I added another mcu to accomplish this. I cannot get the probe part to work.
[probe]
pin: ^!extra_mcu:ar18
....
[stepper_z]
....
endstop_pin: probe:z_virtual_endstop
......

error: Unable to translate pin name: config_end_stop oid=3 pin=ar18 pull_up=1 stepper_count=3

[klippy.log](https://github.com/KevinOConnor/klipper/files/2346340/klippy.log)

**Comment by KevinOConnor** [comment]
You've misspelled "arduino" in the "[mcu extra_mcu]" section.

-Kevin

**Comment by ifUpEth0** [comment]
Thank you my mistake.
