### ISSUE TITLE
Extending module get_status method?

### ISSUE THREAD

**Issue by mcmatrix** [KevinOConnor/klipper#606]
@KevinOConnor 
Do I understand it correctly that a module `get_status` method output can be freely extended?

For example, the gcode module outputs currently only `speed_factor` and `busy`, would be nice to extend it with additional info like `GET_POSITION` is outputting (home, base etc). 
It makes then possible to use `SET_GCODE_OFFSET` in the menu with absolute coordinates.

For `output_pin` and `servo` module we should add `get_status` method and output `last_value`
Currently, the menu functionality is peeking that value directly.

**Comment by KevinOConnor** [comment]
> Do I understand it correctly that a module get_status method output can be freely extended?

That's the intent.

> For output_pin and servo module we should add get_status method and output last_value
Currently, the menu functionality is peeking that value directly.

Yes, that should be corrected then.

-Kevin

**Comment by mcmatrix** [comment]
Thanks, just wanted to be sure that I’m on the right track.
