### ISSUE TITLE
TMC2130  (no) missing steps

### ISSUE THREAD

**Issue by sniperlucian** [KevinOConnor/klipper#608]
I wrote a small python script to test at which speed the TMC starts loosing steps. However, even it clearly start skipping - DUMP_TMC shows:   

LOST_STEPS:     00000000\n

before I start digging - is this a know issue? 

@KevinOConnor 
I would like extend the script to auto optimize **stealthchop_threshold**  and **run_current**. Is here a way to change these values at runtime?

Is here a way to time stamp  DUMP_TMC, to trace force levels during acceleration?

#################################################################

import serial

s = serial.Serial("/dev/tnt1",baudrate=2500000,timeout=1)

#s.write("FIRMWARE_RESTART\n".encode("latin-1"))
#print(s.readlines())
#time.sleep(2)

def send(val):
    s.write(val.encode("latin-1"))
    
    
def wait_ok():
    
    val = ""
    while(val != "ok\n".encode("latin-1")):
         val = s.readline()
         print(val)
#send("G28 X0\n")
#wait_ok()

send("G0 X100 y100 f20000\n")
wait_ok()

send("M400\n")
wait_ok()

send("G0 X300 y300 f20000\n")
wait_ok()

send("M400\n")
wait_ok()

send("DUMP_TMC STEPPER=stepper_x\n") 
wait_ok()
#s.close()

**Comment by KevinOConnor** [comment]
The DUMP_TMC command just returns the registers on the stepper driver.  You'll need to read the Trinamic specifications to determine what they contain.

If you're looking to change the driver settings, you'll need to make code changes to klippy/extras/tmc2130.py (see the get_register and set_register methods).  If you want precise timing, you'll also need to make code changes - the `params` returned by the `self.spi_send_cmd.send()` call has both a transmit and receive timestamp in it.

-Kevin
