### ISSUE TITLE
Anet A8 LCD Button Pins

### ISSUE THREAD

**Issue by davezero78** [KevinOConnor/klipper#609]
Hello, what are the

encoder_pins: ^?, ^?
click_pin: ^!?

 for the display on the Anet A8?
Board: ATmega 1284p

Sorry for my bad English...

**Comment by oderwat** [comment]
You don't need the pins for the display itself to work. They are used for the menu. But the ANET A8 does not have an rotary encoder. Just the 4 way and enter buttons. Which are implemented as analog input with different resistors for the different buttons. I don't know if that input type is supported for the menu so far. I wrote part of the Marlin version of those buttons as they are implemented now.

You may want to buy an A6 display which works with the Anet A8 board or get a custom rep-rap display and use an adapter like the one I published some time ago (https://www.thingiverse.com/thing:2103748). There are other wirings possible too.

P.S.: I don't have an A8 here anymore.

**Comment by mcmatrix** [comment]
> Which are implemented as analog input with different resistors for the different buttons. I don't know if that input type is supported for the menu so far.

Currently, the menu is only supporting separate buttons connected to pin or encoder using two pins.

**Comment by aeropic** [comment]
could we imagine a mod using the ANET display as it is and a separate rotary encoder or 4 buttons matrix wired on the pi GPIO pins ?

**Comment by KevinOConnor** [comment]
It doesn't look like anyone has any immediate plans to implement this.  So, I'm going to close this for now.

**Comment by KevinOConnor** [comment]
This support was added to Klipper.

-Kevin
