### ISSUE TITLE
Crealty Ender 3 unknow command M205 over and over and over

### ISSUE THREAD

**Issue by dotps1** [KevinOConnor/klipper#610]
first off, great product and thank you very much for providing and supporting it.

I got this up and running a few days ago, and I also installed the octopi plug in,  and I noticed I am getting a constant repeting error:

`Unknown Command: M205`

I peeked at the log and I don't even see that in there
[klippy (2).log](https://github.com/KevinOConnor/klipper/files/2354783/klippy.2.log)

here is from the octoprint klipper plugin:
![image](https://user-images.githubusercontent.com/1016996/45125158-3ed2f680-b13b-11e8-9345-3bf2541288f5.png)

thanks for any help!

**Comment by oderwat** [comment]
You may want to read: https://github.com/mmone/OctoprintKlipperPlugin/issues/22

**Comment by dotps1** [comment]
looks like this releated to the plug in and not klipper, thanks!
