### ISSUE TITLE
MKS sBase and RepRapDiscount 128x64 Full Graphic Smart Controller

### ISSUE THREAD

**Issue by rtbon** [KevinOConnor/klipper#612]
Hello, I'm looking to config RepRapDiscount 128x64 Full Graphic Smart Controller with Klipper.
I use a MKS sBase 1.3. After lot of trying nothing seems to work.
My LCD config from smoothie was:

> panel.lcd                                   reprap_discount_glcd     #
panel.spi_channel                           0                 # SPI channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                            0.16              # SPI chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                         3.25!^            # Encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                         3.26!^            # Encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                      1.30!^            # Click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                              1.31              # Pin for buzzer      ; GLCD EXP1 Pin 1

Convert to Klipper it looks like that: 

> [display]
lcd_type:st7920
cs_pin: P0.16 
sclk_pin: P0.14
sid_pin: P0.18
encoder_pins: ^P3.25, ^P3.26
click_pin: ^!P1.30

I've made this to find these pins:
![pinout](https://user-images.githubusercontent.com/43032780/45152076-4e504f00-b1d0-11e8-977b-653e41da273b.jpg)

But the screen stay lighted and nothing appear…
I did something wrong or it's not compatible ?
Thank you !

**Comment by klHaribo** [comment]
hi! have you tried to flip the cables on the board? with fliped plugs my working config is:
# "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays
[display]
lcd_type: st7920
cs_pin: ar16
sclk_pin: ar23
sid_pin: ar17

**Comment by KevinOConnor** [comment]
We need the klipper log file in order to assist - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by rtbon** [comment]
Thanks for your answer @klHaribo, but I already tried to flip plugs and the screen don't light up.
So @KevinOConnor here my klipper log file
[klippy.log](https://github.com/KevinOConnor/klipper/files/2361019/klippy.log)

**Comment by KevinOConnor** [comment]
The log output doesn't look right.  Can you reproduce the problem with an unmodified version of Klipper and post the log from that?

-Kevin

**Comment by zerg32** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2363932/klippy.log)

May be my log will be more useful.

Same issue for me. Works fine with smoothieware but doesnt work with Klipper.

**Comment by KevinOConnor** [comment]
I think the mks sbase pinout has a typo in it.  What happens if you use:
```
[display]
lcd_type = st7920
cs_pin = P0.16
sclk_pin = P0.15
sid_pin = P0.18
```

**Comment by rtbon** [comment]
Thank you very much, you make my day, it works !!!

**Comment by zerg32** [comment]
perfect. also works for me

**Comment by KevinOConnor** [comment]
Thanks.  I added a sample to the generic-smoothieboard.cfg example file (commit b595c3e4).

-Kevin

**Comment by mabl** [comment]
If somebody ever runs into the same issue:

I found that the connector pins are reversed on my sbase 1.3. Everything works when forcing each of the two EXT connectors reversely into its respective socket. 

To avoid noise from the piezo speeker, also define it as an output to avoid it from floating as an input.

```
[static_digital_output beeper]
pins: !P1.31
```

**Comment by bshowket** [comment]
can anyone tell me which pin is 
sid_pin in RepRapDiscount 128x64 Full Graphic? I can't seems to find anything in pinout of exp1 or exp2.

**Comment by shaiss** [comment]
I can confirm this works and have a close to working sbase setup.  We should have an example config for the sbase with at least this quirk noted in there if nothing else
