### ISSUE TITLE
Tevo Tornado MKS Base 1.4 and bltouch

### ISSUE THREAD

**Issue by Hanks552** [KevinOConnor/klipper#627]
i dont know the servo pin and probe pin... im a little lost... So im wondering if anybody can help me or have the profile for the tevo tornado with MKS_Base 1.4 with bltouch. Thanks

Im using generic-ramps.cfg as a start point, i only changed the inverted endstop in 1 axis and changed the bed size to 300x300x400

**Comment by J-charles-C** [comment]
I,

**In your stepper Z :**
[stepper_z]
**endstop_pin: probe:z_virtual_endstop**
#endstop_pin: z_virtual_endstop

**For Bl-Touch :**
# Define the BLTouch servo
[servo bltouch]
pin: Pin of your card for SERVO1 (D11)
maximum_servo_angle: 180
minimum_pulse_width: 0.0006
maximum_pulse_width: 0.0024

# Define a probe using the BLTouch
[probe]
pin:  Pin of your card for Zmin endstop
z_offset: 1.803
activate_gcode:
   SET_SERVO SERVO=bltouch ANGLE=10
   SET_SERVO SERVO=bltouch ANGLE=60
   G4 P200
deactivate_gcode:
   SET_SERVO SERVO=bltouch ANGLE=90
  G4 P200


best

**Comment by J-charles-C** [comment]
Yes it servo1 pin. D11 or D12

best

**Comment by Hanks552** [comment]
Thanks for your reply, but i just dont understand the pinout numbers... because they repeat in other places, thats crazy
