### ISSUE TITLE
Heater extruder not heating at expected rate after FIRMWARE_RESTART

### ISSUE THREAD

**Issue by mgth** [KevinOConnor/klipper#630]
If I send a firmware restart while hotend is hot. And then ask for 200°C the heater will go up for about 10°C. and then fail with "Heater extruder not heating at expected rate". the rate was actually slower than usual.

But if I wait the temp to reach below 100°C it works ok.
This is very reproducible.

**Comment by mgth** [comment]
sorry, capture failed
![image](https://user-images.githubusercontent.com/2568124/45266464-9cc54e00-b45b-11e8-965d-769c649e8f87.png)

**Comment by jakep82** [comment]
You need to post your log file. You probably just need to adjust the heating_gain and/or check_gain_time settings.

**Comment by KevinOConnor** [comment]
As mentioned, one can tune the verify_heater sections to avoid this.  Another option is to not rapidly heat, restart, and reheat.
