### ISSUE TITLE
Quick change of Z-offset

### ISSUE THREAD

**Issue by Avalonnw** [KevinOConnor/klipper#632]
More like a question (and probably a stupid one as well) than issue: If I calibrated my delta and did an extended calibration as well, but now need to change nozzle so the offset might be a bit different, is there a way of measuring/changing this offset without recalibrating everything again?

**Comment by SrGeek** [comment]
Do you mean the OctoKlipper plugin? or the Custom Command Editor plugin?

**Comment by J-charles-C** [comment]
as you want.
