### ISSUE TITLE
Internal error on command:"DELTA_CALIBRATE"

### ISSUE THREAD

**Issue by Avalonnw** [KevinOConnor/klipper#642]
I'm trying to re-run delta calibration (basic) on the experimetal extended calibration branch. Got this error after probing all points:
`Recv: // probe at -0.004,0.002 is z=17.269275
Recv: // probe at 0.000,104.494 is z=17.087914
Recv: // probe at -85.733,49.507 is z=16.967651
Recv: // probe at -80.974,-46.747 is z=17.266330
Recv: // probe at -0.000,-76.994 is z=17.223743
Recv: // probe at 71.447,-41.253 is z=17.164197
Recv: // probe at 76.209,43.998 is z=17.001703
Recv: !! Internal error on command:"DELTA_CALIBRATE"
Recv: ok`
Heatbreak fan turns on after that.
Log attached.

[klippy.txt](https://github.com/KevinOConnor/klipper/files/2374993/klippy.txt)

**Comment by KevinOConnor** [comment]
Oops - should be fixed now (commit 20230c43).

cd ~/klipper ; git fetch ; git checkout origin/work-delta-calibrate-20180828 ; sudo service klipper restart

-Kevin
