### ISSUE TITLE
Stepper motors too hot

### ISSUE THREAD

**Issue by rtbon** [KevinOConnor/klipper#649]
Hello,
Any idea how can I reduce current of my mks sbase stepper motor ? 
There are some DRV8825 drivers and there are hot, too hot for PLA.
Thank you.

**Comment by rtbon** [comment]
Ok sorry, this works fine also for DRV8825
```
[mcp4451 stepper_digipot1]
i2c_address: 88
# Scale the config so that wiper values can be specified in amps.
scale: 2.25
# wiper 0 is X (aka alpha), 1 is Y, 2 is Z, 3 is E0
wiper_0: 1.0
wiper_1: 1.0
wiper_2: 1.0
wiper_3: 1.0
```

**Comment by scarecrow2k6** [comment]
Hi, were you using the MKS Sbase 1.3? Sorry can you please tell me exactly what perimeter did you use to reduce the current? Thanks.
