### ISSUE TITLE
cura slicer

### ISSUE THREAD

**Issue by SrGeek** [KevinOConnor/klipper#654]
didnt know where to put this question.  what firmware do i select when using cura?  klipper is not an option.

**Comment by AxMod3DPrint** [comment]
It's cross compatible with both Marlin and Repetier

**Comment by SrGeek** [comment]
Thank you I'm closing this

**Comment by lmcbmai** [comment]
I am seeing literally thousands of M205 that Cura 3.6.0 adds to gcode files when Marlin firmware is selected. Klipper says M205 is unknown/unsupported gcode. Is it OK to ignore these errors?
Thanks
