### ISSUE TITLE
Printer keeps on pausing during prints

### ISSUE THREAD

**Issue by LazaroFilm** [KevinOConnor/klipper#669]
My printer keeps on pausing for about 1 second randomly during print. 
I have a Pi3 and Ramps 1.4 on HyperCube Evolution (CoreXY)
According to the graph the Host buffer is saturating?? 
This print was a lot of circles. 

<img width="530" alt="screen shot 2018-09-18 at 2 42 48 pm" src="https://user-images.githubusercontent.com/18351100/45709110-2908fc80-bb51-11e8-93cb-112cf10ce296.png">

[klippy.log](https://github.com/KevinOConnor/klipper/files/2394110/klippy.log)

**Comment by jakep82** [comment]
In my experience this is an Octoprint issue.  It can't process and send the gcode fast enough, particularly when you printing circles with a lot of short line segments.  The solution is enabling the virtual SD feature in Klipper which allows Klipper to read the gcode directly, and removes Octoprint from the middle.

**Comment by LazaroFilm** [comment]
Ok, I used the Virtual SD and indeed it fixed the pausing. Now, I lose all the awesome aspect of Octoprint when I do that. Should I report a bug on Octoprint? Is there something else that could be done to help speed the code sent to avoid the pauses? Is there a speed setting in Octoprint to modify? I'm printing at 60mm/s which is not a ludicrous speed.

**Comment by jakep82** [comment]
This has been a known issue in Octoprint for well over 4 years.  The only solution right now is to use the virtual SD feature.  Their was discussion about a possible fix coming in 1.4.0, but that conversation is nearly a year old.

https://github.com/foosel/OctoPrint/issues/450

**Comment by jakep82** [comment]
I should also note leaving the issue open here won't accomplish anything.  The problem is with Octoprint, not Klipper.  Many people running Marlin also have this problem with Octoprint.

**Comment by jimfunk** [comment]
I recently had this issue on a much faster CPU than on the Pi3 (Pentium E5700). It was definitely Octoprint, since it was consuming a full CPU core while klippy consumed about 20%, but I solved it by disabling most of the plugins I had enabled. I suspect it might have been a print time estimator, but I can't be sure since I disabled a bunch of them.

**Comment by LazaroFilm** [comment]
Okay. That’s too bead. Maybe we should open a ticket on the Octoprint side. If it’s not already there. I’ll close this for now.

**Comment by ddacunha** [comment]
I confirm that in my case, it is an OctoPrint issue when printing cylinders in vase mode. The issue appeared after installing [DisplayLayerProgress](https://plugins.octoprint.org/plugins/DisplayLayerProgress/) and caused pauses generating droplets effect on the cylinders. Removing the plugin fixed the issue.
