### ISSUE TITLE
(bed_mesh.py) : z_offset  -- design enhancement

### ISSUE THREAD

**Issue by aeropic** [KevinOConnor/klipper#681]
@Arksine ,
I'm playing a lot with mesh_bed levelling ! (see #638)
As I have the z probe connected to the Z end stop, I would like to avoid the double input of z_offset (one in [stepper_z] position_endstop one in [probe] section)

I found in the code the place where you warn the user if the two values are different. I then added the line marked with "<<<<<<<<<<" to force the z_offset to the endstop value, but this has no effect...
What should I add to make this work. To be clear I would like the code to act like this : 

if  Using probe as a virtual endstop, warn user if stepper_z position_endstop is different AND use the position endstop as z_offset value

Thanks in advance

def finalize(self, offsets, positions):
        global mygrid
        self.probe_params['x_offset'] = offsets[0]
        self.probe_params['y_offset'] = offsets[1]
        z_offset = offsets[2]
        if self.probe_helper.get_last_xy_home_positon() is not None \
                and self.z_endstop_pos is not None:
            # Using probe as a virtual endstop, warn user if the
            # stepper_z position_endstop is different
            if self.z_endstop_pos != z_offset:
                z_msg = "bed_mesh: WARN - probe z_offset is not" \
                        " equal to Z position_endstop\n"
                z_msg += "[probe] z_offset: %.4f\n" % z_offset
                z_msg += "[stepper_z] position_endstop: %.4f" \
                    % self.z_endstop_pos
                logging.info(z_msg)
                self.gcode.respond_info(z_msg)
                z_offset = self.z_endstop_pos    <<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by aeropic** [comment]
Well, I don't know exactly what I did yesterday, but it seems the above patch is working fine !

When the "endstop_pin" is set to "probe:z_virtual_endstop" and the value of stepper_z position_endstop is different to z_offset, I would advice to:
- warn the user as today is the code
- force the z_offset to stepper_z position_endstop and warn the user ...

What are the advantages of having two values for the same parameter (when virtual endstop is used) ? I think it is misleading and when adjusting the z_offset, it is quite easy to forget to patch the second value...

**Comment by aeropic** [comment]
By the way, how would behave the print if a "SET_GCODE_OFFSET Z=0.1" is emitted during print of the first layer (just to baby step the z offset after the bed_mesh levelling has been performed) ?

**Comment by Arksine** [comment]
I initially did automatically use the endstop position, and this was changed and discussed in PR #550.  As  you can see, Kevin would like to make the change to the default endstop position, however it would need to be done in a way as to not break BED_TILT.

The gcode offset that you describe would raise the print by .1mm.  It would behave as you would expect.

**Comment by aeropic** [comment]
Thanks Arksine ...
I read the PR#550 which indeed is the same issue.
As far as I understand, we are waiting for a future mod of BED_TILT, but by now, what would prevent doing the way  I suggest : just fixing the user's mistake by forcing the the z_offset to stepper_z position_endstop in the piece of code where the z_virtual_endstop presence is checked ?

**Comment by aeropic** [comment]
CLOSED in the last bed_mesh release .

Thanks for this !
