### ISSUE TITLE
./klipper/scripts/install-octopi.sh execule fail in raspberry pi

### ISSUE THREAD

**Issue by WindoC** [KevinOConnor/klipper#685]
I fail at the step ./klipper/scripts/install-octopi.sh during installation. 

apt-get install virtualenv stm32flash libnewlib-arm-none-eabi gcc-arm-none-eabi binutils-arm-none-eabi return unable to locate package.

![42353745_10215297459623321_2448087623068024832_n](https://user-images.githubusercontent.com/10722906/45930400-6971db80-bf92-11e8-9376-09aaec97bd9a.jpg)

Any idea to fix that?

Thanks!

**Comment by KevinOConnor** [comment]
That's certainly odd.  You should make sure the OctoPi image is pristine (no download errors) and retry the OctoPi install from scratch.  Make sure your internet connection is working well when running the install-octopi.sh script.

-Kevin

**Comment by WindoC** [comment]
So it must use the one download from the link https://octopi.octoprint.org/latest . Right?

Are there any guide to install it from the default raspberry pi image. I Would like to use klipper but not the OctoPi.

Thanks!

**Comment by KevinOConnor** [comment]
There's some discussion on this at: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#can-i-run-klipper-on-something-other-than-a-raspberry-pi-3 .  Lots of people run Klipper on something other than OctoPi, but to do that you'll need to track down all the Linux admin steps necessary to make it work.

-Kevin
