### ISSUE TITLE
[Feature request]Is it possible to use Anet A6 default display(with rotary encoder)

### ISSUE THREAD

**Issue by Galunid** [KevinOConnor/klipper#691]
Hello, as the name of the issue states: Is it possible to use Anet A6's defualt display? If it is not possible, what would I need to do in order to implement it? Thanks in advance!

**Comment by pecirep** [comment]
It is possible, it's the same as any 12864 display, just different pin positions. I didn't want to change the pins in the config so I just used jumper cables to make an adapter, although I think you can also buy one. That gives you 3 options: adapt your config, use jumper wires, buy an adapter, the first two require checking the docs

**Comment by KevinOConnor** [comment]
If anyone has a tested config for a stock anet a8, I'm happy to add it to the example configs in the Klipper  config directory.

-Kevin

**Comment by bigmethos** [comment]
The following works for with the stock ANet A6 LCD with rotary encoder:
```
[display]
lcd_type: st7920
cs_pin: PA4
sclk_pin: PA1
sid_pin: PA3
encoder_pins: ^PD2, ^PD3
click_pin: ^!PC0

**Comment by denisyivanov** [comment]
> The following works for me with the stock ANet A6 LCD with rotary encoder:
> 
> ```
> [display]
> lcd_type: st7920
> cs_pin: PA4
> sclk_pin: PA1
> sid_pin: PA3
> encoder_pins: ^PD2, ^PD3
> click_pin: ^!PC0
> ```

could you please copy the entire config that works for you?

**Comment by bigmethos** [comment]
Hey @denisyivanov. I have included the entire config, but some of it is unlikely to work for you since I have added on a IR Z probe.

[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/3143355/printer.cfg.txt)
