### ISSUE TITLE
Default Menu

### ISSUE THREAD

**Issue by SergeyKrutyko** [KevinOConnor/klipper#698]
I am sorry for nubby question....

i found default menu in klipper/klippy/extras/display/menu.cfg 

how i can enable it ?

Thanks!

**Comment by ruevs** [comment]
It's enabled by default.
Simply provide the encoder and click pins in your configuration file.
Here is an example for a "RepRapDiscount 2004 Smart Controller" connected to a RAMPS (compatible) board:
https://github.com/KevinOConnor/klipper/blob/170b9678fba2749063023008f51ebdff7e0e0759/config/printer-anycubic-kossel-2016.cfg#L99
Here is an explanation:
https://github.com/KevinOConnor/klipper/blob/170b9678fba2749063023008f51ebdff7e0e0759/config/example-extras.cfg#L820

**Comment by SergeyKrutyko** [comment]
one more questions:

how i can disable few items on default menu ? 
how i can add personal items to menu?
i need create new own menu? or have simply patch?

**Comment by ruevs** [comment]
To remove items from the default menu you have to delete them from menu.cfg. Although re-defining them as empty in printer.cfg may also work - I am not sure, see here https://github.com/KevinOConnor/klipper/pull/500#issuecomment-412507818

Add your custom menus in printer.cfg.
Documentation:
https://github.com/KevinOConnor/klipper/blob/master/config/example-menu.cfg
An example:
https://github.com/KevinOConnor/klipper/issues/596#issuecomment-417929870

**Comment by mcmatrix** [comment]
I don't recommend to change the default menu.cfg
Next time you update Klipper's codebase your changes may be overwritten.

But you can easily overwrite default menu items.
Just redefine items with the same name in your printer config.
For example, to hide Octoprint menu just redefine it with `enable: false`
```ini
[menu __octoprint]
type: list
enable: false
name: OctoPrint
items:
    .__pause
    .__resume
    .__abort
```
To add something to the menu, you need to redefine and include your item.
For example, to add your menu to main, just define your menu items and add it to 
redefined `__main`
```ini
[menu __main]
type: list
name: Main Menu
items:
    __tune
    __octoprint
    __sdcard
    my_super_menu
    __control
    __temp
    __filament
    __prepare
    __test
```
Or you can fully define your own menu structure and use it.
under display section use `menu_root: your_menu_root_elem` attribute.

You have to be careful when redefining menus and ready to adjust your changed with default menu changes.

**Comment by SergeyKrutyko** [comment]
thanks mcmatrix, i try now!
