### ISSUE TITLE
Selecting UART3 on Trigorilla board

### ISSUE THREAD

**Issue by mbgroot** [KevinOConnor/klipper#702]
i'm use UART3 on Trigorilla to connect Raspberry Pi. 
i change CONFIG_SERIAL_PORT to 3 but after make commant it change to 0 back.
or am I changing the wrong place?

**Comment by KevinOConnor** [comment]
Code changes would be required to support UART3 on the atmega2560 (specifically, the src/avr/Kconfig file would need to be changed).

-Kevin

**Comment by mbgroot** [comment]
Thanks for the help, but it did not help.
Changed to 3 and put in the printer.cfg _/dev/serial0_ - the host does not connect to the printer.
Ports and cable are working. On firmware MK4duo everything works.

**Comment by KevinOConnor** [comment]
I added support for selecting alternate UARTs on the 2560 (commit d348f0da).  You might want to try downloading the latest code, make sure you are using an unmodified copy of Klipper, rerun "make menuconfig", recompile the firmware, and reflash the firmware.

If it still doesn't work after doing the above, then attach the full klipper log file as described at: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin

**Comment by mbgroot** [comment]
I rerun "make menuconfig", recompile the firmware, and reflash the firmware. But still don't work...

[klippy.log](https://github.com/KevinOConnor/klipper/files/2436696/klippy.log)

**Comment by KevinOConnor** [comment]
Alas, I have no further advice.  As far as we know, the code works as intended.

-Kevin
