### ISSUE TITLE
MCU 'mcu' shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by nados970** [KevinOConnor/klipper#706]
hello, my print stops with the message "mcu shutdown". I tried to flash but it did not change anything.
I tried to deactivate the pressure advance without success.

I attach my log file.

[klippy.log](https://github.com/KevinOConnor/klipper/files/2427644/klippy.log)

**Comment by KevinOConnor** [comment]
I'm not sure what's going on here, but this log shows up as identical to the log posted in issue #705.

**Comment by KevinOConnor** [comment]
Closing this pending a log of the event.
