### ISSUE TITLE
Extrude only move too long

### ISSUE THREAD

**Issue by smark-** [KevinOConnor/klipper#708]
Whenever I complete a print (or cancel it) and I try to start a new one I always get the error: " Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Extrude only move too long (-6565.890mm vs 50.000mm). It seems like klipper doesn't restart the extrusion counter after a printer is finished. The only way to keep printing it to RESTART the host.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2430862/klippy.log)

**Comment by Flupke1979** [comment]
Reset your extruder in the G-code startscript of the slicer.

**Comment by jakep82** [comment]
G92 E0

**Comment by smark-** [comment]
Thanks, this is a good work-around. I was wondering why this feature is not implemented in Klipper already.

**Comment by KevinOConnor** [comment]
This is a g-code problem.  There's nothing Klipper can do about it - all firmwares have the same requirement.

-Kevin

**Comment by LazaroFilm** [comment]
Even on Marlin you should start your GCode with resetting your extruder, that should be the first line of your start code.

**Comment by smark-** [comment]
I might have missed it, since I don't recall having to do so. If that's the case, that's not a klipper issue
