### ISSUE TITLE
gcode_macro parameters not working

### ISSUE THREAD

**Issue by lufton** [KevinOConnor/klipper#709]
I have gcode_macro section in my printer.cfg that uses parameter DELAY (from **example-extras.cfg**):
```
[gcode_macro MY_DELAY]
gcode:
	G4 P{DELAY}
```
Now I execute:
```
MY_DELAY DELAY=100
```
And get:
```
Recv: !! Error on "G4 P{DELAY}": unable to parse {
```

[klippy.log](https://github.com/KevinOConnor/klipper/files/2430919/klippy.log)

**Comment by mcmatrix** [comment]
From your log I see that your macro definition is
```ini
[gcode_macro MY_DELAY]
gcode = "G4 P{DELAY}"
```
Try to remove double quotes
```ini
[gcode_macro MY_DELAY]
gcode = G4 P{DELAY}
```

**Comment by lufton** [comment]
I think I tried both and both is not working.

**Comment by lufton** [comment]
Actually I tried:
```
gcode:
G4 P{DELAY}
```

**Comment by mcmatrix** [comment]
It seems that you don't have the latest code.
Try to update your codebase.
```
cd ~/klipper
git pull
sudo service klipper restart
```

I get the same parsing error when I use `gcode_macro.py` before the `macro improvement with parameters` change.

**Comment by mcmatrix** [comment]
Check the size of `gcode_macro.py`. It has to be ~1307 bytes.

**Comment by lufton** [comment]
Yeap, ```git reset --hard``` helped. Sorry. Closed.
