### ISSUE TITLE
Might be worth exploring: "6th-order jerk-controlled motion planning"

### ISSUE THREAD

**Issue by lenne0815** [KevinOConnor/klipper#71]
Klipper being the only feasible alternative to smoothie right now i thought about if it would be possible to one up the fantastic current planner implementation one more time; TinyGs toolpath prediction adheres even closer to mechanical reality. ( https://github.com/synthetos/TinyG/wiki/Jerk-Controlled-Motion-Explained )

Thoughts ? Possible ? Worth it ?

Merry Christmas !

**Comment by KevinOConnor** [comment]
It would indeed be interesting!  This type of acceleration is also known as s-curves - as raised in issue #57.
