### ISSUE TITLE
M112 not aborting right away

### ISSUE THREAD

**Issue by povlhp** [KevinOConnor/klipper#727]
When I send M112 during pre-heat phase, it will not abort before the temperature is reached.
Can we please have the M112 take precedence over whatever waiting we are currently doing.

Should be minor thing. Often I start preheat, then thunks about something to change in slicer, and goes back to it.

**Comment by KevinOConnor** [comment]
Klipper will react immediately to an M112 command.  If you're having an issue you need to attach the Klipper log file: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by jakep82** [comment]
I've issued an M112 during pre-heat on several occasions, and Klipper has always aborted immediately.

**Comment by povlhp** [comment]
I will do more tests, and include the log. I experienced it twice.

**Comment by KevinOConnor** [comment]
Okay - closing this for not.  I'll reopen if you have a log from the event.

-Kevin
