### ISSUE TITLE
[Feature Request] GET/SET commands to set any parameter in the .cfg file.

### ISSUE THREAD

**Issue by lar3ry** [KevinOConnor/klipper#728]
Pretty much self-explanatory.
Examples...
   GET_PARAMETER SECTION=\<section name\> PARM=\<parameter name\>
   SET_PARAMETER SECTION=\<section name\> PARM=\<parameter name\>

   GET_PARAMETER SECTION=stepper_x PARM=step_distance
   SET_PARAMETER SECTION=stepper_x PARM=step_distance

**Comment by jakep82** [comment]
Have you tried the OctoKlipper plugin for OctoPrint?  It allows you to view and edit your printer.cfg file directly through OctoPrint.  This is an awful lot of stuff to type out in a terminal when you can just view and edit the file through the web interface.

**Comment by lar3ry** [comment]
No, but I just installed it. Looks good! Thanks!
