### ISSUE TITLE
PT100 with amplifierboard on RUMBA board

### ISSUE THREAD

**Issue by kimkejser** [KevinOConnor/klipper#73]
Is it possible to use a PT100 with an E3D amplifier board, i couldn't find any description in the documentation here on GitHub.

**Comment by KevinOConnor** [comment]
On Wed, Dec 27, 2017 at 11:18:03AM +0000, kimkejser wrote:
> Is it possible to use a PT100 with an E3D amplifier board, i couldn't find any description in the documentation here on GitHub.

It would need some changes to the code.  As an initial step you could
add the following to the Sensors table in klippy/heater.py:

"PT100 INA826": { 'class': Linear, 't1': 100., 'v1': 1.52, 't2': 300., 'v2': 2.29 },

Then one could declare a sensor of "PT100 INA826" in the config.
However, this will have some temperature inaccuracies at the high
temperature range (temp > 500).

The volts and temperatures are from the wiki page at:
https://wiki.e3d-online.com/E3D_PT100_Amplifier_Documentation#Output_Characteristics

-Kevin

**Comment by kimkejser** [comment]
Ok, thank you for the fast reply. I'll give it a whirl tomorrow.
-K

**Comment by kimkejser** [comment]
It works great. Tested it yesterday.
I just added the info to the Sensors table as you described. 
Thanks :-D

**Comment by kimkejser** [comment]
It works great. Tested it yesterday.
I just added the info to the Sensors table as you described. 
Thanks :-D
