### ISSUE TITLE
Other language support for menu

### ISSUE THREAD

**Issue by ich777** [KevinOConnor/klipper#745]
@mcmatrix is it possible to change the language if yes, how? Or do i have to make my complete own custom menu?

**Comment by mcmatrix** [comment]
At the moment there's no support for the language.
You have to override the whole menu to make it appear in the different language.
Don't make changes in `menu.cfg`!
If you use the config name of the same menu item, you can add menu changes to your printer config file. Your changes will redefine an existing menu item.

**Comment by KevinOConnor** [comment]
It doesn't look like this is being worked on right now, so I'm going to close it.  I'll reopen if someone starts actively working on it.

**Comment by manu7irl** [comment]
@mcmatrix 
Hi can you explain a bit more on restructuring the menu? 
because I want to make it work in rtl language hebrew or arabic.
can it be done?
