### ISSUE TITLE
Homing with zprobe multiple samples?

### ISSUE THREAD

**Issue by derdigge** [KevinOConnor/klipper#752]
Dear all.

I am homing my printer with zprobe. Since the feature came with using multiple samples for z_tilt/bed_mesh etc. i am very happy with my probe.

Is there a way to use the multiple sample feature also for homing the z axis?

Thanks
derdigge

**Comment by KevinOConnor** [comment]
It is not currently possible to do this during homing.  However, if you always perform a bed_tilt_calibrate or bed_mesh_calibrate after homing, then any inaccuracies in the initial homing operation should be accounted for by these calibration routines.

**Comment by derdigge** [comment]
What about QUAD_GANTRY_LEVEL will this also do the correct zoffset?

**Comment by derdigge** [comment]
Tested it and it does, thanks.
