### ISSUE TITLE
Lost communication with MCU 'mcu'

### ISSUE THREAD

**Issue by victor41482** [KevinOConnor/klipper#755]
Hey! I have a problem with my printer/klipper. Because when I print over 3 hours print, suddenly it is losing the connection to the MCU. It doesn't happen if I just print a 30-minute print, but when I am printing an 8 hours print, it just stops suddenly. How could this be fixed?

[klippy.log](https://github.com/KevinOConnor/klipper/files/2454226/klippy.log)

**Comment by KevinOConnor** [comment]
A FAQ item was added for this: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#i-keep-getting-random-lost-communication-with-mcu-errors
