### ISSUE TITLE
Print Rotation

### ISSUE THREAD

**Issue by adamrblack** [KevinOConnor/klipper#763]
Hello, loving Klipper on my Anycubic Kossel Linear Plus, but all my prints seem to be rotated 120degs counter clockwise. Delta calibration test printed with A at B tower, B at C tower, and A at B towerfpr example.

Is there a setting I have missed to correct this?

Thanks for the help

**Comment by KevinOConnor** [comment]
Sounds like the motor pins are swapped - run the STEPPER_BUZZ command on each stepper (see: https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md ).  If the motors aren't moving the correct towers then either physically swap the motor cables or swap the motor definitions in the config file.

-Kevin

**Comment by adamrblack** [comment]
Thanks Kevin, stepper_buzz moves the correct stepper, I figured out I had to change the angle of each tower and now things are printing the right way around
