### ISSUE TITLE
Lost communication with MCU 'mcu' - Gcode after lost of connection to MCU?

### ISSUE THREAD

**Issue by fakio87** [KevinOConnor/klipper#766]
Hi,

I get the "Lost communication with MCU 'mcu'" on random occasion. Sometimes it is not occuring for weeks, sometimes multiple times a day. Generally a restart of the Pi fixes the issue. This is an issue I am working on separately.

I am using a wifi plug to start - and shutdown the printer some minutes after completion of a print. This is done by a gcode command after the print.

Is there any way to execute Gcode (the script for switching off power after few minutes) after "Lost communication with MCU 'mcu'". This way I could at least sleep well knowing I will not have a switched on printer being idle for hours.

Thx
fakio

**Comment by KevinOConnor** [comment]
See the FAQ: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#i-keep-getting-random-lost-communication-with-mcu-errors

It may be possible to execute power off actions via an OctoPrint plugin, but I'm not personally familiar with that.

-Kevin
