### ISSUE TITLE
Unable to save mesh

### ISSUE THREAD

**Issue by Avalonnw** [KevinOConnor/klipper#768]
After doing a bed mesh probing I issue BED_MESH_PROFILE SAVE=p1 and get this:
`Send: BED_MESH_PROFILE SAVE=p1
Recv: // Unknown command:"BED_MESH_PROFILE"
Recv: ok`

Log is here: https://drive.google.com/open?id=1i9X-_sAn9jWMVFXhS5LNFBDh_tN6Gvof

**Comment by Arksine** [comment]
You need to pull the latest version of Klipper.

**Comment by Avalonnw** [comment]
That is strange... I'll check

**Comment by Avalonnw** [comment]
I had to reinstall klipper. It worked. Thank you.
