### ISSUE TITLE
Z axis Homing broke

### ISSUE THREAD

**Issue by imotox88** [KevinOConnor/klipper#773]
![aaa](https://user-images.githubusercontent.com/43203568/46860225-38383e80-cdcd-11e8-97ae-f3a99268e925.png)

**Comment by theopensourcerer** [comment]
Please read this. You will need to explain the problem and include your klippy.log file.

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by KevinOConnor** [comment]
@BlackStump - if you set HOMING_STEP_DELAY in klippy/homing.py to 0.000001 does the problem go away?

**Comment by KevinOConnor** [comment]
Okay - I'm going to close this as it's not really clear what the original poster is reporting.

-Kevin
