### ISSUE TITLE
Can not use SAVE_CONFIG

### ISSUE THREAD

**Issue by blaskkaffe** [KevinOConnor/klipper#779]
Is the SAVE_CONFIG command a part of the current master branch? Tried to do a git pull and update to the latest but the icons are the same as before (says fan instead of the icon that waa merged to master) and there is no way to save the delta probing to cofig, except for copying and pasting. Am I missing something?

**Comment by cosminr86** [comment]
Have you restart klipper service?

**Comment by blaskkaffe** [comment]
Yes, i have restarted klipper service, reflashed the controller muktiple times. Tried the same update procedures multiple times and when I check it says I have the latest version of master branch.

To me it seems like the flashing doesnt work even tho everything looks successful.

**Comment by KevinOConnor** [comment]
You'll need to attach the klipper log file in order for us to assist - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by blaskkaffe** [comment]
When I stopped the klipper service AND powercycled the MCU so that it didnt boot it worked after rebuilding and flashing. 

Still not getting the new icon even tho the local files looks allright. Will take a look at the log and send here.

**Comment by KevinOConnor** [comment]
Okay - let us know if you are still having the issue.

-Kevin
