### ISSUE TITLE
Klipper on Geeetech GTM32 Mini S

### ISSUE THREAD

**Issue by nymeia** [KevinOConnor/klipper#788]
is it possible to install Klipper on a Geeetech GTM32 Mini S?

**Comment by Gomer05** [comment]
A quick Google search says the Geeetech board has a STM32F103 processor and the klipper docs/stm32f1.md shows that the mcu is supported.
Have a read, the docs are really useful!

**Comment by KevinOConnor** [comment]
I don't know of anyone that has tested Klipper on the GTM32.  On paper it could work - it would need someone with the board to verify though.

-Kevin
