### ISSUE TITLE
Change config settings "on the fly" - how hard would it be?

### ISSUE THREAD

**Issue by swatti87** [KevinOConnor/klipper#789]
Been trying  to get settings in order but re-starting the print every time is kinda slow.

How hard would it be to make it possible to adjust these settings via a console-command "on the fly" ? 

I have no coding experience or much of understanding about this but the thought came into my mind after starting like the ~30th test-print.

EDIT: Mainly what im looking for is pressure advance, its lookahead and other "config settings"

**Comment by cosminr86** [comment]
you can config a lot of settings on the fly. just read the docs (including g-code.md)
what do you try to do ?

**Comment by swatti87** [comment]
Im mainly hoping to configure "pressure advance" on the fly without having to re-start the print.
Can i do that?

**Comment by jakep82** [comment]
The documents have all the answers.

https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md

**Comment by swatti87** [comment]
> The documents have all the answers.
> 
> https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md

Oh goodie. Must have missed the PA setting there. Looks like all the stuff i want to change are there. 

Closing.
