### ISSUE TITLE
DeltaCalibration failes with MCU shutdown

### ISSUE THREAD

**Issue by VincentGijsen** [KevinOConnor/klipper#790]
hi,

i'm trying to calibrate my delta, using the manual method. After executing `delta_calibrate` is proceed to do the paper test for 7 times. after which i'm told to `save_config`. THis always fails when i try do do so. this also hinders me to proceed to the advanced calibration wich requires the former. Takeing over the values into the config myself doesn't alow me to use the extended calibration.

I also tried to `chmod 777 to /home/pi/printer.cfg` but alas.

[klippy.log](https://github.com/KevinOConnor/klipper/files/2489110/klippy.log)

any thoughts what goes south?

**Comment by VincentGijsen** [comment]
ok, now for the strange part;

after adding the aditional lines (found in klippy.log) in the delta-calibrate section, i can proceed with the input data from my printed model (extende). And behold, when i execute `SAVE_CONFIG` it just works.

So somehow my delta-calibrate section **perhaps** was wrong?

**Comment by KevinOConnor** [comment]
This looks like a dup of issue #733.  You'll need to upgrade to the latest software (see the FAQ for details on upgrading) to get the fix.

-Kevin

**Comment by VincentGijsen** [comment]
indeed, i cloned the repo last sunday, and now 3 days later, there is a fix :)
