### ISSUE TITLE
[Q] Speed before probing

### ISSUE THREAD

**Issue by Hywelmartin** [KevinOConnor/klipper#793]
I can't find how to set the speed before probing?

The problem I have is that my hot end probe(piezo) sometimes trigger during the switch between the approach and the actual probing routine. Or deceleration...
[printer181018.txt](https://github.com/KevinOConnor/klipper/files/2490652/printer181018.txt)

**Comment by theopensourcerer** [comment]
Sounds more like you need to add a delay between the move and the probe. I use a Precision Piezo probe and have a 750mS delay so the head stops moving, waits for 750mS then the bed probes. I'm not in front of my printer right now but as I recall I think I simply added a gcode wait statement in the `activate_gcode:` parameter of the [probe] section. i.e.  

```
G4 P750
```

**Comment by Hywelmartin** [comment]
Yes that would be an option(I had that in Marlin) 

Found it...Lets try it out...

Is there any good forum for this kind of Q...??

**Comment by theopensourcerer** [comment]
I know that there's an "official" channel on IRC and a mailing list and also an "unofficial" group on Facebook. There might be more places too.

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md#mailing-list

https://www.facebook.com/groups/klipper/

**Comment by Hywelmartin** [comment]
thanks... I got it working... hopefully


over and out
