### ISSUE TITLE
Internal error on command:"G28"

### ISSUE THREAD

**Issue by filippor** [KevinOConnor/klipper#798]
I got this error after changing step_distance: from 0.0125  to 0.00625 for the 3 stepper

[klippy.log](https://github.com/KevinOConnor/klipper/files/2496191/klippy.log)

**Comment by filippor** [comment]
some error of bug #773

**Comment by KevinOConnor** [comment]
If you modify klippy/homing.py and change the definition of HOMING_STEP_DELAY at the top of the file to read: `HOMING_STEP_DELAY = 0.000001` - does the problem go away?

**Comment by filippor** [comment]
no I have the same error. I'm on raspberry pi 1 if it can help to find the problem

**Comment by filippor** [comment]
it works with HOMING_STEP_DELAY =0.00000001
