### ISSUE TITLE
Delta Printer Mesh Bed Levelling support [not a issue a feature]

### ISSUE THREAD

**Issue by BlackStump** [KevinOConnor/klipper#817]
I don't see any reference to a delta printers in the mesh section of the config and I see a pull request for support for round and hexagonal beds .
So my question is ...mesh is a no go for delta printers at this stage?

.

**Comment by Arksine** [comment]
Correct.  I have been following the PR you are referencing, however after providing some feedback we haven't heard anything for a while.

I have started some work based on that PR, however its somewhat slow going right now.   I can't give any specific time period as to when I'll be able to finish it, but it is being worked on and will eventually make its way in.
