### ISSUE TITLE
by-id instead of by-path??? in example-multi-mcu.cfg

### ISSUE THREAD

**Issue by Hywelmartin** [KevinOConnor/klipper#837]
klipper/config/example-multi-mcu.cfg states:

# The main micro-controller is used as the timing source for all the
# micro-controllers on the printer. Typically, both the X and Y axes
# are connected to the main micro-controller.
[mcu]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.2:1.0-port0
pin_map: arduino

# The "zboard" micro-controller will be used to control the Z axis.
[mcu zboard]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.3:1.0-port0
pin_map: arduino

# The "auxboard" micro-controller will be used to control the heaters.
[mcu auxboard]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.4:1.0-port0
pin_map: arduino

Shouldn't it be 

serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

**Comment by Devilcow** [comment]
It's different on different machines, and environments, your environment won't necessarily reflect what's in the demo files.

**Comment by FHeilmann** [comment]
both `by-id` and `by-path` can be used. However, with cheap cloned boards (Depending on how badly cloned they are), both may enumerate with the same id, making them indistinguishable. A race condition can also happen where the 'order' of boards is not constant across multiple reboots. This can by solved by using `by-path` instead, where the USB controller identifiers are included in the filename. Those are always guaranteed to be different and persistent across reboots.

**Comment by Hywelmartin** [comment]
Thanks for the clarification. But as I understand By-id is the preferred way to go?  

and after some reading in the FAQ there is an explanation .... sorry ..

Maybe the serial connection part 
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#wheres-my-serial-port
should be in 
https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md


closing this

**Comment by Hywelmartin** [comment]
Thanks for the clarification. But as I understand By-id is the preferred way to go?  

and after some reading in the FAQ there is an explanation .... sorry ..

Maybe the serial connection part 
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#wheres-my-serial-port
should be in 
https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md


closing this
