### ISSUE TITLE
Sorting the virtual SD card files by creation date

### ISSUE THREAD

**Issue by ndupont-net** [KevinOConnor/klipper#846]
Hi, here is my implementation of a sorted list in **virtual_sdcard.py**

A single line as been modified, it's basically only a **sorted** function added to the os.listdir()

My LCD menu now shows me the latest uploaded files first :)

It would be great to see that feature implemented in Klipper

```
 def get_file_list(self):
        dname = self.sdcard_dirname
        try:
            filenames = sorted(os.listdir(self.sdcard_dirname), key=lambda x: os.path.getctime(os.path.join(self.sdcard_dirname,x)), reverse=True) 
            return [(fname, os.path.getsize(os.path.join(dname, fname)))
                    for fname in filenames]
        except:
            logging.exception("virtual_sdcard get_file_list")
            raise self.gcode.error("Unable to get file list")
```

**Comment by KevinOConnor** [comment]
Thanks.  As mentioned previously, code changes should be submitted as github pull requests: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

**Comment by ndupont-net** [comment]
I'll check the modifications in my fork then send a pull request.

For future contribution I'll try to have it synced with my instance.

Nicolas

**Comment by ndupont-net** [comment]
Pulled commits tested and validated with my printer.

I close this issue
