### ISSUE TITLE
Implementation of M300 (beeper support) that could be included in example-extras.cfg

### ISSUE THREAD

**Issue by ndupont-net** [KevinOConnor/klipper#847]
Hi, here is how I have implemented the beeper using an output_pin and a gcode macro.

This could be added to **example-extras.cfg** as it would make for a great drag and drop snippet in custom configurations.

M300 [P<ms>] [S<Hz>],  although the frequency is not pitch-perfect, based on 1kHz and cannot be higher than that with this pwm cycle_time.

```
[output_pin BEEPER_pin]
pin: ar37
pwm: True
value: 0
shutdown_value: 0
cycle_time: 0.001
scale: 1000

[gcode_macro M300]
default_parameter_S=1000
default_parameter_P=100
gcode:  SET_PIN PIN=BEEPER_pin VALUE={S}
        G4 P{P}
        SET_PIN PIN=BEEPER_pin VALUE=0
```

My apologies if this is not the desired way to propose new functionnalities.

I also have a Tevo Tarantula config file that could be shared in the examples, and the implementation of M355 for case light control.

**Comment by KevinOConnor** [comment]
FYI, in issue #787 there was a discussion on possibly adding a "config/sample-macros.cfg" file for things like the above.

-Kevin

**Comment by ndupont-net** [comment]
That sounds like a good place for it, issue closed then

Nicolas
