### ISSUE TITLE
st7920 screen no Menu Arduino Due clone /RAMPS-FD v2.1

### ISSUE THREAD

**Issue by bruce356** [KevinOConnor/klipper#849]
Hi, has anyone had success with the GLCD on Klipper using Ramps-fd 2.
All works fine on Marlin and Repetier.
I am using pins:-
[display]
lcd_type: st7920
cs_pin: ar16
sclk_pin: ar23
sid_pin: ar17

This should be correct, but only get a blank screen.
Thanks and regards - bruce
[klippy_DUE.zip](https://github.com/KevinOConnor/klipper/files/2544701/klippy_DUE.zip)
https://github.com/KevinOConnor/klipper/issues/308

**Comment by KevinOConnor** [comment]
FYI - there was recent discussion on this in issue #814.  The st7920 does work on the Due.  I don't know what the pins would be on the ramps-fd.

-Kevin
