### ISSUE TITLE
List of implemented g-codes? and Delta Calibration options

### ISSUE THREAD

**Issue by deltamelter** [KevinOConnor/klipper#85]
I'm a Delta user and interested in trying klipper. Currently use Auto-calibration branch of Marlin 1.1.8. This does fairly good delta auto calibration by itself (G33) but also allows probing for "Delta printer least-squares calibration calculator" and storage of the resulting corrections to eeprom. The following g-codes are useful for this and I would like to get an idea which of these have been/will be implemented or have equivalent with klipper:

G30 Probe specific position (either current X/Y or specified X/Y as parameters)
http://reprap.org/wiki/G-code#G30:_Single_Z-Probe

M665 sets various delta parameters.
http://reprap.org/wiki/G_code#M665:_Set_delta_configuration

M503 reads current delta parameters
http://reprap.org/wiki/G-code#M503:_Print_settings

G33 Delta AutoCalibration
http://reprap.org/wiki/G-code#G33:_Delta_Auto_Calibration_.28Marlin_1.1.x.29

Currently I do the Least Squares calculation in a custom octoprint plugin (js) but this could easily be implemented in a klipper routine to probe 10 points, calculate and apply the resulting delta params.

So is there a list of which g-codes are implemented, will be implemented or would like to implement?  

Cheers

**Comment by KevinOConnor** [comment]
On Fri, Dec 29, 2017 at 01:46:22PM +0000, Trex wrote:
> I'm a Delta user and interested in trying klipper. Currently use Auto-calibration branch of Marlin 1.1.8. This does fairly good delta auto calibration by itself (G33) but also allows probing for "Delta printer least-squares calibration calculator" and storage of the resulting corrections to eeprom. The following g-codes are useful for this and I would like to get an idea which of these have been/will be implemented or have equivalent with klipper:

Take a look at issue #19 - there's a development branch there with
many of the features you list.  The code's too raw for general use,
but we're getting there.

[...]
> So is there a list of which g-codes are implemented, will be implemented or would like to implement?  

In general, my preference is to support only the subset of g-code that
is produced by widely used software in their common configurations
(eg, octoprint, pronterface, cura, sli3er, etc).  My preference is to
use human readable names (eg, DELTA_AUTOPROBE) for configuration and
manual control commands.

-Kevin
