### ISSUE TITLE
Z_TILT_ADJUST does nothing in VORON 1.5

### ISSUE THREAD

**Issue by dgcaste** [KevinOConnor/klipper#850]
After I G28, I run a Z_TILT_ADJUST and it moves to the first probing point and then stops before doing any probing. Klippy.log shows nothing after the z_tilt_adjust command is read. 

Z probe is a limit switch activated by the hot end touching the bed. Homing works perfectly for all three axes. Z1 is connected to second extruder stepper. Only one MCU. Z seems to be working great otherwise with both motors staying in perfect sync.

Attached log and cfg.
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/2544703/printer.cfg.txt)

[klippy.log](https://github.com/KevinOConnor/klipper/files/2544702/klippy.log)

**Comment by KevinOConnor** [comment]
You haven't defined a [probe] section in your config.  A typical Voron printer uses the probe to perform automated bed levelling.  If you don't define the probe section then the code defaults to "manual probing" which would require you to manually jog the printer and perform the "paper test" at each test point (running NEXT when each point is at the correct height).

-Kevin

**Comment by dgcaste** [comment]
I see! Thanks for the insight. I have a v1.5 which means the Z endstop is also the probe. Can the probe use the same switch?

**Comment by KevinOConnor** [comment]
If the probe is used for the Z endstop, then configure the probe and set the Z endstop to use "probe:z_virtual_endstop" as described in config/example-extras.cfg.

Separately, I'm told the quad_gantry_level module performs better than the z_tilt module on the voron printers.

-Kevin

**Comment by dgcaste** [comment]
That worked great. Thanks! I'm running a 1.5 which has two Z motors for the bed and not 4 for the gantry.
