### ISSUE TITLE
PID for heater_bed?

### ISSUE THREAD

**Issue by TylonHH** [KevinOConnor/klipper#86]
How can I set my PID for the heated bed? It's shooting 5 degrees over the target and cooling down, and so on. I have my personal PID already, but where can I put it in?
If it's not possible yet, please provide it.

**Comment by KenshiHH** [comment]
change

control: watermark

to

control: pid
pid_Kp: 22.2
pid_Ki: 1.08
pid_Kd: 114

**Comment by NickRimmer** [comment]
Need to describe it in example config.
https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg

**Comment by KenshiHH** [comment]
line 188/189
" Control algorithm (either pid or watermark). This parameter must be provided."
