### ISSUE TITLE
[Q] What is the PWM freq. for heating

### ISSUE THREAD

**Issue by protworks** [KevinOConnor/klipper#866]
Hi there, guys. 
I'm using RAMPS1.4 board which will have connected an external power mosfet to drive big heat bed heater.
I'm wondering what is the default PWM frequency for the heating ? 
Is it 10 Hz ( found somewhere in the config file)? 
Can I change it? If yes, what is the max value ?

Thanks in advance.
ProtWorks

**Comment by KevinOConnor** [comment]
The heater options are documented in the config/example.cfg file.  (It is documented in the [extruder] section; they apply to both the bed and extruder.)

-Kevin
