### ISSUE TITLE
Readable TMC_DEBUG output

### ISSUE THREAD

**Issue by hevilp** [KevinOConnor/klipper#869]
Hi,

it is possible to improve the output of TMC_DEBUG?

If I compare it to RepRap or Marlin FW it not readable and useable data.
For example, what tells me
`DRV_STATUS:     80130000`
? Decimal converted = 2148728832 and?

Send: DUMP_TMC STEPPER=stepper_x
Recv: // GCONF:          00000000
Recv: // GSTAT:          00000001
Recv: // IOIN:           11000078
Recv: // TSTEP:          000fffff
Recv: // XDIRECT:        00000000
Recv: // MSCNT:          00000008
Recv: // MSCURACT:       00f7000c
Recv: // CHOPCONF:       14028384
Recv: // DRV_STATUS:     80130000
Recv: // PWM_SCALE:      00000000
Recv: // LOST_STEPS:     00000000
Recv: ok
Send: M105
Recv: ok T0:22.3 /0.0 B:22.5 /0.0
Send: DUMP_TMC STEPPER=stepper_y
Recv: // GCONF:          000001c4
Recv: // GSTAT:          00000001
Recv: // IFCNT:          0000000c
Recv: // OTP_READ:       0000000a
Recv: // IOIN:           20000141
Recv: // FACTORY_CONF:   0000000a
Recv: // TSTEP:          000fffff
Recv: // MSCNT:          00000008
Recv: // MSCURACT:       00f7000c
Recv: // CHOPCONF:       14030053
Recv: // DRV_STATUS:     80130000
Recv: // PWMCONF:        c80d0e24
Recv: // PWM_SCALE:      00000016
Recv: // PWM_AUTO:       000e0024
Recv: ok

**Comment by JustAnother1** [comment]
All these values are documented in the trinamic datasheet. Each bit has a special meaning. Sometimes some bits are grouped for some setting / information. Most of the encoded information can only be understood with a good understanding of the inner workings of the trinamic chip. And with that good information and the datasheet it is possible to decode all needed information from this output.

To improve the situation take a look into the datasheet and comment on which information you think should be parsed into a human readable format. Maybe the over current and short to GND warnings? I don't know what would make sense, so clearing up the situation would be a good first step to improve the situation.
