### ISSUE TITLE
Heater error message is repeated several times

### ISSUE THREAD

**Issue by fritzw** [KevinOConnor/klipper#874]
I just changed my bed heater from watermark to PID (not sure if this is relevant).

After replacing the cold glass plate on my already hot bed, naturally the temperature dropped, klipper complained: `Heater heater_bed not heating at expected rate` and shut down the printer.

So far, so good, safety features are working. Only it repeated the exact same message 58 times (see attached log file). This sounds like a bug, albeit a harmless one, so I'm reporting it.

[klippy.log](https://github.com/KevinOConnor/klipper/files/2563921/klippy.log)

**Comment by manu7irl** [comment]
did you try the calibrate pid function?

**Comment by fritzw** [comment]
Ah, all right. If that is the desired behaviour, I guess we can close this issue.
