### ISSUE TITLE
GLCD Menu function T0 & T1 option is no longer working

### ISSUE THREAD

**Issue by bruce356** [KevinOConnor/klipper#882]
Hi, I updated to the latest Klipper (have not updated for some time) and find that,
### menu move 10mm ###
[menu __control __move_10mm]
type: list
enable: !toolhead.is_printing
name: Move 10mm
items:
    .__tool_0  ;This item no longer works
    .__tool_1   ;This item no longer works
    .__axis_z
    .__axis_x, .__axis_y
    .__axis_e

[menu __control __move_10mm __tool_0]
type: command
name: "Choose: X_T0 "
gcode: T0 

[menu __control __move_10mm __tool_1]
type: command
name: "Choose: X2_T1 "
gcode: T1 

it no longer functions as it should after “Home All” or “allow_move” [force move], with “allow move” if "Choose: X2_T1 " is selected and the encoder is pressed, T0 moves about +1mm, if then "Choose: X_T0 " is selected and the encoder is pressed T1 crashes into the T1 end stop because it thinks it is at position +0 (approx.) and needs to home to +290 (approx.) and of course the end stop is ignored.

After an “Home All” is performed the responses are a little different, if "Choose: X_T0 " is selected and the encoder is pressed, Nothing Happens.  If "Choose: X2_T1 " is selected and the encoder is pressed, T0 moves about +1mm, if then once again "Choose: X_T0 " is selected and the encoder is pressed, T1 moves about 1mm towards the bed and both the Y and Z axis also move a very small amount. 

After this if I continue swapping from  "Choose: X_T0 " to "Choose: X_T1 " only the Y and Z axis move a small amount back and forth.

Thanks and regards – bruce
Have attached my Menu.cfg and Printer.cfg
[Klipper Configs.zip](https://github.com/KevinOConnor/klipper/files/2568434/Klipper.Configs.zip)

**Comment by KevinOConnor** [comment]
You'll need to provide the Klipper log file for us to assist - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

Also, if you've modified the klipper code at all (including menu.cfg) then you'll need to reproduce the issue on a pristine version of Klipper.

-Kevin
