### ISSUE TITLE
Filament Tracking Sensor

### ISSUE THREAD

**Issue by AniInABox** [KevinOConnor/klipper#886]
Hi,

would it be possible to get a Filament Tracking Sensor to work?
Something like this: https://sparklab-shop.de/elektronik/60/fts-v2-filament-tracking-system-1-75mm?c=10

As an Example: Repetier can slow down a print, when the Sensor is not sending the correct Pulses for the Extrusion Steps, so the print is saved.

Also an Extruder Jam can be recognized.

When you need some Debug Assistent, i can buy a Sensor and help you.

Best Regards

**Comment by KevinOConnor** [comment]
I'm sure it is possible to add support, but it would require development work.  There's been some discussion on filament sensors in PR #545.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this in favour of the existing issues on filament trackers (#249 and #545).
