### ISSUE TITLE
Firmware constant 'PWM_MAX' not found

### ISSUE THREAD

**Issue by andrico21** [KevinOConnor/klipper#887]
Hi there.
Cannot run Klipper for a first time, trying to migrate from Marlin 2.x. All my drivers are TMC2130 SPI-controlled. Arduino Due + RURAMPS4D.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2573645/klippy.log)
 -->

What am I do wrong? cannot find anything related to PWM_MAX in FAQ/doc

**Comment by jakep82** [comment]
Try commenting out the hardware pwm line in your fan section.

**Comment by andrico21** [comment]
Yes, now it works, thanks much for quick response!
Despite the warning remark I left for this parameter in the config I didn't realized it may impact  :)
So yes, hardware_pwm defined as True was the problem.
