### ISSUE TITLE
Steppers not moving

### ISSUE THREAD

**Issue by andrico21** [KevinOConnor/klipper#888]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2574851/klippy.log)
[pins_RURAMPS4D_13.zip](https://github.com/KevinOConnor/klipper/files/2574854/pins_RURAMPS4D_13.zip)

Still trying to run Klipper for the first time after Marlin. Cannot get steppers nor moving in any direction, nor buzzing - just silent. I translated pin names from working Marlin pinout (in attachment) for my board using https://www.arduino.cc/en/Hacking/PinMappingSAM3X

**Comment by andrico21** [comment]
Checked with DUMP_TMC command, all four drivers registers reported as zero. For example X is below:
Send: DUMP_TMC STEPPER=stepper_x
Recv: // GCONF:          00000000
Recv: // GSTAT:          00000000
Recv: // IOIN:           00000000
Recv: // TSTEP:          00000000
Recv: // XDIRECT:        00000000
Recv: // MSCNT:          00000000
Recv: // MSCURACT:       00000000
Recv: // CHOPCONF:       00000000
Recv: // DRV_STATUS:     00000000
Recv: // PWM_SCALE:      00000000
Recv: // LOST_STEPS:     00000000
Recv: ok

p.s. first log had extruder TMC2130 undefined, fixed later - see latest log here.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2576265/klippy.log)

**Comment by AxMod3DPrint** [comment]
You'll need to restart klipper in the terminal to kick off the TMCs. Had
the same issue. IE type RESTART into the terminal and hit enter, then try
TMC_DUMP

**Comment by andrico21** [comment]
@AxMod3DPrint just tried, doesn't help - zeroes :(

**Comment by andrico21** [comment]
@AxMod3DPrint okay, got some new state - thanks much for the hint.
Send: DUMP_TMC STEPPER=stepper_x
Recv: // GCONF:          00000000
Recv: // GSTAT:          00000000
Recv: // IOIN:           84400007
Recv: // TSTEP:          80000000
Recv: // XDIRECT:        d0000000
Recv: // MSCNT:          00000000
Recv: // MSCURACT:       00000000
Recv: // CHOPCONF:       00000000
Recv: // DRV_STATUS:     80000000
Recv: // PWM_SCALE:      00000000
Recv: // LOST_STEPS:     60000000
Recv: ok

**Comment by AxMod3DPrint** [comment]
Not a problem. I run an SSR to power off the printer so it powers down the
TMC memory so have to restart when I power up the printer.

**Comment by andrico21** [comment]
Strange, I sent 'DUMP_TMC STEPPER=stepper_x' multiple times with 2-3 second interval and each time I got different values, see attachment.
[stepper_x_registers.txt](https://github.com/KevinOConnor/klipper/files/2577656/stepper_x_registers.txt)

**Comment by andrico21** [comment]
Wow, got it moving. Not sure what actually helps, among other things I zeroed stealthchop threshold which I initially got from ex-production Marlin. Need testing, will post later.

**Comment by andrico21** [comment]
Okay, Z is fine. But for XY I have only one motor moving (corexy) instead of two. Cannot realize right now is this hardware problem (burned driver/motor) or logic. But for any movement carriage moves on diagonal and only one motor is spinning. Latest log in attachment.
[klippy.log](https://github.com/KevinOConnor/klipper/files/2578067/klippy.log)

**Comment by jakep82** [comment]
I'm not sure why one of your motors isn't working, but I do see some issues in your config.  You really don't want to home X and Y at 200mm/s.  I would recommend dropping that to a more reasonable speed like 60mm/s.  Same goes for your Z.  You defined max Z velocity at 50mm/s, but your homing speed is 600.  For X and Y I would also recommend disabling the second homing speed.  In my experience the TMC2130 drivers will not trigger the stallguard feature properly below a certain speed.  It's best to home at 50-60mm/s, and only do it once.

**Comment by andrico21** [comment]
@jakep82 corrected the speed, but still one mo
[klippy.log](https://github.com/KevinOConnor/klipper/files/2578355/klippy.log)
tor is spinning

**Comment by jakep82** [comment]
What are the results of the commands below?

`STEPPER_BUZZ STEPPER=stepper_x`
`STEPPER_BUZZ STEPPER=stepper_y`

**Comment by BlackStump** [comment]
are your step distances correct? 
 your logs still show very high homing speeds!
In the commissioning stage a keep it simple config! with klipper default well everything might help.
you can soup it up after you have if functional

**Comment by andrico21** [comment]
guys, any ways to troubleshoot SPI part with Klipper? today I turned the printer on and nothing is moving including Z, so I receive following because Z is not moving:
Send: G28 Z
Recv: !! Endstop z still triggered after retract
Recv: ok

**Comment by andrico21** [comment]
@BlackStump about the distance - yes, I just took my Marlin configs and for each of corresponding Klipper values I divided 1 by Marlin verified values.

**Comment by BlackStump** [comment]
can you post your current config as the error message surely gives a clue where to look in your config.
that will be your retract distance for the 2nd homing

**Comment by andrico21** [comment]
@BlackStump sure, see in attachment. Also put new log (with the same config inside tho).
[klippy.log](https://github.com/KevinOConnor/klipper/files/2579349/klippy.log)
[printer.zip](https://github.com/KevinOConnor/klipper/files/2579354/printer.zip)

It's clear for me now the issue somewhere in driver configuration, not any retracts. I think the drivers don't apply enough current to motors to even move it from zero speed. See why: https://www.youtube.com/watch?v=P0AG7raBGQs and https://www.youtube.com/watch?v=ofoib1RmkXA

**Comment by andrico21** [comment]
@jakep82 see [above](https://github.com/KevinOConnor/klipper/issues/888#issuecomment-438548724)

**Comment by andrico21** [comment]
actually I still have some classic drivers, but the problem is long time ago I already eliminated all hw endstops except Z in my printer so sure I can test classic driver on Z, but not XY anymore.
As stated before - I already tried flashing back to Marlin and it works like a charm, so no wiring issues supposed to be.

**Comment by BlackStump** [comment]
have you tried the enable pin without ! 
I am guessing that your pins might not be correct might be worth double checking with this helpful doc.
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-convert-a-marlin-pin-number-to-a-klipper-pin-name

**Comment by andrico21** [comment]
@BlackStump the doc you posted is one I initially started with. I already double-checked stepper and driver pins according to https://www.arduino.cc/en/Hacking/PinMappingSAM3X - especially stepper and driver pins. I wonder why the the same driver registers different each time I run DUMP_TMC, even without trying to move any axis between DUMP_TMC commands

**Comment by andrico21** [comment]
wonder if someone tried Klipper on Due with TMC2130 yet... maybe some pulse characteristic issues, dunno....

**Comment by andrico21** [comment]
@BlackStump yep, that's the doc I initially started with. About 'enable pin' - just checked to not invert it: my drivers begin to whistle right after hw restart and became silent as I trying to move any motor without any attempts to move, so obvious - 'enable pin' on my Due should be inverted.

**Comment by andrico21** [comment]
found very similar [issue](https://github.com/KevinOConnor/klipper/issues/435), any thoughts considering I have latest Klipper and flashed Due compiled yesterday?

**Comment by andrico21** [comment]
> found very similar [issue](https://github.com/KevinOConnor/klipper/issues/435), any thoughts considering I have latest Klipper and flashed Due compiled yesterday?

damn yeah, it works! I changed SPI rate to 100000 as @KevinOConnor mentioned in https://github.com/KevinOConnor/klipper/issues/435#issuecomment-401821076

**Comment by andrico21** [comment]
so, the problem was caused by non-compatible with Due SPI rate and as following drivers were misconfigured - sporadically works with unexpected behavior

**Comment by jakep82** [comment]
I'm using TMC2130 drivers on my Due powered printer. They work fine without any SPI issues.

**Comment by andrico21** [comment]
> I'm using TMC2130 drivers on my Due powered printer. They work fine without any SPI issues.
Hmmm, @jakep82 - it was your issue here where I found the solution :) and you wrote there it helped :) if you can - check please your TMC script :)

**Comment by jakep82** [comment]
If you read that thread, changing the SPI speed didn't fix the issue for me.  What did fix it was a small code change Kevin made on that day.  My drivers have worked flawlessly since then without change the SPI speed.

https://github.com/KevinOConnor/klipper/commit/1eb416002bf9abfc2fe9d30e9c42c44704e0f791

**Comment by KevinOConnor** [comment]
How are you stepper drivers wired?  If a lower spi rate improves your results, it could indicate that the SPI lines are noisy.

Another thing to check is that every device on the SPI bus is configured in Klipper.  (Should there be a device on the spi bus that is not configured then it may respond at the same time as one of the steppers and thus corrupt the transmissions.)

There shouldn't be any downsides to using an SPI speed of 100000.

-Kevin

**Comment by andrico21** [comment]
> How are you stepper drivers wired? If a lower spi rate improves your results, it could indicate that the SPI lines are noisy.
Actually the only dark horse here in my hardware is MKS TFT24 display module with SD-reader onboard, but it connected via serial pins to the Due board and using software SPI as I been told by RURAMPS4D developer, only dedicated SD-card reader port uses hardware SPI and this port is unused in my case. Not any reasons to keep it connected with Klipper now as I'm not sure it can be managed from Klipper or not. So, definitely I'm able to test it without display as soon as I'll find enough time to disassemble the chassis.
SPI wiring on this board represented on single picture: http://3dtoday.ru/upload/main/d4f/d4f499564c35a7012e7a9e41ed64b3f0.png

Drivers are standard TMC2130 shield-style connection without any smoothers/protectors added on its way.

> Another thing to check is that every device on the SPI bus is configured in Klipper. (Should there be a device on the spi bus that is not configured then it may respond at the same time as one of the steppers and thus corrupt the transmissions.)
Thanks for clarification, definitely my action plan is temporary disconnect TFT24 cable to check if 40000000 will work. Once I check it - I'll text it here.

BTW, any plans to utilize TFT24 connected via serial with Klipper?

**Comment by andrico21** [comment]
> If a lower spi rate improves your results, it could indicate that the SPI lines are noisy.

> Another thing to check is that every device on the SPI bus is configured in Klipper. (Should there be a device on the spi bus that is not configured then it may respond at the same time as one of the steppers and thus corrupt the transmissions.)
I disconnected the TFT24 with its onboard SD card reader and checked: no, issues with SPI still there on 40000000 SPI rate. BTW I tried 20000000 - works fine without any problems.

**Comment by KevinOConnor** [comment]
FYI, in the latest code there is a (currently undocumented) spi_speed parameter that one can provide in the tmc2130 section to set the spi speed.

It looks like the original issue has been solved, so I am going to close it.

**Comment by robustini** [comment]
@andrico21, please can you share your fixed printer.cfg for RuRamps with TMC2130?
