### ISSUE TITLE
Support M42 command

### ISSUE THREAD

**Issue by Helovi** [KevinOConnor/klipper#90]
Hello, is there any way to control external pins on the board?

Before with my Marlin firmware, I could control an extra fan to cool down the stepper drivers and turn on the lightning by using the M42 command. How does this work with the Klipper firmware?
(The M42 command triggers external bins on the AVR/MKS board)

I found the file gcode.py, and I would like to add some Gcodes to it, how do I start? is there any guide?

**Comment by lenne0815** [comment]
# Run-time configurable digital output pins (one may define any number
# of sections with a "digital_output" prefix). Pins configured here
# will be setup as digital outputs and one may modify them at run-time
# using the "SET_PIN PIN=my_pin VALUE=0" extended g-code command.
#[digital_output my_pin]
#pin:
#   The pin to configure as a digital output. This parameter must be
#   provided.
#value:
#   The value to initially set the pin to during MCU configuration
#   (either 0 or 1). The default is 0 (for low voltage).
#shutdown_value:
#   The value to set the pin to on an MCU shutdown event. The default
#   is 0 (for low voltage).
