### ISSUE TITLE
Z-axis stop during homing with Bltouch

### ISSUE THREAD

**Issue by vsusanto** [KevinOConnor/klipper#904]
Hello all,
I am looking for the solution on my issue of the z-axis stop during homing, but the Bltouch triggered.
This is very frustrated, because I have tried all type of combination to fix this problem.

I try to install the Klipper on my Wanhao I3 V2 with the board converted to RAMPS 1.4 with Bltouch.

Here is the error that I received: 

Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: M105
Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: M105
Recv: !! Failed to home z: Timeout during endstop homing
Changing monitoring state from "Operational" to "Error: Failed to home z: Timeout during endstop homing"
Changing monitoring state from "Error: Failed to home z: Timeout during endstop homing" to "Offline (Error: Failed to home z: Timeout during endstop homing)"
Connection closed, closing down monitor

The following is my printer.cfg:
# This file provides example config file settings for the BLTouch
# automatic bed leveling sensor. This file is just a "snippet" of
# sections specific to the BLTouch - it must be added to a config file
# containing the configuration of the rest of the printer.

# Be sure to review and update this config with the appropriate pins
# and coordinates for your printer.

# See the "example.cfg" and "example-extras.cfg" files for a
# description of config parameters.

# Define the BLTouch servo
[servo bltouch]
pin:ar11
#ar11
maximum_servo_angle: 180
minimum_pulse_width: 0.0006
maximum_pulse_width: 0.0024

# Define a probe using the BLTouch
[probe]
pin:^ar18
#ar19 
#ar7
z_offset: 1.10
speed: 2.0
activate_gcode:
    SET_SERVO SERVO=bltouch ANGLE=10
#    SET_SERVO SERVO=bltouch ANGLE=60
    G4 P1000
deactivate_gcode:
    SET_SERVO SERVO=bltouch ANGLE=90
    G4 P100

# Example bed_tilt config section
[bed_tilt]
# x_adjust:
# y_adjust:

points:
    40,40
    40,90
    40,140
    90,40
    90,100
    100,140
    140,40
    140,90
    140,140

# If the BLTouch is used to home the Z axis, then define a
# homing_override section, use probe:z_virtual_endstop as the
# endstop_pin in the stepper_z section, and set the endstop_position
# in the stepper_z section to match the probe's z_offset.

[homing_override]
set_position_z: 20
axes: z
gcode:

    G90;
	G1 Z20 F600
	G28 X0 Y0
	G1 X100 Y100 F3600;
	SET_SERVO SERVO=bltouch ANGLE=10
	G4 P100
	G28 Z0
	SET_SERVO SERVO=bltouch ANGLE=90 
    G4 P1000

# This file contains common pin mappings for RAMPS (v1.3 and later)
# boards. RAMPS boards typically use a firmware compiled for the AVR
# atmega2560 (though other AVR chips are also possible).

# See the example.cfg file for a description of available parameters.

[stepper_x]
step_pin: ar54
dir_pin: ar55
enable_pin: !ar38
step_distance: .0125
endstop_pin: ^!ar3
#endstop_pin: ^ar2
position_endstop: 0
position_max: 200
homing_speed: 50

[stepper_y]
step_pin: ar60
dir_pin: ar61
enable_pin: !ar56
step_distance: .0125
endstop_pin: ^!ar14
#endstop_pin: ^ar15
position_endstop: 0
position_max: 200
homing_speed: 50

[stepper_z]
step_pin: ar46
dir_pin: !ar48
#enable_pin: !ar62
step_distance: .0025
#endstop_pin: ^ar18
#endstop_pin: ^ar19
endstop_pin: probe:z_virtual_endstop
position_max: 200
position_min: -2

[extruder]
step_pin: ar26
dir_pin: ar28
enable_pin: !ar24
step_distance: .002
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: ar10
sensor_type: NTC 100K beta 3950
sensor_pin: analog13
control: pid
pid_Kp: 22.2
pid_Ki: 1.08
pid_Kd: 114
min_temp: 0
max_temp: 250

#[extruder1]
#step_pin: ar36
#dir_pin: ar34
#enable_pin: !ar30
#heater_pin: ar9
#sensor_pin: analog15
#...

[heater_bed]
heater_pin: ar8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog14
control: watermark
min_temp: 0
max_temp: 130

[fan]
pin: ar9

[mcu]
serial: /dev/ttyACM0
pin_map: arduino

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

# "RepRapDiscount 2004 Smart Controller" type displays
#[display]
#lcd_type: hd44780
#rs_pin: ar16
#e_pin: ar17

# "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays
[display]
lcd_type: st7920
cs_pin: ar16
sclk_pin: ar23
sid_pin: ar17
#d4_pin: ar23
#d5_pin: ar25
#d6_pin: ar27
#d7_pin: ar29
encoder_pins: ^ar31, ^ar33
click_pin: ^!ar35

I appreciate any help that I can get.

**Comment by BlackStump** [comment]
I have included a printer.cfg with Bltouch settings that work fine for me.
[printer.zip](https://github.com/KevinOConnor/klipper/files/2593640/printer.zip)

to test the Bltouch this is the procedure I used
type in the Terminal
 SET_SERVO SERVO=bltouch ANGLE=60
 manual push the pin up then type in the Terminal
QUERY_PROBE
 it should say triggered
type in the Terminal
SET_SERVO SERVO=bltouch ANGLE=10
type in the Terminal
QUERY_PROBE
it should say open
