### ISSUE TITLE
extruder not maintaining temperature

### ISSUE THREAD

**Issue by vampiredawn** [KevinOConnor/klipper#913]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2601324/klippy.log)

**Comment by KevinOConnor** [comment]
I believe this was resolved on IRC - the bed_heater should use PID instead of watermark and the max_power of the bed_heater should be reduced.

-Kevin

**Comment by vampiredawn** [comment]
Yea it was...sorry I didn’t close it. Also turned out I had a wrong resistor setup on the program for some reason. They asked me to post it so I could post the log file with it.

On Nov 21, 2018, at 7:37 PM, KevinOConnor <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe this was resolved on IRC - the bed_heater should use PID instead of watermark and the max_power of the bed_heater should be reduced.

-Kevin
