### ISSUE TITLE
Flashing smoothieboard / MKS Sbase

### ISSUE THREAD

**Issue by nandinho84** [KevinOConnor/klipper#915]
Sorry for my ignorance, but I'm really noob about raspberry.... I'm trying to export the klipper.bin file to put in the SD card of my MKS Sbase board, but I don't know how to do it... Can someone help me?
I know that this is a begginner question, but I can't find it anywhere... If someone could tell me the commands to copy this file to a external drive.... maybe an usb stick or so...

**Comment by BlackStump** [comment]
if you are using Windows OS then WinSCP would be a easy option to grab your file off the pi

https://winscp.net/eng/download.php

**Comment by nandinho84** [comment]
Thanks a lot! It works really easy... One final question... Where are we supposed to put the config file? on the board SD card as the firmware?

**Comment by BlackStump** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md
the printer config is on the pi as per the install doc.

the firmware goes on the sdcard as per info here
https://github.com/KevinOConnor/klipper/blob/master/config/generic-smoothieboard.cfg#L4
