### ISSUE TITLE
Support LED strip control with M150 G-Code

### ISSUE THREAD

**Issue by gmag11** [KevinOConnor/klipper#917]
Hi,

I have an RGB LED strip (not Neopixels) connected to PWM pins on my board. I use M150 G-Code to control it.
Could it be possible to add support for this on Klipper.

Congrats for such a great development!

**Comment by KevinOConnor** [comment]
It should be possible to control the pwm pins using the "[output_pin]" config and the SET_PIN g-code command.  See the config/example-extras.cfg file for details.

If you wish to use M150 instead of SET_PIN, then it is possible to create a [gcode_macro M150] config to run SET_PIN on an M150 request.  Again, see the config/example-extras.cfg file for the details.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue as I think the original question was answered (use a gcode_macro).

-Kevin

**Comment by opit7** [comment]
Hello,

is there a way to control Neopixels/Ws2812?

-opit

**Comment by Zwaubel** [comment]
Hi @KevinOConnor,

could you elaborate on what it takes to implement support for Neopixels/WS28xx LEDs to be used as event driven pixels, for instance as an indicator for temperatures (nozzle and/or bed), print progress etc.?

Thanks!

**Comment by KevinOConnor** [comment]
The Neopixel (and similar) would require host python code to be written.  (The original question was about pwm controlled leds.)  If one wishes to automatically update the led (neopixel or other) whenever some printer status changs then host python code would also need to be written to do that.

-Kevin

**Comment by theopensourcerer** [comment]
I'm fairly sure you can do something like this using the Octoprint Enclosure plugin:

https://plugins.octoprint.org/plugins/enclosure/

"Use custom Gcode to control neopixel"

**Comment by rykiop** [comment]
I would much rather use the main control board to handle everything "printer" related. Having ws2812 LED integration for mcus for Klipper would be the bee's knees. It takes chopping up the timers or halting them all together for a few millis.

**Comment by KevinOConnor** [comment]
FYI, Klipper now has some basic support for Neopixels.

-Kevin
