### ISSUE TITLE
Synchronized axis - advice needed

### ISSUE THREAD

**Issue by Laczen** [KevinOConnor/klipper#919]
Hi,
I am trying to create a new host module for a stepper motor axis that is synchronized to the kinematics movement. I am trying to create this with minimal changes to the main klippy modules. I have created a module rotaxis.py that allows the definition of [rotaxis a]. In the module there is a class PrinterRotAxis that keeps track of its position (I don't want to extend the klipper position) and has its own ``check_move(self, move)``, ``calc_junction(self, prev_move, move)``, ``lookahead(self, moves, flush_count, lazy)`` and ``move(self, print_time, move)`` functions.

A move command would look like ``G1 X10Y10Z0A100`` where A would command the rotational axis. My idea was to extend the gcode processor to update the PrinterRotAxis position when a command containing ``A`` is given. But now I don't think this is going to work: to do the lookahead the position of the A axis needs to be tracked in the movement queue.

Now I am a bit stuck, what should I do, extend the position (and make major changes to the main modules, IMO not a good idea) or is there another way, by including a queue in the rotaxis module ?

**Comment by KevinOConnor** [comment]
It's difficult to provide any kind of advice, as I don't have a good understanding of how you want to use this "rotaxis" mechanism.

It sounds like you may want to implement a limited form of "six degrees of freedom".  Such support has come up a few times in the past - it would require some significant work - mostly in 3rd party software such as the slicer.  If I were to implement 6dof in Klipper, my first idea would be to extend the toolhead.py:Move:start_pos/end_pos variables to contain 7 fields and then update the kinematics accordingly.  It'd certainly take a bit of development work.

-Kevin

**Comment by Laczen** [comment]
Hi @KevinOConnor, thanks for the reply. I am working on it now exactly as you propose.

A different way could be to "separate" the kinematics queue from the other movement queues. The idea is the following: The toolhead kinematics keeps a queue for it's xyz movement, the extruder kinematics a queue for the extrusion position, a rotational axis for it's rotational position... Whenever a motion is requested it is placed on all queues (maybe as zero movement) with the same index, to keep them synchronized.

In such a solution it would be a lot easier to add modules for laser, rotational axis, ... even the extruder could be an extras module. Klipper could then be used for 3d printers, cnc machines, lasers, pick and place robots, ...

**Comment by KevinOConnor** [comment]
Indeed - there are a number of ways to tackle this issue.  It's also likely that the requirements of the robot could significantly impact the implementation.  For example, if the robot needs to be able to change toolhead rotation while simultaneously moving to a new XYZ location, then the kinematics basically needs to know about the rotation so it can plan those moves.  In contrast, if the toolhead rotation only changes rarely, then one could implement a SET_TOOLHEAD_ROTATION command that just performs the rotation and arranges for that rotation to remain static during subsequent XYZ moves.  The latter would be simpler to implement, but may not apply to the requirements of all robots.

-Kevin

**Comment by Laczen** [comment]
Hi @KevinOConnor, I have been thinking about how to implement this in the most general (and extendable) way. Here's my idea:

1. The toolhead class is the main class that controls all movements, but it has no movement queue. It keep a list of classes that need to be called to make a movement.
2. A Kinematics class implements the movement, this class has a property synched_kinematics and also a movement queue. A Kinematics class registers its synchronization with a "higher" class, or at the highest level the toolhead.

How would a typical 3D printer look then:
1. A cartesian kinematics class registers itself with the toolhead.
2. The extruder registers itself with the cartesian kinematics, and as a result is synchronized with the cartesian kinematics.

A robot with cartesian and rotational axis might look like:
1. A cartesian kinematics class registered to the toolhead
2. A rotational axis:
  - Registered to the toolhead: In this case the rotational axis would not be synchronized to the cartesian kinematics, both would do their movement as defined by the movement speed, independent of each other. (Remark: a G1 move with both cartesian and rotational movement is not really valid in this case)
  - Registered to the cartesian kinematics: in this case the rotational axis would be synchronized to the cartesian kinematics

As a result of the "synchronization" the "lower" classes would be allowed to limit the speed of the "higher" classes. A higher class also initiates movement planning and queue changes of lower classes. This would stop when a lower class has no synched_kinematics.

At the same time I would try to make the gcode interpreter simpler by removing global variables and having each of the toolhead kinematics subclasses to respond to M114, M119, ... requests.

This will take me some time to implement (my python knowledge is limited but your code will guide me). If you think it is a good idea, or I have overlooked something let me know.

Kind regards, Jehudi

**Comment by Laczen** [comment]
After reconsidering the above approach requires to much changes to klipper. Support for a laser or a simple pick and place (e.g. for placing smd components) can be done by re-purposing the E-axis. This requires only limited changes and is how I am going to proceed. I close this topic because it is answered.
