### ISSUE TITLE
M900 support

### ISSUE THREAD

**Issue by cbxbiker61** [KevinOConnor/klipper#92]
Marlin supports M900 for linear extruder advance.  The latest Slic3r Prusa 
Edition has integrated support for this in it's material configurations (set 
per material).

Do you think we could add support for M900 in Klipper and interpolate the M900 
command to your pressure advance algorithm?

**Comment by KenshiHH** [comment]
Klipper already got Pressure Advance
https://github.com/KevinOConnor/klipper/blob/master/docs/Pressure_Advance.md

**Comment by cbxbiker61** [comment]
Yes...of course, but it's "statically" defined for the printer.

M900 allows the slicer to specify the amount of advance based on the material....PLA is not the same as...ABS...PETG...

**Comment by KenshiHH** [comment]
from what i gatheres he doesn't like nonreadable commands like M900.

but a possible command like "pressure_advance: 0.1" would be nice.
with that you only need to modify your startscript in the slicer

**Comment by dragonnn** [comment]
I think we should make some generic solution with allows to set most of the config settings, somethink like:
SET CONFIG extruder pressure_advance=0.1
SET CONFIG extruder step_distance=0.004242
And so on. Even redefining the pins on fly could be somehow usefully in some scenarios (swapping multiple extrudes on live for example).

**Comment by cbxbiker61** [comment]
dragonn's idea sounds good.  The main reason why I suggested M900 is to be compatible with the way existing slicers set this.

We could have a klipper specific way as well as an M900 compatible way to make it work with existing slicer setups.  It would require just a bit of math to go from M900 to klipper specific.

**Comment by dragonnn** [comment]
When we have the SET CONFIG solution we could just setup some "alias" for M900. But they is small question, is Klipper pressure_advance value equal to Marlin pressure_advance?

**Comment by cbxbiker61** [comment]
Not straight across equal.  As per my initial post, we'd have to interpolate.

**Comment by KevinOConnor** [comment]
I'm going to close this issue as it doesn't appear that anyone is actively working to implement this feature.

**Comment by KevinOConnor** [comment]
It's possible to configure pressure advance using the SET_PRESSURE_ADVANCE extended g-code command.  See https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md for the details.

**Comment by NoxIX** [comment]
So you can't adjust settings on the fly in Klipper? This is akin to having to reflash marlin to change LA. Seems rather...archaic.

**Comment by theopensourcerer** [comment]
@NoxIX I have SET_PRESSURE_ADVANCE code in my slicer (it's different for PLA vs PETG) - so yes you can adjust this on-the-fly.

**Comment by flagoss** [comment]
Juste Add this to your Printer.cfg
`[gcode_macro M900] 
default_parameter_K: 0.3
gcode :
  SET_PRESSURE_ADVANCE ADVANCE={K}`
