### ISSUE TITLE
Prompt nozzle size check

### ISSUE THREAD

**Issue by tissak** [KevinOConnor/klipper#921]
Hi. I've been printing with klipper happily for some time now. I recently upgraded my nozzle size and without much thought spent only my time tweaking the slicer. During the print I repeatedly hit the safety that prevents pushing too much plastic (max_extrude_cross_section).  Took me a little while to figure out I'd forgotten the printer.cfg

I think the prompt in the terminal was good but possibly it could also hint to verify 'nozzle_diameter' also? This was absolutely my fault but seeing mention of attribute name nozzle would have immediately put me in the right direction for this one.

Thanks for your efforts.

**Comment by KevinOConnor** [comment]
Thanks for the feedback.  I'll note this and if it becomes a recurring issue I'll update the docs.

-Kevin
