### ISSUE TITLE
QUESTION/FEATURE REQUEST: There are any Bltouch / probe test gcode commands?

### ISSUE THREAD

**Issue by nandinho84** [KevinOConnor/klipper#929]
I was wondering if there are any gcodes to test the bltouch probe. 
Some examples of what I'm looking for:
Clear error state; 
deploy probe; 
retract probe 
test probe (one point)

I'm having some issues configuring bltouch and I can't figure out, because it start to blink when I issue the command SET_SERVO SERVO=bltouch ANGLE=10 and stays forever blinking... Then I must shutdown octoprint and cut the power to untrigger it.. (I know that this is a different question, and I'll open a new issue with my log file if I can't figure it out)

**Comment by BlackStump** [comment]
blinking red is alarm state if you issue
SET_SERVO SERVO=bltouch ANGLE=160 
it should reset
ANGLE =10 is push pin down
ANGLE = 90 is push pin up
ANGLE = 120 is self test
ANGLE = 160 is alarm release
ANGLE = 60 is M119 test mode

as per Antclabs Bltouch manual
https://www.antclabs.com/manual

**Comment by nandinho84** [comment]
thank you very much @BlackStump ! Your code helped me a lot.... I've run into other issues, but I've just opened other thread.
