### ISSUE TITLE
 Unable to parse move 'N9 G1 Z15 F{Z_TRAVEL_SPEED}*58'

### ISSUE THREAD

**Issue by mapa3m1** [KevinOConnor/klipper#939]
I have error  Unable to parse move 'N9 G1 Z15 F{Z_TRAVEL_SPEED}*58' 

This is starting gcode which i use before for marlin
; Default start code
G28 ; Home extruder
G1 Z15 F{Z_TRAVEL_SPEED}
M107 ; Turn off fan
G90 ; Absolute positioning
M82 ; Extruder in absolute mode
{IF_BED}M190 S{BED}
; Activate all used extruder
{IF_EXT0}M104 T0 S{TEMP0}
{IF_EXT1}M104 T1 S{TEMP1}
G92 E0 ; Reset extruder position
; Wait for all used extruders to reach temperature
{IF_EXT0}M109 T0 S{TEMP0}
{IF_EXT1}M109 T1 S{TEMP1}
;M420 S1
;nozzle wiping script
G0 X0 Y10 F9000 ; Go to front
G0 Z0.5 ; Drop to bed
G92 E0 ; zero the extruded length
G1 X40 E25 F500 ; Extrude 25mm of filament in a 4cm line
G92 E0 ; zero the extruded length
G1 E-1 F500 ; Retract a little
G1 X80 F4000 ; Quickly wipe away from the filament line
G1 Z0.3 ; Raise and begin printing.

What is wrong?

**Comment by AxMod3DPrint** [comment]
The issue is {Z_TRAVEL_SPEED}. Your slicer obviously didn't put the correct
speed in. This isn't an issue with Klipper, it's your slicer not changing
it's own macros.
