### ISSUE TITLE
ADC five buttons keyboard control

### ISSUE THREAD

**Issue by ZhenyaKa** [KevinOConnor/klipper#945]
How to configure 5 buttons keyboard?
Or it not realized?
[http://ipic.su/img/img7/fs/kiss_386kb.1543542783.png](url)

**Comment by KevinOConnor** [comment]
I suspect this is a similar request to #898 (and #609).  It requires development work in order to support buttons on an analog sensor.

-Kevin

**Comment by KevinOConnor** [comment]
I do not have any immediate plans to work on this.  Others have expressed interest in developing support, but I do not know if they are working on it.

-Kevin

**Comment by ZhenyaKa** [comment]
> I do not have any immediate plans to work on this. Others have expressed interest in developing support, but I do not know if they are working on it.
> 
> -Kevin

Can you add range reading for ADC input? ar12(min, max)
And it will be enouth.

**Comment by KevinOConnor** [comment]
Lets close this issue in favour of the existing issue #898 / # 609.
