### ISSUE TITLE
Update firmware

### ISSUE THREAD

**Issue by nandinho84** [KevinOConnor/klipper#947]
I was wondering what is needed to update klipper firmware. The firmware auto updates itself or it's necessary a fresh install on both raspberry pi and host?

**Comment by jakep82** [comment]
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-upgrade-to-the-latest-software

**Comment by nandinho84** [comment]
Thanks a lot! I was looking all the places and missed the FAQ'S...
