### ISSUE TITLE
M163 mixing filaments : support for rxtruder with multiple filament :  for clay printing

### ISSUE THREAD

**Issue by nuhwandah** [KevinOConnor/klipper#950]
I'm in the process of migrating from Marlin, and would like to use Klipper on my RepRap Clay printer that uses g-code M163 to divide extrusion between a ram and nozzle. I'm not too great with the tech side (it took me months to get my clay printer going in Marlin and I'd like to try using Kilpper.) I was wondering if anyone would be interested in the same thing ?

**Comment by joris57** [comment]
+1 for mixing extruder

**Comment by kakou-fr** [comment]
+1 for mixing extruder

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive as it doesn't look like it is currently being worked on.

-Kevin

**Comment by bguse** [comment]
Hi Kevin, what do you need to get forward on this feature? :-)

**Comment by hevilp** [comment]
Hi @KevinOConnor ,
is there any movement here?

Thanks

**Comment by KevinOConnor** [comment]
An interested developer would need to implement and submit this.  It is not something that I personally will have time to work on in the near future.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, with the latest code (including #5210 ) it may be possible to configure extruder_stepper motors that can push multiple filament spools simultaneously.

-Kevin
