### ISSUE TITLE
How to install klipper branch

### ISSUE THREAD

**Issue by banolka** [KevinOConnor/klipper#960]
Hi I was hoping to try BL-touch optimized branch. How to update klipper to different branch?

**Comment by AxMod3DPrint** [comment]
See #955 - the changes have been merged..

**Comment by KevinOConnor** [comment]
It looks like this was answered.  For future reference, the general approach is to use the commands listed at:  https://github.com/KevinOConnor/klipper/issues/955#issuecomment-446327773

-Kevin
