### ISSUE TITLE
I2C support on Arduino Due

### ISSUE THREAD

**Issue by wesk-ms** [KevinOConnor/klipper#962]
Hello,

I'm trying to configure Klipper to use an I2C oled display (ssd1306) connected to an Arduino Due MC.  In looking at the code, it doesn't appear that I2C support is enabled for the SAM3X8E platform.  Is that correct?  Just thought I'd ask before spending a lot of time reconfiguring mt printer.

Thanks!

**Comment by KevinOConnor** [comment]
You are correct - the i2c support is not currently implemented on the sam3x8e processor.  It is believed that the src/sam4e8e/i2c.c code could work with the sam3x8e with some minor changes - but no one has done this yet.

-Kevin

**Comment by wesk-ms** [comment]
Thanks for the verification.  If I get a chance to port that code over, I'll reach out and let you know.

Thanks again!

**Comment by KevinOConnor** [comment]
FYI - the code at PR #1055 adds i2c support for the sam3x8c.  Though, you'll probably also need the code in PR #1048.

-Kevin

**Comment by wesk-ms** [comment]
Thanks Kevin!  Appreciate the update.


________________________________

**Comment by KevinOConnor** [comment]
FYI - both of the PRs listed above have been merged into the master branch.  So, i2c support should now be working on the Due.

-Kevin
