### ISSUE TITLE
Bed Mesh Levelling won't take negative values in "min_point" 

### ISSUE THREAD

**Issue by WheresWes** [KevinOConnor/klipper#968]
So I have been enjoying tinkering with the Klipper set up and moved now into. Some of the move advanced features.  
I have a modified cr-10s with an x axis that allows the nozzle to travel off the bed to x=-16 (allows me me to mount a wire brush for auto nozzle cleaning).  My Z probe is offset from the nozzle by 37mm (x positive direction). 
I want to Z probe with as low an x value as possible.  Setting 0 for x in the min point works fine but of course this means the Z probe is actually probing at x=37. A little counter intuitive but that is besides the point.  If I set any negative value for the x min point (to print the Z probe a bit closer to the edge of the build platform) klipper packs a sad and refuses to communicate, print or show the display on the control box.  Was a bit of a head scratcher as for some reason I don't have a /tmp/ folder or log file on the pi. 
Not a common issue I'm sure. 
Regards W

**Comment by KevinOConnor** [comment]
Without a log there is little we can do, so I'm closing this issue.
