### ISSUE TITLE
Why any error makes octoprint disconect?

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#971]
First of all I want to thank you Kevin and all other developers for this excellent job.
And after saying all this good things,

1 - Is it possible to avoid that errors like syntax errors, and others, makes octoprint disconnect?
     You should only show in terminal the errors, this way we don't have to repeat connection and lose all changes made.

**Comment by jakep82** [comment]
Please take a closer look at the installation instructions.  Specifically 

> Enter the Settings tab again and under "Serial Connection" change the "Serial Port" setting to "/tmp/printer". Navigate to the "Behavior" sub-tab and select the "Cancel any ongoing prints but stay connected to the printer" option. Click "Save".

https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md

**Comment by rmcbc** [comment]
Great. Thank you,
