### ISSUE TITLE
Some MCU commands are not documented

### ISSUE THREAD

**Issue by fritzw** [KevinOConnor/klipper#973]
There is no documentation for the `button` family of commands like `config_buttons` or `buttons_query` in `/docs/MCU_Commands.md`.

**Comment by KevinOConnor** [comment]
The MCU_Commands document is not intended to be "an authoritative reference for these commands, nor is it an exclusive list of all available commands".  However, if someone wishes to add additional documentation that would be welcome.

-Kevin
