### ISSUE TITLE
Ender3, Bltouch(clone). Not working, strange trigger behaviour.

### ISSUE THREAD

**Issue by grizzlybearrr** [KevinOConnor/klipper#976]
Hello. I try to config Ender3 with Bltouch clone. System normally works on Marlin.
For checking signals i connect oscilloscope.  In default case a have no any signals.
Then i connect default ender3 endstop parallely with bltouch. If i press and fix endstop, oscilloscope start to show signals (for example - on startup or bltouch self-test).

I try to make tests from this issue:
https://github.com/KevinOConnor/klipper/issues/955#issuecomment-444147484
1)pin_move_time  200-300 : 
sensor not fix after trigger, QUERY_PROBE take 'open' status, oscilloscope show 5v peak duration 5ms/
2)pin_move_time  315+ : 
sensor fix after trigger, QUERY_PROBE take 'open' status, oscilloscope show nothing

simetimes i get QUERY_PROBE get 'TRIGGERED' status, but i can not already stability repeat this.

my log file
[klippy.log](https://github.com/KevinOConnor/klipper/files/2659200/klippy.log)

my config
[klipper_ender3_bltouch_pin27_1.txt](https://github.com/KevinOConnor/klipper/files/2659204/klipper_ender3_bltouch_pin27_1.txt)

blotouch z-min signal
![2018-12-08_023604](https://user-images.githubusercontent.com/29143141/49679420-3375cb00-fa9c-11e8-9030-cb79c536472d.png)

**Comment by KevinOConnor** [comment]
Do you have a clone or an original bltouch?  Can you run the script described at: https://github.com/KevinOConnor/klipper/issues/955#issuecomment-445550111 and forward the log?

Lets move this discussion into the existing issue #955.

-Kevin
