### ISSUE TITLE
Error: Failed to home x: Timeout during endstop homing

### ISSUE THREAD

**Issue by Asygan** [KevinOConnor/klipper#978]
Hello, I am new to the world of 3d printing and I am currently building a corexy hypercube.
For the electronic part, I use a re-arm and a ramps 1.6 with TMC 2208.
I am currently testing the electronics out of the machine, which is not finished assembling.
Only motors and limit switches are connected.

So I installed Octopi and Klipper, it works, the commands staus, QUERY_ENDSTOPS, STEPPER_BUZZ are ok.
I have commented everything I do not want to use or have not connected in the config files.
When the connection set established, I can not make homing, the engines turns 5 scondes and I have an error: Error: Failed to home x: Timeout during endstop homing
And if I activate the end stop x during these few seconds I have another error: Error: Endstop x still triggered after retract

Do you have an idea of the problem?

I attach the two error files.

Thank you and sorry for english!
[klippy1.log](https://github.com/KevinOConnor/klipper/files/2660394/klippy1.log)
[klippy2.log](https://github.com/KevinOConnor/klipper/files/2660395/klippy2.log)

**Comment by KevinOConnor** [comment]
Nothing in the log looks unusual.  Double check that the step_distance and position_min/max settings are correct.  Also, you may want to reduce your homing speed (eg, use the default of 5mm/s) during testing.

Separately, it is not recommended to use the tmc2208 stepper motor drivers in standalone mode (due to issue #196).  They do seem to work well if you wire up the PDN-UART pin to the micro-controller and do runtime configuration of them.

-Kevin

**Comment by Asygan** [comment]
Hello Kevin, and thank you for your answer.

I modified the homing speed, I set it to 5mm / s, and I set step_distance to .00390625. It's much better.

The problem I think now is that I activate my switch manually because my machine is not fully assembled, and I think it is impossible to stop in the right place?

Is there any way that the motor stops directly when the switch is triggered?

If I understand correctly, it is imperative to start with a homing before being able to move the engine manually?

For the UART mode, I'm going to look at this, I'm going slowly, I'm just starting and I tell you that everything is not obvious to me :)

thanks again

**Comment by KevinOConnor** [comment]
It looks like the original question was answered so I'm going to close this issue.  There's some further information on overriding the homing checks at: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#why-cant-i-move-the-stepper-before-homing-the-printer
