### ISSUE TITLE
Strange problem with power off / power on

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#980]
My system:
- Arduino mega + RAMPS 1.4 (USB don't power up arduino, the cable don't have +5V, I remove it)
- Raspberry pi 2
- Power sypply to arduino + ramps controlled by relay using GPIO in raspberry

Problem: 
 - System is all ok, arduino mega powered and connected to Octoprint.
 - In Octoprint shutdown arduino + ramps power
 - In Octoprint power up arduino + ramps
 - Serial connect to klipper
 - Printer says not ready and LCD display doesn't show information.
 - In terminal do FIRMWARE_RESET and no printer ready.
 - Change in [mcu] restart_method: to arduino, command and rpi_usb none solves the problem.

Solution:
 - Take the USB cable from Raspberry to Arduino and put it again, then the printer became ready.

Can some one explain to me what I'm doing wrong?

**Comment by BlackStump** [comment]
without a log file there is not much info to go on.
but as a guess your pi is not finding the usb, do you have usb by id if not that might be the solution
https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#wheres-my-serial-port

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by rmcbc** [comment]
Solve using "/dev/serial/by-id/...."
Thanks.
