### ISSUE TITLE
Homing suddenly doesn't work anymore (Safe Z homing)

### ISSUE THREAD

**Issue by radry** [KevinOConnor/klipper#981]
I sucessfully used klipper before with the same config, then didn't use my printer for several months.
Now homing doesn't work anymore when I click "home" in octoprint webinterface.

It homes X and Y but not Z with following error:

```
Send: G91
Recv: ok
Send: G28 X0 Y0
Send: G90
Recv: !! Must home axis first: 100.000 130.000 -0.362 [0.000]
Recv: !! Must home axis first: 100.000 130.000 -0.362 [0.000]
```

Homing script in config:

```
[homing_override]
gcode:

    G28 X0 Y0            ; home X and Y
    G0  X100 Y130       ; move to safe homing spot
    G28 Z0               ; home Z
    G0  Z10              ; clear homing button
```

What is wrong or how do I do a "safe homing" of Z?

**Comment by BlackStump** [comment]
suggestion is to try G28 in the Octoprint terminal, and as always include the log.

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by radry** [comment]
Here you go, exact same result.

G28 from terminal and 

```
!! Must home axis first: 100.000 130.000 -0.362 [0.000]
!! Must home axis first: 100.000 130.000 -0.362 [0.000]
```

[klippy.log](https://github.com/KevinOConnor/klipper/files/2664710/klippy.log)

**Comment by jakep82** [comment]
Try adding the following to your stepper_z1 section:

> position_min: -1

**Comment by jakep82** [comment]
Actually, looking closer it seems you're missing something in your homing override section.  You need the line below.

> set_position_z: 5

**Comment by KevinOConnor** [comment]
It looks like this question was answered, so I'm closing this issue.
