### ISSUE TITLE
No bed tilt compensation

### ISSUE THREAD

**Issue by reefwarrior** [KevinOConnor/klipper#985]
Hi

I have not included the log file; as nothing significant is indicate.

The last couple of lines:

Stats 208655.7: gcodein=1736 mcu: mcu_awake=0.009 mcu_task_avg=0.000096 mcu_task_stddev=0.000080 bytes_write=35804 bytes_read=73241 bytes_retransmit=9 bytes_invalid=0 send_seq=2479 receive_seq=2479 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000092 heater_bed: target=0 temp=39.8 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=51.2 pwm=0.000
Stats 208656.7: gcodein=1741 mcu: mcu_awake=0.009 mcu_task_avg=0.000096 mcu_task_stddev=0.000080 bytes_write=35810 bytes_read=73341 bytes_retransmit=9 bytes_invalid=0 send_seq=2480 receive_seq=2480 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000092 heater_bed: target=0 temp=39.6 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=50.4 pwm=0.000
Stats 208657.7: gcodein=1741 mcu: mcu_awake=0.010 mcu_task_avg=0.000099 mcu_task_stddev=0.000081 bytes_write=35816 bytes_read=73470 bytes_retransmit=9 bytes_invalid=0 send_seq=2481 receive_seq=2481 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000091 heater_bed: target=0 temp=39.2 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=50.4 pwm=0.000
Stats 208658.7: gcodein=1741 mcu: mcu_awake=0.010 mcu_task_avg=0.000099 mcu_task_stddev=0.000081 bytes_write=35822 bytes_read=73584 bytes_retransmit=9 bytes_invalid=0 send_seq=2482 receive_seq=2482 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000092 heater_bed: target=0 temp=39.6 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=50.4 pwm=0.000
Stats 208659.7: gcodein=1741 mcu: mcu_awake=0.010 mcu_task_avg=0.000099 mcu_task_stddev=0.000081 bytes_write=35847 bytes_read=73694 bytes_retransmit=9 bytes_invalid=0 send_seq=2485 receive_seq=2485 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000092 heater_bed: target=0 temp=39.9 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=50.1 pwm=0.000
Stats 208661.7: gcodein=1746 mcu: mcu_awake=0.010 mcu_task_avg=0.000099 mcu_task_stddev=0.000081 bytes_write=35880 bytes_read=73932 bytes_retransmit=9 bytes_invalid=0 send_seq=2489 receive_seq=2489 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=16000092 heater_bed: target=0 temp=39.8 pwm=0.000 print_time=1047.334 buffer_time=0.000 print_stall=1 extruder: target=0 temp=50.4 pwm=0.000

Anyway, my issue.

I have done a bed_tilt_calibrate. Values were given, I have added it to the config too. Nevertheless; it seems klippy is not compensating for the bed tilt - I don't see the Z axis moving at all. 

Herewith the configuration file section as applicable:

[bed_tilt]
speed: 50
horizontal_move_z: 10
points:
	230, 232 
	230, 127
	230, 27
	152, 27
	152, 127
	152, 232
	52, 232
	52, 127
	52, 27
samples: 3
x_adjust: 0.006283
y_adjust: -0.001108 
z_adjust: -1.458722

Any suggestions?

Tinus

**Comment by reefwarrior** [comment]
Issue partially sorted....

**Comment by reefwarrior** [comment]
Seems it is compensating, but not enough. I can see the Z axis moving as the carriage moves along X and Y, but the offset from the bed is too close on one spot and too far on the other....

**Comment by KevinOConnor** [comment]
In order to assist, you need to attach the Klipper log file from the event.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by KevinOConnor** [comment]
Any further update on this?  If not, I'm inclined to close this issue.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue - please open a new one if you run into further problems.
