### ISSUE TITLE
Not a issue but a thanks. I'm amazed with all this work.

### ISSUE THREAD

**Issue by rmcbc** [KevinOConnor/klipper#988]
To all developers: You should be proud because you created and amazing system.

1 - Klippy (excellent design and very nice to use), thanks to Kevin O'Connor
2 - Firmware (seems to be efficient and works ok), thanks to Kevin O'Connor
3 - OctoKlipper (a nice interface for octoprint to klipper), thanks to Martin Muehlhaeuser 
4 - Octoprint (a fantastic interface and printer controller), thanks to Gina Häußge

With all the parts we have available it became a perfect system that works like a charm.
I'm amazed with all this.
I'm a developer and I'm going to try to help where you need, because finally found a system that works very well, in my opinion better or with a much more potential to grow than Marlin.
Thanks for this good work.

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this issue, but thanks again.

-Kevin
