### ISSUE TITLE
Can't make OctotPrint printer ready

### ISSUE THREAD

**Issue by LeonKnook** [KevinOConnor/klipper#990]
Did the hole procedure and are almost there, but don't get printer ready in octoprint.
Commented out al the heaters to avoid there is a thermistor on the wrong pin.

Send: status
Recv: // Klipper state: Ready 

[klippy.log](https://github.com/KevinOConnor/klipper/files/2669353/klippy.log)

Please some help

kind regards,
Leon

**Comment by jakep82** [comment]
Not sure what issue you're seeing.  When sending status the printer is returning ready.  That would indicate it's connected and ready to print.  The log looks normal.

**Comment by LeonKnook** [comment]
Good to know but should there be the message ' printer ready'  en not ' klipper state ready' ?
did the whole procedure again, flashing the firmware and all that.

Send: firmware_restart
Recv: ok
Recv: // Klipper state: Disconnect
Recv: // Klipper state: Ready

Thank you for your effort.

**Comment by jakep82** [comment]
That message is exactly what you want to see. Klipper runs the printer.  The printer is ready.

**Comment by LeonKnook** [comment]
Must be an issue with the radds board maybe, arduino due is brand new. Home all does not work, no movement. Endstops are in correct logic.

**Comment by jakep82** [comment]
Have you tried stepper_buzz to see if the motors work?  Do your heaters work?

https://github.com/KevinOConnor/klipper/blob/master/docs/Config_checks.md

**Comment by LeonKnook** [comment]
Thank very much. I will do a complete walk true on that document and come back.

**Comment by Hywelmartin** [comment]
is it a clone Due?   #844

**Comment by LeonKnook** [comment]
Yes it is a clone Due. And I flashed wirt ttyACM0 which is there in the config.cfg

**Comment by LeonKnook** [comment]
That document was perfect! It solved all my problems. Not yet printed but everything is working properly now.
Thank very much for pointing me in the right direction.
Kind regards,
Leon

**Comment by KevinOConnor** [comment]
It sounds like this issue was resolved, so I'm closing it.
