### ISSUE TITLE
[minor] Thermistor.py: float division by zero

### ISSUE THREAD

**Issue by TheGuv** [KevinOConnor/klipper#995]
Dear Kevin and devs,

Firstly, a big thank you for all the work. I'm not using Klipper in a 3D printer, but rather a multipurpose CNC machine [https://www.v1engineering.com/wp-content/uploads/2018/10/renb1-1.jpg]. I was using Marlin but because I desired some (light) customisation which I was finding awkward I switched to Klipper with no regrets. As a bonus, on my Mega2560+RAMPS_1.4 fast-moves are a lot faster.

As part of my customisation I would like a plain temperature device - one that can have the temperature displayed on the LCD but without any associated heater or cooling fan pin. I don't think there is anything so I just used the heater_bed device and allocated an unused pin for the heater. 

I set min_temp to -999 and max_temp to 999.
This resulted in "Error: Option 'min_temp' in section 'heater_bed' must have minimum of -273.15"

OK, reset min_temp to -273.15 as suggested: "ZeroDivisionError: float division by zero"

Not critical, I was trying to avoid a shutdown when the thermistor is unplugged which reads -107C. I can just set min_temp to -150 instead.

[bug.log](https://github.com/KevinOConnor/klipper/files/2676610/bug.log)

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 7fe14f05).

-Kevin
