### ISSUE TITLE
How can I get printing status in the /klipper/klippy/chelper/kin_cartesian.c file?

### ISSUE THREAD

**Issue by luxiangnk** [KevinOConnor/klipper#999]
Hi,

I want to add my own algorithm, which will filter the trajectory, in the /klipper/klippy/chelper/kin_cartesian.c. 

The problem is, I only want to apply the algorithm during the printing (print the gcode in Gcode files) not during the homing or during changing the position with keyboard. Is there any FLAG (it represents the print job is start), which I can transfer from the python code into this file? Thanks so much.

**Comment by KevinOConnor** [comment]
The movement code doesn't currently make a distinction between homing and non-homing moves.  So, you'd have to change the python code to track that and forward the information on.

-Kevin

**Comment by luxiangnk** [comment]
> The movement code doesn't currently make a distinction between homing and non-homing moves. So, you'd have to change the python code to track that and forward the information on.
> 
> -Kevin

Hi Kevin. I see and thanks for your reply! I wonder if the /klipper/klippy/chelper/kin_cartesian.c is the best place for me to apply a filter? I need collect some trajectory points (i.e. 100 points) in advance, then filter them and send them. So I have 100 steps delay , and some problem were cause by this delay when compute the next stepper time.

Could you give me some hints that where is the best file or code for me to apply this filter? Thanks so much！

**Comment by KevinOConnor** [comment]
I'm going to close this as I think the original question was answered.

-Kevin
